### ISSUE TITLE
suited for tensorflow-gpu 2.2.0

### ISSUE THREAD

**Issue by DemonDamon** [tensorflow/models#10008]
now installed tensorflow-gpu==2.2.0 in docker container, with cuda 10.2, driver 440. and i don't want to change docker env. tf-models-official==2.2.0, and tensorflow==2.2.0, but git clone from the latest models, and arouse error like below:

Traceback (most recent call last):
  File "./models-master/research/object_detection/model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "/root/anaconda3/envs/py36-tf2/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 31, in <module>
    from object_detection import model_lib
  File "/root/anaconda3/envs/py36-tf2/lib/python3.6/site-packages/object_detection/model_lib.py", line 34, in <module>
    from object_detection.builders import optimizer_builder
  File "/root/anaconda3/envs/py36-tf2/lib/python3.6/site-packages/object_detection/builders/optimizer_builder.py", line 25, in <module>
    from official.modeling.optimization import ema_optimizer
ModuleNotFoundError: No module named 'official.modeling.optimization'

i just want to know, how to make it work

**Comment by DemonDamon** [comment]
solved

**Comment by geometrikal** [comment]
@DemonDamon What was the solution, I'm running into the same problem... With previous installs it worked fine...
