### ISSUE TITLE
failed to run train.py (im using python 3.6.9 & tensorflow 2.5)

### ISSUE THREAD

**Issue by danielivan09** [tensorflow/models#10013]
failed to run train.py (im using python 3.6.9 & tensorflow 2.5)

i got this
Traceback (most recent call last):
  File "c:\tensorflow1\models\research\object_detection\train.py", line 53, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 36, in <module>
    from object_detection.meta_architectures import context_rcnn_meta_arch
  File "C:\tensorflow1\models\research\object_detection\meta_architectures\context_rcnn_meta_arch.py", line 35, in <module>
    from object_detection.protos import faster_rcnn_pb2
  File "C:\tensorflow1\models\research\object_detection\protos\faster_rcnn_pb2.py", line 21, in <module>
    from object_detection.protos import fpn_pb2 as object__detection_dot_protos_dot_fpn__pb2
ImportError: cannot import name 'fpn_pb2' from 'object_detection.protos' (C:\tensorflow1\models\research\object_detection\protos\__init__.py)

should i run the model_main? please help me...

**Comment by jvishnuvardhan** [comment]
@danielivan09 Sorry for the late response. Can you please explain steps followed before noticing this error or share a simple standalone code to reproduce the error. Thanks!

**Comment by PelinSuK** [comment]
did you find any solution i have exactly the same problem
