### ISSUE TITLE
Maskrcnn Internal:  Missing 0-th output from {{node while/body/_1/mask_rcnn_model/res_net/conv2d/Conv2D}}

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/models#10011]
I was trying maskrcnn in beta directory, but was unable to get the training started with both "resnet" and "spinenet". This is my config:
```
runtime:
  distribution_strategy: 'one_device' #'mirrored'
  num_gpus: 1
task:
  model:
    num_classes: 91
    input_size: [640, 640, 3] 

  init_checkpoint: ''
  annotation_file: ''

  train_data:
    input_path: '/home/deploy/ved/coco/tfrecord/train/*.tfrecord' 
    global_batch_size: 1
    file_type: 'tfrecord'

  validation_data:
    input_path: '/home/deploy/ved/coco/tfrecord/val/*.tfrecord' 
    global_batch_size: 1
```
I'm passing `maskrcnn_resnetfpn_coco` as the `experiment` flag while training with ~/models/official/vision/beta/train.py. I'm getting following error:
```
Traceback (most recent call last):
  File "/home/deploy/models/official/vision/beta/train.py", line 69, in <module>
    app.run(main)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/deploy/models/official/vision/beta/train.py", line 63, in main
    model_dir=model_dir)
  File "/home/deploy/models/official/core/train_lib.py", line 110, in run_experiment
    eval_interval=params.trainer.validation_interval)
  File "/home/deploy/models/orbit/controller.py", line 303, in train_and_evaluate
    self.train(steps=num_steps, checkpoint_at_completion=False)
  File "/home/deploy/models/orbit/controller.py", line 215, in train
    self._train_n_steps(num_steps)
  File "/home/deploy/models/orbit/controller.py", line 410, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/home/deploy/models/orbit/standard_runner.py", line 144, in train
    self._train_loop_fn(self._train_iter, num_steps)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  Missing 0-th output from {{node while/body/_1/mask_rcnn_model/res_net/conv2d/Conv2D}}
	 [[while/body/_1/gradient_tape/mask_rcnn_model/fpn/conv2d_8/Conv2D/Conv2DBackpropFilter/_2320]]
  (1) Internal:  Missing 0-th output from {{node while/body/_1/mask_rcnn_model/res_net/conv2d/Conv2D}}
0 successful operations.
0 derived errors ignored. [Op:__inference_loop_fn_57848]

Function call stack:
loop_fn -> loop_fn
```

I'm getting error even when I try to change the `experiment` flag to `maskrcnn_spinenet_coco`. This is the error:
```
Traceback (most recent call last):
  File "/home/deploy/models/official/vision/beta/train.py", line 69, in <module>
    app.run(main)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/deploy/models/official/vision/beta/train.py", line 63, in main
    model_dir=model_dir)
  File "/home/deploy/models/official/core/train_lib.py", line 110, in run_experiment
    eval_interval=params.trainer.validation_interval)
  File "/home/deploy/models/orbit/controller.py", line 303, in train_and_evaluate
    self.train(steps=num_steps, checkpoint_at_completion=False)
  File "/home/deploy/models/orbit/controller.py", line 215, in train
    self._train_n_steps(num_steps)
  File "/home/deploy/models/orbit/controller.py", line 410, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/home/deploy/models/orbit/standard_runner.py", line 144, in train
    self._train_loop_fn(self._train_iter, num_steps)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  Missing 0-th output from {{node while/body/_1/mask_rcnn_model/spine_net/conv2d/Conv2D}}
	 [[while/body/_1/mask_rcnn_model/spine_net/conv2d_18/Conv2D/_502]]
  (1) Internal:  Missing 0-th output from {{node while/body/_1/mask_rcnn_model/spine_net/conv2d/Conv2D}}
0 successful operations.
0 derived errors ignored. [Op:__inference_loop_fn_94378]

Function call stack:
loop_fn -> loop_fn
```

Tensorflow-gpu version used: 2.5.0

**Comment by arashwan** [comment]
Can you try batch size of 2?

**Comment by anshkumar** [comment]
I tried with batch size of 2, but got same error.

For evaluation, I changed the code to use record file. Since, images are of different sizes, I first resize the mask to same size, so that batches can be made. During evaluation, I resize these mask back the image size, so that MAP can be calculated. (PR: [9987](https://github.com/tensorflow/models/pull/9987))

**Comment by itai12312** [comment]
Is there any update? I have a similar issue?
Config:
runtime:
[log.txt](https://github.com/tensorflow/models/files/6707384/log.txt)

  num_gpus: 1
  distribution_strategy: 'one_device' # 'tpu'
  mixed_precision_dtype: 'bfloat16' # 'float32'
trainer:
  optimizer_config:
    learning_rate:
      stepwise:
        boundaries: [26334, 30954]
        name: PiecewiseConstantDecay
        values: [0.01, 0.001, 0.0001]
      type: stepwise
    optimizer:
      type: sgd
  train_steps: 1
task:
  init_checkpoint: '
  annotation_file: ''
  losses:
    l2_weight_decay: 0.0001
  model:
    num_classes: 91
    max_level: 7
    min_level: 3
    input_size: [640, 640, 3] # [640, 640, 3]
    norm_activation:
      activation: relu
      norm_epsilon: 0.001
      norm_momentum: 0.99
      use_sync_bn: true
  train_data:
    tfds_name: 'coco/2017'
    tfds_split: 'train'
    drop_remainder: true
    dtype: float # bfloat16
    global_batch_size: 1 # 256
    input_path: ''
    is_training: true
    shuffle_buffer_size: 1000
    deterministic: True
    seed: 0
  validation_data:
    tfds_name: 'coco/2017'
    tfds_split: 'validation'
    drop_remainder: true
    dtype: bfloat16
    global_batch_size: 2 # 8
    input_path: ''
    is_training: false
    deterministic: True
    seed: 0

**Comment by arashwan** [comment]
@itai12312  can you change global_batch_size for train_data to 2, and let me know if you are still having the same error?

**Comment by itai12312** [comment]
Same error:
    return graph_function._call_flat(
  File "/home/izeitak/miniconda3/envs/env2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/izeitak/miniconda3/envs/env2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/izeitak/miniconda3/envs/env2/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  Missing 0-th output from {{node while/body/_1/retina_net_model/res_net/conv2d/Conv2D}}
  (1) Internal:  Missing 0-th output from {{node while/body/_1/retina_net_model/res_net/conv2d/Conv2D}}
	 [[while/body/_1/retina_net_model/res_net/bottleneck_block_4/activation_1/Relu/_184]]
0 successful operations.
0 derived errors ignored. [Op:__inference_loop_fn_50403]

Function call stack:
loop_fn -> loop_fn

**Comment by itai12312** [comment]
@arashwan Do you have any idea how this error can be fixed?

**Comment by arashwan** [comment]
Last thing to try before trying to debug on my side, can you try running with 'mirrored' strategy instead one device?

**Comment by thewq** [comment]
@itai12312 @anshkumar Is there any update? I also meet the similar issue

**Comment by itai12312** [comment]
I think it also happened with mirrored, but I don't remember, I moved on to something else.
