### ISSUE TITLE
Docker fails installation test

### ISSUE THREAD

**Issue by Tob-iee** [tensorflow/models#10038]
After i'm done with the docker image installation, I then run the container and try running the test for the api and i get this error.

_Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 21, in <module>
    import tensorflow.compat.v1 as tf
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 444, in <module>
    _ll.load_library(_main_dir)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
_

please is there a solution for this error.

**Comment by eriosta** [comment]
Try this:

`pip install -U tensorflow==2.3.0`

see broken's response on [here](https://github.com/tensorflow/text/issues/385)

**Comment by Tob-iee** [comment]
It didn't resolve the issue, of you have an idea what the main issue might be please that would b more helpful

**Comment by hiwaveSupport** [comment]
I am seeing the same issue with the docker image. I also tried the pip install -U tensorflow==2.3.0, which gets over this issue but then creates a new one which seems to be related to base tf2 files installed. Any ideas how this can be resolved?
