### ISSUE TITLE
RuntimeError: tf.placeholder() is not compatible with eager execution .

### ISSUE THREAD

**Issue by Priyabrata409** [tensorflow/models#10031]
# Prerequisites
I am using Tensorflow 2.5  in python 3.8. 
I am trying to get the frozen_grpah.pb file by running following command
`!python Tensorflow\models\research\object_detection\export_inference_graph.py  --input_type=image_tensor --pipeline_config_path=Tensorflow\workspace\models\my_ssd_mobnet\pipeline.config --trained_checkpoint_prefix=Tensorflow\workspace\models\my_ssd_mobnet\ckpt-11.data-00000-of-00001 --output_directory=Tensorflow\workspace\models\my_ssd_mobnet\export  `

I got the following issue
Traceback (most recent call last):
  File "Tensorflow\models\research\object_detection\export_inference_graph.py", line 206, in <module>
    tf.app.run()
  File "C:\Users\priyabrata\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\priyabrata\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\priyabrata\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "Tensorflow\models\research\object_detection\export_inference_graph.py", line 194, in main
    exporter.export_inference_graph(
  File "C:\Users\priyabrata\anaconda3\envs\tensorflow_gpu\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\exporter.py", line 611, in export_inference_graph
    _export_inference_graph(
  File "C:\Users\priyabrata\anaconda3\envs\tensorflow_gpu\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\exporter.py", line 503, in _export_inference_graph
    outputs, placeholder_tensor_dict = build_detection_graph(
  File "C:\Users\priyabrata\anaconda3\envs\tensorflow_gpu\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\exporter.py", line 457, in build_detection_graph
    placeholder_tensor, input_tensors = input_placeholder_fn_map[input_type](
  File "C:\Users\priyabrata\anaconda3\envs\tensorflow_gpu\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\exporter.py", line 186, in _image_tensor_input_placeholder
    input_tensor = tf.placeholder(
  File "C:\Users\priyabrata\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\array_ops.py", line 3268, in placeholder
    raise RuntimeError("tf.placeholder() is not compatible with "
RuntimeError: tf.placeholder() is not compatible with eager execution.

I also checked the exporter.py ,but couldn't fix the issue

**Comment by sahasraa** [comment]
@Priyabrata409 did you fix the above issue? please help if you did, i am facing the same issue

python export_inference_graph.py --input_type=image_tensor --pipeline_config_path=/home/sahasra/jukshio/object_det_rec/exported_models_trial1_gpu_py38_models_effdetdo_aug21_gpu/pipeline.config --trained_checkpoint_prefix=/home/sahasra/jukshio/object_det_rec/exported_models_trial1_gpu_py38_models_effdetdo_aug21_gpu/checkpoint/ckpt-0.data-00000-of-00001 --output_directory=/home/sahasra/jukshio/object_det_rec/exported_models_trial1_gpu_py38_models_effdetdo_aug21_gpu/export/
2021-09-02 12:43:38.083801: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-02 12:43:38.083829: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-09-02 12:43:39.620722: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-09-02 12:43:39.620748: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-09-02 12:43:39.620882: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sahasra-Latitude-3510): /proc/driver/nvidia/version does not exist
2021-09-02 12:43:39.621059: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0902 12:43:39.630269 140218740490624 ssd_efficientnet_bifpn_feature_extractor.py:142] EfficientDet EfficientNet backbone version: efficientnet-b0
I0902 12:43:39.630398 140218740490624 ssd_efficientnet_bifpn_feature_extractor.py:144] EfficientDet BiFPN num filters: 64
I0902 12:43:39.630460 140218740490624 ssd_efficientnet_bifpn_feature_extractor.py:145] EfficientDet BiFPN num iterations: 3
I0902 12:43:39.633752 140218740490624 efficientnet_model.py:147] round_filter input=32 output=32
I0902 12:43:39.656783 140218740490624 efficientnet_model.py:147] round_filter input=32 output=32
I0902 12:43:39.656892 140218740490624 efficientnet_model.py:147] round_filter input=16 output=16
I0902 12:43:39.704717 140218740490624 efficientnet_model.py:147] round_filter input=16 output=16
I0902 12:43:39.704834 140218740490624 efficientnet_model.py:147] round_filter input=24 output=24
I0902 12:43:39.823941 140218740490624 efficientnet_model.py:147] round_filter input=24 output=24
I0902 12:43:39.824063 140218740490624 efficientnet_model.py:147] round_filter input=40 output=40
I0902 12:43:40.010115 140218740490624 efficientnet_model.py:147] round_filter input=40 output=40
I0902 12:43:40.010272 140218740490624 efficientnet_model.py:147] round_filter input=80 output=80
I0902 12:43:40.182394 140218740490624 efficientnet_model.py:147] round_filter input=80 output=80
I0902 12:43:40.182524 140218740490624 efficientnet_model.py:147] round_filter input=112 output=112
I0902 12:43:40.358724 140218740490624 efficientnet_model.py:147] round_filter input=112 output=112
I0902 12:43:40.358849 140218740490624 efficientnet_model.py:147] round_filter input=192 output=192
I0902 12:43:40.600727 140218740490624 efficientnet_model.py:147] round_filter input=192 output=192
I0902 12:43:40.600852 140218740490624 efficientnet_model.py:147] round_filter input=320 output=320
I0902 12:43:40.664604 140218740490624 efficientnet_model.py:147] round_filter input=1280 output=1280
I0902 12:43:40.697749 140218740490624 efficientnet_model.py:458] Building model efficientnet with params ModelConfig(width_coefficient=1.0, depth_coefficient=1.0, resolution=224, dropout_rate=0.2, blocks=(BlockConfig(input_filters=32, output_filters=16, kernel_size=3, num_repeat=1, expand_ratio=1, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=16, output_filters=24, kernel_size=3, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=24, output_filters=40, kernel_size=5, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=40, output_filters=80, kernel_size=3, num_repeat=3, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=80, output_filters=112, kernel_size=5, num_repeat=3, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=112, output_filters=192, kernel_size=5, num_repeat=4, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=192, output_filters=320, kernel_size=3, num_repeat=1, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise')), stem_base_filters=32, top_base_filters=1280, activation='simple_swish', batch_norm='default', bn_momentum=0.99, bn_epsilon=0.001, weight_decay=5e-06, drop_connect_rate=0.2, depth_divisor=8, min_depth=None, use_se=True, input_channels=3, num_classes=1000, model_name='efficientnet', rescale_input=False, data_format='channels_last', dtype='float32')
Traceback (most recent call last):
  File "/home/sahasra/jukshio/object_det_rec/TensorFlow/models/research/object_detection/export_inference_graph.py", line 206, in <module>
    tf.app.run()
  File "/home/sahasra/anaconda3/envs/obj_det/lib/python3.9/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/sahasra/anaconda3/envs/obj_det/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/sahasra/anaconda3/envs/obj_det/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/sahasra/jukshio/object_det_rec/TensorFlow/models/research/object_detection/export_inference_graph.py", line 194, in main
    exporter.export_inference_graph(
  File "/home/sahasra/jukshio/object_det_rec/TensorFlow/models/research/object_detection/exporter.py", line 611, in export_inference_graph
    _export_inference_graph(
  File "/home/sahasra/jukshio/object_det_rec/TensorFlow/models/research/object_detection/exporter.py", line 503, in _export_inference_graph
    outputs, placeholder_tensor_dict = build_detection_graph(
  File "/home/sahasra/jukshio/object_det_rec/TensorFlow/models/research/object_detection/exporter.py", line 457, in build_detection_graph
    placeholder_tensor, input_tensors = input_placeholder_fn_map[input_type](
  File "/home/sahasra/jukshio/object_det_rec/TensorFlow/models/research/object_detection/exporter.py", line 186, in _image_tensor_input_placeholder
    input_tensor = tf.placeholder(
  File "/home/sahasra/anaconda3/envs/obj_det/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 3268, in placeholder
    raise RuntimeError("tf.placeholder() is not compatible with "
RuntimeError: tf.placeholder() is not compatible with eager execution.

**Comment by Rahman2001** [comment]
I think it might be late, but it will be useful to leave the answer to this question. 
If you want to run your app using TF 1.x and TF 2.x, then simply disable eager execution: 
`tf.compat.v1.disable_eager_execution()`
