### ISSUE TITLE
model_builder_tf1_test.py producing "Cannot import name 'get_config' from 'tensorflow.python.eager.context'"

### ISSUE THREAD

**Issue by daniqsilva25** [tensorflow/models#10071]
## Bug description

I am using the TensorFlow Model Garden and TensorFlow 1 (1.15.0), and when I try to run [model_builder_tf1_test.py](https://github.com/tensorflow/models/blob/master/research/object_detection/builders/model_builder_tf1_test.py) to verify the installation of the Object Detection API the following error occurs:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf1_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/content/models/research/object_detection/builders/model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "/content/models/research/object_detection/meta_architectures/deepmac_meta_arch.py", line 19, in <module>
    from object_detection.models.keras_models import resnet_v1
  File "/content/models/research/object_detection/models/keras_models/resnet_v1.py", line 22, in <module>
    from keras.applications import resnet
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 37, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/eager/context.py)

Also, even if I try to run [model_main.py](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py) to start training a model, a similiar error appears:

Traceback (most recent call last):
  File "/content/models/research/object_detection/model_main.py", line 25, in <module>
    from object_detection import model_lib
  File "/content/models/research/object_detection/model_lib.py", line 30, in <module>
    from object_detection import exporter as exporter_lib
  File "/content/models/research/object_detection/exporter.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/content/models/research/object_detection/builders/model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "/content/models/research/object_detection/meta_architectures/deepmac_meta_arch.py", line 19, in <module>
    from object_detection.models.keras_models import resnet_v1
  File "/content/models/research/object_detection/models/keras_models/resnet_v1.py", line 22, in <module>
    from keras.applications import resnet
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 37, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/eager/context.py)

## Environment

I am using Google Colaboratory with a Colab Notebook in a GPU runtime to perform object detection (training, testing) with a TensorFlow-v1.15.0 installation.

My procedure to install the Object Detection API is the following:

!git clone --quiet https://github.com/tensorflow/models.git --depth 1

!pip install tf_slim
!apt-get install -qq protobuf-compiler python-pil python-lxml python-tk
!pip install -q Cython contextlib2 pillow lxml matplotlib PyDrive
!pip install -q pycocotools
!pip install lvis
import numpy as np

%cd /content/models/research

!protoc object_detection/protos/*.proto --python_out=.
!cp object_detection/packages/tf1/setup.py .
!python -m pip install --use-feature=2020-resolver .

import os
os.environ['PYTHONPATH'] += '/content/models:/content/models/research/:/content/models/research/slim/'
import sys
sys.path.append("/content/models")

from tensorflow import keras
!python object_detection/builders/model_builder_tf1_test.py

## Last Notes

Yesterday, the same Colab Notebook was working correctly and today is not, presenting the behavior already demonstrated.

**Comment by saikumarchalla** [comment]
@daniqsilva25  Could you please check with latest version. I tried to install TF OD API and  it was installed properly on colab. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/62ee67712b1f59687a7c838ae883afdb/models_repo.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
@daniqsilva25  Is the issue resolved for you?.

**Comment by saikumarchalla** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by daniqsilva25** [comment]
> @daniqsilva25 Was the issue resolved for you?.

Yes, I have tested TF1 OD API with the last version and it worked correctly!
Thank you very much!
