### ISSUE TITLE
AttributeError: '_UserObject' object has no attribute 'prune' 

### ISSUE THREAD

**Issue by llzhaoshuo** [tensorflow/models#10075]
When I test the trained local feature model to extract local features，I encountered the following problems  :
Traceback (most recent call last):   File "../examples/extract_features.py", line 148, in <module>     app.run(main=main, argv=[sys.argv[0]] + unparsed)   File "/home/lzs/anaconda3/envs/delg/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)   File "/home/lzs/anaconda3/envs/delg/lib/python3.6/site-packages/absl/app.py", line 312, in run     _run_main(main, args)   File "/home/lzs/anaconda3/envs/delg/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main     sys.exit(main(argv))   File "../examples/extract_features.py", line 85, in main     extractor_fn = extractor.MakeExtractor(config)   File "/media/lzs/de2ef254-eaa4-4486-b00b-ab367ed2a6d8/home/lzs/models/research/delf/delf/python/examples/extractor.py", line 138, in MakeExtractor     model = model.prune(feeds=feeds, fetches=fetches) AttributeError: '_UserObject' object has no attribute 'prune' 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
python ../examples/extract_features.py --config_path ../examples/delf_config_example.pbtxt --list_images_path list_images.txt --output_dir data/local_features

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by llzhaoshuo** [comment]
I've solved it.Thank you very much!

**Comment by ymodak** [comment]
@llzhaoshuo Can you please describe what steps you took to resolve it? Thanks!
