### ISSUE TITLE
AttributeError: 'DatasetV1Adapter' object has no attribute 'unbatch'

### ISSUE THREAD

**Issue by robertorovella91** [tensorflow/models#10089]
Hi to all,
i am trying to run model_lib_test script but i get the following with tensorflow 1.14 how can i fix?
Thanks in advance
## 2. Describe the bug

Model_lib_test fail with tensorflow 1.14 

## 3. Steps to reproduce
python3 model_lib_tf1_test.py

## 4. Expected behavior
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_lib_tf1_test.py", line 257, in test_model_fn_in_eval_mode_sequences
    self._assert_model_fn_for_train_eval(configs, 'eval')
  File "model_lib_tf1_test.py", line 146, in _assert_model_fn_for_train_eval
    configs['model'])()).get_next()
  File "/home/roberto/Desktop/Tensorflow/models/research/object_detection/inputs.py", line 916, in _eval_input_fn
    params=params)
  File "/home/roberto/Desktop/Tensorflow/models/research/object_detection/inputs.py", line 1056, in eval_input
    reduce_to_frame_fn=reduce_to_frame_fn)
  File "/home/roberto/Desktop/Tensorflow/models/research/object_detection/builders/dataset_builder.py", line 255, in build
    input_reader_config)
  File "/home/roberto/Desktop/Tensorflow/models/research/object_detection/inputs.py", line 1189, in reduce_to_frame
    dataset = dataset.unbatch()
AttributeError: 'DatasetV1Adapter' object has no attribute 'unbatch'

----------------------------------------------------------------------
Ran 20 tests in 69.980s

FAILED (errors=1, skipped=2)

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution  Linux Ubuntu 18.04):

- TensorFlow installed from pip
- TensorFlow version 1.14
- Python version: 3.7.3

**Comment by ymodak** [comment]
`dataset.unbatch()` was added with TF 1.15 https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/data/Dataset#unbatch
Please upgrade to TF 1.15 and try again. Thanks!
