### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by shubham7066** [tensorflow/models#10129]
Getting this error on using model_main_tf2.py:

Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 112, in main
    record_summaries=FLAGS.record_summaries)
  File "/kaggle/working/TFOD/models/research/object_detection/model_lib_v2.py", line 585, in train_loop
    os.path.join(model_dir, 'train'))
  File "/opt/conda/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

what should i do

_Originally posted by @shubham7066 in https://github.com/tensorflow/models/issues/9372#issuecomment-878848676_

**Comment by ymodak** [comment]
From the stack trace looks like your `--model_dir` path is incorrect. You may also want to check `--pipeline_config_path` if correctly set.
