### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError: flag --record_summaries=training: ('Non-boolean argument to boolean flag', 'training')

### ISSUE THREAD

**Issue by wzh19980523** [tensorflow/models#10142]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden research directory)
- [ ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/research/git

## 2. Describe the bug

When I run python model_main_tf2.py   --logtostderr   --model_dir=training   --pipeline_config_path=training/pipline.config   --checkpoint_every_n=200   --record_summaries=training   for training An error has occurred

python model_main_tf2.py   --logtostderr   --model_dir=training   --pipeline_config_path=training/pipline.config   --checkpoint_every_n=200   --record_summaries=training
2021-07-17 22:22:20.880656: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-07-17 22:22:20.880754: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/flags/_flag.py", line 181, in _parse
    return self.parser.parse(argument)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 305, in parse
    raise ValueError('Non-boolean argument to boolean flag', argument)
ValueError: ('Non-boolean argument to boolean flag', 'training')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 306, in run
    flags_parser,
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 375, in _run_init
    flags_parser=flags_parser,
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 220, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 31, in _parse_flags_tolerate_undef
    return flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 113, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 663, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 812, in _parse_args
    flag.parse(value)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/flags/_flag.py", line 166, in parse
    self.value = self._parse(argument)
  File "/home/dl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/flags/_flag.py", line 184, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --record_summaries=training: ('Non-boolean argument to boolean flag', 'training')

## 6. System information

- OS Platform and Distribution : Linux Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):tensorflow 2.3.0
- Python version: python 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:no gpu
- GPU model and memory:

**Comment by wzh19980523** [comment]
The entire URL of the file you are using
https://github.com/tensorflow/models/research

**Comment by saikumarchalla** [comment]
@wzh19980523  Could you please provide the information like which pre-trained model are you using?.

Also, the URL you have provided is showing error. Thanks!

**Comment by wzh19980523** [comment]
> @wzh19980523 Could you please provide the information like which pre-trained model are you using?.
> 
> Also, the URL you have provided is showing error. Thanks!

sorry the URL is https://github.com/tensorflow/models
pre-trained is ssd_mobilenet_v2_320x320_coco17_tpu-8

**Comment by wzh19980523** [comment]
> > @wzh19980523 Could you please provide the information like which pre-trained model are you using?.
> > Also, the URL you have provided is showing error. Thanks!
> 
> sorry the URL is https://github.com/tensorflow/models
> pre-trained is ssd_mobilenet_v2_320x320_coco17_tpu-8

i run flllowing command
 python3 model_main_tf2.py \
  --logtostderr \
  --model_dir=training \
  --pipeline_config_path=training/pipline.config \
  --checkpoint_every_n=200 \
  --record_summaries=training

**Comment by wzh19980523** [comment]
> > > @wzh19980523 Could you please provide the information like which pre-trained model are you using?.
> > > Also, the URL you have provided is showing error. Thanks!
> > 
> > 
> > sorry the URL is https://github.com/tensorflow/models
> > pre-trained is ssd_mobilenet_v2_320x320_coco17_tpu-8
> 
> i run flllowing command
> python3 model_main_tf2.py
> --logtostderr
> --model_dir=training
> --pipeline_config_path=training/pipline.config
> --checkpoint_every_n=200
> --record_summaries=training

I refer to this URL https://github.com/Sun-Yize-SDUWH/Deep-Learning-On-Raspberry-Pi-Zero

**Comment by jvishnuvardhan** [comment]
@wzh19980523 Based on the error message, it looks like `--record_summaries` is looking for a boolean as shown below.
https://github.com/tensorflow/models/blob/03a5f09a095cbae5b2223c8423c2356f46dcdb71/research/object_detection/model_main_tf2.py#L67

Can you try setting it as `--record_summaries=True`. Thanks!
