### ISSUE TITLE
cifar10 error

### ISSUE THREAD

**Issue by melvyniandrag** [tensorflow/models#1015]
In /models/tutorials/image/cifar10 when I run cifar10_train.py I get this error:

`AttributeError: module 'tensorflow' has no attribute 'strided_slice'`

Full stack trace:

```

Traceback (most recent call last):
  File "cifar10_train.py", line 120, in <module>
    tf.app.run()
  File "/home/temp/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run 
    sys.exit(main(sys.argv))
  File "cifar10_train.py", line 116, in main
    train()
  File "cifar10_train.py", line 63, in train
    images, labels = cifar10.distorted_inputs()
  File "/home/temp/models/tutorials/image/cifar10/cifar10.py", line 156, in distorted_inputs
    batch_size=FLAGS.batch_size)
  File "/home/temp/models/tutorials/image/cifar10/cifar10_input.py", line 161, in distorted_inputs
    read_input = read_cifar10(filename_queue)
  File "/home/temp/models/tutorials/image/cifar10/cifar10_input.py", line 87, in read_cifar10
    tf.strided_slice(record_bytes, [0], [label_bytes]), tf.int32)
AttributeError: module 'tensorflow' has no attribute 'strided_slice'

```

**Comment by melvyniandrag** [comment]
Nevermind. I had installed v10 not v12. Now I have another error that 

`TypeError: strided_slice() missing 1 required positional argument: 'strides'`

I have seen solutions to this on SO. When I read and understand the tutorial I'll submit a PR to have the tutorial code changed.
