### ISSUE TITLE
freeze_variables has no effect when training with model_main_tf2.py

### ISSUE THREAD

**Issue by jessicametzger** [tensorflow/models#10167]
I noticed the freeze_variables train config is never accounted for when training with model_main_tf2.py

# Versions

- Tensorflow 2.5
- Commit: latest (Mon Jul 19 12:32:17 2021 -0700)
- tf_env_collect.sh output [here](https://textsaver.flap.tv/lists/48jl)

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py
https://github.com/tensorflow/models/blob/master/research/object_detection/model_lib_v2.py

## 2. Describe the bug

When I provide something in the freeze_variables config ([here in train.proto](https://github.com/tensorflow/models/blob/697da6578fe886dc2478ce71291ccd7d39f5d51d/research/object_detection/protos/train.proto#L114)), e.g. `freeze_variables: ['.*conv.']`, and then run training with [model_main_tf2.py](
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py) as in the [tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html), no variables are frozen and all layers are trained. I went through the model and training protocol configuration steps in [model_lib_v2.py](https://github.com/tensorflow/models/blob/master/research/object_detection/model_lib_v2.py), in the [train_loop method](https://github.com/tensorflow/models/blob/697da6578fe886dc2478ce71291ccd7d39f5d51d/research/object_detection/model_lib_v2.py#L437) which is called in model_main_tf2.py, and it never seems to touch the freeze_variables option.

## 3. Steps to reproduce

Follow the steps of the tutorial to set up a training run for the [SSD resnet50 v1 fpn model](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz), and use the config file included with the model. Add `freeze_variables: ['.*conv.']` to `train_config`. If you add `print(detection_model.trainable_variables)` to [line 673 of model_lib_v2.py](https://github.com/tensorflow/models/blob/697da6578fe886dc2478ce71291ccd7d39f5d51d/research/object_detection/model_lib_v2.py#L673) (right before the training begins), it outputs all variables, i.e. all variables are still trainable.

## 4. Expected behavior

Variables matching the provided freeze_variable regex should no longer be trainable.

**Comment by jessicametzger** [comment]
I have added the following code at [line 310 of model_lib_v2.py](https://github.com/tensorflow/models/blob/03a5f09a095cbae5b2223c8423c2356f46dcdb71/research/object_detection/model_lib_v2.py#L310), inside the eager_train_step method:

```python
  if train_config.freeze_variables:
    trainable_variables = variables_helper.filter_variables(trainable_variables, exclude_patterns=train_config.freeze_variables)
```

I have also added train_config as an argument to the eager_train_step method. I think this solves it, but I am not sure.

**Comment by iumyx2612** [comment]
> I have added the following code at [line 310 of model_lib_v2.py](https://github.com/tensorflow/models/blob/03a5f09a095cbae5b2223c8423c2356f46dcdb71/research/object_detection/model_lib_v2.py#L310), inside the eager_train_step method:
> 
> ```python
>   if train_config.freeze_variables:
>     trainable_variables = variables_helper.filter_variables(trainable_variables, exclude_patterns=train_config.freeze_variables)
> ```
> 
> I have also added train_config as an argument to the eager_train_step method. I think this solves it, but I am not sure.

I did as you said but this is the output message: 
```
...
Use fn_output_signature instead
INFO:tensorflow:Error reported to Coordinator: in user code:

    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:633 train_step_fn  *
        losses_dict = eager_train_step(
    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:312 eager_train_step  *
        trainable_variables = variables_helper.filter_variables(trainable_variables,
    E:\Anaconda\envs\TFOD\lib\site-packages\object_detection\utils\variables_helper.py:69 filter_variables  *
        if re.match(pattern, var.op.name):
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\distribute\values.py:230 __getattr__
        return getattr(self._get(), name)
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:596 op
        return self._handle.op
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\framework\ops.py:1222 op
        raise AttributeError(

    AttributeError: Tensor.op is meaningless when eager execution is enabled.
Traceback (most recent call last):
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\training\coordinator.py", line 297, in stop_on_exception
    yield
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\distribute\mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:633 train_step_fn  *
        losses_dict = eager_train_step(
    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:312 eager_train_step  *
        trainable_variables = variables_helper.filter_variables(trainable_variables,
    E:\Anaconda\envs\TFOD\lib\site-packages\object_detection\utils\variables_helper.py:69 filter_variables  *
        if re.match(pattern, var.op.name):
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\distribute\values.py:230 __getattr__
        return getattr(self._get(), name)
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:596 op
        return self._handle.op
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\framework\ops.py:1222 op
        raise AttributeError(

    AttributeError: Tensor.op is meaningless when eager execution is enabled.

I0819 12:50:48.308307 18452 coordinator.py:217] Error reported to Coordinator: in user code:

    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:633 train_step_fn  *
        losses_dict = eager_train_step(
    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:312 eager_train_step  *
        trainable_variables = variables_helper.filter_variables(trainable_variables,
    E:\Anaconda\envs\TFOD\lib\site-packages\object_detection\utils\variables_helper.py:69 filter_variables  *
        if re.match(pattern, var.op.name):
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\distribute\values.py:230 __getattr__
        return getattr(self._get(), name)
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:596 op
        return self._handle.op
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\framework\ops.py:1222 op
        raise AttributeError(

    AttributeError: Tensor.op is meaningless when eager execution is enabled.
Traceback (most recent call last):
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\training\coordinator.py", line 297, in stop_on_exception
    yield
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\distribute\mirrored_run.py", line 323, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:633 train_step_fn  *
        losses_dict = eager_train_step(
    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:312 eager_train_step  *
        trainable_variables = variables_helper.filter_variables(trainable_variables,
    E:\Anaconda\envs\TFOD\lib\site-packages\object_detection\utils\variables_helper.py:69 filter_variables  *
        if re.match(pattern, var.op.name):
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\distribute\values.py:230 __getattr__
        return getattr(self._get(), name)
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:596 op
        return self._handle.op
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\framework\ops.py:1222 op
        raise AttributeError(

    AttributeError: Tensor.op is meaningless when eager execution is enabled.

Traceback (most recent call last):
  File "E:\Anaconda\envs\TFOD\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "E:/Work work/DATN/Tensorflow/workspace/model_main_tf2.py", line 106, in main
    model_lib_v2.train_loop(
  File "E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py", line 683, in train_loop
    losses_dict = _dist_train_step(train_input_iter)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\eager\def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\eager\def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\eager\function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:667 _dist_train_step  *
        _sample_and_train(strategy, train_step_fn, data_iterator)
    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:649 _sample_and_train  *
        per_replica_losses_dict = strategy.run(
    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:633 train_step_fn  *
        losses_dict = eager_train_step(
    E:\Work work\DATN\Tensorflow\workspace\model_lib_v2.py:312 eager_train_step  *
        trainable_variables = variables_helper.filter_variables(trainable_variables,
    E:\Anaconda\envs\TFOD\lib\site-packages\object_detection\utils\variables_helper.py:69 filter_variables  *
        if re.match(pattern, var.op.name):
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\distribute\values.py:230 __getattr__
        return getattr(self._get(), name)
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:596 op
        return self._handle.op
    E:\Anaconda\envs\TFOD\lib\site-packages\tensorflow\python\framework\ops.py:1222 op
        raise AttributeError(

    AttributeError: Tensor.op is meaningless when eager execution is enabled.


Process finished with exit code -1
```
