### ISSUE TITLE
How to get better fps for raspberry pi with coral usb

### ISSUE THREAD

**Issue by kotran88** [tensorflow/models#10268]
Hello I trained well with tf1 - coco ssd model and get result quite as I intended
normally, I do all command with google colab

with pb file to convert to tfltie, 
I used this command

`!tflite_convert --graph_def_file=/content/drive/MyDrive/onoff_dnn/models/my_tflite_mobile/tflite_graph.pb --output_file=/content/drive/MyDrive/onoff_dnn/models/my_tflite_mobile/detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 --allow_custom_ops --post_training_quantize --inference_type FLOAT --inference_input_type FLOAT`

and I download edge compiler as coral doc says
```
! curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
! echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
! sudo apt-get update
! sudo apt-get install edgetpu-compiler
```

then, I compiled like this
```
NUMBER_OF_TPUS =  1
!edgetpu_compiler detect.tflite --num_segments=$NUMBER_OF_TPUS

```
but it says number of edge TPU subgraphs is 0. 
should I do something when I train to get best result for raspberry pi? 
```

Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 21 ms.

Input model: detect.tflite
Input size: 5.49MiB
Output model: detect_edgetpu.tflite
Output size: 5.49MiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 75
Operation log: detect_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 75
See the operation log file for individual operation details.
Compilation child process completed within timeout period.
Compilation succeeded! 
``` @

**Comment by kotran88** [comment]
I tried new pretrained model
http://download.tensorflow.org/models/object_detection/ssdlite_mobiledet_edgetpu_320x320_coco_2020_05_19.tar.gz
but it cause error when I start training. 
```

Traceback (most recent call last):
  File "/content/drive/MyDrive/onoff_dnn/models/research/object_detection/legacy/train.py", line 186, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/onoff_dnn/models/research/object_detection/legacy/train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/drive/MyDrive/onoff_dnn/models/research/object_detection/legacy/trainer.py", line 397, in train
    init_saver = tf.train.Saver(available_var_map)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/training/saver.py", line 865, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables/boolean_mask/GatherV2:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)  File "/content/drive/MyDrive/onoff_dnn/models/research/object_detection/legacy/train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)  File "/content/drive/MyDrive/onoff_dnn/models/research/object_detection/legacy/trainer.py", line 415, in train
    saver=saver)  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/training/sync_replicas_optimizer.py", line 359, in apply_gradients
    return train_op  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
E0921 07:16:49.499078 139701572372352 tf_should_use.py:76] ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables/boolean_mask/GatherV2:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)  File "/content/drive/MyDrive/onoff_dnn/models/research/object_detection/legacy/train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)  File "/content/drive/MyDrive/onoff_dnn/models/research/object_detection/legacy/trainer.py", line 415, in train
    saver=saver)  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/training/sync_replicas_optimizer.py", line 359, in apply_gradients
    return train_op  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
```
