### ISSUE TITLE
ERROR: You must give at least one requirement to install (see "pip help install")

### ISSUE THREAD

**Issue by yeashen1113** [tensorflow/models#10362]
Hi all, I'm trying to set up TensorFlow CPU 1.15.0 on an Anaconda environment,

I was following tutorials on how to set up but I encounter an error when I reach this step:
cp object_detection/packages/tf1/setup.py .
python -m pip install 

I understand that I'm using windows thus I change the above step to 
copy object_detection/packages/tf1/setup.py
python -m pip install 

Here is the error statement.
**ERROR: You must give at least one requirement to install (see "pip help install")**

I google it and can't find anyone with the same issue, what is it that I'm doing wrong? Pls help!

Below is the step I have taken to install TensorFlow:
1. conda create -n tensorflow1 pip python=3.7
2. conda activate tensorflow1
3. python -m pip install --upgrade pip
4. pip install --ignore-installed --upgrade tensorflow==1.15.0
5. 
conda install -c anaconda protobuf
pip install pillow
pip install lxml
pip install Cython
pip install contextlib2
pip install jupyter
pip install matplotlib
pip install pandas
pip install opencv-python
6. set PYTHONPATH=C:\tensorflow1\models;C:\tensorflow1\models\research;C:\tensorflow1\models\research\slim
7. cd C:\tensorflow1\models\research
8. protoc object_detection/protos/*.proto --python_out=.
9. copy object_detection\packages\tf1\setup.py
10. python -m pip install

ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by yeashen1113** [comment]
Guys update on my problem,
Upon googling, I realize that I might have typed the wrong command as simple command:
**pip install .**
started the installation. 

However, after the installation, I run the following command to test if the installation is successful:
**python builders\model_builder_tf1_test.py**

A new error occur:
(tensorflow1) C:\tensorflow1\models\research\object_detection>python builders\model_builder_tf1_test.py
2021-11-15 15:00:30.638411: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-11-15 15:00:30.638523: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "builders\model_builder_tf1_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "C:\tensorflow1\models\research\object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in <module>
    import tensorflow_io as tfio  # pylint:disable=g-import-not-at-top
ModuleNotFoundError: No module named 'tensorflow_io'

I believe that the installation was unsuccessful, can I know why?

**Comment by yeashen1113** [comment]
Guys update on my problem,
Upon googling, I realize that I might have typed the wrong command as simple command:
pip install .
started the installation.

However, after the installation, I run the following command to test if the installation is successful:
python builders\model_builder_tf1_test.py

A new error occur:
(tensorflow1) C:\tensorflow1\models\research\object_detection>python builders\model_builder_tf1_test.py
2021-11-15 15:00:30.638411: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-11-15 15:00:30.638523: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
File "builders\model_builder_tf1_test.py", line 21, in
from object_detection.builders import model_builder
File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 37, in
from object_detection.meta_architectures import deepmac_meta_arch
File "C:\tensorflow1\models\research\object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in
import tensorflow_io as tfio # pylint:disable=g-import-not-at-top
ModuleNotFoundError: No module named 'tensorflow_io'

I believe that the installation was unsuccessful, can I know why?
PS I don't know if its the same issue or do I have to create a new issue for this question.
