### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_io'

### ISSUE THREAD

**Issue by yeashen1113** [tensorflow/models#10370]
Upon running the command: python builders\model_builder_tf1_test.py
I got the below error:
(tensorflow1) C:\tensorflow1\models\research\object_detection>python builders\model_builder_tf1_test.py
2021-11-15 15:49:12.718784: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-11-15 15:49:12.718926: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "builders\model_builder_tf1_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "C:\tensorflow1\models\research\object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in <module>
    import tensorflow_io as tfio  # pylint:disable=g-import-not-at-top
ModuleNotFoundError: No module named 'tensorflow_io'

Is it because of the setup.py? Pls help!

**Comment by kumariko** [comment]
@yeashen1113 Could you please have a look on the [link1](https://stackoverflow.com/questions/58986079/tensorflow-io-module-is-missing-how-do-i-get-gfile), [link2](https://githubmemory.com/repo/tensorflow/io/issues/1453) and let us know if it helps? Thanks!

**Comment by yeashen1113** [comment]
Hi all, so I think I figure out the problem, I checked my TensorFlow version and it is at 2 for some reason. Maybe it auto-upgrade after running some commands, I downloaded TensorFlow 1.15.0 and the model_builder_tf1_test.py is working normally. 

However I'm facing other issues when running the final command, python model_main.py --model_dir=training/ pipeline_config_path=training/ ssd_mobilenet_v2_quantized_300x300_coco.config. 

I will create a new issue for that.

**Comment by khyatigarg1** [comment]
I seem to be having the same issue where I receive this error when I try to test the API has been correctly installed:
---
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/Users/khyati/models/research/object_detection/builders/model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "/Users/khyati/models/research/object_detection/meta_architectures/deepmac_meta_arch.py", line 28, in <module>
    import tensorflow_io as tfio  # pylint:disable=g-import-not-at-top
ModuleNotFoundError: No module named 'tensorflow_io'
---
My tensorflow version is 2.4.1 and my python is in 3.8

**Comment by rabbitmice** [comment]
不凶！

**Comment by yaminocellist** [comment]
I have the same issue using TensorFlow version = 2.10.0

**Comment by ANJ-Projects** [comment]
This is not solved yet. Even getting python2, and pip did not work. This project needs better setup documentation

**Comment by haoleng-Wick** [comment]
You can install the package named "tensorflow.io" with pip
`pip install tensorflow.io`
