### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by glcsvg** [tensorflow/models#10378]
Im using tensorflow 2.5(cpu),a few days ago i was not getting error

`
/TensorFlow/models/research$ python object_detection/builders/model_builder_tf2_test.py`

My eeror:
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 25, in <module>
    from object_detection.builders import model_builder
  File "/home/dell/TensorFlow/models/research/object_detection/builders/model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "/home/dell/TensorFlow/models/research/object_detection/meta_architectures/deepmac_meta_arch.py", line 28, in <module>
    import tensorflow_io as tfio  # pylint:disable=g-import-not-at-top
  File "/home/dell/miniconda3/envs/tensorflow22/lib/python3.8/site-packages/tensorflow_io/__init__.py", line 17, in <module>
    from tensorflow_io.python.api import *  # pylint: disable=wildcard-import
  File "/home/dell/miniconda3/envs/tensorflow22/lib/python3.8/site-packages/tensorflow_io/python/api/__init__.py", line 19, in <module>
    from tensorflow_io.python.ops.io_dataset import IODataset
  File "/home/dell/miniconda3/envs/tensorflow22/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py", line 96, in <module>
    plugin_ops = _load_library("libtensorflow_io_plugins.so", "fs")
  File "/home/dell/miniconda3/envs/tensorflow22/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py", line 64, in _load_library
    l = load_fn(f)
  File "/home/dell/miniconda3/envs/tensorflow22/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py", line 56, in <lambda>
    load_fn = lambda f: tf.experimental.register_filesystem_plugin(f) is None
  File "/home/dell/miniconda3/envs/tensorflow22/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 218, in register_filesystem_plugin
    py_tf.TF_RegisterFilesystemPlugin(plugin_location)

**Comment by saberkun** [comment]
Hi, sorry about this. it is because the __init__.py was accidentally removed. (our internal build system does not rely on it)
I will fix it soon.

I am not sure why Python3 pip still need this __init__.py. Please share your knowledge if you know if with py3, the __init__.py can go away for package release.
