### ISSUE TITLE
Error exporting inference graph for spaghettinet

### ISSUE THREAD

**Issue by jjd9** [tensorflow/models#10408]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release...
- [ ] ... and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or **research** directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py

## 2. Describe the bug

After retraining the new spaghettinet object detection model on a custom dataset, I went to export the graph using the `export_inference_graph.py` file. Training worked fine, but when I tried to run export_inference_graph.py as described in the tf1 docs, I received the following error.

```
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W1201 04:03:47.530538 140603187050368 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/op_def_library.py", line 528, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/constant_op.py", line 303, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 160, 160, 8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/op_def_library.py", line 542, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/constant_op.py", line 303, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 160, 160, 8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/models/research/object_detection/export_inference_graph.py", line 206, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/export_inference_graph.py", line 202, in main
    side_input_types=side_input_types)
  File "/content/models/research/object_detection/exporter.py", line 625, in export_inference_graph
    side_input_types=side_input_types)
  File "/content/models/research/object_detection/exporter.py", line 512, in _export_inference_graph
    side_input_types=side_input_types)
  File "/content/models/research/object_detection/exporter.py", line 471, in build_detection_graph
    **side_inputs)
  File "/content/models/research/object_detection/exporter.py", line 432, in _get_outputs_from_inputs
    preprocessed_inputs, true_image_shapes, **side_inputs)
  File "/content/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 579, in predict
    preprocessed_inputs)
  File "/content/models/research/object_detection/models/ssd_spaghettinet_feature_extractor.py", line 894, in extract_features
    feature_maps = spaghetti_net.apply(preprocessed_inputs)
  File "/content/models/research/object_detection/models/ssd_spaghettinet_feature_extractor.py", line 384, in apply
    self._spaghetti_node(node, '{}/{}'.format(scope, node))
  File "/content/models/research/object_detection/models/ssd_spaghettinet_feature_extractor.py", line 335, in _spaghetti_node
    '{}_{}'.format(scope, idx))
  File "/content/models/research/object_detection/models/ssd_spaghettinet_feature_extractor.py", line 188, in _ibn_fused_grouped
    slice_input = tf.slice(net, slice_begin, slice_shape)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py", line 855, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/gen_array_ops.py", line 9222, in _slice
    "Slice", input=input, begin=begin, size=size, name=name)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/op_def_library.py", line 546, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'size' to a tensor and failed. Error: Cannot convert a partially known TensorShape to a Tensor: (?, 160, 160, 8)
```

To confirm that this was not a problem with my training, I tried just directly exporting the model checkpoint available from the model zoo (http://download.tensorflow.org/models/object_detection/tf1/spaghettinet_edgetpu_s_2021_10_13.tar.gz). And I get the same error. This leads me to believe this may be a bug in the spaghetti net, export_inference_graph.py, or a gap in the docs. But if that were the case, how was the frozen_inference_graph.pb available from the tf1 model zoo download created???

## 3. Steps to reproduce

This can be reproduced by pasting the following code into a google colab cell and running it. I tested this with some of the other models in the tf1 zoo, and it works properly for those (e.g. http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz).

```
# Setup all the dependencies
# -------------------------------------------
try:
  # This %tensorflow_version magic only works in Colab.
  %tensorflow_version 1.x
except Exception:
  pass
# For your non-Colab code, be sure you have tensorflow==1.15
import tensorflow as tf
assert tf.__version__.startswith('1')

! pip install tf_slim
! git clone https://github.com/tensorflow/models.git

import os
os.environ['PYTHONPATH'] += ':/content/models/research/'
os.environ['PYTHONPATH'] += ':/content/models/research/slim/'
os.environ['PYTHONPATH'] += ':/content/models/research/object_detection/utils/'
os.environ['PYTHONPATH'] += ':/content/models/research/object_detection'

! apt-get install protobuf-compiler

%cd models/research
# Compile all the protobuf dependencies
! protoc object_detection/protos/*.proto --python_out=.
# Set up and install the object detection API
! cp object_detection/packages/tf1/setup.py .
! python -m pip install .
# Run a test to make sure setup is correct
! python object_detection/builders/model_builder_test.py
# -------------------------------------------
# Get the model from the tf1 zoo https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md
model_name = "spaghettinet_edgetpu_s"
!mkdir /content/pretrained_model
%cd /content/pretrained_model
! wget http://download.tensorflow.org/models/object_detection/tf1/{model_name}_2021_10_13.tar.gz
! tar xvf {model_name}.tar.gz
# -------------------------------------------
# Attempt to export the saved checkpoint as per https://colab.research.google.com/drive/1M8JxWhdTzL3MMFXS_hEYyJq3ND5LwZuG#scrollTo=939iMz18Ojsn
config_path = '/content/pretrained_model/'+model_name+'/pipeline.config'
! python3 /content/models/research/object_detection/export_inference_graph.py \
    --input_type=image_tensor \
    --pipeline_config_path=$config_path \
    --output_directory=/content/inference_graph \
    --trained_checkpoint_prefix=/content/pretrained_model/spaghettinet_edgetpu_s/model.ckpt-400000
```

## 4. Expected behavior

The spaghettinet model checkpoint is exported to a frozen_inference_graph.pb after running the export_inference_graph.py script as described in the docs.

## 5. Additional context

Please see error above.

## 6. System information

- OS Platform and Distribution: Google colab notebook with GPU backend, likely some recent version of Linux?
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): 1.15.2
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.2 
- GPU model and memory: Tesla K80 (Driver Version: 460.32.03), 12 GB memory

**Comment by jjd9** [comment]
Figured it out! :grinning: You have to set the input_shape when exporting the inference graph for some reason. Although it is odd that this is not the case with the other tf1 model zoo models I have tried, my bad for not figuring it out sooner... :man_facepalming:
