### ISSUE TITLE
object_detection: AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by Rayndell** [tensorflow/models#10417]
After installing object_detection for TF 2 (Windows) following the link: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

When executing the test program (python object_detection\builders\model_builder_tf2_test.py), got this error message:

D:\TensorFlow\models\research>python object_detection\builders\model_builder_tf2_test.py
Traceback (most recent call last):
  File "object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "D:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "D:\TensorFlow\models\research\object_detection\builders\anchor_generator_builder.py", line 27, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "D:\TensorFlow\models\research\object_detection\protos\anchor_generator_pb2.py", line 15, in <module>
    from object_detection.protos import flexible_grid_anchor_generator_pb2 as object__detection_dot_protos_dot_flexible__grid__anchor__generator__pb2
  File "D:\TensorFlow\models\research\object_detection\protos\flexible_grid_anchor_generator_pb2.py", line 21, in <module>
    _FLEXIBLEGRIDANCHORGENERATOR = DESCRIPTOR.message_types_by_name['FlexibleGridAnchorGenerator']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

**Comment by Rayndell** [comment]
OK, after further verification it turned out that the protobuf version installed on my Python was outdated.

For those with the same problem : pip install --upgrade protobuf should solve the case.
