### ISSUE TITLE
Error running tensorflow from docker container

### ISSUE THREAD

**Issue by mgmike** [tensorflow/models#10461]
I am following the directions of the [tf2.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md) doc. I built the docker image and ran the container successfully.

When running the 'test the integration' line, 

> python object_detection/builders/model_builder_tf2_test.py

I get the following error message:
>Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 22, in <module>
    import tensorflow.compat.v1 as tf
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 438, in <module>
    _ll.load_library(_main_dir)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

I am running Ubuntu 18.04 with cuda 11.2, cudnn 8.1.1 and driver 460.106.00 for gtx 1080ti. 
I have not changed anything about the docker container so the tensorflow version is 2.6.2, and the python version is 3.6.9. 
I checked the tensorflow compatibility matrix and everything seems fine, except for my base gcc version which is 7.5.0. Could this be the issue? Either way, both included tensorflow version checks give the same issue.

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Comment by sulc** [comment]
Looks like (unresolved) issue #10439
