### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 8: invalid start byte

### ISSUE THREAD

**Issue by Let-me-look** [tensorflow/models#10471]
tensorflow-gpu 2.5
Win11
python3.8

I'm learning "tensorflow 2 objection detection api" from [here](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html) 
Python model_main_FT2.py --model_dir=D:/tf_train/workspaces/cats_dogs/trained_frozen_models --pipeline_config_path=D:/tf_train/workspaces/cats_dogs/training/ssd_mobilenet_v2_coke. config --alsologtostderr" error occurred

```
(tf_gpu) D:\tf_train\workspaces>python model_main_tf2.py --model_dir=D:/tf_train/workspaces/cats_dogs/trained_frozen_models --pipeline_config_path=D:/tf_train/workspaces/cats_dogs/trai
ning/ssd_mobilenet_v2_coco.config --alsologtostderr
2022-01-25 11:28:20.761295: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the followi
ng CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-25 11:28:21.076840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1669 MB memory:  -> device: 0, nam
e: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0125 11:28:21.075846 25732 mirrored_strategy.py:376] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: None
I0125 11:28:21.075846 25732 config_util.py:552] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0125 11:28:21.075846 25732 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:From D:\tf_train\models\research\object_detection\model_lib_v2.py:563: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute
.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0125 11:28:21.212110 25732 deprecation.py:341] From D:\tf_train\models\research\object_detection\model_lib_v2.py:563: StrategyBase.experimental_distribute_datasets_from_function (from
 tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 106, in main
    model_lib_v2.train_loop(
  File "D:\tf_train\models\research\object_detection\model_lib_v2.py", line 563, in train_loop
    train_input = strategy.experimental_distribute_datasets_from_function(
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 348, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1199, in experimental_distribute_datasets_from_function
    return self.distribute_datasets_from_function(dataset_fn, options)
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1190, in distribute_datasets_from_function
    return self._extended._distribute_datasets_from_function(  # pylint: disable=protected-access
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\distribute\mirrored_strategy.py", line 594, in _distribute_datasets_from_function
    return input_lib.get_distributed_datasets_from_function(
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 175, in get_distributed_datasets_from_function
    return DistributedDatasetsFromFunction(
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1618, in __init__
    self.build()
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1638, in build
    _create_datasets_from_function_with_input_context(
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 2350, in _create_datasets_from_function_with_input_context
    dataset = dataset_fn(ctx)
  File "D:\tf_train\models\research\object_detection\model_lib_v2.py", line 554, in train_dataset_fn
    train_input = inputs.train_input(
  File "D:\tf_train\models\research\object_detection\inputs.py", line 902, in train_input
    dataset = INPUT_BUILDER_UTIL_MAP['dataset_build'](
  File "D:\tf_train\models\research\object_detection\builders\dataset_builder.py", line 210, in build
    decoder = decoder_builder.build(input_reader_config)
  File "D:\tf_train\models\research\object_detection\builders\decoder_builder.py", line 52, in build
    decoder = tf_example_decoder.TfExampleDecoder(
  File "D:\tf_train\models\research\object_detection\data_decoders\tf_example_decoder.py", line 458, in __init__
    _ClassTensorHandler(
  File "D:\tf_train\models\research\object_detection\data_decoders\tf_example_decoder.py", line 92, in __init__
    name_to_id = label_map_util.get_label_map_dict(
  File "D:\tf_train\models\research\object_detection\utils\label_map_util.py", line 201, in get_label_map_dict
    label_map = load_labelmap(label_map_path_or_proto)
  File "D:\tf_train\models\research\object_detection\utils\label_map_util.py", line 168, in load_labelmap
    label_map_string = fid.read()
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 123, in read
    return self._prepare_value(self._read_buf.read(length))
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 95, in _prepare_value
    return compat.as_str_any(val)
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 142, in as_str_any
    return as_str(value)
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 121, in as_str
    return as_text(bytes_or_text, encoding)
  File "D:\Anaconda\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 112, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 8: invalid start byte
```
By constantly "printing" it is found that a large part of the contents of ".record" are garbled and a small part can be recognized
I wonder if the ".record" content is not in "UTF-8" format
How can I solve this problem?
Thanks

**Comment by Let-me-look** [comment]
I solved the problem because I put the.pbtxt and.record paths backwards. I can't believe I've been stuck with this problem for so long
