### ISSUE TITLE
MoviNet: Prediction Examples fail to run

### ISSUE THREAD

**Issue by feckpown** [tensorflow/models#10516]
Downloading the base-model checkpoint in the readme link provided, and running the Base Model prediction example results in the following error 

```
Traceback (most recent call last):
  File "load_base_model_checkpoint.py", line 35, in <module>
    prediction = tf.argmax(output, -1)
  File "/home/user/anaconda3/envs/action-py38/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/user/anaconda3/envs/action-py38/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value ({'state_block0_layer0_pool_buffer': <tf.Tensor: shape=(1, 1, 1, 1, 24), dtype=float32, numpy=
array([[[[[-0.8313048 , 13.299668  ,  8.275953  , -1.5032257 ,
            0.13795474,  6.271177  ,  1.7804825 , 16.430262  ,
            2.8388941 ,  7.296987  , -1.6074306 , 12.282716  ,
            2.0157857 ,  2.534751  , 16.4007    ,  7.444105  ,
           -1.2791033 ,  5.60878   , -0.60923654, 19.528364  ,
           11.432778  ,  6.325898  ,  3.3752327 , -1.7349824 ]]]]],
      dtype=float32)>, 'state_block0_layer0_pool_frame_count': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>, 'state_block1_layer0_pool_buffer': <tf.Tensor: shape=(1, 1, 1, 1, 80), dtype=float32, numpy=
...
...
...
Exception ignored in: <function _CheckpointRestoreCoordinatorDeleter.__del__ at 0x7f5ed4e00160>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/action-py38/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py", line 174, in __del__
TypeError: 'NoneType' object is not callable
```

Same thing happens when running the Streaming Models example..

**Comment by sineeli** [comment]
Hi @feckpown,

In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 
Thanks!
