### ISSUE TITLE
How to run a simple test for model training

### ISSUE THREAD

**Issue by springile** [tensorflow/models#10510]
Hi 

I use tensorflow 2.8, code for object dectection is the lastest.

With tf2_training_and_evaluation.md, I'like to do a simple test for model training.

```bash
# From the tensorflow/models/research/ directory
PIPELINE_CONFIG_PATH={path to pipeline config file}
MODEL_DIR={path to model directory}
python object_detection/model_main_tf2.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --alsologtostderr
```

The config file I use is :`/models/research/object_detection/samples/configs/faster_rcnn_resnet152_pets.config

I got this error:

Traceback (most recent call last):
  File "object_detection/model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "/home/qube2/someai/tensorflow/tf2_api_env/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/qube2/someai/tensorflow/tf2_api_env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/qube2/someai/tensorflow/tf2_api_env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main_tf2.py", line 112, in main
    record_summaries=FLAGS.record_summaries)
  File "/home/qube2/someai/code/models/research/object_detection/model_lib_v2.py", line 530, in train_loop
    raise ValueError('train_pb2.load_all_detection_checkpoint_vars '
ValueError: train_pb2.load_all_detection_checkpoint_vars unsupported in TF2

Please help.

John.

**Comment by kumariko** [comment]
@[springile](https://github.com/springile) Could you please refer this [link1](https://stackoverflow.com/questions/48795950/tensorflowobject-detection-valueerror-when-try-to-train-with-num-clones-2) , [link2](https://stackoverflow.com/questions/55238397/tensorflow-object-detection-train-config-file-error) and let us know if it helps .Thanks!
