### ISSUE TITLE
UnicodeDecodeError related to the file path encoding on Windows 10

### ISSUE THREAD

**Issue by NickBear-star** [tensorflow/models#10541]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/research/object_detection/model_main_tf2.py

## 2. Describe the bug

I cannot use the script `model_main_tf2.py` on Windows.  The Windows file paths do not seem to be encoded correctly, The use of `model_main_tf2.py` systematically ends with the following error:

```
...
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(compat.path_to_str(self.__name), 1024 * 512)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 132: invalid continuation byte
```

## 3. Steps to reproduce
I just run the following command after modification of the file paths in `pipeline.config`
`python model_main_tf2.py --model_dir=C:\Users\JohnDoe\tmp\model\ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8 --pipeline_config_path=C:\Users\JohnDoe\tmp\model\ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8\pipeline.config`

Then the following error is issued:
```
...
Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "workflow/model_main_tf2.py", line 106, in main
    model_lib_v2.train_loop(
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\object_detection\model_lib_v2.py", line 617, in train_loop
    manager = tf.compat.v2.train.CheckpointManager(
  File "C:\Users\IDC1110\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 637, in __init__
    recovered_state = get_checkpoint_state(directory)
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 275, in get_checkpoint_state
    file_content = file_io.read_file_to_string(
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 356, in read_file_to_string
    return f.read()
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 121, in read
    self._preread_check()
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(compat.path_to_str(self.__name), 1024 * 512)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 132: invalid continuation byte
```
## 4. Expected behavior

I expect at least an error message if Windows path are not taken into account, or a help message explaining how to format correctly a Windows path.

## 6. System information

I am using the following configuration
- Windows 10 Pro
- keras 2.8.0
- keras-preprocessing 1.1.2
- tensorboard 2.8.0
- tensorflow 2.8.0 (from Pip)
- tensorflow-addons 0.16.1
- tensorflow-estimator 2.3.0
- tensorflow-io 0.24.0
- tensorflow-io-gcs-filesystem 0.24.0
- tensorflow-metadata 1.7.0
- tensorflow-model-optimization 0.7.1
- pycocotools-windows 2.0.0.2
- python 3.8.12
- no GPU

```
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
2022-03-17 15:23:48.814418: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-03-17 15:23:48.814573: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
v2.8.0-rc1-32-g3f878cff5b6 2.8.0
```

**Comment by NickBear-star** [comment]
The function `compat.path_to_str(self.__name)` return a `str` object as expected. Precisely, it returns:

`C:/Users/JohnDoe/tmp/model/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8\checkpoint`

This correspond to `--model_dir` value + `\checkpoint`. Hence, the issue seems to come from `_pywrap_file_io.BufferedInputStream()`

**Comment by NickBear-star** [comment]
I finally figures out what happened. The path specified by the `--model_dir` option was the same than the path specified by the `fine_tune_checkpoint` variable in `pipeline.config`. The input checkpoint must be in a different directory thant the output one. I suggest to change the validation steps for the file paths in general, in order to get more specific error message.
