### ISSUE TITLE
hi can u help me

### ISSUE THREAD

**Issue by rezah1369** [tensorflow/models#10554]
i have problem about TF:
i run:
!rm -rf /content/output
!python -m object_detection.model_main
pipeline_config_path= '/content/data/pipeline.config'
model_dir= '/content/checkpoint/model.ckpt.data-00000-of-00001'
num_train_steps=5000
num_eval_steps=100

my error:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/models/research/object_detection/model_main.py", line 108, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/model_main.py", line 70, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "/content/models/research/object_detection/model_lib.py", line 789, in create_estimator_and_inputs
    pipeline_config_path, config_override=config_override)
  File "/content/models/research/object_detection/utils/config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/util/compat.py", line 71, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sushreebarsa** [comment]
@rezah1369 
In order to expedite the trouble-shooting process, could you please provide the entire URL of the repository which you are using. Please provide more details on the issue reported here.Thanks!
