### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.compat.v2.summary' has no attribute 'image'

### ISSUE THREAD

**Issue by NickBear-star** [tensorflow/models#10568]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using
I am using this script:
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

with this model:
http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz

And this dataset:
https://www.kaggle.com/datasets/valentynsichkar/traffic-signs-dataset-in-yolo-format

## 2. Describe the bug

When running `model_main_tf2.py` with SSD-Resnet50, after preprocessing my data into TF records, the training ends with an `AttributeError`: `module 'tensorflow._api.v2.compat.v2.summary' has no attribute 'image'`.

```Python
2022-03-29 14:17:56.091656: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-03-29 14:17:56.092988: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
[...]
INFO:tensorflow:Reading unweighted datasets: ['C:\\Users\\JohnDoe\\tmp\\data\\training\\training_0001-of-0007.tfrecord']
I0329 14:18:07.133054  3940 dataset_builder.py:163] Reading unweighted datasets: ['C:\\Users\\JohnDoe\\tmp\\data\\training\\training_0001-of-0007.tfrecord']
INFO:tensorflow:Reading record datasets for input file: ['C:\\Users\\JohnDoe\\tmp\\data\\training\\training_0001-of-0007.tfrecord']
I0329 14:18:07.136150  3940 dataset_builder.py:80] Reading record datasets for input file: ['C:\\Users\\JohnDoe\\tmp\\data\\training\\training_0001-of-0007.tfrecord']
INFO:tensorflow:Number of filenames to read: 1
I0329 14:18:07.136150  3940 dataset_builder.py:81] Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0329 14:18:07.136150  3940 dataset_builder.py:87] num_readers has been reduced to 1 to match input file shards.
[...]
Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 106, in main
    model_lib_v2.train_loop(
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\object_detection\model_lib_v2.py", line 685, in train_loop
    losses_dict = _dist_train_step(train_input_iter)
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\object_detection\model_lib_v2.py", line 669, in _dist_train_step  *
        _sample_and_train(strategy, train_step_fn, data_iterator)
    File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\object_detection\model_lib_v2.py", line 651, in _sample_and_train  *
        per_replica_losses_dict = strategy.run(
    File "C:\Users\JohnDoe\Anaconda3\envs\tfenv\lib\site-packages\object_detection\model_lib_v2.py", line 630, in train_step_fn  *
        tf.compat.v2.summary.image(

    AttributeError: module 'tensorflow._api.v2.compat.v2.summary' has no attribute 'image' 
```

## 3. Steps to reproduce

```
model_main_tf2.py
--model_dir="C:\\Users\\JohnDoe\\tmp\\models\\trained\\ssd_resnet50_v1_fpn_640x640_coco17_tpu-8"
--pipeline_config_path="C:\\Users\\JohnDoe\\tmp\\models\\trained\\ssd_resnet50_v1_fpn_640x640_coco17_tpu-8\\pipeline.config"
--alsologtostderr
```

## 4. Expected behavior

A training proceeding normally

## 5. Additional context

The training data are splitted in several shards, but I am only using 1 of them for the moment.

## 6. System information

- OS Platform and Distribution: Windows 10 Pro + an Anaconda environment (conda 4.11.0)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow 2.8.0 (pypi)
- Python version: python 3.8.12
- CUDA/cuDNN version: None
- GPU model and memory: None

Conda list extract:
- keras 2.8.0
- keras-preprocessing 1.1.2
- proto-plus 1.20.3
- protobuf 3.19.1
- tensorboard 2.8.0
- tensorboard-data-server 0.6.1
- tensorboard-plugin-wit 1.8.1
- tensorflow 2.8.0
- tensorflow-addons 0.16.1
- tensorflow-datasets 4.5.2
- tensorflow-estimator 2.3.0
- tensorflow-io 0.24.0
- tensorflow-io-gcs-filesystem 0.24.0
- tensorflow-metadata 1.7.0
- tensorflow-model-optimization 0.7.1
- tensorflow-text 2.8.1

**Comment by NickBear-star** [comment]
The tf.summary API is not exhaustive. It lacks several methods described in the [doc](https://www.tensorflow.org/api_docs/python/tf/summary), like `scalar()` or `image()`.
```Python
>>> import tensorflow as tf
2022-03-30 09:09:03.938282: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-03-30 09:09:03.939342: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\IDC1110\Anaconda3\envs\tfenv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\IDC1110\Anaconda3\envs\tfenv\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\IDC1110\Anaconda3\envs\tfenv\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
>>> print(tf.__version__)
2.8.0
>>> tf.summary.scalar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow._api.v2.summary' has no attribute 'scalar'
>>> dir(tf.summary)
['SummaryWriter', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'create_file_writer', 'create_noop_writer', 'experimental', 'flush', 'graph', 'record_if', 'should_record_summaries', 'trace_export', 'trace_off', 'trace_on', 'write']
```

Furhtermore, there is a warning about a missing Tensorboard installation, while it is present in the environment:
```Python
>>> import tensorboard
>>> tensorboard
<module 'tensorboard' (namespace)>
>>> dir(tensorboard)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'summary']
>>>
```
