### ISSUE TITLE
Cannot run inference on previously woking CenterNet-ResNet50-FPN model

### ISSUE THREAD

**Issue by Neathle** [tensorflow/models#10594]
I am testing various models in the detection zoo and I trained them last summer. When trying to run inference now, the following error appears. The rest of the models work fine, including CenterNet-MobileNetV2-FPN.

### Versions
- Tensorflow: 2.8.0
- tfslim: 1.1.0
- CUDA: 11.2
- cuDNN: 8.1.1
- OS: Windows 11 (10.0.22000)

### Error trace
Note that D:\tensorflow is the working directory and \tf is where the environment is located
```
[info] Building model
2022-04-17 20:28:13.543027: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-17 20:28:13.975109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9621 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:09:00.0, compute capability: 8.6
[info] Restoring checkpoint
[debug] Running inference on color_00000001.jpg
2022-04-17 20:28:19.994587: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
2022-04-17 20:28:22.795192: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:675 : INVALID_ARGUMENT: input depth must be evenly divisible by filter depth: 2 vs 256
[info] Running inference Traceback (most recent call last):
  File "d:/tensorflow/models/performance_test.py", line 125, in <module>
    detections, predictions_dict, shapes = detect_fn(input_tensor)
  File "D:\tensorflow\tf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\tensorflow\tf\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'center_0/conv2d_3/Conv2D' defined at (most recent call last):
    File "d:/tensorflow/models/performance_test.py", line 125, in <module>
      detections, predictions_dict, shapes = detect_fn(input_tensor)
    File "d:/tensorflow/models/performance_test.py", line 48, in detect_fn
      prediction_dict = model.predict(image, shapes)
    File "D:\tensorflow\tf\lib\site-packages\object_detection\meta_architectures\center_net_meta_arch.py", line 3897, in predict
      for head_name, heads in self._prediction_head_dict.items():
    File "D:\tensorflow\tf\lib\site-packages\object_detection\meta_architectures\center_net_meta_arch.py", line 3898, in predict
      predictions[head_name] = [
    File "D:\tensorflow\tf\lib\site-packages\object_detection\meta_architectures\center_net_meta_arch.py", line 3898, in predict
      predictions[head_name] = [
    File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "D:\tensorflow\tf\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "D:\tensorflow\tf\lib\site-packages\keras\engine\sequential.py", line 374, in call
      return super(Sequential, self).call(inputs, training=training, mask=mask)
    File "D:\tensorflow\tf\lib\site-packages\keras\engine\functional.py", line 451, in call
      return self._run_internal_graph(
    File "D:\tensorflow\tf\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "D:\tensorflow\tf\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "D:\tensorflow\tf\lib\site-packages\keras\layers\convolutional.py", line 248, in call
      outputs = self.convolution_op(inputs, self.kernel)
    File "D:\tensorflow\tf\lib\site-packages\keras\layers\convolutional.py", line 233, in convolution_op
      return tf.nn.convolution(
Node: 'center_0/conv2d_3/Conv2D'
input depth must be evenly divisible by filter depth: 2 vs 256
         [[{{node center_0/conv2d_3/Conv2D}}]] [Op:__inference_detect_fn_8325]
Exception ignored in: <function _CheckpointRestoreCoordinatorDeleter.__del__ at 0x00000257FA81B0D0>
Traceback (most recent call last):
  File "D:\tensorflow\tf\lib\site-packages\tensorflow\python\training\tracking\util.py", line 174, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by pindinagesh** [comment]
Hi @Neathle 

Can you share the standalone code to reproduce the issue from our end? Thanks!

**Comment by Neathle** [comment]
Apparently the same architecture downloaded from the zoo works correctly so there must be some kind of corruption to the model, i will try to reconstruct it from the last checkpoint

**Comment by santhoshnumberone** [comment]
> I am testing various models in the detection zoo and I trained them last summer. When trying to run inference now, the following error appears. The rest of the models work fine, including CenterNet-MobileNetV2-FPN.
> 
> ### Versions
> * Tensorflow: 2.8.0
> * tfslim: 1.1.0
> * CUDA: 11.2
> * cuDNN: 8.1.1
> * OS: Windows 11 (10.0.22000)
> 
> ### Error trace
> Note that D:\tensorflow is the working directory and \tf is where the environment is located
> 
> ```
> [info] Building model
> 2022-04-17 20:28:13.543027: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2022-04-17 20:28:13.975109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9621 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:09:00.0, compute capability: 8.6
> [info] Restoring checkpoint
> [debug] Running inference on color_00000001.jpg
> 2022-04-17 20:28:19.994587: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
> 2022-04-17 20:28:22.795192: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:675 : INVALID_ARGUMENT: input depth must be evenly divisible by filter depth: 2 vs 256
> [info] Running inference Traceback (most recent call last):
>   File "d:/tensorflow/models/performance_test.py", line 125, in <module>
>     detections, predictions_dict, shapes = detect_fn(input_tensor)
>   File "D:\tensorflow\tf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File "D:\tensorflow\tf\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
>     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:
> 
> Detected at node 'center_0/conv2d_3/Conv2D' defined at (most recent call last):
>     File "d:/tensorflow/models/performance_test.py", line 125, in <module>
>       detections, predictions_dict, shapes = detect_fn(input_tensor)
>     File "d:/tensorflow/models/performance_test.py", line 48, in detect_fn
>       prediction_dict = model.predict(image, shapes)
>     File "D:\tensorflow\tf\lib\site-packages\object_detection\meta_architectures\center_net_meta_arch.py", line 3897, in predict
>       for head_name, heads in self._prediction_head_dict.items():
>     File "D:\tensorflow\tf\lib\site-packages\object_detection\meta_architectures\center_net_meta_arch.py", line 3898, in predict
>       predictions[head_name] = [
>     File "D:\tensorflow\tf\lib\site-packages\object_detection\meta_architectures\center_net_meta_arch.py", line 3898, in predict
>       predictions[head_name] = [
>     File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>       return fn(*args, **kwargs)
>     File "D:\tensorflow\tf\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
>       outputs = call_fn(inputs, *args, **kwargs)
>     File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>       return fn(*args, **kwargs)
>     File "D:\tensorflow\tf\lib\site-packages\keras\engine\sequential.py", line 374, in call
>       return super(Sequential, self).call(inputs, training=training, mask=mask)
>     File "D:\tensorflow\tf\lib\site-packages\keras\engine\functional.py", line 451, in call
>       return self._run_internal_graph(
>     File "D:\tensorflow\tf\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
>       outputs = node.layer(*args, **kwargs)
>     File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>       return fn(*args, **kwargs)
>     File "D:\tensorflow\tf\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
>       outputs = call_fn(inputs, *args, **kwargs)
>     File "D:\tensorflow\tf\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>       return fn(*args, **kwargs)
>     File "D:\tensorflow\tf\lib\site-packages\keras\layers\convolutional.py", line 248, in call
>       outputs = self.convolution_op(inputs, self.kernel)
>     File "D:\tensorflow\tf\lib\site-packages\keras\layers\convolutional.py", line 233, in convolution_op
>       return tf.nn.convolution(
> Node: 'center_0/conv2d_3/Conv2D'
> input depth must be evenly divisible by filter depth: 2 vs 256
>          [[{{node center_0/conv2d_3/Conv2D}}]] [Op:__inference_detect_fn_8325]
> Exception ignored in: <function _CheckpointRestoreCoordinatorDeleter.__del__ at 0x00000257FA81B0D0>
> Traceback (most recent call last):
>   File "D:\tensorflow\tf\lib\site-packages\tensorflow\python\training\tracking\util.py", line 174, in __del__
> TypeError: 'NoneType' object is not callable
> ```

Check this link out [TensorFlow Hub Object Detection Colab](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_object_detection.ipynb#scrollTo=-y9R0Xllefec) I just ran it, works without any error. You can run any model you want

**Comment by jvishnuvardhan** [comment]
@Neathle Is this still an issue for you? Can you please share a simple standalone code to reproduce the issue.  If this is not an issue, please close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
I think this was resolved with recent TF versions. I have tried couple of other OD models and didn't face any error.

If you still have an issue, please feel free to reopen and share a simple standalone code to reproduce the issue. thanks!
