### ISSUE TITLE
slim\datasets\dataset_utils.py decode failing on reading text file

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/models#1061]
Windows 10/64, Python 3.5/64, TF 0.12.1

## Please let us know which model this issue is about (specify the top-level directory)
models/slim/datasets/dataset_utils.py

Line 128 
127  with tf.gfile.Open(labels_filename, 'r') as f:
128    lines = f.read().decode()

If I remove .decode from line 128 the labels.txt is read correctly.  lines=f.read()

Leaving .decode() casues the following stack trace .. last few lines shown

  File "lib\tensorflow_models\slim\datasets\imagenet.py", line 181, in get_split
    labels_to_names = dataset_utils.read_label_file(dataset_dir)
  File "lib\tensorflow_models\slim\datasets\dataset_utils.py", line 129, in read_label_file
    lines = f.read().decode()
  File "G:\p\p\lib\python\lib\bdb.py", line 54, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "G:\p\p\lib\python\lib\bdb.py", line 110, in dispatch_exception
    if self.quitting: raise BdbQuit

**Comment by tatatodd** [comment]
@apiszcz Can you try this with TF 1.0, to see if it's fixed?  Thanks!

**Comment by apiszcz** [comment]
This issue is with the library tensorflow models distribution/package
https://github.com/tensorflow/models
I do not see dataset_utils.py in tensorflow 1.0, and the last change to models was 5 months, I pulled the package in the last week.
dataset_utils.py	added python3 support to read_label_file	5 months ago

**Comment by tatatodd** [comment]
Yes, but the `tf.gfile.Open` call invokes TensorFlow.  Can you try this with TF 1.0?

**Comment by apiszcz** [comment]
Here is the latest (error still occurs), thank you for investigating this.
TF 0.12.1: error
TF 1.0.0.rc2: error
TF 1.0.0 error, (as of 3/3/2017, build #101)

(Pdb) tf.__version__
'1.0.0-rc2'
(Pdb) tf.__version__
'1.0.0'

(Pdb) c
Traceback (most recent call last):
  File "lib\_tf\train_image_classifier.py", line 35, in <module>
    from datasets import dataset_factory
  File "lib\tensorflow_gpu_100\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "lib\_tf\train_image_classifier.py", line 426, in main
    FLAGS.dataset_name, FLAGS.dataset_split_name, FLAGS.dataset_dir)
  File "lib\tensorflow_models\slim\datasets\dataset_factory.py", line 57, in get_dataset
    reader)
  File "lib\tensorflow_models\slim\datasets\imagenet.py", line 181, in get_split
    labels_to_names = dataset_utils.read_label_file(dataset_dir)
  File "lib\tensorflow_models\slim\datasets\dataset_utils.py", line 129, in read_label_file
    lines = f.read().decode()
AttributeError: 'str' object has no attribute 'decode'

**Comment by foromer4** [comment]
encountered the same issue, any news on this one?

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
