### ISSUE TITLE
TypeError: Since we are restoring a v2 style checkpoint restore_map was expected to return a (str -> Model) mapping, but we received a (str -> CheckpointV1) mapping instead.

### ISSUE THREAD

**Issue by naman720** [tensorflow/models#10613]
'''
Traceback (most recent call last):
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\91620\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\91620\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\91620\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 111, in main
    record_summaries=FLAGS.record_summaries)
  File "C:\Users\91620\Desktop\sign language recognition system\RealTimeObjectDetection\Tensorflow\models\research\object_detection\model_lib_v2.py", line 587, in train_loop
    train_input, unpad_groundtruth_tensors)
  File "C:\Users\91620\Desktop\sign language recognition system\RealTimeObjectDetection\Tensorflow\models\research\object_detection\model_lib_v2.py", line 388, in load_fine_tune_checkpoint
    validate_tf_v2_checkpoint_restore_map(restore_from_objects_dict)
  File "C:\Users\91620\Desktop\sign language recognition system\RealTimeObjectDetection\Tensorflow\models\research\object_detection\model_lib_v2.py", line 338, in validate_tf_v2_checkpoint_restore_map
    value.__class__.__name__))
TypeError: Since we are restoring a v2 style checkpoint restore_map was expected to return a (str -> Model) mapping, but we received a (str -> CheckpointV1) mapping instead.

'''

I am getting this type error when i am trying to run my code to train my model. 
I am using tensorflow 2.3.1
I am using [this ](https://www.youtube.com/watch?v=V0Pk_dPU2lY) video as a reference

Can anyone tell me what the issue is here?

**Comment by ttttf** [comment]
I am using tensorflow 2.8.0
I modified the code in file ' Lib\site-packages\tensorflow\_api\v2\compat\v1\train\_init_.py'
from  'from tensorflow.python.training.tracking.util import CheckpointV1 as Checkpoint' to
'from tensorflow.python.training.tracking.util import Checkpoint as Checkpoint'
And it worked

**Comment by sushreebarsa** [comment]
@naman720 We see that you are using an older version of TF which is not actively supported .Could you please try to upgrade to the latest versions of TF and let us know if it is still an issue? Please refer to the [comment](https://github.com/tensorflow/models/issues/10613#issuecomment-1114361268) above as well and let us know if it helps?Thanks!

**Comment by naman720** [comment]
thanks, the problem was resolved.

**Comment by ranjitsachin** [comment]
I'm facing the same issue and following this: Installation: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html

And using CPU. Please help me

**Comment by sushreebarsa** [comment]
@ranjitsachin Could you please create a new issue with relevant information to get the right help?
Thank you!

**Comment by ranjitsachin** [comment]
Created here: https://github.com/tensorflow/models/issues/11067
Please do the needful
