### ISSUE TITLE
Python Streamlit Deployment: "tensorflow.python.framework.errors_impl.OpError: not an sstable (bad magic number)" Error

### ISSUE THREAD

**Issue by pinzhi000** [tensorflow/models#10630]
I am trying to deploy a streamlit app that uses a tensorflow model.  **The webapp is working properly on my local host** but when I try to deploy it on Streamlit cloud I get the following errror: **tensorflow.python.framework.errors_impl.OpError: not an sstable (bad magic number)**

```
Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/scriptrunner/script_runner.py", line 443, in _run_script

    exec(code, module.__dict__)

  File "/app/resp_db/rsd_app.py", line 159, in <module>

    model = tensorflow.keras.models.load_model('./saved_model')

  File "/home/appuser/venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler

    raise e.with_traceback(filtered_tb) from None

  File "/home/appuser/venv/lib/python3.9/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 45, in error_translator

    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)

tensorflow.python.framework.errors_impl.OpError: not an sstable (bad magic number)


And on my app itself I see this error message: 
![image](https://user-images.githubusercontent.com/7343257/167662865-69b5909b-f955-47d2-a569-1331faead8f4.png)


```

**Comment by pindinagesh** [comment]
Hi @pinzhi000 

Can you please take a look at the workaround proposed for a similar [issue](https://github.com/tensorflow/models/issues/2675). Hope this helps. Thanks!
