### ISSUE TITLE
while training the model im getting an error

### ISSUE THREAD

**Issue by Naveentm16** [tensorflow/models#10642]
python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config

error: 
  Traceback (most recent call last):
  File "model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 111, in main
    record_summaries=FLAGS.record_summaries)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\object_detection\model_lib_v2.py", line 604, in train_loop
    model_dir)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\object_detection\utils\variables_helper.py", line 213, in ensure_checkpoint_supported
    variables = tf.train.list_variables(checkpoint_path)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 109, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 64, in load_checkpoint
    return py_checkpoint_reader.NewCheckpointReader(filename)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 96, in NewCheckpointReader
    error_translator(e)
  File "C:\Users\lenovo\anaconda3\envs\db\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for pre-trained-models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint/ckpt-0

**Comment by sharozhaseeb** [comment]
your checkpoint may be corrupted, try downloading it again

**Comment by jvishnuvardhan** [comment]
@Naveentm16 Can you please share a simple standalone code to reproduce the error? As mentioned by @sharozhaseeb, can you please check your chekpoints? Is that location (`pre-trained-models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint/ckpt-0`) correct? Thanks!
