### ISSUE TITLE
run the evaluation script: AttributeError: 'module' object has no attribute 'merge_all_summaries'

### ISSUE THREAD

**Issue by hoL1day** [tensorflow/models#1066]
I run the evaluation script at /home/common/tool/tensorflow/models/im2txt. PS. my evaluation script are made by myself because I can't find anything look like that in the folder. And my training script and TensorBoard server run well.
But when i run the evaluation script, I got the error below:
`Traceback (most recent call last):
  File "/home/common/tool/tensorflow/models/im2txt/bazel-bin/im2txt/evaluate.runfiles/im2txt/im2txt/evaluate.py", line 198, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/common/tool/tensorflow/models/im2txt/bazel-bin/im2txt/evaluate.runfiles/im2txt/im2txt/evaluate.py", line 194, in main
    run()
  File "/home/common/tool/tensorflow/models/im2txt/bazel-bin/im2txt/evaluate.runfiles/im2txt/im2txt/evaluate.py", line 174, in run
    summary_op = tf.merge_all_summaries()
AttributeError: 'module' object has no attribute 'merge_all_summaries'
`
What can I do for this?

**Comment by sh0rtfuse** [comment]
merge_all_summaries has been deprecated as of 11/30/16

https://www.tensorflow.org/api_docs/python/tf/contrib/deprecated/merge_all_summaries

Use `tf.contrib.deprecated.merge_all_summaries` to maintain compatibility or switch to `tf.summary.merge_all`
