### ISSUE TITLE
[rnn/translate] Model Saver Error

### ISSUE THREAD

**Issue by richardxiong** [tensorflow/models#1070]
## models/tutorials/rnn/translate/

Hello everyone,

I'm training a translation model of my own and run into an error when saving the model parameters:

global step 100 learning rate 0.5000 step-time 2.07 perplexity 64.79
Traceback (most recent call last):
  File "translate.py", line 298, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "translate.py", line 295, in main
    train()
  File "translate.py", line 204, in train
    model.saver.save(sess, checkpoint_path, global_step=model.global_step)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1365, in save
    "Parent directory of {} doesn't exist, can't save.".format(save_path))
ValueError: Parent directory of ./train2/translate.ckpt doesn't exist, can't save.

I didn't change any code related here. The train_dir I'm using is './train2/'. Does anyone have any ideas? Thanks!

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
