### ISSUE TITLE
Error on training model

### ISSUE THREAD

**Issue by Samu-K** [tensorflow/models#10715]
When trying to run object_detection/model_main_tf2.py with command 

`python3 tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=tensorflow/workspace/models/cmod --pipeline_config=tensorflow/workspace/cmod/pipeline.config --num_train_steps=2000  `

I get error:
`Traceback (most recent call last):
  File "/Users/SamuK/Documents/Coding/Home office control/tensorflow/models/research/object_detection/model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "/Users/SamuK/Documents/Coding/Home office control/office_control/lib/python3.9/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/SamuK/Documents/Coding/Home office control/office_control/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/Users/SamuK/Documents/Coding/Home office control/office_control/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/Users/SamuK/Documents/Coding/Home office control/tensorflow/models/research/object_detection/model_main_tf2.py", line 105, in main
    model_lib_v2.train_loop(
  File "/Users/SamuK/Documents/Coding/Home office control/office_control/lib/python3.9/site-packages/object_detection/model_lib_v2.py", line 505, in train_loop
    configs = get_configs_from_pipeline_file(
  File "/Users/SamuK/Documents/Coding/Home office control/office_control/lib/python3.9/site-packages/object_detection/utils/config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/Users/SamuK/Documents/Coding/Home office control/office_control/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 114, in read
    self._preread_check()
  File "/Users/SamuK/Documents/Coding/Home office control/office_control/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 76, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream(filename: str, buffer_size: int, token: tensorflow.python.lib.io._pywrap_file_io.TransactionToken = None)

Invoked with: None, 524288`

System information
- OS: MacOs 12
- TensorFlow version: 2.9.2
- Python version: 3.9.13

Any help?

**Comment by Samu-K** [comment]
Messing around with it I've come to the conclusion it's something to do with tf.compact.path_to_str(). The error line is as follows: 
`self._read_buf = _pywrap_file_io.BufferedInputStream(
          compat.path_to_str(self.__name), 1024 * 256)`
If I replace `combat.path_to_str(self.__name)` with just a written path, the code runs. Until it reaches another point where the same function is used. Any idea on how to replace said function?

**Comment by Samu-K** [comment]
Found the error. Command should be --pipeline_config_path instead of pipeline_config
