### ISSUE TITLE
Unable to train MobileDet with TPU on Google Cloud Vertex AI

### ISSUE THREAD

**Issue by simonecampisi97** [tensorflow/models#10735]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/
https://github.com/tensorflow/models/blob/master/research/object_detection/model_tpu_main.py
https://github.com/tensorflow/models/blob/master/research/object_detection/models/ssd_mobiledet_feature_extractor.py

## 2. Describe the bug

In the past I have always trained mobileDet using google cloud and AI Platform and the TPU, using the seguende command:

```
 gcloud ai-platform jobs submit training `whoami`_object_detection_`date +%s` \
  --staging-bucket=gs://${GCS_BUCKET} \
  --packages=dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,/tmp/pycocotools/pycocotools-2.0.tar.gz \
  --module-name=object_detection.model_tpu_main \
  --runtime-version=1.15 \
  --python-version=3.7 \
  --config tpu_v3.yaml \  
  --region=us-central1 \
  -- \
  --distribution_strategy=tpu \
  --model_dir=gs://${GCS_BUCKET}/training_704_396_100k \
  --pipeline_config_path=gs://${GCS_BUCKET}/data_704_396/pipeline.config
```

where _tpu_v3.yaml_ is:

```
trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  workerType: cloud_tpu
  workerCount: 1
  workerConfig:
    acceleratorConfig:
      type: TPU_V3
      count: 8
```

Now I need to make the migration to Vertex AI, since AI Platform will be deprecated in the ed of September. So I build a docker cointainer with all the necessary packages with the commands reported [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md) , including tensorflow 1.15.5.
The problem is that now, when I try to train the model I get:

```
ValueError: Please provide a TPU Name to connect to.

2022-08-03 10:18:45.404 CEST

workerpool0-0
 raise ValueError('Please provide a TPU Name to connect to.')
2022-08-03 10:18:45.404 CEST

workerpool0-0

 File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/distribute/cluster_resolver/tpu_cluster_resolver.py", line 262, in __init__ (https://console.cloud.google.com/logs/query;query=resource.labels.job_id%3D%224606268999515242496%22%20timestamp%3E%3D%222022-08-03T06:37:36.614043Z%22;timeRange=2022-08-03T05:45:15.819Z%2F2022-08-03T06:45:15.819Z;cursorTimestamp=2022-08-03T06:45:15.818568569Z?authuser=1&project=-mobiledet#:~:text=2022%2D08%2D03%2008%3A42,py%22%2C%20line%2089%2C%20in%20main)

```
I tried also to set the flag --tpu_main=local, but I got:

```

2022-08-02 12:45:41.631 CEST

service
The replica workerpool0-0 exited with a non-zero status of 1. To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=619829274226&resource=ml_job%2Fjob_id%2F4838134011580645376&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%224838134011580645376%22
2022-08-02 12:45:08.286 CEST

workerpool0-0
tensorflow.python.framework.errors_impl.NotFoundError: No session factory registered for the given session options: {target: "local" config: operation_timeout_in_ms: 300000} Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
```

## 3. Steps to reproduce

- Upload in Google Cloud Storage as the images with corresponding annotations as tfrecords. The images are 704x396.
- Dowload and upack from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md the MobileDet model
- Set the pipeline.config of MobileDet
- Upload the config file to google cloud storage
- Build the following Dockerfile and push the container to Artifact Registry:

```
FROM us-docker.pkg.dev/vertex-ai/training/tf-gpu.1-15:latest

ARG DEBIAN_FRONTEND=noninteractive

# Install apt dependencies

RUN apt-get update && apt-get install -y \
    git \
    gpg-agent \
    python3-cairocffi \
    protobuf-compiler \
    python3-pil \
    python3-lxml \
    python3-tk \
    python3-opencv \
    wget

# Installs google cloud sdk, this is mostly for using gsutil to export model.
RUN wget -nv \
    https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz && \
    mkdir /root/tools && \
    tar xvzf google-cloud-sdk.tar.gz -C /root/tools && \
    rm google-cloud-sdk.tar.gz && \
    /root/tools/google-cloud-sdk/install.sh --usage-reporting=false \
        --path-update=false --bash-completion=false \
        --disable-installation-options && \
    rm -rf /root/.config/* && \
    ln -s /root/.config /config && \
    rm -rf /root/tools/google-cloud-sdk/.install/.backup

# Path configuration
ENV PATH $PATH:/root/tools/google-cloud-sdk/bin
# Make sure gsutil will use the default service account
RUN echo '[GoogleCompute]\nservice_account = default' > /etc/boto.cfg

WORKDIR /home/tensorflow

#Copy this code (make sure you are under the ../models/research directory)
COPY . /home/tensorflow/models

WORKDIR /home/tensorflow/models/research


# Compile protobuf configs
RUN protoc object_detection/protos/*.proto --python_out=.

RUN cp object_detection/packages/tf1/setup.py ./
ENV PATH="/home/tensorflow/.local/bin:${PATH}"

RUN python3 -m pip install -U pip
RUN python3 -m pip install .
RUN pip3 install --upgrade google-api-python-client && pip install --upgrade oauth2client

ENTRYPOINT ["python3", "object_detection/model_tpu_main.py"]
```

- Submit a custom Job with the following command:
```
  LOCATION="us-central1"
   JOB_NAME="job_name"
   CONFIG_FILE="config.yaml"

gcloud ai custom-jobs create \
  --region="$LOCATION" \
  --display-name="$JOB_NAME" \
  --config="$CONFIG_FILE"\
```

Where _config.yaml_ is:

```
  workerPoolSpecs:
  replicaCount: 1
  machineSpec:
    machineType:  cloud-tpu
    acceleratorType: TPU_V3
    acceleratorCount: 8
  containerSpec:
    imageUri: image_container_artifact_registry
    args:
      - --distribution_strategy=tpu
      - --model_dir=gs://path_cloud_storage_output_model
      - --pipeline_config_path=gs://path_cloud_storage/pipeline.config
      - --tpu_name=local
```

## 4. Expected behavior

I expected the model to start training, as was the case when I was training with AI Platform.

## 5. Additional context
**WIth**  Flag _--tpu_name=''local"_

```
resource.labels.job_id="4838134011580645376" timestamp>="2022-08-02T10:40:10.722024Z"
Query results
~100 log entries
SEVERITY
TIMESTAMP
SUMMARY
Showing logs for time specified in query. To view more results update your query.
2022-08-02 12:48:12.013 CEST

service
Job failed.
2022-08-02 12:45:41.631 CEST

service
The replica workerpool0-0 exited with a non-zero status of 1. To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=619829274226&resource=ml_job%2Fjob_id%2F4838134011580645376&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%224838134011580645376%22

2022-08-02 12:45:08.286 CEST

workerpool0-0
tensorflow.python.framework.errors_impl.NotFoundError: No session factory registered for the given session options: {target: "local" config: operation_timeout_in_ms: 300000} Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
2022-08-02 12:45:08.286 CEST

workerpool0-0
 self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 699, in __init__
2022-08-02 12:45:08.286 CEST

workerpool0-0
 super(Session, self).__init__(target, graph, config=config)
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1585, in __init__
2022-08-02 12:45:08.286 CEST

workerpool0-0
 cluster_def)) as sess:
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/tpu/tpu_system_metadata.py", line 85, in _query_tpu_system_metadata
2022-08-02 12:45:08.286 CEST

workerpool0-0
 query_topology=self.model_parallelism_enabled))
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 285, in _get_tpu_system_metadata
2022-08-02 12:45:08.286 CEST

workerpool0-0
 metadata = self._get_tpu_system_metadata()
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 360, in num_cores
2022-08-02 12:45:08.286 CEST

workerpool0-0
 num_cores = self.num_cores
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 623, in _validate_tpu_configuration
2022-08-02 12:45:08.286 CEST

workerpool0-0
 self._validate_tpu_configuration()
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 462, in is_running_on_cpu
2022-08-02 12:45:08.286 CEST

workerpool0-0
 if ctx.is_running_on_cpu():
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2901, in _convert_train_steps_to_hooks
2022-08-02 12:45:08.286 CEST

workerpool0-0
 hooks.extend(self._convert_train_steps_to_hooks(steps, max_steps))
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
2022-08-02 12:45:08.286 CEST

workerpool0-0
 saving_listeners=saving_listeners)
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
2022-08-02 12:45:08.286 CEST

workerpool0-0
 raise value
2022-08-02 12:45:08.286 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/six.py", line 719, in reraise
2022-08-02 12:45:08.286 CEST

workerpool0-0
 six.reraise(typ, value, traceback)
2022-08-02 12:45:08.285 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
2022-08-02 12:45:08.285 CEST

workerpool0-0
 rendezvous.raise_errors()
2022-08-02 12:45:08.285 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
2022-08-02 12:45:08.285 CEST

workerpool0-0
 estimator.train(input_fn=train_input_fn, max_steps=train_steps)
2022-08-02 12:45:08.285 CEST

workerpool0-0
 File "object_detection/model_tpu_main.py", line 130, in main
2022-08-02 12:45:08.285 CEST

workerpool0-0
 sys.exit(main(argv))
2022-08-02 12:45:08.285 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
2022-08-02 12:45:08.285 CEST

workerpool0-0
 _run_main(main, args)
2022-08-02 12:45:08.285 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
2022-08-02 12:45:08.285 CEST

workerpool0-0
 _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
2022-08-02 12:45:08.285 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
2022-08-02 12:45:08.285 CEST

workerpool0-0
 tf.app.run()
2022-08-02 12:45:08.285 CEST

workerpool0-0
 File "object_detection/model_tpu_main.py", line 146, in <module>
2022-08-02 12:45:08.285 CEST

workerpool0-0
Traceback (most recent call last):
2022-08-02 12:45:08.282 CEST

workerpool0-0
W0802 10:45:08.282230 140139851130688 error_handling.py:135] Reraising captured error
2022-08-02 12:45:08.282 CEST

workerpool0-0
WARNING:tensorflow:Reraising captured error
2022-08-02 12:45:08.282 CEST

workerpool0-0
I0802 10:45:08.282154 140139851130688 error_handling.py:101] training_loop marked as finished
2022-08-02 12:45:08.282 CEST

workerpool0-0
INFO:tensorflow:training_loop marked as finished
2022-08-02 12:45:08.282 CEST

workerpool0-0
E0802 10:45:08.282033 140139851130688 error_handling.py:75] Error recorded from training_loop: No session factory registered for the given session options: {target: "local" config: operation_timeout_in_ms: 300000} Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
2022-08-02 12:45:08.282 CEST

workerpool0-0
ERROR:tensorflow:Error recorded from training_loop: No session factory registered for the given session options: {target: "local" config: operation_timeout_in_ms: 300000} Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
2022-08-02 12:45:08.282 CEST

workerpool0-0
2022-08-02 10:45:08.281922: E tensorflow/core/common_runtime/session.cc:89] Not found: No session factory registered for the given session options: {target: "local" config: operation_timeout_in_ms: 300000} Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
2022-08-02 12:45:08.281 CEST

workerpool0-0
I0802 10:45:08.281213 140139851130688 tpu_system_metadata.py:78] Querying Tensorflow master (local) for TPU system metadata.
2022-08-02 12:45:08.281 CEST

workerpool0-0
INFO:tensorflow:Querying Tensorflow master (local) for TPU system metadata.
2022-08-02 12:45:08.068 CEST

workerpool0-0
I0802 10:45:08.067925 140139851130688 config_util.py:254] Writing pipeline config file to gs://
data-bucket/mobiledet_vertex_ai_100k/pipeline.config
2022-08-02 12:45:08.068 CEST

workerpool0-0
INFO:tensorflow:Writing pipeline config file to gs://data-bucket/mobiledet_vertex_ai_100k/pipeline.config
2022-08-02 12:45:07.988 CEST

workerpool0-0
I0802 10:45:07.988006 140139851130688 tpu_context.py:220] _TPUContext: eval_on_tpu False
2022-08-02 12:45:07.988 CEST

workerpool0-0
INFO:tensorflow:_TPUContext: eval_on_tpu False
2022-08-02 12:45:07.987 CEST

workerpool0-0
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f74856e2898>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'local', '_evaluation_master': 'local', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=2, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
2022-08-02 12:45:07.987 CEST

workerpool0-0
}
2022-08-02 12:45:07.987 CEST

workerpool0-0
 }
2022-08-02 12:45:07.987 CEST

workerpool0-0
 meta_optimizer_iterations: ONE
2022-08-02 12:45:07.987 CEST

workerpool0-0
 rewrite_options {
2022-08-02 12:45:07.987 CEST

workerpool0-0
graph_options {
2022-08-02 12:45:07.987 CEST

workerpool0-0
I0802 10:45:07.987084 140139851130688 estimator.py:212] Using config: {'_model_dir': 'gs://data-bucket/mobiledet_vertex_ai_100k', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
2022-08-02 12:45:07.987 CEST

workerpool0-0
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f74856e2898>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'local', '_evaluation_master': 'local', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=2, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
2022-08-02 12:45:07.987 CEST

workerpool0-0
}
2022-08-02 12:45:07.987 CEST

workerpool0-0
 }
2022-08-02 12:45:07.987 CEST

workerpool0-0
 meta_optimizer_iterations: ONE
2022-08-02 12:45:07.987 CEST

workerpool0-0
 rewrite_options {
2022-08-02 12:45:07.987 CEST

workerpool0-0
graph_options {
2022-08-02 12:45:07.987 CEST

workerpool0-0
INFO:tensorflow:Using config: {'_model_dir': 'gs://data-bucket/mobiledet_vertex_ai_100k', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
2022-08-02 12:45:07.986 CEST

workerpool0-0
2022-08-02 12:45:07.986 CEST

workerpool0-0
W0802 10:45:07.986425 140139851130688 module_wrapper.py:139] From /usr/local/lib/python3.6/dist-packages/object_detection/model_lib.py:896: The name tf.estimator.tpu.TPUEstimator is deprecated. Please use tf.compat.v1.estimator.tpu.TPUEstimator instead.
2022-08-02 12:45:07.986 CEST

workerpool0-0
2022-08-02 12:45:07.986 CEST

workerpool0-0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/object_detection/model_lib.py:896: The name tf.estimator.tpu.TPUEstimator is deprecated. Please use tf.compat.v1.estimator.tpu.TPUEstimator instead.
2022-08-02 12:45:07.986 CEST

workerpool0-0
I0802 10:45:07.986275 140139851130688 model_lib.py:892] create_estimator_and_inputs: use_tpu True, export_to_tpu None
2022-08-02 12:45:07.986 CEST

workerpool0-0
INFO:tensorflow:create_estimator_and_inputs: use_tpu True, export_to_tpu None
2022-08-02 12:45:07.986 CEST

workerpool0-0
W0802 10:45:07.986208 140139851130688 model_lib.py:855] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
2022-08-02 12:45:07.986 CEST

workerpool0-0
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
2022-08-02 12:45:07.986 CEST

workerpool0-0
I0802 10:45:07.986118 140139851130688 config_util.py:552] Maybe overwriting eval_num_epochs: 1
2022-08-02 12:45:07.986 CEST

workerpool0-0
INFO:tensorflow:Maybe overwriting eval_num_epochs: 1
2022-08-02 12:45:07.986 CEST

workerpool0-0
I0802 10:45:07.986043 140139851130688 config_util.py:552] Maybe overwriting sample_1_of_n_eval_examples: 1
2022-08-02 12:45:07.986 CEST

workerpool0-0
INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: 1
2022-08-02 12:45:07.986 CEST

workerpool0-0
I0802 10:45:07.985978 140139851130688 config_util.py:552] Maybe overwriting use_bfloat16: False
2022-08-02 12:45:07.986 CEST

workerpool0-0
INFO:tensorflow:Maybe overwriting use_bfloat16: False
2022-08-02 12:45:07.986 CEST

workerpool0-0
I0802 10:45:07.985922 140139851130688 config_util.py:552] Maybe overwriting train_steps: None
2022-08-02 12:45:07.986 CEST

workerpool0-0
INFO:tensorflow:Maybe overwriting train_steps: None
2022-08-02 12:45:07.986 CEST

workerpool0-0
W0802 10:45:07.985733 140139851130688 model_lib.py:839] Forced number of epochs for all eval validations to be 1.
2022-08-02 12:45:07.986 CEST

workerpool0-0
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
2022-08-02 12:45:07.824 CEST

workerpool0-0
2022-08-02 12:45:07.824 CEST

workerpool0-0
W0802 10:45:07.824181 140139851130688 module_wrapper.py:139] From object_detection/model_tpu_main.py:103: The name tf.estimator.tpu.TPUConfig is deprecated. Please use tf.compat.v1.estimator.tpu.TPUConfig instead.
2022-08-02 12:45:07.824 CEST

workerpool0-0
2022-08-02 12:45:07.824 CEST

workerpool0-0
WARNING:tensorflow:From object_detection/model_tpu_main.py:103: The name tf.estimator.tpu.TPUConfig is deprecated. Please use tf.compat.v1.estimator.tpu.TPUConfig instead.
2022-08-02 12:45:07.824 CEST

workerpool0-0
2022-08-02 12:45:07.824 CEST

workerpool0-0
W0802 10:45:07.823952 140139851130688 module_wrapper.py:139] From object_detection/model_tpu_main.py:99: The name tf.estimator.tpu.RunConfig is deprecated. Please use tf.compat.v1.estimator.tpu.RunConfig instead.
2022-08-02 12:45:07.824 CEST

workerpool0-0
2022-08-02 12:45:07.824 CEST

workerpool0-0
WARNING:tensorflow:From object_detection/model_tpu_main.py:99: The name tf.estimator.tpu.RunConfig is deprecated. Please use tf.compat.v1.estimator.tpu.RunConfig instead.
```

**Without** flag --tpu_name="local"

```
2022-08-03 08:45:15.818 CEST

service
Job failed.
2022-08-03 08:42:45.490 CEST

service
The replica workerpool0-0 exited with a non-zero status of 1. To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=619829274226&resource=ml_job%2Fjob_id%2F4606268999515242496&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%224606268999515242496%22
2022-08-03 08:42:13.917 CEST

workerpool0-0
ValueError: Please provide a TPU Name to connect to.

2022-08-03 08:42:13.917 CEST

workerpool0-0
 raise ValueError('Please provide a TPU Name to connect to.')
2022-08-03 08:42:13.917 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/cluster_resolver/tpu_cluster_resolver.py", line 262, in __init__
2022-08-03 08:42:13.917 CEST

workerpool0-0
 tpu=[FLAGS.tpu_name], zone=FLAGS.tpu_zone, project=FLAGS.gcp_project))
2022-08-03 08:42:13.917 CEST

workerpool0-0
 File "object_detection/model_tpu_main.py", line 89, in main
2022-08-03 08:42:13.917 CEST

workerpool0-0
 sys.exit(main(argv))
2022-08-03 08:42:13.917 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
2022-08-03 08:42:13.917 CEST

workerpool0-0
 _run_main(main, args)
2022-08-03 08:42:13.917 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
2022-08-03 08:42:13.917 CEST

workerpool0-0
 _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
2022-08-03 08:42:13.917 CEST

workerpool0-0
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
2022-08-03 08:42:13.917 CEST

workerpool0-0
 tf.app.run()
2022-08-03 08:42:13.917 CEST

workerpool0-0
 File "object_detection/model_tpu_main.py", line 139, in <module>
2022-08-03 08:42:13.916 CEST

workerpool0-0
Traceback (most recent call last):
2022-08-03 08:40:51.245 CEST

workerpool0-0.gcsfuse
File system has been successfully mounted.
2022-08-03 08:40:51.144 CEST

workerpool0-0.gcsfuse
Mounting file system "gcsfuse"...
2022-08-03 08:40:51.133 CEST

workerpool0-0.gcsfuse
Opening GCS connection...
2022-08-03 08:37:53.753 CEST

aiplatform.googleapis.com

…tform.ui.JobService.DeleteCustomJob

…-central1/customJobs/8976097644203999232

audit_log, method: "google.cloud.aiplatform.ui.JobService.DeleteCustomJob", principal_email: "
2022-08-03 08:37:49.246 CEST

aiplatform.googleapis.com

…tform.ui.JobService.DeleteCustomJob

…-central1/customJobs/2438911678843191296


audit_log, method: "google.cloud.aiplatform.ui.JobService.DeleteCustomJob", principal_email: 
2022-08-03 08:37:36.848 CEST

service
Waiting for job to be provisioned.
2022-08-03 08:37:36.326 CEST

aiplatform.googleapis.com

…tform.v1.JobService.CreateCustomJob

…s/mobiledet/locations/us-central1

2022-08-03 08:36:11.613 CEST

service
Job cancelled.
2022-08-03 08:36:03.441 CEST

aiplatform.googleapis.com

…tform.ui.JobService.CancelCustomJob

…-central1/customJobs/2438911678843191296

2022-08-03 08:36:02.930 CEST

service
Waiting for job to be provisioned.
2022-08-03 08:36:02.916 CEST

service
Job failed.
2022-08-03 08:36:02.581 CEST

service
TPU resources are insufficient in region: us-central1. Please try a different region.
2022-08-03 08:35:32.420 CEST

service
Waiting for job to be provisioned.
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud - Vertex AI
- TensorFlow version (use command below): 1.15.5
- Python version: 3.7

**Comment by saberkun** [comment]
Could you contact Vertex AI team instead?
