### ISSUE TITLE
Training fails with an error regarding CUDA_DIR/nvmm/libdevice path

### ISSUE THREAD

**Issue by ToWelie89** [tensorflow/models#10739]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection

## 2. Describe the bug

I have prepared a model for training and I want to train it, so from the **\models\research\object_detection** folder I run:
```
python model_main_tf2.py --pipeline_config_path=training/ssd_efficientdet_d3_896x896_coco17_tpu-32.config --model_dir=training --alsologtostderr
```

But I get an error:

```
...
WARNING:tensorflow:Gradients do not exist for variables ['stack_6/block_1/expand_bn/gamma:0', 'stack_6/block_1/expand_bn/beta:0', 'stack_6/block_1/depthwise_conv2d/depthwise_kernel:0', 'stack_6/block_1/depthwise_bn/gamma:0', 'stack_6/block_1/depthwise_bn/beta:0', 'stack_6/block_1/project_bn/gamma:0', 'stack_6/block_1/project_bn/beta:0', 'top_bn/gamma:0', 'top_bn/beta:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss`argument?
W0806 05:39:18.533181 17152 utils.py:76] Gradients do not exist for variables ['stack_6/block_1/expand_bn/gamma:0', 'stack_6/block_1/expand_bn/beta:0', 'stack_6/block_1/depthwise_conv2d/depthwise_kernel:0', 'stack_6/block_1/depthwise_bn/gamma:0', 'stack_6/block_1/depthwise_bn/beta:0', 'stack_6/block_1/project_bn/gamma:0', 'stack_6/block_1/project_bn/beta:0', 'top_bn/gamma:0', 'top_bn/beta:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss`argument?
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
2022-08-06 05:39:51.571040: W tensorflow/core/framework/op_kernel.cc:1733] UNKNOWN: JIT compilation failed.
Traceback (most recent call last):
  File "C:\Git\models2\research\object_detection\model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Git\models2\research\object_detection\model_main_tf2.py", line 105, in main
    model_lib_v2.train_loop(
  File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\object_detection\model_lib_v2.py", line 685, in train_loop
    losses_dict = _dist_train_step(train_input_iter)
  File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node 'train_input_images/write_summary/mod' defined at (most recent call last):
    File "C:\Users\sones\miniconda3\envs\tflow\lib\threading.py", line 966, in _bootstrap
      self._bootstrap_inner()
    File "C:\Users\sones\miniconda3\envs\tflow\lib\threading.py", line 1009, in _bootstrap_inner
      self.run()
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\object_detection\model_lib_v2.py", line 629, in train_step_fn
      if record_summaries:
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\object_detection\model_lib_v2.py", line 630, in train_step_fn
      tf.compat.v2.summary.image(
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\tensorboard\plugins\image\summary_v2.py", line 141, in image
      tag=tag, tensor=lazy_tensor, step=step, metadata=summary_metadata
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\object_detection\model_lib_v2.py", line 599, in <lambda>
      lambda: global_step % num_steps_per_iteration == 0):
Node: 'train_input_images/write_summary/mod'
Detected at node 'train_input_images/write_summary/mod' defined at (most recent call last):
    File "C:\Users\sones\miniconda3\envs\tflow\lib\threading.py", line 966, in _bootstrap
      self._bootstrap_inner()
    File "C:\Users\sones\miniconda3\envs\tflow\lib\threading.py", line 1009, in _bootstrap_inner
      self.run()
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\object_detection\model_lib_v2.py", line 629, in train_step_fn
      if record_summaries:
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\object_detection\model_lib_v2.py", line 630, in train_step_fn
      tf.compat.v2.summary.image(
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\tensorboard\plugins\image\summary_v2.py", line 141, in image
      tag=tag, tensor=lazy_tensor, step=step, metadata=summary_metadata
    File "C:\Users\sones\miniconda3\envs\tflow\lib\site-packages\object_detection\model_lib_v2.py", line 599, in <lambda>
      lambda: global_step % num_steps_per_iteration == 0):
Node: 'train_input_images/write_summary/mod'
2 root error(s) found.
  (0) UNKNOWN:  JIT compilation failed.
         [[{{node train_input_images/write_summary/mod}}]]
         [[Func/train_input_images/write_summary/summary_cond/then/_1957/input/_7577/_30]]
  (1) UNKNOWN:  JIT compilation failed.
         [[{{node train_input_images/write_summary/mod}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__dist_train_step_142854]
```

I notice that I get the error **error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice**. However I have set the CUDA_DIR environment variable both in Windows and in the conda environment to my correct CUDA install folder.

![image](https://user-images.githubusercontent.com/5618925/183232946-79a8136f-78a0-4b36-a092-260ed33971d6.png)
![image](https://user-images.githubusercontent.com/5618925/183232975-b545d23b-3e90-4256-a70d-27b96ee75332.png)

I can also confirm that the nvmm/libdevice folder exists:

![image](https://user-images.githubusercontent.com/5618925/183233004-4e9c7947-842d-4386-8a04-c8b35cad3b25.png)

## 3. Steps to reproduce

See above

## 4. Expected behavior

That the training begins

## 5. Additional context

I have set the following enviroment variables in both Windows and for the conda environment:

CUDA_PATH = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7
CUDA_PATH_V11_7 = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7
CUDA_DIR = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7

And my PATH contains CUDA:

```
C:\Users\sones\miniconda3\envs\tflow;
C:\Users\sones\miniconda3\envs\tflow\Library\mingw-w64\bin;
C:\Users\sones\miniconda3\envs\tflow\Library\usr\bin;
C:\Users\sones\miniconda3\envs\tflow\Library\bin;
C:\Users\sones\miniconda3\envs\tflow\Scripts;
C:\Users\sones\miniconda3\envs\tflow\bin;
C:\Users\sones\miniconda3\condabin;
C:\Users\sones\miniconda3;
C:\Users\sones\miniconda3\Library\mingw-w64\bin;
C:\Users\sones\miniconda3\Library\usr\bin;
C:\Users\sones\miniconda3\Library\bin;
C:\Users\sones\miniconda3\Scripts;
C:\Users\sones\.windows-build-tools\python27;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp;
C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.2.1;
(etc etc)
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device name if the issue happens on a mobile device: -
- TensorFlow installed from (source or binary): pip (I am using a conda environment)
- TensorFlow version (use command below): v2.9.0-18-gd8ce9f9c301 2.9.1
- Python version: 3.10.4
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: CUDA 11.7.1 cuDNN 8.4.1
- GPU model and memory: RTX 3070, 32 Gb DDR 3600 MHz RAM

**Comment by ToWelie89** [comment]
I solved it.

The variable CUDA_DIR is not an environment variable, so setting it as an environment variable wont solve anything. The solution was to set another environment variable for xla flags.

```
export XLA_FLAGS=--xla_gpu_cuda_data_dir=<PATH_TO_CUDA>
```

Remeber that if you CUDA-path contains spaces then the path should be within quotation marks.

```
export XLA_FLAGS=--xla_gpu_cuda_data_dir="<PATH_TO_CUDA>"
```

**Comment by zk-0604** [comment]
> 
I met the same problem as you. Can you explain your solution more clearly? Thank you very much

**Comment by ToWelie89** [comment]
> 

Find the path for your CUDA directory. For me it is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7

Before running the training script, just enter the following command:
```
export XLA_FLAGS=--xla_gpu_cuda_data_dir="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7"
```
If you are using Windows, replace "export" with "set".

Then you can start training with model_main_tf2.py in the same terminal window. I don't know exactly how it works under the hood, but it seems that that CUDA_DIR can be derived from that flag that I suppose is read and used somewhere along the training process. For me it solved the issue, the training then worked, I never saw an error related to CUDA_DIR again.

Just remember that export/set wont save it permanently, for that you need to set it as an environment variable.

**Comment by chunduriv** [comment]
@ToWelie89,

Good to hear that the issue has been resolved. Could you move this issue to close status as it doesn't need further assistance. Thank you.

**Comment by ToWelie89** [comment]
Closing issue. See my solutuion above
