### ISSUE TITLE
Evaluating the Model  { TypeError: 'numpy.float64' object cannot be interpreted as an integer} Tf.29.1 BUG 

### ISSUE THREAD

**Issue by vitorbds** [tensorflow/models#10757]
Using tensorflow 2.9.1 
Docker image : tensorflow/tensorflow:2.9.1-gpu-jupyter

When i try Evaluate my model using:

python model_main_tf2.py --model_dir=my_model--pipeline_config_path=pipeline.config --checkpoint_dir='my_model__check_path'

I get the folow error

[INFO:tensorflow:Finished eval step 100
I0830 17:44:34.779616 140073014974272 model_lib_v2.py:966] Finished eval step 100
INFO:tensorflow:Finished eval step 200
I0830 17:44:43.103840 140073014974272 model_lib_v2.py:966] Finished eval step 200
INFO:tensorflow:Finished eval step 300
I0830 17:44:51.505225 140073014974272 model_lib_v2.py:966] Finished eval step 300
INFO:tensorflow:Finished eval step 400
I0830 17:45:00.095398 140073014974272 model_lib_v2.py:966] Finished eval step 400
INFO:tensorflow:Finished eval step 500
I0830 17:45:08.159903 140073014974272 model_lib_v2.py:966] Finished eval step 500
INFO:tensorflow:Finished eval step 600
I0830 17:45:16.094892 140073014974272 model_lib_v2.py:966] Finished eval step 600
INFO:tensorflow:Finished eval step 700
I0830 17:45:23.770599 140073014974272 model_lib_v2.py:966] Finished eval step 700
INFO:tensorflow:Performing evaluation on 727 images.
I0830 17:45:25.666780 140073014974272 coco_evaluation.py:293] Performing evaluation on 727 images.
creating index...
index created!
INFO:tensorflow:Loading and preparing annotation results...
I0830 17:45:25.675142 140073014974272 coco_tools.py:116] Loading and preparing annotation results...
INFO:tensorflow:DONE (t=0.07s)
I0830 17:45:25.740386 140073014974272 coco_tools.py:138] DONE (t=0.07s)
creating index...
index created!
Traceback (most recent call last):
  File "model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 81, in main
    model_lib_v2.eval_continuously(
  File "/usr/local/lib/python3.8/dist-packages/object_detection/model_lib_v2.py", line 1158, in eval_continuously
    eager_eval_loop(
  File "/usr/local/lib/python3.8/dist-packages/object_detection/model_lib_v2.py", line 1010, in eager_eval_loop
    eval_metrics.update(evaluator.evaluate())
  File "/usr/local/lib/python3.8/dist-packages/object_detection/metrics/coco_evaluation.py", line 302, in evaluate
    box_evaluator = coco_tools.COCOEvalWrapper(
  File "/usr/local/lib/python3.8/dist-packages/object_detection/metrics/coco_tools.py", line 207, in __init__
    cocoeval.COCOeval.__init__(self, groundtruth, detections, iouType=iou_type)
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 180, in linspace
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by changtimwu** [comment]
just upgrade the coco tools to a more recent version
```
pip install -U pycocotools
```
