### ISSUE TITLE
[DELF] No module named 'tensorflow.python.checkpoint' bug because of different tf-slim version

### ISSUE THREAD

**Issue by anguoyuan** [tensorflow/models#10754]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [O ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ O ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ O ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training/install_delf.sh

## 2. Describe the bug

Because the default tf-slim version is changed, the following error happens after install_delf.sh.  

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/models/research/delf/delf/__init__.py", line 37, in <module>
    from delf.python.training import model
  File "/root/models/research/delf/delf/python/training/model/__init__.py", line 22, in <module>
    from delf.python.training.model import export_model_utils
  File "/root/models/research/delf/delf/python/training/model/export_model_utils.py", line 27, in <module>
    from object_detection.core import box_list_ops
  File "/root/models/research/object_detection/core/box_list_ops.py", line 34, in <module>
    from object_detection.utils import ops
  File "/root/models/research/object_detection/utils/ops.py", line 28, in <module>
    import tf_slim as slim
  File "/root/anaconda3/lib/python3.9/site-packages/tf_slim/__init__.py", line 43, in <module>
    import tf_slim.evaluation as evaluation
  File "/root/anaconda3/lib/python3.9/site-packages/tf_slim/evaluation.py", line 132, in <module>
    from tf_slim.training import evaluation
  File "/root/anaconda3/lib/python3.9/site-packages/tf_slim/training/evaluation.py", line 143, in <module>
    from tensorflow.python.checkpoint import checkpoint_management
ModuleNotFoundError: No module named 'tensorflow.python.checkpoint'

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 4. Expected behavior

change the line 52 of install_delf.sh from  "git clone \$ {tf_slim_git_repo}" to "git clone -b v1.1.0 ${tf_slim_git_repo}" 

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sushreebarsa** [comment]
@anguoyuan We have raised a PR internally to fix this issue. 
This issue will be closed automatically once the PR is merged. Thank you!
