### ISSUE TITLE
Cannot build/test Object Detection API on macOS M1 

### ISSUE THREAD

**Issue by damian0815** [tensorflow/models#10769]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [*] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [*] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

N/A 

## 2. Describe the bug

I'm following this official guide for getting starting with the Object Detection API with TF2: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

After manually cloning and building tensorflow/io (necessary on macOS/M1 at this point), the only way to get `model_builder_tf2_test.py` to run is to follow the [hack I describe here](https://github.com/tensorflow/models/issues/10429#issuecomment-1241235388) to make `protobuf.internal.builder` available.

## 3. Steps to reproduce

1. Have a Mac with an M1 chip running macOS 12.5.12. 
2. Install `tensorflow-macos` 2.9.2, `tensorflow-metal` 0.5.13. 
3. Follow the Python Package Installation steps in the `Object Detection API with TensorFlow 2` document in this repo (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md). 
* You'll have to manually build and install `tensorflow_io` and `tensorflow_io_gcs_filesystem`.
* Some packages need to be installed with `pip --no-dependencies`.

## 4. Expected behavior

I can successfully install and test the Object Detection API using `python object_detection/builders/model_builder_tf2_test.py`.

Instead, I get the following `ImportError`:
```
python object_detection/builders/model_builder_tf2_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/Users/damian/miniforge3/envs/tensorflow-object-detection-api/lib/python3.8/site-packages/object_detection/builders/model_builder.py", line 23, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/Users/damian/miniforge3/envs/tensorflow-object-detection-api/lib/python3.8/site-packages/object_detection/builders/anchor_generator_builder.py", line 26, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "/Users/damian/miniforge3/envs/tensorflow-object-detection-api/lib/python3.8/site-packages/object_detection/protos/anchor_generator_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/damian/miniforge3/envs/tensorflow-object-detection-api/lib/python3.8/site-packages/google/protobuf/internal/__init__.py)
```

## 5. Additional context

N/A

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.5.2
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow-macos 2.9.2
- Python version: 3.8.13
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Mac M1

**Comment by damian0815** [comment]
see also numerous comments on https://github.com/tensorflow/models/issues/10429
