### ISSUE TITLE
Unable to use combined_nms despite setting change_coordinate_frame to false

### ISSUE THREAD

**Issue by kulkarnivishal** [tensorflow/models#10788]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ Y] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ Y] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the bug

I'm trying to use combined_nms in post_processing and I get 
`ValueError: change_coordinate_frame (normalizing coordinates relative to clip_window) is not supported by combined_nms.`
however change_coordinate_frame is set to false

## 3. Steps to reproduce
Use ssd or frcnn model and 
1. add combined_nms: true 
2. change_coordinate_frame: false
3. try exporter_v2 to export graph or train with above config changes

## 4. Expected behavior
I'd expect the model to export successfully, ValueError is only raised when change_coordinate_frame is true with combined_nms=true

## 5. Additional context
```
Traceback (most recent call last):
  File "object_detection/exporter_main_v2.py", line 164, in <module>
    app.run(main)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "object_detection/exporter_main_v2.py", line 160, in main
    FLAGS.side_input_types, FLAGS.side_input_names)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/object_detection/exporter_lib_v2.py", line 270, in export_inference_graph
    concrete_function = detection_module.__call__.get_concrete_function()
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1264, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1244, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 786, in _initialize
    *args, **kwds))
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2983, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3292, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3140, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3831, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/object_detection/exporter_lib_v2.py", line 189, in __call__  *
        true_shapes)
    File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/object_detection/exporter_lib_v2.py", line 126, in _run_inference_on_images  *
        detections = self._model.postprocess(prediction_dict, true_shapes)
    File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1542, in postprocess  *
        detections_dict = self._postprocess_box_classifier(
    File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 2125, in _postprocess_box_classifier  *
        (nmsed_boxes, nmsed_scores, nmsed_classes, nmsed_masks,
    File "/home/vishal_fortressiq_com/.virtualenvs/tf2py37/lib/python3.7/site-packages/object_detection/core/post_processing.py", line 999, in batch_multiclass_non_max_suppression  *
        raise ValueError(

    ValueError: change_coordinate_frame (normalizing coordinates relative to clip_window) is not supported by combined_nms.
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.3
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2, 8
- GPU model and memory: T4, 15GB

 v2.8.2-130-g92a51d52ad1 2.8.3

**Comment by sushreebarsa** [comment]
@kulkarnivishal 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!
