### ISSUE TITLE
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for efficientdet_d0_coco17_tpu-32\checkpoint/ckpt-0

### ISSUE THREAD

**Issue by faisalahmadnf** [tensorflow/models#10794]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 92, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for efficientdet_d0_coco17_tpu-32\checkpoint/ckpt-0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 111, in main
    record_summaries=FLAGS.record_summaries)
  File "/content/drive/MyDrive/Tensorflow Object Detection/object_detection/object_detection/model_lib_v2.py", line 604, in train_loop
    model_dir)
  File "/content/drive/MyDrive/Tensorflow Object Detection/object_detection/object_detection/utils/variables_helper.py", line 213, in ensure_checkpoint_supported
    variables = tf.train.list_variables(checkpoint_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 115, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 70, in load_checkpoint
    return py_checkpoint_reader.NewCheckpointReader(filename)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 96, in NewCheckpointReader
    error_translator(e)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for efficientdet_d0_coco17_tpu-32\checkpoint/ckpt-0

**Comment by sushreebarsa** [comment]
@faisalahmadnf 
In order to expedite the trouble-shooting process, could you please provide the entire URL of the repository which you are using. Please provide more details on the issue reported here.Thank you!
