### ISSUE TITLE
Non-compatible type annotations

### ISSUE THREAD

**Issue by dh-cmyk** [tensorflow/models#10847]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [+] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [+] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [+] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/modeling/layers/edgetpu.py

## 2. Describe the bug

A type-annotations error similar to [https://github.com/tensorflow/models/issues/10764](url) when run with Python 3.8 and TF 2.10 on Google Cloud TPU VM

` File "/usr/share/tpu2/models/official/vision/modeling/layers/edgetpu.py", line 105, in <module>
    *tensors: tf.Tensor) -> Iterable[Sequence[tf.Tensor]]:
TypeError: 'ABCMeta' object is not subscriptable`

## 3. Steps to reproduce

Run a EdgeTPU Segmentation model

## 4. Expected behavior

Train an EdgeTPU segmentation model

## 5. Additional context
```
python3 train.py --experiment='deeplabv3plus_mobilenet_edgetpuv2_s_welddataset'  --model_dir='gs://weld-bucket/20221130-dlmn-model-dir' --mode=train --tpu=${TPU_NAME} 
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    from official.projects.edgetpu.vision.configs import mobilenet_edgetpu_config
  File "/usr/share/tpu2/models/official/projects/edgetpu/vision/configs/mobilenet_edgetpu_config.py", line 27, in <module>
    from official.vision.configs import common
  File "/usr/share/tpu2/models/official/vision/__init__.py", line 18, in <module>
    from official.vision import tasks
  File "/usr/share/tpu2/models/official/vision/tasks/__init__.py", line 17, in <module>
    from official.vision.tasks.image_classification import ImageClassificationTask
  File "/usr/share/tpu2/models/official/vision/tasks/image_classification.py", line 28, in <module>
    from official.vision.modeling import factory
  File "/usr/share/tpu2/models/official/vision/modeling/__init__.py", line 17, in <module>
    from official.vision.modeling import backbones
  File "/usr/share/tpu2/models/official/vision/modeling/backbones/__init__.py", line 17, in <module>
    from official.vision.modeling.backbones.efficientnet import EfficientNet
  File "/usr/share/tpu2/models/official/vision/modeling/backbones/efficientnet.py", line 27, in <module>
    from official.vision.modeling.layers import nn_blocks
  File "/usr/share/tpu2/models/official/vision/modeling/layers/__init__.py", line 18, in <module>
    from official.vision.modeling.layers.detection_generator import DetectionGenerator
  File "/usr/share/tpu2/models/official/vision/modeling/layers/detection_generator.py", line 21, in <module>
    from official.vision.modeling.layers import edgetpu
  File "/usr/share/tpu2/models/official/vision/modeling/layers/edgetpu.py", line 105, in <module>
    *tensors: tf.Tensor) -> Iterable[Sequence[tf.Tensor]]:
TypeError: 'ABCMeta' object is not subscriptable
D1130 21:47:32.728455371   63601 init.cc:213]                grpc_shutdown starts clean-up now
```
## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud TPU VM (tpu-vm-tf-2.10.0) with TensorFlow 2.10.0 and Python 3.8.10
- TensorFlow installed from (source or binary): Pre-installed
- TensorFlow version (use command below): 2.10.0
- Python version: 3.8.10

**Comment by laxmareddyp** [comment]
Hi @dh-cmyk,

Can you try cloning latest release branch which is 2.11 version and try running the script you are training and we are trying to resolve the issue internally.

please use below branch.

`!git clone https://github.com/tensorflow/models.git`
`!git checkout r2.11`

and let us know if this helps to resolve the issue.

Thanks.

**Comment by dh-cmyk** [comment]
Hi @laxmareddyp,

Thanks for your follow-up. Changing the branch to 2.11 did solve the issue.

Cheers
