### ISSUE TITLE
numpy.core._exceptions.MemoryError: Unable to allocate 4.69 GiB for an array with shape (102400, 64, 64, 3) and data type float32

### ISSUE THREAD

**Issue by 21328739** [tensorflow/models#10877]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

I am reporting the issue to the correct repository. (Model Garden official or research directory). Yes
I checked to make sure that this issue has not already been filed. Yes

- [x] I am using the tensorflow == 2.3.0 **without gpu support**.

## 1. The entire URL of the file you are using

https://gitee.com/cleryer-1/image-denoise-using-wasserstein-gan

This is my modified version of code: https://drive.google.com/drive/folders/1xdRZ5IOnAx_VyhvBB67x19EoDe6CjHUZ?usp=sharing (i only changed image pathways in config.py )

## 2. Describe the bug
I want to denoise images using GAN.
I'm trying to implement same code on my own test and training data which is as follows: 
(http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_LR_bicubic_X2.zip)
(http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_LR_bicubic_X2.zip)
It gave 2 different errors at different times, these are:
**'NoneType' object is not iterable
numpy.core._exceptions.MemoryError: Unable to allocate 4.69 GiB for an array with shape (102400, 64, 64, 3) and data type float32.**

I also tried it on Google Colab Pro+ but it gives an same error. At the last line, "train()" line it creates an error.  Should i change something on filepaths?
## 3. Steps to reproduce

I followed the link above and reshaped and added noise to my own data(256*256 size) with the help of "python image_operation.py -h" in conda. I also changed the amount of virtual memory but problem still occurs. I only changed path in the config.py file with original work.

## 4. Expected behavior

I expect train.py and test.py to give results.

## 5. Additional context

runfile('C:/Users/eren.alici/Desktop/pythons/train.py', wdir='C:/Users/eren.alici/Desktop/pythons')
generating patches
done
Traceback (most recent call last):

  File "C:\Users\eren.alici\Desktop\pythons\train.py", line 83, in <module>
    train()

  File "C:\Users\eren.alici\Desktop\pythons\train.py", line 24, in train
    truth, noise = get_patch(truth, noise)

  File "C:\Users\eren.alici\Desktop\pythons\utils.py", line 198, in get_patch
    return np.array(out_raw), np.array(out_noise)

MemoryError: Unable to allocate 4.69 GiB for an array with shape (102400, 64, 64, 3) and data type float32

## 6. System information

- OS Platform and Distribution : Windows 10 64 bit Pro
- TensorFlow installed from: pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

edit: i tried to train just 20 image and it gives this error this time:

[C:\Users\asus\AppData\Local\Microsoft\WindowsApps\python3.8.exe C:\Users\asus\PycharmProjects\pythonProject1\train.py 
2022-12-31 16:50:37.740732: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2022-12-31 16:50:37.743082: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
generating patches
done
2022-12-31 16:51:48.724730: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-12-31 16:51:48.727183: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-31 16:51:48.851474: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-OLN8V00
2022-12-31 16:51:48.851846: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-OLN8V00
2022-12-31 16:51:48.860257: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-31 16:51:48.952904: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1e5e84fe770 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-12-31 16:51:48.953235: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "C:\Users\asus\PycharmProjects\pythonProject1\train.py", line 84, in <module>
    train()
  File "C:\Users\asus\PycharmProjects\pythonProject1\train.py", line 45, in train
    for times in epoch_bar(range(truth.shape[0] // BATCH_SIZE)):
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\progressbar\progressbar.py", line 150, in __next__
    value = next(self.__iterable)
TypeError: 'NoneType' object is not an iterator](url)

edit: i tried to train just 20 image and it gives this error this time:

C:\Users\asus\AppData\Local\Microsoft\WindowsApps\python3.8.exe C:\Users\asus\PycharmProjects\pythonProject1\train.py 
2022-12-31 16:50:37.740732: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2022-12-31 16:50:37.743082: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
generating patches
done
2022-12-31 16:51:48.724730: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-12-31 16:51:48.727183: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-31 16:51:48.851474: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-OLN8V00
2022-12-31 16:51:48.851846: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-OLN8V00
2022-12-31 16:51:48.860257: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-31 16:51:48.952904: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1e5e84fe770 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-12-31 16:51:48.953235: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "C:\Users\asus\PycharmProjects\pythonProject1\train.py", line 84, in <module>
    train()
  File "C:\Users\asus\PycharmProjects\pythonProject1\train.py", line 45, in train
    for times in epoch_bar(range(truth.shape[0] // BATCH_SIZE)):
  File "C:\Users\asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\progressbar\progressbar.py", line 150, in __next__
    value = next(self.__iterable)
TypeError: 'NoneType' object is not an iterator

**Comment by laxmareddyp** [comment]
Hi @21328739,

The URL which you provided is not pointing out to the official model garden repository. Please make sure to resubmit the issue with proper official model garden repository so that we can help you with the you are facing.

Thanks.
