### ISSUE TITLE
Restoring LaBSE fine-tuned checkpoint - continue from Ref #10856

### ISSUE THREAD

**Issue by aloka-fernando** [tensorflow/models#10876]
@saberkun Thank you for the response and for providing me with the reference for the issue stated in #10856. Since I am unable to re-open the issue I am mentioning this commend under a new issue. 

I gather the checkpoint restoration can be done for the below two scenarios

(1) to continue fine-tuning - here the dual encoder should be restored.
(2) for inferencing - The shared encoder (in my case LaBSE fine-tuned model) should be restored.

My need is to restore the checkpoint for inferencing. ie. scenario (2) above

During fine-tuning, the files created are as per the screenshot above. There were no .meta files generated. Is this required for restoring the model?

The code I am using is as follows.

```python
bert_tfhub_module='https://tfhub.dev/google/LaBSE/2'
encoder_network = utils.get_encoder_from_hub(bert_tfhub_module)

checkpoint_directory = "/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/models/labse_ft_models/"
AdamWeightDecay = optimization.AdamWeightDecayConfig
optimizer=optimization.OptimizerConfig(
      type="adamw", adamw=AdamWeightDecay())
model_checkpoint = tf.train.Checkpoint(optimizer=optimizer, model=encoder_network)
status = model_checkpoint.restore(tf.train.latest_checkpoint(checkpoint_directory))
for _ in range(num_training_steps):
   optimizer.minimize()  # Variables will be restored on creation.
status.assert_consumed()  # Optional sanity checks.
```

However I get the following error. What seems to be wrong in my code? Here L188 is 
```python
optimizer=optimization.OptimizerConfig(
      type="adamw", adamw=AdamWeightDecay())
```

Error:
```python
Traceback (most recent call last):
  File "/userdirs/aloka/p3_sentence_alignment/pmlmFt_sentence_alignment/scripts/read_checkpoint.py", line 188, in <module>
    model_checkpoint = tf.train.Checkpoint(optimizer=optimizer, model=encoder_network)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 2192, in __init__
    _assert_trackable(converted_v, k)
  File "/userdirs/aloka/miniconda3/envs/ft_dual_encoder/lib/python3.9/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 1566, in _assert_trackable
    raise ValueError(
ValueError: `Checkpoint` was expecting optimizer to be a trackable object (an object derived from `Trackable`), got OptimizerConfig(type='adamw', sgd=SGDConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='SGD', decay=0.0, nesterov=False, momentum=0.0), sgd_experimental=SGDExperimentalConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='SGD', nesterov=False, momentum=0.0, jit_compile=False), adam=AdamConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adam', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False), adam_experimental=AdamExperimentalConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adam', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False, jit_compile=False), adamw=AdamWeightDecayConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='AdamWeightDecay', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False, weight_decay_rate=0.0, include_in_weight_decay=None, exclude_from_weight_decay=None, gradient_clip_norm=1.0), adamw_experimental=AdamWeightDecayExperimentalConfig(clipnorm=None, clipvalue=None, global_clipnorm=1.0, name='AdamWeightDecayExperimental', beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False, weight_decay=0.0, jit_compile=False), lamb=LAMBConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='LAMB', beta_1=0.9, beta_2=0.999, epsilon=1e-06, weight_decay_rate=0.0, exclude_from_weight_decay=None, exclude_from_layer_adaptation=None), rmsprop=RMSPropConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='RMSprop', rho=0.9, momentum=0.0, epsilon=1e-07, centered=False), lars=LARSConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='LARS', momentum=0.9, eeta=0.001, weight_decay_rate=0.0, nesterov=False, classic_momentum=True, exclude_from_weight_decay=None, exclude_from_layer_adaptation=None), adagrad=AdagradConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adagrad', initial_accumulator_value=0.1, epsilon=1e-07), slide=SLIDEConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='SLIDE', beta_1=0.9, beta_2=0.999, epsilon=1e-06, weight_decay_rate=0.0, weight_decay_type='inner', exclude_from_weight_decay=None, exclude_from_layer_adaptation=None, include_in_sparse_layer_adaptation=None, sparse_layer_learning_rate=0.1, do_gradient_rescaling=True, norm_type='layer', ratio_clip_norm=100000.0), adafactor=AdafactorConfig(clipnorm=None, clipvalue=None, global_clipnorm=None, name='Adafactor', factored=True, multiply_by_parameter_scale=True, beta1=None, decay_rate=0.8, step_offset=0, clipping_threshold=1.0, min_dim_size_to_factor=128, epsilon1=1e-30, epsilon2=0.001, weight_decay=None, include_in_weight_decay=None)). If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.

```

_Originally posted by @aloka-fernando in https://github.com/tensorflow/models/issues/10856#issuecomment-1367053097_

**Comment by saberkun** [comment]
Thanks. Reopen the original issue. Let's close this one and discuss in the original post. Thank you

**Comment by aloka-fernando** [comment]
Thanks for re-opening #10856. Ill add comments to the initial thread.
