### ISSUE TITLE
 ImportError: cannot import name 'builder'

### ISSUE THREAD

**Issue by TalalAhmed311** [tensorflow/models#10921]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [  ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the bug

I followed the steps as mention in the documentation

1) Download CUDA and CUDAnn and set  their path in the environment variables
2) Clone models repository
3) Run these following commands:

`cd models/research`

`protoc object_detection/protos/*.proto --python_out=.`

`cp object_detection/packages/tf2/setup.py .`
`python -m pip install --use-feature=2020-resolver .`

When I try to make tfrecords files of my Pascal_VOC using create_tfrecord script it thows an error

2023-02-01 08:19:14.665386: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2023-02-01 08:19:14.665410: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "models\research/create_pascal_tf_record.py", line 38, in <module>
    from object_detection.utils import label_map_util
  File "E:\Custom Models\FasterRCNN\models\research\object_detection\utils\label_map_util.py", line 29, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "E:\Custom Models\FasterRCNN\models\research\object_detection\protos\string_int_label_map_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder'

## System information
- OS Platform and Distribution (Windows 10):
- TensorFlow version '2.11.0':
- Python version: 3.6.13
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  v11.2
- GPU model and memory: GTX 1650 Super 8GB RAM

**Comment by laxmareddyp** [comment]
Hi @TalalAhmed311,

Can you check the following [gist](https://colab.sandbox.google.com/gist/laxmareddyp/72ae17d12f25f6de1419dcd60bcaca8d/10921.ipynb) which is working fine. Please let us know if it resolves your problem.

Thanks.

**Comment by HimanshuJakhmola356** [comment]
hello @TalalAhmed311,
i want to work in that! issue #10921

**Comment by HimanshuJakhmola356** [comment]
can i work it on Now, @TalalAhmed311 
issue no #10921
