### ISSUE TITLE
Broken tf1 models/research/object-detection package 

### ISSUE THREAD

**Issue by MSutt** [tensorflow/models#10949]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/packages/tf1/setup.py
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py

## 2. Describe the bug

Missing requirement in the tf1 package.
As mentioned in my [comment](https://github.com/tensorflow/models/commit/9a6af0a4b2fc308f532683d0d25192b247328168#commitcomment-99158209) of the commit 9a6af0a. 
The changes from that commit broke the tf1 package`models/research/object_detection/packages/tf1/setup.py`. Keras is not part of the `REQUIRED_PACKAGES` and causes training to raise Exception.

## 3. Steps to reproduce

- install tf1 package
```
cd research/
cp object_detection/packages/tf1/setup.py ./
python -m pip install --user .
```
- Start a training that uses a model `resnet_v1` from `models/keras_models`

## 4. Expected behavior

The training don't raise a `ModuleNotFoundError` 

## 5. Additional context
Example of traceback failure 
```
Traceback (most recent call last):
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/home/tensorflow/.local/lib/python3.6/site-packages/object_detection/model_lib.py", line 31, in <module>
    from object_detection import exporter as exporter_lib
  File "/home/tensorflow/.local/lib/python3.6/site-packages/object_detection/exporter.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/home/tensorflow/.local/lib/python3.6/site-packages/object_detection/builders/model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "/home/tensorflow/.local/lib/python3.6/site-packages/object_detection/meta_architectures/deepmac_meta_arch.py", line 20, in <module>
    from object_detection.models.keras_models import resnet_v1
  File "/home/tensorflow/.local/lib/python3.6/site-packages/object_detection/models/keras_models/resnet_v1.py", line 21, in <module>
    from keras.applications import resnet
ModuleNotFoundError: No module named 'keras'
```

**Comment by laxmareddyp** [comment]
Hi @MSutt,

Thanks for raising this one but we suggest you to [migrate](https://www.tensorflow.org/guide/migrate) from TF1 to TF2 can help you to fix the problem and please let us know if it helps you.

Thanks
