### ISSUE TITLE
FileNotFoundError: Op type not registered 'DisableCopyOnRead'

### ISSUE THREAD

**Issue by aurelliafirsty** [tensorflow/models#10999]
I've trained the EfficientDet D1 model in google collab. but, when i want to load the model in jetson nano, i'm facing this error

```
Traceback (most recent call last):
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\saved_model\load.py", line 903, in load_internal
    ckpt_options, options, filters)
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\saved_model\load.py", line 138, in _init_
    meta_graph.graph_def.library, wrapper_function=_WrapperFunction))
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\saved_model\function_deserialization.py", line 388, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\framework\function_def_to_graph.py", line 64, in function_def_to_graph
    fdef, input_shapes)
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\framework\function_def_to_graph.py", line 228, in function_def_to_graph_def
    op_def = default_graph._get_op_def(node_def.op)  # pylint: disable=protected-access
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\framework\ops.py", line 3967, in _get_op_def
    buf)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'DisableCopyOnRead' in binary running on SAMYOB-PC. Make sure the Op and Kernel are registered in the binary running in thiry running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graphare lazily regist, as contrib ops are lazily registered when the module is first accessed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\software\conda2023\envs\older\lib\runpy.py", line 193, in _run_module_as_main
    "_main_", mod_spec)
  File "E:\software\conda2023\envs\older\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\software\conda2023\envs\older\Scripts\saved_model_cli.exe\_main_.py", line 7, in <module>
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 1204, in main
    args.func(args)
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 729, in show
    _show_all(args.dir)
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 308, in _show_all
    _show_defined_functions(saved_model_dir)
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 188, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\saved_model\load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "E:\software\conda2023\envs\older\lib\site-packages\tensorflow\python\saved_model\load.py", line 906, in load_internal
    str(err) + "\n If trying to load on a different device from the "
FileNotFoundError: Op type not registered 'DisableCopyOnRead' in binary running on SAMYOB-PC. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loadn the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.cont the graph, as contrib ops are lazily registere is first accessrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhostaved_model.LoadOptions to the io_device such as '/job:localhost'.
```
 
 can you help me to solve this error?

**Comment by laxmareddyp** [comment]
Hi @aurelliafirsty,

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) and [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks for understanding.

**Comment by selinaarokiaswamy-GSLAB** [comment]
The issue still persists.. suggest any workaround please
