### ISSUE TITLE
Error while training flower

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [tensorflow/models#11]
After successfully downloading and generating training and validation splits (I had to install coreutils and replace shuf with gshuf on OS X ). I encountered following error immediately. 
```
(portenv)dhcp-ccc-3940:inception aub3$ bazel-bin/inception/flowers_train   --train_dir="${TRAIN_DIR}"   --data_dir="${FLOWERS_DATA_DIR}"   --pretrained_model_checkpoint_path="${MODEL_PATH}"   --fine_tune=True   --initial_learning_rate=0.001   --input_queue_memory_factor=1
/Users/aub3/portenv/lib/python2.7/site-packages/tensorflow/python/ops/image_ops.py:586: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if width == new_width_const and height == new_height_const:
Traceback (most recent call last):
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/flowers_train.py", line 41, in <module>
    tf.app.run()
  File "/Users/aub3/portenv/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/flowers_train.py", line 37, in main
    inception_train.train(dataset)
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception_train.py", line 235, in train
    loss = _tower_loss(images, labels, num_classes, scope)
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception_train.py", line 110, in _tower_loss
    scope=scope)
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception_model.py", line 90, in inference
    scope=scope)
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/slim/inception_model.py", line 88, in inception_v3
    scope='conv0')
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/slim/ops.py", line 184, in conv2d
    restore=restore)
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/Users/aub3/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/slim/variables.py", line 224, in variable
    trainable=trainable, collections=collections)
TypeError: get_variable() got an unexpected keyword argument 'regularizer'

```

**Comment by keveman** [comment]
Did you compile TensorFlow from source and install it as a PIP package as mentioned in the 'Getting Started' section?

>  NOTE Before doing anything, we first need to build TensorFlow from source, and installed as a PIP package. Please follow the instructions at Installing From Source.

**Comment by AKSHAYUBHAT** [comment]
Do I need to use the Master branch, or 0.7.1

**Comment by keveman** [comment]
You need HEAD of the master branch.

**Comment by AKSHAYUBHAT** [comment]
Thanks, I will try and update.

**Comment by waterofphysics** [comment]
@AKSHAYUBHAT 
Could you please give detailed procedure to solve this problem?
I have encountered the same problem.
And I have installed TensorFlow from source and installed it as a PIP package (tensorflow can be imported in python environment), as @keveman has suggested.

**Comment by AKSHAYUBHAT** [comment]
@waterofphysics I think you need to use the HEAD or the master branch for slim tensorflow to compile. 
I haven't tried it yet.

**Comment by waterofphysics** [comment]
@AKSHAYUBHAT Thank you, but I am still a little bit confused about `use the HEAD or the master branch for slim tensorflow to compile`. Could you please give more information about this?
`Slim` refers to https://github.com/tensorflow/models/tree/master/inception/inception/slim or something else?

**Comment by AKSHAYUBHAT** [comment]
@waterofphysics You need to install latest version of TensorFlow using the github repo and not the pip package for version 0.7.1.

**Comment by waterofphysics** [comment]
@AKSHAYUBHAT Thanks for your help. Yes, I have installed the latest version of TensorFlow through 
`Clone the TensorFlow repository` and `Create the pip package and install` not from `Pip Installation` in `Download and Setup` instructions...
