### ISSUE TITLE
ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos'

### ISSUE THREAD

**Issue by kabilankavi131** [tensorflow/models#11069]
<h3>
When i run the verification script i get this error 
<br><hr>
Traceback (most recent call last):
  File "D:\TFODCourse\Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "D:\tfod\Lib\site-packages\object_detection\builders\model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "D:\tfod\Lib\site-packages\object_detection\builders\anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' (D:\tfod\Lib\site-packages\object_detection\protos\__init__.py)

<br>
<h4>Kindly help me to fix this error i've used to many issues on github to solve this error but im not able to solve this error <br>
![Screenshot (23)](https://github.com/tensorflow/models/assets/94551372/ef16796c-eeb8-47b4-9b44-5f0fbf4aab35)
</h4>

</h3>

**Comment by kabilankavi131** [comment]
can not import anchor_generator_pb2
