### ISSUE TITLE
No module named 'lvis_evaluation'

### ISSUE THREAD

**Issue by Obenhelen** [tensorflow/models#11079]
while training the model i am getting this error..
Traceback (most recent call last):
  File "C:\Users\OBENCECILIA\Desktop\RealTimeObjectDetection\Tensorflow\models\research\object_detection\model_main_tf2.py", line 31, in <module>
    import model_lib_v2
  File "C:\Users\OBENCECILIA\Desktop\RealTimeObjectDetection\Tensorflow\models\research\object_detection\model_lib_v2.py", line 29, in <module>
    import eval_util
  File "C:\Users\OBENCECILIA\Desktop\RealTimeObjectDetection\Tensorflow\models\research\object_detection\eval_util.py", line 34, in <module>
    import lvis_evaluation
ModuleNotFoundError: No module named 'lvis_evaluation'

**Comment by Obenhelen** [comment]
I also tried pip install lvis_evaluation but got another error...
ERROR: Could not find a version that satisfies the requirement lvis_evaluation (from versions: none)
ERROR: No matching distribution found for lvis_evaluation
thanks in advanced

**Comment by Obenhelen** [comment]
please help me solve this. ive been stuck here for days

**Comment by Sam-Seaberry** [comment]
Have you tried this: https://pypi.org/project/lvis/ ?
`pip install lvis`
