### ISSUE TITLE
ValueError:  is not supported for tf version 2. 

### ISSUE THREAD

**Issue by krantawan** [tensorflow/models#11075]
Hello I got a issue with Training model in Colab 

> 2023-08-15 08:58:57.576011: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> 2023-08-15 08:59:01.304497: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
> INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
> I0815 08:59:01.305459 133091154064000 mirrored_strategy.py:419] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
> INFO:tensorflow:Maybe overwriting train_steps: 10000
> I0815 08:59:01.327453 133091154064000 config_util.py:552] Maybe overwriting train_steps: 10000
> INFO:tensorflow:Maybe overwriting use_bfloat16: False
> I0815 08:59:01.327646 133091154064000 config_util.py:552] Maybe overwriting use_bfloat16: False
> Traceback (most recent call last):
>   File "CenterNet_HourGlass104/Tensorflow/models/research/object_detection/model_main_tf2.py", line 114, in <module>
>     tf.compat.v1.app.run()
>   File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/platform/app.py", line 36, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "CenterNet_HourGlass104/Tensorflow/models/research/object_detection/model_main_tf2.py", line 105, in main
>     model_lib_v2.train_loop(
>   File "/usr/local/lib/python3.10/dist-packages/object_detection/model_lib_v2.py", line 547, in train_loop
>     detection_model = MODEL_BUILD_UTIL_MAP['detection_model_fn_base'](
>   File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/model_builder.py", line 1262, in build
>     return build_func(getattr(model_config, meta_architecture), is_training,
>   File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/model_builder.py", line 412, in _build_ssd_model
>     _check_feature_extractor_exists(ssd_config.feature_extractor.type)
>   File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/model_builder.py", line 270, in _check_feature_extractor_exists
>     raise ValueError(
> ValueError:  is not supported for tf version 2. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

I used model and found the same problem
[Model TF2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)
- [CenterNet HourGlass104 512x512](http://download.tensorflow.org/models/object_detection/tf2/20200713/centernet_hg104_512x512_coco17_tpu-8.tar.gz)
- [Faster R-CNN ResNet50 V1 640x640](http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8.tar.gz)
- [CenterNet MobileNetV2 FPN 512x512](http://download.tensorflow.org/models/object_detection/tf2/20210210/centernet_mobilenetv2fpn_512x512_coco17_od.tar.gz)

Tersorflow version 2.13.0 in Colab

Please help me to fix this issue.  I would be so appreciate if you help me.
Thanks,

**Comment by krantawan** [comment]
@83here I have sent all the data to your email, sir.

**Comment by Tytanium101** [comment]
was this solved? im having a similar issue
