### ISSUE TITLE
'pip3 install tf-models-nightly Collecting tf-models-nightly'

### ISSUE THREAD

**Issue by Carson-We** [tensorflow/models#11151]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ V] I am using the latest TensorFlow Model Garden release and TensorFlow 2.

- [V ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ V] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

hi, when I using 'pip3 install tf-models-nightly Collecting tf-models-nightly' on my Mac, it doesn't work

## 3. Steps to reproduce

pip3 install tf-models-nightly Collecting tf-models-nightly on Terminal

## 4. Expected behavior(Terminal shown)

```
`Collecting tf-models-nightly
  Using cached tf_models_nightly-2.15.0.dev20240127-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: Cython in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (3.0.8)
Requirement already satisfied: Pillow in ./miniconda3/lib/python3.11/site-packages (from tf-models-nightly) (10.0.1)
Requirement already satisfied: gin-config in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (0.5.0)
Requirement already satisfied: google-api-python-client>=1.6.7 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (2.115.0)
Requirement already satisfied: immutabledict in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (4.1.0)
Requirement already satisfied: kaggle>=1.3.9 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (1.6.3)
Requirement already satisfied: matplotlib in ./miniconda3/lib/python3.11/site-packages (from tf-models-nightly) (3.8.0)
Requirement already satisfied: numpy>=1.20 in ./miniconda3/lib/python3.11/site-packages (from tf-models-nightly) (1.26.0)
Requirement already satisfied: oauth2client in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (4.1.3)
Requirement already satisfied: opencv-python-headless in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (4.9.0.80)
Requirement already satisfied: pandas>=0.22.0 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (2.2.0)
Requirement already satisfied: psutil>=5.4.3 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (5.9.8)
Requirement already satisfied: py-cpuinfo>=3.3.0 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (9.0.0)
Requirement already satisfied: pycocotools in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (2.0.7)
Requirement already satisfied: pyyaml>=6.0.0 in ./miniconda3/lib/python3.11/site-packages (from tf-models-nightly) (6.0.1)
Requirement already satisfied: sacrebleu in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (2.4.0)
Requirement already satisfied: scipy>=0.19.1 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (1.12.0)
Requirement already satisfied: sentencepiece in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (0.1.99)
Requirement already satisfied: seqeval in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (1.2.2)
Requirement already satisfied: six in ./miniconda3/lib/python3.11/site-packages (from tf-models-nightly) (1.16.0)
Requirement already satisfied: tensorflow-datasets in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (4.9.4)
Requirement already satisfied: tensorflow-hub>=0.6.0 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (0.16.0)
Requirement already satisfied: tensorflow-model-optimization>=0.4.1 in ./.local/lib/python3.11/site-packages (from tf-models-nightly) (0.7.5)
INFO: pip is looking at multiple versions of tf-models-nightly to determine which version is compatible with other requirements. This could take a while.
  Using cached tf_models_nightly-2.15.0.dev20240126-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240125-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240124-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240123-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240122-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240121-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240120-py2.py3-none-any.whl.metadata (1.4 kB)
INFO: pip is still looking at multiple versions of tf-models-nightly to determine which version is compatible with other requirements. This could take a while.
  Using cached tf_models_nightly-2.15.0.dev20240119-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240118-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240117-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240116-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240115-py2.py3-none-any.whl.metadata (1.4 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached tf_models_nightly-2.15.0.dev20240114-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240113-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240112-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240111-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240110-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240109-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240108-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240107-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240106-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240105-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240104-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240103-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240102-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20240101-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231231-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231230-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231229-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231228-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231227-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231226-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231225-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231224-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231223-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231222-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231221-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231220-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231219-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231218-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231217-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231216-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231214-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231213-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231212-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231211-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231210-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231209-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231208-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231207-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231206-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231205-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231204-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231203-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231202-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231201-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231130-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231129-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231128-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231127-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231126-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231125-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231124-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231123-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231122-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231121-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231120-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231119-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231118-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231117-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.15.0.dev20231116-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231115-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231114-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231113-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231112-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231111-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231110-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231109-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231108-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231107-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231106-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231105-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231104-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231103-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231102-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231101-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231031-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231030-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231029-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231028-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231027-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231026-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231025-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231024-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231022-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231021-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231020-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231019-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231018-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231017-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231016-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231015-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231014-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231013-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231012-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231011-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231010-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231009-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231008-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231007-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231006-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231005-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231004-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231003-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231002-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20231001-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230930-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230929-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230928-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230927-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230926-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230925-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230924-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230923-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230922-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.14.0.dev20230921-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.2.dev20230920-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.2.dev20230919-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.2.dev20230918-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.2.dev20230917-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.2.dev20230916-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.2.dev20230915-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.2.dev20230914-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.1.dev20230913-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.1.dev20230912-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached tf_models_nightly-2.13.1.dev20230911-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting pyyaml<5.4.0,>=5.1 (from tf-models-nightly)
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lb/mc1_bh0n5mxd9ldr3tdf2pbr0000gn/T/pip-install-mx1nl2gh/pyyaml_f7c0d772a59145c7bc1216da03a0850a/setup.py", line 291, in <module>
          setup(
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/lb/mc1_bh0n5mxd9ldr3tdf2pbr0000gn/T/pip-install-mx1nl2gh/pyyaml_f7c0d772a59145c7bc1216da03a0850a/setup.py", line 199, in get_source_files
          self.cython_sources(ext.sources, ext)
          ^^^^^^^^^^^^^^^^^^^
        File "/Users/tszsanwu/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`
```

## 5. Additional context
no logs 

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macxOS Sonama Version 14.3 (23D56)
- TensorFlow installed from (source or binary):Terminal
- TensorFlow version (use command below):2.15.0
- Python version:Python 3.11.6
- Bazel version (if compiling from source):/
- GCC/Compiler version (if compiling from source):/
- CUDA/cuDNN version:/
- GPU model and memory:Apple M2 Max 38 core GPU( support metal 3) 64 GB RAM

**Comment by laxmareddyp** [comment]
Hi @Carson-We ,

Thank you for getting in touch. Regrettably, TF-Text does not currently provide support for Apple Mac computers. This is the reason behind the error you're encountering. For more comprehensive information, please consult the [Readme.md](https://github.com/tensorflow/text#a-note-about-different-operating-system-packages). This should provide you with a clearer understanding of the cause of the error you're experiencing.

Thanks.

**Comment by Carson-We** [comment]
> Hi @Carson-We ,
> 
> Thank you for getting in touch. Regrettably, TF-Text does not currently provide support for Apple Mac computers. This is the reason behind the error you're encountering. For more comprehensive information, please consult the [Readme.md](https://github.com/tensorflow/text#a-note-about-different-operating-system-packages). This should provide you with a clearer understanding of the cause of the error you're experiencing.
> 
> For reference you can check this [previous issue](https://github.com/tensorflow/models/issues/11071) raised by the community.
> 
> Thanks.

Thanks you very much. It's helps me a lot ❤️
