### ISSUE TITLE
Unable to install tf-models-official

### ISSUE THREAD

**Issue by engares** [tensorflow/models#11169]
# Prerequisites & system information
-Windows 10 or Jetson Nano Ubuntu 18.04.6 LTS
(The same output in both)
-Python 3.10
-Anaconda or Archiconda
-Jupyter

TF
```
 print(tf.version.GIT_VERSION, tf.version.VERSION)
v1.12.1-106616-g5b29cd2a5f6 2.17.0-dev20240225
```

## 1. Describe the bug

I'm trying to replicate [ this TF official tutorial on MOVINETS](https://www.tensorflow.org/tutorials/video/transfer_learning_with_movinet) on my local machine. I tried both on my jetson nano and in my W10 laptop. 

The problems seems to appear on the tf-models-official installation, I'm sure its related to cython and pyyalm

```
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/engares/archiconda3/envs/colab/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/engares/archiconda3/envs/colab/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/engares/archiconda3/envs/colab/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-a122kq9z/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`\`\`
```

I have tried to [clone the source](https://github.com/tensorflow/models#Installation)
but it's unable to import the model 
 
```
`# Import the MoViNet model from TensorFlow Models (tf-models-official) for the MoViNet model
from official.projects.movinet.modeling import movinet
from official.projects.movinet.modeling import movinet_model
```
`
```
`AttributeError                            Traceback (most recent call last)
Cell In[4], line 20
     18 import keras
     19 import tensorflow as tf
---> 20 import tensorflow_hub as hub
     21 from tensorflow.keras import layers
     22 from tensorflow.keras.optimizers import Adam

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tensorflow_hub/__init__.py:111
    103       print(
    104           "\n\nFailed to import tf_keras. Please note that tf_keras is not"
    105           " installed by default when you install tensorflow_hub. This is so"
    106           " that users can decide which tf_keras package to use. To use"
    107           " tensorflow_hub, please install a current version of tf_keras.\n\n"
    108       )
    109       raise
--> 111 _ensure_keras_2_importable()
    114 # pylint: disable=g-import-not-at-top
    115 # pylint: disable=g-bad-import-order
    116 # Symbols exposed via tensorflow_hub.
    117 from tensorflow_hub.keras_layer import KerasLayer

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tensorflow_hub/__init__.py:100, in _ensure_keras_2_importable()
     98 if version_fn and version_fn().startswith("3."):
     99   try:
--> 100     import tf_keras as keras
    101   except ImportError:
    102     # Print more informative error message, then reraise.
    103     print(
    104         "\n\nFailed to import tf_keras. Please note that tf_keras is not"
    105         " installed by default when you install tensorflow_hub. This is so"
    106         " that users can decide which tf_keras package to use. To use"
    107         " tensorflow_hub, please install a current version of tf_keras.\n\n"
    108     )

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from tf_keras import __internal__
      4 from tf_keras import activations
      5 from tf_keras import applications

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/__internal__/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from tf_keras.__internal__ import backend
      4 from tf_keras.__internal__ import layers
      5 from tf_keras.__internal__ import losses

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/__internal__/backend/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from tf_keras.src.backend import _initialize_variables as initialize_variables
      4 from tf_keras.src.backend import track_variable

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/__init__.py:21
      1 # Copyright 2015 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Implementation of the TF-Keras API, the high-level API of TensorFlow.
     16 
     17 Detailed documentation and user guides are available at
     18 [keras.io](https://keras.io/).
     19 """
---> 21 from tf_keras.src import applications
     22 from tf_keras.src import distribute
     23 from tf_keras.src import models

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/applications/__init__.py:18
      1 # Copyright 2016 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Keras Applications are premade architectures with pre-trained weights."""
---> 18 from tf_keras.src.applications.convnext import ConvNeXtBase
     19 from tf_keras.src.applications.convnext import ConvNeXtLarge
     20 from tf_keras.src.applications.convnext import ConvNeXtSmall

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/applications/convnext.py:33
     31 from tf_keras.src import utils
     32 from tf_keras.src.applications import imagenet_utils
---> 33 from tf_keras.src.engine import sequential
     34 from tf_keras.src.engine import training as training_lib
     36 # isort: off

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/engine/sequential.py:24
     22 from tf_keras.src import layers as layer_module
     23 from tf_keras.src.engine import base_layer
---> 24 from tf_keras.src.engine import functional
     25 from tf_keras.src.engine import input_layer
     26 from tf_keras.src.engine import training

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/engine/functional.py:33
     31 from tf_keras.src.engine import input_spec
     32 from tf_keras.src.engine import node as node_module
---> 33 from tf_keras.src.engine import training as training_lib
     34 from tf_keras.src.engine import training_utils
     35 from tf_keras.src.saving import serialization_lib

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/engine/training.py:48
     46 from tf_keras.src.optimizers import optimizer_v1
     47 from tf_keras.src.saving import pickle_utils
---> 48 from tf_keras.src.saving import saving_api
     49 from tf_keras.src.saving import saving_lib
     50 from tf_keras.src.saving import serialization_lib

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/saving/saving_api.py:25
     22 from tensorflow.python.util.tf_export import keras_export
     24 from tf_keras.src.saving import saving_lib
---> 25 from tf_keras.src.saving.legacy import save as legacy_sm_saving_lib
     26 from tf_keras.src.utils import io_utils
     28 try:

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/saving/legacy/save.py:27
     25 from tf_keras.src.saving.legacy import serialization
     26 from tf_keras.src.saving.legacy.saved_model import load as saved_model_load
---> 27 from tf_keras.src.saving.legacy.saved_model import load_context
     28 from tf_keras.src.saving.legacy.saved_model import save as saved_model_save
     29 from tf_keras.src.saving.legacy.saved_model.utils import keras_option_scope

File ~/archiconda3/envs/colab/lib/python3.10/site-packages/tf_keras/src/saving/legacy/saved_model/load_context.py:68
     64     """Returns whether under a load context."""
     65     return _load_context.in_load_context()
---> 68 tf.__internal__.register_load_context_function(in_load_context)

AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'register_load_context_function'`
```

I have also tried this but nothing seems to work: 
```
#!pip install "cython<3.0.0" && pip install "pyyaml!=6.0.0,!=5.4.0,!=5.4.1" # pyyaml is broken with cython 3

```

## 2. Steps to reproduce

`!pip install tf-models-official`
```

import keras
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Import the MoViNet model from TensorFlow Models (tf-models-official) for the MoViNet model
from official.projects.movinet.modeling import movinet
from official.projects.movinet.modeling import movinet_model
```
`

## 3. Expected behavior

A nice and clean installation of TF-models

**Comment by laxmareddyp** [comment]
Hi @engares,

We are looking into this issue and will let you know as soon as possible.

**Comment by laxmareddyp** [comment]
Hi @engares,

I understood that what is happening in your case now, TF-Text do not support Windows after version 2.10. This is the reason it is always throwing import error on your windows OS.Please look at this[ Readme.md](https://github.com/tensorflow/text#a-note-about-different-operating-system-packages) for more details.
As a workaround you can use colab notebooks or [configure WSL2](https://www.tensorflow.org/install/pip#windows-wsl2_1) in your system, then you can install above pip packages.

Did you try on ubuntu machine rather than Jetson Nano , as we do not have available device to test on it.

Hope this helps.

**Comment by engares** [comment]
@laxmareddyp  Everything working fine on W10!! Thanks 🙏

**Comment by laxmareddyp** [comment]
@engares , Glad that it is working without any issues and will close this as completed. Please feel free to connect with us in future if you face any issues.Thanks

**Comment by laxmareddyp** [comment]
Hi,

we have created a separate pip package for TensorFlow Official Models ([tf-models-no-deps 2.16.0](https://pypi.org/project/tf-models-no-deps/)) this won't have TensorFlow Text (TF-Text) as a dependency. This will allow users to install and use tf-models-official(for vision users) on any platform without needing TF-Text specifically.
Thanks

**Comment by Ahong303** [comment]
Hi, after using it, the same problem still persists and cannot be installed. Can you explain the installation process in detail
