### ISSUE TITLE
error: subprocess-exited-with-error    × python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by Rajcr2** [tensorflow/models#11188]
while installing object detection API.

`python -m pip install .`

after executing this commands I got following error.

> Collecting pyyaml<5.4.0,>=5.1 (from tf-models-official>=2.5.1->object_detection==0.1)
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hp\AppData\Local\Temp\pip-install-1f1sjj65\pyyaml_b746b1d06c424b9ba35410c1c37f7a0e\setup.py", line 291, in <module>
          setup(
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\command\egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "C:\Users\hp\AppData\Local\Temp\pip-install-1f1sjj65\pyyaml_b746b1d06c424b9ba35410c1c37f7a0e\setup.py", line 199, in get_source_files
          self.cython_sources(ext.sources, ext)
        File "C:\Users\hp\.conda\envs\tfcd\lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

> 

Anyone please tell solution.

**Comment by laxmareddyp** [comment]
Hi @Rajcr2 ,

Could you please share the proper reproducible commands or steps you are using?. The provided steps are unclear to me. Meanwhile , I've attempted to run the object detection notebook on Colab, and it ran successfully. I've attached the [gist](https://colab.sandbox.google.com/gist/laxmareddyp/7fad812c1ab676baba6a3b41af9c6288/object_detection.ipynb#scrollTo=hFdVelJ2YbQz) for your reference. Additionally, I created a virtual environment and executed the "tf-models-official" command, which also ran successfully on my local system. Please try to create a new(fresh) virtual environment and execute the commands.
When attempting to install packages, version conflicts may arise due to previous unsuccessful installation attempts of the same package.

<img width="717" alt="image" src="https://github.com/tensorflow/models/assets/113547567/2e815a6d-ab20-4fec-a011-d09cc8eccd2a">

<img width="717" alt="image" src="https://github.com/tensorflow/models/assets/113547567/1420c472-6b90-4d42-a256-ca3f2b095547">

**Comment by Rajcr2** [comment]
oh thanks for reply.

[](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html)
I followed this while installing .

`!git clone `https://github.com/tensorflow/models.git`
after cloning, in the models/research folder I tried installing object detection API where problem occured.

**Comment by laxmareddyp** [comment]
Hi @Rajcr2 ,

I understand why it is happening in your case, since with the latest tensorflow version,  libraries are deprecated and Support for the older codebase has been discontinued. Could you kindly utilize the [official Object Detection ](https://github.com/tensorflow/models/blob/master/docs/vision/object_detection.ipynb) models provided by TensorFlow Model Garden. This codebase is up to date with the latest changes.

Thanks.
