### ISSUE TITLE
when i use tensorboard in tf1.0 there are SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by andongchen** [tensorflow/models#1126]
when i fine this inception3 model and use tensorboard in tf1.0 all have syntaxerror invalid syntax .

DATASET_DIR=/home/cy/data/flowers
TRAIN_DIR=./flowers-models/inception_v3
CHECKPOINT_PATH=./pretrainmodel/inception_v3.ckpt
python3 train_image_classifier.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=flowers \
    --dataset_split_name=train \
    --model_name=inception_v3 \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --checkpoint_exclude_scopes=InceptionV3/Logits,InceptionV3/AuxLogits/Logits \
    --trainable_scopes=InceptionV3/Logits,InceptionV3/AuxLogits/Logits

cy@cy:~/PycharmProjects/models-master/slim/flowers-models$ tensorboard --logdir=./inception_v3
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/tensorboard.py", line 34, in <module>
    from tensorflow.tensorboard.backend import server
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/backend/server.py", line 38, in <module>
    from tensorflow.tensorboard.plugins.projector import plugin as projector_plugin
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 27, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/__init__.py", line 83, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/cy/.local/lib/python3.5/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/cy/.local/lib/python3.5/site-packages/dask/dataframe/core.py", line 11, in <module>
    import pandas as pd
  File "/home/cy/.local/lib/python3.5/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/home/cy/.local/lib/python3.5/site-packages/pandas/compat/__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "/home/cy/.local/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

**Comment by andongchen** [comment]
when i remove tf1.0 and install tf 0.12 problem is sloved

**Comment by nealwu** [comment]
Is this still happening for you on TensorFlow 1.0? The models code has been recently upgraded.

**Comment by andongchen** [comment]
no,not happened recently.thanks

**Comment by nealwu** [comment]
OK, glad to hear. Closing this then.

**Comment by haibin894609937** [comment]
you should run :   pip install python-dateutil --upgrade
