### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'`

### ISSUE THREAD

**Issue by maltintas45** [tensorflow/models#1128]
I am new in syntaxnet.So it may be a trivial question but I could not  find what is the reason. I installed syntaxnet according the tutorial and it pass all test. But when I try to construct a new model, I encounter below error. What is the issue? Do I miss something?

Thanks

> `~/models/syntaxnet$ sudo bazel-bin/syntaxnet/parser_trainer \ --task_context=syntaxnet/context-1.pbtxt \ --arg_prefix=brain_pos \   --compute_lexicon \  --graph_builder=greedy \  --training_corpus=training-corpus \  --tuning_corpus=tuning-corpus \  --output_path=models \  --batch_size=32 \  --decay_steps=3600 \  --hidden_layer_sizes=128 \  --learning_rate=0.08 \  --momentum=0.9 \  --seed=0 \  --params=128-0.08-3600-0.9-0
[sudo] password for sm: 
Traceback (most recent call last):
  File "/home/sm/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/__main__/syntaxnet/parser_trainer.py", line 302, in <module>
    tf.app.run()
  File "/home/sm/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/sm/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/__main__/syntaxnet/parser_trainer.py", line 258, in main
    if not gfile.IsDirectory(OutputPath('')):
  File "/home/sm/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/__main__/syntaxnet/parser_trainer.py", line 91, in OutputPath
    return os.path.join(FLAGS.output_path, StageName(), FLAGS.params, path)
  File "/home/sm/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/__main__/syntaxnet/parser_trainer.py", line 87, in StageName
    return os.path.join(FLAGS.arg_prefix, FLAGS.graph_builder)
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'`

**Comment by maltintas45** [comment]
Is there noone who wants to explain this issue?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
