### ISSUE TITLE
ultralytics 8.0.232 has requirement numpy>=1.22.2, but you'll have numpy 1.19.5 which is incompatible

### ISSUE THREAD

**Issue by anilshootup** [tensorflow/models#11339]
python {
            version '3.8'
            pip {
                install "matplotlib"
                install "pandas"
                install "ultralytics==8.0.232"
                install "seaborn==0.12.2"
                install "numpy"
                install "opencv-python"
                install "gitpython"
            }
        }
        I am getting this issue when i build the code
        ultralytics 8.0.232 has requirement numpy>=1.22.2, but you'll have numpy 1.19.5 which is incompatible.
        but when i change                 install "numpy==1.22.2"
        
        then it shows  : Failed to install numpy==1.22.2 from https://files.pythonhosted.org/packages/e9/6c/c0a8130fe198f27bab92f1b28631e0cc2572295f6b7a31e87efe7448aa1c/numpy-1.22.2.zip#sha256=076aee5a3763d41da6bef9565fdf3cb987606f567cd8b104aded2b38b7b47abf.
        please help me what i am doing wrong

**Comment by bharatjetti** [comment]
Hi @anilshootup 
I tried installing ultralytics==8.0.232 within Python 3.8 environment. I followed these steps, 
Within Environment,
```pip install --upgrade pip```
```pip install ultralytics==8.0.232```
It worked fine.
please try this and let me know if you face any more difficulties.
Here are the screenshots.
<img width="1462" alt="Screenshot 2024-11-19 at 12 47 21 PM" src="https://github.com/user-attachments/assets/474818d2-f561-4d03-8db4-23eeab83dc94">
<img width="1462" alt="Screenshot 2024-11-19 at 12 47 56 PM" src="https://github.com/user-attachments/assets/d22fb969-c273-4e33-8043-abbcf720a7e4">

**Comment by anilshootup** [comment]
actually this is am doing using Android  gradle file 
<img width="1275" alt="Screenshot 2024-11-19 at 1 30 37 PM" src="https://github.com/user-attachments/assets/1cccb7a6-df7f-4f4d-986a-d1d1e3edea9b">

I am getting this error

**Comment by anilshootup** [comment]
also i am getting this exception 

ERROR: Exception:
Traceback (most recent call last):
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/commands/install.py", line 335, in run
    requirement_set = resolver.resolve(
        reqs, check_supported_wheels=not options.target_dir
    )
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/operations/prepare.py", line 433, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
        req, self.req_tracker, self.finder, self.build_isolation,
    )
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/operations/prepare.py", line 86, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_internal/distributions/sdist.py", line 97, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_vendor/pep517/wrappers.py", line 160, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        'config_settings': config_settings
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    })
    ^^
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/Users/cdp/AndroidStudioProjects/SdEnergyMeter/app/build/python/env/debug/lib/python3.13/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/private/var/folders/f1/bdvrvq0j1tsfylmfwl7pbb680000gn/T/pip-build-env-tiflvfzg/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.extern.six import PY3, string_types
ModuleNotFoundError: No module named 'setuptools.extern.six'

Chaquopy: Exit status 2
when i build my code Using below configuration 

 python {
            version '3.9'
            pip {
                install "matplotlib"
                install "pandas"
                install "ultralytics==8.0.232"
                install "seaborn==0.12.2"
                install "numpy==1.21.2"
                install "opencv-python"
                install "gitpython"
            }
        }
NOTE : I am using com.chaquo.python library to run python code in android

**Comment by bharatjetti** [comment]
Hi @anilshootup 
Could you please provide the complete steps,
As I can see in the error message the python 3.13 is being used, 
by seeing this error message "ModuleNotFoundError: No module named 'setuptools.extern.six'"
Could you include " install "six" " in the configuration and try the build.
Thank you
