### ISSUE TITLE
Bazel version 0.2.2b causes test error

### ISSUE THREAD

**Issue by nathanathan** [tensorflow/models#114]
```
> bazel test syntaxnet/... util/utf8/...
.........
ERROR: /home/nathan/t11/models/syntaxnet/WORKSPACE:11:1: Traceback (most recent call last):
        File "/home/nathan/t11/models/syntaxnet/WORKSPACE", line 11
                check_version("0.2.0")
        File "/home/nathan/.cache/bazel/_bazel_nathan/e431d047c94467cd60d94b34d8d43bcc/external/tf/tensorflow/tensorflow.bzl", line 22, in check_version
                _parse_bazel_version(native.bazel_version)
        File "/home/nathan/.cache/bazel/_bazel_nathan/e431d047c94467cd60d94b34d8d43bcc/external/tf/tensorflow/tensorflow.bzl", line 15, in _parse_bazel_version
                int(number)
invalid literal for int(): "2b".
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: syntaxnet.
ERROR: no such package 'external': Package 'external' contains errors.
INFO: Elapsed time: 1.014s
ERROR: Couldn't start the build. Unable to run tests.
```

**Comment by Brok-Bucholtz** [comment]
@nathanathan 
Have you tried using Bazel 0.2.2 instead of 0.2.2b?  The [documentation](https://github.com/tensorflow/models/blob/master/syntaxnet/README.md) says to use version 0.2.2.  Let me know if this helps.

**Comment by nathanathan** [comment]
@Brok-Bucholtz Yes, version 0.2.2 works.

**Comment by Brok-Bucholtz** [comment]
Awesome!  Don't forget to close the issue.
