### ISSUE TITLE
im2txt: tf.losses.add_loss(loss,batch_loss) NameError: global name 'loss' is not defined

### ISSUE THREAD

**Issue by kevalcshah10** [tensorflow/models#1142]
## Please let us know which model this issue is about (specify the top-level directory)
When I am trying Training steps 

bazel-bin/im2txt/train   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=1000

INFO:tensorflow:Prefetching values from 8 files matching /home/kevalcshah10/im2txt/data/mscoco/train-?????-of-00256
Traceback (most recent call last):
  File "/home/kevalcshah10/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/kevalcshah10/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/home/kevalcshah10/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 358, in build
    self.build_model()
  File "/home/kevalcshah10/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 317, in build_model
    tf.losses.add_loss(loss,batch_loss)
NameError: global name 'loss' is not defined

What can be error ??? Appreciate ur help !!

**Comment by prb12** [comment]
This is a TF1.0 compatibility issue.

Many of the models in this repository have not been updated yet for TF1.0 as described here https://www.tensorflow.org/install/migration

@cshallue  is the owner of this model according to the README.md, and can probably comment further.

**Comment by cshallue** [comment]
@kevalcshah10 you are working with an old version of this repository. Using the latest version should fix your issue 

@prb12 this model is updated for TF1.0 :)
