### ISSUE TITLE
#Textsum - seq2seq_attention_model.py 'module' object has no attribute 'seq2seq'

### ISSUE THREAD

**Issue by xtr33me** [tensorflow/models#1181]
I am currently running latest TF 1.0, CUDA 8, CudNN 5.1.10. I performed the update on the textsum directory to 1.0 and must say overall it was a really nice implementation so thanks.  That said, it seems like there was atleast one method item that wasn't updated.  The one I am currently dealing with is in seq2seq_attention_model.py .  It's erroring out with the call to tf.nn.seq2seq.sequence_loss.  I have pasted the trace below.

After looking at the API docs I did notice that it does seem that seq2seq_loss is no longer at this location, however when I changed the call over to what I beleived was correct (tf.contrib.seq2seq.sequence_loss) I receive the second error traceback shown after the first one below.  I will post anything I find, however I thought perhaps someone might see what's going on quicker.

```
Traceback (most recent call last):
  File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 208, in main
    decoder = seq2seq_attention_decode.BSDecoder(model, batcher, hps, vocab)
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_decode.py", line 92, in __init__
    self._model.build_graph()
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_model.py", line 298, in build_graph
    self._add_seq2seq()
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_model.py", line 240, in _add_seq2seq
    self._loss = tf.nn.seq2seq.sequence_loss(
AttributeError: 'module' object has no attribute 'seq2seq'
```

**Error I receive when converting over to tf.contrib.seq2seq.sequence_loss:**
```
Traceback (most recent call last):
  File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 208, in main
    decoder = seq2seq_attention_decode.BSDecoder(model, batcher, hps, vocab)
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_decode.py", line 92, in __init__
    self._model.build_graph()
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_model.py", line 298, in build_graph
    self._add_seq2seq()
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_model.py", line 241, in _add_seq2seq
    model_outputs, targets, loss_weights)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/loss.py", line 62, in sequence_loss
    if len(logits.get_shape()) != 3:
AttributeError: 'list' object has no attribute 'get_shape'

```

**Comment by nealwu** [comment]
Should be fixed by https://github.com/tensorflow/models/pull/1197.
