### ISSUE TITLE
[Inception] Resource Exhausted exception when generating TF-Records

### ISSUE THREAD

**Issue by redserpent7** [tensorflow/models#1222]
Hi,

I started generating TF records to start training Imagenet data from scratch. I keep getting this error and the process terminates:

````2017-03-20 08:51:14.244444 [thread 0]: Processed 19000 of 1077584 images in thread batch.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 389, in _process_image_files_batch
    image_buffer, height, width = _process_image(filename, coder)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 317, in _process_image
    image_data = f.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 102, in read
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 72, in _preread_check
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
ResourceExhaustedError: /imagenet2/raw-data/train/n02055803/n02055803_8301.jpg

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 389, in _process_image_files_batch
    image_buffer, height, width = _process_image(filename, coder)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 317, in _process_image
    image_data = f.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 102, in read
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 72, in _preread_check
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
ResourceExhaustedError: /imagenet2/raw-data/train/n02382948/n02382948_22355.jpg

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 389, in _process_image_files_batch
    image_buffer, height, width = _process_image(filename, coder)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 317, in _process_image
    image_data = f.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 102, in read
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 72, in _preread_check
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
ResourceExhaustedError: /imagenet2/raw-data/train/n12409470/n12409470_12184.jpg

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 389, in _process_image_files_batch
    image_buffer, height, width = _process_image(filename, coder)
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 317, in _process_image
    image_data = f.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 102, in read
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 72, in _preread_check
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
ResourceExhaustedError: /imagenet2/raw-data/train/n03978966/n03978966_12697.jpg

2017-03-20 08:51:17.086050: Finished writing all 8620676 images in data set.
Determining list of input files and labels from /imagenet2/raw-data/train/.
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 704, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 700, in main
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 597, in _process_dataset
  File "/home/ubuntu/tensorflow_models/models-master/inception/bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/build_imagenet_data.py", line 513, in _find_image_files
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 251, in get_matching_files
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
tensorflow.python.framework.errors.ResourceExhaustedError: /imagenet2/raw-data/train/n00006484
````

I am not sure what resource its exhausting. I am running it on CPU with 8 cores and 30GB of RAM. I kept monitoring the process using top and both memory and CPU levels were low during the process until the crash.

Does generating TF-Records require GPU?

Regards

**Comment by shlens** [comment]
TF-Records generation does not require a GPU. This seems like a read error.

Would you be able to check that your image files are readable in the inferred location? According to the error log, there should be some readable image files here:
`/imagenet2/raw-data/train/n03978966/n03978966_12697.jpg`

Additionally, please provide more details about what type of OS/platform/version you are using.

**Comment by redserpent7** [comment]
I checked all directories that are shown in the log.
All the images are readable, verified with imagemagick and PIL.

I am runnung TF 0.10 on Ubuntu 14.04 64-bit

**Comment by aselle** [comment]
Could you try writing a simple TensorFlow graph that tries to read that jpeg manually and do something with it. Then run that graph and see if it successfully reads. ImageMagick has a lot of code invested in opening images that are not quite within the spec?. Or there could be a bug in the TensorFlow decoder? In either case, it would be good to find out.

**Comment by redserpent7** [comment]
Can you give me an example of a good graph that can give me a good verification that the image is readable or not.

**Comment by aselle** [comment]
My guess is you are running out of file descriptors or disk space. see the resource exhausted exception.


Could you give more details?

What exact command line generates this error?
What version of tensorflow? from source? from binary?
What operating system? 
What architecture?

**Comment by redserpent7** [comment]
Sorry for the late reply, been extremely busy the past month. 
Yes it seems to be the file descriptors indeed. Increased the limit to 1000000 and it generated the records.

it did throw a couple of exceptions on some images but it has finished and did not terminate abruptly. I now have these training tf-records for the full imagenet data 21K classes and would like if someone can confirm if this is correct:

```
-rw-rw-r-- 1 ubuntu ubuntu  931089417 Apr 29 12:12 train-00000-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  409790818 Apr 29 12:14 train-00001-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  554035402 Apr 29 12:10 train-00128-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  939685141 Apr 29 12:12 train-00256-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  910998487 Apr 29 12:15 train-00257-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  913723915 Apr 29 12:17 train-00258-of-01024
-rw-rw-r-- 1 ubuntu ubuntu   33659740 Apr 29 12:17 train-00259-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  193418067 Apr 29 12:08 train-00384-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  909082335 Apr 29 12:12 train-00512-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  506756588 Apr 29 12:14 train-00513-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  499611567 Apr 29 12:10 train-00640-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  933976690 Apr 29 12:12 train-00768-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  923061417 Apr 29 12:16 train-00769-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  649488327 Apr 29 12:17 train-00770-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  935988859 Apr 29 12:12 train-00896-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  925880392 Apr 29 12:16 train-00897-of-01024
-rw-rw-r-- 1 ubuntu ubuntu  501654790 Apr 29 12:17 train-00898-of-01024
```

Not sure if this is how its supposed to be as I am assuming I should end up with 1024 files. Is the above correct?

**Comment by redserpent7** [comment]
Yeah I think I found out the issue. It seems whenever one of the processing threads hits a corrupt jpeg it drops the entire batch and when all the threads stop, the 'download_and_preprocess_imagenet' just reports that it has succeeded.

I added a try/except block inside the processing loop to skip any corrupt images and I got a total of 1024 training files and 128 validation files.
