### ISSUE TITLE
RNN Tutorial (PTB) NotImplementedError

### ISSUE THREAD

**Issue by andrewjylee** [tensorflow/models#1225]
## Please let us know which model this issue is about (specify the top-level directory)
I'm trying to run the recurrent neural network tutorial: https://www.tensorflow.org/tutorials/recurrent#run_the_code

When I run 
python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model=small

I get:
Traceback (most recent call last):
  File "ptb_word_lm.py", line 371, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "ptb_word_lm.py", line 331, in main
    train_input = PTBInput(config=config, data=train_data, name="TrainInput")
  File "ptb_word_lm.py", line 91, in __init__
    self.input_data, self.targets = reader.ptb_producer(data, batch_size, num_steps, name=name)
  File "/Volumes/Data/poet/ptb/models/tutorials/rnn/ptb/reader.py", line 105, in ptb_producer
    data = tf.reshape(raw_data[0 : batch_size * batch_len],
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/array_ops.py", line 139, in _SliceHelper
    "Negative stop indices are not currently supported")
NotImplementedError: Negative stop indices are not currently supported

Anyone else get this error?

**Comment by ebrevdo** [comment]
What version of tensorflow are you using?

**Comment by andrewjylee** [comment]
hm I'm seeing that I'm on 1.0.1 now, I'm not sure if I was on 1.0.1 when I ran that example though... :/

**Comment by skye** [comment]
Can you rerun the example and confirm you're still seeing the same problem? Thanks.

**Comment by andrewjylee** [comment]
I'm sorry, I was on version 0.7.1. Updated to 1.0.1 and problem is not there. Sorry, thanks, closing this thread.
