### ISSUE TITLE
[textsum] running example error

### ISSUE THREAD

**Issue by Jacksonlark** [tensorflow/models#1237]
using model https://github.com/tensorflow/models/tree/master/textsum

and bazel build -c opt --config=cuda textsum/...

when I running likes:
./bazel-bin/textsum/seq2seq_attention --mode=train --article_key=article --abstract_key=abstract --data_path=textsum/data/data --vocab_path=textsum/data/vocab --log_root=textsum/log_root --train_dir=textsum/log_root/train

ERROR happens:(tensorflow1.0 and cpu only)

Fresh to tensorflow, so ask for help

Traceback (most recent call last):
  File "/Users/***/machineLearning/tensorflow.models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
    tf.app.run()
  File "/Users/***/anaconda/envs/tensorflow_1.0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/***/machineLearning/tensorflow.models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 196, in main
    _Train(model, batcher)
  File "/Users/***/machineLearning/tensorflow.models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 85, in _Train
    model.build_graph()
  File "/Users/***/machineLearning/tensorflow.models/textsum/seq2seq_attention_model.py", line 295, in build_graph
    self._add_seq2seq()
  File "/Users/***/machineLearning/tensorflow.models/textsum/seq2seq_attention_model.py", line 235, in _add_seq2seq
    decoder_outputs, targets, loss_weights, sampled_loss_func)
  File "/Users/***/machineLearning/tensorflow.models/textsum/seq2seq_lib.py", line 84, in sampled_sequence_loss
    average_across_timesteps=average_across_timesteps))
  File "/Users/***/machineLearning/tensorflow.models/textsum/seq2seq_lib.py", line 49, in sequence_loss_by_example
    crossent = loss_function(inp, target)
  File "/Users/***/machineLearning/tensorflow.models/textsum/seq2seq_attention_model.py", line 231, in sampled_loss_func
    hps.num_softmax_samples, vsize)
  File "/Users/***/anaconda/envs/tensorflow_1.0/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 1191, in sampled_softmax_loss
    name=name)
  File "/Users/***/anaconda/envs/tensorflow_1.0/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 974, in _compute_sampled_logits
    array_ops.reshape(true_w, new_true_w_shape))
  File "/Users/***/anaconda/envs/tensorflow_1.0/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 357, in multiply
    return gen_math_ops._mul(x, y, name)
  File "/Users/***/anaconda/envs/tensorflow_1.0/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1625, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/Users/***/anaconda/envs/tensorflow_1.0/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 522, in apply_op
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int32 of argument 'x'.

**Comment by xtr33me** [comment]
@Jacksonlark Just curious, so when you look at the local copy of **seq2seq_attention_model.py** are you seeing, in your definition of **sampled_loss_func**, the call to **tf.nn.sampled_softmax_loss** with the params **labels** and **inputs** in the order shown below?  The reason I ask, is I had the same issue you had and the swapping of those to align with the modded API worked for me.  This was the fix checked that I believe was checked in a couple days ago that you referenced. 

```

def sampled_loss_func(inputs, labels):
          with tf.device('/cpu:0'):  # Try gpu.
            labels = tf.reshape(labels, [-1, 1])
            return tf.nn.sampled_softmax_loss(w_t, v, labels, inputs,
                           hps.num_softmax_samples, vsize)
```

**Comment by Jacksonlark** [comment]
@xtr33me 
Yeah, swapping inputs and labels worked. 
After this issue. I found this error has been checked. But have not been fixed.
