### ISSUE TITLE
Skip thoughts example cannot load pretrained model

### ISSUE THREAD

**Issue by bowu** [tensorflow/models#1260]
I followed the tutorial to run the skip thoughts model and could successfully load vocab.txt, embeddings.npy and so on, but couldn't load the pretrained model. The output I got is:
/home/bwu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Using TensorFlow backend.
Loading unidirectional model...
INFO:tensorflow:Reading vocabulary from /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//vocab.txt
INFO:tensorflow:Loaded vocabulary with 930914 words.
INFO:tensorflow:Loading embedding matrix from /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//embeddings.npy
INFO:tensorflow:Loaded embedding matrix with shape (930914, 620)
INFO:tensorflow:Building model.
Traceback (most recent call last):
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 117, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 91, in main
    FLAGS.uni_embeddings_file, FLAGS.uni_checkpoint_path)
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/encoder_manager.py", line 84, in load_model
    checkpoint_path)
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/skip_thoughts_encoder.py", line 153, in build_graph_from_config
    return self._create_restore_fn(checkpoint_path, saver)
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/skip_thoughts_encoder.py", line 125, in _create_restore_fn
    raise ValueError("No checkpoint file found in: %s" % checkpoint_path)
ValueError: No checkpoint file found in: /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02/

The pretrained models are in the directory, which is why the loading of vocab.txt was successful.

**Comment by aselle** [comment]
What did you run exactly? Can you show a list of the directory 
```
/home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02/
```
so we can see what files are in there?

**Comment by cshallue** [comment]
You need to provide the full path to the model, which in this case I believe would be 

```
/home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02/model.ckpt-501424
```

**Comment by bowu** [comment]
bwu@bwuserv2:~/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02$ ls -lh
total 5.8G
-rw-r----- 1 bwu bwu 4.4G Mar  9 22:52 embeddings.npy
-rw-r----- 1 bwu bwu 1.5G Mar  9 22:47 model.ckpt-501424.data-00000-of-00001
-rw-r----- 1 bwu bwu 4.4K Mar  9 22:46 model.ckpt-501424.index
-rw-r----- 1 bwu bwu 3.2M Mar  9 22:46 model.ckpt-501424.meta
-rw-r----- 1 bwu bwu 7.7M Mar  9 22:51 vocab.txt

I tried what cshallue suggested. Here is my script:

CHECKPOINT_PATH=/home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02/
VOCAB_FILE=${CHECKPOINT_PATH}/vocab.txt
EMBEDDINGS_FILE=${CHECKPOINT_PATH}/embeddings.npy
EVAL_DATA_DIR=/home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/eval_data/data/customerr/
../bazel-bin/skip_thoughts/evaluate \
  --eval_task=CR \
  --data_dir=${EVAL_DATA_DIR} \
  --uni_vocab_file=${VOCAB_FILE} \
  --uni_embeddings_file=${EMBEDDINGS_FILE} \
  --uni_checkpoint_path=${CHECKPOINT_PATH}/model.ckpt-501424

bwu@bwuserv2:~/ResearchProjects/tf_models/skip_thoughts/skip_thoughts$ ./myrun.sh
Using TensorFlow backend.
Loading unidirectional model...
INFO:tensorflow:Reading vocabulary from /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//vocab.txt
INFO:tensorflow:Loaded vocabulary with 930914 words.
INFO:tensorflow:Loading embedding matrix from /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//embeddings.npy
INFO:tensorflow:Loaded embedding matrix with shape (930914, 620)
INFO:tensorflow:Building model.
INFO:tensorflow:Loading model from checkpoint: /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
INFO:tensorflow:Restoring parameters from /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.684292: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.685773: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.688156: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.690463: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.692053: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.692866: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.694443: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.696159: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.698656: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.699381: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.701881: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.702590: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
2017-03-28 19:34:41.703919: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
Traceback (most recent call last):
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 117, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 91, in main
    FLAGS.uni_embeddings_file, FLAGS.uni_checkpoint_path)
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/encoder_manager.py", line 87, in load_model
    restore_model(sess)
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/skip_thoughts_encoder.py", line 130, in _restore_fn
    saver.restore(sess, checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 786, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 994, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1044, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1064, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
       	 [[Node: save/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_9/tensor_names, save/RestoreV2_9/shape_and_slices)]]

Caused by op u'save/RestoreV2_9', defined at:
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 117, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 91, in main
    FLAGS.uni_embeddings_file, FLAGS.uni_checkpoint_path)
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/encoder_manager.py", line 84, in load_model
    checkpoint_path)
  File "/home/bwu/ResearchProjects/tf_models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/skip_thoughts_encoder.py", line 151, in build_graph_from_config
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/bwu/ResearchProjects/tf_models/skip_thoughts/skip_thoughts/pretrained/skip_thoughts_uni_2017_02_02//model.ckpt-501424
       	 [[Node: save/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_9/tensor_names, save/RestoreV2_9/shape_and_slices)]]

**Comment by cshallue** [comment]
@aselle do you know what this error means? The path to the model checkpoint seems correct (except for the extra "/") and this command works for me.

**Comment by ankitarya10** [comment]
@bowu @aselle @cshallue  Note sure if something changed in the pretrained script, but I am getting 
embedding vector of shape (20000,620) which is much smaller the size of the vocabulary and not matching what @bowu  pasted.

INFO: Found 1 target...
Target //skip_thoughts:vocabulary_expansion up-to-date:
  bazel-bin/skip_thoughts/vocabulary_expansion
INFO: Elapsed time: 0.108s, Critical Path: 0.00s
INFO:tensorflow:Loading skip-thoughts embedding matrix from /home/icarus/skip_thoughts27/pretrained/skip_thoughts_uni_2017_02_02/model.ckpt-501424
INFO:tensorflow:Loaded skip-thoughts embedding matrix of shape (20000, 620)

**Comment by ankitarya10** [comment]
Has the vocabulary expansion already been done on the pre-trained models ?

**Comment by cshallue** [comment]
@ankitarya10 yes, the vocabulary expansion has already been done on the pre-trained models

**Comment by bowu** [comment]
It is indeed because of the extra "/" in the path. Now it works. Thanks so much!

**Comment by bowu** [comment]
To help others, the extra "/" is not a problem for loading vocab files, but it is a problem for loading the pretrained model.

**Comment by cshallue** [comment]
@bowu great! Good to know about the "/" subtlety for the future.
