### ISSUE TITLE
skip_thoughts vocabulary expansion fails when loading vocabulary from vocab.txt of skip_thoughts_uni_2017_02_02

### ISSUE THREAD

**Issue by ankitarya10** [tensorflow/models#1268]
## Please let us know which model this issue is about (specify the top-level directory)
https://github.com/tensorflow/models/skip_thoughts

there is empty line on line 677445 of vocab.txt, where it throws as assesrtion error:

Traceback (most recent call last):
  File "/home/icarus/skip_thoughts/bazel-bin/skip_thoughts/vocabulary_expansion.runfiles/__main__/skip_thoughts/vocabulary_expansion.py", line 205, in <module>
    tf.app.run()
  File "/home/icarus/anaconda2/envs/deep_learning/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/icarus/skip_thoughts/bazel-bin/skip_thoughts/vocabulary_expansion.runfiles/__main__/skip_thoughts/vocabulary_expansion.py", line 181, in main
    skip_thoughts_vocab = _load_vocabulary(FLAGS.skip_thoughts_vocab)
  File "/home/icarus/skip_thoughts/bazel-bin/skip_thoughts/vocabulary_expansion.runfiles/__main__/skip_thoughts/vocabulary_expansion.py", line 115, in _load_vocabulary
    assert word not in vocab, "Attempting to add word twice: %s" % word
AssertionError: Attempting to add word twice:

Any reason for the empty line to be there in the first place ?

**Comment by ankitarya10** [comment]
Another occurrence on line 918116. Function works fine after removing the empty lines.

**Comment by cshallue** [comment]
Vocabulary expansion has already been done on the pretrained models, so you can skip this step

**Comment by ankitarya10** [comment]
@cshallue I got confused as vocab.txt size is much smaller than google word2vec vocab size. Is there a reason why ?

**Comment by cshallue** [comment]
The word2vec model has 3M words, but many of those are bigrams (i.e. word pairs) that we don't use for the skip thoughts model. We are left with about 930k words:
```
wc -l vocab.txt
930913 vocab.txt
```

**Comment by shmilyhh** [comment]
@cshallue But the model shape is still (20000, 620). How does it happen?
