### ISSUE TITLE
The RNN Tutorial Code can't run in anaconda with windows

### ISSUE THREAD

**Issue by sweetmilkcat** [tensorflow/models#1269]
I try to  run Recurrent Neural Networks Tutorial Code in anaconda3   with windows, but I get the following error :
python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model=small

Traceback (most recent call last):
  File "ptb_word_lm.py", line 71, in <module>
    "A type of model. Possible options are: small, medium, large.")
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 80, in DEFINE_string
    _define_helper(flag_name, default_value, docstring, str)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 65, in _define_helper
    type=flagtype)
  File "C:\Anaconda3\lib\argparse.py", line 1344, in add_argument
    return self._add_action(action)
  File "C:\Anaconda3\lib\argparse.py", line 1707, in _add_action
    self._optionals._add_action(action)
  File "C:\Anaconda3\lib\argparse.py", line 1548, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "C:\Anaconda3\lib\argparse.py", line 1358, in _add_action
    self._check_conflict(action)
  File "C:\Anaconda3\lib\argparse.py", line 1497, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "C:\Anaconda3\lib\argparse.py", line 1506, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --model: conflicting option string: --model
What does it mean? please help me to solve this problem. thanks.
Tensorflow version:'0.12.0-rc0'

**Comment by nealwu** [comment]
Hi, please uninstall your TensorFlow version and install TensorFlow 1.0, and let us know if the problem is still happening.

**Comment by sweetmilkcat** [comment]
Hi, I uninstall TensorFlow and install TensorFlow 1.0.，but the problem is still happening.

**Comment by sweetmilkcat** [comment]
when run following code ,I get a new problem. 
cd C:/models/tutorials/rnn/ptb
python ptb_word_lm.py --data_path=C:\tmp\simple-examples\data\ --model=small
Traceback (most recent call last):
  File "ptb_word_lm.py", line 385, in <module>
    tf.app.run()
  File "D:\anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 332, in main
    raw_data = reader.ptb_raw_data(FLAGS.data_path)
  File "C:\models\tutorials\rnn\ptb\reader.py", line 73, in ptb_raw_data
    word_to_id = _build_vocab(train_path)
  File "C:\models\tutorials\rnn\ptb\reader.py", line 34, in _build_vocab
    data = _read_words(filename)
  File "C:\models\tutorials\rnn\ptb\reader.py", line 30, in _read_words
    return f.read().decode("utf-8").replace("\n", "<eos>").split()
AttributeError: 'str' object has no attribute 'decode'
please help me......

**Comment by nealwu** [comment]
Looks like a Python 3 specific error to me. Try removing the `.decode("utf-8")`?

**Comment by jart** [comment]
This question might be more appropriate for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).

**Comment by selay01** [comment]
File ".../reader.py", line 31, in _read_words
    return f.read().decode("utf-8").replace("\n", "<eos>").split()
AttributeError: 'str' object has no attribute 'decode'

This is a Python 3 error to me. Removing the .decode("utf-8") works.

**Comment by shivadvg19** [comment]
Yes I too got the same error after removing .decode("utf-8) worked for me.
