### ISSUE TITLE
[syntaxnet, dragnn] bazel test ... failed in CentOS 7 

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#1271]
i reported a similar issue for OS X ( https://github.com/tensorflow/models/issues/1201 ). 
but, this case is for CentOS 7.

- environment
```
CentOS 7 : CentOS Linux release 7.2.1511 (Core)
syntaxnet : c15fada28113eca32dc98d6e3bec4755d0d5b4c2 ( 2017. 3. 27 )
python : 2.7.10
bazel : 0.4.3
swig : 3.0.7
protobuf==3.0.0b2
numpy==1.11.2
mock==2.0.0
asciitree==0.3.3
pygraphviz==1.3.1

tensorflow
./configure
  : default setting
  : no jemalloc, no OpenGL, enable GPU, no Clould, no JIT
  : python site-packages == /home/username/.local/lib/python/site-packages
```

- errors
```
//syntaxnet/util:registry_test                                           PASSED in 2.1s
//syntaxnet:whole_sentence_features_test                                 PASSED in 0.0s
//util/utf8:unicodetext_unittest                                         PASSED in 0.0s
//dragnn/python:graph_builder_test                                       FAILED in 137.4s
  /home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log
//dragnn/python:render_parse_tree_graphviz_test                          FAILED in 7.2s
  /home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log
//dragnn/python:render_spec_with_graphviz_test                           FAILED in 7.3s
  /home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/render_spec_with_graphviz_test/test.log
//dragnn/python:visualization_test                                       FAILED in 2.1s
  /home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/visualization_test/test.log
//examples/dragnn:test_run_all_tutorials                                 FAILED in 7.9s
  /home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log

Executed 52 out of 52 tests: 47 tests pass and 5 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

- examples
```
ERROR: testSimpleTaggerWrappedLSTM (__main__.GraphBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/graph_builder_test.runfiles/__main__/dragnn/python/graph_builder_test.py", line 481, in testSimpleTaggerWrappedLSTM
    'simple_tagger_wrapped_lstm_master_spec.textproto')
  File "/home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/graph_builder_test.runfiles/__main__/dragnn/python/graph_builder_test.py", line 462, in RunFullTrainingAndInference
    self.assertProtoEquals(expected_sentences[i], pred_sentence)
  File "/home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/graph_builder_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 223, in assertProtoEquals
    descriptor_pool=descriptor_pool.Default())
TypeError: Merge() got an unexpected keyword argument 'descriptor_pool'

...

ERROR: testSampleTraceSerialization (__main__.VisualizationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/visualization_test.runfiles/__main__/dragnn/python/visualization_test.py", line 54, in testSampleTraceSerialization
    json = visualization.parse_trace_json(_get_trace_proto_string())
  File "/home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/visualization_test.runfiles/__main__/dragnn/python/visualization.py", line 68, in parse_trace_json
    as_proto, preserving_proto_field_name=True)
TypeError: MessageToJson() got an unexpected keyword argument 'preserving_proto_field_name'

```

**Comment by markomernick** [comment]
It looks like you may need to upgrade your proto2 dependency to the most recent release.

**Comment by dsindex** [comment]
@markomernick thank you :) 

after upgrade protobuf3.0.0b2 -> 3.2.0, 
number of errors has decreased 5 to 2. 

the remained errors look like : 
```
vi /home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log


exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/render_parse_tree_graphviz_test.runfiles/__main__/dragnn/python/render_parse_tree_graphviz_test.py", line 23, in <module>
    from dragnn.python import render_parse_tree_graphviz
  File "/home/username/.cache/bazel/_bazel_hanadmin/356428332ee20bfb1efe3b3dc1661ee3/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/render_parse_tree_graphviz_test.runfiles/__main__/dragnn/python/render_parse_tree_graphviz.py", line 25, in <module>
    import pygraphviz
ImportError: No module named pygraphviz

```

but i already installed `pygraphviz` using the command : 
```
$ pip install pygraphviz --user
```

it seems that 'render_parse_tree_graphviz' can't find `per-user site-packages`. 
so i removed pygraphviz and reinstall it system-wise.

finally all works fine. 
```
//util/utf8:unicodetext_unittest                                (cached) PASSED in 0.0s
//dragnn/python:render_parse_tree_graphviz_test                          PASSED in 1.5s
//dragnn/python:render_spec_with_graphviz_test                           PASSED in 1.5s

Executed 2 out of 52 tests: 52 tests pass.
```

**Comment by mjakubicek** [comment]
I just hit this as well -- can you please correct the installation instructions which explicitly mention that one should install protobuf 3.0.0b2 to say that 3.2.0 is required?

**Comment by rlucca** [comment]
I hit this too.

**Comment by q3452** [comment]
@mjakubicek Thanks, I ran into the same thing building on Ubuntu 16.04
