### ISSUE TITLE
Questions of run evaluator for dependency parsing

### ISSUE THREAD

**Issue by zhou-zh** [tensorflow/models#1355]
I hope run conll2017 baseline to predict dependency parsing , after trained the english model i got the parser_spec.textproto and the checkpoint.model. Then i started to run the evaluator.py in  /dragnn/tools/,
followed the guide i used those commands:
```
bazel run -c opt //dragnn/tools:evaluator -- \
  --master_spec="/home/zhiheng/models/syntaxnet/trained-english/parser_spec.textproto" \
  --checkpoint_file="/home/zhiheng/models/syntaxnet/trained-english/checkpoint.model" \
  --input_file="/home/zhiheng/data/UD_english/test_english.conllu
```
but it showed error as follows:
```
Traceback (most recent call last):
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/tools/evaluator.py", line 168, in <module>
    tf.app.run()
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/tools/evaluator.py", line 108, in main
    builder = graph_builder.MasterBuilder(master_spec, hyperparam_config)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/graph_builder.py", line 175, in __init__
    component_spec)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 182, in Create
    return _ResolveAndCreate(baseclass, path, subclass_name, *args, **kwargs)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 166, in _ResolveAndCreate
    subclass = _Create(baseclass, resolved_subclass_name, *args, **kwargs)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 131, in _Create
    return subclass(*args, **kwargs)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/component.py", line 116, in __init__
    self.network = self.make_network(self.spec.network_unit)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/component.py", line 143, in make_network
    return network_units.NetworkUnitInterface.Create(network_type, self)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 182, in Create
    return _ResolveAndCreate(baseclass, path, subclass_name, *args, **kwargs)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 166, in _ResolveAndCreate
    subclass = _Create(baseclass, resolved_subclass_name, *args, **kwargs)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 131, in _Create
    return subclass(*args, **kwargs)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/wrapped_units.py", line 234, in __init__
    super(LayerNormBasicLSTMNetwork, self).__init__(component)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/wrapped_units.py", line 102, in __init__
    component, init_layers=layers, init_context_layers=context_layers)
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/network_units.py", line 657, in __init__
    check.Gt(spec.size, 0, 'Invalid fixed feature size')
  File "/home/zhiheng/.cache/bazel/_bazel_zhiheng/7d6fd27fe29dcb09299b0785a4c85115/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/check.py", line 38, in Gt
    raise error('Expected (%s) > (%s): %s' % (lhs, rhs, message))
ValueError: Expected (0) > (0): Invalid fixed feature size
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```
My system is Ubuntu 14.04.3, bazel - 0.4.5
Thanks for any help! 
@calberti

**Comment by bogatyy** [comment]
Can you list the command you used to produce `parser_spec.textproto` and the contents of the file?
From the error message, seems that the spec is incomplete.

**Comment by hans** [comment]
I'm getting the same error when running the baseline models released for CoNLL 2017. Here's my invocation (running in the DRAGNN Docker container):

```
$ bazel run -c opt dragnn/tools:evaluator -- \
    --master_spec /conll2017/conll17/English/parser_spec.textproto \
    --checkpoint_file /conll2017/conll17/English/checkpoint \
    --input_file /conll2017/input.txt

INFO: Running command line: bazel-bin/dragnn/tools/evaluator --master_spec /conll2017/conll17/English/parser_spec.textproto --checkpoint_file /conll2017/conll17/English/checkpoint --input_file /conll2017/input.txt
INFO:tensorflow:Building the graph
INFO:tensorflow:[char_lstm] input_dropout_rate=1.0 recurrent_dropout_rate=0.8
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/tools/evaluator.py", line 168, in <module>
    tf.app.run()
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/tools/evaluator.py", line 108, in main
    builder = graph_builder.MasterBuilder(master_spec, hyperparam_config)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/graph_builder.py", line 175, in __init__
    component_spec)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 182, in Create
    return _ResolveAndCreate(baseclass, path, subclass_name, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 166, in _ResolveAndCreate
    subclass = _Create(baseclass, resolved_subclass_name, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 131, in _Create
    return subclass(*args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/component.py", line 116, in __init__
    self.network = self.make_network(self.spec.network_unit)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/component.py", line 143, in make_network
    return network_units.NetworkUnitInterface.Create(network_type, self)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 182, in Create
    return _ResolveAndCreate(baseclass, path, subclass_name, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 166, in _ResolveAndCreate
    subclass = _Create(baseclass, resolved_subclass_name, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/registry.py", line 131, in _Create
    return subclass(*args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/wrapped_units.py", line 234, in __init__
    super(LayerNormBasicLSTMNetwork, self).__init__(component)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/wrapped_units.py", line 102, in __init__
    component, init_layers=layers, init_context_layers=context_layers)
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/dragnn/python/network_units.py", line 657, in __init__
    check.Gt(spec.size, 0, 'Invalid fixed feature size')
  File "/root/.cache/bazel/_bazel_root/821bda42e7dedbfae9d936785dd2d125/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/tools/evaluator.runfiles/__main__/syntaxnet/util/check.py", line 38, in Gt
    raise error('Expected (%s) > (%s): %s' % (lhs, rhs, message))
ValueError: Expected (0) > (0): Invalid fixed feature size
```

**Comment by hans** [comment]
I re-ran the `make_parser_spec` script and it also does not output `size` keys in the resulting proto. Is there a mismatch in the code here? Or am I / are we doing something incorrectly?

**Comment by jingcangcang** [comment]
@bogatyy 
I also have the same problem. Can you tell us how to fix it? Thanks.

**Comment by continuesmile** [comment]
In fact , I didn't train the whole process，that is too long，I interrupted the process during the train，i use  the Ctrl +C  to stop it and triggered the KeyboardInterrupt，then i use the `parser_spec.textproto` to run the
evaluator. So is that caused the `parser_spec.textproto` incomplete？

**Comment by paul05100** [comment]
Test the following 2 flags : '--resource_dir=/conll2017/conll17/English' and '--complete_master_spec=true'

This completes the parser_spec.textproto  with the directory data.

flags.DEFINE_string('resource_dir', '',
                    'Optional base directory for resources in the master spec.')
flags.DEFINE_bool('complete_master_spec', False, 'Whether the master_spec '
                  'needs the lexicon and other resources added to it.')
....
if FLAGS.complete_master_spec:
    spec_builder.complete_master_spec(master_spec, None, FLAGS.resource_dir)

**Comment by karmel** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
