### ISSUE TITLE
GPU Instance  AttributeError: 'module' object has no attribute 'unstack'

### ISSUE THREAD

**Issue by leenabharambe** [tensorflow/models#1391]
I'm having system configurations as -
ubuntu 16.04
bazel 0.4.5
TensorFlow 1.0.0

I'm facing this issue-
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/models/summarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/tensorflow/models/summarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 196, in main
    _Train(model, batcher)
  File "/home/ubuntu/tensorflow/models/summarization/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 85, in _Train
    model.build_graph()
  File "/home/ubuntu/tensorflow/models/summarization/textsum/seq2seq_attention_model.py", line 296, in build_graph
    self._add_seq2seq()
  File "/home/ubuntu/tensorflow/models/summarization/textsum/seq2seq_attention_model.py", line 142, in _add_seq2seq
    encoder_inputs = tf.unstack(tf.transpose(self._articles))
AttributeError: 'module' object has no attribute 'unstack'

Can you please help me how to resolve it?

**Comment by girving** [comment]
Are you sure you're using TensorFlow 1.0.0?  `tf.unstack` doesn't exist in old versions of TensorFlow before 1.0.0.

**Comment by girving** [comment]
:)
