### ISSUE TITLE
GPU AWS Instance 59GB Memory- giving MemoryError while running Model

### ISSUE THREAD

**Issue by leenabharambe** [tensorflow/models#1398]
Hello,
I'm running this model from AWS instance. It is giving an error as:
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/tensorflow/models/summarization/textsum/batch_reader.py", line 136, in _FillInputQueue
    (article, abstract) = input_gen.next()
  File "/home/ubuntu/tensorflow/models/summarization/textsum/batch_reader.py", line 245, in _TextGenerator
    e = example_gen.next()
  File "/home/ubuntu/tensorflow/models/summarization/textsum/data.py", line 109, in ExampleGen
    example_str = struct.unpack('%ds' % str_len, reader.read(str_len))[0]
MemoryError

What will be the solution for this?

**Comment by leenabharambe** [comment]
System storage info is -
Filesystem      Size  Used Avail Use% Mounted on
udev             30G     0   30G   0% /dev
tmpfs           6.0G  8.9M  6.0G   1% /run
/dev/xvda1       30G   12G   18G  39% /
tmpfs            30G     0   30G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            30G     0   30G   0% /sys/fs/cgroup
tmpfs           6.0G     0  6.0G   0% /run/user/1000

NVIDIA status-
ubuntu@ip-172-31-28-161:~$ lspci | grep -i nvidia
00:1e.0 3D controller: NVIDIA Corporation GK210GL [Tesla K80] (rev a1)

What should be done to resolve the error?

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
