### ISSUE TITLE
A NameError given when use im2txt model

### ISSUE THREAD

**Issue by LtveG** [tensorflow/models#1411]
Ubuntu
My TensorFlow version is 1.1.0-rc1 and its installed from source
Bazel version is 0.4.5
python is 2.7

I want to try the im2txt,and download the model.ckpt-3000000 and word_counts.txt from Google
Then i use : 

```
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
```
The error form Terminal
```
INFO:tensorflow:Building model.
INFO:tensorflow:Initializing vocabulary from file: /home/sky/Lan/Tensorflow/im2txt/im2txt/word_counts.txt
Traceback (most recent call last):
  File "/home/sky/Lan/Tensorflow/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 86, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/sky/Lan/Tensorflow/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 56, in main
    vocab = vocabulary.Vocabulary(FLAGS.vocab_file)
  File "/home/sky/Lan/Tensorflow/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/vocabulary.py", line 49, in __init__
    reverse_vocab = [eval(line.split()[0]).decode() for line in reverse_vocab]
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined
```

The error : File "<string>", line 1, in <module>
NameError: name 'a' is not defined

I can't solve

**Comment by aselle** [comment]
Your line 49 seems to have been modified. Are you sure you are using the latest master from tensorflow/models...
https://github.com/tensorflow/models/blob/master/im2txt/im2txt/inference_utils/vocabulary.py#L49
Your code seems to have an `eval()` around the split.

**Comment by LtveG** [comment]
@aselle  Thank you very much! i has modified the it .
But it give other error:
`NotFoundError (see above for traceback): Tensor name "lstm/basic_lstm_cell/weights" not found in checkpoint files /home/sky/Lan/Tensorflow/im2txt/im2txt/model.ckpt-3000000` 
`[[Node: save/RestoreV2_381 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_381/tensor_names, save/RestoreV2_381/shape_and_slices)]]`
`tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lstm/basic_lstm_cell/weights" not found in checkpoint files /home/sky/Lan/Tensorflow/im2txt/im2txt/model.ckpt-3000000`

The traceback as : 

- File "/home/sky/Lan/Tensorflow/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 86, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/sky/Lan/Tensorflow/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 66, in main
    restore_fn(sess)
  File "/home/sky/Lan/Tensorflow/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 96, in _restore_fn
    saver.restore(sess, checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)

**Comment by PavlosMelissinos** [comment]
Hi, this looks like a compatibility issue.

You said you are on tensorflow v1.1. Which checkpoint files did you download? Please mind that the original ones do not work for v1.x.

Try downgrading to 0.12 or download and use the alternative 1M checkpoint that is offered [here](https://github.com/tensorflow/models/issues/466#issuecomment-295427641).

I've successfully tried both (the latter on 1.0 stable) for inference.

Hope this helps.

**Comment by KranthiGV** [comment]
@LtveG 
It certainly seems to be due to the difference in versions of tokenizer, etc.
If you use the model trained on older version of im2txt code, follow the steps at https://github.com/tensorflow/models/issues/466#issuecomment-254002590
There's also a trained model available which is trained using TF 1.0 [here](https://github.com/KranthiGV/Pretrained-Show-and-Tell-model). It would work without any changes, I believe.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by chih-hong** [comment]
tensorflow.python.framework.errors_impl.NotFoundError: /home/sca_test/workspace/im2txt/data/word_counts.txt; No such file or directory
how to solve it.
I also encountered the same problem.
Can teach me how to solve it?
