### ISSUE TITLE
Slim throws all Variables must have their device set: name: "global_step" after upgrade tensorflow to v1.0.0

### ISSUE THREAD

**Issue by tobiajo** [tensorflow/models#1419]
When running [Slim](https://github.com/tensorflow/models/tree/master/slim) with multiple worker replicas I get the following exception:
```
Traceback (most recent call last):
  File "train_image_classifier.py", line 594, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 396, in main
    train()
  File "train_image_classifier.py", line 590, in train
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 715, in train
    init_fn=init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 336, in __init__
    self._verify_setup()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 881, in _verify_setup
    "their device set: %s" % op)
ValueError: When using replicas, all Variables must have their device set: name: "global_step"
op: "VariableV2"
attr {
  key: "_class"
  value {
    list {
      s: "loc:@global_step"
    }
  }
}
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT64
  }
}
attr {
  key: "shape"
  value {
    shape {
    }
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}
```

The line numbers does not match because of that I have added [this](https://github.com/tobiajo/yarntf/commit/23fdddc8fcfb4a55a90ed8f692b0f44100c759df) to `train_image_classifier.py`.

@nathansilberman @sguada

**Comment by aselle** [comment]
http://stackoverflow.com/questions/38793718/distributed-tensorflow-valueerror-when-when-using-replicas-all-variables-mus

**Comment by tobiajo** [comment]
@aselle already tried that.

If I add a `with tf.device("/job:ps/task:0"):` block as follows:
```
# Create global_step
with tf.device(deploy_config.variables_device()):
  with tf.device("/job:ps/task:0"):
    global_step = slim.create_global_step()
```

I instead get the following error:
```
INFO:tensorflow:Starting Session.
INFO:tensorflow:Starting Queues.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnavailableError'>, {"created":"@1493329722.442957130","description":"EOF","file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
2017-04-27 21:48:42.458561: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458624: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458680: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458720: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458814: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458849: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458880: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458922: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458957: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.458986: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-04-27 21:48:42.459018: E tensorflow/core/distributed_runtime/master_session.cc:1414] Cleanup partition error: Unavailable: {"created":"@1493329722.457980157","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}

**Comment by tobiajo** [comment]
And with the `sync_replicas` flag set, I get:

```
Traceback (most recent call last):
  File "train_image_classifier.py", line 581, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 382, in main
    train()
  File "train_image_classifier.py", line 527, in train
    total_num_replicas=FLAGS.worker_replicas)
TypeError: __init__() got an unexpected keyword argument 'replica_id'
End of LogType:stderr
```

**Comment by tobiajo** [comment]
I get the gRPC error only if the `clone_on_cpu` flag is set.

With no boolean flags set, the workaround seems to solve issue so that I can run the example.

**Comment by aselle** [comment]
Sorry, I am unclear on exactly what you changed to make it work. Is it something that can be wrapped into a PR to fix the problem once and for all. I'd like to make sure nobody else hits this.

**Comment by tobiajo** [comment]
I created a PR, if the fix is not sufficient, please have some other do a PR.

**Comment by aselle** [comment]
Thanks for the PR, @sguada, will hopefully look at it soon.

**Comment by sguada** [comment]
Could you explain what is the problem?

**Comment by tobiajo** [comment]
The Slim model no longer works for distributed TensorFlow. This exception is thrown when using multiple workers. I attached [this example](https://github.com/tobiajo/yarntf/commit/23fdddc8fcfb4a55a90ed8f692b0f44100c759df) which show how I run it distributed. Where `yarntf.createClusterServer()` is just a wrapper around `tf.train.ClusterSpec()` and `tf.train.Server()`.

TensorFlowOnSpark had the same issue: https://github.com/yahoo/TensorFlowOnSpark/issues/46

**Comment by tobiajo** [comment]
The Slim model no longer works for distributed TensorFlow. This exception is thrown when using multiple workers. I attached [this modification of the original](https://github.com/tobiajo/yarntf/commit/23fdddc8fcfb4a55a90ed8f692b0f44100c759df) which show how I run it distributed. Where `yarntf.createClusterServer()` is just a wrapper around `tf.train.ClusterSpec()` and `tf.train.Server()`.

TensorFlowOnSpark had the same issue: https://github.com/yahoo/TensorFlowOnSpark/issues/46

**Comment by zack6514** [comment]
have this problem solved?

**Comment by tobiajo** [comment]
@zack6514 no

**Comment by stevve** [comment]
when this  problem occured to me, changing the order of my code help me to slove it, because some Variable define  outrange scope of  tf.device("/job:ps/task:0"), so I define some Variable(tf.Variable()) under tf.device,then it run correctly.

this is my error hint :
2017-09-12 08:54:33.343818: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:240] Started 
ValueError: When using replicas, all Variables must have their device set: name: "Variable"
op: "VariableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 5
      }
      dim {
        size: 5
      }
      dim {
        size: 1
      }
      dim {
        size: 32
      }
    }
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
