### ISSUE TITLE
issues with calling resnet on cognitive_mapping_and_planning

### ISSUE THREAD

**Issue by linpt** [tensorflow/models#1442]
Hi, folks also @s-gupta 

I'm trying to run CMP and reproduce results, but few problems appears.
Still there was no mentions on what platform that package was tested. 
I try to run on Ubuntu 14.04 and freshly installed 16.04.
TF version 1.1.0
CUDA 8.0, 
cudnn 5.0 (6.0 on 16.04)

example script 
CUDA_VISIBLE_DEVICES=0 LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64 PYTHONPATH='.' PYOPENGL_PLATFORM=egl \
  python scripts/script_nav_agent_release.py --config_name cmp.lmap_Msc.clip5.sbpd_d_r2r+bench_test \
  --logdir output/cmp.lmap_Msc.clip5.sbpd_d_r2r

in all those models cases 
error apears:

  File "scripts/script_nav_agent_release.py", line 256, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "scripts/script_nav_agent_release.py", line 90, in main
    _launcher(FLAGS.config_name, FLAGS.logdir)
  File "scripts/script_nav_agent_release.py", line 99, in _launcher
    _train(args)
  File "scripts/script_nav_agent_release.py", line 148, in _train
    batch_norm_is_training=True, summary_mode='train')
  File "/media/user/models/cognitive_mapping_and_planning/tfcode/cmp.py", line 392, in setup_to_run
    wt_decay=args.solver.wt_decay)
  File "/media/user/models/cognitive_mapping_and_planning/tfcode/cmp_utils.py", line 165, in fr_v2
    reuse=False, scope=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v2.py", line 211, in resnet_v2
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 227, in stack_blocks_dense
    rate=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v2.py", line 110, in bottleneck
    scope='shortcut')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 917, in convolution
    _reuse=reuse)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/convolutional.py", line 420, in __init__
    name=name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/convolutional.py", line 105, in __init__
    self.strides = utils.normalize_tuple(strides, rank, 'strides')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/utils.py", line 84, in normalize_tuple
    str(n) + ' integers. Received: ' + str(value))
ValueError: The `strides` argument must be a tuple of 2 integers. Received: depth_bottleneck

My not educated guess would be, different versions was used to test, in that I would like to know them.
And fixes for versions mentioned above would be appreciated.

Edit: also distillation.py file is missing in folder [tfcode](https://github.com/tensorflow/models/blob/master/cognitive_mapping_and_planning/scripts/script_distill.py#L49)

**Comment by povidanius** [comment]
Very interesting approach, but I also run into aforementioned problems when trying to run the code. scripts/scripts_download_pretrained_models.sh is not in the repository as well (pretrained models seem to be at https://github.com/tensorflow/models/tree/master/cognitive_mapping_and_planning/output)

**Comment by s-gupta** [comment]
Thanks for reporting these issues. Please find responses below:

1. Resnet issue (@povidanius , @linpt): I tested this code with the latest nightly build for tensorflow which includes commit [d82f8f818cec7a1099a7e680a30ba8f5f8ed2589](https://github.com/tensorflow/tensorflow/commit/d82f8f818cec7a1099a7e680a30ba8f5f8ed2589) which changes the interface for using resnet blocks. Switching to any version beyond this commit will fix this issue.

2. Missing scripts/scripts_download_pretrained_models.py (@povidanius): Thanks for pointing this out, I will fix the README to reflect this change.

3. Missing distillation.py (@linpt): This was an oversight, and I am working on seeing if I can get this released as well. In the meanwhile, you can use the already distilled models available from scripts/script_download_init_models.sh. Again you may need a relatively new tensorflow version to be able to read in and use this model. There was a bug that was fixed a couple of week ago which was causing error while loading this model.

**Comment by concretevitamin** [comment]
@linpt seems like the issues have been addressed.  Closing this for now as part of the triage process.  If you've found them not to work, feel free to reopen with new info.  Thanks!

**Comment by zhixy** [comment]
@s-gupta  I suffer the same issue, whether with TF 1.1.0 or 1.0.1, I think 1.1.0 is later than the commit [d82f8f818cec7a1099a7e680a30ba8f5f8ed2589](https://github.com/tensorflow/tensorflow/commit/d82f8f818cec7a1099a7e680a30ba8f5f8ed2589)

**Comment by zhixy** [comment]
test with 1.2.0rc0 and 1.2.0rc1, above issue disappeared but new problem appears, look at the following output:


> ERROR:root:Checkpoint_dir: output/cmp.lmap_Msc.clip5.sbpd_rgb_r2r
WARNING:tensorflow:From /home/xy/github/models/cognitive_mapping_and_planning/tfcode/nav_utils.py:101: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
WARNING:tensorflow:From /home/xy/github/models/cognitive_mapping_and_planning/tfcode/nav_utils.py:101: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
WARNING:tensorflow:From /home/xy/github/models/cognitive_mapping_and_planning/tfcode/cmp_utils.py:144: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
WARNING:tensorflow:From /home/xy/github/models/cognitive_mapping_and_planning/tfcode/cmp_utils.py:144: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
Traceback (most recent call last):
  File "scripts/script_nav_agent_release.py", line 253, in <module>
    app.run()
  File "/home/xy/github/models/cognitive_mapping_and_planning/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "scripts/script_nav_agent_release.py", line 89, in main
    _launcher(FLAGS.config_name, FLAGS.logdir)
  File "scripts/script_nav_agent_release.py", line 100, in _launcher
    _test(args)
  File "scripts/script_nav_agent_release.py", line 195, in _test
    summary_mode=args.control.test_mode)
  File "/home/xy/github/models/cognitive_mapping_and_planning/tfcode/cmp.py", line 388, in setup_to_run
    wt_decay=args.solver.wt_decay, stride=args.arch.fr_stride)
  File "/home/xy/github/models/cognitive_mapping_and_planning/tfcode/cmp_utils.py", line 149, in fr_v2
    arg_sc.values()[i]['normalizer_params']['updates_collections'] = updates_collections
KeyError: 'normalizer_params'

**Comment by linpt** [comment]
@zhixy I'm just comment, such part. There was comment, that in some usage, that variable set to None, so that means not using. So you can run it without it.

**Comment by tianzhuotao** [comment]
@s-gupta  thanks, after updating the resnet_util.py, my code works
