### ISSUE TITLE
What train_dir to use for Tensorflow imagenet_train to train from scratch?

### ISSUE THREAD

**Issue by quanghoc** [tensorflow/models#1459]
I am following the below page

https://github.com/tensorflow/models/tree/master/inception

I got to the point I have to run:

`bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/tmp/imagenet_data`

However, I got below error:

```
Traceback (most recent call last):
  File "/home/demo/anaconda3/envs/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>
    tf.app.run()
  File "/home/demo/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/demo/anaconda3/envs/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 35, in main
    tf.gfile.DeleteRecursively(FLAGS.train_dir)
  File "/home/demo/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 420, in delete_recursively
    pywrap_tensorflow.DeleteRecursively(compat.as_bytes(dirname), status)
  File "/home/demo/anaconda3/envs/tensorflow/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/demo/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /tmp/imagenet_train
```

My `DATA_DIR` is `/tmp/imagenet_data` from previous step `bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}"`

But what would be my train_dir? The doc doesn't mention it? Look like an empty folder is incorrect.

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by quanghoc** [comment]
I posted in Stackoverflow and they said to post it here

http://stackoverflow.com/questions/43910534/what-train-dir-to-use-for-tensorflow-imagenet-train-to-train-from-scratch#comment74854423_43910534

What I am trying to get is a better Documentation to explain `train_dir`. Can someone help?

**Comment by girving** [comment]
"They" in this case means someone random on the internet.

Cc @shlens.
