### ISSUE TITLE
Following instructions on OS X throws an error I don't quite understand

### ISSUE THREAD

**Issue by patrickmcguire** [tensorflow/models#146]
## Please let us know which model this issue is about (specify the top-level directory)
me-macbookpro2:syntaxnet me$   bazel test --linkopt=-headerpad_max_install_names \
>     syntaxnet/... util/utf8/...
......
Unhandled exception thrown during build; message: topLevelKey: TARGET_PATTERN:syntaxnet/...
alreadyReported: false
path to cycle:
TARGET_PATTERN:syntaxnet/...
RECURSIVE_PKG:rootedPath=[/Users/me/models/syntaxnet]/[syntaxnet], excludedPaths=<omitted>)
PACKAGE:syntaxnet
cycle:
PACKAGE:external
WORKSPACE_FILE:[/Users/me/models/syntaxnet]/[WORKSPACE]
SKYLARK_IMPORTS_LOOKUP:com.google.devtools.build.lib.skyframe.SkylarkImportLookupValue$SkylarkImportLookupKey@2dac75f5
AST_FILE_LOOKUP:@tf//tensorflow:tensorflow.bzl
PACKAGE_LOOKUP:@tf//tensorflow
REPOSITORY:@tf

INFO: Elapsed time: 0.412s
java.lang.IllegalStateException: topLevelKey: TARGET_PATTERN:syntaxnet/...
alreadyReported: false
path to cycle:
TARGET_PATTERN:syntaxnet/...
RECURSIVE_PKG:rootedPath=[/Users/me/models/syntaxnet]/[syntaxnet], excludedPaths=<omitted>)
PACKAGE:syntaxnet
cycle:
PACKAGE:external
WORKSPACE_FILE:[/Users/me/models/syntaxnet]/[WORKSPACE]
SKYLARK_IMPORTS_LOOKUP:com.google.devtools.build.lib.skyframe.SkylarkImportLookupValue$SkylarkImportLookupKey@2dac75f5
AST_FILE_LOOKUP:@tf//tensorflow:tensorflow.bzl
PACKAGE_LOOKUP:@tf//tensorflow
REPOSITORY:@tf

	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:188)
	at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:82)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:164)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
	at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
	at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.getTargetsToBuild(LegacyLoadingPhaseRunner.java:417)
	at com.google.devtools.build.lib.pkgcache.LegacyLoadingPhaseRunner.execute(LegacyLoadingPhaseRunner.java:134)
	at com.google.devtools.build.lib.buildtool.BuildTool.runLoadingPhase(BuildTool.java:401)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:165)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:334)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.doTest(TestCommand.java:119)
	at com.google.devtools.build.lib.runtime.commands.TestCommand.exec(TestCommand.java:104)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:371)
	at com.google.devtools.build.lib.runtime.BlazeRuntime$3.exec(BlazeRuntime.java:1016)
	at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:65)
	at com.google.devtools.build.lib.server.RPCServer.executeRequest(RPCServer.java:434)
	at com.google.devtools.build.lib.server.RPCServer.serve(RPCServer.java:229)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:975)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:772)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:55)

**Comment by patrickmcguire** [comment]
I made a mistake somewhere in the process and downloaded an ancient bazel version. Works fine now
