### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by xiaohuizheng** [tensorflow/models#1477]
E tensorflow/core/common_runtime/direct_session.cc:137] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615
Traceback (most recent call last):
  File "resnet_main.py", line 247, in <module>
    tf.app.run()
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "resnet_main.py", line 240, in main
    train(hps)
  File "resnet_main.py", line 146, in train
    config=tf.ConfigProto(allow_soft_placement=True)) as mon_sess:
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 315, in MonitoredTrainingSession
    return MonitoredSession(session_creator=session_creator, hooks=all_hooks)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 601, in __init__
    session_creator, hooks, should_recover=True)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 434, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 767, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 772, in _create_session
    return self._sess_creator.create_session()
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 494, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 375, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 256, in prepare_session
    config=config)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 161, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1187, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 552, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/zhengxiaohui/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

**Comment by ali01** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because  it is really difficult to help without that information. Thanks!

**Comment by karmel** [comment]
Automatically closing due to lack of activity. Please re-open if there are further updates.
