### ISSUE TITLE
resnet_v1_test.py Failing

### ISSUE THREAD

**Issue by richardmarcum** [tensorflow/models#1484]
### System information
- **What is the top-level directory of the model you are using**:
models/slim/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Anaconda
- **TensorFlow version (use command below)**:
1.1
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
python nets/resnet_v1_test.py

### Describe the problem
I am trying to run the script to test the resnet_v1 network i.e. resnet_v1_test.py 
However, this fails.  I have not modified this file in anyway.

### Source code / logs
======================================================================
ERROR: testRootlessFullyConvolutionalEndpointShapes (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 338, in testRootlessFullyConvolutionalEndpointShapes
    scope='resnet')
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 280, in _resnet_small
    scope=scope)
  File "nets/resnet_v1.py", line 204, in resnet_v1
    logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2259, in squeeze
    return gen_array_ops._squeeze(input, axis, name)
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3378, in _squeeze
    squeeze_dims=squeeze_dims, name=name)
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/richard/.anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 16 for 'resnet/SpatialSqueeze' (op: 'Squeeze') with input shapes: [2,16,16,10].

======================================================================
ERROR: testEndPointsV1 (__main__.ResnetUtilsTest)
Test the end points of a tiny v1 bottleneck network.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 169, in testEndPointsV1
    _, end_points = self._resnet_plain(inputs, blocks, scope='tiny')
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 159, in _resnet_plain
    end_points = dict(tf.get_collection('end_points'))
TypeError: cannot convert dictionary update sequence element #0 to a sequence

======================================================================
FAIL: testAtrousFullyConvolutionalUnknownHeightWidth (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 441, in testAtrousFullyConvolutionalUnknownHeightWidth
    [batch, None, None, 32])
AssertionError: Lists differ: [2, 32] != [2, None, None, 32]

First differing element 1:
32
None

Second list contains 2 additional elements.
First extra element 2:
None

- [2, 32]
+ [2, None, None, 32]

======================================================================
FAIL: testClassificationEndPoints (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 290, in testClassificationEndPoints
    self.assertTrue(logits.op.name.startswith('resnet/logits'))
AssertionError: False is not true

======================================================================
FAIL: testFullyConvolutionalUnknownHeightWidth (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 422, in testFullyConvolutionalUnknownHeightWidth
    [batch, None, None, 32])
AssertionError: Lists differ: [2, 32] != [2, None, None, 32]

First differing element 1:
32
None

Second list contains 2 additional elements.
First extra element 2:
None

- [2, 32]
+ [2, None, None, 32]

======================================================================
FAIL: testUnknownBatchSize (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richard/gitFiles/TensorFlow/slim/nets/resnet_v1_test.py", line 405, in testUnknownBatchSize
    self.assertTrue(logits.op.name.startswith('resnet/logits'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 17 tests in 31.426s

FAILED (failures=4, errors=5)

**Comment by skye** [comment]
@nathansilberman

**Comment by sguada** [comment]
It should be fixed at head now, please re-open if it is not.
