### ISSUE TITLE
[neural_gpu] [failure] vocab_size=40000, multi GPUs

### ISSUE THREAD

**Issue by ip01** [tensorflow/models#1502]
### System information
- **What is the top-level directory of the model you are using**:
neural_gpu
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux 3fc345ec6592 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.2 LTS (Xenial Xerus)"
(docker host - Ubuntu 14.02)
- **TensorFlow installed from (source or binary)**:
from source
- **TensorFlow version (use command below)**:
tf.VERSION = 1.1.0-rc2
tf.GIT_VERSION = unknown
tf.COMPILER_VERSION = unknown
- **Bazel version (if compiling from source)**:
Build label: 0.4.5
- **CUDA/cuDNN version**:
Cuda release 8.0, V8.0.61
cuDNN 6.0.20
- **GPU model and memory**:
DGX-1 (8xP-100, 16276MiB each)
NVIDIA Driver Version: 375.66
- **Exact command to reproduce**:
`python neural_gpu_trainer.py --problem=wmt --vocab_size=40000 --nmaps=256 --vec_size=256 --curriculum_seq=1.0 --max_length=60 --data_dir=/TF-Common/seq2seq-WMT15 --num_gpus=4`

### Describe the problem
` --vocab_size=40000 --num_gpus=4` fails (apparently, in gpu_util.cc PrepareCopy) with ""Dst tensor is not initialized." mesage
Has to be mentioned that both ` --vocab_size=16 --num_gpus=4` and ` --vocab_size=40000 --num_gpus=1` do not fail.

### Source code / logs
```
         [[Node: gpu1/gradients/gpu1/while_1/mul_1_grad/mul/StackPush = StackPush[T=DT_FLOAT, _class=["loc:@gpu1/while_1/dropout/mul", "loc:@gpu1/while_1/mul_1"], swap_memory=true, _device="/job:localhost/replica:0/task:0/gpu:1"](gpu1/gradients/gpu1/while_1/mul_1_grad/mul/RefEnter, gpu1/while_1/dropout/mul, ^gpu1/gradients/Add)]]
Traceback (most recent call last):
  File "neural_gpu_trainer.py", line 1029, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "neural_gpu_trainer.py", line 1022, in main
    train()
  File "neural_gpu_trainer.py", line 731, in train
    update_mem=True, state=state)
  File "/TF-Common/models/neural_gpu/neural_gpu.py", line 719, in step
    res = sess.run([self.after_enc_step] + feed_out, feed_in)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[Node: gpu1/gradients/gpu1/while_1/mul_1_grad/mul/StackPush = StackPush[T=DT_FLOAT, _class=["loc:@gpu1/while_1/dropout/mul", "loc:@gpu1/while_1/mul_1"], swap_memory=true, _device="/job:localhost/replica:0/task:0/gpu:1"](gpu1/gradients/gpu1/while_1/mul_1_grad/mul/RefEnter, gpu1/while_1/dropout/mul, ^gpu1/gradients/Add)]]
         [[Node: gpu0/gradients/gpu0/while_1/Gather/Enter_grad/b_acc_7/_663 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_19407_gpu0/gradients/gpu0/while_1/Gather/Enter_grad/b_acc_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'gpu1/gradients/gpu1/while_1/mul_1_grad/mul/StackPush', defined at:
  File "neural_gpu_trainer.py", line 1029, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "neural_gpu_trainer.py", line 1022, in main
    train()
  File "neural_gpu_trainer.py", line 655, in train
    (train_set, dev_set, en_vocab_path, fr_vocab_path), sv, sess) = initialize()
  File "neural_gpu_trainer.py", line 349, in initialize
    model = make_ngpu(beam_size, True)
  File "neural_gpu_trainer.py", line 346, in make_ngpu
    do_layer_norm=FLAGS.layer_norm, beam_size=cur_beam_size, backward=back)
  File "/TF-Common/models/neural_gpu/neural_gpu.py", line 648, in __init__
    colocate_gradients_with_ops=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 540, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 346, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 540, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_grad.py", line 666, in _MulGrad
    return (array_ops.reshape(math_ops.reduce_sum(grad * y, rx), sx),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1061, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1498, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2500, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1273, in __init__
    self._control_flow_context.AddOp(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2143, in AddOp
    self._AddOpInternal(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2166, in _AddOpInternal
    real_x = self.AddValue(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2099, in AddValue
    real_val = grad_ctxt.grad_state.GetRealValue(val)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 986, in GetRealValue
    history_value = cur_grad_state.AddForwardAccumulator(cur_value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 874, in AddForwardAccumulator
    enter_acc, value, swap_memory=swap_enabled)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1602, in _stack_push
    swap_memory=swap_memory, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2500, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'gpu1/while_1/mul_1', defined at:
  File "neural_gpu_trainer.py", line 1029, in <module>
    tf.app.run()
[elided 4 identical lines from previous traceback]
  File "neural_gpu_trainer.py", line 346, in make_ngpu
    do_layer_norm=FLAGS.layer_norm, beam_size=cur_beam_size, backward=back)
  File "/TF-Common/models/neural_gpu/neural_gpu.py", line 602, in __init__
    parallel_iterations=1, swap_memory=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2766, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2595, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2545, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/TF-Common/models/neural_gpu/neural_gpu.py", line 595, in step_lambda
    step, i, 1, dec_t, out_ta, tgts, ml, nu, oi, bc)
  File "/TF-Common/models/neural_gpu/neural_gpu.py", line 400, in dec_step
    step = dec_substep(step, decided)
  File "/TF-Common/models/neural_gpu/neural_gpu.py", line 386, in dec_substep
    cutoff, "dcgru_%d" % layer, do_layer_norm)
  File "/TF-Common/models/neural_gpu/neural_gpu.py", line 140, in conv_gru
    return gate * mem + (1 - gate) * candidate
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1061, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1498, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2500, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Dst tensor is not initialized.
         [[Node: gpu1/gradients/gpu1/while_1/mul_1_grad/mul/StackPush = StackPush[T=DT_FLOAT, _class=["loc:@gpu1/while_1/dropout/mul", "loc:@gpu1/while_1/mul_1"], swap_memory=true, _device="/job:localhost/replica:0/task:0/gpu:1"](gpu1/gradients/gpu1/while_1/mul_1_grad/mul/RefEnter, gpu1/while_1/dropout/mul, ^gpu1/gradients/Add)]]
         [[Node: gpu0/gradients/gpu0/while_1/Gather/Enter_grad/b_acc_7/_663 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_19407_gpu0/gradients/gpu0/while_1/Gather/Enter_grad/b_acc_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

**Comment by lukaszkaiser** [comment]
I think it is just running out of memory and giving this strange message. Remember that in `neural_gpu_trainer` the effective batch size is `batch_size = FLAGS.batch_size * FLAGS.num_gpus` -- so if you're sticking to the default batch of 32 with 8 gpus, you're effectively running at batch 256. And the embeddings are not sharded, so they might incur large memory cost. Could you try with `--batch_size=4` or `--batch_size=8` to check if that works?

**Comment by ip01** [comment]
Thank you Lukasz, it is OOM indeed... Meaningfull memory allocation error handling in TF core would  be desirable anyway, but aparently your model is not the proper place to complain about it :-)

**Comment by lukaszkaiser** [comment]
Thanks for checking!
