### ISSUE TITLE
object_detection/models/faster_rcnn_resnet_v1_feature_extractor_test.py Broken !

### ISSUE THREAD

**Issue by darshanhegde** [tensorflow/models#1585]
Looks like resnet_v1 feature extractors are broken. Here is the log of running the test - ` python models/faster_rcnn_resnet_v1_feature_extractor_test.py`

```======================================================================
ERROR: test_extract_proposal_features_stride_eight (__main__.FasterRcnnResnetV1FeatureExtractorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "models/faster_rcnn_resnet_v1_feature_extractor_test.py", line 65, in test_extract_proposal_features_stride_eight
    preprocessed_inputs, scope='TestScope')
  File "/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 131, in extract_proposal_features
    return self._extract_proposal_features(preprocessed_inputs, scope)
  File "/models/object_detection/models/faster_rcnn_resnet_v1_feature_extractor.py", line 125, in _extract_proposal_features
    scope=var_scope)
  File "/models/slim/nets/resnet_v1.py", line 280, in resnet_v1_101
    reuse=reuse, scope=scope)
  File "/models/slim/nets/resnet_v1.py", line 204, in resnet_v1
    logits = tf.squeeze(net, [1, 2], name='SpatialSqueeze')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2281, in squeeze
    return gen_array_ops._squeeze(input, axis, name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3329, in _squeeze
    squeeze_dims=squeeze_dims, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 28 for 'TestScope/resnet_v1_101/resnet_v1_101/SpatialSqueeze' (op: 'Squeeze') with input shapes: [4,28,28,2048].

----------------------------------------------------------------------
```

**Comment by derekjchow** [comment]
Does [this PR](https://github.com/tensorflow/models/pull/1586) correct the issue for you?

**Comment by darshanhegde** [comment]
Yes. Perfect !
