### ISSUE TITLE
How to make label-map.pbtxt for object detction?

### ISSUE THREAD

**Issue by june9713** [tensorflow/models#1601]
Hello everyone.
I am trying to make my own object detction model.

But, I cant start script because I dont know how to make label-map.pbtxt file.

In "object_detection/g3doc/running_pets.md" file, there is a direction about how to run training.

python object_detection/create_pet_tf_record.py \
    --label_map_path=object_detection/data/pet_label_map.pbtxt \
    --data_dir=`pwd` \
    --output_dir=`pwd`

But tjis scrip make error when runnong because there os no label map file.

Please help me to make label map.
Thaks for reading!^^

**Comment by jch1** [comment]
@june9713 - There should be a label map file (it is here: https://github.com/tensorflow/models/blob/master/object_detection/data/pet_label_map.pbtxt)

Can you check that this file is there for you as well?  Are you running the script from the root directory?

**Comment by june9713** [comment]
@jch1 Thanks! I found it! I will try This one. Thank you!

**Comment by mjohnst** [comment]
I'm trying to modify an existing label map for my own class, but seeing an error.

My `businesscard_label_map.pbtxt`:
```
item {
  id: 0
  name: 'businesscard'
  display_name: 'Businesscard'
}
```

gives this error when I run `create_pascal_tf_record.py`:
```
Traceback (most recent call last):
  File "object_detection/create_pascal_tf_record.py", line 181, in <module>
    tf.app.run()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/create_pascal_tf_record.py", line 156, in main
    label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)
  File "/home/cortananvisionsvc/src/models/object_detection/utils/label_map_util.py", line 122, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/home/cortananvisionsvc/src/models/object_detection/utils/label_map_util.py", line 107, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 472, in Merge
    text.split('\n'),
TypeError: a bytes-like object is required, not 'str'
```
Using Python3.5 from anaconda
Any help would be greatly appreciated!

**Comment by splendor-kill** [comment]
@mjohnst use python 2.7 env

**Comment by mjohnst** [comment]
Thanks @splendor-kill this fixed my issue

**Comment by derekjchow** [comment]
@mjohnst could you exact command (with arguments) you used in the python3.5 env?

**Comment by mjohnst** [comment]
@derekjchow I ran this command (CVdevkit is a custom data set I created with the same directory structure and annotation format as VOCdevkit)
```
python object_detection/create_pascal_tf_record.py \
--data_dir=/home/mj/CVdevkit \
--year=VOC2012 \
--set=train \
--output_path=/home/mj/pascal_train.record \
--label_map_path=/home/mj/businesscard_label_map.pbtxt
```

```
> which python
/anaconda/envs/py35/bin/python
```

**Comment by radzfoto** [comment]
The problem in Python 3.x is that the you need to convert python strings into raw strings (e.g. raw_string=b'this is a python string') when you assign them to the tensorflow example feature list. If you already have a string variable, convert it to a utf8 byte string. Here's an example for both which I've tested with Python 3.5 and 3.6 with Tensorflow 1.2.1:

`
    import tensorflow
    from object_detection.utils import dataset_util

    encodetype = b'rgb'
    filename = 'afilename'
    filename_utf8 = image_filename.encode('utf8')

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/filename': dataset_util.bytes_feature(filename_utf8),
        'image/format': _string_feature(encodetype)}))
`

**Comment by Draichi** [comment]
@jch1 

> @june9713 - There should be a label map file (it is here: https://github.com/tensorflow/models/blob/master/object_detection/data/pet_label_map.pbtxt)

This link has CHANGED. correct link here:
https://github.com/tensorflow/models/blob/master/research/object_detection/data/pet_label_map.pbtxt

**Comment by abirnedia** [comment]
I am using python 3.6 while running your project I am having an error in the label_mapping_model as PY4jjavaerror.Below is the error report for your reference

Py4JJavaError Traceback (most recent call last)
in ()
4
5 # Fitting preparation pipeline
----> 6 labels_mapping_model = labels_mapping_pipeline.fit(train_df)
7
8 # Transforming labels column and adding id column

~\Anaconda3\lib\site-packages\pyspark\ml\base.py in fit(self, dataset, params)
130 return self.copy(params)._fit(dataset)
131 else:
--> 132 return self._fit(dataset)
133 else:
134 raise ValueError("Params must be either a param map or a list/tuple of param maps, "

~\Anaconda3\lib\site-packages\pyspark\ml\pipeline.py in _fit(self, dataset)
107 dataset = stage.transform(dataset)
108 else: # must be an Estimator
--> 109 model = stage.fit(dataset)
110 transformers.append(model)
111 if i < indexOfLastEstimator:

~\Anaconda3\lib\site-packages\pyspark\ml\base.py in fit(self, dataset, params)
130 return self.copy(params)._fit(dataset)
131 else:
--> 132 return self._fit(dataset)
133 else:
134 raise ValueError("Params must be either a param map or a list/tuple of param maps, "

~\Anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _fit(self, dataset)
286
287 def _fit(self, dataset):
--> 288 java_model = self._fit_java(dataset)
289 model = self._create_model(java_model)
290 return self._copyValues(model)

~\Anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _fit_java(self, dataset)
283 """
284 self._transfer_params_to_java()
--> 285 return self._java_obj.fit(dataset._jdf)
286
287 def _fit(self, dataset):

~\Anaconda3\lib\site-packages\py4j\java_gateway.py in call(self, *args)
1158 answer = self.gateway_client.send_command(command)
1159 return_value = get_return_value(
-> 1160 answer, self.gateway_client, self.target_id, self.name)
1161
1162 for temp_arg in temp_args:

~\Anaconda3\lib\site-packages\pyspark\sql\utils.py in deco(*a, **kw)
61 def deco(*a, **kw):
62 try:
---> 63 return f(*a, **kw)
64 except py4j.protocol.Py4JJavaError as e:
65 s = e.java_exception.toString()

~\Anaconda3\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
318 raise Py4JJavaError(
319 "An error occurred while calling {0}{1}{2}.\n".
--> 320 format(target_id, ".", name), value)
321 else:
322 raise Py4JError(

Py4JJavaError: An error occurred while calling o758.fit.
: java.lang.IllegalArgumentException
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:449)
at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:432)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:432)
at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:262)
at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:261)
at scala.collection.immutable.List.foreach(List.scala:381)
at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:261)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
at org.apache.spark.SparkContext.clean(SparkContext.scala:2292)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2066)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2092)
at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:939)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
at org.apache.spark.rdd.RDD.collect(RDD.scala:938)
at org.apache.spark.rdd.PairRDDFunctions$$anonfun$countByKey$1.apply(PairRDDFunctions.scala:370)
at org.apache.spark.rdd.PairRDDFunctions$$anonfun$countByKey$1.apply(PairRDDFunctions.scala:370)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
at org.apache.spark.rdd.PairRDDFunctions.countByKey(PairRDDFunctions.scala:369)
at org.apache.spark.rdd.RDD$$anonfun$countByValue$1.apply(RDD.scala:1208)
at org.apache.spark.rdd.RDD$$anonfun$countByValue$1.apply(RDD.scala:1208)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
at org.apache.spark.rdd.RDD.countByValue(RDD.scala:1207)
at org.apache.spark.ml.feature.StringIndexer.fit(StringIndexer.scala:140)
at org.apache.spark.ml.feature.StringIndexer.fit(StringIndexer.scala:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:214)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by abirnedia** [comment]
I am using python 3.6 while running your project I am having an error in the label_mapping_model as PY4jjavaerror.Below is the error report for your reference

Py4JJavaError Traceback (most recent call last)
in ()
4
5 # Fitting preparation pipeline
----> 6 labels_mapping_model = labels_mapping_pipeline.fit(train_df)
7
8 # Transforming labels column and adding id column

~\Anaconda3\lib\site-packages\pyspark\ml\base.py in fit(self, dataset, params)
130 return self.copy(params)._fit(dataset)
131 else:
--> 132 return self._fit(dataset)
133 else:
134 raise ValueError("Params must be either a param map or a list/tuple of param maps, "

~\Anaconda3\lib\site-packages\pyspark\ml\pipeline.py in _fit(self, dataset)
107 dataset = stage.transform(dataset)
108 else: # must be an Estimator
--> 109 model = stage.fit(dataset)
110 transformers.append(model)
111 if i < indexOfLastEstimator:

~\Anaconda3\lib\site-packages\pyspark\ml\base.py in fit(self, dataset, params)
130 return self.copy(params)._fit(dataset)
131 else:
--> 132 return self._fit(dataset)
133 else:
134 raise ValueError("Params must be either a param map or a list/tuple of param maps, "

~\Anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _fit(self, dataset)
286
287 def _fit(self, dataset):
--> 288 java_model = self._fit_java(dataset)
289 model = self._create_model(java_model)
290 return self._copyValues(model)

~\Anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _fit_java(self, dataset)
283 """
284 self._transfer_params_to_java()
--> 285 return self._java_obj.fit(dataset._jdf)
286
287 def _fit(self, dataset):

~\Anaconda3\lib\site-packages\py4j\java_gateway.py in call(self, *args)
1158 answer = self.gateway_client.send_command(command)
1159 return_value = get_return_value(
-> 1160 answer, self.gateway_client, self.target_id, self.name)
1161
1162 for temp_arg in temp_args:

~\Anaconda3\lib\site-packages\pyspark\sql\utils.py in deco(*a, **kw)
61 def deco(*a, **kw):
62 try:
---> 63 return f(*a, **kw)
64 except py4j.protocol.Py4JJavaError as e:
65 s = e.java_exception.toString()

~\Anaconda3\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
318 raise Py4JJavaError(
319 "An error occurred while calling {0}{1}{2}.\n".
--> 320 format(target_id, ".", name), value)
321 else:
322 raise Py4JError(

Py4JJavaError: An error occurred while calling o758.fit.
: java.lang.IllegalArgumentException
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:449)
at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:432)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:432)
at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:262)
at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:261)
at scala.collection.immutable.List.foreach(List.scala:381)
at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:261)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
at org.apache.spark.SparkContext.clean(SparkContext.scala:2292)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2066)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2092)
at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:939)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
at org.apache.spark.rdd.RDD.collect(RDD.scala:938)
at org.apache.spark.rdd.PairRDDFunctions$$anonfun$countByKey$1.apply(PairRDDFunctions.scala:370)
at org.apache.spark.rdd.PairRDDFunctions$$anonfun$countByKey$1.apply(PairRDDFunctions.scala:370)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
at org.apache.spark.rdd.PairRDDFunctions.countByKey(PairRDDFunctions.scala:369)
at org.apache.spark.rdd.RDD$$anonfun$countByValue$1.apply(RDD.scala:1208)
at org.apache.spark.rdd.RDD$$anonfun$countByValue$1.apply(RDD.scala:1208)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
at org.apache.spark.rdd.RDD.countByValue(RDD.scala:1207)
at org.apache.spark.ml.feature.StringIndexer.fit(StringIndexer.scala:140)
at org.apache.spark.ml.feature.StringIndexer.fit(StringIndexer.scala:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:214)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by sayakpaul** [comment]
I am wondering if anyone had the struggle to create the labelmap file for more than say, 50 classes. If one created a script to do that, it would be really helpful if that's shared here.

**Comment by quant61** [comment]
@sayakpaul
Example of converting python list to `label_map.pbtxt`
```python

from object_detection.protos.string_int_label_map_pb2 import StringIntLabelMap, StringIntLabelMapItem
from google.protobuf import text_format


def convert_classes(classes, start=1):
    msg = StringIntLabelMap()
    for id, name in enumerate(classes, start=start):
        msg.item.append(StringIntLabelMapItem(id=id, name=name))

    text = str(text_format.MessageToBytes(msg, as_utf8=True), 'utf-8')
    return text


if __name__ == '__main__':
    txt = convert_classes(['cat', 'dog', 'fox', 'squirrel'])
    print(txt)
    with open('label_map.pbtxt', 'w') as f:
        f.write(txt)
```
output(in both stdout and file):
```
item {
  name: "cat"
  id: 1
}
item {
  name: "dog"
  id: 2
}
item {
  name: "fox"
  id: 3
}
item {
  name: "squirrel"
  id: 4
}

```

**Comment by ahmetcetin** [comment]
using just python:
```
def convert_classes(classes, start=1):
    msg = ''
    for id, name in enumerate(classes, start=start):
        msg = msg + "item {\n"
        msg = msg + " id: " + str(id) + "\n"
        msg = msg + " name: '" + name + "'\n}\n\n"
    return msg[:-1]
```

```
label_map = convert_classes(labels)
with open(output_path + "tf_label_map.pbtxt", "w") as f:
    f.write(label_map)
    f.close()
```

**Comment by makansahurbebas** [comment]
> @june9713 - There should be a label map file (it is here: https://github.com/tensorflow/models/blob/master/object_detection/data/pet_label_map.pbtxt)
> 
> Can you check that this file is there for you as well? Are you running the script from the root directory?

For anyone looking, site is updated as they moved this to research folder.  https://github.com/tensorflow/models/blob/master/research/object_detection/data/pet_label_map.pbtxt

**Comment by Leci37** [comment]
**If you want to create _.pbtxt_ from panda DF** ,
 here is the script that has been useful to me 

```python

import re
import pandas as pd
import json

from object_detection.utils import label_map_util


df_cats = pd.read_csv("category_pandas.csv",  sep='\t')
df_cats = df_cats[['id','nombre', 'name', 'take']]                    #adapt 
df_cats = df_cats.rename(columns={'name': 'name_eng', 'nombre': 'name'}) #adapt 
df_cats['display_name'] = df_cats['name']                            #adapt 
df_cats['name'] = df_cats['name'].str.lower()

print("Custom the columns of the new .pbtxt")
df_cats = df_cats[['id', 'name', 'display_name']]
pd_json = df_cats.sort_values('id').to_json(orient='records')

dict_pbtxt = {}  # store our reformed records
print("CAREFULL the 0 id is not valid for create a .pbtxt")
for record in json.loads(pd_json):
    if record['id'] != 0: 
        dict_pbtxt[record['id']] = record

json_pbtxt = json.dumps(dict_pbtxt, indent=0, ensure_ascii=False).encode('utf8').decode() # convert back to json str
for c in df_cats.columns:
    json_pbtxt = json_pbtxt.replace("\""+c+"\"", "\t"+c)   # remove " useless
json_pbtxt = re.sub(r"\"\d*\": {", r"item{", json_pbtxt)      # replace "23" for item
json_pbtxt = json_pbtxt[1:-1]                                  #Remove fisrt and last char due to {} useless


PATH_TO_LABELS = 'RESULT/label_map.pbtxt'
print(PATH_TO_LABELS)
with open(PATH_TO_LABELS, 'w+', encoding='utf-8') as f:
    f.write( json_pbtxt  )

print("Check correct format of: ", PATH_TO_LABELS)
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)
print("end")


```
