### ISSUE TITLE
The checkpoint files of the object detection models cannot be imported

### ISSUE THREAD

**Issue by futurely** [tensorflow/models#1602]
### System information
OS: Ubuntu 16.04.2 LTS (Xenial Xerus)

TensorFlow version: ('v1.2.0-rc2-21-g12f033d', '1.2.0')

### Describe the problem
The checkpoint files of the [object detection models](https://github.com/tensorflow/models/blob/056965d53401e07b3f3d898f81830b3c5ccf9478/object_detection/g3doc/detection_model_zoo.md) cannot be imported. Related to https://github.com/tensorflow/models/issues/1564.

### Source code / logs
`meta_graph_def = tf.train.import_meta_graph(model.ckpt.meta)`

```shell
Traceback (most recent call last):
  File "../../extract_graph_def.py", line 19, in <module>
    main()
  File "../../extract_graph_def.py", line 15, in main
    extract_graph_def(input, output)
  File "../../extract_graph_def.py", line 7, in extract_graph_def
    meta_graph_def = tf.train.import_meta_graph(input)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named SSTableReaderV2 in defined operations.
```

**Comment by jch1** [comment]
@futurely  - can you say what program you are trying to run and with what parameters please?

**Comment by futurely** [comment]
Thanks! I've successfully fine-tuned models initialized with the released checkpoints. This issue no longer needs to be addressed.

**Comment by kaishijeng** [comment]
futurely,

   Can you share how you resolve this issue?
I have encountered the same issue as described in #1564

Thanks,

**Comment by futurely** [comment]
To get rid of the `SSTableReaderV2 ` op that doesn't exist in the open source TensorFlow, build a graph with `logits, end_points = mobilenet_v1.mobilenet_v1(tf.random_uniform((1, 224, 224, 3)), 1001)` instead of importing from the checkpoint meta graph def with `saver = tf.train.import_meta_graph('mobilenet_v1_1.0_224.ckpt.meta')`. A complete example is in object_detection/exporter.py.

**Comment by tamizharasank** [comment]
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
1.4.0
Traceback (most recent call last):
  File "freezeGraph-WORKING.py", line 13, in <module>
    saver = tf.train.import_meta_graph('/media/panamon/newvolumeD/tamizh3/object-detection/models/research/object_detection/ssd_mobilenet_v1_coco_11_06_2017/model.ckpt.meta')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1810, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/meta_graph.py", line 660, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named SSTableReaderV2 in defined operations.
