### ISSUE TITLE
TypeError: get_variable() got an unexpected keyword argument 'regularizer'

### ISSUE THREAD

**Issue by sentryAI** [tensorflow/models#17]
I am interested in training inception from scratch. I manage to build imagenet as instructed. However, the following command:

bazel-bin/inception/imagenet_train.py --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/tmp/imagenet_data

Results in this stack trace:

I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops.py:586: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if width == new_width_const and height == new_height_const:
Traceback (most recent call last):
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/imagenet_train.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/imagenet_train.py", line 37, in main
    inception_train.train(dataset)
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception_train.py", line 235, in train
    loss = _tower_loss(images, labels, num_classes, scope)
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception_train.py", line 110, in _tower_loss
    scope=scope)
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception_model.py", line 90, in inference
    scope=scope)
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/slim/inception_model.py", line 88, in inception_v3
    scope='conv0')
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/slim/ops.py", line 184, in conv2d
    restore=restore)
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/ssd/esteva/tensorflow_master/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/slim/variables.py", line 224, in variable
    trainable=trainable, collections=collections)
TypeError: get_variable() got an unexpected keyword argument 'regularizer'

Any idea what's happening?

**Comment by waterofphysics** [comment]
Hi @sentryAI, I have encounter the same error as discussed in  https://github.com/tensorflow/models/issues/11
This is due to TensorFlow installation version in your computer. You "need to build TensorFlow from source, and installed as a PIP package. Please follow the instructions at Installing From Source" as suggested in `inception/README.md` 

The possible reason is that you have installed TensorFlow through `Pip Installation` before you installed from sources. So when `import tensorflow`, python environment imports what you have installed from the former `Pip Installation` version.

In this case, you can use `sudo pip uninstall tensorflow` first, and then rebuild TensorFLow from source.

**Comment by sentryAI** [comment]
Thanks, this cleared up the issue!
