### ISSUE TITLE
Error After Optimizing Model for Eval: tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

### ISSUE THREAD

**Issue by ghost** [tensorflow/models#1721]
I have been trying to optimize a model for deployment using Tensorflow tools graph_transforms using the following configuration:
```
../../tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
	--in_graph="/home/conner/models/object_detection/inference_graph_v1.pb" \
	--out_graph="/home/conner/models/object_detection/optimized_inference_graph_v1.pb" \
	--inputs='image_tensor' \
	--outputs='detection_boxes,detection_scores,detection_classes,num_detections' \
	--transforms='
	  strip_unused_nodes(type=float, shape="1,-1,-1,3")
	  remove_nodes(op=Identity, op=CheckNumerics)
	  fold_constants(ignore_errors=true)
	  fold_batch_norms
	  fold_old_batch_norms'
```
This completes without error, however when I try to eval the model I get the following error:
```
Traceback (most recent call last):
  File "benchmark_prediction_speed.py", line 92, in <module>
    feed_dict={image_tensor: image_np_expanded})
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
```
I have tried look for a operation to add to the list to ignore to stop the program from breaking, but I cannot find anything that seems to fix it.

**Comment by tatatodd** [comment]
@petewarden Might have some ideas here

**Comment by jch1** [comment]
Hi @conner-starsky -

I looked into this a bit.  I believe the issue lies in the "remove_nodes(op=Identity, op=CheckNumerics)" part of your command.  Can you get rid of that part and retry?
We set our outputs to be identity ops in the exporter, so it may be problematic to remove those ops.

**Comment by conner-starsky** [comment]
Sadly, I get the same error. I'm just trying to improve the speed of the model's prediction. Is there anyway to do that easier?
```
Traceback (most recent call last):
  File "benchmark_prediction_speed.py", line 93, in <module>
    feed_dict={image_tensor: image_np_expanded})
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/conner/.pyenv/versions/2.7.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
```

**Comment by chandrakantkhandelwal** [comment]
@jch1  I was also facing the same issue as @conner-starsky, however after doing the modification you suggested, it is working fine. But there is a significant drop in the accuracy of model. FYI: I was trying to quantize the latest released SSD-Mobilenet model by google. Any suggestions to avoid reduction in accuracy?

Thanks

**Comment by gdelab** [comment]
I got the same error, @jch1 's suggestion fixed it but created a new error: 

> ValueError: Specified colocation to an op that does not exist during import: FirstStageFeatureExtractor/resnet_v1_101/block3/unit_1/bottleneck_v1/conv3/BatchNorm/beta in FirstStageFeatureExtractor/resnet_v1_101/block3/unit_1/bottleneck_v1/conv3/BatchNorm/beta/read

I don't get this on the unquantized version, do you have any idea what might cause that ? Removing fold_batch_norm and fold_old_batch_norms does not help.
(I'm using a Faster RCNN with ResNet101_v1 on custom data)

**Comment by zhangshuaitao** [comment]
@jch1  I was also facing the same issue as @conner-starsky,  INFO:tensorflow:global step 109662: loss = 5.3843 (0.160 sec/step)
INFO:tensorflow:global step 109663: loss = 4.5832 (0.256 sec/step)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Retval[0] does not have value
INFO:tensorflow:global step 109664: loss = 8.8361 (0.098 sec/step)
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
File "./train_seglink.py", line 275, in
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "./train_seglink.py", line 271, in main
train(train_op)
File "./train_seglink.py", line 260, in train
session_config = sess_config
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 759, in train
sv.saver.save(sess, sv.save_path, global_step=sv.global_step)
File "/usr/lib/python2.7/contextlib.py", line 24, in exit
self.gen.next()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
self.stop(close_summary_writer=close_summary_writer)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 792, in stop
stop_grace_period_secs=self._stop_grace_secs)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
six.reraise(*self._exc_info_to_raise)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 296, in stop_on_exception
yield
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 494, in run
self.run_loop()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 994, in run_loop
self._sv.global_step])
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
run_metadata_ptr)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
feed_dict_string, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
target_list, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
zst@zst-robot1:~/zst/seglink-master$
我的tf 版本是1.2.1,我也尝试在1.1.0上运行也会出现这样的错误.

**Comment by jinxin0924** [comment]
Any one solve this problem? I have the same error.

**Comment by danvargg** [comment]
Facing the exact same issue here.

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[26] does not have value`

**Comment by Danliran** [comment]
this bug is still here, i facing it. tf 1.15.0 , when i training resnet50 base on tensorflow/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py.

**Comment by kumariko** [comment]
@ghost Could you please let us know if you still need help on this issue ? and please refer [link1](https://stackoverflow.com/questions/48295072/invalidargumenterror-retval0-does-not-have-value-is-thrown-when-using-tflearn), [link2](https://github.com/tensorflow/tensorflow/issues/30467) and let us know if it helps? Thanks!

**Comment by LotusTang** [comment]
您发送的邮件已经收到，我会尽快阅读并给您回复。
