### ISSUE TITLE
Train from Scratch Problem: ValueError

### ISSUE THREAD

**Issue by tqshao** [tensorflow/models#1750]
I am using tensorflow 1.2 (gpu) on Ubuntu 14
I got an error when change 'from_detection_checkpoint' (I think this is the place to set train from scratch?) to false in config file.  
`Traceback (most recent call last):
  File "object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/DensoML/tensorflow/models/object_detection/trainer.py", line 216, in train
    from_detection_checkpoint=train_config.from_detection_checkpoint)
  File "/home/DensoML/tensorflow/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1436, in restore_fn
    self.second_stage_feature_extractor_scope)
  File "/home/DensoML/tensorflow/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 188, in restore_from_classification_checkpoint_fn
    saver = tf.train.Saver(variables_to_restore)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1161, in build
    raise ValueError("No variables to save")
ValueError: No variables to save`

**Comment by derekjchow** [comment]
Change fine_tune_checkpoint to be an empty string. What does your config look like?

**Comment by tqshao** [comment]
Thanks! It worked out! I was using faster_rcnn_resnet101_pet.
