### ISSUE TITLE
Error running lm_1b, "Caused by op u'save/restore_slice_11'"

### ISSUE THREAD

**Issue by cheezer** [tensorflow/models#1802]
When I run the model, it can't reload the model. I tried version 1.2 and version 0.11. Neither of them can work. 

Is there anyone who can help?

The traceback is as follows:

bazel-bin/lm_1b/lm_1b_eval --mode sample --prefix "I love that I"  --pbtxt data/graph-2016-09-10.pbtxt --vocab_file data/vocab-2016-09-10.txt --ckpt 'data/ckpt-*'
Recovering graph.
Recovering checkpoint data/ckpt-*
2017-06-28 21:12:56.406946: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 21:12:56.406965: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 21:12:56.406970: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 21:12:56.406973: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 21:12:56.406976: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-06-28 21:12:56.750715: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:09:00.0
Total memory: 11.90GiB
Free memory: 11.75GiB
2017-06-28 21:12:56.981859: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x5b86120 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-06-28 21:12:56.982799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties:
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:06:00.0
Total memory: 11.90GiB
Free memory: 11.75GiB
2017-06-28 21:12:57.209289: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x5b89f70 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-06-28 21:12:57.210225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 2 with properties:
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:05:00.0
Total memory: 11.90GiB
Free memory: 11.72GiB
2017-06-28 21:12:57.214612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 2
2017-06-28 21:12:57.214624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y Y
2017-06-28 21:12:57.214628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y Y
2017-06-28 21:12:57.214633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   Y Y Y
2017-06-28 21:12:57.214642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:09:00.0)
2017-06-28 21:12:57.214647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: TITAN X (Pascal), pci bus id: 0000:06:00.0)
2017-06-28 21:12:57.214652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:2) -> (device: 2, name: TITAN X (Pascal), pci bus id: 0000:05:00.0)
2017-06-28 21:12:57.451099: I tensorflow/core/common_runtime/simple_placer.cc:675] Ignoring device specification /device:GPU:0 for node 'lstm/lstm_0/Assign' because the input edge from 'Variable' is a reference connection and already has a device field set to /device:CPU:0
2017-06-28 21:12:57.451135: I tensorflow/core/common_runtime/simple_placer.cc:675] Ignoring device specification /device:GPU:0 for node 'lstm/lstm_1/Assign' because the input edge from 'Variable_1' is a reference connection and already has a device field set to /device:CPU:0
2017-06-28 21:12:57.494972: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.494995: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.494979: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495045: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495019: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.494997: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495098: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495110: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495085: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495051: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495137: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495000: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495167: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495046: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495170: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495177: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495054: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495148: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495212: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495221: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495148: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495200: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495047: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495181: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495222: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495236: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495279: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495117: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495263: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495262: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495282: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495336: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495274: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495300: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495359: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495324: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495312: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495367: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495389: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495359: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495441: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495417: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495420: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495079: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495411: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495472: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495450: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495383: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495431: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495382: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495313: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495477: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495491: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495546: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495576: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495526: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495487: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495539: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495535: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495611: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495620: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495561: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495567: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495651: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495659: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495491: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495510: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495678: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495694: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495690: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495518: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495601: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495735: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495742: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495628: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495759: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495628: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495772: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495782: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495789: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495627: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495776: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495705: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495800: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495832: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495792: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495818: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495841: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495737: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495677: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495815: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495823: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495836: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495724: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495846: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495874: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495868: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495861: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495851: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2017-06-28 21:12:57.495873: W tensorflow/core/framework/op_kernel.cc:1158] Internal: Overlapping slices: existing slice = -:-, new slice = -:-
Traceback (most recent call last):
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 308, in <module>
    tf.app.run()
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 298, in main
    _SampleModel(FLAGS.prefix, vocab)
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 174, in _SampleModel
    sess, t = _LoadModel(FLAGS.pbtxt, FLAGS.ckpt)
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 115, in _LoadModel
    sess.run('save/restore_all', {'save/Const:0': ckpt_file})
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Overlapping slices: existing slice = -:-, new slice = -:-
	 [[Node: save/restore_slice_11 = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/restore_slice_11/tensor_name, save/restore_slice_11/shape_and_slice)]]

Caused by op u'save/restore_slice_11', defined at:
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 308, in <module>
    tf.app.run()
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 298, in main
    _SampleModel(FLAGS.prefix, vocab)
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 174, in _SampleModel
    sess, t = _LoadModel(FLAGS.pbtxt, FLAGS.ckpt)
  File "/home/qizhe/lm/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 111, in _LoadModel
    'global_step:0'], name='')
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 311, in import_graph_def
    op_def=op_def)
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/qizhe/tool/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Overlapping slices: existing slice = -:-, new slice = -:-
	 [[Node: save/restore_slice_11 = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/restore_slice_11/tensor_name, save/restore_slice_11/shape_and_slice)]]

**Comment by cheezer** [comment]
The error turned out to be that multiple tensors with the same name were restored.

**Comment by domil** [comment]
How did you solved this issue? I am getting the same error. Please post the solution.

**Comment by qizhex** [comment]
Yes. I inputted a wrong filename for the checkpoint restoration.
