### ISSUE TITLE
Executing train.py threw an WinError

### ISSUE THREAD

**Issue by soukira** [tensorflow/models#1830]
Python version : 3.5.2
Tensorflow : 1.2.0

when i ran python translate.py , I got the following error: 
Downloading http://www.statmt.org/wmt10/training-giga-fren.tar to /tmp\training-giga-fren.tar
Traceback (most recent call last):
  File "translate.py", line 322, in <module>
    tf.app.run()
  File "C:\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "translate.py", line 319, in main
    train()
  File "translate.py", line 173, in train
    FLAGS.data_dir, FLAGS.from_vocab_size, FLAGS.to_vocab_size)
  File "C:\Python\Python35\Lib\site-packages\models\tutorials\rnn\translate\data_utils.py", line 267, in prepare_wmt_data
    train_path = get_wmt_enfr_train_set(data_dir)
  File "C:\Python\Python35\Lib\site-packages\models\tutorials\rnn\translate\data_utils.py", line 80, in get_wmt_enfr_train_set
    _WMT_ENFR_TRAIN_URL)
  File "C:\Python\Python35\Lib\site-packages\models\tutorials\rnn\translate\data_utils.py", line 60, in maybe_download
    filepath, _ = urllib.request.urlretrieve(url, filepath)
  File "C:\Python\Python35\lib\urllib\request.py", line 217, in urlretrieve
    block = fp.read(bs)
  File "C:\Python\Python35\lib\http\client.py", line 448, in read
    n = self.readinto(b)
  File "C:\Python\Python35\lib\http\client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "C:\Python\Python35\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Do i need to use python 2.7 version?

**Comment by aselle** [comment]
```
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```
Looks like you have a network problem. Can you download the url manually with wget or curl or your web browser?

**Comment by soukira** [comment]
@aselle thanks!! Tensorflow version 1.0.0 seems to have solved the problem
