### ISSUE TITLE
error use pre-trained model of resnet101 when training on pascal voc 2012 with faster-rcnn-resnet101-voc07

### ISSUE THREAD

**Issue by briantse100** [tensorflow/models#1839]
The error is model parameter is conflict of the net by using [ pre-trained model of resnet101 ](http://download.tensorflow.org/models/resnet_v1_101_2016_08_28.tar.gz) when training on pascal voc 2012 with faster-rcnn-resnet101-voc07. Is there pre-trained model of resnet101 for the API? Thanks!

**Comment by jch1** [comment]
Hi @briantse100  - that should work... what specifically is your error?

**Comment by briantse100** [comment]
Ok, thanks for your replay. 
# The problem
As follow is the error:
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, Tensor name "FirstStageFeatureExtractor/resnet_v1_101/block3/unit_21/bottleneck_v1/conv2/BatchNorm/gamma" not found in checkpoint files /home/briantse/tf-faster-rcnn---/tf-faster-rcnn-master/data/imagenet_weights/res101.ckpt
	 [[Node: save/RestoreV2_321 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_321/tensor_names, save/RestoreV2_321/shape_and_slices)]]

Caused by op u'save/RestoreV2_321', defined at:
  File "object_detection/train.py", line 199, in <module>
    tf.app.run()
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 195, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/briantse/code/models+objection/object_detection/trainer.py", line 215, in train
    from_detection_checkpoint=train_config.from_detection_checkpoint)
  File "/home/briantse/code/models+objection/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1447, in restore_fn
    saver = tf.train.Saver(first_stage_variables)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "FirstStageFeatureExtractor/resnet_v1_101/block3/unit_21/bottleneck_v1/conv2/BatchNorm/gamma" not found in checkpoint files /home/briantse/tf-faster-rcnn---/tf-faster-rcnn-master/data/imagenet_weights/res101.ckpt
	 [[Node: save/RestoreV2_321 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_321/tensor_names, save/RestoreV2_321/shape_and_slices)]]

Traceback (most recent call last):
  File "object_detection/train.py", line 199, in <module>
    tf.app.run()
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 195, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/briantse/code/models+objection/object_detection/trainer.py", line 289, in train
    saver=saver)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 776, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/home/briantse/anaconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 788, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 949, in managed_session
    start_standard_services=start_standard_services)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 706, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 264, in prepare_session
    init_fn(sess)
  File "/home/briantse/code/models+objection/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1450, in restore
    saver.restore(sess, checkpoint_path)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "FirstStageFeatureExtractor/resnet_v1_101/block3/unit_21/bottleneck_v1/conv2/BatchNorm/gamma" not found in checkpoint files /home/briantse/tf-faster-rcnn---/tf-faster-rcnn-master/data/imagenet_weights/res101.ckpt
	 [[Node: save/RestoreV2_321 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_321/tensor_names, save/RestoreV2_321/shape_and_slices)]]

Caused by op u'save/RestoreV2_321', defined at:
  File "object_detection/train.py", line 199, in <module>
    tf.app.run()
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 195, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/briantse/code/models+objection/object_detection/trainer.py", line 215, in train
    from_detection_checkpoint=train_config.from_detection_checkpoint)
  File "/home/briantse/code/models+objection/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1447, in restore_fn
    saver = tf.train.Saver(first_stage_variables)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/briantse/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "FirstStageFeatureExtractor/resnet_v1_101/block3/unit_21/bottleneck_v1/conv2/BatchNorm/gamma" not found in checkpoint files /home/briantse/tf-faster-rcnn---/tf-faster-rcnn-master/data/imagenet_weights/res101.ckpt
	 [[Node: save/RestoreV2_321 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_321/tensor_names, save/RestoreV2_321/shape_and_slices)]]

**Comment by jch1** [comment]
In your config file... is there a from_detection_checkpoint option that's set to true?  It looks like you might be trying to train from a classification checkpoint in which case you should set this to be false.

**Comment by briantse100** [comment]
Ok, thanks! It works after the parameter from_detection_checkpoint option is set to be false. Thank you! It is my fault. As follow is the explain of the parameter from_detection_checkpoint option in the train.proto:
`// Specifies if the finetune checkpoint is from an object detection model.
  // If from an object detection model, the model being trained should have
  // the same parameters with the exception of the num_classes parameter.
  // If false, it assumes the checkpoint was a object classification model.
  optional bool from_detection_checkpoint = 8 [default=false];`

**Comment by cy89** [comment]
@briantse100 it looks like you resolved this a few days ago. Please reopen and tell us if there's something else you need help with.
