### ISSUE TITLE
Attention_ocr: cannot train a model using pre-trained Inception weights as initialization

### ISSUE THREAD

**Issue by wjbKimberly** [tensorflow/models#1841]
Hi, thx a lot for your work.
When I follow your guide use inception_v3.ckpt, it dosen't work.

To train a model using pre-trained Inception weights as initialization:
`
python train.py --checkpoint_inception=inception_v3.ckpt
`

Maybe it could be change into
`
python train.py --checkpoint_inception=./inception_v3.ckpt
`
And it works on my computer.

**Comment by aselle** [comment]
Could you submit a pull request please?

**Comment by wjbKimberly** [comment]
It seems that I have changed a lot when fork your code. Could you please change the README doc by yourself?

**Comment by jart** [comment]
I don't understand why the `./` would change things. Could you please help understand better, with a full traceback of the error, system information, etc.?

**Comment by wjbKimberly** [comment]
Run:
`python train.py --checkpoint=model.ckpt-399731`
Get:
```
Traceback (most recent call last):
  File "train.py", line 209, in <module>
    app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 201, in main
    FLAGS.checkpoint_inception)
  File "/home/wangjianbo_i/models/attention_ocr/python/model.py", line 520, in create_init_fn_to_restore
    assign_from_checkpoint(utils.variables_to_restore(), master_checkpoint)
  File "/home/wangjianbo_i/models/attention_ocr/python/model.py", line 515, in assign_from_checkpoint
    assign_op, feed_dict = slim.assign_from_checkpoint(checkpoint, variables)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 512, in assign_from_checkpoint
    reader = pywrap_tensorflow.NewCheckpointReader(model_path)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt-399731
```
If I change it to:
`python train.py --checkpoint=./model.ckpt-399731`
It works.

**Comment by jart** [comment]
I'll take your word for it. Opened up a PR in https://github.com/tensorflow/models/pull/1951.
