### ISSUE TITLE
adversarial_text doesn't seem to work for rcv1 like dataset

### ISSUE THREAD

**Issue by anikethjr** [tensorflow/models#1845]
I have a dataset whose format is the same as that of the rcv1 dataset. When I follow the instructions given in the README file, I get an error while training : 

INFO:tensorflow:step 10, loss = 2.95 (235.2 examples/sec; 0.136 sec/batch)
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.OverflowError'>, Loss is nan
Traceback (most recent call last):
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 63, in <module>
    tf.app.run()
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 59, in main
    pretrained_model_dir=FLAGS.pretrained_model_dir)
  File "/data/aniketh/utopia/adversarial_text/train_utils.py", line 92, in run_training
    global_step_val = train_step(sess, train_op, loss, global_step)
  File "/data/aniketh/utopia/adversarial_text/train_utils.py", line 132, in train_step
    raise OverflowError('Loss is nan')
OverflowError: Loss is nan
ERROR: Non-zero return code '1' from command: Process exited with status 1.

The csv files are in the required format - three files test.csv, train.csv and unlab.csv. Each file has two columns - the first with the classification (four classes - 1,2,3,4) , the unlabelled data has 0 in the classification column. The second column has the text data.

Exact commands which I ran:

bazel run :gen_vocab -- --output_dir=/data/aniketh/utopia/data --dataset=rcv1 --rcv1_input_dir=/data/aniketh/utopia/csv --lowercase=False

bazel run :gen_data -- --output_dir=/data/aniketh/utopia/data --dataset=rcv1 --rcv1_input_dir=/data/aniketh/utopia/csv --lowercase=False --label_gain=False --num_classes=4

bazel run :pretrain -- \
    --train_dir=/data/aniketh/utopia/pretrain \
    --data_dir=/data/aniketh/utopia/data \
    --num_classes=4 \
    --vocab_size=75606 \
    --embedding_dims=50 \
    --rnn_cell_size=64 \
    --num_candidate_samples=100 \
    --batch_size=32 \
    --learning_rate=0.001 \
    --learning_rate_decay_factor=0.9999 \
    --max_steps=100 \
    --max_grad_norm=1.0 \
    --num_timesteps=50 \
    --keep_prob_emb=0.5 \
    --adv_training_method=at \
    --use_seq2seq_autoencoder=True \
    --normalize_embeddings
    

bazel run :train_classifier -- \
    --train_dir=/data/aniketh/utopia/train \
    --pretrained_model_dir=/data/aniketh/utopia/pretrain \
    --data_dir=/data/aniketh/utopia/data \
    --num_classes=4 \
    --vocab_size=75606 \
    --embedding_dims=50 \
    --rnn_cell_size=64 \
    --cl_num_layers=1 \
    --cl_hidden_size=30 \
    --batch_size=32 \
    --learning_rate=0.0005 \
    --learning_rate_decay_factor=0.9998 \
    --max_steps=1000 \
    --max_grad_norm=1.0 \
    --num_timesteps=50 \
    --keep_prob_emb=0.5 \
    --normalize_embeddings \
    --adv_training_method=at \
    --use_seq2seq_autoencoder=True \
    --perturb_norm_length=5.0 

bazel run :evaluate -- \
    --eval_dir=/data/aniketh/utopia/eval \
    --checkpoint_dir=/data/aniketh/utopia/train \
    --eval_data=train \
    --run_once \
    --num_examples=1307 \
    --data_dir=/data/aniketh/utopia/data \
    --vocab_size=75606 \
    --embedding_dims=50 \
    --rnn_cell_size=64 \
    --batch_size=32 \
    --num_timesteps=50 \
    --use_seq2seq_autoencoder=True \
    --normalize_embeddings

**Comment by anikethjr** [comment]
Ok so managed to fix that my changing the document_generators.py file. The file doesn't read the unlabelled data properly. Corrected code for the function rcv1_documents:

def rcv1_documents(dataset='train',
                   include_unlabeled=True,
                   include_validation=False):
  # pylint:disable=line-too-long
  """Generates Documents for Reuters Corpus (rcv1) dataset.

  Dataset described at
  http://www.ai.mit.edu/projects/jmlr/papers/volume5/lewis04a/lyrl2004_rcv1v2_README.htm

  Args:
    dataset: str, identifies the csv file within the rcv1 data directory.
    include_unlabeled: bool, whether to include the unlab file. Only valid
      when dataset=train.
    include_validation: bool, whether to include validation data, which is a
      randomly selected 10% of the data.

  Yields:
    Document

  Raises:
    ValueError: if FLAGS.rcv1_input_dir is empty.
  """
  # pylint:enable=line-too-long

  if not FLAGS.rcv1_input_dir:
    raise ValueError('Must provide FLAGS.rcv1_input_dir')

  tf.logging.info('Generating rcv1 documents...')

  datasets = [dataset]
  if include_unlabeled:
    if dataset == 'train':
      datasets.append('unlab')
  for dset in datasets:
    with open(os.path.join(FLAGS.rcv1_input_dir, dset + '.csv')) as db_f:
      reader = csv.reader(db_f)
      for row in reader:
        # 10% of the data is randomly held out
        is_validation = random.randint(1, 10) == 1
        if is_validation and not include_validation and dset!='unlab':
          continue

        content = row[1]
        if int(row[0]) != 0:
          yield Document(
              content=content,
              is_validation=is_validation,
              is_test=False,
              label=int(row[0]),
              add_tokens=True)
        else:
          yield Document(
              content=content,
              is_validation=False,
              is_test=False,
              label=None,
              add_tokens=True)

**Comment by anikethjr** [comment]
Managed to fix the error by modifying the document_generators.py file. The unlabelled data wasn't being handled properly:

for dset in datasets:
    with open(os.path.join(FLAGS.rcv1_input_dir, dset + '.csv')) as db_f:
      reader = csv.reader(db_f)
      for row in reader:
        # 10% of the data is randomly held out
        is_validation = random.randint(1, 10) == 1
        if is_validation and not include_validation and dset!='unlab':
          continue

        content = row[1]
        if int(row[0]) != 0:
          yield Document(
              content=content,
              is_validation=is_validation,
              is_test=False,
              label=int(row[0]),
              add_tokens=True)
        else:
          yield Document(
              content=content,
              is_validation=False,
              is_test=False,
              label=None,
              add_tokens=True)

**Comment by anikethjr** [comment]
The train_classifier file doesn't seem to work now... Gives me the following error:
```
INFO: Found 1 target...
WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-out -> /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out:  /data/aniketh/utopia/adversarial_text/bazel-out (File exists)
  cannot create symbolic link bazel-out -> /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out:  /data/aniketh/utopia/adversarial_text/bazel-out (File exists)
  cannot create symbolic link bazel-adversarial_text -> /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__:  /data/aniketh/utopia/adversarial_text/bazel-adversarial_text (File exists)
  cannot create symbolic link bazel-bin -> /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin:  /data/aniketh/utopia/adversarial_text/bazel-bin (File exists)
  cannot create symbolic link bazel-testlogs -> /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/testlogs:  /data/aniketh/utopia/adversarial_text/bazel-testlogs (File exists)
  cannot create symbolic link bazel-genfiles -> /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/genfiles:  /data/aniketh/utopia/adversarial_text/bazel-genfiles (File exists).
Target //:train_classifier up-to-date:
  /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier
INFO: Elapsed time: 0.317s, Critical Path: 0.00s

INFO: Running command line: /home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier '--train_dir=/data/aniketh/utopia/train' '--pretrained_model_dir=/data/aniketh/utopia/pretrain' '--data_dir=/data/aniketh/utopia/data' '--num_classes=4' '--vocab_size=27184' '--embedding_dims=50' '--rnn_cell_size=64' '--batch_size=32' '--learning_rate=0.0005' '--learning_rate_decay_factor=0.9998' '--max_steps=1000' '--max_grad_norm=1.0' '--num_timesteps=50' '--keep_prob_emb=0.5' --normalize_embeddings '--adv_training_method=at' '--use_seq2seq_autoencoder=True' '--perturb_norm_length=5.0'
INFO:tensorflow:Constructing TFRecordReader from files: ['/data/aniketh/utopia/data/train_classification.tfrecords']
INFO:tensorflow:Trainable variables:
INFO:tensorflow:------------------------------------------------------------
INFO:tensorflow:<tf.Variable 'embedding/embedding_1:0' shape=(27184, 50) dtype=float32_ref>
INFO:tensorflow:<tf.Variable 'dense/kernel:0' shape=(64, 30) dtype=float32_ref>
INFO:tensorflow:<tf.Variable 'dense/bias:0' shape=(30,) dtype=float32_ref>
INFO:tensorflow:<tf.Variable 'dense_1/kernel:0' shape=(30, 4) dtype=float32_ref>
INFO:tensorflow:<tf.Variable 'dense_1/bias:0' shape=(4,) dtype=float32_ref>
INFO:tensorflow:<tf.Variable 'LSTM/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0' shape=(114, 256) dtype=float32_ref>
INFO:tensorflow:<tf.Variable 'LSTM/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0' shape=(256,) dtype=float32_ref>
INFO:tensorflow:Will attempt restore from /data/aniketh/utopia/pretrain: [<tf.Variable 'embedding/embedding_1:0' shape=(27184, 50) dtype=float32_ref>, <tf.Variable 'LSTM/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0' shape=(114, 256) dtype=float32_ref>, <tf.Variable 'LSTM/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0' shape=(256,) dtype=float32_ref>]
2017-07-05 14:39:02.378833: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-05 14:39:02.380470: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-05 14:39:02.382001: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-05 14:39:02.382030: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-05 14:39:02.382038: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-05 14:39:03.462610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:02:00.0
Total memory: 11.90GiB
Free memory: 11.76GiB
2017-07-05 14:39:03.462654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-07-05 14:39:03.462662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-07-05 14:39:03.462677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0)
INFO:tensorflow:Restoring parameters from /data/aniketh/utopia/train/model.ckpt-0
INFO:tensorflow:Checkpoint exists in FLAGS.train_dir; skipping pretraining restore
INFO:tensorflow:Saving checkpoint to path /data/aniketh/utopia/train/model.ckpt
INFO:tensorflow:global_step/sec: 0
2017-07-05 14:39:13.308602: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.308722: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.308788: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309129: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309172: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309204: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309234: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309265: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309293: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309549: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
2017-07-05 14:39:13.309642: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]

Caused by op u'optimization/dense/kernel_gradient', defined at:
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 63, in <module>
    tf.app.run()
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 53, in main
    train_op, loss, global_step = model.classifier_training()
  File "/data/aniketh/utopia/adversarial_text/graphs.py", line 156, in classifier_training
    train_op = optimize(loss, self.global_step)
  File "/data/aniketh/utopia/adversarial_text/graphs.py", line 664, in optimize
    FLAGS.replicas_to_aggregate, FLAGS.task)
  File "/data/aniketh/utopia/adversarial_text/layers.py", line 320, in optimize
    _summarize_vars_and_grads(grads_and_vars)
  File "/data/aniketh/utopia/adversarial_text/layers.py", line 391, in _summarize_vars_and_grads
    tf.summary.histogram(tag('gradient'), grad_values)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/summary/summary.py", line 221, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 131, in _histogram_summary
    name=name)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]

Traceback (most recent call last):
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 63, in <module>
    tf.app.run()
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 59, in main
    pretrained_model_dir=FLAGS.pretrained_model_dir)
  File "/data/aniketh/utopia/adversarial_text/train_utils.py", line 93, in run_training
    sv.stop()
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 296, in stop_on_exception
    yield
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 494, in run
    self.run_loop()
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 994, in run_loop
    self._sv.global_step])
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]

Caused by op u'optimization/dense/kernel_gradient', defined at:
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 63, in <module>
    tf.app.run()
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/aniketh/.cache/bazel/_bazel_aniketh/8c5282dbcffe18d6c89921f5f1ad06fa/execroot/__main__/bazel-out/local-fastbuild/bin/train_classifier.runfiles/__main__/train_classifier.py", line 53, in main
    train_op, loss, global_step = model.classifier_training()
  File "/data/aniketh/utopia/adversarial_text/graphs.py", line 156, in classifier_training
    train_op = optimize(loss, self.global_step)
  File "/data/aniketh/utopia/adversarial_text/graphs.py", line 664, in optimize
    FLAGS.replicas_to_aggregate, FLAGS.task)
  File "/data/aniketh/utopia/adversarial_text/layers.py", line 320, in optimize
    _summarize_vars_and_grads(grads_and_vars)
  File "/data/aniketh/utopia/adversarial_text/layers.py", line 391, in _summarize_vars_and_grads
    tf.summary.histogram(tag('gradient'), grad_values)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/summary/summary.py", line 221, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 131, in _histogram_summary
    name=name)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aniketh/adversarial/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: optimization/dense/kernel_gradient
	 [[Node: optimization/dense/kernel_gradient = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](optimization/dense/kernel_gradient/tag, optimization/clip_by_global_norm/optimization/clip_by_global_norm/_0/_1447)]]
```

**Comment by cy89** [comment]
Please pardon me if I'm suggesting obvious things, but doesn't the "Loss is NaN" suggest that your training data and labels are somehow getting the loss function to misbehave (divide by zero, or other sources of NaNs), which is cascading into the downstream histogram code? Can you look at the losses you're getting, and figure out which inputs are poorly curated?

**Comment by anikethjr** [comment]
Hmm I have checked the input files....They are just plaintext and are in the format specified by the program. Also, I tried running the code on just two classes and it works fine....So, it must be something with the multi-class functionality of the code...

**Comment by michaelisard** [comment]
It's unfortunately hard to know how to help you without more concrete repro instructions. Could you construct a small toy dataset that exhibits the problem, and share that?

**Comment by anikethjr** [comment]
I have attached a small dataset which recreates the problem I mentioned. 


[Data.tar.gz](https://github.com/tensorflow/models/files/1138698/Data.tar.gz)

**Comment by michaelisard** [comment]
Thanks! @rsepassi would you be able to take a look?

**Comment by rsepassi** [comment]
Have you tried it with the rcv1 dataset directly first?

**Comment by anikethjr** [comment]
Hmm the problem is that the RCV1 dataset itself isn't in the format specified..... I checked many sources online to find the original dataset but couldn't manage to find it. But my dataset is in exactly the same format as that required by the document_generator.py file and on doing some debugging, I discovered that there is no issue in the generation of the sequences by gen_data.py. So, there must be something wrong elsewhere....
Another issue ([https://github.com/tensorflow/models/issues/1915]) also has similar problems on the dbpedia dataset which means there's something wrong with the multiclass classification feature.

**Comment by StevenLOL** [comment]
HI, @anikethjr if you get time, maybe you can try the dbpedia dataset , seems your titan has enough GPU memory compare to my gtx 1080.  (to speedup, you can skip the pre-training part )

I also feel there maybe a bug somewhere, as in #1915 the NAN and OOM occurred randomly.

**Comment by WangLianChen** [comment]
more than 4-classes it can work？

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
