### ISSUE TITLE
google.protobuf.text_format.ParseError: 110:25 : Expected string but found: '“'

### ISSUE THREAD

**Issue by johnsonlegend** [tensorflow/models#1897]
It looks like I have some problems when specifying my PATH_TO_BE_CONFIGURED, but I follows the tutorial and don't get what's wrong with my file path. 

`fine_tune_checkpoint: “/Users/johson/Data/Tensorflow/Models/object_detection/samples/checkpoints/faster_rcnn_resnet101_coco_11_06_2017/model.ckpt"`

> python object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=object_detection/samples/configs/faster_rcnn_resnet101_pets.config \
    --train_dir=object_detection/models/model/train
Traceback (most recent call last):
  File "object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 143, in main
    model_config, train_config, input_config = get_configs_from_pipeline_file()
  File "object_detection/train.py", line 103, in get_configs_from_pipeline_file
    text_format.Merge(f.read(), pipeline_config)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 809, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1151, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1166, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "/Users/johson/anaconda3/envs/envy/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1185, in _ConsumeSingleByteString
    raise self.ParseError('Expected string but found: %r' % (text,))
google.protobuf.text_format.ParseError: 133:19 : Expected string but found: '“'

**Comment by johnsonlegend** [comment]
Solved. It's some quotation marks issues with Textedit.

**Comment by XYAskWhy** [comment]
How did you solved this? I have a very similar issue.
> google.protobuf.text_format.ParseError: 112:25 : Expected string but found: '/'

**Comment by XYAskWhy** [comment]
Sloved. It was a mistake in the .config file.

**Comment by RakeshChandran** [comment]
@XYAskWhy what type of mistake was that ? Kindly elaborate.

**Comment by XYAskWhy** [comment]
I forgot the " ' ' " in one of the PATH_TO_BE_CONFIGUREDs. @RakeshChandran

**Comment by RakeshChandran** [comment]
Thank you for your response @XYAskWhy .. In my case it was a \n and \t operator in the path name.

**Comment by pooyan1983** [comment]
@XYAskWhy , @johnsonlegend  @RakeshChandran I have this problem when I run train.py in object_detection. This is what I get "TypeError: Expected string, got ['data/train.records'] of type 'RepeatedScalarFieldContainer' instead."
I have repleased all path_to_be_configured parts properly. Could you please advise?

**Comment by ngksai93** [comment]
i have also the same issue

**Comment by ngksai93** [comment]
/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 92, in main
    FLAGS.pipeline_config_path)
  File "/home/gopalakrishna/work/models-master/research/object_detection/utils/config_util.py", line 88, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 679, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1152, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
google.protobuf.text_format.ParseError: 186:1 : Expected identifier or number, got ''.
  

please help me

**Comment by pixx1** [comment]
Hi!
found a solution. 
I checked my label files with small Linux command-line program "file", the result was:
```
broken.pbtxt: UTF-8 Unicode (with BOM) text, with CRLF line terminators
working.pbtxt: ASCII text
```
So when you editing your label files keep track of it.

Hopefully it helps

**Comment by aawgit** [comment]
I faced a similar problem relating to label_map_path when running on local machine. Solved by removing spaces between lines in the label map pbtxt file.

**Comment by ruksin** [comment]
i faced a problem when running train.py for object detection..my error is like this:

doe@doe:~/anaconda3/envs/tensorflow/models/research/object_detection$ python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config
WARNING:tensorflow:From /home/doe/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1500, in _ParseAbstractInteger
    return int(text, 0)
ValueError: invalid literal for int() with base 0: '03'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1449, in _ConsumeInteger
    result = ParseInteger(tokenizer.token, is_signed=is_signed, is_long=is_long)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1471, in ParseInteger
    result = _ParseAbstractInteger(text, is_long=is_long)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1502, in _ParseAbstractInteger
    raise ValueError('Couldn\'t parse integer: %s' % text)
ValueError: Couldn't parse integer: 03

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/doe/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/doe/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 94, in main
    FLAGS.pipeline_config_path)
  File "/home/doe/anaconda3/envs/tensorflow/models/research/object_detection/utils/config_util.py", line 94, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 871, in _MergeScalarField
    value = _ConsumeInt32(tokenizer)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1362, in _ConsumeInt32
    return _ConsumeInteger(tokenizer, is_signed=True, is_long=False)
  File "/home/doe/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1451, in _ConsumeInteger
    raise tokenizer.ParseError(str(e))
google.protobuf.text_format.ParseError: 9:18 : Couldn't parse integer: 03

**Comment by pixx1** [comment]
@ruksin not quite shure about you file. But it sais 

"ValueError: Couldn't parse integer: 03"

is there something wrong with your label_map? 
Maybe you wrote id: 03 insteat of id: 3?

@chaine09 Maybe there was a problem with line break:
https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types#1552775

**Comment by tcai5633** [comment]
(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\tensorflow1\models\research\object_detection\utils\config_util.py", line 94, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 888, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1251, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1266, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1285, in _ConsumeSingleByteString
    raise self.ParseError('Expected string but found: %r' % (text,))
google.protobuf.text_format.ParseError: 106:23 : Expected string but found: '“'

請問遇到上面這個問題要怎麼解決?
謝謝

**Comment by ravikd123** [comment]
I'm getting the below error. please do help.

google.protobuf.text_format.ParseError: 158:3 : Message type "object_detection.protos.TrainConfig" has no field named "load_all_detection_checkpoint_vars".

**Comment by MalharJ** [comment]
@ravikd123 I'm getting the same error as well. Were you able to fix it?

**Comment by qwertyDvo** [comment]
I had encountered same problem and fix it by removing all comments in the top of the config file

**Comment by wanglidog** [comment]
> I had encountered same problem and fix it by removing all comments in the top of the config file

could you tell me how to solve this problem in detail?

**Comment by chibsta** [comment]
Hi,
I just commented out  "load_all_detection_checkpoint_vars=true" in my config file. If you get a "ValueError: axis = 0 not in [0, 0)" error after this see: HarshalGarg's comment at https://github.com/datitran/raccoon_dataset/issues/45.

I am training now. Fingers crossed will run to the end!

**Comment by qwertyDvo** [comment]
There were some comments (using this ' and #) in the config file at the top of config file. I had to remove them

**Comment by alwaysyes** [comment]
> Hi,
> I just commented out "load_all_detection_checkpoint_vars=true" in my config file. If you get a "ValueError: axis = 0 not in [0, 0)" error after this see: HarshalGarg's comment at https://github.com/[datitran/raccoon_dataset/issues/45](https://github.com/datitran/raccoon_dataset/issues/45).
> 
> I am training now. Fingers crossed will run to the end!

thank you

**Comment by alwaysyes** [comment]
> There were some comments (using this ' and #) in the config file at the top of config file. I had to remove them
> Sorry for my English if not clear

thanks for your idea. I have solved it by use your suggestion.

**Comment by venkatesha2411** [comment]
> Solved. It's some quotation marks issues with Textedit.

@johnsonlegend will you please elaborate how did you resolve the issue. Thank you in advance

**Comment by aadishjoshi** [comment]
My Error

`python "object_detection/model_main.py" --logtostderr --train_dir="training/" --pipeline_config_path="object_detection/ssd_mobilenet_v1_pets.config"
Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "C:\Users\aadis\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "C:\Users\aadis\Documents\Anaconda WorkSpace\TensorFlow\Custom_Object_Detection\models\research\object_detection\model_lib.py", line 536, in create_estimator_and_inputs
    config_override=config_override)
  File "C:\Users\aadis\Documents\Anaconda WorkSpace\TensorFlow\Custom_Object_Detection\models\research\object_detection\utils\config_util.py", line 96, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Users\aadis\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\aadis\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\aadis\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\aadis\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\aadis\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 706, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "C:\Users\aadis\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 1166, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
google.protobuf.text_format.ParseError: 1:1 : Expected identifier or number, got \ufeff.`


my Config File:
`# SSD with Mobilenet v1, configured for Oxford-IIIT Pets Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
# should be configured.

model {
  ssd {
    num_classes: 8
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v1'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 24
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "ssd_mobilenet_v1_coco_11_06_2017/model.ckpt"
  from_detection_checkpoint: true
  load_all_detection_checkpoint_vars: true
  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
  # never decay). Remove the below line to train indefinitely.
  num_steps: 200000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "data/train.record"
  }
  label_map_path: "training/object-detection.pbtxt"
}

eval_config: {
  metrics_set: "coco_detection_metrics"
  num_examples: 1100
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "data/test.record"
  }
  label_map_path: "training/object-detection.pbtxt"
  shuffle: false
  num_readers: 1
}
`

**Comment by mohdshafahad** [comment]
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=
training/ssd_inception_v2_coco.config
WARNING:tensorflow:From /home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/tensorflow/python/platform/app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 1402, in _ParseAbstractInteger
    return int(text, 0)
ValueError: invalid literal for int() with base 0: '}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 1351, in _ConsumeInteger
    result = ParseInteger(tokenizer.token, is_signed=is_signed, is_long=is_long)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 1373, in ParseInteger
    result = _ParseAbstractInteger(text, is_long=is_long)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 1404, in _ParseAbstractInteger
    raise ValueError('Couldn\'t parse integer: %s' % text)
ValueError: Couldn't parse integer: }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/tensorflow/python/util/deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/object_detection-0.1-py3.4.egg/object_detection/utils/config_util.py", line 100, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 477, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 527, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 560, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 575, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 676, in _MergeField
    merger(tokenizer, message, field)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 766, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 676, in _MergeField
    merger(tokenizer, message, field)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 801, in _MergeScalarField
    value = _ConsumeUint32(tokenizer)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 1279, in _ConsumeUint32
    return _ConsumeInteger(tokenizer, is_signed=False, is_long=False)
  File "/home/mohd/anaconda3/envs/tensorflow/lib/python3.4/site-packages/google/protobuf/text_format.py", line 1353, in _ConsumeInteger
    raise tokenizer.ParseError(str(e))
google.protobuf.text_format.ParseError: 174:1 : Couldn't parse integer: }

**Comment by mohdshafahad** [comment]
can somebody please help me in clearing this error?

**Comment by TarunPrajapat** [comment]
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\tensorflow\models\research\object_detection\utils\config_util.py", line 104, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 153:3 : Message type "object_detection.protos.TrainConfig" has no field named "load_all_detection_checkpoint_vars".

**Comment by Artem921** [comment]
has anyone encountered an error -google.protobuf.text_format.ParseError: 177:5 :

**Comment by sakshijain032** [comment]
> @XYAskWhy 
Can you please be more elaborative how you solved the error

**Comment by Artem921** [comment]
in the configuration file in a certain place there were no brackets - {}

**Comment by ozlemalci** [comment]
google.protobuf.text_format.ParseError: 7:1 : '<!DOCTYPE html>': Expected identifier or number, got <.

help me

**Comment by JanderHungrige** [comment]
Hi, I solved it by using the ubuntu text editor directly. Before it was opened by LibreOffice writer. At saving it asked me for the format and I saved as txt. That created the error. Using the text editor directly keep the .record form.

**Comment by JESLIYA-JOSE** [comment]
> Hi!
> found a solution.
> I checked my label files with small Linux command-line program "file", the result was:
> 
> ```
> broken.pbtxt: UTF-8 Unicode (with BOM) text, with CRLF line terminators
> working.pbtxt: ASCII text
> ```
> 
> So when you editing your files keep track of it.
> 
> Hopefully it helps

Please tell me what u did. I am not clear. I am stuck with the same issue.Expected identifier or number, got %s.' % result

**Comment by saurabhsharma495** [comment]
Sloved. It was a mistake in the .config file i have put '/' after "".

**Comment by JJmistry** [comment]
Changing the ' to " on line 21 fixed this issue for me
      type: "faster_rcnn_resnet50_keras"
