### ISSUE TITLE
Error running estimator cifar10_main.py on CPU

### ISSUE THREAD

**Issue by tfboyd** [tensorflow/models#1900]
/tutorials/image/cifar10_estimator

python cifar10_main.py --num_gpus=0 --train_steps=100 --data_dir=/home/toby/CIFAR/cifar-10-batches-py/ --num_intra_threads=0 --is_cpu_ps=True

WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpexIE_J
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': gpu_options {
}
allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_tf_random_seed': 1, '_keep_checkpoint_every_n_hours': 10000, '_save_checkpoints_steps': None, '_model_dir': '/tmp/tmpexIE_J', '_save_summary_steps': 100}
Starting to train...
INFO:tensorflow:image after unit resnet/tower_cpu/stage/residual_v1/: (?, 32, 32, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage/residual_v1_1/: (?, 32, 32, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage/residual_v1_2/: (?, 32, 32, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage/residual_v1_3/: (?, 32, 32, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage/residual_v1_4/: (?, 32, 32, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage/residual_v1_5/: (?, 32, 32, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage/residual_v1_6/: (?, 32, 32, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1/avg_pool/: (?, 16, 16, 16)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1/: (?, 16, 16, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1_1/: (?, 16, 16, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1_2/: (?, 16, 16, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1_3/: (?, 16, 16, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1_4/: (?, 16, 16, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1_5/: (?, 16, 16, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_1/residual_v1_6/: (?, 16, 16, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1/avg_pool/: (?, 8, 8, 32)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1/: (?, 8, 8, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1_1/: (?, 8, 8, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1_2/: (?, 8, 8, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1_3/: (?, 8, 8, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1_4/: (?, 8, 8, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1_5/: (?, 8, 8, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/stage_2/residual_v1_6/: (?, 8, 8, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/global_avg_pool/: (?, 64)
INFO:tensorflow:image after unit resnet/tower_cpu/fully_connected/: (?, 11)
INFO:tensorflow:Create CheckpointSaverHook.
2017-07-09 09:36:12.755980: I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 4 visible devices
2017-07-09 09:36:12.756467: I tensorflow/compiler/xla/service/service.cc:198] XLA service 0x5eba430 executing computations on platform Host. Devices:
2017-07-09 09:36:12.756483: I tensorflow/compiler/xla/service/service.cc:206]   StreamExecutor device (0): <undefined>, <undefined>
[libprotobuf ERROR google/protobuf/io/zero_copy_stream_impl_lite.cc:173] Cannot allocate buffer larger than kint32max for StringOutputStream.
Traceback (most recent call last):
  File "cifar10_main.py", line 416, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "cifar10_main.py", line 405, in main
    hooks=[logging_hook])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 612, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 944, in run
    feed_dict, options)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 970, in _call_hook_before_run
    request = hook.before_run(run_context)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 353, in before_run
    "graph.pbtxt")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/graph_io.py", line 67, in write_graph
    file_io.atomic_write_string_to_file(path, str(graph_def))
ValueError: Unable to convert message to str

**Comment by tfboyd** [comment]
I did almost zero debugging but I found it odd that this was printed twice.  When using the MKL this almost always is printed once.  It needs fixed but is not an issue.  I also tried without MKL.  All versions were TF 1.2 RC2.  

2017-07-09 09:47:12.661040: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes
2017-07-09 09:47:12.661085: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
2017-07-09 09:47:12.661107: E tensorflow/core/common_runtime/bfc_allocator.cc:378] tried to deallocate nullptr
2017-07-09 09:47:13.091671: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes
2017-07-09 09:47:13.091694: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
2017-07-09 09:47:13.091707: E tensorflow/core/common_runtime/bfc_allocator.cc:378] tried to deallocate nullptr

**Comment by tfboyd** [comment]
It also failed running on GPU with TF 1.2.1 installed from pip install tensorflow-gpu running this command.

python cifar10_main.py --num_gpus=1 --train_steps=100 --data_dir=/home/toby/CIFAR/cifar-10-batches-py/ --num_intra_threads=0 --is_cpu_ps=False --model_dir=./

A little weird as I know someone else is running this from the garden version.

**Comment by tfboyd** [comment]
I think I Know the issue.  I knew we were including the dataset in the graph and that might be creating the problem.  It is still "weird" that I see more "tried to allocate 0 bytes" more in this than I do in the other versions of the model code.  I will try to fix the dataset issue.

**Comment by protoget** [comment]
@tfboyd 
For the 1st msg: it's because the dataset serialization fix wasn't included. I'll update README to use nightly build 558 or later.
For the 2nd: I think it doesn't matter -- let me know if you think otherwise.
For the 3rd: if the error msg is the same as the first one, trying the right build would work.

**Comment by tfboyd** [comment]
I forgot all about the serialization thing.  palm to face.  Sorry.  At least we know that was not in 1.2 and we need to use placeholders which estimators does not seem to support when using tf.data.  CLOSED
