### ISSUE TITLE
when i want to change the voc_data to tf_data,it tell me that cannot import name string_int_label_map_pb2

### ISSUE THREAD

**Issue by yuye1992** [tensorflow/models#1904]
Traceback (most recent call last):
  File "create_pascal_tf_record.py", line 37, in <module>
    from object_detection.utils import label_map_util
  File "build/bdist.linux-x86_64/egg/object_detection/utils/label_map_util.py", line 22, in <module>
ImportError: cannot import name string_int_label_map_pb2

**Comment by korrawat** [comment]
Have you completed installation in the [instructions](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md)? 

Related: #1604

**Comment by yuye1992** [comment]
@korrawat  Oh,yes,i am sure,and it often happens that when i import some models,it will tell me that i cannot import it.

**Comment by kecaiwu** [comment]
May be you can add 'export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim' to your .bashrc file.

**Comment by michaelisard** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by yuye1992** [comment]
ubuntu 14.04,tensorflow-gpu1.01,python 2.7.6 @michaelisard Thank you.

**Comment by michaelisard** [comment]
Can you give more detailed repro instructions of exactly what you did that triggers the error, and a fuller error log? It is hard to know what the problem could be from the information you have given. Thanks!

**Comment by wt-huang** [comment]
Closing this issue due to inactivity, feel free to reopen if the problem persists.
