### ISSUE TITLE
Attention_ocr: get ResourceExhaustedError when train from scrach

### ISSUE THREAD

**Issue by wjbKimberly** [tensorflow/models#1921]
### System information
What is the top-level directory of the model you are using: attention_ocr
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
OS Platform and Distribution: Linux Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): ('v1.0.0-65-g4763edf-dirty', '1.0.1')
CUDA/cuDNN version: 8.0

### Describe the problem
When I running train.py to train form scrach, it returns ResourceExhaustedError, what should I do?

```
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 204, in main
    train(total_loss, init_fn, hparams)
  File "train.py", line 153, in train
    init_fn=init_fn)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 776, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 788, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 949, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 707, in prepare_or_wait_for_session
    self._write_graph()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 610, in _write_graph
    self._logdir, "graph.pbtxt")
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/graph_io.py", line 67, in write_graph
    file_io.atomic_write_string_to_file(path, str(graph_def))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 352, in atomic_write_string_to_file
    write_string_to_file(temp_pathname, contents)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 249, in write_string_to_file
    f.write(file_content)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 93, in write
    compat.as_bytes(file_content), self._writable_file, status)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: /tmp/attention_ocr/train/graph.pbtxt.tmp39fcda1ef6b0465a8c951797c07859da
```

**Comment by jart** [comment]
What is the make and model of your graphics card? It might not have enough GPU memory. Titan X cards are quite popular among users.

**Comment by wjbKimberly** [comment]
Thx for your rep!

**Comment by wjbKimberly** [comment]
It seems that the space /tmp is not enough, I clean up it and solved it.
Thx.
