### ISSUE TITLE
Incompatible shapes during the half way training?

### ISSUE THREAD

**Issue by protossw512** [tensorflow/models#1931]
I was training my self-created dataset on faster_rcnn_resnet101 to detect cars on drone images.
During the training,  it always shuts down itself at about 60-80 steps with 'Invalid argument' error message. It seems like the gradient tensor shape is not correct. The training dataset has only 48 images, each image is with size of 640x480. Each image could contain 1-~50 bounding boxes.  In .config I tried both default settings and my version, but same issue happens every time. And the images one have 1 channel, I did not do anything to convert them into 3 channel images. But it seems does not affect the code from running.

The annotations are saved in .xml file with the same format as PASCAL. 

Is there any way to allocate where is the issue?

**UPDATE:**
I switched to rfcn-resnet101, and it worked without any issue.

The full command line running log and error message:
```python
2017-07-11 14:45:32.571704: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-11 14:45:32.571747: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-11 14:45:32.571759: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-11 14:45:32.571769: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-11 14:45:32.571862: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-11 14:45:32.965550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:85:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
2017-07-11 14:45:32.965629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-07-11 14:45:32.965642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-07-11 14:45:32.965663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:85:00.0)
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Summary name Learning Rate is illegal; using Learning_Rate instead.
INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2017-07-11 14:45:58.528415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:85:00.0)
INFO:tensorflow:Restoring parameters from ./train_car/model.ckpt-0
2017-07-11 14:46:00.330317: I tensorflow/core/common_runtime/simple_placer.cc:675] Ignoring device specification /device:GPU:0 for node 'prefetch_queue_Dequeue' because the input edge from 'prefetch_queue' is a reference connection and already has a device field set to /device:CPU:0
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path ./train_car/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Recording summary at step 0.
INFO:tensorflow:global step 1: loss = 6.7217 (9.334 sec/step)
2017-07-11 14:46:18.295713: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2383 get requests, put_count=1972 evicted_count=1000 eviction_rate=0.507099 and unsatisfied allocation rate=0.634075
2017-07-11 14:46:18.295793: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:global step 2: loss = 1.3664 (1.021 sec/step)
INFO:tensorflow:global step 3: loss = 1.4107 (0.851 sec/step)
INFO:tensorflow:global step 4: loss = 1.6531 (0.852 sec/step)
INFO:tensorflow:global step 5: loss = 1.9746 (0.828 sec/step)
INFO:tensorflow:global step 6: loss = 1.2003 (0.831 sec/step)
INFO:tensorflow:global step 7: loss = 9.3316 (0.864 sec/step)
INFO:tensorflow:global step 8: loss = 0.9591 (0.848 sec/step)
INFO:tensorflow:global step 9: loss = 1.0816 (0.855 sec/step)
INFO:tensorflow:global step 10: loss = 12.4307 (0.862 sec/step)
INFO:tensorflow:global step 11: loss = 1.2062 (0.868 sec/step)
INFO:tensorflow:global step 12: loss = 7.5121 (0.849 sec/step)
INFO:tensorflow:global step 13: loss = 0.8427 (0.840 sec/step)
INFO:tensorflow:global step 14: loss = 1.8111 (0.847 sec/step)
INFO:tensorflow:global step 15: loss = 1.2490 (0.850 sec/step)
INFO:tensorflow:global step 16: loss = 0.9210 (0.842 sec/step)
INFO:tensorflow:global step 17: loss = 0.7701 (0.871 sec/step)
2017-07-11 14:46:32.286401: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2110 get requests, put_count=2062 evicted_count=1000 eviction_rate=0.484966 and unsatisfied allocation rate=0.507583
2017-07-11 14:46:32.286591: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
INFO:tensorflow:global step 18: loss = 2.1307 (0.853 sec/step)
INFO:tensorflow:global step 19: loss = 10.3885 (0.858 sec/step)
INFO:tensorflow:global step 20: loss = 1.1922 (0.826 sec/step)
INFO:tensorflow:global step 21: loss = 7.8912 (0.851 sec/step)
INFO:tensorflow:global step 22: loss = 1.1314 (0.875 sec/step)
INFO:tensorflow:global step 23: loss = 1.6444 (0.847 sec/step)
INFO:tensorflow:global step 24: loss = 0.8428 (0.857 sec/step)
INFO:tensorflow:global step 25: loss = 1.9894 (0.840 sec/step)
INFO:tensorflow:global step 26: loss = 1.5942 (0.850 sec/step)
INFO:tensorflow:global step 27: loss = 5.2916 (0.842 sec/step)
INFO:tensorflow:global step 28: loss = 2.8976 (0.842 sec/step)
INFO:tensorflow:global step 29: loss = 0.7820 (0.855 sec/step)
INFO:tensorflow:global step 30: loss = 0.6961 (0.841 sec/step)
INFO:tensorflow:global step 31: loss = 10.2150 (0.832 sec/step)
INFO:tensorflow:global step 32: loss = 0.9315 (0.879 sec/step)
INFO:tensorflow:global step 33: loss = 11.1960 (0.831 sec/step)
INFO:tensorflow:global step 34: loss = 0.8144 (0.871 sec/step)
INFO:tensorflow:global step 35: loss = 2.1525 (0.833 sec/step)
INFO:tensorflow:global step 36: loss = 10.7719 (0.866 sec/step)
INFO:tensorflow:global step 37: loss = 0.8374 (0.852 sec/step)
INFO:tensorflow:global step 38: loss = 0.6778 (0.838 sec/step)
INFO:tensorflow:global step 39: loss = 9.7022 (0.847 sec/step)
INFO:tensorflow:global step 40: loss = 0.7753 (0.832 sec/step)
INFO:tensorflow:global step 41: loss = 0.8812 (0.841 sec/step)
INFO:tensorflow:global step 42: loss = 7.0602 (0.845 sec/step)
INFO:tensorflow:global step 43: loss = 0.8531 (0.851 sec/step)
INFO:tensorflow:global step 44: loss = 2.2444 (0.850 sec/step)
INFO:tensorflow:global step 45: loss = 1.3414 (0.854 sec/step)
INFO:tensorflow:global step 46: loss = 1.0245 (0.851 sec/step)
INFO:tensorflow:global step 47: loss = 0.4828 (0.864 sec/step)
INFO:tensorflow:global step 48: loss = 8.9272 (0.845 sec/step)
INFO:tensorflow:global step 49: loss = 0.7533 (0.853 sec/step)
INFO:tensorflow:global step 50: loss = 0.4499 (0.867 sec/step)
INFO:tensorflow:global step 51: loss = 0.2957 (0.869 sec/step)
INFO:tensorflow:global step 52: loss = 0.3013 (0.836 sec/step)
2017-07-11 14:47:02.073326: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 7385 get requests, put_count=7492 evicted_count=1000 eviction_rate=0.133476 and unsatisfied allocation rate=0.12891
2017-07-11 14:47:02.073427: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 655 to 720
INFO:tensorflow:global step 53: loss = 1.7691 (0.832 sec/step)
INFO:tensorflow:global step 54: loss = 0.4391 (0.850 sec/step)
INFO:tensorflow:global step 55: loss = 0.5527 (0.833 sec/step)
INFO:tensorflow:global step 56: loss = 0.5139 (0.851 sec/step)
INFO:tensorflow:global step 57: loss = 0.3027 (0.852 sec/step)
INFO:tensorflow:global step 58: loss = 0.2983 (0.864 sec/step)
INFO:tensorflow:global step 59: loss = 0.2247 (0.870 sec/step)
INFO:tensorflow:global step 60: loss = 0.4706 (0.842 sec/step)
INFO:tensorflow:global step 61: loss = 7.5751 (0.869 sec/step)
INFO:tensorflow:global step 62: loss = 0.4400 (0.855 sec/step)
INFO:tensorflow:global step 63: loss = 0.3054 (0.864 sec/step)
INFO:tensorflow:global step 64: loss = 6.7280 (0.842 sec/step)
INFO:tensorflow:global step 65: loss = 4.8004 (0.854 sec/step)
INFO:tensorflow:global step 66: loss = 0.2637 (0.868 sec/step)
INFO:tensorflow:global step 67: loss = 1.5711 (0.845 sec/step)
INFO:tensorflow:global step 68: loss = 0.2334 (0.866 sec/step)
INFO:tensorflow:global step 69: loss = 0.6833 (0.846 sec/step)
2017-07-11 14:47:16.293535: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Incompatible shapes: [1,63,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
2017-07-11 14:47:16.293796: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Incompatible shapes: [1,63,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
2017-07-11 14:47:16.293909: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Incompatible shapes: [1,63,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Incompatible shapes: [1,63,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
	 [[Node: gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1/_3931 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22225_gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs', defined at:
  File "train.py", line 198, in <module>
    tf.app.run()
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/scratch2/wangxiny2/workspace/models/object_detection/trainer.py", line 220, in train
    clones, training_optimizer, regularization_losses=None)
  File "/scratch2/wangxiny2/workspace/models/slim/deployment/model_deploy.py", line 297, in optimize_clones
    optimizer, clone, num_clones, regularization_losses, **kwargs)
  File "/scratch2/wangxiny2/workspace/models/slim/deployment/model_deploy.py", line 261, in _optimize_clone
    clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 540, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 346, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 540, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.py", line 650, in _SubGrad
    rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 395, in _broadcast_gradient_args
    name=name)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'Loss/BoxClassifierLoss/Loss/sub', defined at:
  File "train.py", line 198, in <module>
    tf.app.run()
[elided 1 identical lines from previous traceback]
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/scratch2/wangxiny2/workspace/models/object_detection/trainer.py", line 192, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/scratch2/wangxiny2/workspace/models/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/scratch2/wangxiny2/workspace/models/object_detection/trainer.py", line 133, in _create_losses
    losses_dict = detection_model.loss(prediction_dict)
  File "/scratch2/wangxiny2/workspace/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1173, in loss
    groundtruth_classes_with_background_list))
  File "/scratch2/wangxiny2/workspace/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1329, in _loss_box_classifier
    batch_reg_targets, weights=batch_reg_weights) / normalizer
  File "/scratch2/wangxiny2/workspace/models/object_detection/core/losses.py", line 71, in __call__
    return self._compute_loss(prediction_tensor, target_tensor, **params)
  File "/scratch2/wangxiny2/workspace/models/object_detection/core/losses.py", line 157, in _compute_loss
    diff = prediction_tensor - target_tensor
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2501, in _sub
    result = _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,63,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
	 [[Node: gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1/_3931 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22225_gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    tf.app.run()
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/scratch2/wangxiny2/workspace/models/object_detection/trainer.py", line 290, in train
    saver=saver)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 749, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 488, in train_step
    run_metadata=run_metadata)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,63,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
	 [[Node: gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1/_3931 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22225_gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs', defined at:
  File "train.py", line 198, in <module>
    tf.app.run()
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/scratch2/wangxiny2/workspace/models/object_detection/trainer.py", line 220, in train
    clones, training_optimizer, regularization_losses=None)
  File "/scratch2/wangxiny2/workspace/models/slim/deployment/model_deploy.py", line 297, in optimize_clones
    optimizer, clone, num_clones, regularization_losses, **kwargs)
  File "/scratch2/wangxiny2/workspace/models/slim/deployment/model_deploy.py", line 261, in _optimize_clone
    clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 540, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 346, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 540, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.py", line 650, in _SubGrad
    rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 395, in _broadcast_gradient_args
    name=name)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'Loss/BoxClassifierLoss/Loss/sub', defined at:
  File "train.py", line 198, in <module>
    tf.app.run()
[elided 1 identical lines from previous traceback]
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/scratch2/wangxiny2/workspace/models/object_detection/trainer.py", line 192, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/scratch2/wangxiny2/workspace/models/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/scratch2/wangxiny2/workspace/models/object_detection/trainer.py", line 133, in _create_losses
    losses_dict = detection_model.loss(prediction_dict)
  File "/scratch2/wangxiny2/workspace/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1173, in loss
    groundtruth_classes_with_background_list))
  File "/scratch2/wangxiny2/workspace/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1329, in _loss_box_classifier
    batch_reg_targets, weights=batch_reg_weights) / normalizer
  File "/scratch2/wangxiny2/workspace/models/object_detection/core/losses.py", line 71, in __call__
    return self._compute_loss(prediction_tensor, target_tensor, **params)
  File "/scratch2/wangxiny2/workspace/models/object_detection/core/losses.py", line 157, in _compute_loss
    diff = prediction_tensor - target_tensor
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2501, in _sub
    result = _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
  File "/scratch2/wangxiny2/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,63,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
	 [[Node: gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1/_3931 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22225_gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_1/bottleneck_v1/conv3/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by frederictost** [comment]
You can try to start your class id from 1 instead of 0. It worked for me.
item {
  id: 1
  name: 'balloon'
}
