### ISSUE TITLE
pet detector - model freeze

### ISSUE THREAD

**Issue by mattryles** [tensorflow/models#1995]
Hi,

This is a feature request, the pet detector tutorial has really helped me but I am struggling to freeze the inference outputted graph, specifically what to input for "output_node_names".

What would be great if you could just add another section for freezing the pet detector.

I'd be happy to write the tutorial once I got mine going :) I'm probably in a good place to do it being extremely new to tensorflow.

**Comment by mattryles** [comment]
Going follow this later :
https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

If I succeed tonight I'll write a small tutorial and post it.

**Comment by mattryles** [comment]
I've pulled a list of the nodes from the object graph but not sure which nodes are relevant for the detection for the pet detector.

Any guidance?

Thanks

Matt

**Comment by mattryles** [comment]
Okay so I've manage to run freeze_graph.py using the following  command:

bazel build tensorflow/python/tools:freeze_graph && \
bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=tensorflow/python/tools/freezeinput/output_inference_graph.pb \
--input_checkpoint=tensorflow/python/tools/freezeinput/myoutput/train/model.ckpt-12731 \
--output_graph=tensorflow/python/tools/freezeoutput/frozen_graph.pb  --output_node_names=softmax


and getting this error from protbuf  :(

matt@matt-pc-ubuntu:~/tensorflow$ bazel build tensorflow/python/tools:freeze_graph && \
> bazel-bin/tensorflow/python/tools/freeze_graph \
> --input_graph=tensorflow/python/tools/freezeinput/output_inference_graph.pb \
> --input_checkpoint=tensorflow/python/tools/freezeinput/myoutput/train/model.ckpt-12731 \
> --output_graph=tensorflow/python/tools/freezeoutput/frozen_graph.pb  --output_node_names=softmax
WARNING: /home/matt/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/matt/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/distributed_runtime/master_session.cc:
tensorflow/core/distributed_runtime/master_session.cc: In member function 'tensorflow::Status tensorflow::MasterSession::ReffedClientGraph::RunPartitions(const tensorflow::MasterEnv*, tensorflow::int64, tensorflow::int64, tensorflow::SimpleGraphExecutionState*, tensorflow::MasterSession::PerStepState*, tensorflow::CallOptions*, const tensorflow::RunStepRequestWrapper&, tensorflow::MutableRunStepResponseWrapper*, tensorflow::CancellationManager*, bool)':
tensorflow/core/distributed_runtime/master_session.cc:568:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < req.num_feeds(); ++i) {
                         ^
tensorflow/core/distributed_runtime/master_session.cc:580:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         } else if (feeds_iter->second != i) {
                                       ^
tensorflow/core/distributed_runtime/master_session.cc:588:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < req.num_fetches(); ++i) {
                         ^
tensorflow/core/distributed_runtime/master_session.cc: At global scope:
tensorflow/core/distributed_runtime/master_session.cc:443:13: warning: 'bool tensorflow::CopyIfNeeded(tensorflow::TensorProto*, tensorflow::TensorProto*)' defined but not used [-Wunused-function]
 static bool CopyIfNeeded(TensorProto* in, TensorProto* out) {
             ^
INFO: From Compiling tensorflow/python/pywrap_tensorflow_internal.cc:
bazel-out/local-opt/bin/tensorflow/python/pywrap_tensorflow_internal.cc: In function 'PyObject* _wrap_PyRecordReader_New(PyObject*, PyObject*)':
bazel-out/local-opt/bin/tensorflow/python/pywrap_tensorflow_internal.cc:4784:138: warning: 'arg2' may be used uninitialized in this function [-Wmaybe-uninitialized]
     result = (tensorflow::io::PyRecordReader *)tensorflow::io::PyRecordReader::New((string const &)*arg1,arg2,(string const &)*arg3,arg4);
                                                                                                                                          ^
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-self-assign'
INFO: From Compiling tensorflow/stream_executor/stream_executor_pimpl.cc:
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/core/status.h:24,
                 from ./tensorflow/stream_executor/lib/status.h:21,
                 from ./tensorflow/stream_executor/stream_executor_pimpl.h:25,
                 from tensorflow/stream_executor/stream_executor_pimpl.cc:20:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::__cxx11::string* tensorflow::internal::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = int; T2 = long long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
tensorflow/stream_executor/stream_executor_pimpl.cc:615:3:   required from here
./tensorflow/core/platform/default/logging.h:228:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         == )  // Compilation error with CHECK_EQ(NULL, x)?
                         ^
./tensorflow/core/platform/macros.h:76:29: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (x)
                             ^
./tensorflow/core/platform/default/logging.h:227:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
 ^
INFO: From Compiling tensorflow/core/kernels/hexagon/hexagon_rewriter_transform.cc:
tensorflow/core/kernels/hexagon/hexagon_rewriter_transform.cc: In function 'tensorflow::Status tensorflow::graph_transforms::RewriteQuantizedStrippedModelForHexagon(const tensorflow::GraphDef&, const tensorflow::graph_transforms::TransformFuncContext&, tensorflow::GraphDef*)':
tensorflow/core/kernels/hexagon/hexagon_rewriter_transform.cc:50:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < context.input_names.size(); ++i) {
                      ^
INFO: From Compiling tensorflow/core/kernels/remote_fused_graph_execute_utils.cc:
tensorflow/core/kernels/remote_fused_graph_execute_utils.cc: In static member function 'static tensorflow::Status tensorflow::RemoteFusedGraphExecuteUtils::DryRunInferenceForAllNode(const tensorflow::GraphDef&, const std::vector<std::pair<std::__cxx11::basic_string<char>, tensorflow::Tensor> >&, bool, tensorflow::RemoteFusedGraphExecuteUtils::TensorShapeMap*)':
tensorflow/core/kernels/remote_fused_graph_execute_utils.cc:162:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < output_node_names.size(); ++i) {
                     ^
tensorflow/core/kernels/remote_fused_graph_execute_utils.cc:167:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < input_node_info_list.size(); ++i) {
                     ^
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,back
                 from ./tensorflow/core/lib/core/status.h:24,
                 from ./tensorflow/core/lib/core/errors.h:19,
                 from ./tensorflow/core/framework/tensor_shape.h:24,
                 from ./tensorflow/core/framework/partial_tensor_shape.h:22,
                 from ./tensorflow/core/framework/attr_value_util.h:22,
                 from ./tensorflow/core/framework/function.h:20,
                 from ./tensorflow/core/graph/graph.h:43,
                 from ./tensorflow/core/kernels/remote_fused_graph_execute_utils.h:23,
                 from tensorflow/core/kernels/remote_fused_graph_execute_utils.cc:16:
tensorflow/core/kernels/remote_fused_graph_execute_utils.cc:172:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(graph_def.node_size() == output_tensors.size());
                               ^
./tensorflow/core/platform/macros.h:75:30: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (x)
                              ^
tensorflow/core/kernels/remote_fused_graph_execute_utils.cc:172:3: note: in expansion of macro 'CHECK'
   CHECK(graph_def.node_size() == output_tensors.size());
   ^
INFO: From Compiling tensorflow/core/distributed_runtime/master.cc:
tensorflow/core/distributed_runtime/master.cc: In member function 'tensorflow::Status tensorflow::DeviceFinder::Wait()':
tensorflow/core/distributed_runtime/master.cc:199:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < targets_.size(); ++i) {
                           ^
INFO: From Compiling tensorflow/tools/graph_transforms/quantize_nodes.cc:
tensorflow/tools/graph_transforms/quantize_nodes.cc:172:6: warning: 'bool tensorflow::graph_transforms::{anonymous}::AreAttrsEqual(const tensorflow::NodeDef*, const tensorflow::NodeDef*)' defined but not used [-Wunused-function]
 bool AreAttrsEqual(const NodeDef* current_node, const NodeDef* other_node) {
      ^
Target //tensorflow/python/tools:freeze_graph up-to-date:
  bazel-bin/tensorflow/python/tools/freeze_graph
INFO: Elapsed time: 56.850s, Critical Path: 12.79s
Traceback (most recent call last):
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 218, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 150, in main
    FLAGS.variable_names_blacklist)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 96, in freeze_graph
    text_format.Merge(f.read(), input_graph_def)
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 619, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 1066, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number.')
google.protobuf.text_format.ParseError: 2:1 : Expected identifier or number.
matt@matt-pc-ubuntu:~/tensorflow$

**Comment by drpngx** [comment]
Can you put your model on pastebin? It looks like it's not a correct text protobuf format

**Comment by mattryles** [comment]
my graph.pbtxt is 20.7 MB

**Comment by drpngx** [comment]
It looks like it's having issue on the first two lines.

**Comment by mattryles** [comment]
Thanks, you helped me just discovered I was using a .pb file for --input_graph= and not the .pbtxt file.
So I added  --input_binary=true and still got an error.

So I ran it against my pbtxt file with --input_binary=false and got a result.

Thank you very much, I can nearly taste this working end to end. From images to API wrapper.

bazel build tensorflow/python/tools:freeze_graph && \
bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=tensorflow/python/tools/freezeinput/myoutput/train/graph.pbtxt \
--input_checkpoint=tensorflow/python/tools/freezeinput/myoutput/train/model.ckpt-12731 \
--output_graph=tensorflow/python/tools/freezeoutput/frozen_graph.pb  --output_node_names=Softmax \
--input_binary=false

**Comment by drpngx** [comment]
Just curious, what error did you get when using `--input_binary=true`?

**Comment by mattryles** [comment]
`matt@matt-pc-ubuntu:~/tensorflow$ 
matt@matt-pc-ubuntu:~/tensorflow$ bazel build tensorflow/python/tools:freeze_graph && \
> bazel-bin/tensorflow/python/tools/freeze_graph \
> --input_graph=tensorflow/python/tools/freezeinput/output_inference_graph.pb \
> --input_checkpoint=tensorflow/python/tools/freezeinput/myoutput/train/model.ckpt-12731 \
> --output_graph=tensorflow/python/tools/freezeoutput/frozen_graph.pb  --output_node_names=Softmax \
> --input_binary=true
WARNING: /home/matt/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/matt/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
Target //tensorflow/python/tools:freeze_graph up-to-date:
  bazel-bin/tensorflow/python/tools/freeze_graph
INFO: Elapsed time: 0.264s, Critical Path: 0.00s
2017-07-20 18:56:06.170467: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170483: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170487: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170490: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170493: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 218, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 150, in main
    FLAGS.variable_names_blacklist)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 127, in freeze_graph
    saver = saver_lib.Saver(var_list=var_list)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 673, in build
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 602, in _ValidateAndSliceInputs
    variable)
TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("Conv/biases:0", shape=(512,), dtype=float32)
matt@matt-pc-ubuntu:~/tensorflow$ 
matt@matt-pc-ubuntu:~/tensorflow$ `

**Comment by mattryles** [comment]
`matt@matt-pc-ubuntu:~/tensorflow$ 
matt@matt-pc-ubuntu:~/tensorflow$ bazel build tensorflow/python/tools:freeze_graph && \
> bazel-bin/tensorflow/python/tools/freeze_graph \
> --input_graph=tensorflow/python/tools/freezeinput/output_inference_graph.pb \
> --input_checkpoint=tensorflow/python/tools/freezeinput/myoutput/train/model.ckpt-12731 \
> --output_graph=tensorflow/python/tools/freezeoutput/frozen_graph.pb  --output_node_names=Softmax \
> --input_binary=true
WARNING: /home/matt/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/matt/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
Target //tensorflow/python/tools:freeze_graph up-to-date:
  bazel-bin/tensorflow/python/tools/freeze_graph
INFO: Elapsed time: 0.264s, Critical Path: 0.00s
2017-07-20 18:56:06.170467: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170483: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170487: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170490: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 18:56:06.170493: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 218, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 150, in main
    FLAGS.variable_names_blacklist)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 127, in freeze_graph
    saver = saver_lib.Saver(var_list=var_list)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 673, in build
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/home/matt/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 602, in _ValidateAndSliceInputs
    variable)
TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("Conv/biases:0", shape=(512,), dtype=float32)
matt@matt-pc-ubuntu:~/tensorflow$ 
`

**Comment by mattryles** [comment]
Just to clear this up.

"The output of export_inference_graph.py should currently already be a frozen graph, so it would be redundant to try to freeze it again."

https://stackoverflow.com/questions/45218374/freezing-the-tensorflow-object-detection-api-pet-detector-graph/45222284#45222284

**Comment by fastlater** [comment]
@mattryles I am having the same error
TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("Conv/biases:0", shape=(512,), dtype=float32)
when I am trying in cmd
python freeze_graph.py --input_graph=output_graph.pb --input_checkpoint=map.ckpt --input_binary=true --output_graph=./tmp/frozen_graph.pb --output_node_names=final_result

I tried to use --variable_name_blacklist but nothing happens.

**Comment by mattryles** [comment]
Try just using the graph.pbtxt file with  --input_binary=false, it worked for me but when I tried to integrate it with an API it didn't output the correct operations, "image_tensor:0" could not be found. I am not sure why. So maybe I either outputed the wrong node_names or somethign else went wrong along the way. I'm going to start training end to end this weekend, so hopefully I'll be in a better situation then.

**Comment by mattryles** [comment]
Okay, so I've done the whole process end to end with my images resized to 20% the original size and it's gone way better, my eval ran smoothly. I used the ssd_inception_v2 feature extractor this time.

This time when I look inside my graph.pbtxt I'm not sure which node I should use to export? Softmax isn't there, is there a different output node for ssd_inception_v2 ?

**Comment by mattryles** [comment]
So I've retrained the model, it's all gone really well, eval worked fine and in tensorboard everything is detected.

I run it through the frozen_graph.pb with --output_node_names=Softmax and it works.

Then when I follow the Jupyter Notebook I get this error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-ac6bec7b5dbb> in <module>()
      9       # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
     10       image_np_expanded = np.expand_dims(image_np, axis=0)
---> 11       image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
     12       # Each box represents a part of the image where a particular object was detected.
     13       boxes = detection_graph.get_tensor_by_name('detection_boxes:0')

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in get_tensor_by_name(self, name)
   2731       raise TypeError("Tensor names are strings (or similar), not %s."
   2732                       % type(name).__name__)
-> 2733     return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
   2734 
   2735   def _next_id(self):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in as_graph_element(self, obj, allow_tensor, allow_operation)
   2582 
   2583     with self._lock:
-> 2584       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
   2585 
   2586   def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   2624           raise KeyError("The name %s refers to a Tensor which does not "
   2625                          "exist. The operation, %s, does not exist in the "
-> 2626                          "graph." % (repr(name), repr(op_name)))
   2627         try:
   2628           return op.outputs[out_n]

KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

**Comment by mattryles** [comment]
I used export_inference_graph.py instead of freeze_graph
