### ISSUE TITLE
I want to port SSD model to mobile, but I met several problems.

### ISSUE THREAD

**Issue by GodOfSmallThings** [tensorflow/models#2003]
I want to port SSD model into tensorflow mobile, and I met problem.

In "tensorflow/example/android/src/org/DetectorActivity.java", I changed
_private static final String YOLO_MODEL_FILE = "file:///android_asset/graph-tiny-yolo-voc.pb" as
private static final String YOLO_MODEL_FILE = "file:///android_asset/ssd_mobilenet_graph.pb"_ , which is SSD's frozen graph. 

However, when I installed it into mobile(Galaxy 7) it stops with error message below.

_java.lang.IllegalArgumentException: No Operation named [input] in the Graph
                                                                         at org.tensorflow.Session$Runner.operationByName(Session.java:353)
                                                                         at org.tensorflow.Session$Runner.feed(Session.java:142)
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.addFeed(TensorFlowInferenceInterface.java:415)
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.feed(TensorFlowInferenceInterface.java:216)
                                                                         at org.tensorflow.demo.TensorFlowYoloDetector.recognizeImage(TensorFlowYoloDetector.java:154)
                                                                         at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:312)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)_

So I thought code below is the problem. How should I change this?
 
_private static final String YOLO_INPUT_NAME = "input";
private static final String YOLO_OUTPUT_NAMES = "output";_

Thank you.

**Comment by jch1** [comment]
Hi @GodOfSmallThings - we will update the Android Detect demo very soon to handle checkpoints trained using the Tensorflow Object Detection API.  Stay tuned :)

**Comment by dbishai** [comment]
I wrote my own SSD detector class loosely based off of TensorFlowYoloDetector. I am using the following for inputs and outputs:

```java
    private static final String SSD_MODEL_FILE = "file:///android_asset/ssd_mobilenet_v1_coco_11_06_2017.pb";
    private static final String SSD_INPUT_NAME = "image_tensor:0";
    private static final String[] SSD_OUTPUT_NAMES = {"detection_boxes:0", "detection_scores:0", "detection_classes:0", "num_detections:0"};
```

**Comment by eshirima** [comment]
@jch1 Will there be support for iOS?

**Comment by GodOfSmallThings** [comment]
Thank you for all replies ! :)

**Comment by GodOfSmallThings** [comment]
@jch1 BTW, would it update SSD MobileNet too? :)
