### ISSUE TITLE
CMP Loading Area6 Mesh Error

### ISSUE THREAD

**Issue by daerduoCarey** [tensorflow/models#2079]
Hi, @s-gupta 

When I'm visualizing the area_6 mesh using your `script_env_vis.py` script, I encounter the following error. BTW, there is no problem loading and visualizing other area meshes.

`Traceback (most recent call last):
  File "scripts/script_env_vis.py", line 187, in <module>
    app.run()
  File "/home/kaichun/Documents/models/cognitive_mapping_and_planning/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "scripts/script_env_vis.py", line 183, in main
    b = load_building(FLAGS.dataset_name, FLAGS.building_name)
  File "scripts/script_env_vis.py", line 79, in load_building
    b.load_building_into_scene()
  File "/home/kaichun/Documents/models/cognitive_mapping_and_planning/datasets/nav_env.py", line 386, in load_building_into_scene
    self.renderer_entitiy_ids += self.r_obj.load_shapes(self.shapess)
  File "/home/kaichun/Documents/models/cognitive_mapping_and_planning/render/swiftshader_renderer.py", line 377, in load_shapes
    assert name not in entities, '{:s} entity already exists.'.format(name)
AssertionError: area6_ entity already exists.
`

I suppose this error comes from some error while loading the mesh. I find that there are several sub-meshes have the same names "area6_" with no texture image suffix attached. Can you help me figure out the reason? I'd appreciate it very much!

Also, may I ask why you didn't use area_2 in your experiment? Thanks!

Thank you!

Bests,
Kaichun

**Comment by s-gupta** [comment]
I pushed a fix in PR #2082.

**Comment by daerduoCarey** [comment]
thanks.
