### ISSUE TITLE
when i run model_builder_test.py in terminal, it pops the error   from google.protobuf.internal import python_message   File "D:\python35\lib\site-packages\google\protobuf\internal\python_message.py", line 846     except struct.error, e:                        ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sainttelant** [tensorflow/models#2118]
as mentioned above, it pops the error as follows details:

 Traceback (most recent call last):
  File "D:\python35\Lib\site-packages\tensorflow\models\object_detection\builders\model_builder_test.py", line 18, in <module>
    import tensorflow as tf
  File "D:\python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "D:\python35\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "D:\python35\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "D:\python35\lib\site-packages\google\protobuf\reflection.py", line 68, in <module>
 from google.protobuf.internal import python_message
  File "D:\python35\lib\site-packages\google\protobuf\internal\python_message.py", line 846
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
