### ISSUE TITLE
something wrong with training Resnet_v2_152

### ISSUE THREAD

**Issue by bruce1408** [tensorflow/models#2128]
# ============error info============
Traceback (most recent call last):
  File "train_image_classifier.py", line 573, in <module>
    tf.app.run()
  File "/home/bruce/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 533, in main
    var_list=variables_to_train)
  File "/home/bruce/tensorflow/example_learn/models/slim/deployment/model_deploy.py", line 297, in optimize_clones
    optimizer, clone, num_clones, regularization_losses, **kwargs)
  File "/home/bruce/tensorflow/example_learn/models/slim/deployment/model_deploy.py", line 261, in _optimize_clone
    clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)
  File "/home/bruce/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 380, in compute_gradients
    raise ValueError("No variables to optimize.")
ValueError: No variables to optimize.
# ==============================
when i use my own dataset to train with resnet_v2_152,something wrong as above. I wrote a scripe as the web did .
# ============the scripe ============
DATASET_DIR=/home/bruce/dataset/data/record_slim/
 TRAIN_DIR=/home/bruce/tensorflow/example_learn/models/slim/new_checkpoint
 CHECKPOINT_PATH=/home/bruce/tensorflow/example_learn/models/slim/resnet_v2_152.ckpt
 python train_image_classifier.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=dogs \
    --dataset_split_name=train \
    --model_name=resnet_v2_152 \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --checkpoint_exclude_scopes=Resnet_v2_152/Logits,Resnet_v2_152/AuxLogits \
    --trainable_scopes=Resnet_v2_152/Logits,Resnet_v2_152/AuxLogits
# ==========================
thx !

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by hangzh2012** [comment]
resnet_v2_152 modle don't have scope "Resnet_v2_152/Logits,Resnet_v2_152/AuxLogits"
try :
--checkpoint_exclude_scopes=resnet_v2_152/logits 
--trainable_scopes=resnet_v2_152/logits
