### ISSUE TITLE
street

### ISSUE THREAD

**Issue by starkhu** [tensorflow/models#2176]
hello,brothers,the model i run is Street
there is an error when i run vgsl_model_test.py.(my python version is 2.7)
the error information is:

Traceback (most recent call last):
  File "vgsl_model_test.py", line 230, in testEndToEndSizes1dFixed
    mode='train')
  File "/home/star/workspace/models/street/python/vgsl_model.py", line 225, in InitNetwork
    optimizer_type, num_preprocess_threads, reader)
  File "/home/star/workspace/models/street/python/vgsl_model.py", line 319, in Build
    self._AddOptimizer(optimizer_type)
  File "/home/star/workspace/models/street/python/vgsl_model.py", line 490, in _AddOptimizer
    self.loss, global_step=self.global_step, name='train')
  File "/home/star/anaconda3/envs/my_tf/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 315, in minimize
    grad_loss=grad_loss)
  File "/home/star/anaconda3/envs/my_tf/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/star/anaconda3/envs/my_tf/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 514, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'Loufx64_35/forward/VariableLSTM' (op type: VariableLSTM)

How should i do?
thankyou!

**Comment by reedwm** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by dksb** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
