### ISSUE TITLE
ImportError: libcusolver.so.7.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shuuchen** [tensorflow/models#2257]
Hi All,

I am trying to install following https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md

But the following error happens when I test installation:
```python
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 18, in <module>
    import tensorflow as tf
  File "/home/shuchen/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/shuchen/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/shuchen/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/shuchen/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/shuchen/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/shuchen/softwares/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcusolver.so.7.5: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
I am using ubuntu 16.04, cuda8.0, cuDNN 6.0 and python 2.7

Any help please?

**Comment by shuuchen** [comment]
I have followed https://github.com/tensorflow/tensorflow/issues/1501 and other issues to set the
environment variables, but it doesn't work

**Comment by AhmedRebai** [comment]
Hi, me too when I run: import tensorflow as tf 

I got this 

ImportError: libcusolver.so.7.5: cannot open shared object file: No such file or directory

**Comment by shuuchen** [comment]
@AhmedRebai 
I solved that by upgrading tensorflow to the latest version

**Comment by tfboyd** [comment]
As of TF 1.0 CUDA 8 is the default.  I am surprised if many of the examples work with TF pre 1.0.  I understand you may have compiled from source.  Either way I strongly and kindly suggest CUDA 8 and cuDNN 5.1 until TF 1.3 and then cuDNN 6.0 for TF 1.3 forward.  We will move to cuDNN 7.0 very soon for the default builds.  Closing.

**Comment by ellisdg** [comment]
I had this problem and figured out that it was due to a mismatch between CUDA and my anaconda environment. CUDA 8  was installed on the system, but the anaconda environment was using ```cudatookit: 7.5-0```.

Updating the ```cudatoolkit``` fixed the problem:
```
conda update cudatoolkit
```
