### ISSUE TITLE
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by ghostrickk** [tensorflow/models#2290]
Hi! I just installed Tensorflow GPU using anaconda. I use Windows 10 OS and Nvidia GTX1070 GPU. Help please? When I try to run this program:

import tensorflow as tf
hello = tf.constant('Hello, Tensorflow!')
sess = tf.Session()
print(sess.run(hello))

the following error messages appear:

runfile('D:/College/4th Year 3rd Term/Computer Vision/tensorflow test.py', wdir='D:/College/4th Year 3rd Term/Computer Vision')
Traceback (most recent call last):

  File "<ipython-input-1-c4bce082fc7d>", line 1, in <module>
    runfile('D:/College/4th Year 3rd Term/Computer Vision/tensorflow test.py', wdir='D:/College/4th Year 3rd Term/Computer Vision')

  File "C:\Users\ERDT\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Users\ERDT\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/College/4th Year 3rd Term/Computer Vision/tensorflow test.py", line 8, in <module>
    import tensorflow as tf

  File "C:\Users\ERDT\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *

  File "C:\Users\ERDT\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\ERDT\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\ERDT\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\ERDT\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ERDT\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ERDT\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ERDT\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\ERDT\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

**Comment by martinwicke** [comment]
Can you please fill out the issue template completely and open a new issue?
