### ISSUE TITLE
RuntimeError: Coordinator stopped with threads still running: Thread-25 in textsum module

### ISSUE THREAD

**Issue by rakashi** [tensorflow/models#2310]
Traceback (most recent call last):
  File "seq2seq_attention.py", line 216, in <module>
    tf.app.run()
  File "/home/sysadmin/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "seq2seq_attention.py", line 199, in main
    _Train(model, batcher)
  File "seq2seq_attention.py", line 117, in _Train
    sv.Stop()
  File "/home/sysadmin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/sysadmin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 397, in join
    " ".join(stragglers))
RuntimeError: Coordinator stopped with threads still running: Thread-25
[sysadmin@hnode3 textsum]$

**Comment by rakashi** [comment]
Hai, i just resolved this issue with just removing sv.stop() in your seq2seq_attention.py file and try it again it will work

**Comment by ashakodali** [comment]
Hi, I resolved this issue myself 
 In seq2seq_attention.py script remove sv.stop() line in code and rerun the code it will work

**Comment by michaelisard** [comment]
Great I will close now but let me know if there are more issues.
