### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: =

### ISSUE THREAD

**Issue by isharaux** [tensorflow/models#2334]
I am trying to convert trained_checkpoint to final frozen model from the export_inference_graph.py script provided in tensorflow/models,but the following error results.
```
$ sudo python3 object_detection/export_inference_graph.py  --input_type image_tensor  --pipeline_config_path = "ssd_inception_v2_pets.config"  --trained_checkpoint_prefix="object_detection/ssd_inception_v2_coco_11_06_2017/model.ckpt"  --output_directory="birds_inference_graph.pb"

Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 109, in <module>
    tf.app.run()
  File "/home/ishara/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/export_inference_graph.py", line 102, in main
    text_format.Merge(f.read(), pipeline_config)
  File "/home/ishara/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/ishara/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ishara/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: =
```
Operating System:
Ubuntu 16.04

**Comment by cy89** [comment]
Sorry for the slow response. Have you also tried posting on StackOverflow? There's a large community that listens and responds to questions there.

**Comment by coolKeen** [comment]
try this:
sudo python3 object_detection/export_inference_graph.py  --input_type image_tensor  --pipeline_config_path="ssd_inception_v2_pets.config"  --trained_checkpoint_prefix="object_detection/ssd_inception_v2_coco_11_06_2017/model.ckpt"  --output_directory="birds_inference_graph.pb"
Pay more attention that there should not be any space near '='!!!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) since it is not a bug or feature request. There is also a larger community that reads questions there.
