### ISSUE TITLE
When training SyntaxNet on a dataset: "Expected Identifier" error

### ISSUE THREAD

**Issue by vijayyak** [tensorflow/models#235]
## Please let us know which model this issue is about (specify the top-level directory)

**SyntaxNet**
I'm attempting to train SyntaxNet to dependency-parse a small subset of Universal Dependencies. Whenever I set my context.pbtxt to point to the correct files and run
`bazel-bin/syntaxnet/parser_trainer \
>   --task_context=syntaxnet/context.pbtxt \
>   --arg_prefix=brain_pos \
>   --compute_lexicon \
>   --graph_builder=greedy \
>   --training_corpus=training-corpus \
>   --tuning_corpus=tuning-corpus \
>   --output_path=models \
>   --batch_size=32 \
>   --decay_steps=3600 \
>   --hidden_layer_sizes=128 \
>   --learning_rate=0.08 \
>   --momentum=0.9 \
>   --seed=0 \
>   --params=128-0.08-3600-0.9-0`

I get the following error trace:
Traceback (most recent call last):
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 303, in <module>
    tf.app.run()
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/tf/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 263, in main
    RewriteContext()
  File "/home/ubuntu/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 98, in RewriteContext
    text_format.Merge(fin.read(), context)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 309, in Merge
    return MergeLines(text.split('\n'), message, allow_unknown_extension)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 346, in MergeLines
    _ParseOrMerge(lines, message, True, allow_unknown_extension)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 371, in _ParseOrMerge
    allow_unknown_extension)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 425, in _MergeField
    name = tokenizer.ConsumeIdentifier()
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 764, in ConsumeIdentifier
    raise self._ParseError('Expected identifier.')
google.protobuf.text_format.ParseError: 157:1 : Expected identifier.

please advise?

**Comment by JiaElse** [comment]
I am having the same problem here, spent hours looking at the source code already. How did you solve it?

**Comment by miraclecorp** [comment]
Ping!

**Comment by Hannes125** [comment]
I am also having that problem.. does someone know how to solve it?
