### ISSUE TITLE
Use my word_counts.txt to generate image captions.

### ISSUE THREAD

**Issue by j2233ack** [tensorflow/models#2362]
Use my word_counts.txt to generate image captions.

Here's my error code:
Traceback (most recent call last):
   File "/root/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 85, in <module>
     tf.app.run ()
   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
     _sys.exit (main (_sys.argv [: 1] + flags_passthrough))
   File "/root/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 55, in main
     vocab = vocabulary.Vocabulary (FLAGS.vocab_file)
   File "/root/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/vocabulary.py", line 49, in __init__
     reverse_vocab = [line.split () [0] for line in reverse_vocab]
IndexError: list index out of range

Can someone help me?

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
