### ISSUE TITLE
Error installing: AttributeError: module 'pandas' has no attribute 'computation'

### ISSUE THREAD

**Issue by js1972** [tensorflow/models#2378]
### System information
- **What is the top-level directory of the model you are using**: models/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Just following the installation instructions
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (provided in AWS Deep Learning AMI)
- **TensorFlow version (use command below)**: v1.2.0-0-g12f033d 1.2.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: `python object_detection/builders/model_builder_test.py`

### Describe the problem
There seems to be a bug in the installation process. I have followed the instructions [here](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md).
With the final step I run:
```
python object_detection/builders/model_builder_test.py
```
And it fails with error message: AttributeError: module 'pandas' has no attribute 'computation'.

I am applying this to the standard AWS Deep Learning AMI which has anaconda installed. I've used `source src/anaconda3/bin/activate root` to activate the Python 3.5 environment then followed the install instructions.
Could there be missing dependencies that are not listed in the installation instructions?

### Source code / logs
Full error stack trace:

```
(root) ubuntu@ip-172-31-37-243:~/models$ python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/ubuntu/models/object_detection/builders/model_builder.py", line 19, in <module>
    from object_detection.builders import box_predictor_builder
  File "/home/ubuntu/models/object_detection/builders/box_predictor_builder.py", line 18, in <module>
    from object_detection.core import box_predictor
  File "/home/ubuntu/models/object_detection/core/box_predictor.py", line 35, in <module>
    slim = tf.contrib.slim
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/home/ubuntu/src/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import factorization
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/ubuntu/src/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py", line 36, in <module>
    pd.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas' has no attribute 'computation'
```

**Comment by corcra** [comment]
Did you see this issue? https://github.com/tflearn/tflearn/issues/766

The solution there is to upgrade dask, `pip install dask --upgrade`

**Comment by js1972** [comment]
Thankyou @corcra - I also found that by building my own AWS instance instead of using the AWS provided deep learning AMI works perfectly well too.
