### ISSUE TITLE
Evaluate im2txt is giving error

### ISSUE THREAD

**Issue by rakashi** [tensorflow/models#2397]
Hi, I have trained image2text using MSCOCO dataset and I have got my model when i am trying to predict text my image its giving values like p= 0.00036 coming I didnt get is it probability if it is probability its very less how this value is coming 

And also When I am trying to evaluating my model its giving the following error

/home/lakshmi/anaconda3/bin/python /home/lakshmi/PycharmProjects/im2txt/evaluate.py
INFO:tensorflow:Prefetching values from 1 files matching /home/lakshmi/Output1
INFO:tensorflow:Starting evaluation at 2017-09-16-12:16:23
2017-09-16 12:16:23.362931: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-16 12:16:23.362978: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Loading model from checkpoint: /home/lakshmi/trainoutput/model.ckpt-50001
INFO:tensorflow:Restoring parameters from /home/lakshmi/trainoutput/model.ckpt-50001
INFO:tensorflow:Successfully loaded model.ckpt-50001 at global step = 50001.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.FailedPreconditionError'>, /home/lakshmi/Output1
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, filename_queue)]]
ERROR:tensorflow:Evaluation failed.
Traceback (most recent call last):
  File "/home/lakshmi/PycharmProjects/im2txt/evaluate.py", line 197, in <module>
    tf.app.run()
  File "/home/lakshmi/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/lakshmi/PycharmProjects/im2txt/evaluate.py", line 193, in main
    run()
  File "/home/lakshmi/PycharmProjects/im2txt/evaluate.py", line 183, in run
    run_once(model, saver, summary_writer, summary_op)
  File "/home/lakshmi/PycharmProjects/im2txt/evaluate.py", line 150, in run_once
    coord.join(threads, stop_grace_period_secs=10)
  File "/home/lakshmi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/lakshmi/anaconda3/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/lakshmi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/home/lakshmi/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/home/lakshmi/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/lakshmi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /home/lakshmi/Output1
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, filename_queue)]]

Process finished with exit code 1

Can any one help me How can I resolve it

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
