### ISSUE TITLE
object_detection model import error

### ISSUE THREAD

**Issue by kamixueti** [tensorflow/models#2457]
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    from object_detection import trainer
  File "..\object_detection\trainer.py", line 33, in <module>
    from deployment import model_deploy
ModuleNotFoundError: No module named 'deployment'

this deployment Is the slim.deployment?

**Comment by kamixueti** [comment]
I know how what.
I forget the export PYTHONPATH

# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
