### ISSUE TITLE
NewRandomAccessFile

### ISSUE THREAD

**Issue by Mauajama** [tensorflow/models#2497]
Traceback (most recent call last):

  File "<ipython-input-1-0fe5deb5982c>", line 1, in <module>
    runfile('C:/Users/mauajama.firdaus/run_rnn_joint.py', wdir='C:/Users/mauajama.firdaus')

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/mauajama.firdaus/run_rnn_joint.py", line 484, in <module>
    tf.app.run()

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))

  File "C:/Users/mauajama.firdaus/run_rnn_joint.py", line 481, in main
    train()

  File "C:/Users/mauajama.firdaus/run_rnn_joint.py", line 224, in train
    FLAGS.data_dir, FLAGS.in_vocab_size, FLAGS.out_vocab_size)

  File "C:\Users\mauajama.firdaus\data_utils.py", line 145, in prepare_multi_task_data
    tokenizer=naive_tokenizer)

  File "C:\Users\mauajama.firdaus\data_utils.py", line 50, in create_vocabulary
    for line in f:

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 213, in __next__
    return self.next()

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 207, in next
    retval = self.readline()

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 176, in readline
    self._preread_check()

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)

  File "C:\Users\mauajama.firdaus\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))

NotFoundError: NewRandomAccessFile failed to Create/Open: C:/Users/mauajama.firdaus/data/ATIS_samples/train/train.seq.in : The system cannot find the file specified.

**Comment by cy89** [comment]
You've just given us a traceback. Could you please explain what you were trying to do to cause the bug? 


Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by wt-huang** [comment]
Closing this issue due to inactivity, feel free to reopen if this is still an issue.
