### ISSUE TITLE
Syntaxnet: tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value training/softmax_bias/Momentum/init

### ISSUE THREAD

**Issue by PeterBourgonje** [tensorflow/models#252]
Using syntaxtnet, I'm trying to train my own tagger on the German section of Universal Dependencies (downloaded from here: http://universaldependencies.org/).
I've put the German de-ud-[test|train|dev].conllu in my context.pbtxt file and after getting a complaint about the mapping to multiple coarse POS tags and using the script uploaded by @prakhar21 (https://github.com/tensorflow/models/issues/215) to modify my dev/train/test files,  I follow the docs and try:

`sudo bazel-bin/syntaxnet/parser_trainer --task_context=syntaxnet/context.pbtxt --arg_prefix=brain_pos --compute_lexicon --graph_builder=greedy --training_corpus=training-corpus --tuning+corpus=tuning=corpus --output_path=models --batch_size=32 --decay_steps=3600 --hidden_layer_sizes=128 --learning_rate=0.08 --momentum=0.9 --seed=0 --params=128-0.08-3600-0.9-0
`
and get:

```
INFO:tensorflow:Computing lexicon...
I syntaxnet/lexicon_builder.cc:124] Term maps collected over 269626 tokens from 14118 documents
I syntaxnet/term_frequency_map.cc:137] Saved 47976 terms to models/brain_pos/greedy/128-0.08-3600-0.9-0/word-map.
I syntaxnet/term_frequency_map.cc:137] Saved 46263 terms to models/brain_pos/greedy/128-0.08-3600-0.9-0/lcword-map.
I syntaxnet/term_frequency_map.cc:137] Saved 0 terms to models/brain_pos/greedy/128-0.08-3600-0.9-0/tag-map.
I syntaxnet/term_frequency_map.cc:137] Saved 0 terms to models/brain_pos/greedy/128-0.08-3600-0.9-0/category-map.
I syntaxnet/term_frequency_map.cc:137] Saved 33 terms to models/brain_pos/greedy/128-0.08-3600-0.9-0/label-map.
I syntaxnet/term_frequency_map.cc:101] Loaded 33 terms from models/brain_pos/greedy/128-0.08-3600-0.9-0/label-map.
I syntaxnet/embedding_feature_extractor.cc:35] Features: stack(3).word stack(2).word stack(1).word stack.word input.word input(1).word input(2).word input(3).word;input.digit input.hyphen;stack.suffix(length=2) input.suffix(length=2) input(1).suffix(length=2);stack.prefix(length=2) input.prefix(length=2) input(1).prefix(length=2)
I syntaxnet/embedding_feature_extractor.cc:36] Embedding names: words;other;suffix;prefix
I syntaxnet/embedding_feature_extractor.cc:37] Embedding dims: 64;4;8;8
I syntaxnet/term_frequency_map.cc:101] Loaded 47976 terms from models/brain_pos/greedy/128-0.08-3600-0.9-0/word-map.
I syntaxnet/term_frequency_map.cc:101] Loaded 0 terms from models/brain_pos/greedy/128-0.08-3600-0.9-0/tag-map.
INFO:tensorflow:Training...
INFO:tensorflow:Building training network with parameters: feature_sizes: [8 2 3 3] domain_sizes: [47979     5  6018  7543]
INFO:tensorflow:Initializing...
Traceback (most recent call last):
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 306, in <module>
    tf.app.run()
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/tf/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 302, in main
    Train(sess, num_actions, feature_sizes, domain_sizes, embedding_dims)
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 231, in Train
    sess.run(parser.inits.values())
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/tf/tensorflow/python/client/session.py", line 333, in run
    run_metadata_ptr)
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/tf/tensorflow/python/client/session.py", line 573, in _run
    feed_dict_string, options, run_metadata)
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/tf/tensorflow/python/client/session.py", line 653, in _do_run
    target_list, options, run_metadata)
  File "/home/peter/ParseyMcParsefaceAndTheUniversalDependencies/secondInstall/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/tf/tensorflow/python/client/session.py", line 674, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value training/softmax_bias/Momentum/init
	 [[Node: _send_training/softmax_bias/Momentum/init_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=4121792675886808083, tensor_name="training/softmax_bias/Momentum/init:0", _device="/job:localhost/replica:0/task:0/cpu:0"](training/softmax_bias/Momentum/init)]]
```

I do get it working for other languages (e.g. Dutch), after also using this conversion script.
Is this an issue with tensorflow/syntaxnet, or with the universal dependencies?

**Comment by calberti** [comment]
An empty tag map seems suspicious: **Loaded 0 terms from models/brain_pos/greedy/128-0.08-3600-0.9-0/tag-map.**

Instead of running the preprocessing script on the dataset, can you add
```
Parameter {
  name: "join_category_to_pos"
  value: "true"
}
```
to you context file?  That should let training run smoothly on UD datasets.
