### ISSUE TITLE
cnn tutorial running problem

### ISSUE THREAD

**Issue by hunk3749** [tensorflow/models#2551]
Traceback (most recent call last):
  File "/home/dhanpal/Desktop/cifar10_train.py", line 10, in <module>
    import cifar10
  File "/home/dhanpal/Desktop/cifar10.py", line 350, in <module>
    if not os.path.exists(extracted_dir_path):
NameError: name 'extracted_dir_path' is not defined
>>>

**Comment by drpngx** [comment]
Can you point to the source you are using? How are you starting it?
