### ISSUE TITLE
export inference error deploying model on google cloud platform

### ISSUE THREAD

**Issue by sainttelant** [tensorflow/models#2573]
sudo python3 object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path object_detection/samples/configs/faster_rcnn_resnet101_pets.config --trained_checkpoint_prefix model.ckpt-200003 --output_directory output_inference_graph.pb

Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 71, in <module>
    from object_detection import exporter
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/exporter.py", line 28, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/builders/model_builder.py", line 30, in <module>
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/models/faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
ImportError: No module named 'nets'

it is weird， i exported inference graph, it displayed like above, note, i 've already trained the model on GCP, and of course, i 've already added the pythonpath, and python setup.py build and install successfully, why did i encounter such issue after i trained the model?   plz tell me why i will appreciate so much

**Comment by sainttelant** [comment]
any solusions? plz help

**Comment by derekjchow** [comment]
Could you check your PYTHONPATH variable again? It seems slim/ was not added on the shell you ran the exporter command from.

Additionally, you shouldn't need to run as root (and it's quite possible root will run with a different PYTHONPATH than your normal user.)
