### ISSUE TITLE
SyntaxNet test failures

### ISSUE THREAD

**Issue by huguesb** [tensorflow/models#2589]
### System information
- **What is the top-level directory of the model you are using**: `models/research/syntaxnet`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no custom code, just trying to build SyntaxNet
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 (docker container on OSX)
- **TensorFlow installed from (source or binary)**: compiled from source as part of the SyntaxNet build process
- **TensorFlow version (use command below)**: git commit `90267567` (which is the commit that the remote points to inside this repo at commit `538f89c4`)
- **Bazel version (if compiling from source)**: 0.7.0
- **CUDA/cuDNN version**: N/A GPU support disabled
- **GPU model and memory**: N/A GPU support disabled
- **Exact command to reproduce**: `bazel test ...` (after following the instructions at https://github.com/tensorflow/models/tree/master/research/syntaxnet )

### Describe the problem

22 tests are failing, specifically:

```
INFO: Elapsed time: 12.593s, Critical Path: 1.07s
//dragnn/components/stateless:stateless_component_test          (cached) PASSED in 0.1s
//dragnn/components/syntaxnet:syntaxnet_component_test          (cached) PASSED in 0.2s
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test (cached) PASSED in 0.1s
//dragnn/components/syntaxnet:syntaxnet_transition_state_test   (cached) PASSED in 0.1s
//dragnn/core:beam_test                                         (cached) PASSED in 0.1s
//dragnn/core:compute_session_impl_test                         (cached) PASSED in 0.1s
//dragnn/core:compute_session_pool_test                         (cached) PASSED in 0.1s
//dragnn/core:dragnn_bulk_op_kernels_test                       (cached) PASSED in 0.1s
//dragnn/core:dragnn_op_kernels_test                            (cached) PASSED in 0.1s
//dragnn/core:index_translator_test                             (cached) PASSED in 0.1s
//dragnn/core:input_batch_cache_test                            (cached) PASSED in 0.1s
//dragnn/core:resource_container_test                           (cached) PASSED in 0.1s
//dragnn/io:sentence_input_batch_test                           (cached) PASSED in 0.1s
//syntaxnet:arc_standard_transitions_test                       (cached) PASSED in 0.2s
//syntaxnet:binary_segment_state_test                           (cached) PASSED in 0.1s
//syntaxnet:binary_segment_transitions_test                     (cached) PASSED in 0.1s
//syntaxnet:char_ngram_string_extractor_test                    (cached) PASSED in 0.1s
//syntaxnet:char_properties_test                                (cached) PASSED in 0.1s
//syntaxnet:char_shift_transitions_test                         (cached) PASSED in 0.1s
//syntaxnet:head_transitions_test                               (cached) PASSED in 0.1s
//syntaxnet:label_transitions_test                              (cached) PASSED in 0.1s
//syntaxnet:morphology_label_set_test                           (cached) PASSED in 0.1s
//syntaxnet:once_transitions_test                               (cached) PASSED in 0.1s
//syntaxnet:parser_features_test                                (cached) PASSED in 0.1s
//syntaxnet:segmenter_utils_test                                (cached) PASSED in 0.1s
//syntaxnet:sentence_features_test                              (cached) PASSED in 0.1s
//syntaxnet:shared_store_test                                   (cached) PASSED in 0.1s
//syntaxnet:tagger_transitions_test                             (cached) PASSED in 0.1s
//syntaxnet:whole_sentence_features_test                        (cached) PASSED in 0.2s
//util/utf8:unicodetext_unittest                                (cached) PASSED in 0.1s
//dragnn/python:bulk_component_test                                      FAILED in 1.1s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log
//dragnn/python:composite_optimizer_test                                 FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/composite_optimizer_test/test.log
//dragnn/python:digraph_ops_test                                         FAILED in 1.1s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/digraph_ops_test/test.log
//dragnn/python:evaluation_test                                          FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/evaluation_test/test.log
//dragnn/python:graph_builder_test                                       FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log
//dragnn/python:lexicon_test                                             FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log
//dragnn/python:network_units_test                                       FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/network_units_test/test.log
//dragnn/python:render_parse_tree_graphviz_test                          FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log
//dragnn/python:render_spec_with_graphviz_test                           FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_spec_with_graphviz_test/test.log
//dragnn/python:sentence_io_test                                         FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/sentence_io_test/test.log
//dragnn/python:spec_builder_test                                        FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/spec_builder_test/test.log
//dragnn/python:visualization_test                                       FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/visualization_test/test.log
//dragnn/tools:model_trainer_test                                        FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/tools/model_trainer_test/test.log
//examples/dragnn:test_run_all_tutorials                                 FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log
//syntaxnet:beam_reader_ops_test                                         FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log
//syntaxnet/util:check_test                                              FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/check_test/test.log
//syntaxnet/util:registry_test                                           FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/registry_test/test.log
```

Most of the test errors seem to have the same root cause:
```
root@0ae10c4a8cb7:/models/research/syntaxnet# cat /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/lexicon_builder_test.runfiles/__main__/syntaxnet/lexicon_builder_test.py", line 22, in <module>
    import tensorflow as tf
  File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/lexicon_builder_test.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/lexicon_builder_test.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/lexicon_builder_test.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 102, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/lexicon_builder_test.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 30, in <module>
    from tensorflow.python.framework import function
  File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/lexicon_builder_test.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 38, in <module>
    from tensorflow.python.ops import variable_scope as vs
  File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/lexicon_builder_test.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 192, in <module>
    """
AttributeError: 'int' object attribute '__doc__' is read-only
```

**Comment by huguesb** [comment]
It seem I was affected by tensorflow/tensorflow#12491

After applying the solution mentioned there, namely `pip uninstall enum && apt-get python-enum34`, I am down to 14 failing tests, which again seem to have a common root cause:

```
cat /root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/tools/model_trainer_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
2017-10-25 23:11:11.840113: F external/org_tensorflow/tensorflow/core/framework/variant_op_registry.cc:104] Check failed: existing == nullptr (0x26352c8 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered
```

**Comment by SaintNazaire** [comment]
Same here, issue #2677

**Comment by SaintNazaire** [comment]
Confirmed dup of issue #2355.
