### ISSUE TITLE
cognitive_mapping_and_planning run script_test_pretrained_models.sh .show KeyError: 'normalizer_params'

### ISSUE THREAD

**Issue by mapleluo** [tensorflow/models#2602]
Pass is_training directly to the network instead of the arg_scope.
Traceback (most recent call last):
  File "/home/luo/models-master/research/cognitive_mapping_and_planning/scripts/script_nav_agent_release.py", line 255, in <module>
    app.run()
  File "/home/luo/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/luo/models-master/research/cognitive_mapping_and_planning/scripts/script_nav_agent_release.py", line 91, in main
    _launcher(FLAGS.config_name, FLAGS.logdir)
  File "/home/luo/models-master/research/cognitive_mapping_and_planning/scripts/script_nav_agent_release.py", line 102, in _launcher
    _test(args)
  File "/home/luo/models-master/research/cognitive_mapping_and_planning/scripts/script_nav_agent_release.py", line 197, in _test
    summary_mode=args.control.test_mode)
  File "/home/luo/models-master/research/cognitive_mapping_and_planning/tfcode/cmp.py", line 388, in setup_to_run
    wt_decay=args.solver.wt_decay, stride=args.arch.fr_stride)
  File "/home/luo/models-master/research/cognitive_mapping_and_planning/tfcode/cmp_utils.py", line 149, in fr_v2
    arg_sc.values()[i]['normalizer_params']['updates_collections'] = updates_collections
KeyError: 'normalizer_params'

but how to sovle it？

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by wangchangquan** [comment]
@mapleluo  have you solve the problem? can you tell the method to solve it.
