### ISSUE TITLE
Import context ImportError: No module named eager

### ISSUE THREAD

**Issue by temiklis** [tensorflow/models#2658]
How to fix this?

```
The replica ps 1 exited with a non-zero status of 1. Termination reason: Error. 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 49, in <module>
    from object_detection import trainer
  File "/root/.local/lib/python2.7/site-packages/object_detection/trainer.py", line 33, in <module>
    from deployment import model_deploy
  File "/root/.local/lib/python2.7/site-packages/deployment/model_deploy.py", line 106, in <module>
    from tensorflow.python.eager import context
ImportError: No module named eager

The replica ps 2 exited with a non-zero status of 1. Termination reason: Error. 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 49, in <module>
    from object_detection import trainer
  File "/root/.local/lib/python2.7/site-packages/object_detection/trainer.py", line 33, in <module>
    from deployment import model_deploy
  File "/root/.local/lib/python2.7/site-packages/deployment/model_deploy.py", line 106, in <module>
    from tensorflow.python.eager import context
ImportError: No module named eager

To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=837058927346&resource=ml_job%2Fjob_id%2Fprice2&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22price2%22"   
```

**Comment by jart** [comment]
Are your models and tensorflow repositories both synced to head? Eager functionality is very new.

**Comment by lyltencent** [comment]
Hi, I am facing the same issue, has anyone solved this?

**Comment by jart** [comment]
@lyltencent Are you synced to head?

**Comment by temiklis** [comment]
@jart I did the example for Google cloud. How can I do this? If I start training on the local machine then everything is fine, no such errors.

**Comment by jart** [comment]
I'm not familiar with Google Cloud Datalab but if you're obtaining TensorFlow through them, then you might be able to obtain better support through them.

**Comment by lyltencent** [comment]
@jart , Hi I have note solved the problem. Did you mean the tensorflow version? Could you let me know what version of tensorflow are your using? I am using 1.1.0. 
Thanks,.

**Comment by bignamehyp** [comment]
The latest tf version is 1.4. You can simply run pip install tf-nightly or pip install tf-nightly-gpu. And please contact Google cloud support if you are obtaining tensorflow through them.

**Comment by valerie-chen** [comment]
jic anyone is still running into this issue: `pip install tf-nightly` worked for me
