### ISSUE TITLE
Object Detection: Error while running faster_rcnn_nas_coco

### ISSUE THREAD

**Issue by MayankSingal** [tensorflow/models#2751]
On running the following command:

` python object_detection/train.py --logtostderr --pipeline_config_path=object_detection/samples/configs/faster_rcnn_nas_coco.config --train_dir=/data/nasnet_OD/
`
I get the following error:
`File "object_detection/train.py", line 163, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/data/tf_models/models/research/object_detection/trainer.py", line 332, in train
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 782, in train
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 800, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,1] vs. shape[2] = [1,0]
	 [[Node: concat = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ExpandDims, ExpandDims_1, ExpandDims_2, ExpandDims_3, ExpandDims/dim)]]
`
Can anyone let me know of the reason why this is happening?

I am training this on a custom dataset which has only one class. So I have put num_classes: 1 in the config file.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by mateuszbuda** [comment]
@MayankSingal Did you post this question on SO or maybe resolved it eventually?
I face the same issue using `faster_rcnn_resnet50_coco.config` on a custom dataset with 2 classes and only one class present in each image.
I tried with tensorflow 1.4 and 1.5.
The only difference was that TF 1.5 run longer before this exception happened (~4k iterations on 1.4 vs ~25k iterations of 1.5).

<details>
  <summary>Error log</summary>

```
2018-02-27 02:53:28.024956: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,3] vs. shape[2] = [1,2]
         [[Node: concat = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32](ExpandDims, ExpandDims_1, ExpandDims_2, ExpandDims_3, concat/axis)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, ConcatOp : Dimensions of inputs should match: shape[0] = [1,3] vs. shape[2] = [1,2]
         [[Node: concat = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32](ExpandDims, ExpandDims_1, ExpandDims_2, ExpandDims_3, concat/axis)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
INFO:tensorflow:global step 26375: loss = 0.1705 (0.249 sec/step)
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 164, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/maciej/models/research/object_detection/trainer.py", line 359, in train
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 782, in train
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 826, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 387, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1251, in _single_operation_run
    self._session, None, {}, [], target_list, status, None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,3] vs. shape[2] = [1,2]
         [[Node: concat = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32](ExpandDims, ExpandDims_1, ExpandDims_2, ExpandDims_3, concat/axis)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?,?,3], [], [], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
```

</details>

**Comment by shantianyang** [comment]
Hi, "InvalidArgumentError: ConcatOp : Dimensions of inputs should match" , I meet the same problem, Did you have some solutions?  thanks!!!

**Comment by mateuszbuda** [comment]
I'll dare to suggest a hypothesis that increasing the `first_stage_max_proposals`, `max_detections_per_class`, and `max_total_detections` might help.

**Comment by shantianyang** [comment]
Hi, @mateuszbuda , i meet this problem in a model with cnn+lstm, if there is only the cnn layers, it can be work well, when feed output of cnn to the lstm, and then fc, it still can be work, But only 5th, it pops up ':Demension ...ConcatOp'  problem. I change the hyper paramters ,but still the same problem.
