### ISSUE TITLE
script_test_pretrained_model.sh

### ISSUE THREAD

**Issue by siavash-khodadadeh** [tensorflow/models#2816]
It seems that there is a bug when I run this command. It says that
scale cannot be an integer: False

ERROR:root:Checkpoint_dir: output/bl.v2.noclip.sbpd_d_r2r_h0_64_80
Traceback (most recent call last):
  File "scripts/script_nav_agent_release.py", line 253, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "scripts/script_nav_agent_release.py", line 89, in main
    _launcher(FLAGS.config_name, FLAGS.logdir)
  File "scripts/script_nav_agent_release.py", line 100, in _launcher
    _test(args)
  File "scripts/script_nav_agent_release.py", line 195, in _test
    summary_mode=args.control.test_mode)
  File "/~/programming/models/research/cognitive_mapping_and_planning/tfcode/vision_baseline_lstm.py", line 260, in setup_to_run
    is_training)
  File "/~/programming/models/research/cognitive_mapping_and_planning/tfcode/nav_utils.py", line 101, in get_repr_from_image
    with slim.arg_scope(resnet_v2.resnet_utils.resnet_arg_scope(resnet_is_training)):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 257, in resnet_arg_scope
    weights_regularizer=regularizers.l2_regularizer(weight_decay),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/regularizers.py", line 92, in l2_regularizer
    raise ValueError('scale cannot be an integer: %s' % (scale,))

This is my error log

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by wangchangquan** [comment]
have you slove the problem？ i meet the same ,can you tell me how to solve ti.
