### ISSUE TITLE
Error from "python object_detection/builders/model_builder_test.py" command.

### ISSUE THREAD

**Issue by flipflop98** [tensorflow/models#2830]
I have following error while doing the installation final step. 
I'm using tensorflow (1.4), cuda (8.0), cudnn (6.0), matplotlib (2.1.0) under anaconda virtual environment.

----------------------------------------------------------------------------------------------------------------------------
(tensorflow) chkim@chkim-PMTSB09D-Samsung-DeskTop:~/다운로드/models-master/research$ python object_detection/builders/model_builder_test.py

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/chkim/다운로드/models-master/research/object_detection/builders/model_builder.py", line 29, in <module>
    from object_detection.meta_architectures import ssd_meta_arch
  File "/home/chkim/다운로드/models-master/research/object_detection/meta_architectures/ssd_meta_arch.py", line 31, in <module>
    from object_detection.utils import visualization_utils
  File "/home/chkim/다운로드/models-master/research/object_detection/utils/visualization_utils.py", line 24, in <module>
    import matplotlib.pyplot as plt
  File "/home/chkim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/pyplot.py", line 69, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/chkim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()
  File "/home/chkim/anaconda2/envs/tensorflow/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 16, in <genexpr>
    if not line.startswith('  File "<frozen importlib._bootstrap'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 20: ordinal not in range(128)
-------------------------------------------------------------------------------------------------------------------------

**Comment by aselle** [comment]
@flipflop98, this looks like a python 3 incompatibilityl. You can work around this  by using python 2 
@derekjchow, could you look into supporting python 3 properly?

**Comment by chrza** [comment]
Pls take a look at the infer_detections.py script also when fixing python 3 issues as I mentioned in #2892 
my workaround was setting up an ubuntu env with python 2.7

**Comment by MartinSnow** [comment]
I got the same error information. Have you fixed it?

**Comment by yar31313** [comment]
파일 경로에 한글 들어가있어서 그런거같네요.
'다운로드'를 'downloads' 같은 걸로 바꾸고 경로설정 바꾸고 실행해보세요.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
