### ISSUE TITLE
random_pad_image throwing a "type int32 that does not match type float32" error

### ISSUE THREAD

**Issue by tyleretchart** [tensorflow/models#2841]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8, cuDNN 6
- **GPU model and memory**: 1080Ti 11 GB
- **Exact command to reproduce**:

### Describe the problem
When I add

```
data_augmentation_options {
    random_pad_image {
        min_image_height: 812.0
        min_image_width: 812.0
        max_image_height: 870.0
        max_image_width: 898.0
    }
}
```

in the train_config section of my pipeline config, and then run train.py, I get the following error:

```
Traceback (most recent call last):
  File "../env/lib/python3.5/site-packages/object_detection/train.py", line 163, in <module>
    tf.app.run()
  File "/home/tyler/env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "../env/lib/python3.5/site-packages/object_detection/train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/tyler/env/lib/python3.5/site-packages/object_detection/trainer.py", line 217, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/tyler/env/lib/python3.5/site-packages/object_detection/trainer.py", line 77, in create_input_queue
    include_keypoints=include_keypoints))
  File "/home/tyler/env/lib/python3.5/site-packages/object_detection/core/preprocessor.py", line 2547, in preprocess
    results = func(*args, **params)
  File "/home/tyler/env/lib/python3.5/site-packages/object_detection/core/preprocessor.py", line 1131, in random_pad_image
    tf.stack([image_height, image_width]))
  File "/home/tyler/env/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2522, in maximum
    "Maximum", x=x, y=y, name=name)
  File "/home/tyler/env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Maximum' Op has type int32 that does not match type float32 of argument 'x'.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Scale of 0 disables regularizer.
Traceback (most recent call last):
  File "../env/lib/python3.5/site-packages/object_detection/eval.py", line 130, in <module>
    tf.app.run()
  File "/home/tyler/env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "../env/lib/python3.5/site-packages/object_detection/eval.py", line 126, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/tyler/env/lib/python3.5/site-packages/object_detection/evaluator.py", line 210, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/home/tyler/env/lib/python3.5/site-packages/object_detection/eval_util.py", line 393, in repeated_checkpoint_run
    return metrics
UnboundLocalError: local variable 'metrics' referenced before assignment
```

I think the issue is in the line:

```
TypeError: Input 'y' of 'Maximum' Op has type int32 that does not match type float32 of argument 'x'.
```

The proto forces the parameters min_image_height, min_image_width, max_image_height, and max_image_width to be floats, so I can't change those to ints.

It appears that this issue does not show up if I don't specify any parameters, such as:

```
data_augmentation_options {
    random_pad_image {
    }
 }
```

### Source code / logs
This is the config that I used:

```
model {
  faster_rcnn {
    num_classes: 1
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 812
        max_dimension: 812
      }
    }
    feature_extractor {
      type: "faster_rcnn_resnet101"
      first_stage_features_stride: 16
    }
    first_stage_anchor_generator {
      grid_anchor_generator {
        height_stride: 4
        width_stride: 4
        scales: 0.03125
        scales: 0.0625
        scales: 0.125
        scales: 0.25
        scales: 0.5
        scales: 1.0
        scales: 2.0
        scales: 4.0
        aspect_ratios: 0.5
        aspect_ratios: 1.0
        aspect_ratios: 2.0
      }
    }
    first_stage_box_predictor_conv_hyperparams {
      op: CONV
      regularizer {
        l2_regularizer {
          weight: 0.0
        }
      }
      initializer {
        truncated_normal_initializer {
          stddev: 0.009999999776482582
        }
      }
    }
    first_stage_nms_score_threshold: 0.0
    first_stage_nms_iou_threshold: 0.699999988079071
    first_stage_max_proposals: 300
    first_stage_localization_loss_weight: 2.0
    first_stage_objectness_loss_weight: 1.0
    initial_crop_size: 14
    maxpool_kernel_size: 2
    maxpool_stride: 2
    second_stage_box_predictor {
      mask_rcnn_box_predictor {
        fc_hyperparams {
          op: FC
          regularizer {
            l2_regularizer {
              weight: 0.0
            }
          }
          initializer {
            variance_scaling_initializer {
              factor: 1.0
              uniform: true
              mode: FAN_AVG
            }
          }
        }
        use_dropout: false
        dropout_keep_probability: 1.0
      }
    }
    second_stage_post_processing {
      batch_non_max_suppression {
        score_threshold: 0.0
        iou_threshold: 0.6000000238418579
        max_detections_per_class: 300
        max_total_detections: 300
      }
      score_converter: SOFTMAX
    }
    second_stage_localization_loss_weight: 2.0
    second_stage_classification_loss_weight: 1.0
  }
}
train_config {
  batch_size: 2
  data_augmentation_options {
    normalize_image {
      original_minval: 0.0
      original_maxval: 255.0
      target_minval: 0.0
      target_maxval: 1.0
    }
  }
  data_augmentation_options {
    random_pad_image {
      min_image_height: 812.0
      min_image_width: 812.0
      max_image_height: 870.0
      max_image_width: 898.0

    }
  }
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    random_vertical_flip {
    }
  }
  data_augmentation_options {
    random_rotation90 {
    }
  }
  data_augmentation_options {
    normalize_image {
      original_minval: 0.0
      original_maxval: 1.0
      target_minval: 0.0
      target_maxval: 255.0
    }
  }
  optimizer {
    momentum_optimizer {
      learning_rate {
        constant_learning_rate {
          learning_rate: 0.0015249886782839894
        }
      }
      momentum_optimizer_value: 0.8637624382972717
    }
    use_moving_average: false
    moving_average_decay: 0.9997233748435974
  }
  gradient_clipping_by_norm: 10.0
  fine_tune_checkpoint: "../faster_rcnn_resnet101_coco_11_06_2017/model.ckpt"
  from_detection_checkpoint: true
  num_steps: 124
}
train_input_reader {
  label_map_path: "liod_datasets/DETAILED_label_map.pbtxt"
  queue_capacity: 110
  min_after_dequeue: 100
  num_readers: 8
  tf_record_input_reader {
    input_path: "liod_datasets/DETAILED_TRAINING_unbalanced.record"
  }
}
eval_config {
  num_visualizations: 1206
  num_examples: 1206
  max_evals: 1
}
eval_input_reader {
  label_map_path: "liod_datasets/DETAILED_label_map.pbtxt"
  shuffle: false
  queue_capacity: 1
  min_after_dequeue: 0
  num_epochs: 1
  num_readers: 1
  tf_record_input_reader {
    input_path: "liod_datasets/DETAILED_VALIDATION.record"
  }
}
```

And the command I used to run it:

```
../env/lib/python3.5/site-packages/object_detection/train.py --logtostderr --pipeline_config_path=./pipeline_train.config --train_dir=./pipeline_train --num_clones=2
```

**Comment by tatatodd** [comment]
@jch1 @tombstone can you comment on this?

**Comment by kingstarcraft** [comment]
@tyleretchart 
I have met the same problem, have you solved this problem?

**Comment by randolfo75** [comment]
Same problem here

**Comment by ira7bar** [comment]
This can be solved by replacing lines 1444-1452 with:
  if max_image_size is None:
    max_image_size = tf.stack([image_height * 2, image_width * 2])
  max_image_size = tf.maximum(tf.cast(max_image_size, tf.int32),
                              tf.stack([image_height, image_width]))

  if min_image_size is None:
    min_image_size = tf.stack([image_height, image_width])
  min_image_size = tf.maximum(tf.cast(min_image_size, tf.int32),
                              tf.stack([image_height, image_width]))

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
