### ISSUE TITLE
Hello, multiple issues (no bounding boxes, can't run eval and train at the same time, and trouble using checkpoints

### ISSUE THREAD

**Issue by Jreyno40** [tensorflow/models#2850]
Hello! Here to mention some issues I'm having, as it seems they may not be my fault (but happy to be corrected if they are). I've asked a stackoverflow question here but received no responses.: https://stackoverflow.com/questions/47384021/no-bounding-boxes-showing-up 

I'm running tensorflow on a windows 10 system, and I don't have any custom code, but rather a novel dataset. I have a GTX 1070. I am running tensorflow 1.3.0 (is this a problem?). 

In summary:

    I have tried several of the sample pipeline config files, but most don't generate a bounding box for me. inception_v2_pet.config does generate bounding boxes on epoch 0, but for future checkpoints it does not. 

    Further, I'm getting some of the NVIDIA issues mentioned in previously raised issues for this repo. I get the CUDANN crash messages when attempting to run train.py and eval.py at the same time.

Now, when trying to load from a ckpt for ssd_mobilenet_v1_coco_2017_11_17.ckpt, with ssd_mobilenet_v1_coco.config I get the following message:

```
Traceback (most recent call last):
  File "object_detection/train.py", line 163, in <module>
    tf.app.run()
  File "C:\Users\mccla\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\trainer.py", line 193, in train
    detection_model = create_model_fn()
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\builders\model_builder.py", line 83, in build
    return _build_ssd_model(model_config.ssd, is_training)
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\builders\model_builder.py", line 139, in _build_ssd_model
    is_training)
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\builders\model_builder.py", line 107, in _build_ssd_feature_extractor
    pad_to_multiple = feature_extractor_config.pad_to_multiple
AttributeError: 'SsdFeatureExtractor' object has no attribute 'pad_to_multiple'
```

**Comment by Jreyno40** [comment]
I've updated Tensorflow and pulled the latest model repo, but nothing is fixing my issue.
