### ISSUE TITLE
After quantize the ssd_mobilenet_v1_android_export.pb, Tensorflow Android can not load it 

### ISSUE THREAD

**Issue by offbye** [tensorflow/models#2853]
I have tried the below  commands  to compress sdd-mobilenet_v1 model.
```shell
  bazel-bin/tensorflow/tools/quantization/quantize_graph --
input=/data5/zxt/model/ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb 
 --output_node_names=detection_boxes,detection_scores,detection_classes,num_detections
 --print_nodes --output=/tmp/ssd.pb  --mode=weights --logtostderr
```

When load the quantized model on android demo， I met errors. 
Is there anyone who can help ? 
thanks. 
 

```shell
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
    Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Greater). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
   at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:535)
   at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>

```

**Comment by mpeniak** [comment]
I'd be interested to know this too. BTW, did you look into using TF Lite for object detection using ssd_mobilenet? I am currently looking into this as it should result in significant speedup if supported.

**Comment by offbye** [comment]
I have tried  Tflite on  some models , bu I find only mobilenet model can be converted to  .lite format. 
Many operators can not be supported now.

**Comment by tatatodd** [comment]
The error indicates a graph serialization mismatch:
```
Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.
```

What do you mean when you say you "load the quantized model on android demo"?  I'm suspecting that there's a mismatch between the version of the code that the android demo is using, vs. the code that built the GraphDef.

**Comment by tatatodd** [comment]
Looks like you duplicated this question in the tensorflow/tensorflow repository as: https://github.com/tensorflow/tensorflow/issues/14777

Please don't ask the same question in multiple repositories.  It's unfriendly, and wastes our time and resources.

Closing this out; please follow-up on the other issue.
