### ISSUE TITLE
Some training problems in im2txt

### ISSUE THREAD

**Issue by j2233ack** [tensorflow/models#2869]
I try to use different data sets in im2txt and the files to be processed are also executed

I use the CPU and also call batch_size = 16
I find the relevant issues on the stackoverflow, but basically I do not know where to start this error.
So who can give me a hint or teaching?

This error is what I got while training:

hsu@ubuntu:~/models-master/research/im2txt$ MSCOCO_DIR="/home/hsu/models-master/research/im2txt/im2txt/data/mscoco"
hsu@ubuntu:~/models-master/research/im2txt$ INCEPTION_CHECKPOINT="/home/hsu/models-master/research/im2txt/im2txt/data/inception_v3.ckpt"
hsu@ubuntu:~/models-master/research/im2txt$ MODEL_DIR="/home/hsu/models-master/research/im2txt/im2txt/model"
hsu@ubuntu:~/models-master/research/im2txt$ bazel build -c opt //im2txt/..........................................
INFO: Analysed 17 targets (20 packages loaded).
INFO: Found 17 targets...
INFO: Elapsed time: 6.421s, Critical Path: 0.17s
INFO: Build completed successfully, 1 total action
hsu@ubuntu:~/models-master/research/im2txt$ bazel-bin/im2txt/train   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=1000000
INFO:tensorflow:Creating training directory: /home/hsu/models-master/research/im2txt/im2txt/model/train
INFO:tensorflow:Prefetching values from 256 files matching /home/hsu/models-master/research/im2txt/im2txt/data/mscoco/train-?????-of-00256
2017-11-21 19:44:22.013137: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Restoring Inception variables from checkpoint file /home/hsu/models-master/research/im2txt/im2txt/data/inception_v3.ckpt
INFO:tensorflow:Restoring parameters from /home/hsu/models-master/research/im2txt/im2txt/data/inception_v3.ckpt
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /home/hsu/models-master/research/im2txt/im2txt/model/train/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, indices[8,5] = 14103 is not in [0, 12000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq_embedding/map/read, batch_and_pad:1)]]

Caused by op u'seq_embedding/embedding_lookup', defined at:
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 355, in build
    self.build_seq_embeddings()
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 226, in build_seq_embeddings
    seq_embeddings = tf.nn.embedding_lookup(embedding_map, self.input_seqs)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 328, in embedding_lookup
    transform_fn=None)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 150, in _embedding_lookup_and_transform
    result = _clip(_gather(params[0], ids, name=name), ids, max_norm)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 54, in _gather
    return array_ops.gather(params, ids, name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2486, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1834, in gather
    validate_indices=validate_indices, name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[8,5] = 14103 is not in [0, 12000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq_embedding/map/read, batch_and_pad:1)]]

Traceback (most recent call last):
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 110, in main
    saver=saver)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 763, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 487, in train_step
    run_metadata=run_metadata)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[8,5] = 14103 is not in [0, 12000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq_embedding/map/read, batch_and_pad:1)]]

Caused by op u'seq_embedding/embedding_lookup', defined at:
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 355, in build
    self.build_seq_embeddings()
  File "/home/hsu/models-master/research/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 226, in build_seq_embeddings
    seq_embeddings = tf.nn.embedding_lookup(embedding_map, self.input_seqs)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 328, in embedding_lookup
    transform_fn=None)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 150, in _embedding_lookup_and_transform
    result = _clip(_gather(params[0], ids, name=name), ids, max_norm)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 54, in _gather
    return array_ops.gather(params, ids, name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2486, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1834, in gather
    validate_indices=validate_indices, name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[8,5] = 14103 is not in [0, 12000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq_embedding/map/read, batch_and_pad:1)]]

**Comment by j2233ack** [comment]
I use Ubuntu 16.04

**Comment by estelle1722** [comment]
I  have the same problem as you.But  I use the dataset called Xray.And  there are 14 classes in the dataset.If you have time, we can communicate with each other.

**Comment by j2233ack** [comment]
Okay !!
The above problem I have solved.
As long as the size of the vocabulary to adjust large like, for example, the original set 12000 my vocabulary more than 12000, the size transferred to 15000 will be okay.

**Comment by estelle1722** [comment]
I know how you solve your problem.But my program reports error like this:tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [64,14] rhs shape= [64,10]
the number 14 means my dataset classes,and I don't know what the number 10 means?

**Comment by estelle1722** [comment]
@j2233ack And when you apply resnet on your own dataset im2txt,you make a clssification or not.And in the procession,what parameters do you modify?

**Comment by j2233ack** [comment]
You have to clear your model / train?
A new start to training.

**Comment by tatatodd** [comment]
Looks like you resolved your own issue, nice!

For future reference, this type of question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
