### ISSUE TITLE
AttributeError: 'SsdFeatureExtractor' object has no attribute 'pad_to_multiple'

### ISSUE THREAD

**Issue by Jreyno40** [tensorflow/models#2873]
I am attempting to run ssd_mobilenet_v1_coco.config from the samples directory locally, and I am receiving this issue. This is on the most recent master branch with tensorflow 1.4 on windows 10.
```
Traceback (most recent call last):
  File "object_detection/train.py", line 163, in <module>
    tf.app.run()
  File "C:\Users\mccla\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\trainer.py", line 193, in train
    detection_model = create_model_fn()
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\builders\model_builder.py", line 83, in build
    return _build_ssd_model(model_config.ssd, is_training)
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\builders\model_builder.py", line 139, in _build_ssd_model
    is_training)
  File "C:\Users\mccla\Desktop\School\DeepLearning\TensorflowModels\research\object_detection\builders\model_builder.py", line 107, in _build_ssd_feature_extractor
    pad_to_multiple = feature_extractor_config.pad_to_multiple
AttributeError: 'SsdFeatureExtractor' object has no attribute 'pad_to_multiple'
```

**Comment by Jreyno40** [comment]
I believe this is my fault; I haven't re-compiled the protos after updating to the most recent version of the repo. I will close this after I have checked.
