### ISSUE TITLE
3D reconstruction using tensorflow implementation of ptn, error in  pretraining rotator 

### ISSUE THREAD

**Issue by Santubasa** [tensorflow/models#2906]
Hi,
When I tried to pretrain the rotator model with the dataset provided in the webpage, I'm getting the following Value error and I guess the problem is with the inp_dir path for the dataset on the system.

Tried providing both absolute and relative path but still the problem persist, any help would be great since I'm completely new to tensorflow .

ERROR:
INFO: Analysed target //:pretrain_rotator (0 packages loaded).
INFO: Found 1 target...
Target //:pretrain_rotator up-to-date:
  bazel-bin/pretrain_rotator
INFO: Elapsed time: 0.174s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/pretrain_rotator '--step_size=1' '--init_model=/tmp/ptn_train/'
/.shapenet_tf
Traceback (most recent call last):
  File "/home/sbasavaraju/.cache/bazel/_bazel_sbasavaraju/b31d182e049bda91baa4373c1dc1e3ce/execroot/__main__/bazel-out/local-opt/bin/pretrain_rotator.runfiles/__main__/pretrain_rotator.py", line 236, in <module>
    app.run()
  File "/home/sbasavaraju/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/sbasavaraju/.cache/bazel/_bazel_sbasavaraju/b31d182e049bda91baa4373c1dc1e3ce/execroot/__main__/bazel-out/local-opt/bin/pretrain_rotator.runfiles/__main__/pretrain_rotator.py", line 119, in main
    ['encoder', 'rotator', 'decoder'], FLAGS)
  File "/media/sbasavaraju/DATA/ptn/model_rotator.py", line 151, in get_regularization_loss
    return losses.regularization_loss(scopes, params)
  File "/media/sbasavaraju/DATA/ptn/losses.py", line 173, in regularization_loss
    reg_loss += tf.add_n([tf.nn.l2_loss(var) for var in scope_vars])
  File "/home/sbasavaraju/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1942, in add_n
    raise ValueError("inputs must be a list of at least one Tensor with the "
ValueError: inputs must be a list of at least one Tensor with the same dtype and shape
ERROR: Non-zero return code '1' from command: Process exited with status 1

------------------------

System information
-  top-level directory of the model you are using: ptn
- OS Platform and Distribution : Ubuntu 16.04
- TensorFlow version : 1.3.0
- Bazel version: 0.70

**Comment by aselle** [comment]
@xcyan, @hellojas, could you take a look please.

**Comment by xcyan** [comment]
@Santubasa Can you try to print out some debugging information in the losses.py
Just put the following lines ahead of line 172.
`print(scope_vars)`
`print(scope)`
https://github.com/tensorflow/models/blob/master/research/ptn/losses.py#L172

I can help you debug when you send the feedback to me. Thanks!

**Comment by Santubasa** [comment]
@xcyan fortunately I found the solution in the meantime, wherein I was working on a python 3.6.3 version and downgraded the version to 2.7 and the error no longer exists.

Thanks for your support!
