### ISSUE TITLE
Error starting Mujoco task with Trust-PCL

### ISSUE THREAD

**Issue by ViktorM** [tensorflow/models#2948]
When trying to start Mujoco task with Trust-PCL as recommended in https://github.com/tensorflow/models/tree/master/research/pcl_rl readme I've hit an error:
```
[2017-12-03 05:36:46,648] Making new env: Walker2d-v1
Traceback (most recent call last):
  File "trainer.py", line 453, in <module>
    app.run()
  File "/home/viktor/anaconda3/envs/mujoco/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "trainer.py", line 449, in main
    trainer.run()
  File "trainer.py", line 388, in run
    self.controller.setup()
  File "/home/viktor/DeepRL/models/research/pcl_rl/controller.py", line 118, in setup
    self.model.setup()
  File "/home/viktor/DeepRL/models/research/pcl_rl/model.py", line 135, in setup
    self.actions)
  File "/home/viktor/DeepRL/models/research/pcl_rl/policy.py", line 405, in multi_step
    time_length = tf.shape(all_obs[0])[0]
IndexError: list index out of range
```
I have TF 1.4 installed with Python 3.5.2. Looks like code was developed on Python 2.7, I had to replace all xrange with range function to be able to start it. And then got an error above.

**Comment by drpngx** [comment]
Sorry, this is not our code. We can't really support that.

FWIW, For `xrange`, we usually get it from `six`.

**Comment by ashaw596** [comment]
After running it through a 3 to 2 converter. The main remaining bug is you need to convert all 'sampling_dim / 2' in policy.py to 'sampling_dim // 2'. Not 100% sure thats all the bugs. But it runs after that.

**Comment by ewanlee** [comment]
I also encountered this problem. Did you solve it? @ViktorM

**Comment by ewanlee** [comment]
`zip` returns an iterator in Python 3.x instead of a list like it did in Python 2.x. This means that, after you unpack it once, it will become exhausted and no longer usable. So there are some bugs in `setup_placeholders` method in `model.py` @ofirnachum
