### ISSUE TITLE
ImportError: No module named 'tkinter' during testing the installation

### ISSUE THREAD

**Issue by soumenms2015** [tensorflow/models#2949]
Hello I am using python3.4 and tensorflow 1.2.1 . I am getting the following error while testing the installation of object detection api.

Here is:
..models/research> python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "../models/research/object_detection/builders/model_builder.py", line 29, in <module>
    from object_detection.meta_architectures import ssd_meta_arch
  File "../models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 31, in <module>
    from object_detection.utils import visualization_utils
  File "../models/research/object_detection/utils/visualization_utils.py", line 24, in <module>
    import matplotlib.pyplot as plt
  File "../lib/python3.4/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "../lib/python3.4/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "../lib/python3.4/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "../lib/python3.4/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "../lib/python3.4/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "../lib/python3.4/site-packages/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named 'tkinter'

Any help would be appreciated !!

**Comment by reedwm** [comment]
/CC @tombstone, can you take a look? This might be related to #2739

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
