### ISSUE TITLE
run eval.py error

### ISSUE THREAD

**Issue by MonsterCJJ** [tensorflow/models#3040]
When i run eval.py , i got the follows error. I don't know how to solve it.

`/home/monstercjj/anaconda3/bin/python /home/monstercjj/PycharmProjects/person_detection/eval.py --logtostderr \ --checkpoint_dir=/home/monstercjj/PycharmProjects/person_detection/models_v3/model/train \ --eval_dir=/home/monstercjj/PycharmProjects/person_detection/models_v3/model/eval \ --pipeline_config_path=/home/monstercjj/PycharmProjects/person_detection/models_v3/model/pipeline.config
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
2017-12-21 15:49:50.783170: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-21 15:49:50.785633: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2017-12-21 15:49:50.785668: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: monstercjj
2017-12-21 15:49:50.785673: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: monstercjj
2017-12-21 15:49:50.785692: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.90.0
2017-12-21 15:49:50.785705: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.90  Tue Sep 19 19:17:35 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
"""
2017-12-21 15:49:50.785715: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.90.0
2017-12-21 15:49:50.785718: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.90.0
INFO:tensorflow:Restoring parameters from /home/monstercjj/PycharmProjects/person_detection/models_v3/model/train/model.ckpt-53993
INFO:tensorflow:Restoring parameters from /home/monstercjj/PycharmProjects/person_detection/models_v3/model/train/model.ckpt-53993
WARNING:root:The following classes have no ground truth examples: 1
/home/monstercjj/PycharmProjects/person_detection/object_detection/utils/object_detection_evaluation.py:585: RuntimeWarning: Mean of empty slice
  mean_ap = np.nanmean(self.average_precision_per_class)
Traceback (most recent call last):
  File "/home/monstercjj/PycharmProjects/person_detection/eval.py", line 132, in <module>
    tf.app.run()
  File "/home/monstercjj/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/monstercjj/PycharmProjects/person_detection/eval.py", line 128, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/monstercjj/PycharmProjects/person_detection/object_detection/evaluator.py", line 210, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/home/monstercjj/PycharmProjects/person_detection/object_detection/eval_util.py", line 381, in repeated_checkpoint_run
    save_graph_dir)
  File "/home/monstercjj/PycharmProjects/person_detection/object_detection/eval_util.py", line 271, in _run_checkpoint_once
    image_id=batch, detections_dict=result_dict)
  File "/home/monstercjj/PycharmProjects/person_detection/object_detection/utils/object_detection_evaluation.py", line 199, in add_single_detected_image_info
    detection_classes)
  File "/home/monstercjj/PycharmProjects/person_detection/object_detection/utils/object_detection_evaluation.py", line 497, in add_single_detected_image_info
    groundtruth_is_difficult_list, groundtruth_is_group_of_list))
  File "/home/monstercjj/PycharmProjects/person_detection/object_detection/utils/per_image_evaluation.py", line 95, in compute_object_detection_metrics
    groundtruth_is_difficult_lists, groundtruth_is_group_of_list)
  File "/home/monstercjj/PycharmProjects/person_detection/object_detection/utils/per_image_evaluation.py", line 203, in _compute_tp_fp
    groundtruth_is_difficult_lists[groundtruth_class_labels == i])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1`
```

**Comment by michaelisard** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by withyou1771** [comment]
I met the same question. Did you solve it?
