### ISSUE TITLE
Cifar tutorial broken with "Default AvgPoolingOp only supports NHWC."

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/models#3050]
Trying latest tensorflow (commit https://github.com/tensorflow/tensorflow/commit/f950ea836d) and latest models repo on my macbook.

```
cd ~/git/models/tutorials/image/cifar10_estimator
python cifar10_main.py --data-dir=/tmp/cifar --job-dir=/tmp/cifar
```
This crashes with following

```
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x118fbb438>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': gpu_options {
  force_gpu_compatible: true
}
allow_soft_placement: true
, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/cifar'}
WARNING:tensorflow:From /Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:267: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
WARNING:tensorflow:From /Users/yaroslav/git/models/tutorials/image/cifar10_estimator/cifar10.py:74: TFRecordDataset.__init__ (from tensorflow.contrib.data.python.ops.readers) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.TFRecordDataset`.
WARNING:tensorflow:From /Users/yaroslav/git/models/tutorials/image/cifar10_estimator/cifar10.py:78: calling Dataset.map (from tensorflow.contrib.data.python.ops.dataset_ops) with num_threads is deprecated and will be removed in a future version.
Instructions for updating:
Replace `num_threads=T` with `num_parallel_calls=T`. Replace `output_buffer_size=N` with `ds.prefetch(N)` on the returned dataset.
WARNING:tensorflow:From /Users/yaroslav/git/models/tutorials/image/cifar10_estimator/cifar10.py:78: calling Dataset.map (from tensorflow.contrib.data.python.ops.dataset_ops) with output_buffer_size is deprecated and will be removed in a future version.
Instructions for updating:
Replace `num_threads=T` with `num_parallel_calls=T`. Replace `output_buffer_size=N` with `ds.prefetch(N)` on the returned dataset.
INFO:tensorflow:image after unit resnet/tower_0/stage/residual_v1/: (?, 16, 32, 32)
INFO:tensorflow:image after unit resnet/tower_0/stage/residual_v1_1/: (?, 16, 32, 32)
INFO:tensorflow:image after unit resnet/tower_0/stage/residual_v1_2/: (?, 16, 32, 32)
INFO:tensorflow:image after unit resnet/tower_0/stage/residual_v1_3/: (?, 16, 32, 32)
INFO:tensorflow:image after unit resnet/tower_0/stage/residual_v1_4/: (?, 16, 32, 32)
INFO:tensorflow:image after unit resnet/tower_0/stage/residual_v1_5/: (?, 16, 32, 32)
INFO:tensorflow:image after unit resnet/tower_0/stage/residual_v1_6/: (?, 16, 32, 32)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1/avg_pool/: (?, 16, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1/: (?, 32, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1_1/: (?, 32, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1_2/: (?, 32, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1_3/: (?, 32, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1_4/: (?, 32, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1_5/: (?, 32, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_1/residual_v1_6/: (?, 32, 16, 16)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1/avg_pool/: (?, 32, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1/: (?, 64, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1_1/: (?, 64, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1_2/: (?, 64, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1_3/: (?, 64, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1_4/: (?, 64, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1_5/: (?, 64, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/stage_2/residual_v1_6/: (?, 64, 8, 8)
INFO:tensorflow:image after unit resnet/tower_0/global_avg_pool/: (?, 64)
INFO:tensorflow:image after unit resnet/tower_0/fully_connected/: (?, 11)
INFO:tensorflow:Create CheckpointSaverHook.
2017-12-23 12:02:03.073209: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
2017-12-23 12:02:15.917345: E tensorflow/core/common_runtime/executor.cc:651] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC.
	 [[Node: resnet/tower_0/stage_1/residual_v1/avg_pool/average_pooling2d/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet/tower_0/stage/residual_v1_6/Relu_1)]]
Traceback (most recent call last):
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC.
	 [[Node: resnet/tower_0/stage_1/residual_v1/avg_pool/average_pooling2d/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet/tower_0/stage/residual_v1_6/Relu_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cifar10_main.py", line 519, in <module>
    main(**vars(args))
  File "cifar10_main.py", line 387, in main
    **hparams))
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 661, in train_and_evaluate
    self.train(delay_secs=0)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 390, in train
    saving_listeners=self._saving_listeners)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 868, in _call_train
    saving_listeners=saving_listeners)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 815, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1013, in run
    run_metadata=run_metadata)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1104, in run
    raise six.reraise(*original_exc_info)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1161, in run
    run_metadata=run_metadata)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 941, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC.
	 [[Node: resnet/tower_0/stage_1/residual_v1/avg_pool/average_pooling2d/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet/tower_0/stage/residual_v1_6/Relu_1)]]

Caused by op 'resnet/tower_0/stage_1/residual_v1/avg_pool/average_pooling2d/AvgPool', defined at:
  File "cifar10_main.py", line 519, in <module>
    main(**vars(args))
  File "cifar10_main.py", line 387, in main
    **hparams))
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 661, in train_and_evaluate
    self.train(delay_secs=0)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 390, in train
    saving_listeners=self._saving_listeners)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 868, in _call_train
    saving_listeners=saving_listeners)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "cifar10_main.py", line 111, in _resnet_model_fn
    params.batch_norm_epsilon)
  File "cifar10_main.py", line 234, in _tower_fn
    logits = model.forward_pass(feature, input_data_format='channels_last')
  File "/Users/yaroslav/git/models/tutorials/image/cifar10_estimator/cifar10_model.py", line 72, in forward_pass
    self.strides[i])
  File "/Users/yaroslav/git/models/tutorials/image/cifar10_estimator/model_base.py", line 71, in _residual_v1
    orig_x = self._avg_pool(orig_x, stride, stride)
  File "/Users/yaroslav/git/models/tutorials/image/cifar10_estimator/model_base.py", line 206, in _avg_pool
    x, pool_size, stride, 'SAME', data_format=self._data_format)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/layers/pooling.py", line 361, in average_pooling2d
    return layer.apply(inputs)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 763, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 653, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/layers/pooling.py", line 273, in call
    data_format=utils.convert_data_format(self.data_format, 4))
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2015, in avg_pool
    name=name)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 69, in _avg_pool
    data_format=data_format, name=name)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/Users/yaroslav/anaconda/envs/cifar/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1617, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Default AvgPoolingOp only supports NHWC.
	 [[Node: resnet/tower_0/stage_1/residual_v1/avg_pool/average_pooling2d/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 2, 2], padding="SAME", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet/tower_0/stage/residual_v1_6/Relu_1)]]

```

**Comment by yaroslavvb** [comment]
Looks like the problem is that 'num-gpus' is set to "1" by default. It might be better to use tf.testing.is_gpu_available() to select data format.

Also for this tutorial data generation crashes in Python 3 because there's no cPickle there (replaced with `import pickle`)

**Comment by skye** [comment]
@sherrym @shlens can one of you look into this? Thanks.

**Comment by yaroslavvb** [comment]
The simplest change that will avoid headache for new users is to add the following after this line https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10_estimator/cifar10_main.py#L506

```
  if args.num_gpus>0:
    assert tf.test.is_gpu_available(), "Requested GPUs but none found."
```

**Comment by shlens** [comment]
@yaroslavvb Looks reasonable to me. Send a PR for my review?

**Comment by shlens** [comment]
I believed this is now closed as a PR added an is_gpu_available() check. Please reopen otherwise.
