### ISSUE TITLE
Something wrong in "object_detection/builders/model_builder_test.py"

### ISSUE THREAD

**Issue by gun1you1** [tensorflow/models#3090]
When i run the "object_detection/builders/model_builder_test.py",some problom happen :+1: 
EEEEEEEEEE.
======================================================================
ERROR: test_create_faster_rcnn_inception_resnet_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 544, in test_create_faster_rcnn_inception_resnet_v2_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 85, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 226, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\image_resizer_builder.py", line 81, in build
    method = _tf_resize_method(keep_aspect_ratio_config.resize_method)
AttributeError: 'KeepAspectRatioResizer' object has no attribute 'resize_method'

======================================================================
ERROR: test_create_faster_rcnn_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 611, in test_create_faster_rcnn_inception_v2_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 85, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 226, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\image_resizer_builder.py", line 81, in build
    method = _tf_resize_method(keep_aspect_ratio_config.resize_method)
AttributeError: 'KeepAspectRatioResizer' object has no attribute 'resize_method'

======================================================================
ERROR: test_create_faster_rcnn_model_from_config_with_example_miner (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 669, in test_create_faster_rcnn_model_from_config_with_example_miner
    model = model_builder.build(model_proto, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 85, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 226, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\image_resizer_builder.py", line 81, in build
    method = _tf_resize_method(keep_aspect_ratio_config.resize_method)
AttributeError: 'KeepAspectRatioResizer' object has no attribute 'resize_method'

======================================================================
ERROR: test_create_faster_rcnn_nas_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 477, in test_create_faster_rcnn_nas_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 85, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 226, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\image_resizer_builder.py", line 81, in build
    method = _tf_resize_method(keep_aspect_ratio_config.resize_method)
AttributeError: 'KeepAspectRatioResizer' object has no attribute 'resize_method'

======================================================================
ERROR: test_create_faster_rcnn_resnet101_with_mask_prediction_enabled (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 412, in test_create_faster_rcnn_resnet101_with_mask_prediction_enabled
    text_format.Merge(model_text_proto, model_proto)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 643, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 60:9 : Message type "object_detection.protos.FasterRcnn" has no field named "second_stage_mask_prediction_loss_weight".

======================================================================
ERROR: test_create_faster_rcnn_resnet_v1_models_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 336, in test_create_faster_rcnn_resnet_v1_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 85, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 226, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\image_resizer_builder.py", line 81, in build
    method = _tf_resize_method(keep_aspect_ratio_config.resize_method)
AttributeError: 'KeepAspectRatioResizer' object has no attribute 'resize_method'

======================================================================
ERROR: test_create_rfcn_resnet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 735, in test_create_rfcn_resnet_v1_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 85, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 226, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\image_resizer_builder.py", line 81, in build
    method = _tf_resize_method(keep_aspect_ratio_config.resize_method)
AttributeError: 'KeepAspectRatioResizer' object has no attribute 'resize_method'

======================================================================
ERROR: test_create_ssd_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 124, in test_create_ssd_inception_v2_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 56, in create_model
    return model_builder.build(model_config, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 83, in build
    return _build_ssd_model(model_config.ssd, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 139, in _build_ssd_model
    is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 107, in _build_ssd_feature_extractor
    pad_to_multiple = feature_extractor_config.pad_to_multiple
AttributeError: 'SsdFeatureExtractor' object has no attribute 'pad_to_multiple'

======================================================================
ERROR: test_create_ssd_inception_v3_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 195, in test_create_ssd_inception_v3_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 56, in create_model
    return model_builder.build(model_config, is_training=True)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 83, in build
    return _build_ssd_model(model_config.ssd, is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 139, in _build_ssd_model
    is_training)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 107, in _build_ssd_feature_extractor
    pad_to_multiple = feature_extractor_config.pad_to_multiple
AttributeError: 'SsdFeatureExtractor' object has no attribute 'pad_to_multiple'

======================================================================
ERROR: test_create_ssd_mobilenet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 266, in test_create_ssd_mobilenet_v1_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\giggle\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 643, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 15:11 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "batch_norm_trainable".

----------------------------------------------------------------------
Ran 11 tests in 0.013s

FAILED (errors=10)

plese help! thank you !

**Comment by iyeszin** [comment]
Hi, had you solved it? How?

**Comment by zaichang** [comment]
Try regenerating the python protobuf classes:

```protoc object_detection/protos/*.proto --python_out=.```

This error happened to me as well after I updated the models repo as the generated classes were out of date.

**Comment by awaiseye** [comment]
hi , is that fixed yet. What did you do to fix that?
