### ISSUE TITLE
Problem running my own model following the TensorFlow for Poets 2: Optimize for Mobile tutorial

### ISSUE THREAD

**Issue by PhillipLy** [tensorflow/models#3117]
### System information
- **OS Platform and Distribution: 
     1) Windows 10 for Android Studio and Training Custom Model via Tensorflow-GPU;  
     2) Ubuntu 16.04 (via Oracle VM VirtualBox) to follow TensorFlow for Poets 2: Optimize for Mobile Tutorial 
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.4
- **CUDA/cuDNN version**:  Cuda Toolkit 8.0 and cuDNN v5.1
- **GPU model and memory**: NVIDIA GTX 1070. 8GB
- **Exact command to reproduce**: Please see "TensorFlow for Poets 2: Optimize for Mobile" tutorial.

### Describe the problem
I am following the "TensorFlow for Poets 2: Optimize for Mobile" tutorial and everything works just fine until I tried and run my own model on a virtual device (Nexus 5x API 27 x86). Please note that I have successfully ran the default app (setup classifies images into one of the 1000 ImageNet classes, using the standard MobileNet) before running into this problem. 
Furthermore, I have already followed the below instructions and modified my ClassifierActivity.java file accordinly. I suspect I need to deploy this apk on a real Android device instead of using a virtual device. I won't get my hand on a real device in 2-3 weeks so I appreciate any help to resolve this bug. Thank you for any help in advance!

Instructions to run custom model:
  // These are the settings for the original v1 Inception model. If you want to
  // use a model that's been produced from the TensorFlow for Poets codelab,
  // you'll need to set IMAGE_SIZE = 299, IMAGE_MEAN = 128, IMAGE_STD = 128,
  // INPUT_NAME = "Mul", and OUTPUT_NAME = "final_result".
  // You'll also need to update the MODEL_FILE and LABEL_FILE paths to point to
  // the ones you produced.

### Source code / logs
01/06 17:25:08: Launching tfmobile
$ adb install-multiple -r -t D:\tensorflow_skinlesion\android\tfmobile\gradleBuild\intermediates\split-apk\debug\dep\dependencies.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_0.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_1.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_2.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_3.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_4.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_5.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_6.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_7.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_8.apk D:\tensorflow\android\tfmobile\gradleBuild\intermediates\split-apk\debug\slices\slice_9.apk D:\tensorflow\android\tfmobile\gradleBuild\outputs\apk\debug\tfmobile-debug.apk 
Split APKs installed
$ adb shell am start -n "org.tensorflow.demo/org.tensorflow.demo.ClassifierActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 4543 on device emulator-5554
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/InstantRun: starting instant run server: is main process
D/tensorflow: CameraActivity: onCreate org.tensorflow.demo.ClassifierActivity@33c8742
D/tensorflow: CameraActivity: onStart org.tensorflow.demo.ClassifierActivity@33c8742
D/tensorflow: CameraActivity: onResume org.tensorflow.demo.ClassifierActivity@33c8742
D/OpenGLRenderer: HWUI GL Pipeline
I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xa490c700: maj 3 min 1 rcv 4
D/EGL_emulation: eglMakeCurrent: 0xa490c700: ver 3 1 (tinfo 0x92f460a0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
I/CameraManagerGlobal: Connecting to camera service
I/tensorflow: CameraConnectionFragment: Desired size: 640x480, min size: 480x480
I/tensorflow: CameraConnectionFragment: Valid preview sizes: [640x480]
I/tensorflow: CameraConnectionFragment: Rejected preview sizes: [352x288, 320x240, 176x144]
I/tensorflow: CameraConnectionFragment: Exact size match found.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.tensorflow.demo, PID: 4543
                  java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                      at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:89)
                      at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:130)
                      at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:159)
                      at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:421)
                      at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:428)
                      at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64)
                      at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95)
                      at android.view.TextureView.getHardwareLayer(TextureView.java:390)
                      at android.view.TextureView.draw(TextureView.java:339)
                      at android.view.View.updateDisplayListIfDirty(View.java:18142)
                      at android.view.View.draw(View.java:18920)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                      at android.view.View.updateDisplayListIfDirty(View.java:18133)
                      at android.view.View.draw(View.java:18920)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                      at android.view.View.draw(View.java:19195)
                      at android.view.View.updateDisplayListIfDirty(View.java:18142)
                      at android.view.View.draw(View.java:18920)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                      at android.view.View.updateDisplayListIfDirty(View.java:18133)
                      at android.view.View.draw(View.java:18920)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                      at android.view.View.updateDisplayListIfDirty(View.java:18133)
                      at android.view.View.draw(View.java:18920)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                      at android.view.View.draw(View.java:19195)
                      at com.android.internal.policy.DecorView.draw(DecorView.java:788)
                      at android.view.View.updateDisplayListIfDirty(View.java:18142)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                      at android.view.Choreographer.doFrame(Choreographer.java:658)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Application terminated.

**Comment by PhillipLy** [comment]
Solved. Also my apology for posting this in the wrong place.

**Comment by polaroidkidd** [comment]
How did you solve it? I'm having problems as well
