### ISSUE TITLE
Convert channel last to channel first.

### ISSUE THREAD

**Issue by xiaochenwang94** [tensorflow/models#3167]
https://github.com/tensorflow/models/blob/1887a5fe187c8ab9f623cd91b74fc8432ce76d6f/official/resnet/resnet_model.py#L244
In this function, the model wants to transform channel last to channel first? Should there be
`if data_format == 'channels_last': `?

**Comment by nealwu** [comment]
Hi @xiaochenwang94, the model code is correct. The input comes in `channels_last` format by default, so we only need to transpose it if we wish to convert it to `channels_first` format.

**Comment by xiaochenwang94** [comment]
The comment before this line is `# Convert the inputs from channels_last (NHWC) to channels_first (NCHW).` 
Should it be `# Convert the inputs from channels_first (NCHW) to channels_last (NHWC).`?

**Comment by nealwu** [comment]
No, `data_format` specifies the desired format, not the existing one. The data always comes in as channels_last format.

**Comment by deepaksuresh** [comment]
@nealwu I have trained a model in `channel_first` format on `GPU`. I'd like to perform inference using that model on `CPU`, but `CPU` supports only `channel_last` format. Is there a way I can convert the trained model to run on `CPU`?

**Comment by nealwu** [comment]
Hi @deepaksuresh, I believe you can just run the model again passing in the same `model_dir` that you used before, except this time with `--data_format=channels_last`. Let me know if that works.

**Comment by deepaksuresh** [comment]
Hi @nealwu , I get the following error when I try to run the model with `--data_format=channels_last`
`INFO:tensorflow:Restoring parameters from ./multires\model.ckpt-32208
2018-02-28 11:09:27.817211: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_33/beta/Momentum not found in checkpoint
2018-02-28 11:09:27.817363: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_33/beta not found in checkpoint
2018-02-28 11:09:27.818302: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_33/gamma/Momentum not found in checkpoint
2018-02-28 11:09:27.818641: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_33/gamma not found in checkpoint
2018-02-28 11:09:27.820607: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_33/moving_mean not found in checkpoint
2018-02-28 11:09:27.820607: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_33/moving_variance not found in checkpoint
2018-02-28 11:09:27.820802: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_34/beta not found in checkpoint
2018-02-28 11:09:27.823904: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_34/beta/Momentum not found in checkpoint
2018-02-28 11:09:27.826989: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_34/gamma not found in checkpoint
2018-02-28 11:09:27.831631: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_34/gamma/Momentum not found in checkpoint
2018-02-28 11:09:27.836555: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_34/moving_mean not found in checkpoint
2018-02-28 11:09:27.839932: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_34/moving_variance not found in checkpoint
2018-02-28 11:09:27.843526: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_35/beta not found in checkpoint
2018-02-28 11:09:27.847889: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_35/beta/Momentum not found in checkpoint
2018-02-28 11:09:27.851506: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_35/gamma not found in checkpoint
2018-02-28 11:09:27.852205: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_40/moving_variance not found in checkpoint
2018-02-28 11:09:27.855024: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_35/gamma/Momentum not found in checkpoint
2018-02-28 11:09:27.857765: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_35/moving_mean not found in checkpoint
2018-02-28 11:09:27.860790: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_35/moving_variance not found in checkpoint
2018-02-28 11:09:27.865890: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_36/beta not found in checkpoint
2018-02-28 11:09:27.868689: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_36/beta/Momentum not found in checkpoint
2018-02-28 11:09:27.872010: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_36/gamma not found in checkpoint
2018-02-28 11:09:27.874703: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_36/gamma/Momentum not found in checkpoint
2018-02-28 11:09:27.878892: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_40/moving_mean not found in checkpoint
2018-02-28 11:09:27.882202: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_36/moving_mean not found in checkpoint
2018-02-28 11:09:27.884890: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_36/moving_variance not found in checkpoint
2018-02-28 11:09:27.888129: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_37/beta not found in checkpoint
2018-02-28 11:09:27.890883: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_37/gamma not found in checkpoint
2018-02-28 11:09:27.895220: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_37/moving_mean not found in checkpoint
2018-02-28 11:09:27.898419: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_37/moving_variance not found in checkpoint
2018-02-28 11:09:27.901206: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_38/beta not found in checkpoint
2018-02-28 11:09:27.904575: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_40/gamma/Momentum not found in checkpoint
2018-02-28 11:09:27.907660: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_38/beta/Momentum not found in checkpoint
2018-02-28 11:09:27.912927: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_38/gamma not found in checkpoint
2018-02-28 11:09:27.915872: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_38/gamma/Momentum not found in checkpoint
2018-02-28 11:09:27.918740: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_38/moving_mean not found in checkpoint
2018-02-28 11:09:27.921838: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_38/moving_variance not found in checkpoint
2018-02-28 11:09:27.926000: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_39/beta not found in checkpoint
2018-02-28 11:09:27.929175: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_39/beta/Momentum not found in checkpoint
2018-02-28 11:09:27.932065: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_40/gamma not found in checkpoint
2018-02-28 11:09:27.958865: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_40/beta/Momentum not found in checkpoint
2018-02-28 11:09:27.943802: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_39/moving_mean not found in checkpoint
2018-02-28 11:09:27.958865: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_40/beta not found in checkpoint
2018-02-28 11:09:27.946774: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_39/moving_variance not found in checkpoint
2018-02-28 11:09:27.938414: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_39/gamma/Momentum not found in checkpoint
2018-02-28 11:09:27.935211: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Key batch_normalization_39/gamma not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\Photogauge\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "C:\Users\Photogauge\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "C:\Users\Photogauge\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [32] rhs shape= [64]
         [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@batch_normalization_10/beta"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](batch_normalization_10/beta, save/RestoreV2_12/_527)]]`

Thank you for your time

**Comment by deepaksuresh** [comment]
Hi @nealwu , I forgot to mention that the model has already been trained, in `channel_first` format on `GPU`, and was exported as a `.pb` file using `tf.estimator..export_savedmodel`. Is there a way to make this model run on `CPU`, which supports only `channel_last` operations?
Thanks for your time.

**Comment by nealwu** [comment]
@deepaksuresh try using my pre-trained model at the bottom of https://github.com/tensorflow/models/tree/master/official/resnet#pre-trained-model.

**Comment by deepaksuresh** [comment]
@nealwu 
1. "I believe you can just run the model again passing in the same model_dir that you used before, except this time with --data_format=channels_last", yes this works!
I ran the script with `--data_format=channels_first`, saved the model, and then ran the script with the same `model_dir` with `--data_format=channels_last`. I was able to run this model on `CPU`!

2.  The above solution works when the training files were available. In the case where I had only the output of `tf.estimator.export_savedmodel`, I had to do a network surgery. I made a clone of the graph, in `channel_last`  format, loaded it in and assigned all variables, values from the trained model. This new graph runs fine on `CPU`.
Thanks a lot for the help

**Comment by nealwu** [comment]
Excellent! Glad that worked for you.

**Comment by laetitiaoist** [comment]
Hi! I am new to this repository. Why do we assume the input is in NHWC format? If my input is already in NCHW format, then this line will transpose it. 
Can I use this model if my input is already in the format NCHW?

**Comment by kingaza** [comment]
@deepaksuresh Could give explain a little bit more detailed about

> In the case where I had only the output of tf.estimator.export_savedmodel, I had to do a network surgery. I made a clone of the graph, in channel_last format, loaded it in and assigned all variables, values from the trained model. This new graph runs fine on CPU.

I have a complex network which has been exported to a pb file, and as you case, I want to run it on CPU however it is in format of NCHW...

@nealwu it is also appreciated if you can give me some hints.

**Comment by M-Harrington** [comment]
Likewise to @kingaza, it'd be nice to have more guidance on this. I've run into the same issue, it seems that loading a pre-saved function isn't always easily fixed with --data_format=channels_last .  It would be nice to have a built-in function to handle this.  @nealwu is this something that would be worth creating a separate issue for?
