### ISSUE TITLE
maximum box coordinate value is larger than 1.01

### ISSUE THREAD

**Issue by nealzGu** [tensorflow/models#3178]
Hey all,

how can I edit files in "build/..." ???

I got this error message, which is caused by my label files. I want to set the threshold from 1.01 to 1.1, but changing box_list_ops.py in /object_detection/core/ has no effect, since the code is looking to the "/build" folder. 

Is that something I can change by setting a different PYTHONPATH (already tried out, nothing worked)? How can I edit this file?

Thanks!

````
Caused by op u'ToAbsoluteCoordinates/Assert/AssertGuard/Assert', defined at:
  File "object_detection/train.py", line 210, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 206, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "build/bdist.linux-x86_64/egg/object_detection/trainer.py", line 192, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "build/bdist.linux-x86_64/egg/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/object_detection/trainer.py", line 131, in _create_losses
    prediction_dict = detection_model.predict(images)
  File "build/bdist.linux-x86_64/egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 545, in predict
    anchors, image_shape))
  File "build/bdist.linux-x86_64/egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 596, in _predict_second_stage
    anchors, image_shape)
  File "build/bdist.linux-x86_64/egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 894, in _postprocess_rpn
    ) = self._format_groundtruth_data(image_shape)
  File "build/bdist.linux-x86_64/egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1016, in _format_groundtruth_data
    for boxes in self.groundtruth_lists(fields.BoxListFields.boxes)]
  File "build/bdist.linux-x86_64/egg/object_detection/core/box_list_ops.py", line 802, in to_absolute_coordinates
    'than 1.01: ', box_maximum])

````

**Comment by nealzGu** [comment]
also, if try to use a different architecture (inception), I got this error message:

````
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "object_detection/train.py", line 210, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/train.py", line 206, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "build/bdist.linux-x86_64/egg/object_detection/trainer.py", line 159, in train
    groundtruth_keypoints_list = None
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 75, in build
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 214, in _build_faster_rcnn_model
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 186, in _build_faster_rcnn_feature_extractor
ValueError: Unknown Faster R-CNN feature_extractor: faster_rcnn_inception_v2
````

are these messages somehow related to each other? did something went wrong during installation!?

Thanks!

**Comment by monomon** [comment]
Note that your dataset coordinates have to be normalized in the range [0-1].

**Comment by nealzGu** [comment]
I'm doing this by 
````
        xmins.append(float(label['xmin'] / width))
        xmaxs.append(float(label['xmax'] / width))
        ymins.append(float(label['ymin'] / height))
        ymaxs.append(float(label['ymax'] / height))
````
during creation of t.record file.

**Comment by monomon** [comment]
Could you try logging the values of box coordinates e.g. in `to_absolute_coordinates` to see what they are?

**Comment by nealzGu** [comment]
where can I find this?

Im not sure if the bboxes are the problem. The scores during inference are extremely low, so it's not detecting anything, altough the training process ran smoothly...

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
