### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by nesrinenino** [tensorflow/models#3193]
Hello, trying to run this command  in Windows10 C:\Users\nesrine\models\tutorials\image\imagenet>python classify_image.py
Traceback (most recent call last):
  File "classify_image.py", line 227, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "classify_image.py", line 190, in main
    maybe_download_and_extract()
  File "classify_image.py", line 186, in maybe_download_and_extract
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\tarfile.py", line 241, in copyfileobj
    buf = src.read(BUFSIZE)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\gzip.py", line 274, in read
    return self._buffer.read(size)
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Users\nesrine\AppData\Local\Programs\Python\Python35\lib\gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
thank you for any help

**Comment by hdoubleps** [comment]
I wanna also know that .I also face this error.Can you tell me please.:'(

**Comment by Pikamander2** [comment]
@tatatodd - I got this error as well due to the download getting interrupted. None of the StackOverflow answers helped. What files do we need to delete to restart the download?
