### ISSUE TITLE
"if grad" TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed

### ISSUE THREAD

**Issue by w4-sjcho** [tensorflow/models#32]
Getting the following error with the latest tensorflow (head version)
```
Traceback (most recent call last):
  File "/home/gabe/repos/tf-models/inception/bazel-bin/inception/my_train.runfiles/inception/my_train.py", line 41, in <module>
    tf.app.run()
  File "/home/gabe/anaconda2/envs/tf-inception/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/gabe/repos/tf-models/inception/bazel-bin/inception/my_train.runfiles/inception/my_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/gabe/repos/tf-models/inception/bazel-bin/inception/my_train.runfiles/inception/inception_train.py", line 269, in train
    if grad:
  File "/home/gabe/anaconda2/envs/tf-inception/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 475, in __nonzero__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.
```

https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py#L269

Changing to `if grad is not None` solved the issue.

**Comment by sguada** [comment]
Solved by #36
