### ISSUE TITLE
Not able to install due to errors in the BUILD file

### ISSUE THREAD

**Issue by kartik144** [tensorflow/models#3204]
I am getting the following error on installing. Could someone please help?

```
ERROR: /home/kartik144/models/research/syntaxnet/dragnn/protos/BUILD:35:1: Traceback (most recent call last):
	File "/home/kartik144/models/research/syntaxnet/dragnn/protos/BUILD", line 35
		tf_proto_library_py(name = "data_py_pb2", srcs = ["dat..."])
	File "/home/kartik144/models/research/syntaxnet/syntaxnet/syntaxnet.bzl", line 53, in tf_proto_library_py
		py_proto_library(name = name, srcs = srcs, srcs_versi...", <5 more arguments>)
	File "/home/kartik144/.cache/bazel/_bazel_kartik144/244617ffdeb94b8739837877bf6c8971/external/protobuf_archive/protobuf.bzl", line 374, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: package contains errors: dragnn/protos
ERROR: /home/kartik144/models/research/syntaxnet/dragnn/protos/BUILD:40:1: Traceback (most recent call last):
	File "/home/kartik144/models/research/syntaxnet/dragnn/protos/BUILD", line 40
		tf_proto_library_py(name = "trace_py_pb2", srcs = ["tr..."], ..."])
	File "/home/kartik144/models/research/syntaxnet/syntaxnet/syntaxnet.bzl", line 53, in tf_proto_library_py
		py_proto_library(name = name, srcs = srcs, srcs_versi...", <5 more arguments>)
	File "/home/kartik144/.cache/bazel/_bazel_kartik144/244617ffdeb94b8739837877bf6c8971/external/protobuf_archive/protobuf.bzl", line 374, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /home/kartik144/models/research/syntaxnet/dragnn/protos/BUILD:46:1: Traceback (most recent call last):
	File "/home/kartik144/models/research/syntaxnet/dragnn/protos/BUILD", line 46
		tf_proto_library_py(name = "spec_py_pb2", srcs = ["spe..."])
	File "/home/kartik144/models/research/syntaxnet/syntaxnet/syntaxnet.bzl", line 53, in tf_proto_library_py
		py_proto_library(name = name, srcs = srcs, srcs_versi...", <5 more arguments>)
	File "/home/kartik144/.cache/bazel/_bazel_kartik144/244617ffdeb94b8739837877bf6c8971/external/protobuf_archive/protobuf.bzl", line 374, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:13:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:23:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:28:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:33:1: name 'tf_proto_library_py' is not defined
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:38:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:43:1: name 'tf_proto_library_py' is not defined
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:48:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:54:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:59:1: name 'tf_proto_library_py' is not defined
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:64:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:69:1: name 'tf_proto_library_py' is not defined
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:773:1: name 'tf_gen_op_libs' is not defined
ERROR: /home/kartik144/models/research/syntaxnet/syntaxnet/BUILD:777:1: name 'tf_gen_op_wrapper_py' is not defined
ERROR: package contains errors: syntaxnet
ERROR: error loading package 'syntaxnet': Package 'syntaxnet' contains errors
INFO: Elapsed time: 2.262s
FAILED: Build did NOT complete successfully (19 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

**Comment by drpngx** [comment]
@calberti @andorardo @bogatyy @markomernick any idea?

**Comment by markomernick** [comment]
What version of TF do you have installed?

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again. Feel free to reopen the issue if it still persists. Thanks!
