### ISSUE TITLE
Another errors when reading the DELF pre-trained model

### ISSUE THREAD

**Issue by Vasay** [tensorflow/models#3289]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution**: Mac OS High Sierra
- **Python version**: 3.5.0
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version**: v1.3.0-rc2-20-g0787eee 1.3.0 (also tried 1.5)
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: no cuda
- **GPU model and memory**: no gpu
- **Exact command to reproduce**: 
```
# From tensorflow/models/research/delf/delf/python/examples/
python3 extract_features.py \
  --config_path delf_config_example.pbtxt \
  --list_images_path list_images.txt \
  --output_dir data/oxford5k_features
```

### Describe the problem
I'm trying to reproduce DELF example from https://github.com/tensorflow/models/blob/master/research/delf/EXTRACTION_MATCHING.md

Unfortunately I'm getting error reading the file delf/python/examples/parameters/delf_v1_20171026/pca/mean.datum:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 5: invalid start byte`
File seems to be corrupted, but I've tried to download and unpack it twice.
The file is opened with command 
```
  with tf.gfile.FastGFile(file_path, 'r') as f:
    return ParseFromString(f.read())
```
but it contains no string data if opened in notepad.
Full error description is below:

```
INFO:tensorflow:Restoring parameters from b'parameters2/delf_v1_20171026/model/variables/variables'
Traceback (most recent call last):
  File "extract_features.py", line 197, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "extract_features.py", line 118, in main
    boxes, raw_descriptors, config)
  File "/Users/ariel/curious/research/libs/tensorflow/models/research/delf/delf/python/feature_extractor.py", line 360, in DelfFeaturePostProcessing
    config.delf_local_config.pca_parameters.mean_path),
  File "/Users/ariel/curious/research/libs/tensorflow/models/research/delf/delf/python/datum_io.py", line 97, in ReadFromFile
    return ParseFromString(f.read())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 93, in _prepare_value
    return compat.as_str_any(val)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 5: invalid start byte
```

**Comment by andrefaraujo** [comment]
I see that you are using python 3.5. We had some issues with this in the past. Could you do a quick attempt with python 2.7?

**Comment by Vasay** [comment]
Yes it helped. But because of other parts of my system use python3 it is essential to make it run. Do you have any ideas what to try?

Also my success with python 2.7 was partial. I got another incompatibility error on next step.
Tried to execute:
```
python match_images.py \
  --image_1_path data/oxford5k_images/hertford_000056.jpg \
  --image_2_path data/oxford5k_images/oxford_000317.jpg \
  --features_1_path data/oxford5k_features/hertford_000056.delf \
  --features_2_path data/oxford5k_features/oxford_000317.delf \
  --output_image matched_images.png
```
With result:
```
INFO:tensorflow:Loaded image 1's 1000 features
INFO:tensorflow:Loaded image 2's 1000 features
INFO:tensorflow:Found 90 inliers
Traceback (most recent call last):
  File "match_images.py", line 141, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/ariel/tensorflow-venv/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "match_images.py", line 86, in main
    img_1 = mpimg.imread(cmd_args.image_1_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/image.py", line 1242, in imread
    im = pilread(fname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/image.py", line 1223, in pilread
    return pil_to_array(image)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/image.py", line 1328, in pil_to_array
    x = toarray(im)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/image.py", line 1313, in toarray
    x_str = im.tostring('raw', im.mode)
  File "/Users/ariel/tensorflow-venv/lib/python2.7/site-packages/PIL/Image.py", line 740, in tostring
    raise NotImplementedError("tostring() has been removed. "
NotImplementedError: tostring() has been removed. Please call tobytes() instead.
```

**Comment by andrefaraujo** [comment]
Great to hear that this worked. I mentioned some Python 3 potential issues here: https://github.com/tensorflow/models/blob/master/research/delf/INSTALL_INSTRUCTIONS.md#troubleshooting

Did you try following the entire installation process using python3? Eg, using pip3 instead of pip, etc

**Comment by Vasay** [comment]
Ok, I will double check it.

It seems like I have a problem deserializing object from the mean.datum file, which is serialized with protobuf. May it be that the object was serialized by python2.7 and because of it, I have problems deserializing it in python3+?

**Comment by andrefaraujo** [comment]
That would be strange, hopefully it's not the case. You can also check https://github.com/google/protobuf/issues to see if they have anything mentioning this, and if not maybe you can post an issue there to clarify?

**Comment by Vasay** [comment]
I've made another attempt on new Ubuntu machine (first try was on MacOS) with no tensorflow previously installed.
I have done all steps exactly like in manual and unfortunately exactly the same error with python3 :(
That's really strange.
Will post smth to https://github.com/google/protobuf/issues now.

**Comment by aosokin** [comment]
Hi @Vasay @andrefaraujo , I confirm the bug.
I've precisely followed the installation process (fresh install on Ubuntu 16.04 and python 3.6) and get
```
INFO:tensorflow:Restoring parameters from b'parameters/delf_v1_20171026/model/variables/variables'
Traceback (most recent call last):
  File "extract_features.py", line 191, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/aosokin/local/software/anaconda3/envs/tensorflow3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "extract_features.py", line 112, in main
    boxes, raw_descriptors, config)
  File "/media/aosokin/kingston2tb/projects/delf-tensorflow/models/research/delf/delf/python/feature_extractor.py", line 360, in DelfFeaturePostProcessing
    config.delf_local_config.pca_parameters.mean_path),
  File "/media/aosokin/kingston2tb/projects/delf-tensorflow/models/research/delf/delf/python/datum_io.py", line 97, in ReadFromFile
    return ParseFromString(f.read())
  File "/home/aosokin/local/software/anaconda3/envs/tensorflow3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 126, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/aosokin/local/software/anaconda3/envs/tensorflow3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 94, in _prepare_value
    return compat.as_str_any(val)
  File "/home/aosokin/local/software/anaconda3/envs/tensorflow3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/home/aosokin/local/software/anaconda3/envs/tensorflow3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 5: invalid start byte
```
exactly as @Vasay

**Comment by davigreen** [comment]
@andrefaraujo Yes we have the same error with python3 on Ubuntu 16.

**Comment by andrefaraujo** [comment]
sorry everyone for the problems with python 3+. Let me investigate what's going on here. I might need to release a new file to be used with python 3, or maybe some code change could help solving the problem.

Please note that everything works with python 2.7, so if you want to make progress while this is being fixed, you can do that...

**Comment by andrefaraujo** [comment]
I think I found what the problem might be. We may simply need to replace `'r'` by `'rb'` in this line: https://github.com/tensorflow/models/blob/master/research/delf/delf/python/datum_io.py#L96

The problem seems to be simply this: https://github.com/tensorflow/tensorflow/issues/11312

Can one of you please try this and let me know if it worked?

**Comment by andrefaraujo** [comment]
Note that we will probably have to do the same edit here: https://github.com/tensorflow/models/blob/master/research/delf/delf/python/feature_io.py#L172, to be able to read features without having the same error.

**Comment by Vasay** [comment]
Thank you!
I confirm: it works.

**Comment by andrefaraujo** [comment]
awesome, will do a PR now to fix this!

**Comment by andrefaraujo** [comment]
https://github.com/tensorflow/models/pull/3324

Closing this issue. But if you have any further problems related to this, feel free to reopen and post here.

**Comment by andrefaraujo** [comment]
oops, just realized I cannot actually close this (?). @reedwm , can you please close this issue?
