### ISSUE TITLE
Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropFilterOp only supports NHWC

### ISSUE THREAD

**Issue by xiongzhp** [tensorflow/models#3304]
This happens when I run the recently released code implementing capsule network https://github.com/Sarasra/models/tree/master/research/capsules
That repo doesn't accept issues and I think the problem comes from tensorflow, so I posted here.
Any help will be appreciated! Thanks!
> WARNING:tensorflow:From experiment.py:330: print_model_analysis (from tensorflow.contrib.tfprof.model_analyzer) is deprecated and will be removed after 2018-01-01.
Instructions for updating:
Use `tf.profiler.profile(graph, run_meta, op_log, cmd, options)`. Build `options` with `tf.profiler.ProfileOptionBuilder`. See README.md for details
230 ops no flops stats due to incomplete shapes.
Parsing Inputs...

=========================Options=============================
-max_depth                  10000
-min_bytes                  0
-min_peak_bytes             0
-min_residual_bytes         0
-min_output_bytes           0
-min_micros                 0
-min_accelerator_micros     0
-min_cpu_micros             0
-min_params                 0
-min_float_ops              0
-min_occurrence             0
-step                       -1
-order_by                   name
-account_type_regexes       _trainable_variables
-start_name_regexes         .*
-trim_name_regexes          
-show_name_regexes          .*
-hide_name_regexes          
-account_displayed_op_only  true
-select                     params
-output                     stdout:

==================Model Analysis Report======================
node name | # parameters
_TFProfRoot (--/8.22m params)
  capsule2 (--/1.47m params)
    capsule2/biases (10x16, 160/160 params)
    capsule2/weights (1152x8x160, 1.47m/1.47m params)
  conv1 (--/20.99k params)
    conv1/biases (256, 256/256 params)
    conv1/weights (9x9x1x256, 20.74k/20.74k params)
  conv_capsule1 (--/5.31m params)
    conv_capsule1/biases (32x8x1x1, 256/256 params)
    conv_capsule1/weights (9x9x256x256, 5.31m/5.31m params)
  recons (--/1.41m params)
    recons/recons_1 (--/82.43k params)
      recons/recons_1/biases (512, 512/512 params)
      recons/recons_1/weights (160x512, 81.92k/81.92k params)
    recons/recons_2 (--/525.31k params)
      recons/recons_2/biases (1024, 1.02k/1.02k params)
      recons/recons_2/weights (512x1024, 524.29k/524.29k params)
    recons/recons_3 (--/803.60k params)
      recons/recons_3/biases (784, 784/784 params)
      recons/recons_3/weights (1024x784, 802.82k/802.82k params)

======================End of Report==========================
total_params: 8215728
  0%|                                                                                            | 0/300000 [00:00<?, ?it/s]2018-02-02 16:33:12.291716: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropFilterOp only supports NHWC.
	 [[Node: tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/conv_capsule1/conv/Reshape, tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/ShapeN:1, tower_0/gradients/tower_0/conv_capsule1/conv/Reshape_1_grad/Reshape)]]

Traceback (most recent call last):
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropFilterOp only supports NHWC.
	 [[Node: tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/conv_capsule1/conv/Reshape, tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/ShapeN:1, tower_0/gradients/tower_0/conv_capsule1/conv/Reshape_1_grad/Reshape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment.py", line 577, in <module>
    tf.app.run()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "experiment.py", line 564, in main
    FLAGS.dataset, FLAGS.validate)
  File "experiment.py", line 335, in train
    max_steps, save_step)
  File "experiment.py", line 289, in run_experiment
    save_step=save_step)
  File "experiment.py", line 183, in train_experiment
    summary, _ = session.run([result.summary, result.train_op])
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropFilterOp only supports NHWC.
	 [[Node: tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/conv_capsule1/conv/Reshape, tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/ShapeN:1, tower_0/gradients/tower_0/conv_capsule1/conv/Reshape_1_grad/Reshape)]]

Caused by op 'tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/Conv2DBackpropFilter', defined at:
  File "experiment.py", line 577, in <module>
    tf.app.run()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "experiment.py", line 564, in main
    FLAGS.dataset, FLAGS.validate)
  File "experiment.py", line 326, in train
    result, _ = model.multi_gpu(features, num_gpus)
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/model.py", line 181, in multi_gpu
    tower_output = self._single_tower(i, features[i])
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/model.py", line 113, in _single_tower
    grads = self._optimizer.compute_gradients(losses)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/nn_grad.py", line 481, in _Conv2DGrad
    data_format)]
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 704, in conv2d_backprop_filter
    use_cudnn_on_gpu=use_cudnn_on_gpu, data_format=data_format, name=name)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'tower_0/conv_capsule1/conv/Conv2D', defined at:
  File "experiment.py", line 577, in <module>
    tf.app.run()
[elided 3 identical lines from previous traceback]
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/model.py", line 181, in multi_gpu
    tower_output = self._single_tower(i, features[i])
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/model.py", line 105, in _single_tower
    inferred = self.inference(feature)
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/capsule_model.py", line 197, in inference
    capsule_output = self._build_capsule(hidden1, features['num_classes'])
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/capsule_model.py", line 65, in _build_capsule
    leaky=self._hparams.leaky,)
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/layers/layers.py", line 322, in conv_slim_capsule
    stride, padding)
  File "/home/deepchem/capsule-model-forked-from-Sarasra/models/layers/layers.py", line 253, in _depthwise_conv3d
    data_format='NCHW')
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Conv2DCustomBackpropFilterOp only supports NHWC.
	 [[Node: tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/conv_capsule1/conv/Reshape, tower_0/gradients/tower_0/conv_capsule1/conv/Conv2D_grad/ShapeN:1, tower_0/gradients/tower_0/conv_capsule1/conv/Reshape_1_grad/Reshape)]]

**Comment by zhaoxin19** [comment]
I meet the same problem with tensorflow1.5. Something should be noticed, that the conv2d op is put on CPU while the code put it on GPU. And the same code can run well on tensorflow 1.4. Looking forward for a solution.

_device="/job:localhost/replica:0/task:0/device:CPU:0"

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by xiaohang96** [comment]
I meet the same problem with tensorflow-gpu1.4, Looking forward for a solution.Thanks!
