### ISSUE TITLE
Randomly crash for GPU OOM error during training for object detection, though use small batch size.

### ISSUE THREAD

**Issue by civilman628** [tensorflow/models#3316]
------------------------

### System information
- **What is the top-level directory of the model you are using**:
/models/research/object_detection/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
 Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.4 GPU
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA 8.0  cuDNN:6
- **GPU model and memory**:
GeForce GTX TITAN X, totalMemory: 11.92GiB freeMemory: 11.80GiB

- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

== cat /etc/issue ===============================================
Linux scopephotos 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.3 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux scopephotos 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.3)
protobuf (3.5.0.post1)
tensorflow-gpu (1.4.1)
tensorflow-tensorboard (0.4.0rc3)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.4.1
tf.GIT_VERSION = v1.4.0-19-ga52c8d9
tf.COMPILER_VERSION = v1.4.0-19-ga52c8d9
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Fri Feb  2 17:05:15 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:05:00.0  On |                  N/A |
| 22%   55C    P0    86W / 250W |    123MiB / 12205MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:06:00.0 Off |                  N/A |
| 22%   56C    P0    91W / 250W |      2MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:09:00.0 Off |                  N/A |
| 22%   48C    P0    86W / 250W |      2MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 22%   37C    P2    70W / 250W |  11747MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1477      G   /usr/lib/xorg/Xorg                           119MiB |
|    0     15876      G   /usr/bin/nvidia-settings                       0MiB |
|    3      6844      C   python                                     11735MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudart-5d6d23a3.so.8.0.61
/usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
/usr/local/cuda-8.0/lib64/libcudart_static.a
/usr/local/cuda-8.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-8.0/doc/man/man7/libcudart.7

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
'v1.4.0-19-ga52c8d9', '1.4.1'

### Describe the problem
training object detection model: ssd_mobilenet_v1   meet OOM error of GPU, I reduce the number of batch size, but useless. Large batch size (default 24 ) will crash early, after about 300 steps. Small batch size=16 will crash later, like 600 steps.  

### Source code / logs

WARNING:tensorflow:From ../object_detection/trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
2018-02-02 16:59:44.774125: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-02 16:59:45.101562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.2155
pciBusID: 0000:06:00.0
totalMemory: 11.92GiB freeMemory: 11.80GiB
2018-02-02 16:59:45.101595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0, compute capability: 5.2)
INFO:tensorflow:Restoring parameters from ./fashion_checkpoint/model.ckpt-0
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path ./fashion_checkpoint/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Recording summary at step 0.
**INFO:tensorflow:global step 1: loss = 35.1448 (15.144 sec/step)
INFO:tensorflow:global step 2: loss = 34.5482 (2.441 sec/step)**
2018-02-02 17:01:02.690697: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.98GiB.  Current allocation summary follows.
2018-02-02 17:01:02.690759: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (256): 	Total Chunks: 915, Chunks in use: 913. 228.8KiB allocated for chunks. 228.2KiB in use in bin. 10.3KiB client-requested in use in bin.
2018-02-02 17:01:02.690771: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (512): 	Total Chunks: 24, Chunks in use: 14. 12.0KiB allocated for chunks. 7.0KiB in use in bin. 7.0KiB client-requested in use in bin.
2018-02-02 17:01:02.690779: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (1024): 	Total Chunks: 18, Chunks in use: 17. 19.0KiB allocated for chunks. 17.8KiB in use in bin. 17.3KiB client-requested in use in bin.
2018-02-02 17:01:02.690788: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (2048): 	Total Chunks: 31, Chunks in use: 30. 66.0KiB allocated for chunks. 63.5KiB in use in bin. 63.2KiB client-requested in use in bin.
2018-02-02 17:01:02.690795: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (4096): 	Total Chunks: 394, Chunks in use: 393. 2.85MiB allocated for chunks. 2.85MiB in use in bin. 2.84MiB client-requested in use in bin.
2018-02-02 17:01:02.690803: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (8192): 	Total Chunks: 9, Chunks in use: 9. 87.5KiB allocated for chunks. 87.5KiB in use in bin. 83.5KiB client-requested in use in bin.
2018-02-02 17:01:02.690811: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (16384): 	Total Chunks: 22, Chunks in use: 22. 471.8KiB allocated for chunks. 471.8KiB in use in bin. 467.9KiB client-requested in use in bin.
 
...
...
...

2018-02-02 17:01:03.001726: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 1 Chunks of size 3145728 totalling 3.00MiB
2018-02-02 17:01:03.001731: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 2 Chunks of size 4194304 totalling 8.00MiB
2018-02-02 17:01:03.001738: I tensorflow/core/common_runtime/bfc_allocator.cc:679] 2 Chunks of size 4718592 totalling 9.00MiB
2018-02-02 17:01:03.001744: I tensorflow/core/common_runtime/bfc_allocator.cc:683] Sum Total of in-use chunks: 60.28MiB
2018-02-02 17:01:03.001753: I tensorflow/core/common_runtime/bfc_allocator.cc:685] Stats: 
Limit:                 12041302836
InUse:                    63212032
MaxInUse:               8206210816
NumAllocs:                   19700
MaxAllocSize:           4294967296

2018-02-02 17:01:03.001834: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *___________________________________________________________________________________________________
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, Dst tensor is not initialized.
	 [[Node: prefetch_queue_Dequeue/_4113 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_838_prefetch_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
Traceback (most recent call last):
  **File "train_fashion.py", line 171, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_fashion.py", line 167, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "../object_detection/trainer.py", line 333, in train
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 763, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 487, in train_step
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[Node: prefetch_queue_Dequeue/_4113 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_838_prefetch_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
scopeserver@scopephotos:~/RaidDisk/DeepLearning/mwang/models/research/object_detection$**

**Comment by civilman628** [comment]
I set batch size = 8, but it still crash. This is not normal.

**Comment by civilman628** [comment]
I meet this issue today again, after training for 17825 steps. It says: ran out of memory trying to allocate 4.42GiB

i am very curious about why it try to allocate  4.42GiB memory. 17825 steps already repeat many epochs. The peak memory demand  should already happen very long time ago, especially at the beginning when training start. And it becomes to demand such a large amount memory later... does not make sense.


INFO:tensorflow:global step 17815: loss = 4.2434 (0.539 sec/step)
INFO:tensorflow:global step 17816: loss = 5.2405 (0.531 sec/step)
INFO:tensorflow:global step 17817: loss = 3.2369 (0.563 sec/step)
INFO:tensorflow:global step 17818: loss = 3.8381 (0.542 sec/step)
INFO:tensorflow:global step 17819: loss = 6.1966 (0.729 sec/step)
INFO:tensorflow:global step 17820: loss = 5.2233 (0.548 sec/step)
INFO:tensorflow:global step 17821: loss = 3.9810 (0.619 sec/step)
INFO:tensorflow:global step 17822: loss = 4.9960 (0.640 sec/step)
INFO:tensorflow:global step 17823: loss = 3.5530 (0.498 sec/step)
INFO:tensorflow:global step 17824: loss = 3.8853 (0.529 sec/step)
INFO:tensorflow:global step 17825: loss = 4.2335 (0.543 sec/step)
**2018-02-05 13:11:25.666037: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.42GiB.  Current allocation summary follows.**
2018-02-05 13:11:25.666151: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (256): 	Total Chunks: 356, Chunks in use: 337. 89.0KiB allocated for chunks. 84.2KiB in use in bin. 5.6KiB client-requested in use in bin.
2018-02-05 13:11:25.666178: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (512): 	Total Chunks: 30, Chunks in use: 14. 16.2KiB allocated for chunks. 7.2KiB in use in bin. 7.0KiB client-requested in use in bin.
2018-02-05 13:11:25.666199: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (1024): 	Total Chunks: 19, Chunks in use: 17. 20.0KiB allocated for chunks. 17.8KiB in use in bin. 17.3KiB client-requested in use in bin.
2018-02-05 13:11:25.666219: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (2048): 	Total Chunks: 30, Chunks in use: 30. 63.5KiB allocated for chunks. 63.5KiB in use in bin. 63.2KiB client-requested in use in bin.
2018-02-05 13:11:25.666238: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (4096): 	Total Chunks: 10, Chunks in use: 10. 42.0KiB allocated for chunks. 42.0KiB in use in bin. 42.0KiB client-requested in use in bin.
2018-02-05 13:11:25.666257: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (8192): 	Total Chunks: 8, Chunks in use: 8. 76.0KiB allocated for chunks. 76.0KiB in use in bin. 76.0KiB client-requested in use in bin.
2018-02-05 13:11:25.666274: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (16384): 	Total Chunks: 116, Chunks in use: 116. 2.02MiB allocated for chunks. 2.02MiB in use in bin. 2.00MiB client-requested in use in bin.
2018-02-05 13:11:25.666294: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (32768): 	Total Chunks: 12, Chunks in use: 12. 520.0KiB allocated for chunks. 520.0KiB in use in bin. 520.0KiB client-requested in use in bin.
2018-02-05 13:11:25.666314: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (65536): 	Total Chunks: 10, Chunks in use: 10. 777.0KiB allocated for chunks. 777.0KiB in use in bin. 777.0KiB client-requested in use in bin.
2018-02-05 13:11:25.666332: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (131072): 	Total Chunks: 16, Chunks in use: 16. 2.20MiB allocated for chunks. 2.20MiB in use in bin. 2.16MiB client-requested in use in bin.
2018-02-05 13:11:25.666349: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (262144): 	Total Chunks: 8, Chunks in use: 7. 2.13MiB allocated for chunks. 1.86MiB in use in bin. 1.75MiB client-requested in use in bin.
2018-02-05 13:11:25.666367: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (524288): 	Total Chunks: 6, Chunks in use: 6. 3.14MiB allocated for chunks. 3.14MiB in use in bin. 3.14MiB client-requested in use in bin.
2018-02-05 13:11:25.666386: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (1048576): 	Total Chunks: 20, Chunks in use: 19. 22.33MiB allocated for chunks. 20.69MiB in use in bin. 19.71MiB client-requested in use in bin.
2018-02-05 13:11:25.666404: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (2097152): 	Total Chunks: 2, Chunks in use: 2. 4.93MiB allocated for chunks. 4.93MiB in use in bin. 4.00MiB client-requested in use in bin.
2018-02-05 13:11:25.666423: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (4194304): 	Total Chunks: 5, Chunks in use: 4. 24.69MiB allocated for chunks. 17.00MiB in use in bin. 17.00MiB client-requested in use in bin.
2018-02-05 13:11:25.666440: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-05 13:11:25.666457: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-05 13:11:25.666473: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-05 13:11:25.666490: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (67108864): 	Total Chunks: 1, Chunks in use: 0. 64.00MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-05 13:11:25.666510: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (134217728): 	Total Chunks: 1, Chunks in use: 0. 128.00MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-05 13:11:25.666527: I tensorflow/core/common_runtime/bfc_allocator.cc:627] Bin (268435456): 	Total Chunks: 5, Chunks in use: 0. 8.25GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-02-05 13:11:25.666544: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin for 4.42GiB was 256.00MiB, Chunk State: 
2018-02-05 13:11:25.666565: I tensorflow/core/common_runtime/bfc_allocator.cc:649]   Size: 256.00MiB | Requested Size: 49.44MiB | in_use: 0
2018-02-05 13:11:25.666583: I tensorflow/core/common_runtime/bfc_allocator.cc:649]   Size: 1.00GiB | Requested Size: 49.44MiB | in_use: 0
2018-02-05 13:11:25.666599: I tensorflow/core/common_runtime/bfc_allocator.cc:649]   Size: 1.00GiB | Requested Size: 25.38MiB | in_use: 0
2018-02-05 13:11:25.666614: I tensorflow/core/common_runtime/bfc_allocator.cc:649]   Size: 2.00GiB | Requested Size: 1.29GiB | in_use: 0
2018-02-05 13:11:25.666629: I tensorflow/core/common_runtime/bfc_allocator.cc:649]   Size: 4.00GiB | Requested Size: 2.15GiB | in_use: 0
2018-02-05 13:11:25.666645: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0x230a300000 of size 1280
2018-02-05 13:11:25.666659: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0x230a300500 of size 256
2018-02-05 13:11:25.666671: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0x230a300600 of size 256
2018-02-05 13:11:25.666683: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0x230a300700 of size 256
2018-02-05 13:11:25.666695: I tensorflow/core/common_runtime/bfc_allocator.cc:661] Chunk at 0x230a300800 of size 256

**Comment by civilman628** [comment]
I update to TF 1.5, CUDA 9.0, cuDNN 7 still meet the same issue. It crashes after some training steps when trying to allocate 4.8Gib memory. it is not normal that current TF session tries to allocate such a large amount memory after many training steps.

**Comment by civilman628** [comment]
no one look into this bug?

**Comment by pujoseno** [comment]
yes, we have same error but i'dont no to fixed this bug.

**Comment by dextroza** [comment]
I cannot even continue to train ssd_mobilenet_v2_coco on COCO dataset. Tried to reduce batch_size to 8, but didn't help. I have TF 1.6, GTX 1080 Ti with 11GB, cuda 9.0. The error is:
":tensorflow:Starting Queues.
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Error reported to Coordinator: Dst tensor is not initialized. 
....
"

**Comment by sdy1106** [comment]
I have the same bug, @civilman628  do you have any way to solve it?

**Comment by MrWanter** [comment]
same bug here, dont the reason, see my post https://github.com/tensorflow/models/issues/4994

**Comment by u10116032** [comment]
@civilman628 
Same issue here, do you have any solution?
Thanks in advance!

**Comment by civilman628** [comment]
@u10116032 木有

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by civilman628** [comment]
the issue is still there.

**Comment by Adrian-Fleck** [comment]
The Error ist also There for me

**Comment by tilakrayal** [comment]
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!

**Comment by Kia4631** [comment]
I'm experiencing the same issue with Tensorflow 2.7.
When it crashed after some epochs for the first time, I re-ran the training command without any changes and it went for more steps. Then it crashed again! Now I'm adding this **"TF_GPU_ALLOCATOR=cuda_malloc_async"** to my training command as  Tensorflow has suggested in the error.
I'll update here if it doesn't crash again!
