### ISSUE TITLE
export_training fails 'ValueError: 'images' must have either 3 or 4 dimensions.'

### ISSUE THREAD

**Issue by ckalas** [tensorflow/models#3328]
Python 3.5, TF 1.4.1, Ubuntu 16.04.

I am trying to export a model using the command `python3 export_inference_graph.py --pipeline_config_path=configs/ssd_inception_v2_cool_model.config --checkpoint_path=cool_model/model.ckpt-37605.data-00000-of-00001 --inference_graph_path=./ --export_as_saved_model --input_type=image_tensor`

I copied the export_inference_graph.py script to the directory in which I train so I don't need to run from the /models directory.

The full traceback is:

`Traceback (most recent call last):
  File "export_inference_graph.py", line 113, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "export_inference_graph.py", line 109, in main
    FLAGS.model_version)
  File "/home/dbc/models/research/object_detection/exporter.py", line 428, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "/home/dbc/models/research/object_detection/exporter.py", line 352, in _export_inference_graph
    preprocessed_inputs = detection_model.preprocess(inputs)
  File "/home/dbc/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 232, in preprocess
    dtype=tf.float32)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2816, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2640, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2590, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "/home/dbc/models/research/object_detection/core/preprocessor.py", line 1871, in resize_image
    align_corners=align_corners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 748, in resize_images
    raise ValueError('\'images\' must have either 3 or 4 dimensions.')
ValueError: 'images' must have either 3 or 4 dimensions.
`

**Comment by aldrin233** [comment]
Try putting export_inference_graph back to the original directory then run from there. Looking at my files, i try to run export_inference_graph.py in its original directory.

**Comment by ckalas** [comment]
@aldrin233 it works from that directory! i had got it to export last year from another directory by copying files, i guess they changed stuff. the error i was getting though was not indicative of the problem at all which is difficult.

**Comment by trc2019** [comment]
I have the same problem
