### ISSUE TITLE
Error when trying to use faster rcnn nas 

### ISSUE THREAD

**Issue by JayJoeSeventh** [tensorflow/models#3337]
I have successfully use ssd mobilenet to train a custom object detection model. But when I am trying to use faster rcnn nas model, I am getting this error:

Traceback (most recent call last):
  File "train.py", line 168, in <module>
    tf.app.run()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 164, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\Asus\Desktop\Types of Training Approaches\2. Faster R-CNN NAS\T
rain !\Training\trainer.py", line 202, in train
    detection_model = create_model_fn()
  File "C:\Users\Asus\Desktop\Types of Training Approaches\2. Faster R-CNN NAS\T
rain !\Training\builders\model_builder.py", line 108, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\Asus\Desktop\Types of Training Approaches\2. Faster R-CNN NAS\T
rain !\Training\builders\model_builder.py", line 350, in _build_faster_rcnn_mode
l
    **common_kwargs)
  File "C:\Users\Asus\Desktop\Types of Training Approaches\2. Faster R-CNN NAS\T
rain !\Training\meta_architectures\faster_rcnn_meta_arch.py", line 339, in __ini
t__
    raise ValueError('second_stage_batch_size should be no greater than '
ValueError: second_stage_batch_size should be no greater than first_stage_max_pr
oposals.

Help? :[ Second batch size should ne no greater than first stage max proposals?

FYI, my training images are all less than 800 x 800 pix.

**Comment by ZER-0-NE** [comment]
@JayJoeSeventh You can refer to the issue #2668

**Comment by JayJoeSeventh** [comment]
@ZER-0-NE Thanks ! :)

**Comment by zeynali** [comment]
@JayJoeSeventh , Hi , are you try to fine-tune this model ?
