### ISSUE TITLE
Bug in beginners tutorial using premade_estimator.py

### ISSUE THREAD

**Issue by muhammedchand** [tensorflow/models#3345]
### System information
- **What is the top-level directory of the model you are using**:
 C:\Python3\Lib\site-packages\tensorflow\models\samples\core\get_started
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.5.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
V8.0.60
- **GPU model and memory**:
GT635m 4GB
- **Exact command to reproduce**:
python3 premade_estimator.py

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
When parsing the host variable in client.py the variable returned conatins a trailing semi-colon resulting in the port number reasiing an error since it's taken as a literal:
 " ValueError: invalid literal for int() with base 10: '3128;' "
### Source code / logs
```
   C:\Python3\Lib\site-packages\tensorflow\models\samples\core\get_started>py premade_estimator.py
    Downloading data from http://download.tensorflow.org/data/iris_training.csv
    Traceback (most recent call last):
      File "C:\Python3\lib\http\client.py", line 798, in _get_hostport
        port = int(host[i+1:])
    ValueError: invalid literal for int() with base 10: '3128;'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "premade_estimator.py", line 88, in <module>
        tf.app.run(main)
      File "C:\Python3\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
        _sys.exit(main(argv))
      File "premade_estimator.py", line 34, in main
        (train_x, train_y), (test_x, test_y) = iris_data.load_data()
      File "C:\Python3\Lib\site-packages\tensorflow\models\samples\core\get_started\iris_data.py", line 19, in load_data
        train_path, test_path = maybe_download()
      File "C:\Python3\Lib\site-packages\tensorflow\models\samples\core\get_started\iris_data.py", line 12, in maybe_download
        train_path = tf.keras.utils.get_file(TRAIN_URL.split('/')[-1], TRAIN_URL)
      File "C:\Python3\lib\site-packages\tensorflow\python\keras\_impl\keras\utils\data_utils.py", line 238, in get_file
        urlretrieve(origin, fpath, dl_progress)
      File "C:\Python3\lib\urllib\request.py", line 188, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "C:\Python3\lib\urllib\request.py", line 163, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Python3\lib\urllib\request.py", line 466, in open
        response = self._open(req, data)
      File "C:\Python3\lib\urllib\request.py", line 484, in _open
        '_open', req)
      File "C:\Python3\lib\urllib\request.py", line 444, in _call_chain
        result = func(*args)
      File "C:\Python3\lib\urllib\request.py", line 1282, in http_open
        return self.do_open(http.client.HTTPConnection, req)
      File "C:\Python3\lib\urllib\request.py", line 1223, in do_open
        h = http_class(host, timeout=req.timeout, **http_conn_args)
      File "C:\Python3\lib\http\client.py", line 762, in __init__
        (self.host, self.port) = self._get_hostport(host, port)
      File "C:\Python3\lib\http\client.py", line 803, in _get_hostport
        raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
    http.client.InvalidURL: nonnumeric port: '3128;'

```

**Comment by skye** [comment]
@nealwu is this your jurisdiction?

**Comment by nealwu** [comment]
The samples folder is @MarkDaoust

(FYI you can check [CODEOWNERS](https://github.com/tensorflow/models/blob/master/CODEOWNERS) to see who to assign issues to)

**Comment by MarkDaoust** [comment]
Interesting, I can't reproduce this. 

It looks like the error is coming from farther down the stack. Which version of python are you using?:

```
import sys
sys.version
```

**Comment by muhammedchand** [comment]
Im runnig 3.5.2 but I just re-ran the script and had no problems. My guess is it was a a weird networking issue that blocked the port. Didn't change anything but it's working fine now. Possible solution may be just resetting your router if anyone see's this.
