### ISSUE TITLE
bugs in faster_rcnn_meta_arch_test_lib.py

### ISSUE THREAD

**Issue by Shirhe-Lyh** [tensorflow/models#3356]
When I was runing the module faster_rcnn_meta_arch_test_lib.py in ubuntu16.04:

#From object_detection/meta_architectures
$ python3 faster_rcnn_meta_arch_test_lib.py

I got 3 errors listed as following:

======================================================================
ERROR: test_loss_with_hard_mining (__main__.FasterRCNNMetaArchTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "faster_rcnn_meta_arch_test_lib.py", line 1095, in test_loss_with_hard_mining
    hard_mining=True)
  File "faster_rcnn_meta_arch_test_lib.py", line 236, in _build_model
    num_classes=num_classes, is_training=is_training), **common_kwargs)
  File "faster_rcnn_meta_arch_test_lib.py", line 108, in _get_model
    **common_kwargs)
  File "/home/shirhe-lyh/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 325, in __init__
    if is_training and second_stage_batch_size > first_stage_max_proposals:
TypeError: unorderable types: NoneType() > int()

======================================================================
ERROR: test_predict_correct_shapes_in_inference_mode_both_stages (__main__.FasterRCNNMetaArchTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "faster_rcnn_meta_arch_test_lib.py", line 375, in test_predict_correct_shapes_in_inference_mode_both_stages
    self._get_box_classifier_features_shape(image_size,
AttributeError: 'FasterRCNNMetaArchTestBase' object has no attribute '_get_box_classifier_features_shape'

======================================================================
ERROR: test_predict_gives_correct_shapes_in_train_mode_both_stages (__main__.FasterRCNNMetaArchTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "faster_rcnn_meta_arch_test_lib.py", line 438, in test_predict_gives_correct_shapes_in_train_mode_both_stages
    self._get_box_classifier_features_shape(image_size,
AttributeError: 'FasterRCNNMetaArchTestBase' object has no attribute '_get_box_classifier_features_shape'

----------------------------------------------------------------------
Ran 17 tests in 26.742s

FAILED (errors=3)

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
