### ISSUE TITLE
Type error upon first running

### ISSUE THREAD

**Issue by Josh-Payne** [tensorflow/models#3361]
Came across an interesting type error when running `$ python mnist.py ` right after downloading the models repository. Here are the details: 

```
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x11667a710>, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_master': '', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_model_dir': '/tmp/mnist_model', '_save_summary_steps': 100}
Traceback (most recent call last):
  File "mnist.py", line 261, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/joshpayne1/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "mnist.py", line 193, in main
    mnist_classifier.train(input_fn=train_input_fn, hooks=[logging_hook])
  File "/Users/joshpayne1/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/joshpayne1/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/Users/joshpayne1/miniconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "mnist.py", line 104, in model_fn
    logits = model(image, training=True)
  File "mnist.py", line 67, in __call__
    y = tf.reshape(inputs, self._input_shape)
  File "/Users/joshpayne1/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/Users/joshpayne1/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
TypeError: Failed to convert object of type <class 'tensorflow.python.data.ops.dataset_ops.RepeatDataset'> to Tensor. Contents: <RepeatDataset shapes: ((?, 784), (?,)), types: (tf.float32, tf.int32)>. Consider casting elements to a supported type.

```
MacOS 10.13.2, version of Tensorflow: ('v1.4.0-19-ga52c8d9b01', '1.4.1'). Installed from the source, no custom code written.

**Comment by meyougonglv** [comment]
i've got the same error, have u solved it ?

**Comment by Josh-Payne** [comment]
Unfortunately not...I ended up just using an older version of the repository
