### ISSUE TITLE
Troubles computing evaluation measures via offline_eval_map_corloc.py

### ISSUE THREAD

**Issue by tureckova** [tensorflow/models#3377]
### System information
- **What is the top-level directory of the model you are using:** research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Win 10, version 1709, 64-bit
- **TensorFlow installed from (source or binary):** source
- **TensorFlow version (use command below):** 1.4.0
- **CUDA/cuDNN version:** -
- **GPU model and memory:** -
- **Exact command to reproduce:**
python object_detection/metrics/offline_eval_map_corloc.py --eval_dir=C:/Users/Uzivatel/Documents/projects/Doggie_smile/dog-face-detector/models/model9/eval/validation_eval_metric --eval_config_path=C:/Users/Uzivatel/Documents/projects/Doggie_smile/dog-face-detector/models/model9/eval/validation_eval_metric/validation_eval_config.pbtxt --input_config_path=C:/Users/Uzivatel/Documents/projects/Doggie_smile/dog-face-detector/models/model9/eval/validation_eval_metric/validation_input_config.pbtxt

### Describe the problem
I would like to evaluate my detector and find the AP, preferably using the pascal_voc_metrics. I followed the nice tutorial [Inference and evaluation on the Open Images dataset](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/oid_inference_and_evaluation.md). I managed to infer the detections and export TFRecord file, but when I tried to compute evaluation measures I get an error while reading config files.
I provide my TFRecord as well as my config files.
[eval.zip](https://github.com/tensorflow/models/files/1721930/eval.zip)

What I did wrong?
Any help would be appreciated.
Thank you.

### Error message I got
Traceback (most recent call last):
  File "../object_detection/metrics/offline_eval_map_corloc.py", line 173, in <module>
    tf.app.run(main)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "../object_detection/metrics/offline_eval_map_corloc.py", line 161, in main
    eval_config_path=FLAGS.eval_config_path)
  File "C:\Users\Uzivatel\Documents\tensorflow\models\research\object_detection\utils\config_util.py", line 118, in get_configs_from_multiple_files
    text_format.Merge(f.read(), eval_config)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 679, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 1152, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
google.protobuf.text_format.ParseError: 1:1 : Expected identifier or number, got ﻿.

**Comment by vlachynska** [comment]
I've tested the same thing on **Linux** system: **Debian Stretch**. Still **TensorFlow version 1.4.0**. 
I've generated the TFRecord as well as my config files on this system and ended up with the same error message. Has anyone the same troubles?

**Comment by vlachynska** [comment]
#

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
