### ISSUE TITLE
I can't train, how to code with the problem, I have tried many times.

### ISSUE THREAD

**Issue by wanghuite** [tensorflow/models#3538]
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "C:\Users\as\AppData\Local\conda\conda\envs\kate\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "D:\as\models\research\object_detection\trainer.py", line 235, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "D:\as\models\research\object_detection\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 120, in get_next
    dataset_builder.build(config)).get_next()
  File "D:\as\models\research\object_detection\builders\dataset_builder.py", line 138, in build
    label_map_proto_file=label_map_proto_file)
  File "D:\as\models\research\object_detection\data_decoders\tf_example_decoder.py", line 110, in __init__
    dct_method=dct_method),
TypeError: __init__() got an unexpected keyword argument 'dct_method'

**Comment by Shirhe-Lyh** [comment]
Hello, wanghuite. I got a simple but not elegent solution to this problem. You can remove the argument 'dct_method' in __init__(..., dct_method='') and in line 110 in the file tf_example_decoder.py.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
