### ISSUE TITLE
Object Detection: an unexpected keyword argument 'groundtruth_is_difficult_list'

### ISSUE THREAD

**Issue by rohitkharanghar** [tensorflow/models#3554]
### System information
- **Have I written custom code - No**
- **OS Platform and Distribution-Ubuntu 16.04)**
- **TensorFlow installed from binary**:
- **TensorFlow version **:1.4.1
- **CUDA/cuDNN version**:8.0/6.0
- **GPU model and memory**:NVIDIA Corporation Device 1b80 and 8GB
- **Exact command to reproduce**:python eval.py --logtostderr --checkpoint_dir=training/ --pipeline_config_path=training/faster_rcnn_resnet101_coco.config --eval_dir=evaluation_dir/

I am getting following error:
`WARNING:root:image 0 does not have groundtruth difficult flag specified
WARNING:root:The following classes have no ground truth examples: [3 4 7]
/data/rsk/models1/models/research/object_detection/utils/metrics.py:144: RuntimeWarning: invalid value encountered in true_divide
  num_images_correctly_detected_per_class / num_gt_imgs_per_class)
Traceback (most recent call last):
  File "eval.py", line 137, in <module>
    tf.app.run()
  File "/data/rsk/anaconda3/envs/tfod/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 133, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/data/rsk/models1/models/research/object_detection/evaluator.py", line 210, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/data/rsk/models1/models/research/object_detection/eval_util.py", line 381, in repeated_checkpoint_run
    save_graph_dir)
  File "/data/rsk/models1/models/research/object_detection/eval_util.py", line 271, in _run_checkpoint_once
    image_id=batch, detections_dict=result_dict)
  File "/data/rsk/models1/models/research/object_detection/utils/object_detection_evaluation.py", line 250, in add_single_detected_image_info
    detected_masks=detection_masks)
  File "/data/rsk/models1/models/research/object_detection/utils/object_detection_evaluation.py", line 622, in add_single_detected_image_info
    groundtruth_masks=groundtruth_masks))
TypeError: compute_object_detection_metrics() got an unexpected keyword argument 'groundtruth_is_difficult_list'`
Help please.

**Comment by pkulzc** [comment]
Could you please sync to HEAD and try again?

**Comment by hoshii77** [comment]
i have the same warning,have you solved this problem? Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
