### ISSUE TITLE
Drawing Classifier

### ISSUE THREAD

**Issue by aqsasamreen** [tensorflow/models#3582]
I am facing an error when running the train.py code for training and evaluate Quickdraw model.
2018-03-13 22:03:48.821192: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
2018-03-13 22:04:11.623656: W C:\tf_jenkins\workspace\rel-win\M\windows\PY\35\tensorflow\core\framework\op_kernel.cc:1198] Out of range: Attempted to repeat an empty dataset infinitely.
2018-03-13 22:04:34.399568: W C:\tf_jenkins\workspace\rel-win\M\windows\PY\35\tensorflow\core\framework\op_kernel.cc:1198] Out of range: Attempted to repeat an empty dataset infinitely.
2018-03-13 22:05:04.193623: W C:\tf_jenkins\workspace\rel-win\M\windows\PY\35\tensorflow\core\framework\op_kernel.cc:1198] Out of range: Attempted to repeat an empty dataset infinitely.
WARNING:tensorflow:No new checkpoint ready for evaluation. Skip the current evaluation pass as evaluation results are expected to be same for the same checkpoint.
Traceback (most recent call last):
  File "D:/ FYP/draw/model_train.py", line 370, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Aqsa\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "D:/ FYP/draw/model_train.py", line 282, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "C:\Users\Aqsa\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\training.py", line 432, in train_and_evaluate
    executor.run_local()
  File "C:\Users\Aqsa\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\training.py", line 622, in run_local
    raise RuntimeError('There was no new checkpoint after the training.')
RuntimeError: There was no new checkpoint after the training.

Process finished with exit code 1

**Comment by Bhavyabhushanyadav** [comment]
I get the same error when running a job on cloud ml engine, but the code works fine on my local machine.

**Comment by yuq-1s** [comment]
I went into this error today. It turns out that I did not set global_step in optimizer.minimize function.

**Comment by harshini-gadige** [comment]
@aqsasamreen Hi, are you still getting the error ?

**Comment by wt-huang** [comment]
Closing as this is resolved
