### ISSUE TITLE
TypeError: Expected string, got dict_keys in astronet model

### ISSUE THREAD

**Issue by KhaledSharif** [tensorflow/models#3608]
### System information
- **What is the top-level directory of the model you are using**: `models/research/astronet`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Below
- **TensorFlow version (use command below)**: Below
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `python3.5 train.py`

```
> python3.5 -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.4.0-19-ga52c8d9 1.4.1
```

### Error trace
In line 187 of [this file](https://github.com/tensorflow/models/blob/master/research/astronet/astronet/ops/dataset_ops.py#L187), the command below will raise the following error:

```python
table_initializer = tf.contrib.lookup.KeyValueTensorInitializer(
        keys=input_config.label_map.keys(),
        values=input_config.label_map.values(),
        key_dtype=tf.string,
        value_dtype=tf.int32)
```

```
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 114, in main
    train_steps=FLAGS.train_steps):
  File "/media/khaled/thor/PycharmProjects/astronet-kepler/util/estimator_util.py", line 322, in continuous_train_and_eval
    estimator.train(train_input_fn, hooks=train_hooks, steps=steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 708, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 577, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 663, in _call_input_fn
    return input_fn(**kwargs)
  File "/media/khaled/thor/PycharmProjects/astronet-kepler/util/estimator_util.py", line 71, in input_fn
    use_tpu=use_tpu)
  File "/media/khaled/thor/PycharmProjects/astronet-kepler/ops/dataset_ops.py", line 206, in build_dataset
    value_dtype=tf.int32)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/lookup_ops.py", line 325, in __init__
    self._keys = ops.convert_to_tensor(keys, dtype=key_dtype, name="keys")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 836, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 383, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 303, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected string, got dict_keys(['NTP', 'PC', 'AFP']) of type 'dict_keys' instead.

```

### How to fix
A simple change to something compatible with [this breaking change](https://stackoverflow.com/questions/8953627/python-dictionary-keys-error) from Python 2 to Python 3. There are also many references to `iteritems` which I changed to `items` to get compatibility too.

```python
table_initializer = tf.contrib.lookup.KeyValueTensorInitializer(
            keys=list(input_config.label_map.keys()),
            values=list(input_config.label_map.values()),
            key_dtype=tf.string,
            value_dtype=tf.int32)
```

### People of interest
@cshallue

**Comment by cshallue** [comment]
Thanks for bringing this to my attention! I'll send a fix shortly.

**Comment by cshallue** [comment]
Fixed! Please let me know if you encounter any further issues.
