### ISSUE TITLE
how to prepare labelmap.pbtxt

### ISSUE THREAD

**Issue by pandasMX** [tensorflow/models#3624]
Hi, I'm training on my own dataset, so i need to generate my own labelmap.pbtxt. The code i used to generate it is as below. It seems to be fine during training. 
```
file = pd.read_csv(filename,header=None)
categories = file[5].unique()
end = '\n'
s = ' '
class_map = {}
for ID, name in enumerate(categories):
    out = ''
    out += 'item' + s + '{' + end
    out += s*2 + 'id:' + ' ' + (str(ID+1)) + end
    out += s*2 + 'name:' + ' ' + '\'' + name + '\'' + end
    out += '}' + end*2
    

    with open(output_name, 'a') as f:
        f.write(out)
        
    class_map[name] = ID+1
```

the final output looks like this:
```
item {
  id: 1
  name: 'apple'
}

item {
  id: 2
  name: 'banana'
}
```

However, when i run eval.py, it gave me an error: 
```
  File "object_detection/eval.py", line 133, in <module>
    tf.app.run()
  File "/home/user/virenv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/eval.py", line 120, in main
    label_map = label_map_util.load_labelmap(input_config.label_map_path)
  File "/data/input_prep/models/research/object_detection/utils/label_map_util.py", line 122, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'
```
Is it because the pbtxt i generated not correct? If so, why the training seems to be ok. And what's the correct way to generate the labelmap.pbtxt? Thanks!

**Comment by pkulzc** [comment]
Training process may not use label maps in some cases. This looks more like a python file reading issue. Your can try using 'rb' mode [here](https://github.com/tensorflow/models/blob/master/research/object_detection/utils/label_map_util.py#L128)

**Comment by pandasMX** [comment]
Hi, I tried to 'rb', but a new error pop up.
```
/research$ python object_detection/eval.py --logtostderr --pipeline_config_path=/home/user/ssd/ssd_mobilenet_v1_coco.config --checkpoint_dir=/home/user/ssd/training_checkpoints --eval_dir=/home/user/ssd/evaluation_checkpoints

/home/user/models/research/object_detection/utils/label_map_util.py:122: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  label_map.ParseFromString(label_map_string)
Traceback (most recent call last):
  File "object_detection/eval.py", line 133, in <module>
    tf.app.run()
  File "/home/user/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/eval.py", line 121, in main
    max_num_classes = max([item.id for item in label_map.item])
ValueError: max() arg is an empty sequence
```

**Comment by pandasMX** [comment]
I found the reason. That's because one of my label name is like 'men's_wear' where there's a ' inside.
