### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError: flag --tf_initial_checkpoint=None: Flag --tf_initial_checkpoint must be specified.

### ISSUE THREAD

**Issue by betterhalfwzm** [tensorflow/models#3628]
python deeplab/train.py \
>     --logtostderr \
>     --training_number_of_steps=30000 \
>     --train_split="train" \
>     --model_variant="xception_65" \
>     --atrous_rates=6 \
>     --atrous_rates=12 \
>     --atrous_rates=18 \
>     --output_stride=16 \
>     --decoder_output_stride=4 \
>     --train_crop_size=513 \
>     --train_crop_size=513 \
>     --train_batch_size=1 \
>     --dataset="pascal_voc_seg" \
>     --tf_initial_checkpoints="/home/tjpu/models/research/deeplab/result/tf_initial_checkpoints/xception\model.ckpt.index" \
>     --dataset_dir="/home/tjpu/models/research/deeplab/datasets/pascal_voc_seg/tfrecord"
Traceback (most recent call last):
  File "deeplab/train.py", line 347, in <module>
    tf.app.run()
  File "/home/tjpu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 120, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/home/tjpu/.local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/home/tjpu/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 633, in __call__
    self._assert_all_validators()
  File "/home/tjpu/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 507, in _assert_all_validators
    self._assert_validators(all_validators)
  File "/home/tjpu/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 528, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --tf_initial_checkpoint=None: Flag --tf_initial_checkpoint must be specified.

**Comment by betterhalfwzm** [comment]
tf_initial_checkpoint= not  tf_initial_checkpoints=

**Comment by LamboAventador** [comment]
@betterhalfwzm I got the same problem, did you solve it?

**Comment by betterhalfwzm** [comment]
@LamboAventador tf_initial_checkpoint= not tf_initial_checkpoints=
