### ISSUE TITLE
[deeplab] the tensorflow version?

### ISSUE THREAD

**Issue by shipeng-uestc** [tensorflow/models#3657]
I use tensorflow1.3 and tensorflow1.4 .
When I run model_test.py ,there are an error" 'module' object has no attribute 'DEFINE_enum' ".
Can anyone tell me the tf version to success run model_test.py

**Comment by littlebelly** [comment]
you need have tensorflow 1.5 or newer for running deeplab

**Comment by yjl9122** [comment]
tf 1.6, but i can't run, i got a bug.

Traceback (most recent call last):
  File "/data/segmentation/models-master/research/deeplab/train.py", line 347, in <module>
    tf.app.run()
  File "/data/config/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/data/segmentation/models-master/research/deeplab/train.py", line 243, in main
    model_variant=FLAGS.model_variant)
  File "/data/segmentation/models-master/research/deeplab/utils/input_generator.py", line 168, in get
    dynamic_pad=True)
  File "/data/config/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 989, in batch
    name=name)
  File "/data/config/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 763, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/data/config/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 483, in dequeue_ma
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/data/config/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2430, in _queu
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/data/config/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 519, in _ap
    repr(values), type(values).__name__))
TypeError: Expected int32 passed to parameter 'n' of op 'QueueDequeueManyV2', got 4.0 of type 'float' instead.
