### ISSUE TITLE
vocab file not found

### ISSUE THREAD

**Issue by carlos12silva94** [tensorflow/models#3665]
Hi, i've cloned tensorflow repo and used pre treined data from https://github.com/KranthiGV/Pretrained-Show-and-Tell-model, and when i try to run this, i get this error. Apparently the word_counts.txt file doesn't has problems and i don't know what's going on.

```
(tensorflow) MacBook-Pro-de-Carlos-2:im2txt Carlos$ sudo bazel-bin/im2txt/run_inference \ --checkpoint_path=${CHECKPOINT_PATH} \ --vocab_file=word_counts.txt \ --input_files=${IMAGE_FILE}
INFO:tensorflow:Building model.
CRITICAL:tensorflow:Vocab file  not found.
INFO:tensorflow:Initializing vocabulary from file: 
Traceback (most recent call last):
  File "/Users/Carlos/code/tensorflow/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 85, in <module>
    tf.app.run()
  File "/Users/Carlos/code/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/Users/Carlos/code/tensorflow/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 55, in main
    vocab = vocabulary.Vocabulary(FLAGS.vocab_file)
  File "/Users/Carlos/code/tensorflow/models/research/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/vocabulary.py", line 48, in __init__
    reverse_vocab = list(f.readlines())
  File "/Users/Carlos/code/tensorflow/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 183, in readlines
    self._preread_check()
  File "/Users/Carlos/code/tensorflow/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/Users/Carlos/code/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
