### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /models/research/faster_rcnn_resnet101_coco_11_06_2017/pet_label_map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by kanghyeonwook** [tensorflow/models#3666]
my comand is 
khw@khw:~/바탕화면/models/research$ python object_detection/train.py --logtostderr --pipeline_config_path=object_detection/faster_rcnn_resnet101_pets.config --train_dir=object_detection

but my trouble is 
home/khw/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From /home/khw/바탕화면/models/research/object_detection/trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/khw/바탕화면/models/research/object_detection/trainer.py", line 235, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/khw/바탕화면/models/research/object_detection/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "object_detection/train.py", line 120, in get_next
    dataset_builder.build(config)).get_next()
  File "/home/khw/바탕화면/models/research/object_detection/builders/dataset_builder.py", line 138, in build
    label_map_proto_file=label_map_proto_file)
  File "/home/khw/바탕화면/models/research/object_detection/data_decoders/tf_example_decoder.py", line 195, in __init__
    use_display_name)
  File "/home/khw/바탕화면/models/research/object_detection/utils/label_map_util.py", line 149, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/home/khw/바탕화면/models/research/object_detection/utils/label_map_util.py", line 129, in load_labelmap
    label_map_string = fid.read()
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /models/research/faster_rcnn_resnet101_coco_11_06_2017/pet_label_map.pbtxt; No such file or directory

pet_label_map.pbtxt  exists  the file but not recognize
help me

**Comment by pkulzc** [comment]
Looks like you should use absolute path in your config file.

**Comment by kanghyeonwook** [comment]
i wirte absolute path but 

Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/khw/models/research/object_detection/trainer.py", line 255, in train
    train_config.optimizer)
  File "/home/khw/models/research/object_detection/builders/optimizer_builder.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "/home/khw/models/research/object_detection/builders/optimizer_builder.py", line 108, in _create_learning_rate
    learning_rate_sequence)
  File "/home/khw/models/research/object_detection/utils/learning_schedules.py", line 154, in manual_stepping
    tf.constant(range(num_boundaries), dtype=tf.int32),
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 433, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/khw/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 344, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got range(0, 3) of type 'range' instead.

i get this error

**Comment by jerevon** [comment]
I have the same error with you, although I change with absolute directory.
have you already solve this problem???
thanks

**Comment by pkulzc** [comment]
This looks like a python2/python3 issue. Try using python 2 if possible.

**Comment by hammadullah125** [comment]
@jerevon Did you solve this problem ????

**Comment by aruna09** [comment]
I am using python2 and getting the same error. Did anyone find a workaround?

**Comment by pkulzc** [comment]
I'm closing this issue since it has mixed error message that are not relevant. 

Feel free to reopen and file a new bug/feature request if needed.

**Comment by kranthik13** [comment]
Making the relative paths to absolute paths did the job.
Thanks!

**Comment by PalTAJ** [comment]
For some reason using the absolute and relative path in config file didn't work
also tried python 2.7 and 3.6 and same issue.

how i managed to make it work:
1- i commented both lines that requires the path to labelmap.pbtxt in config file (depending on your algorithm).
2- i pasted labelmap.pbtxt to train.py directory (in my case it was pwd/models/research/object_detection).
3 - open terminal to the directory you have train.py in (mentioned above).
4- after changing the paths according to yours in the line below run it: 

python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_coco.config --label_map_path=labelMap.pbtxt

hope it helps.
