### ISSUE TITLE
prefetch_to_device does not work with Estimator API 

### ISSUE THREAD

**Issue by mpekalski** [tensorflow/models#3908]
### System information
- **What is the top-level directory of the model you are using**:
V:\kaggle\zalando\zaland
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
added one line of custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
b'unknown' 1.8.0-dev20180329
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
9.0/7
- **GPU model and memory**:
1080TI
- **Exact command to reproduce**:
I run model from 
https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py
and just added at the end of the `train_input_fn()`
```
ds = ds.apply(tf.contrib.data.prefetch_to_device("/gpu:0"))
```

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Is there a plan to enable `prefetch_to_device` in Estimator API?

### Source code / logs
```
PS V:\kaggle\zalando\zalando> cd 'v:\kaggle\zalando\zalando'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\ProgramData\Anaconda3\python.exe' 'C:\Users\Marcin\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher_nodebug.py' 'v:\kaggle\zalando\zalando' '53728' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput' 'v:\kaggle\zalando\zalando\mnist_official.py'
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/mnist_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001F27714EA90>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Downloading https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz to /tmp/mnist_data\train-images-idx3-ubyte.gz
Downloading https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz to /tmp/mnist_data\train-labels-idx1-ubyte.gz
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):  File "C:\Users\Marcin\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher_nodebug.py", line 74, in run
    _vspu.exec_file(file, globals_obj)
  File "C:\Users\Marcin\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 119, in exec_file
    exec_code(code, file, global_variables)
  File "C:\Users\Marcin\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 95, in exec_code
    exec(code_obj, global_variables)
  File "v:\kaggle\zalando\zalando\mnist_official.py", line 267, in <module>
    main(argv=sys.argv)
  File "v:\kaggle\zalando\zalando\mnist_official.py", line 235, in main
    mnist_classifier.train(input_fn=train_input_fn, hooks=train_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 825, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 687, in _get_features_and_labels_from_input_fn
    iterator = result.make_initializable_iterator()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\data\python\ops\prefetching_ops.py", line 145, in make_initializable_iterator
    raise NotImplementedError("`prefetch_to_device()` is not currently "
NotImplementedError: `prefetch_to_device()` is not currently compatible with initializable iterators. Use `make_one_shot_iterator()` instead.
```

**Comment by qlzh727** [comment]
Assigning to code owner for more input. @mrry
