### ISSUE TITLE
AttributeError: 'XXX' object has no attribute 'inplace_batchnorm_update'

### ISSUE THREAD

**Issue by MengYangD** [tensorflow/models#3968]
I am trying to train a pretrained `ssd_inception_v2_coco` model, it worked well before I updated the models. But After I pulled the last updates from the TF models repository, it alwayls shows the error:

```bash
/home/duane/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "/home/duane/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/trainer.py", line 211, in train
    detection_model = create_model_fn()
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 93, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 164, in _build_ssd_model
    inplace_batchnorm_update=ssd_config.inplace_batchnorm_update)
AttributeError: 'Ssd' object has no attribute 'inplace_batchnorm_update'
```
I found [this](https://stackoverflow.com/questions/49688535/attributeerror-fasterrcnn-object-has-no-attribute-inplace-batchnorm-update) in stackoverflow. I  re-compiled `.proto` files according to the answer, but it still has the error.

I do : 
```bash
 python object_detection/builders/model_builder_test.py
```
it has the error, too.

So I re-do  
```bash
git clone https://github.com/tensorflow/models.git
``` 
and re-install according to the [Installation](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md), then     
I do `python object_detection/builders/model_builder_test.py` again. It still has error:

```
/home/duane/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
EEEEEEEEEEEEEE.
======================================================================
ERROR: test_create_embedded_ssd_mobilenet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 516, in test_create_embedded_ssd_mobilenet_v1_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 69, in create_model
    return model_builder.build(model_config, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 93, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 164, in _build_ssd_model
    inplace_batchnorm_update=ssd_config.inplace_batchnorm_update)
AttributeError: 'Ssd' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_faster_rcnn_inception_resnet_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 860, in test_create_faster_rcnn_inception_resnet_v2_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 96, in build
    add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 272, in _build_faster_rcnn_model
    frcnn_config.inplace_batchnorm_update)
AttributeError: 'FasterRcnn' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_faster_rcnn_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 927, in test_create_faster_rcnn_inception_v2_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 96, in build
    add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 272, in _build_faster_rcnn_model
    frcnn_config.inplace_batchnorm_update)
AttributeError: 'FasterRcnn' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_faster_rcnn_model_from_config_with_example_miner (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 985, in test_create_faster_rcnn_model_from_config_with_example_miner
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 96, in build
    add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 272, in _build_faster_rcnn_model
    frcnn_config.inplace_batchnorm_update)
AttributeError: 'FasterRcnn' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_faster_rcnn_nas_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 726, in test_create_faster_rcnn_nas_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 96, in build
    add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 272, in _build_faster_rcnn_model
    frcnn_config.inplace_batchnorm_update)
AttributeError: 'FasterRcnn' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_faster_rcnn_pnas_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 793, in test_create_faster_rcnn_pnas_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 96, in build
    add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 272, in _build_faster_rcnn_model
    frcnn_config.inplace_batchnorm_update)
AttributeError: 'FasterRcnn' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_faster_rcnn_resnet101_with_mask_prediction_enabled (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 662, in test_create_faster_rcnn_resnet101_with_mask_prediction_enabled
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 96, in build
    add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 272, in _build_faster_rcnn_model
    frcnn_config.inplace_batchnorm_update)
AttributeError: 'FasterRcnn' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_faster_rcnn_resnet_v1_models_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 582, in test_create_faster_rcnn_resnet_v1_models_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 3:9 : Message type "object_detection.protos.FasterRcnn" has no field named "inplace_batchnorm_update".

======================================================================
ERROR: test_create_rfcn_resnet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 1051, in test_create_rfcn_resnet_v1_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 96, in build
    add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 272, in _build_faster_rcnn_model
    frcnn_config.inplace_batchnorm_update)
AttributeError: 'FasterRcnn' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_ssd_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 137, in test_create_ssd_inception_v2_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 69, in create_model
    return model_builder.build(model_config, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 93, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 164, in _build_ssd_model
    inplace_batchnorm_update=ssd_config.inplace_batchnorm_update)
AttributeError: 'Ssd' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_ssd_inception_v3_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 208, in test_create_ssd_inception_v3_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 69, in create_model
    return model_builder.build(model_config, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 93, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 164, in _build_ssd_model
    inplace_batchnorm_update=ssd_config.inplace_batchnorm_update)
AttributeError: 'Ssd' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_ssd_mobilenet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 366, in test_create_ssd_mobilenet_v1_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 3:9 : Message type "object_detection.protos.Ssd" has no field named "inplace_batchnorm_update".

======================================================================
ERROR: test_create_ssd_mobilenet_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 442, in test_create_ssd_mobilenet_v2_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 69, in create_model
    return model_builder.build(model_config, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 93, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 164, in _build_ssd_model
    inplace_batchnorm_update=ssd_config.inplace_batchnorm_update)
AttributeError: 'Ssd' object has no attribute 'inplace_batchnorm_update'

======================================================================
ERROR: test_create_ssd_resnet_v1_fpn_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 294, in test_create_ssd_resnet_v1_fpn_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 93, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 164, in _build_ssd_model
    inplace_batchnorm_update=ssd_config.inplace_batchnorm_update)
AttributeError: 'Ssd' object has no attribute 'inplace_batchnorm_update'

----------------------------------------------------------------------
Ran 15 tests in 0.017s

FAILED (errors=14)

```

**Comment by MengYangD** [comment]
Oh, I found : 
```
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 294, in test_create_ssd_resnet_v1_fpn_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 93, in build
    return _build_ssd_model(model_config.ssd, is_training, add_summaries)
  File "/home/duane/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 164, in _build_ssd_model
    inplace_batchnorm_update=ssd_config.inplace_batchnorm_update)
```
I think maybe I need to re-install `/research/setup.py`:
```
# From /models/research/
$ python setup.py build
$ python setup.py install
```
then I try `python object_detection/builders/model_builder_test.py`. It has no error.

**Comment by MengYangD** [comment]
Solved

**Comment by georgeannie** [comment]
I am getting the same error. Followed your instruction. Git clone updates of tensorflow, did protoc, setup build and install and finally ran model_builder_test.py but running into the same issue..Any other plan of action you can offer?

**Comment by MengYangD** [comment]
@georgeannie 
 Sorry, I hava no other idea, I solved my problem according to the method written above. But could you show you error logs ? Maybe we can found something.
