### ISSUE TITLE
Error when executing the parser trainer

### ISSUE THREAD

**Issue by RodSernaPerez** [tensorflow/models#3990]
I am trying to train Syntaxnet on a new Corpus. I have edited the context.pbtxt so it points to the route of the corpus:

input {
  name: 'training-corpus'
  record_format: 'conll-sentence'
  Part {
    file_pattern: '/root/models/syntaxnet/corpus/ud-treebanks-v2.1/UD_English/en-ud-train.conllu'
  }
}
input {
  name: 'tuning-corpus'
  record_format: 'conll-sentence'
  Part {
    file_pattern: '/root/models/syntaxnet/corpus/ud-treebanks-v2.1/UD_English/en-ud-dev.conllu'
  }
}
input {
  name: 'test-corpus'
  record_format: 'conll-sentence'
  Part {
    file_pattern: '/root/models/syntaxnet/corpus/ud-treebanks-v2.1/UD_English/en-ud-test.conllu'
  }
}

But when I try to execute the parser trainer with

bazel-bin/syntaxnet/parser_trainer \
  --task_context=/root/models/syntaxnet/syntaxnet/context.pbtxt \
  --arg_prefix=brain_pos \ 
  --compute_lexicon \     
  --graph_builder=greedy \  
  --training_corpus=training-corpus \  
  --tuning_corpus=tuning-corpus \
  --output_path=models \ 
  --batch_size=32 \       
  --decay_steps=3600 \
  --hidden_layer_sizes=128 \
  --learning_rate=0.08 \
  --momentum=0.9 \
  --seed=0 \
  --params=128-0.08-3600-0.9-0 

I get the following error:

root@1f26ab651d1f:~/models/syntaxnet# bazel-bin/syntaxnet/parser_trainer \
>   --task_context=/root/models/syntaxnet/syntaxnet/context.pbtxt \
>   --arg_prefix=brain_pos \
Traceback (most recent call last):
  File "/root/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 303, in <module>
    tf.app.run()
  File "/root/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/external/tf/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/root/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 263, in main
    RewriteContext()
  File "/root/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 98, in RewriteContext
    text_format.Merge(fin.read(), context)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 309, in Merge
    return MergeLines(text.split('\n'), message, allow_unknown_extension)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 346, in MergeLines
    _ParseOrMerge(lines, message, True, allow_unknown_extension)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 371, in _ParseOrMerge
    allow_unknown_extension)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 473, in _MergeField
    allow_unknown_extension)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 443, in _MergeField
    message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 232:1 : Message type "syntaxnet.TaskInput" has no field named "input".

How can I fix it?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
