### ISSUE TITLE
Object_detection: train.py error

### ISSUE THREAD

**Issue by MTanzeelulrehman** [tensorflow/models#4048]
**What is the top-level directory of the model you are using**: C:\Users\lenovo\Downloads\models-r1.5\research\object_detection
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow**no
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04**windows 10)
**TensorFlow installed from (source or binary**binary
**TensorFlow version (use command below** 1.5
no-gpu 
**Describe the problem**
When i start the training by using the following command **python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config**
i get the following error
![image](https://user-images.githubusercontent.com/37152054/39088495-a1d9fe7a-45cc-11e8-8da6-d56d39a097ec.png)
![image](https://user-images.githubusercontent.com/37152054/39088500-b6beb1a0-45cc-11e8-982c-4eaedbcefc1e.png)
![image](https://user-images.githubusercontent.com/37152054/39088508-da392d40-45cc-11e8-933e-00b2a7ddb534.png)
![image](https://user-images.githubusercontent.com/37152054/39088518-0250466a-45cd-11e8-9d9a-7e69d8560a1f.png)
can u please suggest any solution for it

**Comment by vivekch0976** [comment]
I am facing this error i could not recognize it


(base) C:\Users\vivek chaudhary\Desktop\models\research\object_detection>python train.py --logtostderr --train_dir=training --pipeline_config_path=training/ssd_mobilenet_v1_coco.config
WARNING: Logging before flag parsing goes to stderr.
W0626 12:48:06.161778 11688 lazy_loader.py:50]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0626 12:48:06.580734 11688 deprecation_wrapper.py:119] From train.py:54: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0626 12:48:06.580734 11688 deprecation_wrapper.py:119] From train.py:54: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0626 12:48:06.580734 11688 deprecation_wrapper.py:119] From train.py:163: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0626 12:48:06.596354 11688 deprecation_wrapper.py:119] From train.py:88: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0626 12:48:06.596354 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\utils\config_util.py:41: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0626 12:48:06.596354 11688 deprecation_wrapper.py:119] From train.py:93: The name tf.gfile.Copy is deprecated. Please use tf.io.gfile.copy instead.

W0626 12:48:07.690572 11688 deprecation.py:323] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W0626 12:48:07.698522 11688 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\data\parallel_reader.py:246: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0626 12:48:07.710549 11688 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0626 12:48:07.710549 11688 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:190: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
W0626 12:48:07.718494 11688 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:199: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0626 12:48:07.722489 11688 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:199: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0626 12:48:07.738469 11688 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\data\parallel_reader.py:95: TFRecordReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TFRecordDataset`.
W0626 12:48:07.762437 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\data_decoders\tf_example_decoder.py:52: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0626 12:48:07.762437 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\data_decoders\tf_example_decoder.py:67: The name tf.VarLenFeature is deprecated. Please use tf.io.VarLenFeature instead.

W0626 12:48:07.954555 11688 deprecation.py:323] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\trainer.py:65: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0626 12:48:07.958550 11688 deprecation.py:506] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py:180: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
W0626 12:48:07.962543 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\preprocessor.py:367: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0626 12:48:08.147912 11688 deprecation.py:323] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\preprocessor.py:910: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
W0626 12:48:08.179152 11688 deprecation.py:323] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\box_list_ops.py:199: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0626 12:48:09.428865 11688 deprecation.py:323] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\batcher.py:96: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
W0626 12:48:09.460107 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\prefetcher.py:51: The name tf.PaddingFIFOQueue is deprecated. Please use tf.queue.PaddingFIFOQueue instead.

W0626 12:48:09.460107 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\prefetcher.py:58: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0626 12:48:09.475727 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\trainer.py:222: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

W0626 12:48:10.841901 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\preprocessor.py:1868: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

W0626 12:48:17.568698 11688 deprecation_wrapper.py:119] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\box_predictor.py:526: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

I0626 12:48:17.568698 11688 box_predictor.py:527] depth of additional conv before box predictor: 0
I0626 12:48:17.631184 11688 box_predictor.py:527] depth of additional conv before box predictor: 0
I0626 12:48:17.724912 11688 box_predictor.py:527] depth of additional conv before box predictor: 0
I0626 12:48:17.787401 11688 box_predictor.py:527] depth of additional conv before box predictor: 0
I0626 12:48:17.855372 11688 box_predictor.py:527] depth of additional conv before box predictor: 0
I0626 12:48:17.919284 11688 box_predictor.py:527] depth of additional conv before box predictor: 0
W0626 12:48:18.210894 11688 deprecation.py:323] From C:\Users\vivek chaudhary\Desktop\models\research\object_detection\matchers\argmax_matcher.py:165: setdiff1d (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2018-11-30.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\vivek chaudhary\Desktop\models\research\object_detection\trainer.py", line 228, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "C:\Users\vivek chaudhary\Desktop\models\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "C:\Users\vivek chaudhary\Desktop\models\research\object_detection\trainer.py", line 167, in _create_losses
    losses_dict = detection_model.loss(prediction_dict)
  File "C:\Users\vivek chaudhary\Desktop\models\research\object_detection\meta_architectures\ssd_meta_arch.py", line 474, in loss
    location_losses, cls_losses, prediction_dict, match_list)
  File "C:\Users\vivek chaudhary\Desktop\models\research\object_detection\meta_architectures\ssd_meta_arch.py", line 640, in _apply_hard_mining
    match_list=match_list)
  File "C:\Users\vivek chaudhary\Desktop\models\research\object_detection\core\losses.py", line 515, in __call__
    location_losses = tf.unstack(location_losses)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1197, in unstack
    (axis, -value_shape.ndims, value_shape.ndims))
ValueError: axis = 0 not in [0, 0)
