### ISSUE TITLE
object_detection_mobilenet_v2--TypeError: 'dict_items' object does not support indexing

### ISSUE THREAD

**Issue by Jaijith** [tensorflow/models#4060]
### Describe the problem
I have been trying to move to mobilenet_v2 from mobilenet_v1 version. Though I dilgently followed the documentation for object detection api, I am getting the following error while using mobilenet_V2 as the feature extractor for detection. The same ecosystem is working perfectly if I switch to mobilenet_v1 as the feature extractor. Kindly help

### Source code / logs
jaijith@tensor-bdt-jai:~/BDT_CUTTER_DULL/models/research/object_detection$ python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/trainer.py", line 246, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/deployment/model_deploy.py", line 193, in create_clones
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/trainer.py", line 179, in _create_losses
    prediction_dict = detection_model.predict(images, true_image_shapes)
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/meta_architectures/ssd_meta_arch.py", line 378, in predict
    preprocessed_inputs)
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/meta_architectures/ssd_meta_arch.py", line 122, in extract_features
    return self._extract_features(preprocessed_inputs)
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/models/ssd_mobilenet_v2_feature_extractor.py", line 126, in _extract_features
    scope=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/nets/mobilenet/mobilenet_v2.py", line 162, in mobilenet_base
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/nets/mobilenet/mobilenet_v2.py", line 154, in mobilenet
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/nets/mobilenet/mobilenet.py", line 325, in mobilenet
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/nets/mobilenet/mobilenet.py", line 198, in mobilenet_base
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/nets/mobilenet/mobilenet.py", line 90, in _set_arg_scope_defaults
TypeError: 'dict_items' object does not support indexing

**Comment by Jaijith** [comment]
The problem is with the slim egg.
Unzip slim egg pacakge and edit the mobilenet.py file line 91 to len(default.tems()). 
build the egg file again and replace the older one

**Comment by cannguyen275** [comment]
Hi @Jaijith , I face with the same problem.
When edit the mobilenet.py, which code that I have to change to len(defaults.items()) ???
Thanks

**Comment by leccyril** [comment]
@Jaijith  not clear at all it does'nt help
