### ISSUE TITLE
[convert imagenet to tfrecod] build_imagenet_data

### ISSUE THREAD

**Issue by y-kl8** [tensorflow/models#4096]
I run the script and when I build the tfrecods version of the imagenet data, I meet this problem.

Saving results to /home/yangyuchao/research/Tensorflow_Model_Inception/raw-data/tfrecod/

Successfully read 615299 bounding boxes across 544546 images.

Determining list of input files and labels from /home/yangyuchao/resource/ILSVRC2012/val.

Finished finding files in 100 of 1000 classes.

Finished finding files in 200 of 1000 classes.

Finished finding files in 300 of 1000 classes
.
Finished finding files in 400 of 1000 classes.

Finished finding files in 500 of 1000 classes.

Finished finding files in 600 of 1000 classes.

Finished finding files in 700 of 1000 classes.

Finished finding files in 800 of 1000 classes.

Finished finding files in 900 of 1000 classes.

Finished finding files in 1000 of 1000 classes.

Found 50000 JPEG files across 1000 labels inside /home/yangyuchao/resource/ILSVRC2012/val.

Found 0 images with bboxes out of 50000 images
Launching 8 threads for spacings: [[0, 6250], [6250, 12500], [12500, 18750], [18750, 25000], [25000, 31250], [31250, 37500], [37500, 43750], [43750, 50000]]

2018-04-26 12:28:33.595907: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.

2018-04-26 12:28:33.595941: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.

2018-04-26 12:28:33.595949: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.

2018-04-26 12:28:33.595956: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.

2018-04-26 12:28:33.595963: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.

2018-04-26 12:28:35.424667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties:
 
name: TITAN V

major: 7 minor: 0 memoryClockRate (GHz) 1.455

pciBusID 0000:04:00.0

Total memory: 11.78GiB

Free memory: 11.36GiB

2018-04-26 12:28:35.424797: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x7697d70

2018-04-26 12:28:35.679608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 1 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.62
pciBusID 0000:03:00.0
Total memory: 10.91GiB
Free memory: 10.75GiB

2018-04-26 12:28:35.680027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 0 and 1

2018-04-26 12:28:35.680040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 1 and 0

2018-04-26 12:28:35.680050: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 1 

2018-04-26 12:28:35.680056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y N 

2018-04-26 12:28:35.680060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 1:   N Y 

2018-04-26 12:28:35.680071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN V, pci bus id: 0000:04:00.0)

2018-04-26 12:28:35.680083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0)

Exception in thread Thread-2:

Traceback (most recent call last):
  
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    
self.run()
  
File "/usr/lib/python3.5/threading.py", line 862, in run
    
self._target(*self._args, **self._kwargs)
  
File "/home/yangyuchao/research/Tensorflow_Model_Inception/inception/data/build_imagenet_data.py", line 395, in _process_image_files_batch
    height, width)
  
File "/home/yangyuchao/research/Tensorflow_Model_Inception/inception/data/build_imagenet_data.py", line 214, in _convert_to_example
    'image/colorspace': _bytes_feature(colorspace),
  
File "/home/yangyuchao/research/Tensorflow_Model_Inception/inception/data/build_imagenet_data.py", line 176, in _bytes_feature
   
 return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

TypeError: 'RGB' has type str, but expected one of: bytes

And in the file of tfrecod, the train-00000-of-01024 ......validation-00000-of-00064.......are all empty.

who can help me solve this problem?

**Comment by y-kl8** [comment]
@Vilmara I see you met the similar problem,can you help me?

**Comment by ahyunSeo** [comment]
try 

colorspace = b'RGB'
# ...
image_format = b'JPEG'

**Comment by y-kl8** [comment]
I have tried ,but there still a error:
TypeError: 'n01806143' has type str, but expected one of: bytes 
@ahyunSeo

**Comment by ahyunSeo** [comment]
I just gave up and run with python 2.x

2018-04-26 15:46 GMT+09:00 y-kl8 <notifications@github.com>:

**Comment by yqtianust** [comment]
To use the script build_imagenet_data.py using Python3, you need apply this patch:
[patch.txt](https://github.com/tensorflow/models/files/4532985/patch.txt)
