### ISSUE TITLE
PATH_TO_BE_CONFIGURED

### ISSUE THREAD

**Issue by AliceDinh** [tensorflow/models#4189]
What is `PATH_TO_BE_CONFIGURED` in the following command:
`sed -i "s|PATH_TO_BE_CONFIGURED|"${YOUR_GCS_BUCKET}"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config`
In the tutorial at the address:
https://cloud.google.com/blog/big-data/2017/06/training-an-object-detector-using-cloud-machine-learning-engine
`The PATH_TO_BE_CONFIGURED strings need to be changed so they point to the dataset files and fine-tune checkpoint you’ve uploaded to your Cloud Storage bucket.`
So, it is my local machine or my bucket:
`sed -i "s|/home/alicedinh/models/research/pet_train.record|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config	`
OR
`sed -i "s|gs://alicedinh/data/pet_train.record|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config	`

**Comment by derekjchow** [comment]
If you're following the cloud tutorial, use the GCS bucket:

`sed -i "s|gs://alicedinh/data/pet_train.record|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config`

**Comment by AliceDinh** [comment]
@derekjchow 
Do I need to modify the `faster_rcnn_resnet101_pets.config` file? I reckon that I have to coz if I don't put the absolute path to replace `PATH_TO_BE_CONFIGURED` in this file, the training fail with error:
`NotFoundError: PATH_TO_BE_CONFIGURED/pet_label_map.pbtxt`
Then, as your suggestion, I did the following command:
```
sed -i "s|gs://alicedinh/data/pet_train.record|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config	
sed -i "s|gs://alicedinh/data/pet_val.record|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config
sed -i "s|gs://alicedinh/data/pet_label_map.pbtxt|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config
sed -i "s|gs://alicedinh/data/model.ckpt.meta|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config
sed -i "s|gs://alicedinh/data/model.ckpt.index|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config	
sed -i "s|gs://alicedinh/data/model.ckpt.data-00000-of-00001|"gs://alicedinh"/data|g" object_detection/samples/configs/faster_rcnn_resnet101_pets.config		
```
then I upload the `faster_rcnn_resnet101_pets.config` file to my bucket - the one I modified `PATH_TO_BE_CONFIGURED` by this command:
`gsutil cp object_detection/samples/configs/faster_rcnn_resnet101_pets.config gs://alicedinh/data/faster_rcnn_resnet101_pets.config`

Then, I run this command to train:
```
gcloud beta ml-engine jobs submit training `whoami`_object_detection_`date +%s` \
    --job-dir=gs://alicedinh/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \
    --module-name object_detection.train \
    --runtime-version 1.2 \
    --region us-central1 \
    --config object_detection/samples/cloud/cloud.yml \
    -- \
    --train_dir=gs://alicedinh/train \
    --pipeline_config_path=gs://alicedinh/data/faster_rcnn_resnet101_pets.config
```
I met the following error:
`AttributeError: 'module' object has no attribute 'data' `
Please help

**Comment by derekjchow** [comment]
Please share the full AttributeError

**Comment by AliceDinh** [comment]
@derekjchow 
Here is the full log:
```
alicedinh_object_detection_1525751468
Failed (6 min 43 sec)
Creation time: 8 May 2018, 10:51:20
Start time: 8 May 2018, 10:57:33
End time: 8 May 2018, 10:58:03
Consumed ML units: 2.76

Error message
The replica master 0 exited with a non-zero status of 1. 
Termination reason: Error. Traceback (most recent call last): 
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) 
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals 
File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 167, in <module> tf.app.run() 
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) 
File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 163, in main worker_job_name, is_chief, FLAGS.train_dir) 
File "/root/.local/lib/python2.7/site-packages/object_detection/trainer.py", line 264, in train train_config.prefetch_queue_capacity, data_augmentation_options) 
File "/root/.local/lib/python2.7/site-packages/object_detection/trainer.py", line 59, in create_input_queue tensor_dict = create_tensor_dict_fn() 
File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 120, in get_next dataset_builder.build(config)).get_next() 
File "/root/.local/lib/python2.7/site-packages/object_detection/builders/dataset_builder.py", line 164, in build functools.partial(tf.data.TFRecordDataset, buffer_size=8 * 1000 * 1000), AttributeError: 'module' object has no attribute 'data' 
The replica worker 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): 
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) 
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals 
File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 167, in <module> tf.app.run() 
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) 
File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 163, in main worker_job_name, is_chief, FLAGS.train_dir) 
File "/root/.local/lib/python2.7/site-packages/object_detection/trainer.py", line 264, in train train_config.prefetch_queue_capacity, data_augmentation_options) 
File "/root/.local/lib/python2.7/site-packages/object_detection/trainer.py", line 59, in create_input_queue tensor_dict = create_tensor_dict_fn() 
File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 120, in get_next dataset_builder.build(config)).get_next() 
File "/root/.local/lib/python2.7/site-packages/object_detection/builders/dataset_builder.py", line 164, in build functools.partial(tf.data.TFRecordDataset, buffer_size=8 * 1000 * 1000), AttributeError: 'module' object has no attribute 'data' 
To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=171749705993&resource=ml_job%2Fjob_id%2Falicedinh_object_detection_1525751468&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22alicedinh_object_detection_1525751468%22
Training input

{
  "scaleTier": "CUSTOM",
  "masterType": "standard_gpu",
  "workerType": "standard_gpu",
  "parameterServerType": "standard",
  "workerCount": "5",
  "parameterServerCount": "3",
  "packageUris": [
    "gs://alicedinh/train/packages/e0151f1e1c5c027709422ec1f5954b3ccd4bdaee5c747dbf63007d22cad04d7f/object_detection-0.1.tar.gz",
    "gs://alicedinh/train/packages/e0151f1e1c5c027709422ec1f5954b3ccd4bdaee5c747dbf63007d22cad04d7f/slim-0.1.tar.gz"
  ],
  "pythonModule": "object_detection.train",
  "args": [
    "--train_dir=gs://alicedinh/train",
    "--pipeline_config_path=gs://alicedinh/data/faster_rcnn_resnet101_pets.config"
  ],
  "region": "us-central1",
  "runtimeVersion": "1.2",
  "jobDir": "gs://alicedinh/train"
}

Training output

{
  "consumedMLUnits": 2.76
}

```

**Comment by gg0305** [comment]
I had exactly the same problem and couldn't figure it out. I have tried using both python 2.7 and python 3.6.5 but still getting the same error message

**Comment by izdi** [comment]
I'm coming from [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md](running_on_mobile_tensorflowlite) doc and I can't figure out the details. 

Would be useful to have some description about those variables and where they come from.
To me as I'm far from the field it's not obvious, but I'm willing to build apps with it.

Thanks!

**Comment by didopop3** [comment]
I have similar issue when running locally. 
'''/Users/kaibochen/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/utils/visualization_utils.py:25: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'MacOSX' by the following code:
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/model_lib.py", line 26, in <module>
    from object_detection import eval_util
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/eval_util.py", line 28, in <module>
    from object_detection.metrics import coco_evaluation
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/metrics/coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/metrics/coco_tools.py", line 47, in <module>
    from pycocotools import coco
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x12688f510>) includes params argument, but params are not passed to Estimator.
Traceback (most recent call last):
  File "object_detection/model_main.py", line 101, in <module>
    tf.app.run()
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 97, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 650, in run_local
    hooks=train_hooks)
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 853, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 691, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 798, in _call_input_fn
    return input_fn(**kwargs)
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/inputs.py", line 408, in _train_input_fn
    batch_size=params['batch_size'] if params else train_config.batch_size)
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 123, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/data_decoders/tf_example_decoder.py", line 271, in __init__
    use_display_name)
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/utils/label_map_util.py", line 163, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/Users/kaibochen/src/ml_models/tensorflow/models/research/object_detection/utils/label_map_util.py", line 132, in load_labelmap
    label_map_string = fid.read()
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/Users/kaibochen/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ~/src/ml_models/tensorflow/models/research/pet_label_map.pbtxt; No such file or directory'''

However there is definitely such in the given location.
I ran into the same problem both on a mac and aws ec2 instance

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
