### ISSUE TITLE
object-detection train.py crashes with "corrupted record" error

### ISSUE THREAD

**Issue by MisterMorden** [tensorflow/models#4206]
------------------------

### System information
- **What is the top-level directory of the model you are using**: object-detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: GeForce GTX 1080 Ti 11 GB
- **Exact command to reproduce**: python C:/Users/aarjad/AppData/Local/Programs/Python/Python35/Lib/site-packages/tensorflow/models/research/object_detection/train.py --logtostderr --train_dir="D:/25 manufacturers data/Train_resnet_101_thorough_2" --pipeline_config_path="D:/25 manufacturers data/resnet_101_pipeline.config"

### Describe the problem
I am trying to train an RCNN Resnet 101 model using the COCO pretrained model as a starting point.  My data set consists of 13267 examples across 23 categories.  About half of these examples are "hard negative" images with no objects of interest in them so as to reduce false positives.  After training for ~60k steps, the program crashes with a "tensorflow.python.framework.errors_impl.DataLossError"

### Source code / logs
INFO:tensorflow:global step 62389: loss = 0.0646 (0.304 sec/step)
INFO:tensorflow:global step 62390: loss = 0.0191 (0.319 sec/step)
INFO:tensorflow:global step 62391: loss = 0.0154 (0.313 sec/step)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, corrupted record at 6473107163
         [[Node: parallel_read/ReaderReadV2_4 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/TFRecordReaderV2_4, parallel_read/filenames)]]
INFO:tensorflow:global step 62392: loss = 0.2560 (0.321 sec/step)
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "C:/Users/aarjad/AppData/Local/Programs/Python/Python35/Lib/site-packages/tensorflow/models/research/object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Users/aarjad/AppData/Local/Programs/Python/Python35/Lib/site-packages/tensorflow/models/research/object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\models\research\object_detection\trainer.py", line 299, in train
    saver=saver)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 767, in train
    sv.stop(threads, close_summary_writer=True)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\aarjad\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 6473107163
         [[Node: parallel_read/ReaderReadV2_4 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/TFRecordReaderV2_4, parallel_read/filenames)]]

Thank you for your attention.

Best regards,
Alex

**Comment by MisterMorden** [comment]
I did end up fixing this problem eventually.  The solution was to use JPEG images instead of PNG images.  I'm not sure why this fixed the problem.

**Comment by VIshalWaldiya** [comment]
I used PNG images only.

**Comment by MisterMorden** [comment]
To be clear, I remade my .record file several times and the only thing it would change is the timing of the crash.
