### ISSUE TITLE
Error when running model_builder_test.py

### ISSUE THREAD

**Issue by Bahramudin** [tensorflow/models#4225]
### System information
- **What is the top-level directory of the model you are using**: object-detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Bazel version (if compiling from source)**: --
- **CUDA/cuDNN version**: 9.0, 7.1.3
- **GPU model and memory**: Tesla P40, totalMemory: 22.38GiB freeMemory: 22.21GiB
- **Exact command to reproduce**:

I have installed Tensor-flow successfully, and when I try to install Object-Detection-API in issuing below command I got error:
Command:
`python3 object_detection/builders/model_builder_test.py`
Error:
```
ction/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/adil/workspace/models/research/object_detection/builders/model_builder.py", line 17, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/home/adil/workspace/models/research/object_detection/builders/anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "/home/adil/workspace/models/research/object_detection/protos/anchor_generator_pb2.py", line 15, in <module>
    from object_detection.protos import grid_anchor_generator_pb2 as object__detection_dot_protos_dot_grid__anchor__generator__pb2
  File "/home/adil/workspace/models/research/object_detection/protos/grid_anchor_generator_pb2.py", line 22, in <module>
    serialized_pb=_b('\n3object_detection/protos/grid_anchor_generator.proto\x12\x17object_detection.protos\"\xcd\x01\n\x13GridAnchorGenerator\x12\x13\n\x06height\x18\x01 \x01(\x05:\x03\x32\x35\x36\x12\x12\n\x05width\x18\x02 \x01(\x05:\x03\x32\x35\x36\x12\x19\n\rheight_stride\x18\x03 \x01(\x05:\x02\x31\x36\x12\x18\n\x0cwidth_stride\x18\x04 \x01(\x05:\x02\x31\x36\x12\x18\n\rheight_offset\x18\x05 \x01(\x05:\x01\x30\x12\x17\n\x0cwidth_offset\x18\x06 \x01(\x05:\x01\x30\x12\x0e\n\x06scales\x18\x07 \x03(\x02\x12\x15\n\raspect_ratios\x18\x08 \x03(\x02')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

**Note:** I have installed protobuf version 2.6 , 3.5.1, 3.4.0 **All not worked?**

**Comment by fuatka** [comment]
For tensorflow-1.8 models installation, you need protoc-3.5.1 version to compile proto files.
You can check running protoc version,
`protoc --version`

# From tensorflow/models/research/
`protoc object_detection/protos/*.proto --python_out=.`

# From tensorflow/models/research/
`export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim`

**Comment by bitfort** [comment]
Did the addition of protoc help?

**Comment by rgmyr** [comment]
I am having precisely the same issue, and am using protoc-3.5.1. My system is similar system to @Bahramudin's except different GPU model and cuDNN version = 7.0.5.

**Comment by lganderson** [comment]
I'm having the same issue on macOS. I've tried Protobuf 3.5.1, 3.4.0, and 3.0.0 all with same results.
```
user@Mac-Work:~/Projects/tensorflow-models/research$ protoc --version
libprotoc 3.0.0
user@Mac-Work:~/Projects/tensorflow-models/research$ protoc object_detection/protos/*.proto --python_out=.
user@Mac-Work:~/Projects/tensorflow-models/research$ export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
user@Mac-Work:~/Projects/tensorflow-models/research$ python object_detection/builders/model_builder_test.py
dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Users/user/Library/Python/2.7/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/Library/Python/2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/builders/model_builder.py", line 17, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/Library/Python/2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/builders/anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "/Library/Python/2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/protos/anchor_generator_pb2.py", line 15, in <module>
    from object_detection.protos import grid_anchor_generator_pb2 as object__detection_dot_protos_dot_grid__anchor__generator__pb2
  File "/Library/Python/2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/protos/grid_anchor_generator_pb2.py", line 22, in <module>
    serialized_pb=_b('\n3object_detection/protos/grid_anchor_generator.proto\x12\x17object_detection.protos\"\xcd\x01\n\x13GridAnchorGenerator\x12\x13\n\x06height\x18\x01 \x01(\x05:\x03\x32\x35\x36\x12\x12\n\x05width\x18\x02 \x01(\x05:\x03\x32\x35\x36\x12\x19\n\rheight_stride\x18\x03 \x01(\x05:\x02\x31\x36\x12\x18\n\x0cwidth_stride\x18\x04 \x01(\x05:\x02\x31\x36\x12\x18\n\rheight_offset\x18\x05 \x01(\x05:\x01\x30\x12\x17\n\x0cwidth_offset\x18\x06 \x01(\x05:\x01\x30\x12\x0e\n\x06scales\x18\x07 \x03(\x02\x12\x15\n\raspect_ratios\x18\x08 \x03(\x02')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'```

**Comment by bitfort** [comment]
Sorry for the delay getting back to you -- can you try upgrading to proto 3.6.0?

**Comment by urbanintell** [comment]
@bitfort I did and I am getting the same error

**Comment by jannehlamin** [comment]
Can someone me please, I am getting the same error

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
