### ISSUE TITLE
DeepLab with TensorFlow Mobile or TensorFlow Lite

### ISSUE THREAD

**Issue by dailystudio** [tensorflow/models#4278]
Hello @aquariusjay,

We just want to run this modal on Android. We have tried two approach TensorFlow Mobile and TensorFlow Lite.

With **TensorFlow Mobile**, we download the pre-trained modals with MobileNetV2:
mobilenetv2_coco_voc_trainaug
mobilenetv2_coco_voc_trainval
mobilenetv2_coco_cityscapes_trainfine

We can successfully load the modal, but when run the inference, we get the following error:
```
05-16 16:06:34.122 611-635/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.orange.labs.colorme.dev, PID: 611
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Slice' with these attrs.  Registered devices: [CPU], Registered kernels:
      device='CPU'; T in [DT_BOOL]
      device='CPU'; T in [DT_FLOAT]
      device='CPU'; T in [DT_INT32]
    
    	 [[Node: SemanticPredictions = Slice[Index=DT_INT32, T=DT_INT64](ArgMax, SemanticPredictions/begin, SemanticPredictions/size)]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:298)
        at org.tensorflow.Session$Runner.runAndFetchMetadata(Session.java:260)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:220)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
        at com.dailystudio.deeplab.DeeplabV3.segment(DeeplabV3.java:104)
        at com.dailystudio.deeplab.DeeplabApplication$1.doInBackground(DeeplabApplication.java:46)
        at com.dailystudio.deeplab.DeeplabApplication$1.doInBackground(DeeplabApplication.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)

```
I think this is caused by the output node "SemanticPredictions" call the operation Slice with INT64 data. This is not supported by TensorFlow Mobile yet.

With **TensorFlow Lite**, we use the following command to convert is to tflite format:
```
toco \
	--input_file=$(pwd)/model/frozen_inference_graph.pb \
	--input_format=TENSORFLOW_GRAPHDEF \
	--output_format=TFLITE \
	--output_file=$(pwd)/model/deeplabv3_mnv2_pascal_trainval.tflite \
	--inference_type=FLOAT \
	--input_type=QUANTIZED_UINT8 \
	--input_arrays=ImageTensor \
	--output_arrays=SemanticPredictions \
	--input_shapes=1,513,513,3 \
	--default_ranges_min=0 --default_ranges_max=255

```
We get the following warnings:
```
2018-05-16 16:19:29.429205: W tensorflow/contrib/lite/toco/toco_cmdline_flags.cc:245] --input_type is deprecated. It was an ambiguous flag that set both --input_data_types and --inference_input_type. If you are trying to complement the input file with information about the type of input arrays, use --input_data_type. If you are trying to control the quantization/dequantization of real-numbers input arrays in the output file, use --inference_input_type.
2018-05-16 16:19:29.492371: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1270] Converting unsupported operation: Equal
2018-05-16 16:19:29.492813: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1270] Converting unsupported operation: LogicalAnd
2018-05-16 16:19:29.521856: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 812 operators, 1241 arrays (0 quantized)
2018-05-16 16:19:29.550535: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 802 operators, 1222 arrays (0 quantized)
2018-05-16 16:19:29.582482: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 802 operators, 1222 arrays (0 quantized)
2018-05-16 16:19:29.610492: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 148 operators, 358 arrays (0 quantized)
2018-05-16 16:19:29.613697: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 148 operators, 358 arrays (0 quantized)
2018-05-16 16:19:29.616876: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 143 operators, 348 arrays (0 quantized)
2018-05-16 16:19:29.619981: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 4: 142 operators, 346 arrays (0 quantized)
2018-05-16 16:19:29.622935: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 5: 141 operators, 344 arrays (0 quantized)
2018-05-16 16:19:29.626348: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 141 operators, 344 arrays (0 quantized)
2018-05-16 16:19:29.629622: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:329] Total transient array allocated size: 3158144 bytes, theoretical optimal value: 3158144 bytes.
2018-05-16 16:19:29.631849: F tensorflow/contrib/lite/toco/tflite/export.cc:315] Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops. Here is a list of operators for which you will need custom implementations: ExpandDims, Slice, Stack, TensorFlowShape.
./convert-lite.sh: line 11: 70835 Abort trap: 6           /Volumes/Workspace/tensorflow/workspace/tensorflow/bazel-bin/tensorflow/contrib/lite/toco/toco --input_file=$(pwd)/model/frozen_inference_graph.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=$(pwd)/model/deeplabv3_mnv2_pascal_trainval.tflite --inference_type=FLOAT --input_type=QUANTIZED_UINT8 --input_arrays=ImageTensor --output_arrays=SemanticPredictions --input_shapes=1,513,513,3 --default_ranges_min=0 --default_ranges_max=255
```
The model could not be loaded successfully. I think it is caused the warning:
Here is a list of operators for which you will need custom implementations: ExpandDims, Slice, Stack, TensorFlowShape.

Is it possible to update node SemanticPredictions to use INT32 data type on Slice operation? Or do you have any suggestion on how to run it with TensorFlow lite?

**Comment by aquariusjay** [comment]
Hi dailystudio,

Thanks for bringing up this issue.
Regarding your questions, I would have a few suggestions at this moment:

1. You could try to change the export_model.py to use int32 SemanticPredictions, and see what happens (e.g., there may be other issues).
2. You could contact TensorFlow Mobile and TensorFlow Lite to support those operations.

We will look into this issue more carefully in the near future.

Thanks,

**Comment by dailystudio** [comment]
Hello aquariusjay,
Thanks for your valuable advices!

I modify the line in export_model.py (around line 131):
```
    semantic_predictions = tf.slice(
        tf.cast(predictions[common.OUTPUT_TYPE], tf.int32),
        [0, 0, 0],
        [1, resized_image_size[0], resized_image_size[1]])

```
add tf.cast to cast predictions to int32. And then export model with the following command:
```
python export_model.py --checkpoint_path model/model.ckpt-30000 --export_path model/frozen_inference_graph.pb
```
Here I only pointed the checkpoint path and export path, rest parameters kept with default value.

Now running the model with Tensorflow Mobile is successful!

The new issue is that the output array (SemanticPredictions) is a zero array, all the elements are 0.
There is no any error or warning are printed during the inference. 

Do you have any suggestion? Is it caused by some unsupported op in the model? Or should I add more parameters during exporting the model?

**Comment by aquariusjay** [comment]
You need to make sure you have provided the right flag values for the model variant (e.g., MobileNet-v2 or Xception_65) that you are using.
Check local_test.sh or local_test_mobilenetv2.sh for reference.

**Comment by dailystudio** [comment]
Hello aquariusjay,

Now it works on my mobile devices. I add model variant parameter during export model and also fix a dimension issue of passing the width and heigh in wrong order during the inference. 

Thanks for your help. I will accomplish it as complete demo.

**Comment by liangxiao05** [comment]
@dailystudio，hi,could you share which  mobile do you run it on ,and how is the latency?

**Comment by dailystudio** [comment]
@liangxiao05, at Oneplus 3T and Oneplus 5, 900ms ~ 2700ms per inference.

**Comment by JoseRNFaria** [comment]
@dailystudio 
I tried your solution and it worked. Thanks.
In my pixel 2 the run time is ~1300 - 1500 ms

**Comment by dailystudio** [comment]
@JoseRNFaria Glad to here that my works can help you!

**Comment by Shenghsin** [comment]
@dailystudio  I have the same problem "The new issue is that the output array (SemanticPredictions) is a zero array, all the elements are 0." Could you tell me how to fix it?? Thanks!

**Comment by dailystudio** [comment]
@Shenghsin @aquariusjay @JoseRNFaria , I have written a demo app of this model. I am still updating the document. Here is the repository link:
https://github.com/dailystudio/ml/tree/master/deeplab

**Comment by llhe** [comment]
@dailystudio To run deeplabv3+ on mobile phones faster, you can checkout [MACE](https://github.com/xiaomi/mace) which has deeplabv3+ in the [MACE Model Zoo](https://github.com/XiaoMi/mace-models/tree/master/deeplab-v3-plus). Here are some [benchmark results](https://github.com/XiaoMi/mace/issues/1) which includes deeplab-v3-plus-mobilenet-v2.

**Comment by austingg** [comment]
hope we can use tensorflowlite to run the deeplab v3+ model, since segmentation task ususally cost much more than classification task. quantization may help a lot.

**Comment by hiepgaf** [comment]
@llhe: When I run deeplab-v3-plus-mobilenet-v2  from MACE Model Zoo in @dailystudio demo app. The app is not work.
Caused by: java.lang.IllegalArgumentException: Expects arg[0] to be float but uint8 is provided
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:298)
        at org.tensorflow.Session$Runner.runAndFetchMetadata(Session.java:260)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:220)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
        at com.module.hiepthb.modules.deeplearning.portrait.ml.DeeplabModel.segment(DeeplabModel.java:274)
        at com.module.hiepthb.modules.deeplearning.portrait.SegmentBitmapsLoader.loadInBackground(SegmentBitmapsLoader.java:146)
        at com.module.hiepthb.modules.deeplearning.portrait.SegmentBitmapsLoader.loadInBackground(SegmentBitmapsLoader.java:55)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

How to make it work?

**Comment by hiepgaf** [comment]
Hello @llhe,
When I run deeplab-v3-plus-mobilenet-v2  from MACE Model Zoo in @dailystudio demo app. The app is not work.

`Caused by: java.lang.IllegalArgumentException: Expects arg[0] to be float but uint8 is provided
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:298)
        at org.tensorflow.Session$Runner.runAndFetchMetadata(Session.java:260)
        `

How to make it work?

**Comment by weehe91325** [comment]
@dailystudio, did you managed to use in your demo the model converted to TF Lite?

**Comment by sumsuddin** [comment]
Hi, @dailystudio. Just change this [line](https://github.com/tensorflow/models/blob/dda23ecff1ceb40f61f41b3a4aab2cdaf183582e/research/deeplab/model.py#L184) to `predictions[output] = tf.argmax(logits, 3, output_type=dtypes.int32)`.

**Comment by ARIFCSE10** [comment]
> Hello aquariusjay,
> Thanks for your valuable advices!
> 
> I modify the line in export_model.py (around line 131):
> 
> ```
>     semantic_predictions = tf.slice(
>         tf.cast(predictions[common.OUTPUT_TYPE], tf.int32),
>         [0, 0, 0],
>         [1, resized_image_size[0], resized_image_size[1]])
> ```
> add tf.cast to cast predictions to int32. And then export model with the following command:
> 
> ```
> python export_model.py --checkpoint_path model/model.ckpt-30000 --export_path model/frozen_inference_graph.pb
> ```
> Here I only pointed the checkpoint path and export path, rest parameters kept with default value.
> 
> Now running the model with Tensorflow Mobile is successful!
> 
> The new issue is that the output array (SemanticPredictions) is a zero array, all the elements are 0.
> There is no any error or warning are printed during the inference.
> 
> Do you have any suggestion? Is it caused by some unsupported op in the model? Or should I add more parameters during exporting the model?

could you share frozen_graph.pb after int32 casting?

**Comment by SanthoshRajendiran** [comment]
@dailystudio @aquariusjay @sumsuddin.. Is there support for TFLite conversion of DeeplabV3 with MobilenetV2? Could not find relevant documentation.

**Comment by melody-rain** [comment]
watching this

**Comment by jinfengboan** [comment]
watching

**Comment by ajinkya933** [comment]
> Hello aquariusjay,
> Thanks for your valuable advices!
> 
> I modify the line in export_model.py (around line 131):
> 
> ```
>     semantic_predictions = tf.slice(
>         tf.cast(predictions[common.OUTPUT_TYPE], tf.int32),
>         [0, 0, 0],
>         [1, resized_image_size[0], resized_image_size[1]])
> ```
> add tf.cast to cast predictions to int32. And then export model with the following command:
> 
> ```
> python export_model.py --checkpoint_path model/model.ckpt-30000 --export_path model/frozen_inference_graph.pb
> ```
> Here I only pointed the checkpoint path and export path, rest parameters kept with default value.
> 
> Now running the model with Tensorflow Mobile is successful!
> 
> The new issue is that the output array (SemanticPredictions) is a zero array, all the elements are 0.
> There is no any error or warning are printed during the inference.
> 
> Do you have any suggestion? Is it caused by some unsupported op in the model? Or should I add more parameters during exporting the model?

@dailystudio  I followed your notes without adding "model_variant" and was able to get frozen_inference_graph.pb file. my script is 

`$ python3 deeplab/export_model2.py   --logtostderr   --checkpoint_path=deeplab/exp2/model.ckpt-3850   --export_path=deeplab/exported_model2/frozen_inference_graph.pb `

But, when I add model variant 

`$ python3 deeplab/export_model2.py   --logtostderr   --checkpoint_path=deeplab/exp2/model.ckpt-3850   --export_path=deeplab/exported_model2/frozen_inference_graph.pb   --model_variant=”mobilenet_v2” `

I am getting the following error:

```
  File "deeplab/export_model2.py", line 182, in <module>
    tf.app.run()
  File "/Users/ajinkyabobade/Documents/enviornments/project1_env/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/ajinkyabobade/Documents/enviornments/project1_env/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/ajinkyabobade/Documents/enviornments/project1_env/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deeplab/export_model2.py", line 124, in main
    image_pyramid=FLAGS.image_pyramid)
  File "/Users/ajinkyabobade/Documents/enviornments/models/research/deeplab/model.py", line 183, in predict_labels
    fine_tune_batch_norm=False)
  File "/Users/ajinkyabobade/Documents/enviornments/models/research/deeplab/model.py", line 313, in multi_scale_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/Users/ajinkyabobade/Documents/enviornments/models/research/deeplab/model.py", line 553, in _get_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/Users/ajinkyabobade/Documents/enviornments/models/research/deeplab/model.py", line 395, in extract_features
    use_bounded_activation=model_options.use_bounded_activation)
  File "/Users/ajinkyabobade/Documents/enviornments/models/research/deeplab/core/feature_extractor.py", line 343, in extract_features
    arg_scope = arg_scopes_map[model_variant](
KeyError: '”mobilenet_v2”'

```

How do I resolve this error ?

**Comment by essalahsouad** [comment]
@dailystudio 

> Hello aquariusjay,
Now it works on my mobile devices. I add model variant parameter during export model and also fix a dimension issue of passing the width and heigh in wrong order during the inference.
Thanks for your help. I will accomplish it as complete demo.

how do you solve the issue, because  have tried to convert the pb file to tflite by using tf converter
`tflite_convert ----output_format=TFLITE --inference_type=FLOAT --inference_input_type=FlOAT --input_arrays=sub_2 --input_shapes=1,257,257,3 --output_arrays=ResizeBilinear_2 --output_file=mobilenet.tflite --graph_def=mobilenet.pb --mean_values=128 --std_dev_values=127 --allow_custom_ops --post_training_quantize`
and i got a slow inference on mobile(using iphone 6)
can check this for me ??

**Comment by helloItzMe** [comment]
can anyone create a py script file for converting xception model frozen_graph.pb file to tflite??

**Comment by charlizesmith** [comment]
do you have any tflite file of the module
