### ISSUE TITLE
Is it available to run Object Detection API on Google cloud with TPU?

### ISSUE THREAD

**Issue by liangxiao05** [tensorflow/models#4283]
As described,thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment]
It appears there is support for TPUs (https://github.com/tensorflow/models/blob/master/research/object_detection/model_tpu_main.py), however given the early state of TPUs you should really know what you're doing before you attempt it.

**Comment by shreyaaggarwal** [comment]
Hi, I am trying to train the Object Detection model API on GPU and run the inference on TPU. All the documentation is on running the training on TPU. I have trained on GPU but it's not converting to TPU by following the documentation. 

The only page in documentation I could find on training on GPU and running inference on TPU is: [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tpu_exporters.md](url) but this command gives me the following error:

```
WARNING: Logging before flag parsing goes to stderr.
W0701 12:30:11.709724 18108 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\slim\nets\inception_resnet_v2.py:373: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W0701 12:30:11.811449 18108 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\slim\nets\mobilenet\mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

W0701 12:30:11.842369 18108 deprecation_wrapper.py:119] From object_detection/tpu_exporters/export_saved_model_tpu.py:54: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

Traceback (most recent call last):
  File "object_detection/tpu_exporters/export_saved_model_tpu.py", line 54, in <module>
    tf.app.run()
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\sgupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\sgupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/tpu_exporters/export_saved_model_tpu.py", line 43, in main
    raise tf.app.UsageError('Too many command-line arguments.')
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.app' has no attribute 'UsageError'

(tensorflow_gpu) C:\Users\sgupta\tensorflow_triage\models\research>python object_detection/tpu_exporters/export_saved_model_tpu.py --pipeline_config_file=C:/Users/sgupta/workspace/triage_tool/training/ssd_mobilenet_v1_pets.config --ckpt_path=C:/Users/sgupta/workspace/triage_tool/train_with_model_main/model.ckpt-119 --export_dir=C:/Users/sgupta/workspace/triage_tool/training/output_tf_exporter --input_placeholder_name=image_tensor:0 --input_type=image_tensor  device=[GPU]
WARNING: Logging before flag parsing goes to stderr.
W0701 12:30:37.318855 34140 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\slim\nets\inception_resnet_v2.py:373: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W0701 12:30:37.388669 34140 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\slim\nets\mobilenet\mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

W0701 12:30:37.494386 34140 deprecation_wrapper.py:119] From object_detection/tpu_exporters/export_saved_model_tpu.py:54: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

Traceback (most recent call last):
  File "object_detection/tpu_exporters/export_saved_model_tpu.py", line 54, in <module>
    tf.app.run()
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\sgupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\sgupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/tpu_exporters/export_saved_model_tpu.py", line 43, in main
    raise tf.app.UsageError('Too many command-line arguments.')
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.app' has no attribute 'UsageError'

(tensorflow_gpu) C:\Users\sgupta\tensorflow_triage\models\research>python object_detection/tpu_exporters/export_saved_model_tpu.py --pipeline_config_file=C:/Users/sgupta/workspace/triage_tool/training/ssd_mobilenet_v1_pets.config --ckpt_path=C:/Users/sgupta/workspace/triage_tool/train_with_model_main/model.ckpt-119 --export_dir=C:/Users/sgupta/workspace/triage_tool/training/output_tf_exporter --input_placeholder_name=image_tensor:0 --input_type=image_tensor
WARNING: Logging before flag parsing goes to stderr.
W0701 12:44:26.311263 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\slim\nets\inception_resnet_v2.py:373: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W0701 12:44:26.441916 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\slim\nets\mobilenet\mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

W0701 12:44:26.492776 33144 deprecation_wrapper.py:119] From object_detection/tpu_exporters/export_saved_model_tpu.py:54: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0701 12:44:26.507738 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\tpu_exporters\export_saved_model_tpu_lib.py:40: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0701 12:44:26.518707 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\exporter.py:110: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0701 12:44:26.520702 33144 deprecation.py:323] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\tpu_exporters\ssd.py:60: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0701 12:44:26.623427 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\core\preprocessor.py:2487: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

W0701 12:44:26.722163 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\meta_architectures\ssd_meta_arch.py:566: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0701 12:44:31.551258 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\core\anchor_generator.py:149: The name tf.assert_equal is deprecated. Please use tf.compat.v1.assert_equal instead.

W0701 12:44:31.578186 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\predictors\convolutional_box_predictor.py:149: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

I0701 12:44:31.589159 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:31.717813 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:31.855444 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:31.992079 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:32.083837 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:32.181574 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
W0701 12:44:32.429908 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\tpu_exporters\export_saved_model_tpu_lib.py:73: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-07-01 12:44:32.437774: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
I0701 12:44:36.938892 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:37.072536 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:37.295939 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:37.394675 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:37.505379 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
I0701 12:44:37.646003 33144 convolutional_box_predictor.py:150] depth of additional conv before box predictor: 0
W0701 12:44:38.605438 33144 deprecation.py:323] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\core\post_processing.py:183: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0701 12:44:39.351747 33144 deprecation_wrapper.py:119] From C:\Users\sgupta\tensorflow_triage\models\research\object_detection\tpu_exporters\export_saved_model_tpu_lib.py:77: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

Traceback (most recent call last):
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1339, in _run_fn
    self._extend_graph()
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'TPUOrdinalSelector' used by {{node TPUOrdinalSelector}}with these attrs: []
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[TPUOrdinalSelector]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/tpu_exporters/export_saved_model_tpu.py", line 54, in <module>
    tf.app.run()
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\sgupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\sgupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/tpu_exporters/export_saved_model_tpu.py", line 47, in main
    FLAGS.input_type, FLAGS.use_bfloat16)
  File "C:\Users\sgupta\tensorflow_triage\models\research\object_detection\tpu_exporters\export_saved_model_tpu_lib.py", line 80, in export
    sess.run(init_op)
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\sgupta\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'TPUOrdinalSelector' used by node TPUOrdinalSelector (defined at C:\Users\sgupta\tensorflow_triage\models\research\object_detection\tpu_exporters\ssd.py:196) with these attrs: []
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[TPUOrdinalSelector]]

```
What is the top-level directory of the model you are using: models/research
Have I written custom code: Not yet (Just edited the config file)
OS Platform and Distribution: Windows 10
TensorFlow installed from: pip (tensorflow 1.14 not available on conda)
TensorFlow version: 1.14, tensorflow-gpu==1.12
Bazel version: N/A
CUDA/cuDNN version: 10.0
GPU model and memory: NVIDIA Quadro M2000M and memory: 32 GB
Exact command to reproduce: `C:\Users\sgupta\tensorflow_triage\models\research>python object_detection/tpu_exporters/export_saved_model_tpu.py --pipeline_config_file=C:/Users/sgupta/workspace/triage_tool/training/ssd_mobilenet_v1_pets.config --ckpt_path=C:/Users/sgupta/workspace/triage_tool/train_with_model_main/model.ckpt-119 --export_dir=C:/Users/sgupta/workspace/triage_tool/training/output_tf_exporter --input_placeholder_name=image_tensor:0 --input_type=image_tensor`
