### ISSUE TITLE
Download the dataset for mnist model failed

### ISSUE THREAD

**Issue by snnn** [tensorflow/models#4309]
### System information
- **What is the top-level directory of the model you are using**:
official\mnist
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
'v1.8.0-0-g93bc2e2072' 1.8.0
- **Bazel version (if compiling from source)**:
None
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
None
- **Exact command to reproduce**:
```
git clone https://github.com/tensorflow/models C:\os\models
cd C:\os\models
set PYTHONPATH=%PYTHONPATH%;C:\os\models
python official\mnist\mnist.py --export_dir saved_model
```

### Describe the problem
Download the dataset for mnist model failed.

### Source code / logs
```
I0518 12:49:22.012639 16288 tf_logging.py:116] Using default config.
I0518 12:49:22.013639 16288 tf_logging.py:116] Using config: {'_task_type': 'worker', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000018B3D290080>, '_log_step_count_steps': 100, '_train_distribute': None, '_tf_random_seed': None, '_master': '', '_model_dir': '/tmp/mnist_model', '_save_summary_steps': 100, '_keep_checkpoint_every_n_hours': 10000, '_global_id_in_cluster': 0, '_service': None, '_is_chief': True, '_save_checkpoints_steps': None, '_evaluation_master': '', '_task_id': 0, '_num_worker_replicas': 1, '_keep_checkpoint_max': 5, '_num_ps_replicas': 0, '_save_checkpoints_secs': 600, '_session_config': None}
Downloading https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz to C:\Users\chasun\AppData\Local\Temp\tmp1qxrc6qh.gz
Traceback (most recent call last):
  File "official\mnist\mnist.py", line 264, in <module>
    absl_app.run(main)
  File "C:\Python35\lib\site-packages\absl\app.py", line 274, in run
    _run_main(main, argv)
  File "C:\Python35\lib\site-packages\absl\app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "official\mnist\mnist.py", line 258, in main
    run_mnist(flags.FLAGS)
  File "official\mnist\mnist.py", line 240, in run_mnist
    mnist_classifier.train(input_fn=train_input_fn, hooks=train_hooks)
  File "C:\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 853, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "C:\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 691, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "C:\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 798, in _call_input_fn
    return input_fn(**kwargs)
  File "official\mnist\mnist.py", line 222, in train_input_fn
    ds = dataset.train(flags_obj.data_dir)
  File "C:\os\models\official\mnist\dataset.py", line 112, in train
    'train-labels-idx1-ubyte')
  File "C:\os\models\official\mnist\dataset.py", line 84, in dataset
    images_file = download(directory, images_file)
  File "C:\os\models\official\mnist\dataset.py", line 77, in download
    os.remove(zipped_filepath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\chasun\\AppData\\Local\\Temp\\tmp1qxrc6qh.gz'
```

**Comment by robieta** [comment]
Curious. It's possible that another process (i.e. an antivirus) was inspecting it. If you run the script again it should work since the downloader shouldn't re-download it. You may have to rerun it twice if it fails again on the validation archive cleanup.

**Comment by takotab** [comment]
I had the same problem.  I solved it with changing this:
`  _, zipped_filepath = tempfile.mkstemp(suffix='.gz')`
to:
```
f, zipped_filepath = tempfile.mkstemp(suffix='.gz')
os.close(f)
```
However in check_image_file_header the magic number is incorrect (2049) in addition the number of rows/columns do not match. I get this error:

> ValueError, Invalid MNIST file E://data//MNIST\test\t10k-labels-idx1-ubyte: Expected 28x28 images, found 117571840x67175433

**Comment by robieta** [comment]
@takotab good catch.

**Comment by wt-huang** [comment]
Closing as this is resolved
