### ISSUE TITLE
multi-label classification problem

### ISSUE THREAD

**Issue by ztwe** [tensorflow/models#4396]
When build tfrecord, I have encoded the labels as N-hot encoding. 

Then I comment the following code:
    **labels = slim.one_hot_encoding(
         labels, dataset.num_classes - FLAGS.labels_offset)**

But it crash when train:
Traceback (most recent call last):
  File "../train_image_classifier_multilabel.py", line 620, in <module>
    tf.app.run()
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "../train_image_classifier_multilabel.py", line 519, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/root/Projects/scene-tf/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "../train_image_classifier_multilabel.py", line 513, in clone_fn
    label_smoothing=FLAGS.label_smoothing, weights=1.0)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/losses/losses_impl.py", line 676, in sigmoid_cross_entropy
    logits.get_shape().assert_is_compatible_with(multi_class_labels.get_shape())
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 764, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (32, 63) and (32,) are incompatible

The sigmoid_cross_entropy encounters problem:
      **tf.losses.sigmoid_cross_entropy(
          logits=logits, multi_class_labels=labels,
          label_smoothing=FLAGS.label_smoothing, weights=1.0)**

Obviously, the shape of logits is   (32, 63)  and labels is  (32,) .

It seems that the comment of one_hot_encoding is wrong.
But I don't know how to fix it.

**Comment by ztwe** [comment]
I think the main problem is the lack of encoding function. Do anyone know how to  implement N-hot encoding which is aimed to replace one-hot encoding？
