### ISSUE TITLE
 _MergeMessageField     raise tokenizer.ParseErrorPreviousToken('Expected "%s".' % (end_token,)) google.protobuf.text_format.ParseError: 140:16 : Expected "}".

### ISSUE THREAD

**Issue by Shiv1799** [tensorflow/models#4398]
### System information
- **What is the top-level directory of the model you are using**:Object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:windows 10
- **TensorFlow installed from (source or binary)**:Binary
- **TensorFlow version (use command below)**:1.8.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:latest
- **GPU model and memory**:NVIDIA GEFORCE
- **Exact command to reproduce**: python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Ankit Sharma\Anaconda2\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\tensorflow1\models\research\object_detection\utils\config_util.py", line 94, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Users\Ankit Sharma\Anaconda2\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\Ankit Sharma\Anaconda2\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\Ankit Sharma\Anaconda2\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\Ankit Sharma\Anaconda2\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\Ankit Sharma\Anaconda2\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Ankit Sharma\Anaconda2\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 822, in _MergeMessageField
    raise tokenizer.ParseErrorPreviousToken('Expected "%s".' % (end_token,))
google.protobuf.text_format.ParseError: 140:16 : Expected "}".

**Comment by LoveNordling** [comment]
Any solution to this? The message doesn't specify which file or which line that triggered the error.
