### ISSUE TITLE
the error about input dimension based on tf.slim training

### ISSUE THREAD

**Issue by ztwe** [tensorflow/models#4430]
I do experiment in multi-label classification based on tf.slim. I fix the build of tfrecord and the encoding after reading from tfrecord. The code for image stays the same.

When start training, it crashes:

```
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Recording summary at step 8.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, input must be 4-dimensional[1,1,461,459,3]
         [[Node: ResizeBilinear = ResizeBilinear[T=DT_UINT8, align_corners=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ExpandDims, ResizeBilinear/size)]]
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "../train_image_classifier_ml.py", line 685, in <module>
    tf.app.run()
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "../train_image_classifier_ml.py", line 681, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 784, in train
    ignore_live_threads=ignore_live_threads)
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 828, in stop
    ignore_live_threads=ignore_live_threads)
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1249, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/root/anaconda3/envs/tf14_py27/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: input must be 4-dimensional[1,1,461,459,3]
         [[Node: ResizeBilinear = ResizeBilinear[T=DT_UINT8, align_corners=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ExpandDims, ResizeBilinear/size)]]
```

I check my code. It seems everything is right. I don't know where does [1,1,461,459,3] come from.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ztwe** [comment]
the top-level directory of the model I am using:   tf.slim
Have I written custom code: yes
OS Platform and Distribution: ubuntu16.04
TensorFlow installed from: anaconda3
TensorFlow version: 1.8.0
Bazel version: no
CUDA/cuDNN version: 9.0/7.2
GPU model and memory: Tesla V100

**Comment by karmel** [comment]
It's hard to help debug with the information you provided. Can you create a minimal code example that demonstrates the issue?

**Comment by ztwe** [comment]
The inputs contain channels that > 3.

**Comment by twinsyssy1018** [comment]
@ztwe have you solved  the problem ?   how to find out the  inputs with 4 channels?

**Comment by udaynitk1** [comment]
The inputs contain channels that > 3.
--


how to solve the issue. i have the same problem. I want to debug
