### ISSUE TITLE
eval.py stops while initializing without any error message

### ISSUE THREAD

**Issue by Z0org** [tensorflow/models#4431]
### System information
- **What is the top-level directory of the model you are using**:
tensorflow/models/research/object_detection 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary (pip install tensorflow-gpu)
- **TensorFlow version (use command below)**:
v1.8.0-0-g93bc2e2072 1.8.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA 9.0/ cuDNN 7.1
- **GPU model and memory**:
NVIDIA GTX1070Ti 8Gb
- **Exact command to reproduce**:
python eval.py --logtostderr --pipeline_config_path=faster_rcnn_resnet101_coco.config --checkpoint_dir =./models/train --eval_dir=./models/eval

### Describe the problem
I try to evaluate my training Progress with the eval.py script. The training runs fine but every time i try to run the eval script it stops at some point (see the log at the end). I tried running it over night but it dosn't change anything. The only thing I changed in the script is to force it to run in CPU-Mode by adding the line
os.environ["CUDA_VISIBLE_DEVICES"]="" #cpu mode
in the eval.py file. 
It worked fine a few weeks ago and after but I don't know what has changed since. I updated Tensorflow but nothing changed.
### Source code / logs
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From /home/simtower2/miniconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/core/box_predictor.py:396: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead

**Some additional info: I tried to run the script eval_util_test.py and it finishes with 2 Errors. Here is the output in case it helps:**

```
/home/simtower2/miniconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/utils/visualization_utils.py:25: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "eval_util_test.py", line 24, in <module>
    from object_detection import eval_util
  File "/home/simtower2/miniconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/eval_util.py", line 28, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/simtower2/miniconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/metrics/coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "/home/simtower2/miniconda3/lib/python3.6/site-packages/tensorflow/models/research/object_detection/metrics/coco_tools.py", line 47, in <module>
    from pycocotools import coco
  File "/home/simtower2/miniconda3/lib/python3.6/site-packages/tensorflow/models/research/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/home/simtower2/miniconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/simtower2/miniconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
2018-06-03 07:41:16.883961: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-03 07:41:16.943664: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-03 07:41:16.943967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.41GiB
2018-06-03 07:41:16.943979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-03 07:41:17.097276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-03 07:41:17.097298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-03 07:41:17.097302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-03 07:41:17.097415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2434 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
E2018-06-03 07:41:17.169258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-03 07:41:17.169285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-03 07:41:17.169290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-03 07:41:17.169293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-03 07:41:17.169384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2434 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
E..
======================================================================
ERROR: test_get_eval_metric_ops_for_coco_detections (__main__.EvalUtilTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "eval_util_test.py", line 74, in test_get_eval_metric_ops_for_coco_detections
    for key, (value_op, _) in metric_ops.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

======================================================================
ERROR: test_get_eval_metric_ops_for_coco_detections_and_masks (__main__.EvalUtilTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "eval_util_test.py", line 94, in test_get_eval_metric_ops_for_coco_detections_and_masks
    for key, (value_op, _) in metric_ops.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

----------------------------------------------------------------------
Ran 4 tests in 0.367s

FAILED (errors=2)

```

**Comment by a819721810** [comment]
I met it before.
I don't think that it is due to "logging.info()"function can output result for some reason .You can use "tf.logging.info()"function.

**Comment by Z0org** [comment]
Thanks for your answer. But where exactly should I change it, because in eval.py it is already like this.

**Comment by kulkarnivishal** [comment]
I don't understand this comment? "I added from tensorflow.python.platform import tf_logging as logging to eval_util.py to the eval.py file and removed the tf" 
I am facing the same issue while running eval.py. I don't see any output
