### ISSUE TITLE
tensorflow.python.framework.errors_impl.notfounderror: /PATH/TO/.CONFIG; No such file or directory

### ISSUE THREAD

**Issue by Abduoit** [tensorflow/models#4445]
System information

**Have I written custom code (NO):
OS Platform and Distribution (Linux Ubuntu 16.04):
TensorFlow installed from (binary):
TensorFlow version (1.6.0):
Python version: (3.5.2)
Bazel version (N/A):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: CUDA 9.0/ CUDDN 7
GPU model and memory: Nvidia GTX 1080/ 8GB
Exact command to reproduce:** 
`python object_detection/train.py     --logtostderr     --pipeline_config_path=/home/jesse/gpu-py3/models/research/object_detection/models/model/faster_rcnn_resnet101_pets.config    --train_dir=/home/jesse/gpu-py3/models/research/object_detection/models/model/training_test/training/`

I am trying to train my dataset with `faster_rcnn_resnet101_pets.config` but it seems there's path problem, I checked similar issues and I tried relative and absolute paths, but same issue still there.

Thanks for your help !!

The whole error:-

```
(gpu-py3) jesse@jesse-System-Product-Name:~/gpu-py3/models/research$ python object_detection/train.py     --logtostderr     --pipeline_config_path=/home/jesse/gpu-py3/models/research/object_detection/models/model/faster_rcnn_resnet101_pets.config    --train_dir=/home/jesse/gpu-py3/models/research/object_detection/models/model/training_test/training/
/home/jesse/gpu-py3/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-04 14:37:15.629071: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-04 14:37:15.751553: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-04 14:37:15.751798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.86
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.29GiB
2018-06-04 14:37:15.751810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-06-04 14:37:15.899815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3245 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "object_detection/train.py", line 200, in <module>
    tf.app.run()
  File "/home/jesse/gpu-py3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 145, in main
    model_config, train_config, input_config = get_configs_from_pipeline_file()
  File "object_detection/train.py", line 103, in get_configs_from_pipeline_file
    text_format.Merge(f.read(), pipeline_config)
  File "/home/jesse/gpu-py3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/jesse/gpu-py3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/jesse/gpu-py3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/jesse/gpu-py3/models/research/object_detection/models/model/faster_rcnn_resnet101_pets.config; No such file or directory

```

**Comment by Abduoit** [comment]
The problem was with file `.config` I don't know why, it is corrupted for some reason. 
When I usually open any file (with gedit) I should see (on the left side at the upper bar) file name, then file path. But I noticed that there no file path for `.config` only file name. Anyway, I copied the content into another normal `.config`, then issue solved.

**Comment by AzinPoshtyar** [comment]
I had the same experience.
