### ISSUE TITLE
resnet-v1-50-beta for deeplab

### ISSUE THREAD

**Issue by Shanlans** [tensorflow/models#4464]
Hi
I noticed you updated Resnet-50 here. I want to try this on my own dataset. But cannot run correctly. 

python train.py --logtostderr --training_number_of_steps=30000 --learning_rate = 1e-5 --train_split="train" --model_variant="resnet_v1_50" --atrous_rates=6 --atrous_rates=12 --atrous_rates=18 --output_stride=16 --decoder_output_stride=4 --train_crop_size=512 --train_crop_size=512 --train_batch_size=4 --dataset="Lensdataset" --tf_initial_checkpoint="resnet_v1_50_2018_05_04\model.ckpt" --train_logdir="Log" --dataset_dir="datasets\Lensdataset\tfrecord" --fine_tune_batch_norm=True --initialize_last_layer=False --last_layers_contain_logits_only=True

Error:
File "train.py", line 396, in <module>
    tf.app.run()
  File "C:\Users\sunny\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 120, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "C:\Users\sunny\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "C:\Users\sunny\Anaconda3\envs\tensorflow\lib\site-packages\absl\flags\_flagvalues.py", line 623, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "C:\Users\sunny\Anaconda3\envs\tensorflow\lib\site-packages\absl\flags\_flagvalues.py", line 759, in _parse_args
    flag.parse(value)
  File "C:\Users\sunny\Anaconda3\envs\tensorflow\lib\site-packages\absl\flags\_flag.py", line 151, in parse
    self.value = self._parse(argument)
  File "C:\Users\sunny\Anaconda3\envs\tensorflow\lib\site-packages\absl\flags\_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --model_variant=None: value should be one of <xception_65|mobilenet_v2>

It seems I need modify somewhere to make the argument correct.

**Comment by derinozturk** [comment]
Were you able to get Resnet working? I had the same error but was able to fix it to get another error. I modified lines 45-46 in common.py to include 'resnet_v1_50'. However once I did that I get this error:

Traceback (most recent call last):
  File "/home/derin/models/research/deeplab/train.py", line 392, in <module>
    tf.app.run()
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/derin/models/research/deeplab/train.py", line 276, in main
    clones = model_deploy.create_clones(config, model_fn, args=model_args)
  File "/home/derin/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/derin/models/research/deeplab/train.py", line 205, in _build_deeplab
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/model.py", line 300, in multi_scale_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/model.py", line 466, in _get_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/model.py", line 369, in _extract_features
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/core/feature_extractor.py", line 259, in extract_features
    activation_fn=tf.nn.relu6 if use_bounded_activations else tf.nn.relu)
TypeError: resnet_arg_scope() got an unexpected keyword argument 'activation_fn'

**Comment by aquariusjay** [comment]
You should be able to use resnet model variants by changing line 45-46 in common.py as follows:

flags.DEFINE_string('model_variant', 'mobilenet_v2', 'DeepLab model variant.')

The slim version we are using is slightly different. Please also remove argument 'activation_fn' in this [line](https://github.com/tensorflow/models/blob/master/research/deeplab/core/feature_extractor.py#L259).
We are working on this fix along with other fixes. Sorry about the inconvenience.

**Comment by derinozturk** [comment]
@aquariusjay I removed the argument in feature_extractor.py at line 254 so that it now reads: 
arg_scope = arg_scopes_map[model_variant](
        weight_decay=weight_decay,
        batch_norm_decay=0.95,
        batch_norm_epsilon=1e-5,
        batch_norm_scale=True)
However, I'm now getting a new error:
Traceback (most recent call last):
  File "/home/derin/models/research/deeplab/train.py", line 394, in <module>
    tf.app.run()
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/derin/models/research/deeplab/train.py", line 278, in main
    clones = model_deploy.create_clones(config, model_fn, args=model_args)
  File "/home/derin/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/derin/models/research/deeplab/train.py", line 205, in _build_deeplab
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/model.py", line 300, in multi_scale_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/model.py", line 466, in _get_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/model.py", line 369, in _extract_features
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/home/derin/models/research/deeplab/core/feature_extractor.py", line 270, in extract_features
    use_bounded_activations=use_bounded_activations)
  File "/home/derin/models/research/deeplab/core/feature_extractor.py", line 335, in network_fn
    return func(preprocess_function(inputs), *args, **kwargs)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 334, in resnet_v1_50
    use_bounded_activations=use_bounded_activations)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

Is this related to the slim version difference you are mentioned?

**Comment by aquariusjay** [comment]
Hi derinozturk,

We are still trying to figure out the difference among slim versions. Regarding your issue:
1. stack_block_dense() function does take argument 'outputs_collections' (see [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/resnet_utils.py#L128)). I am not sure why the code breaks because of that.
2. Could you please try running 'resnet_v1_beta_test.py' ([here](https://github.com/tensorflow/models/blob/master/research/deeplab/core/resnet_v1_beta_test.py))?
3. In addition to remove the argument 'use_bounded_activations' in feature_extractor.py, you also need to remove them in resnet_v1_beta.py. This change is also included in the coming update.
4. If you just need a light-weight model, you could also try the provided xception_41 model variant.

Thanks,

**Comment by derinozturk** [comment]
@aquariusjay, after making the changes you outlined in point 3,I tried running resnet_v1_beta_test.py, I receive this output which shows the same 'output_collections' error from above:

======================================================================
ERROR: testAtrousFullyConvolutionalEndpointShapes (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 175, in testAtrousFullyConvolutionalEndpointShapes
    scope='resnet')
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testAtrousFullyConvolutionalUnknownHeightWidth (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 265, in testAtrousFullyConvolutionalUnknownHeightWidth
    output_stride=output_stride)
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testAtrousFullyConvolutionalValues (__main__.ResnetCompleteNetworkTest)
Verify dense feature extraction with atrous convolution.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 201, in testAtrousFullyConvolutionalValues
    output_stride=output_stride)
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testClassificationEndPoints (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 99, in testClassificationEndPoints
    scope='resnet')
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testClassificationEndPointsWithMultigrid (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 117, in testClassificationEndPointsWithMultigrid
    scope='resnet')
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testClassificationShapes (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 133, in testClassificationShapes
    scope='resnet')
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testFullyConvolutionalEndpointShapes (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 153, in testFullyConvolutionalEndpointShapes
    scope='resnet')
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testFullyConvolutionalUnknownHeightWidth (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 246, in testFullyConvolutionalUnknownHeightWidth
    global_pool=global_pool)
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

======================================================================
ERROR: testUnknownBatchSize (__main__.ResnetCompleteNetworkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resnet_v1_beta_test.py", line 228, in testUnknownBatchSize
    scope='resnet')
  File "resnet_v1_beta_test.py", line 89, in _resnet_small
    scope=scope)
  File "/home/derin/models/research/deeplab/core/resnet_v1_beta.py", line 214, in resnet_v1_beta
    store_non_strided_activations)
  File "/home/derin/anaconda2/envs/ml/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for keyword argument 'outputs_collections'

----------------------------------------------------------------------
Ran 10 tests in 2.096s

FAILED (errors=9)

**Comment by aquariusjay** [comment]
Thanks for the update.
It seems that the difference slim version may cause this problem.
Would you like to help dig more into slim? You could just run the resent_v1_beta_test.py and try to identify the problem.
If that will take too much of your time, I would suggest just use xception_41.

**Comment by aquariusjay** [comment]
@derinozturk 
huihui-personal has kindly helped resolve this issue (see his [merged pull request](https://github.com/tensorflow/models/pull/4534)). The problem should be gone. Please take it a shot and let us know if there is still any problem.
