### ISSUE TITLE
AttributeError: 'Deeplab' object has no attribute 'module'

### ISSUE THREAD

**Issue by TracesChen** [tensorflow/models#4469]
/home/ubuntu/anaconda3/envs/pytorch/bin/python /home/ubuntu/MaskTrack-master/training/train_offline.py --NoLabels 2 --lr 0.001 --wtDecay 0.001 --epochResume 0 --epochs 15 --batchSize 6
CUDA available
Traceback (most recent call last):
  File "/home/ubuntu/MaskTrack-master/training/train_offline.py", line 120, in <module>
    lr=base_lr, momentum=0.9, weight_decay=weight_decay)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/optim/sgd.py", line 57, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/optim/optimizer.py", line 39, in __init__
    self.add_param_group(param_group)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/optim/optimizer.py", line 146, in add_param_group
    param_group['params'] = list(params)
  File "/home/ubuntu/MaskTrack-master/training/utility_functions.py", line 34, in get_1x_lr_params_NOscale
    b.append(model.module.Scale.conv1)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'Deeplab' object has no attribute 'module'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by TracesChen** [comment]
@tensorflowbutler thanks for you ! this is a problem with the code

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
