### ISSUE TITLE
Tensorflow API multi channel

### ISSUE THREAD

**Issue by Shiro-LK** [tensorflow/models#4535]
### System information
- **What is the top-level directory of the model you are using**: ssd mobilenet v2
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**: anaconda
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**: N/AN
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: k80
- **Exact command to reproduce**:

### Describe the problem
I am trying to train the Tensorflow API on multiple channels (different from 3 channels). I followed this tutorial : https://github.com/minhnhat93/tf_object_detection_multi_channels but it seems there is a little problem. I tried to understand where the problem comes from and maybe it comes from  line 196 in data_decoder/tf_example_decoder.py : 

```
image = slim_example_decoder.ItemHandlerCallback(
          keys=['image/encoded', 'image/height', 'image/width', 'image/channels'],
          func=self._read_image
        )

  def _read_image(self, keys_to_tensors):
      image_encoded = keys_to_tensors['image/encoded']
      height = keys_to_tensors['image/height']
      width = keys_to_tensors['image/width']
      channels = keys_to_tensors['image/channels']
      to_shape = tf.cast(tf.stack([height, width, channels]), tf.int32)
      image = tf.reshape(tf.decode_raw(image_encoded, tf.uint8), to_shape)
      return image

```
Moreover, I think it could be a good feature to add to the original tensorflow repository. It can be usefull when we work on grayscale image(1 channel) or more channels (3<)
### Source code / logs
```
INFO:tensorflow:Error reported to Coordinator: Nan in summary histogram for: ModelVars/BoxPredictor_5/ClassPredictor_depthwise/BatchNorm/moving_variance
	 [[Node: ModelVars/BoxPredictor_5/ClassPredictor_depthwise/BatchNorm/moving_variance = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ModelVars/BoxPredictor_5/ClassPredictor_depthwise/BatchNorm/moving_variance/tag, BoxPredictor_5/ClassPredictor_depthwise/BatchNorm/moving_variance/read)]]
	 [[Node: FeatureExtractor/MobilenetV2/expanded_conv_5/expand/kernel/Regularizer/l2_regularizer/_551 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3224_...egularizer", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'ModelVars/BoxPredictor_5/ClassPredictor_depthwise/BatchNorm/moving_variance', defined at:
  File "models_multi/research/object_detection/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "models_multi/research/object_detection/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/models_multi/research/object_detection/trainer.py", line 338, in train
    model_var.op.name, model_var))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/summary.py", line 203, in histogram
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 283, in histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

```

EDIT: I also tried on image of 3 channels (instead of 4), it works for a while but I got after 400 steps the same error.
EDIT2 : Training on faster RCNN resnet50 (for 3 channels) seems to work better. But I cannot load the pre trained weight I get this error :  

`WARNING:root:Variable [FirstStageFeatureExtractor/resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta/Momentum] is not available in checkpoint
WARNING:root:Variable [FirstStageFeatureExtractor/resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/gamma/Momentum] is not available in checkpoint
WARNING:root:Variable [FirstStageFeatureExtractor/resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/weights/Momentum] is not available in checkpoint
WARNING:root:Variable [FirstStageFeatureExtractor/resnet_v1_50/block1/unit_1/bottleneck_v1/conv2/BatchNorm/beta/Momentum] is not available in checkpoint
WARNING:root:Variable [FirstStageFeatureExtractor/resnet_v1_50/block1/unit_1/bottleneck_v1/conv2/BatchNorm/gamma/Momentum] is not available in checkpoint
WARNING:root:Variable [FirstStageFeatureExtractor/resnet_v1_50/block1/unit_1/bottleneck_v1/conv2/weights/Momentum] is not available in checkpoint`

EDIT 3: with Faster RCNN (4 channels), I got this error : 

```
Traceback (most recent call last):
  File "models_multi/research/object_detection/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "models_multi/research/object_detection/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/models_multi/research/object_detection/trainer.py", line 401, in train
    saver=saver)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 747, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/supervisor.py", line 1000, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/supervisor.py", line 828, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/supervisor.py", line 989, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/supervisor.py", line 726, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/session_manager.py", line 279, in prepare_session
    config=config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/session_manager.py", line 207, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [7,7,4,64] rhs shape= [7,7,3,64]
	 [[Node: save/Assign_404 = Assign[T=DT_FLOAT, _class=["loc:@FirstStageFeatureExtractor/resnet_v1_50/conv1/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](FirstStageFeatureExtractor/resnet_v1_50/conv1/weights, save/RestoreV2:404)]]

Caused by op 'save/Assign_404', defined at:
  File "models_multi/research/object_detection/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "models_multi/research/object_detection/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/models_multi/research/object_detection/trainer.py", line 361, in train
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 494, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 185, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access


```

I need probably to change some other parameters but I do not know where exactly.

**Comment by pkulzc** [comment]
Yes multi-channel is a nice thing to have and we are planning on that. 
About your error when using 3 channels, did you try lower your learning rate?

**Comment by Shiro-LK** [comment]
I reduced the learning rate by a factor of 100 but I get the same error.

**Comment by cmbowyer13** [comment]
You need to modify the first convolutional weight matrix to match. In the .ckpt file you need to read in all the variables, and grab that first conv weight variable, and modify it accordingly. Then save that .ckpt file to some directory. Then, attempt to restart training, but fine tuning from that .ckpt file. So add another layer to the weight cake. 3->4 in depth dimension.

**Comment by Shiro-LK** [comment]
I think I found the problem. In tf_example_decoder.py I need to change the line 325 : 
`tensor_dict[fields.InputDataFields.image].set_shape([None, None,3])` . 3 has to be changed to the number of channels. To do that, I would like to use `self.keys_to_features['image/channels']` but I did not succeed to change it in int32/int64 format I got this error : 
`ValueError: Argument must be a dense tensor: FixedLenFeature(shape=(), dtype=tf.int64, default_value=3) - got shape [3], but wanted [3, 0].` using this : `num_chan = tf.cast( self.keys_to_features['image/channels'], tf.int64)` 
Why does it not working ?

**Comment by Krissy93** [comment]
@pkulzc sorry to bother you, do you have any info on the matter?
I know right now the API supports additional channels for training, but how do you export the model after that? I managed to train with 4 channels but I don't know how to use the model now.
If I export it using `export_inference_graph.py` giving it an input tensor of shape `[-1,-1,-1,4]`, the inference result is empty. I think the model needs explicitly the additional channels somehow to work correctly, since I guess the preprocess stage is in charge of combining the inputs... Is there anyone working on that?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
