### ISSUE TITLE
when python train.py ,if occured this .

### ISSUE THREAD

**Issue by heidongxianhau** [tensorflow/models#4536]
WARNING:tensorflow:From /home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/trainer.py:260: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 0 to match input file shards.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/trainer.py", line 274, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/builders/dataset_builder.py", line 186, in build
    process_fn, config.input_path[:], input_reader_config)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/object_detection-0.1-py2.7.egg/object_detection/utils/dataset_util.py", line 141, in read_dataset
    sloppy=config.shuffle))
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 901, in apply
    dataset = transformation_func(self)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 167, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 70, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 486, in add_to_graph
    self._create_definition_if_needed()
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 58, in tf_map_func
    dataset = map_func(nested_args)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/data/ops/readers.py", line 90, in __init__
    filenames, dtypes.string, name="filenames")
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 923, in convert_to_tensor
    as_ref=False)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1013, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/deeplearning/anaconda2/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 857, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32)'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by heidongxianhau** [comment]
thankyou.
as for my top-level directory, ../tensorflow/models/research/object_detection
and i just want to train my dataset on the original model in object_detection,ssd_inception_v2.
i run my model on ubuntu1604, and the tf version is 1.4.0, the version of CUDA is 8.0. and i have two gpu 1080ti,the memory is both 11G.
i run the model according the website  https://blog.csdn.net/w5688414/article/details/78970874  and https://blog.csdn.net/w5688414/article/details/78971205
but after i make the data ready,and I give the command: python3 train.py \  
--logtostderr  \  
--train_dir=training/ssd_inception_v2_whsyxt \  
--pipeline_config_path=training/ssd_inception_v2_whsyxt/ssd_inception_v2_coco.config  
Then i get the bug like the above.

**Comment by Jearcci** [comment]
Me too. have the  same problem.
~/tensorflow/models_v1/research/object_detection$ python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
WARNING:tensorflow:From /home/u18/tensorflow/models_v1/research/object_detection/trainer.py:260: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/u18/.conda/envs/condaten/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/u18/tensorflow/models_v1/research/object_detection/trainer.py", line 274, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/u18/tensorflow/models_v1/research/object_detection/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/home/u18/tensorflow/models_v1/research/object_detection/builders/dataset_builder.py", line 175, in build
    use_display_name=input_reader_config.use_display_name,
AttributeError: 'InputReader' object has no attribute 'use_display_name'

--Ubuntu 18.04
--Tensorflow-GPU 1.8
--Gpu: 1080ti

Could you help me?

**Comment by heidongxianhau** [comment]
I have got the problem, there maybe something wrong with your data-set. Please check your data images carefully.

**Comment by daher-alfawares** [comment]
I've solved this problem by making sure my config points to the tf record files correctly. hope this helps

**Comment by gar1t** [comment]
I don't feel I solved this problem because I don't understand it, but I made the error message go away in my case by indeed specifying the tf record locations using the pattern from the sample config files. Specifically I ensured that the `-?????-00010` suffix was included in the path. I had been omitting these in earlier work, which had worked fine. I'm not sure what changed here, but there it is.

**Comment by joeljosephjin** [comment]
> I've solved this problem by making sure my config points to the tf record files correctly. hope this helps

How do u do that?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
