### ISSUE TITLE
python ncf_main.py  AttributeError: 'float' object has no attribute '_unconditional_loss'

### ISSUE THREAD

**Issue by chongfaqin** [tensorflow/models#4549]
D:\anaconda3\python.exe D:/widedeep/dnnrecommend/recommendation/ncf_main.py
D:\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-15 17:12:47.470001: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
I0615 17:12:47.473455 16368 tf_logging.py:116] Data preprocessing...
I0615 17:12:52.540076 16368 tf_logging.py:116] Creating Estimator from Keras model...
Traceback (most recent call last):
  File "D:/widedeep/dnnrecommend/recommendation/ncf_main.py", line 335, in <module>
    absl_app.run(main)
  File "D:\anaconda3\lib\site-packages\absl\app.py", line 274, in run
    _run_main(main, argv)
  File "D:\anaconda3\lib\site-packages\absl\app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "D:/widedeep/dnnrecommend/recommendation/ncf_main.py", line 172, in main
    run_ncf(FLAGS)
  File "D:/widedeep/dnnrecommend/recommendation/ncf_main.py", line 194, in run_ncf
    layers, FLAGS.batch_size, FLAGS.mf_regularization,mlp_regularization)
  File "D:\widedeep\dnnrecommend\recommendation\official\recommendation\neumf_model.py", line 105, in __init__
    mf_user_latent = tf.keras.layers.Flatten()(mf_embedding_user(user_input))
  File "D:\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\base_layer.py", line 239, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "D:\anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 696, in __call__
    self.build(input_shapes)
  File "D:\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\base_layer.py", line 499, in wrapper
    output_shape = fn(instance, input_shape)
  File "D:\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\embeddings.py", line 122, in build
    dtype=self.dtype)
  File "D:\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\base_layer.py", line 201, in add_weight
    trainable=trainable)
  File "D:\anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 576, in add_variable
    self.add_loss(regularization)
  File "D:\anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 373, in add_loss
    loss._unconditional_loss = True  # pylint: disable=protected-access
AttributeError: 'float' object has no attribute '_unconditional_loss'

Process finished with exit code 1

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chongfaqin** [comment]
![image](https://user-images.githubusercontent.com/40291854/41504489-20c77564-7223-11e8-82db-d526e9214ab8.png)
OS Platform is win10
Tensorflow 1.7.0
anaconda 3
memory
python ncf_main.py

**Comment by robieta** [comment]
This is because your tensorflow version is too old; official models are only guaranteed for the tf-nightly. Unfortunately this also occurs in tf 1.8 (the latest anaconda tf build, which Google does not control) so you'll either need to build from source or use pip (since we do maintain up to date tf-nightly and tf-nightly-gpu packages).

**Comment by chongfaqin** [comment]
@robieta thanks，but tensorflow 1.8  still wrong.

**Comment by robieta** [comment]
Yes, that's what I was saying. 1.8 is still too old.

**Comment by chongfaqin** [comment]
Thanks ,1.9 is ok.
