### ISSUE TITLE
AttributeError: 'KeepAspectRatioResizer' object has no attribute 'per_channel_pad_value'

### ISSUE THREAD

**Issue by azemZejnil** [tensorflow/models#4561]
So, I trained an object detection model and now I want to export .ckpt files. When I try to export the .ckpt files:
`python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training3/model.ckpt-47816 --output_directory inference_graph`

I get this:

```
Traceback (most recent call last):
  File "export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "/home/ubuntu/tensorflow1/models/research/object_detection/exporter.py", line 454, in export_inference_graph
    is_training=False)
  File "/home/ubuntu/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 101, in build
    add_summaries)
  File "/home/ubuntu/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 274, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "/home/ubuntu/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/builders/image_resizer_builder.py", line 83, in build
    if keep_aspect_ratio_config.per_channel_pad_value:

AttributeError: 'KeepAspectRatioResizer' object has no attribute 'per_channel_pad_value'
```

It seems that everybody has this working fine and have no problems with this. Could anyone please tell me what is going on here?
Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
This was fixed in [commit](https://github.com/tensorflow/models/commit/9adf02423db3e1450b703f33b2f3863f07abcbb0#diff-84c8ce31554add44ab9abffe6f79cffb). Feel free to reopen the issue if the problem still persists. Thanks!
