### ISSUE TITLE
TypeError: resize_images() got an unexpected keyword argument 'size'

### ISSUE THREAD

**Issue by huanggengxin** [tensorflow/models#457]
Sorry,When I run the training script.
## Please let us know which model this issue is about (specify the top-level directory)
# Directory containing preprocessed MSCOCO data.
MSCOCO_DIR="${HOME}/im2txt/data/mscoco"

# Inception v3 checkpoint file.
INCEPTION_CHECKPOINT="${HOME}/im2txt/data/inception_v3.ckpt"

# Directory to save the model.
MODEL_DIR="${HOME}/im2txt/model"

# Build the model.
bazel build -c opt --config=cuda im2txt/...

# Run the training script.
bazel-bin/im2txt/train \
  --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256" \
  --inception_checkpoint_file="${INCEPTION_CHECKPOINT}" \
  --train_dir="${MODEL_DIR}/train" \
  --train_inception=false \
  --number_of_steps=1000000

this is the terminal imformation:
will@Will-Air ~/tensorflow/tensorflow/models/im2txt $ bazel-bin/im2txt/train   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=1000000
INFO:tensorflow:Prefetching values from 256 files matching /home/will/im2txt/data/mscoco/train-?????-of-00256
Traceback (most recent call last):
  File "/home/will/tensorflow/tensorflow/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/will/tensorflow/tensorflow/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/home/will/tensorflow/tensorflow/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 352, in build
    self.build_inputs()
  File "/home/will/tensorflow/tensorflow/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 165, in build_inputs
    image = self.process_image(encoded_image, thread_id=thread_id)
  File "/home/will/tensorflow/tensorflow/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 119, in process_image
    image_format=self.config.image_format)
  File "/home/will/tensorflow/tensorflow/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/image_processing.py", line 113, in process_image
    method=tf.image.ResizeMethod.BILINEAR)
TypeError: resize_images() got an unexpected keyword argument 'size'

I use python 2.7 and tensorflow r0.10 base on linux mint 17.
Looking for your answer.
Thanks!

**Comment by imaxpayne** [comment]
here is the solution that works for me:

> http://stackoverflow.com/questions/39672514/error-when-training-im2txt-model

The author actually fixed this problem, so I closed the issue I opend.

**Comment by huanggengxin** [comment]
@imaxpayne  Thanks for your help .The problem was fixed.Thank you very much!

**Comment by huanggengxin** [comment]
Thank you very much!

2016-09-27 2:51 GMT+08:00 imaxpayne <notifications@github.com>:
