### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by santanu-2018** [tensorflow/models#4593]
### System Information

-  **What is the top-level directory of the model I am using**: /models/research/differential_privacy/multiple_teachers 

- **Have I written custom code**: No

- **OS Platform and Distribution**:Linux Ubuntu 18.04

- **TensorFlow installed from**: conda

- **TensorFlow version**:1.8.0

- **Bazel version**: N/A

- **CUDA/cuDNN version**:N/A (I dont have GPU)

- **GPU model and memory**: N/A

- **Exact command to reproduce**:Train two teachers,
python train_teachers.py --nb_teachers=250 --teacher_id=0 --dataset=mnist --train_dir=train_dir --data_dir=data_dir
python train_teachers.py --nb_teachers=250 --teacher_id=1 --dataset=mnist --train_dir=train_dir --data_dir=data_dir

### Describe the Problem
Hi, I am getting an error when I try to run the code of differential_privacy using multiple teachers. When I run the command 
"python train_teachers.py --nb_teachers=250 --teacher_id=0 --dataset=mnist --train_dir=train_dir --data_dir=data_dir", 
I get the following error:

### Source Code/Logs

Traceback (most recent call last):
  File "train_teachers.py", line 104, in <module>
    tf.app.run()
  File "/home/santanu/miniconda/envs/fedlearn/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_teachers.py", line 101, in main
    assert train_teacher(FLAGS.dataset, FLAGS.nb_teachers, FLAGS.teacher_id)
  File "train_teachers.py", line 63, in train_teacher
    train_data, train_labels, test_data, test_labels = input.ld_mnist()
  File "/home/santanu/Downloads/models-master/research/differential_privacy/multiple_teachers/input.py", line 386, in ld_mnist
    train_data = extract_mnist_data(local_urls[0], 60000, 28, 1)
  File "/home/santanu/Downloads/models-master/research/differential_privacy/multiple_teachers/input.py", line 274, in extract_mnist_data
    return np.load(file_obj)
  File "/home/santanu/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 404, in load
    magic = fid.read(N)
  File "/home/santanu/miniconda/envs/fedlearn/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 127, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/santanu/miniconda/envs/fedlearn/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 95, in _prepare_value
    return compat.as_str_any(val)
  File "/home/santanu/miniconda/envs/fedlearn/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 113, in as_str_any
    return as_str(value)
  File "/home/santanu/miniconda/envs/fedlearn/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 86, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

Any suggestion how to overcome it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
