### ISSUE TITLE
object_detection: trainer.py:260: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by Jearcci** [tensorflow/models#4612]
~/tensorflow/models_v1/research/object_detection$ python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

WARNING:tensorflow:From /home/u18/tensorflow/models_v1/research/object_detection/trainer.py:260: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
File "train.py", line 184, in 
tf.app.run()
File "/home/u18/.conda/envs/condaten/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
_sys.exit(main(argv))
File "train.py", line 180, in main
graph_hook_fn=graph_rewriter_fn)
File "/home/u18/tensorflow/models_v1/research/object_detection/trainer.py", line 274, in train
train_config.prefetch_queue_capacity, data_augmentation_options)
File "/home/u18/tensorflow/models_v1/research/object_detection/trainer.py", line 59, in create_input_queue
tensor_dict = create_tensor_dict_fn()
File "train.py", line 121, in get_next
dataset_builder.build(config)).get_next()
File "/home/u18/tensorflow/models_v1/research/object_detection/builders/dataset_builder.py", line 175, in build
use_display_name=input_reader_config.use_display_name,
AttributeError: 'InputReader' object has no attribute 'use_display_name'

--Ubuntu 18.04
--Tensorflow-GPU 1.8
--Gpu: 1080ti

Could you help me ?
Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mri1939** [comment]
@Jearcci Just run the command below from `/models/research` directory : 
`protoc object_detection/protos/*.proto --python_out=`

**Comment by Jearcci** [comment]
Thank you very much.
It worked 
after /models/research directory :
protoc object_detection/protos/*.proto --python_out=. 
=>again
Sorry 
And  Thank you for your help.

**Comment by masterchop** [comment]
This doesnt fix it for me, what am i missing? all my protos were built
