### ISSUE TITLE
Issue in /research/global_objectives code

### ISSUE THREAD

**Issue by anuragsodhi** [tensorflow/models#4638]
The loss_layers_example.py returns the following error:

"TypeError: Fetch argument dict_values([<tf.Variable 'precision_at_recall/lambdas:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'precision_at_recall/div:0' shape=(1,) dtype=float32>, <tf.Tensor 'precision_at_recall/Sum_2:0' shape=(1,) dtype=float32>, <tf.Tensor 'precision_at_recall/Sum_3:0' shape=(1,) dtype=float32>]) has invalid type <class 'dict_values'>, must be a string or Tensor. (Can not convert a dict_values into a Tensor or Operation."

Also, the loss layers code is not functioning as it should. I tried P@R and R@P but it does not train the model such that target value of precision or recall is kept as the specified level.

What is the top-level directory of the model you are using: /tensorflow/models/tree/master/research/global_objectives
Have I written custom code: No
OS Platform and Distribution: Windows 10, Python 3.6.5
TensorFlow installed from: pip installed official tensorflow 1.8 
TensorFlow version: v1.8
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A - Intel Onboard graphics 
Exact command to reproduce: ran loss_layers_example.py

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karmel** [comment]
Thanks @anuragsodhi - can you clarify how you ran the file? What were the commands you used to run, and can you provide the full error trace?

**Comment by anuragsodhi** [comment]
I downloaded all the files to global_objectives folder and from within that directory I ran loss_layers_examples.py from spyder. I had to change two import lines before that.
1. Changed "from global_objectives import loss_layers" to "import loss_layers" in the loss_layers_example.py
2. Changed  "from global_objectives import util" to "import util" in the loss_layers.py

Full error trace:

Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

runfile('C:/Users/sodhian/Documents/backup/learning/global_objectives/global_objectives/loss_layers_example.py', wdir='C:/Users/sodhian/Documents/backup/learning/global_objectives/global_objectives')
Traceback (most recent call last):

  File "<ipython-input-1-8661fc2fd6c6>", line 1, in <module>
    runfile('C:/Users/sodhian/Documents/backup/learning/global_objectives/global_objectives/loss_layers_example.py', wdir='C:/Users/sodhian/Documents/backup/learning/global_objectives/global_objectives')

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/sodhian/Documents/backup/learning/global_objectives/global_objectives/loss_layers_example.py", line 213, in <module>
    tf.app.run()

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))

  File "C:/Users/sodhian/Documents/backup/learning/global_objectives/global_objectives/loss_layers_example.py", line 203, in main
    global_objectives_loss_precision = train_model(experiment_data, True)

  File "C:/Users/sodhian/Documents/backup/learning/global_objectives/global_objectives/loss_layers_example.py", line 181, in train_model
    go_outputs = sess.run(other_outputs.values())

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 427, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 253, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)

  File "C:\Users\sodhian\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 286, in __init__
    (fetch, type(fetch), str(e)))

TypeError: Fetch argument dict_values([<tf.Variable 'precision_at_recall/lambdas:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'precision_at_recall/div:0' shape=(1,) dtype=float32>, <tf.Tensor 'precision_at_recall/Sum_2:0' shape=(1,) dtype=float32>, <tf.Tensor 'precision_at_recall/Sum_3:0' shape=(1,) dtype=float32>]) has invalid type <class 'dict_values'>, must be a string or Tensor. (Can not convert a dict_values into a Tensor or Operation.)

**Comment by tcl326** [comment]
I think this issue is caused by the incompatibility between Python2 and Python3. We can resolve this problem by simply changing other_outputs.values() to list(other_outputs.values()). Let me know if I should do a PR on this.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
