### ISSUE TITLE
Adversarial_text with Bidirectional LSTM on IMDB: Matmul dimensions must be equal, but are 512 and 1024

### ISSUE THREAD

**Issue by kmeng01** [tensorflow/models#4649]
### System information
- **OS**: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-104-generic x86_64)
- **TensorFlow installed from**: `pip install --upgrade tensorflow-gpu`
- **TensorFlow version**: 1.8.0
- **CUDA/cuDNN version**: CUDA Version 9.0.176
- **GPU model and memory**: GTX 1080Ti 11GB GDDR5X
- **Exact command to reproduce**: 
```bash
$ python pretrain.py \
--train_dir=$PTDIR \
--data_dir=$IMDBDIR \
--vocab_size=87007 \
--embedding_dims=256 \
--rnn_cell_size=512 \
--num_candidate_samples=1024 \
--batch_size=64 \
--learning_rate=0.001 \
--learning_rate_decay_factor=0.9999 \
--max_steps=100000 \
--max_grad_norm=1.0 \
--num_timesteps=400 \
--keep_prob_emb=0.5 \
--normalize_embeddings \
--bidir_lstm=True

$ python train_classifier.py \
--train_dir=$TDIR \
--pretrained_model_dir=$PTDIR \
--data_dir=$IMDBDIR \
--vocab_size=87007 \
--embedding_dims=256 \
--rnn_cell_size=512 \
--cl_num_layers=1 \
--cl_hidden_size=30 \
--batch_size=64 \
--learning_rate=0.0005 \
--learning_rate_decay_factor=0.9998 \
--max_steps=15000 \
--max_grad_norm=1.0 \
--num_timesteps=400 \
--keep_prob_emb=0.5 \
--normalize_embeddings \
--adv_training_method=vat \
--perturb_norm_length=5.0 \
--bidir_lstm=True
```

### Describe the problem
I am attempting to train the adversarial_text model with a bidirectional lstm on the example `IMDB` dataset. The uni-lstm has already worked correctly. To accomplish this, I have:
1. copied over the `pretrain.py` and `train_classifier.py` commands
2. added the `bidir_lstm=True` flag
3. changed the `rnn_cell_size` to `512` and `embedding_dims` to `256`, which is what the [paper](https://arxiv.org/pdf/1605.07725.pdf) for this code states is the difference in hyperparameters between training the uni-lstm and bidir-lstm.

When I run `pretrain.py`, the code works perfectly fine. However, afterwards, when I run `train_classifier.py`, the code errors with the stack trace shown below. 
I have noticed that if I run `pretrain.py` with the `bidir_lstm=True` flag and `train_classifier.py` without, it works fine. But is that the intended behavior? Thank you for the assistance.

### Stack track log
```bash
Traceback (most recent call last):
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 512 and 1024 for 'cl_logits/dense_2/Tensordot/MatMul' (op: 'MatMul') with input shapes: [51200,512], [1024,30].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_classifier.py", line 68, in <module>
    tf.app.run()
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_classifier.py", line 58, in main
    train_op, loss, global_step = model.classifier_training()
  File "/home/exx/vat-repro/gan-text/models/research/adversarial_text/graphs.py", line 157, in classifier_training
    loss = self.classifier_graph()
  File "/home/exx/vat-repro/gan-text/models/research/adversarial_text/graphs.py", line 432, in classifier_graph
    embedded, return_intermediates=True)
  File "/home/exx/vat-repro/gan-text/models/research/adversarial_text/graphs.py", line 545, in cl_loss_from_embedding
    logits = self.layers['cl_logits'](lstm_out)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/network.py", line 634, in call
    mask=masks)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/network.py", line 805, in _run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 157, in call
    [0]])
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 3004, in tensordot
    ab_matmul = matmul(a_reshape, b_reshape)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2122, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4279, in mat_mul
    name=name)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/exx/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 512 and 1024 for 'cl_logits/dense_2/Tensordot/MatMul' (op: 'MatMul') with input shapes: [51200,512], [1024,30].
````

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
Bazel version

**Comment by tigerhli** [comment]
I got the same problem. 
In cl_loss_from_embedding of graphs.py, 
lstm_out = tf.concat(lstm_outs, 1) try to Concatenate output of forward and reverse LSTMs,
but the dimension of lstm_outs is [batch_size, max_time, cell.output_size], so if concat at 1 dimension as the code, it concatented at max_time, then getting this problem.
If change the code to:
lstm_out = tf.concat(lstm_outs, 2) # Concatenate output of forward and reverse LSTMs, the code can work.

I ran this code months ago and didn't get this problem. When I git the new codes yesterday, this happened.  I'm very confused.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
