### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: A\A10.jpg : The system cannot find the path specified.  ; No such process

### ISSUE THREAD

**Issue by Shazuka** [tensorflow/models#4657]
CRITICAL:tensorflow:File does not exist A\A10.jpg
Traceback (most recent call last):
  File "C:\Users\naveed\Desktop\sign-language-alphabet-recognizer-master\train.py", line 1024, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\naveed\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\naveed\Desktop\sign-language-alphabet-recognizer-master\train.py", line 768, in main
    bottleneck_tensor)
  File "C:\Users\naveed\Desktop\sign-language-alphabet-recognizer-master\train.py", line 395, in cache_bottlenecks
    jpeg_data_tensor, bottleneck_tensor)
  File "C:\Users\naveed\Desktop\sign-language-alphabet-recognizer-master\train.py", line 343, in get_or_create_bottleneck
    bottleneck_tensor)
  File "C:\Users\naveed\Desktop\sign-language-alphabet-recognizer-master\train.py", line 297, in create_bottleneck_file
    image_data = gfile.FastGFile(image_path, 'rb').read()
  File "C:\Users\naveed\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 120, in read
    self._preread_check()
  File "C:\Users\naveed\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\naveed\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: A\A10.jpg : The system cannot find the path specified.

; No such process
Having this problem while retraining the model with the new dataset. Kindly help me to solve the problem.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by soumen29dec** [comment]
i have created csv files using xml_to_csv.py. while i am running generate_tfrecord.py to create TFrecord, it is giving following error.:
Traceback (most recent call last):
  File "generate_tfrecord.py", line 117, in <module>
    tf.app.run()
  File "C:\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 108, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 63, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:/Anaconda/envs/tf_gpu/Lib/site-packages/tensorflow/models/research/workspace/hand_demo/images/1390.jpg : The system cannot find the file specified.
; No such file or directory
i have checked manually in csv files there is no mismatch between count of images and xml files - could you please resolve this issue for me? i have been struggling for quite a while. Thank you!

**Comment by dhruvagupta2014** [comment]
Hi,

I'm getting a similar error on Windows : 

File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\dhruva.gupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\dhruva.gupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "train.py", line 108, in main
    overwrite=True)
  File "C:\Users\dhruva.gupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 397, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "C:\Users\dhruva.gupta\AppData\Local\Continuum\anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open:  : The system cannot find the path specified.
; No such process

Is anyone looking into this ?

**Comment by vatsalkansara2** [comment]
im having same issue
CUDA 10
tensorflow-gpu 1.14
WIndows 10
im using object_detection api from tensorflow
Nvidia 1060 16 gb ram.

**Comment by skshashankkumar41** [comment]
Any Solution??

**Comment by Hykrow** [comment]
still noting found to fix it?

**Comment by pamrani** [comment]
![image](https://user-images.githubusercontent.com/34957346/71551817-cd931300-2a11-11ea-99af-ee84646b6d19.png)

**Comment by akhileshgandhe7** [comment]
> im having same issue
> CUDA 10
> tensorflow-gpu 1.14
> WIndows 10
> im using object_detection api from tensorflow
> Nvidia 1060 16 gb ram.
> ![Capture](https://user-images.githubusercontent.com/25883523/60828443-058e6b80-a1d0-11e9-94c9-24766a43b747.PNG)

I too faced the same issue. Try giving the image_dir path in the commandline along with the csv input and tfrecord path.

**Comment by stijojoseph** [comment]
still no solution?

**Comment by shivprasad94** [comment]
i had same issue, but this had something to do with my images/train folder and respective xml files miss match and label.csv

even if there is small issue/ miss match in images and xml you will get error...

step 1 : check - image/train/cat1.jpg
step 2 : check the file name col data in your- train_labels.csv
the name should be exactly matching in images/train and train_labels.csv (verify with all images,xml)

once everything is done run below command..

python generate_tfrecord.py --csv_input=images/train_labels.csv --image_dir=images/train --output_path=train.record

**Comment by louiselumapas** [comment]
Also experiencing same issue.  The filenames in my csv are fine, no mismatch. 

I followed this tutorial: https://www.youtube.com/watch?v=kq2Gjv_pPe8&list=PLQVvvaa0QuDcNK5GeCQnxYnSSaar2tpku&index=4

``` Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 299,
in run
    _run_main(main, args)
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 250,
in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 46, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: image3.jpg
: The system cannot find the file specified.
; No such file or directory

lumapas.ml@NSP-336PXVC MINGW64 ~/Desktop/object_detection
$ tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: image3.j
pg
bash: tensorflow.python.framework.errors_impl.NotFoundError:: command not found

lumapas.ml@NSP-336PXVC MINGW64 ~/Desktop/object_detection
$ python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record
WARNING:tensorflow:From generate_tfrecord.py:100: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From generate_tfrecord.py:86: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

W0501 20:06:25.868197 10748 deprecation_wrapper.py:119] From generate_tfrecord.py:86: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

WARNING:tensorflow:From generate_tfrecord.py:45: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0501 20:06:25.875191 10748 deprecation_wrapper.py:119] From generate_tfrecord.py:45: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 299,
in run
    _run_main(main, args)
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 250,
in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 46, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: image3.jpg
: The system cannot find the file specified.
; No such file or directory

lumapas.ml@NSP-336PXVC MINGW64 ~/Desktop/object_detection
$ python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record
WARNING:tensorflow:From generate_tfrecord.py:100: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From generate_tfrecord.py:86: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

W0501 20:07:12.875063 17556 deprecation_wrapper.py:119] From generate_tfrecord.py:86: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

WARNING:tensorflow:From generate_tfrecord.py:45: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0501 20:07:12.883063 17556 deprecation_wrapper.py:119] From generate_tfrecord.py:45: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 299,
in run
    _run_main(main, args)
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 250,
in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 46, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\lumapas.ml\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: image3.jpg
: The system cannot find the file specified.
; No such file or directory ```

**Comment by 1advait** [comment]
I am also having the same issue :
cuda 9
windows 10
cudnn 7.1.3
tensorflow==1.5
![issue](https://user-images.githubusercontent.com/75311266/106375426-eb1f7280-63b1-11eb-9931-82f511591c10.png)
pleaase any one help me.

**Comment by aravinthk00** [comment]
(myenv) C:\Users\Downloads\Function-level>python main.py --config config\config.yaml --data_dir=data\ --embedding ELMo
Using TensorFlow backend.
2022-08-11 10:41:35.159324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
[INFO] Start training process....
[INFO] Loading data from C:\Users\30863\Downloads\Function-level\data\....
[INFO] The length of the loaded data list is : 622
[INFO] Applying ELMo model!
[INFO] Setting padding length 1000 for ELMo model. Each textual sequence contains 1000 elements.
[INFO] Patition the data ....
[INFO] Data processing completed!
[INFO] -------------------------------------------------------
[INFO] There are 397 total samples in the training set. 28 vulnerable samples.
[INFO] There are 100 total samples in the validation set. 8 vulnerable samples.
[INFO] -------------------------------------------------------
2022-08-11 10:41:37.696665: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2022-08-11 10:41:37.706766: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-08-11 10:41:37.706953: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-11 10:41:37.714121: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 30863-436055
2022-08-11 10:41:37.715064: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 30863-436055
[INFO] No GPU detected.
[INFO] Using CPU for training. It may take considerable time!
[INFO] Loading the elmo model.
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    helper.exec()
  File "C:\Users\30863\Downloads\Function-level\src\helper.py", line 251, in exec
    model_func = elmo_network.build_elmo_network(GPU_flag)
  File "C:\Users\30863\Downloads\Function-level\src\models\elmo_network.py", line 43, in build_elmo_network
    elmo_embedding = Lambda(self.make_elmo_embedding, output_shape=(None, 1024))(elmo_input)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\keras\engine\base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\keras\layers\core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "C:\Users\30863\Downloads\Function-level\src\models\elmo_network.py", line 35, in make_elmo_embedding
    elmo_model = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\module.py", line 157, in __init__
    self._spec = as_module_spec(spec)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\module.py", line 30, in as_module_spec
    return load_module_spec(spec)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\module.py", line 65, in load_module_spec
    return registry.loader(path)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\registry.py", line 51, in __call__
    return impl(*args, **kwargs)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\native_module.py", line 139, in __call__
    module_def_proto = self._get_module_def_proto(path)
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_hub\native_module.py", line 130, in _get_module_def_proto
    module_def_proto.ParseFromString(f.read())
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\30863\Anaconda3\envs\myenv\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\30863\AppData\Local\Temp\tfhub_modules\9bb74bc86f9caffc8c47dd7b33ec4bb354d9602d\tfhub_module.pb : The system cannot find the file specified.
; No such file or directory

Anyone give me clear solution and why this error raised ? thanks in advance ...
