### ISSUE TITLE
UnrecognizedFlagError: Unknown command line flag 'p'

### ISSUE THREAD

**Issue by JingLiJJ** [tensorflow/models#4716]
For Attention_ocr, while executing python -m unittest discover -p '*_test.py', I am getting an error unknown command line flag 'p'. I don't know how to solve it....

======================================================================
ERROR: test_correct_results_on_test_data (demo_inference_test.DemoInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jj301440/models/research/attention_ocr/python/demo_inference_test.py", line 49, in test_correct_results_on_test_data
    image_path_pattern)
  File "/home/jj301440/models/research/attention_ocr/python/demo_inference.py", line 75, in run
    dataset_name)
  File "/home/jj301440/models/research/attention_ocr/python/demo_inference.py", line 59, in create_model
    dataset = common_flags.create_dataset(split_name=FLAGS.split_name)
  File "/home/jj301440/.conda/envs/jj_27/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/jj301440/.conda/envs/jj_27/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
UnrecognizedFlagError: Unknown command line flag 'p'

======================================================================
ERROR: test_moving_variables_properly_loaded_from_a_checkpoint (demo_inference_test.DemoInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jj301440/models/research/attention_ocr/python/demo_inference_test.py", line 26, in test_moving_variables_properly_loaded_from_a_checkpoint
    dataset_name)
  File "/home/jj301440/models/research/attention_ocr/python/demo_inference.py", line 59, in create_model
    dataset = common_flags.create_dataset(split_name=FLAGS.split_name)
  File "/home/jj301440/.conda/envs/jj_27/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/jj301440/.conda/envs/jj_27/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
UnrecognizedFlagError: Unknown command line flag 'p'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JingLiJJ** [comment]
When I run _test.py files one by one, there was no such error. However, when I used python -m unittest discover -p  '*_test.py', then this error occurred.

**Comment by WilliamL1** [comment]
@JingLiJJ @tensorflowbutler  I have the same issue like yours, it works when just run 'python *_test.py ',  but error occurred when `python -m unittest discover -p '*_test.py' was run`. 
================
Device Info:
Tensorflow Version is 1.9.0 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
CUDA Version 9.2.148
GPU mem 16G
Python 2.7.12
================

**Comment by ganliqiang** [comment]
i get the same error  who can give us help to solve this problem

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
