### ISSUE TITLE
Cannot use custom dataset in official resnet model, raised tensorflow.python.framework.errors_impl.CancelledError.

### ISSUE THREAD

**Issue by JustinhoCHN** [tensorflow/models#4724]
These days I modified the official ```cifar10_main.py``` , in order to train the kaggle dogs_cats_redux dataset.

First, I created the tfrecord files, following the standard pipeline, you guys can download the tfrecord files [here.](https://drive.google.com/open?id=1P7zGwxIY0ynFAN5PrmK71IMu51m4U2Rt)

And then, I wrote some tfrecord parsing functions and dogs_cats_model class, just like the following code:
```
def read_and_decode(filename):
    filename_queue = tf.train.string_input_producer([filename])

    reader = tf.TFRecordReader()
    _, serialized_example = reader.read(filename_queue)
    features = tf.parse_single_example(serialized_example,
                                       features={'label': tf.FixedLenFeature([], tf.int64),
                                                 'img_raw': tf.FixedLenFeature([], tf.string)})
    img = tf.decode_raw(features['img_raw'], tf.uint8)
    img = tf.reshape(img, [_HEIGHT, _WIDTH, _NUM_CHANNELS])
    img = tf.cast(img, tf.float32)
    img = tf.image.per_image_standardization(img)
    label = tf.cast(features['label'], tf.int32)
    label = tf.one_hot(label, _NUM_CLASSES)

    return img, label

class DogsCatsModel(resnet_model.Model):
    """Model class with appropriate defaults for dogs_cats_redux data."""

    def __init__(self, resnet_size, data_format=None, num_classes=_NUM_CLASSES,
                 version=resnet_model.DEFAULT_VERSION):
        """These are the parameters that work for CIFAR-10 data.

    Args:
      resnet_size: The number of convolutional layers needed in the model.
      data_format: Either 'channels_first' or 'channels_last', specifying which
        data format to use when setting up the model.
      num_classes: The number of output classes needed from the model. This
        enables users to extend the same model to their own datasets.
      version: Integer representing which version of the ResNet network to use.
        See README for details. Valid values: [1, 2]

    Raises:
      ValueError: if invalid resnet_size is chosen
    """
        if resnet_size % 6 != 2:
            raise ValueError('resnet_size must be 6n + 2:', resnet_size)

        num_blocks = (resnet_size - 2) // 6

        super(DogsCatsModel, self).__init__(
            resnet_size=resnet_size,
            bottleneck=True,
            num_classes=num_classes,
            num_filters=16,
            kernel_size=3,
            conv_stride=1,
            first_pool_size=None,
            first_pool_stride=None,
            second_pool_size=8,
            second_pool_stride=1,
            block_sizes=[num_blocks] * 3,
            block_strides=[1, 2, 2],
            final_size=64,
            version=version,
            data_format=data_format)

def dogscats_model_fn(features, labels, mode, params):
    """Model function for dogs_cats_redux data."""
    features = tf.reshape(features, [-1, _HEIGHT, _WIDTH, _NUM_CHANNELS])

    learning_rate_fn = resnet_run_loop.learning_rate_with_decay(
        batch_size=params['batch_size'], batch_denom=128,
        num_images=_NUM_IMAGES['train'], boundary_epochs=[100, 150, 200],
        decay_rates=[1, 0.1, 0.01, 0.001])

    # We use a weight decay of 0.0002, which performs better
    # than the 0.0001 that was originally suggested.
    weight_decay = 2e-4

    # Empirical testing showed that including batch_normalization variables
    # in the calculation of regularized loss helped validation accuracy
    # for the CIFAR-10 dataset, perhaps because the regularization prevents
    # overfitting on the small data set. We therefore include all vars when
    # regularizing and computing loss during training.
    def loss_filter_fn(_):
        return True

    return resnet_run_loop.resnet_model_fn(features, labels, mode, DogsCatsModel,
                                           resnet_size=params['resnet_size'],
                                           weight_decay=weight_decay,
                                           learning_rate_fn=learning_rate_fn,
                                           momentum=0.9,
                                           data_format=params['data_format'],
                                           version=params['version'],
                                           loss_filter_fn=loss_filter_fn,
                                           multi_gpu=params['multi_gpu'])

def main(argv):
    parser = resnet_run_loop.ResnetArgParser()
    # Set defaults that are reasonable for this model.
    parser.set_defaults(data_dir='/tmp/cifar10_data',
                        model_dir='/tmp/cifar10_model',
                        resnet_size=32,
                        train_epochs=250,
                        epochs_between_evals=10,
                        batch_size=32)

    flags = parser.parse_args(args=argv[1:])

    input_function = flags.use_synthetic_data and get_synth_input_fn() or input_fn

    resnet_run_loop.resnet_main(
        flags, dogscats_model_fn, input_function,
        shape=[_HEIGHT, _WIDTH, _NUM_CHANNELS])
```
And the rest of the code remain the same as the original resnet repo, you guys can check my ```main.py``` [here](https://gist.github.com/JustinhoCHN/d6d4534d322595dc562ff0d0d59b8a59).

But when I run the ```main.py```, it raised the CancelledError:

```
(tf) jto@jto:~/projects/dogs_cats_tf/official/resnet$ python main.py --data_dir='/home/jto/dataset/cats_dogs_redux/' --batch_size=32 --resnet_size=50 --ver
sion=2 --num_parallel_calls=1                                                                                                                              
INFO:tensorflow:Using config: {'_is_chief': True, '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_save_summary_steps': 100, '_task_id': 0, '_trai
n_distribute': None, '_service': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSp
ec object at 0x7f9c32a104e0>, '_save_checkpoints_steps': None, '_evaluation_master': '', '_model_dir': '/tmp/cifar10_model', '_num_ps_replicas': 0, '_save_
checkpoints_secs': 1000000000.0, '_tf_random_seed': None, '_log_step_count_steps': 100, '_global_id_in_cluster': 0, '_session_config': allow_soft_placement
: true
, '_num_worker_replicas': 1}
Starting a training cycle.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-07-09 18:35:22.255463: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compile
d to use: AVX2 FMA
2018-07-09 18:35:22.326229: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but t
here must be at least one NUMA node, so returning NUMA node zero
2018-07-09 18:35:22.326586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.24GiB
2018-07-09 18:35:22.326600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-09 18:35:22.462426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-09 18:35:22.462448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-09 18:35:22.462455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-09 18:35:22.462609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:
0 with 9912 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

......

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 326, in <module>
    main(argv=sys.argv)
  File "main.py", line 321, in main
    shape=[_HEIGHT, _WIDTH, _NUM_CHANNELS])
  File "/home/jto/projects/dogs_cats_tf/official/resnet/resnet_run_loop.py", line 396, in resnet_main
    max_steps=flags.max_train_steps)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 859, in _train_model_default
    saving_listeners)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1059, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1043, in run
    run_metadata=run_metadata)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1191, in run
    run_metadata=run_metadata)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 971, in run
    return self._sess.run(*args, **kwargs)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/jto/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Queue '_2_input_producer' is already closed.
         [[Node: input_producer/input_producer_Close = QueueCloseV2[cancel_pending_enqueues=false](input_producer)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,224,224,3], [?,2]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
         [[Node: IteratorGetNext/_2401 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_534_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```

I've googled so many solutions, most of them say that's because somehow the data queue is stopped, or we didn't start the queue correctly, solutions like:
```
# Start the data queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess, coord)
```

But the official ```resnet_run_loop.resnet_main()``` using ```tf.estimator.Estimator``` to train the model, the source code doesn't need to start the queue like that, so how can we solve this problem? Any ideas would be appreciate. 

What is the top-level directory of the model you are using: ```official/```
Have I written custom code: Yes, see the code above.
OS Platform and Distribution: Ubuntu 16.04 LTS
TensorFlow installed from: pip
TensorFlow version: 1.8.0
Bazel version: N/A
CUDA/cuDNN version: 9.0/7.1
GPU model and memory: GTX 1080 TI, 11GB
Exact command to reproduce: ```python main.py --data_dir='/home/jto/dataset/cats_dogs_redux/' --batch_size=32 --resnet_size=50 --version=2 --num_parallel_calls=1```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by JustinhoCHN** [comment]
@tensorflowbutler updated already, thanks.

**Comment by karmel** [comment]
Thanks, @JustinhoCHN . We recommend using the [Dataset API](https://www.tensorflow.org/api_docs/python/tf/data/Dataset), as queues have been deprecated. Can you modify the code above to use datasets, as in the official example, and retry?

**Comment by JustinhoCHN** [comment]
@karmel yeah, I am using Dataser API, you can check my code [here.](https://gist.github.com/JustinhoCHN/d6d4534d322595dc562ff0d0d59b8a59)

**I am using resnet from model-1.8.0**, there's a ```process_record_dataset()``` in ```official/resnet/resnet_run_loop.py```, I did some small changes to use my own parsing function:

```
def process_record_dataset(dataset, is_training, batch_size, shuffle_buffer,
                           parse_record_fn, num_epochs=1, num_parallel_calls=1,
                           examples_per_epoch=0, multi_gpu=False):
    """Given a Dataset with raw records, return an iterator over the records.

  Args:
    dataset: A Dataset representing raw records
    is_training: A boolean denoting whether the input is for training.
    batch_size: The number of samples per batch.
    shuffle_buffer: The buffer size to use when shuffling records. A larger
      value results in better randomness, but smaller values reduce startup
      time and use less memory.
    parse_record_fn: A function that takes a raw record and returns the
      corresponding (image, label) pair.
    num_epochs: The number of epochs to repeat the dataset.
    num_parallel_calls: The number of records that are processed in parallel.
      This can be optimized per data set but for generally homogeneous data
      sets, should be approximately the number of available CPU cores.
    examples_per_epoch: The number of examples in the current set that
      are processed each epoch. Note that this is only used for multi-GPU mode,
      and only to handle what will eventually be handled inside of Estimator.
    multi_gpu: Whether this is run multi-GPU. Note that this is only required
      currently to handle the batch leftovers (see below), and can be removed
      when that is handled directly by Estimator.

  Returns:
    Dataset of (image, label) pairs ready for iteration.
  """
    # We prefetch a batch at a time, This can help smooth out the time taken to
    # load input files as we go through shuffling and processing.
    dataset = dataset.prefetch(buffer_size=batch_size)
    if is_training:
        # Shuffle the records. Note that we shuffle before repeating to ensure
        # that the shuffling respects epoch boundaries.
        dataset = dataset.shuffle(buffer_size=shuffle_buffer)

    # If we are training over multiple epochs before evaluating, repeat the
    # dataset for the appropriate number of epochs.
    dataset = dataset.repeat(num_epochs)

    # Currently, if we are using multiple GPUs, we can't pass in uneven batches.
    # (For example, if we have 4 GPUs, the number of examples in each batch
    # must be divisible by 4.) We already ensured this for the batch_size, but
    # we have to additionally ensure that any "leftover" examples-- the remainder
    # examples (total examples % batch_size) that get called a batch for the very
    # last batch of an epoch-- do not raise an error when we try to split them
    # over the GPUs. This will likely be handled by Estimator during replication
    # in the future, but for now, we just drop the leftovers here.
    if multi_gpu:
        total_examples = num_epochs * examples_per_epoch
        dataset = dataset.take(batch_size * (total_examples // batch_size))

    # Parse the raw records into images and labels
    # dataset = dataset.map(lambda value: parse_record_fn(value, is_training),
    #                       num_parallel_calls=num_parallel_calls)
    dataset = dataset.map(parse_record_fn)

    dataset = dataset.batch(batch_size)

    # Operations between the final prefetch and the get_next call to the iterator
    # will happen synchronously during run time. We prefetch here again to
    # background all of the above processing work and keep it out of the
    # critical training path.
    dataset = dataset.prefetch(1)
    # iterator = dataset.make_one_shot_iterator()
    # features, labels = iterator.get_next()

    return dataset
```

And as you can see, this function returns a tf.dataset object, so I'm pretty sure it's using tf.dataset pipline.

**Comment by karmel** [comment]
The code in the first post above uses queues for reading the files, so likely the issue is a conflict between the dataset parsing and the queues that are opened:

```
def read_and_decode(filename):
    filename_queue = tf.train.string_input_producer([filename])
```
The Cifar and Resnet examples also read from files, using the dataset API. Try mirroring what those examples do.

**Comment by JustinhoCHN** [comment]
@karmel Thank you so much! That's exactly the problem here, I shouldn't using string_input_producer() to input data again, since the Dataset API already do that for me.

**Comment by zarabozdag** [comment]
> @karmel Thank you so much! That's exactly the problem here, I shouldn't using string_input_producer() to input data again, since the Dataset API already do that for me.

Hi, so you just remove the code (string_input_producer() ), could you share your main.py file?
