### ISSUE TITLE
Retraining Slim Model - resize_images() error

### ISSUE THREAD

**Issue by ryanjay0** [tensorflow/models#477]
Going through the steps in 

https://github.com/tensorflow/models/blob/master/slim/README.md

With:

TensorFlow: (10.0rc0 exact example from page)
LinuxMint 17.3  (Ubuntu 14.04)
Installation method: Pip
Python: 2.7
Model: Flowers

Command:

>  python train_image_classifier.py \
>     --train_dir=${TRAIN_DIR} \
>     --dataset_dir=${DATASET_DIR} \
>     --dataset_name=flowers \
>     --dataset_split_name=train \
>     --model_name=inception_v3 \
>     --checkpoint_path=${CHECKPOINT_PATH} \
>     --checkpoint_exclude_scopes=InceptionV3/Logits,InceptionV3/AuxLogits/Logits \
>     --trainable_scopes=InceptionV3/Logits,InceptionV3/AuxLogits/Logits

Output:

Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 448, in main
    image = image_preprocessing_fn(image, train_image_size, train_image_size)
  File "/home/ryan/workspace/models/slim/preprocessing/preprocessing_factory.py", line 69, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/home/ryan/workspace/models/slim/preprocessing/inception_preprocessing.py", line 302, in preprocess_image
    return preprocess_for_train(image, height, width, bbox, fast_mode)
  File "/home/ryan/workspace/models/slim/preprocessing/inception_preprocessing.py", line 216, in preprocess_for_train
    num_cases=num_resize_cases)
  File "/home/ryan/workspace/models/slim/preprocessing/inception_preprocessing.py", line 42, in apply_with_random_selector
    for case in range(num_cases)])[0]
  File "/home/ryan/workspace/models/slim/preprocessing/inception_preprocessing.py", line 215, in <lambda>
    lambda x, method: tf.image.resize_images(x, [height, width], method=method),
TypeError: resize_images() takes at least 3 arguments (3 given)

**Comment by ryanjay0** [comment]
fixed by using 10.0 not 10.0rc0 and also using the script finetune_inception_v3_on_flowers.sh rather than the commands on the instructions.

**Comment by lehnert** [comment]
I tried using 10.0 and not 10.0rc0 but got some other runtime errors. I fixed this issue by using 10.0rc0 and changing the line of code
`resize_images(x, [height, width] method=method)` 
to
`resize_images(x, height, width, method=method),`
in the file "models/slim/preprocessing/inception_preprocessing.py", line 215.
