### ISSUE TITLE
Object detection error: No such file or directory

### ISSUE THREAD

**Issue by jbasquiat** [tensorflow/models#4772]
Hi,

I'm trying to run locally a training with object detection API  on ubuntu. I've followed instruction [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md
).  I have my pipeline.config, my tfrecord files and model.ckpt from model zoo in a recommended directory structure.

I try to run this script:
```
python object_detection/model_main.py \
    --pipeline_config_path= "/home/juan/TFG/prueba1/models/model/pipeline.config" \
    --model_dir="/home/juan/TFG/prueba1/models/model" \
    --checkpoint_dir= "/home/juan/TFG/prueba1/faster_rcnn_resnet101_kitti/model.ckpt.data-00000-of-00001" \
    --num_train_steps=2000 \
    --num_eval_steps=200 \
    --alsologtostderr
```

But I get this error:
```
Traceback (most recent call last):
  File "object_detection/model_main.py", line 86, in <module>
    tf.app.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 57, in main
    eval_steps=FLAGS.num_eval_steps)
  File "/home/juan/TFG/models-master/research/object_detection/model_lib.py", line 469, in create_estimator_and_inputs
    configs = get_configs_from_pipeline_file(pipeline_config_path)
  File "/home/juan/TFG/models-master/research/object_detection/utils/config_util.py", line 93, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

```

If I understand correctly, the script can't find the pipeline.config, but I've checked that _/home/juan/TFG/prueba1/models/model/pipeline.config_ exist

I have no idea what I'm doing wrong

Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jbasquiat** [comment]
Hi,

I have ubuntu 16.04, with tensorflow 1.8.0 from pip, nvidia gtx940m 4GB, Cuda 9.0 and cuDNN 7.1.

I run the command from models/research/

**Comment by pkulzc** [comment]
Hmm, have you installed tf 1.9+ versions?

**Comment by jbasquiat** [comment]
Solved reinstalling python2.

But now I get this error when I try to run faster_rcnn_resnet101_kitti changing num_classes in pipeline.config to  3:
```

WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7f7cf43ef320>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:From /home/juan/TFG/models-master/research/object_detection/core/box_predictor.py:403: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/juan/TFG/models-master/research/object_detection/core/losses.py:317: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

2018-07-16 22:19:47.790364: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-16 22:19:47.881813: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-16 22:19:47.882594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.43GiB
2018-07-16 22:19:47.882627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-16 22:19:49.450902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-16 22:19:49.450947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-16 22:19:49.450953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-16 22:19:49.451176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3155 MB memory) -> physical GPU (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "object_detection/model_main.py", line 85, in <module>
    tf.app.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 81, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 657, in run_local
    eval_result = evaluator.evaluate_and_export()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 847, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 425, in evaluate
    name=name)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1117, in _evaluate_model
    config=self._session_config)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 209, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 816, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 539, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1002, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1007, in _create_session
    return self._sess_creator.create_session()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 696, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 467, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 279, in prepare_session
    config=config)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 191, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [2048,12] rhs shape= [2048,8]
	 [[Node: save/Assign_527 = Assign[T=DT_FLOAT, _class=["loc:@SecondStageBoxPredictor/BoxEncodingPredictor/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](SecondStageBoxPredictor/BoxEncodingPredictor/weights, save/RestoreV2/_7)]]

Caused by op u'save/Assign_527', defined at:
  File "object_detection/model_main.py", line 85, in <module>
    tf.app.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 81, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 657, in run_local
    eval_result = evaluator.evaluate_and_export()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 847, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 425, in evaluate
    name=name)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1117, in _evaluate_model
    config=self._session_config)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 209, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 816, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 539, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1002, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1007, in _create_session
    return self._sess_creator.create_session()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 696, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 458, in create_session
    self._scaffold.finalize()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 910, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 829, in _build_internal
    restore_sequentially, reshape)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 525, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 494, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 185, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [2048,12] rhs shape= [2048,8]
	 [[Node: save/Assign_527 = Assign[T=DT_FLOAT, _class=["loc:@SecondStageBoxPredictor/BoxEncodingPredictor/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](SecondStageBoxPredictor/BoxEncodingPredictor/weights, save/RestoreV2/_7)]]

```
How can I do fine tunning on my dataset from  faster_rcnn_resnet101_kitti model?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
