### ISSUE TITLE
multi gpu got error

### ISSUE THREAD

**Issue by brantbzhang** [tensorflow/models#48]
I want to use multi gpu，when I use tf.device specify which gpu to use,got an error.

```    
with tf.Graph().as_default(),tf.device('/cpu:0'):

        opt,lr_op,global_step=optimizer(INITIAL_LEARNING_RATE,tf.get_variable('global_step',[],initializer=tf.constant_initializer(0),trainable=False))
        classify_opt,classify_lr_op,classify_global_step=optimizer(CLASSIFY_INITIAL_LEARNING_RATE,tf.get_variable('classify_global_step',[],initializer=tf.constant_initializer(0),trainable=False))

        tower_grads=[]
        classify_tower_grads=[]
        gpu_num=len(os.environ.get('CUDA_VISIBLE_DEVICES','').split(','))
        if gpu_num==0:raise RuntimeError
        for i in range(gpu_num):
            with tf.device('/gpu:%d'%i):
                with tf.name_scope('gpu_%d'%i) as scope:
                    loss_op,classify_loss_op=tower_loss(scope)
                    tf.get_variable_scope().reuse_variables()
                    grads=opt.compute_gradients(loss_op)
                    classify_grads=classify_opt.compute_gradients(classify_loss_op)
                    tower_grads.append(grads)
                    classify_tower_grads.append(classify_grads)
        classify_grads=average_gradients(classify_tower_grads)
        grads=average_gradients(tower_grads)
```

```
Traceback (most recent call last):
  File "cnn_inc_v4.py", line 404, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "cnn_inc_v4.py", line 401, in main
    train()
  File "cnn_inc_v4.py", line 377, in train
    _,loss_value,lr_value=sess.run([train_op,loss_op,lr_op])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'gpu_0/LearnedUnigramCandidateSampler': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available
         [[Node: gpu_0/LearnedUnigramCandidateSampler = LearnedUnigramCandidateSampler[num_sampled=100, num_true=1, range_max=195327, seed=0, seed2=0, unique=true, _device="/device:GPU:0"](gpu_0/ToInt64)]]
Caused by op u'gpu_0/LearnedUnigramCandidateSampler', defined at:
  File "cnn_inc_v4.py", line 404, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "cnn_inc_v4.py", line 401, in main
    train()
  File "cnn_inc_v4.py", line 340, in train
    loss_op,classify_loss_op=tower_loss(scope)
  File "cnn_inc_v4.py", line 282, in tower_loss
    loss_model(logits,yy_node,y_embeddings)
  File "cnn_inc_v4.py", line 204, in loss_model
    neg_ids, _, _ = tf.nn.learned_unigram_candidate_sampler(true_classes=tf.to_int64(tf.reshape(yy,[BATCH_SIZE,1])),num_true=1,num_sampled=NEG_NUM,unique=True,range_max=NUM_LABELS)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/candidate_sampling_ops.py", line 192, in learned_unigram_candidate_sampler
    seed2=seed2, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_candidate_sampling_ops.py", line 251, in _learned_unigram_candidate_sampler
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
```

**Comment by andydavis1** [comment]
It does not look like LearnedUnigramCandidateSampler has a GPU OpKernel. If this is still an issue, can you please provide more information from the template that is provided when you open an new issue?

**Comment by michaelisard** [comment]
Closing due to lack of activity. Please reopen with more information if it's still a problem.
