### ISSUE TITLE
InvalidArgumentError when training im2txt with CUDA enabled

### ISSUE THREAD

**Issue by magicalhobo** [tensorflow/models#486]
I'm getting the following error when trying to train im2txt with CUDA enabled. If I disable GPU support with `export CUDA_VISIBLE_DEVICES=""`, the model trains fine on the CPU.

```
"WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 49958 elements; but when writing their indices, saw 382 elements."
```

Here's the command I'm running:

```
bazel-bin/im2txt/train \
  --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256" \
  --inception_checkpoint_file="${INCEPTION_CHECKPOINT}" \
  --train_dir="${MODEL_DIR}/train" \
  --train_inception=false \
  --number_of_steps=1000000
```

Here's the console output:

```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.7.5 locally
INFO:tensorflow:Prefetching values from 256 files matching /root/im2txt/data/mscoco/train-?????-of-00256
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 960
major: 5 minor: 2 memoryClockRate (GHz) 1.2785
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.37GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors.InvalidArgumentError'>, WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 49958 elements; but when writing their indices, saw 382 elements.
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](init_ops/report_uninitialized_variables/boolean_mask/Reshape_1)]]
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where/_1539 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_439_init_ops/report_uninitialized_variables/boolean_mask/Where", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'init_ops/report_uninitialized_variables/boolean_mask/Where', defined at:
  File "/root/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/root/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 110, in main
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 686, in train
    ready_op = tf_variables.report_uninitialized_variables()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1167, in report_uninitialized_variables
    return array_ops.boolean_mask(variable_names_tensor, variables_mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 950, in boolean_mask
    return _apply_mask_1d(tensor, mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 925, in _apply_mask_1d
    indices = squeeze(where(mask), squeeze_dims=[1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3158, in where
    result = _op_def_lib.apply_op("Where", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2386, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 49958 elements; but when writing their indices, saw 382 elements.
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](init_ops/report_uninitialized_variables/boolean_mask/Reshape_1)]]
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where/_1539 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_439_init_ops/report_uninitialized_variables/boolean_mask/Where", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Traceback (most recent call last):
  File "/root/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/root/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 110, in main
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 754, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 969, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 797, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 958, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 715, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 245, in prepare_session
    is_ready, msg = self._model_ready(sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 435, in _model_ready
    return self._ready(self._ready_op, sess, "Model not ready")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 404, in _ready
    ready_value = sess.run(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 49958 elements; but when writing their indices, saw 382 elements.
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](init_ops/report_uninitialized_variables/boolean_mask/Reshape_1)]]
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where/_1539 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_439_init_ops/report_uninitialized_variables/boolean_mask/Where", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'init_ops/report_uninitialized_variables/boolean_mask/Where', defined at:
  File "/root/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/root/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 110, in main
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 686, in train
    ready_op = tf_variables.report_uninitialized_variables()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1167, in report_uninitialized_variables
    return array_ops.boolean_mask(variable_names_tensor, variables_mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 950, in boolean_mask
    return _apply_mask_1d(tensor, mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 925, in _apply_mask_1d
    indices = squeeze(where(mask), squeeze_dims=[1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3158, in where
    result = _op_def_lib.apply_op("Where", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2386, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): WhereOp: Race condition between counting the number of true elements and writing them.  When counting, saw 49958 elements; but when writing their indices, saw 382 elements.
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where = Where[_device="/job:localhost/replica:0/task:0/cpu:0"](init_ops/report_uninitialized_variables/boolean_mask/Reshape_1)]]
	 [[Node: init_ops/report_uninitialized_variables/boolean_mask/Where/_1539 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_439_init_ops/report_uninitialized_variables/boolean_mask/Where", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

**Comment by tatatodd** [comment]
This looks related: https://github.com/tensorflow/tensorflow/issues/4033

AFAICT this looks like a real bug.  @magicalhobo can you fill out the following information regarding your environment?

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

**Comment by magicalhobo** [comment]
Sure, here you go.

```
> ls  -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 60696704 Sep 30 23:01 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 60696704 Sep 30 23:01 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 60696704 Sep 30 23:01 /usr/local/cuda/lib64/libcudnn.so.5.1.3
-rw-r--r-- 1 root root 59715990 Sep 30 23:01 /usr/local/cuda/lib64/libcudnn_static.a
```
```
> git rev-parse HEAD
78fbc21cc6f2dfbb0a50ee98f98039576b5d03f6
```
```
> bazel version
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0
```

**Comment by tatatodd** [comment]
@mrry @keveman @benoitsteiner @prb12 might be interested in this, because of the similarity with https://github.com/tensorflow/tensorflow/issues/4033

Note that unlike the multi-machine configuration in 4033, this issue is occurring on a single machine.

@magicalhobo Does the error occur consistently when you run with CUDA enabled, or only some of the time?

**Comment by magicalhobo** [comment]
Yes, it occurs every time I try to run with CUDA.

**Comment by tatatodd** [comment]
@magicalhobo I'm trying to reproduce the problem locally; I'll let you know how that goes.

---

Some details.

FYI the `WhereOp: Race condition between counting the number of true elements and writing them` error is typically a sign that there is actually a read/write race on the tensor that is used in the `WhereOp`.  In this case, we're calling WhereOp via `report_uninitialized_variables`, which calls `boolean_mask`:
https://github.com/tensorflow/tensorflow/blob/78fbc21cc6f2dfbb0a50ee98f98039576b5d03f6/tensorflow/python/ops/variables.py#L1167
https://github.com/tensorflow/tensorflow/blob/78fbc21cc6f2dfbb0a50ee98f98039576b5d03f6/tensorflow/python/ops/array_ops.py#L925

But inspecting the code, I can't explain how there can possibly be a read/write race on the `mask` that we're calling `where` on.  So I'll need to reproduce the error to dig into this further.

It's a bit unfortunate that this is happening during the simple error check for uninitialized variables.  If you're in a hurry to try something, you can dig into the code and try to disable the calls to `report_uninitialized_variables()`, but it's not entirely trivial.

**Comment by tatatodd** [comment]
@magicalhobo I can't reproduce the problem.

One difference between my setup and yours is that I'm using a GeForce GTX TITAN X which has 12GB, while you're using a GeForce GTX 960 which has 2GB.  I'm not sure whether that is causing the problem.

Attached is a picture of the relevant area of the graph that is causing you trouble.  The `Where` op is highlighted in red.  The reason I'm attaching this is because the error you're seeing typically indicates that the input to the `Where` op is is probably being written to concurrently with it being read from; thus the race.  However as the graph shows, the input isn't actually being used anywhere else.

![im2txt_where](https://cloud.githubusercontent.com/assets/5453737/19255949/72b18fb8-8f17-11e6-8c93-bcd4e27bc170.png)

Sorry, but I'm not sure what to suggest to you, other than real longshots:
1. If possible, perhaps try a different GPU with more memory
2. Try inspecting `${MODEL_DIR}/train/graph.pbtxt` using tensorboard, or attach it to this issue and I'll inspect it, to make sure the graph that you're running looks like the picture above.

**Comment by magicalhobo** [comment]
Good news! After installing the nightly wheel, everything is working. It must have been a bug in TensorFlow itself because I didn't update tensorflow/models. I would check to make sure my graph looks the same, but tensorboard is broken in this version. Thanks for the help debugging.
