### ISSUE TITLE
objection_detection

### ISSUE THREAD

**Issue by chanyixialex** [tensorflow/models#4860]
run python model_main.py --logtostderr --model_dir='/vol/home/alex/tf-od-test/train' --pipeline_config_path='/vol/home/alex/tf-od-test/models/faster_rcnn_inception_resnet_v2_atrous_pets.config
There is a problem:
File "/vol/home/alex/models/research/object_detection/model_lib.py", line 282, in model_fn 
losses = [loss_tensor for loss_tensor in losses_dict.itervalues()]  
AttributeError: 'dict' object has no attribute 'itervalues'.

**Comment by chanyixialex** [comment]
Traceback (most recent call last):
  File "model_main.py", line 101, in <module>
    tf.app.run()
  File "/vol/venvs/tf1.7/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "model_main.py", line 97, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/vol/venvs/tf1.7/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/vol/venvs/tf1.7/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/vol/venvs/tf1.7/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 650, in run_local
    hooks=train_hooks)
  File "/vol/venvs/tf1.7/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/vol/venvs/tf1.7/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 824, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/vol/venvs/tf1.7/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 805, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/vol/home/alex/models/research/object_detection/model_lib.py", line 282, in model_fn
    losses = [loss_tensor for loss_tensor in losses_dict.itervalues()]
AttributeError: 'dict' object has no attribute 'itervalues'

**Comment by TedLLH** [comment]
You are running in python3, which has no attribute 'itervalues', you can change them to 'values()'

You could try again but most likely it would not work, see #4830 & #4832 

But please do try, and if it works, please let us know.

**Comment by chanyixialex** [comment]
@TedLLH it works. Thank you!!!!

**Comment by TedLLH** [comment]
@chanyixialex It works for you? Could you elaborate a little bit more? Did you successfully train the model with your own data on your local machine after editing the itervalues()?

If you could train your model, do you mind share your source codes to us please? I have tried different ways and I am still stuck, see #4830 & #4832.

Much appreciated.
