### ISSUE TITLE
SLIM: ResourceExhaustedError when running download_and_convert_data with flowers dataset

### ISSUE THREAD

**Issue by asimore** [tensorflow/models#489]
GPU: 2 x GTX1080 (8 GB each), 1 x GTX 960 (4 GB)
Main Memory: 64 GB

No other jobs are running while issuing the command below:

python download_and_convert_data.py --dataset_name=flowers --dataset_dir=/tmp/flowers

Converting image 978/3320 shard 1Traceback (most recent call last):
  File "download_and_convert_data.py", line 73, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "download_and_convert_data.py", line 65, in main
    download_and_convert_flowers.run(FLAGS.dataset_dir)
  File "/root/projects/models/slim/datasets/download_and_convert_flowers.py", line 202, in run
    dataset_dir)
  File "/root/projects/models/slim/datasets/download_and_convert_flowers.py", line 139, in _convert_dataset
    image_data = tf.gfile.FastGFile(filenames[i], 'r').read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 99, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 72, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.ResourceExhaustedError: /tmp/flowers/flower_photos/daisy/14147016029_8d3cf2414e.jpg

**Comment by asimore** [comment]
Building from source (branch r0.11) fixed this particular issue, therefore, I'm closing this issue. I ran into another problem which I'll report in a separate issue.

**Comment by jart** [comment]
Are you on CentOS / RedHat?

**Comment by QuantumTCode** [comment]
What directory did you run this in?
