### ISSUE TITLE
google.protobuf.text_format.ParseError: 135:19 : Message type "object_detection.protos.TFRecordInputReader" has no field named "D"

### ISSUE THREAD

**Issue by shauviks** [tensorflow/models#4905]
Hi When i am trying to run train.py, I am getting the above error . Can someone please help me . The complete error is below.
`(tfobj) D:\tensorflow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
C:\Users\kkran\Anaconda3\envs\tfobj\lib\importlib\_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
C:\Users\kkran\Anaconda3\envs\tfobj\lib\importlib\_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING:tensorflow:From C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\tensorflow\python\platform\app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\tensorflow\python\util\deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "D:\tensorflow\models\research\object_detection\utils\config_util.py", line 94, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\kkran\Anaconda3\envs\tfobj\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 135:19 : Message type "object_detection.protos.TFRecordInputReader" has no field named "D".`

**Comment by xDooooot** [comment]
Hi
I have solved this by checking 'xxx_xxxx_xx.config' file. You can try 'ctrl+F' to find 'D' in your config file to check if there is something wrong with it. Good luck :)

**Comment by yihao727** [comment]
@xDooooot  ,Hi，can you  tell me where is the 'xxx_xxxx_xx.config'  file ,

**Comment by yaozhangwpi** [comment]
I got the same problem with you. How did you fix it？

**Comment by HimathHarshajith** [comment]
did anyone fixed this issue?

**Comment by HimathHarshajith** [comment]
Solved it...!

google.protobuf.text_format.ParseError: 135:19 : Message type "object_detection.protos.TFRecordInputReader" has no field named "D".

The issue is showing by 135:19 in the code the module config file you are using

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by kumariko** [comment]
@shauviks We are checking to see if you still need help on this issue? Could you please have a look on https://github.com/tensorflow/models/issues/4905#issuecomment-488750640 and let us know if it helps? Thanks!
