### ISSUE TITLE
[Vid2Depth] KeyError: u'Icp' when importing meta graph 

### ISSUE THREAD

**Issue by gi097** [tensorflow/models#4980]
### System information
- **What is the top-level directory of the model you are using**:
https://github.com/tensorflow/models/tree/master/research/vid2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacOS High Sierra 10.13.6
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.9.0
- **Bazel version (if compiling from source)**:
Not used
- **CUDA/cuDNN version**:
Not used
- **GPU model and memory**:
Intel HD graphics 4000
- **Exact command to reproduce**:
`saver = tf.train.import_meta_graph('./model-119496.meta')` 

### Describe the problem
I am trying to freeze a graph by using the meta, index and data files, provided in https://github.com/tensorflow/models/tree/master/research/vid2depth. By simply loading the `.meta`. file, I get the following errors:

### Source code / logs

> Traceback (most recent call last):
>   File "convert.py", line 6, in <module>
>     saver = tf.train.import_meta_graph('./model-119496.meta')
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1960, in import_meta_graph
>     **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
>     producer_op_list=producer_op_list)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
>     _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 158, in _RemoveDefaultAttrs
>     op_def = op_dict[node.op]
> KeyError: u'Icp'

**Comment by gi097** [comment]
@rezama

**Comment by gi097** [comment]
After reading the README correctly, I found out that the `icp` is a special op, which needs to be build and installed from source.
