### ISSUE TITLE
ValueError: No variables to save while inception v3 fine-tuning

### ISSUE THREAD

**Issue by gnujimmik** [tensorflow/models#499]
## Please let us know which model this issue is about (specify the top-level directory)

I tried to fine-tune Mixed_7c layer in inception v3 and ran the command as below using my own dataset.
`$ python train_image_classifier.py --train_dir=${TRAIN_DIR}/inception_v3/ --dataset_name=eyes --model_name=inception_v3     --checkpoint_path=${PRETRAINED_CHECKPOINT_DIR}/inception_v3/inception_v3.ckpt     --checkpoint_exclude_scopes=InceptionV3/Logits,InceptionV3/AuxLogits, InceptionV3/Mixed_7c     --trainable_scopes=InceptionV3/Logits,InceptionV3/AuxLogits, InceptionV3/Mixed_7c   --batch_size=64  --max_number_of_steps=10000 --dataset_dir=${DATASET_DIR} --learning_rate=0.001 
`
I added InceptionV3/Mixed_7c block to retrain and got an error like:
```
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/home/mijung/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 575, in main
    init_fn=_get_init_fn(),
  File "train_image_classifier.py", line 370, in _get_init_fn
    ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/home/mijung/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 579, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/home/mijung/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 987, in __init__
    self.build()
  File "/home/mijung/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1007, in build
    raise ValueError("No variables to save")
ValueError: No variables to save

```
Is there anybody know how to fine-tune some of the inception v3 blocks?

**Comment by tatatodd** [comment]
@gnujimmik you seem to have some extra spaces in your command line, before `InceptionV3/Mixed_7c`.  Perhaps try the following:

`$ python train_image_classifier.py --train_dir=${TRAIN_DIR}/inception_v3/ --dataset_name=eyes --model_name=inception_v3     --checkpoint_path=${PRETRAINED_CHECKPOINT_DIR}/inception_v3/inception_v3.ckpt     --checkpoint_exclude_scopes=InceptionV3/Logits,InceptionV3/AuxLogits,InceptionV3/Mixed_7c     --trainable_scopes=InceptionV3/Logits,InceptionV3/AuxLogits,InceptionV3/Mixed_7c   --batch_size=64  --max_number_of_steps=10000 --dataset_dir=${DATASET_DIR} --learning_rate=0.001 
`

**Comment by gnujimmik** [comment]
Yes, It worked! Thank you!
