### ISSUE TITLE
Memory Leak: Dst tensor is not  initialized pops out even I have enough GPU memory

### ISSUE THREAD

**Issue by twangnh** [tensorflow/models#4994]
I'm using tf object detection api
```
INFO:tensorflow:global step 11202: loss = 3.6547 (0.945 sec/step)
INFO:tensorflow:global step 11203: loss = 4.0109 (0.905 sec/step)
INFO:tensorflow:global step 11204: loss = 3.9925 (0.968 sec/step)
INFO:tensorflow:global step 11205: loss = 4.3680 (0.955 sec/step)
INFO:tensorflow:global step 11206: loss = 4.3539 (0.919 sec/step)
INFO:tensorflow:global step 11207: loss = 4.3368 (0.921 sec/step)
INFO:tensorflow:global step 11208: loss = 3.7202 (0.907 sec/step)
INFO:tensorflow:global step 11209: loss = 3.2813 (0.928 sec/step)
INFO:tensorflow:global step 11210: loss = 3.5669 (0.939 sec/step)
INFO:tensorflow:global step 11211: loss = 3.4885 (0.985 sec/step)
INFO:tensorflow:global step 11212: loss = 3.1678 (0.924 sec/step)
INFO:tensorflow:global step 11213: loss = 3.2577 (0.924 sec/step)
INFO:tensorflow:global step 11214: loss = 4.0300 (1.147 sec/step)
INFO:tensorflow:Recording summary at step 11214.
INFO:tensorflow:global step 11215: loss = 3.7617 (0.998 sec/step)
INFO:tensorflow:global step 11216: loss = 3.3286 (0.941 sec/step)
INFO:tensorflow:global step 11217: loss = 3.2815 (0.932 sec/step)
INFO:tensorflow:global step 11218: loss = 4.1242 (0.966 sec/step)
INFO:tensorflow:global step 11219: loss = 4.5689 (0.966 sec/step)
INFO:tensorflow:global step 11220: loss = 3.6092 (1.072 sec/step)
INFO:tensorflow:global step 11221: loss = 4.2938 (1.001 sec/step)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.
framework.errors_impl.InternalError'>, Dst tensor is not initialized.
         [[Node: clone_3/prefetch_queue_Dequeue/_8301 = _Recv[client_term
inated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:3",
 send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_
incarnation=1, tensor_name="edge_1660_clone_3/prefetch_queue_Dequeue", te
nsor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:3
"]()]]
Traceback (most recent call last):                              [65/1841]
  File "train.py", line 216, in <module>
    tf.app.run()
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 212, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/user/prj/tf-object-api-orig/object_detection/trainer.py"
, line 435, in train
    saver=saver)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/contrib/slim/python/slim/learning.py", line 769, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/contrib/slim/python/slim/learning.py", line 487, in train_
step
    run_metadata=run_metadata)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not 
initialized.
         [[Node: clone_3/prefetch_queue_Dequeue/_8301 = _Recv[client_term
inated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:3",
 send_device="/job:localhost/replica:0/task:0/device:CPU:0", sen[69/1841]
incarnation=1, tensor_name="edge_1660_clone_3/prefetch_queue_Dequeue", te
nsor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:3
"]()]]
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    tf.app.run()
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 212, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/user/prj/tf-object-api-orig/object_detection/trainer.py"
, line 435, in train
    saver=saver)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/contrib/slim/python/slim/learning.py", line 769, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/contrib/slim/python/slim/learning.py", line 487, in train_
step
    run_metadata=run_metadata)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/user/anaconda2/envs/tensorflow_/lib/python2.7/site-packa
ges/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not 
initialized.
         [[Node: clone_3/prefetch_queue_Dequeue/_8301 = _Recv[client_term
inated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:3",
 send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_
incarnation=1, tensor_name="edge_1660_clone_3/prefetch_queue_Dequeue", te
nsor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:3
"]()]]
```
I got this error even if I have checked that I have enough GPU memory, I'm train on 4 GPU, the memory consumption holds at about 8G/12G for several thousands step, then the error pops out, I suspect there is memory leak, can someone help?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
