### ISSUE TITLE
[Object detection] OutOfRangeError with Oxford-IIIT Pets Dataset

### ISSUE THREAD

**Issue by jbasquiat** [tensorflow/models#5002]
### System information
- **What is the top-level directory of the model you are using**: models-master/research
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9.0/7.0.5
- **GPU model and memory**: gtx 950M 4Gb
- **Exact command to reproduce**:
```
python object_detection/model_main.py \
    --pipeline_config_path=pets/models/faster_rcnn_resnet101_pets.config \
    --model_dir=pets/models/ \
    --num_train_steps=50000 \
    --num_eval_steps=2000 \
    --alsologtostderr

```
Hi, I'm triying to run Oxford-IIIT Pets Dataset example locally. I ran _object_detection/dataset_tools/create_pet_tf_record.py_ to get tfrecord file. And I download _faster_rcnn_resnet101_pets.config_ and I changed path in the cofig file. I have this directory structure:
```
+data
    -label_map file
    -train TFRecord file
    -eval TFRecord file
+models
    -pipeline config file
    -model.ckpt, .pb and .pbtxt

```

But when I run the python file to train with this:

```
python object_detection/model_main.py \
    --pipeline_config_path=pets/models/faster_rcnn_resnet101_pets.config \
    --model_dir=pets/models/ \
    --num_train_steps=50000 \
    --num_eval_steps=2000 \
    --alsologtostderr

```

I get this error:

```

WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7f5f6e9a90c8>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:From /home/juan/TFG/models-master/research/object_detection/core/box_predictor.py:403: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/juan/TFG/models-master/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:2008: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
WARNING:tensorflow:From /home/juan/TFG/models-master/research/object_detection/core/losses.py:317: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2018-08-04 16:49:15.436297: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-04 16:49:15.508705: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-04 16:49:15.509470: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 2.97GiB
2018-08-04 16:49:15.509486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-08-04 16:49:16.708317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-04 16:49:16.708344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-08-04 16:49:16.708351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-08-04 16:49:16.708519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2688 MB memory) -> physical GPU (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2018-08-04 16:49:52.851978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-08-04 16:49:52.852048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-04 16:49:52.852055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-08-04 16:49:52.852061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-08-04 16:49:52.852274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2688 MB memory) -> physical GPU (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.00s).
Accumulating evaluation results...
Please run evaluate() first
DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
Traceback (most recent call last):
  File "object_detection/model_main.py", line 85, in <module>
    tf.app.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 81, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 657, in run_local
    eval_result = evaluator.evaluate_and_export()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 847, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 425, in evaluate
    name=name)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1117, in _evaluate_model
    config=self._session_config)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 212, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 679, in __exit__
    self._close_internal(exception_type)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 711, in _close_internal
    h.end(self._coordinated_creator.tf_sess)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 811, in end
    feed_dict=self._final_ops_feed_dict)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[1], [1,?], [1,?,4], [1,?,37], [1,?], [1,?], [1,?], [1,?], [1,?,?,3], [1], [1], [1,?,?,3], [1], [1,3]], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_UINT8, DT_STRING, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
	 [[Node: SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/non_max_suppression_8/NonMaxSuppressionV2/_4669 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5335_...pressionV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'IteratorGetNext', defined at:
  File "object_detection/model_main.py", line 85, in <module>
    tf.app.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 81, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 657, in run_local
    eval_result = evaluator.evaluate_and_export()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 847, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 425, in evaluate
    name=name)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1085, in _evaluate_model
    input_fn, model_fn_lib.ModeKeys.EVAL))
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 691, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 798, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/juan/TFG/models-master/research/object_detection/inputs.py", line 379, in _eval_input_fn
    input_dict = dataset_util.make_initializable_iterator(dataset).get_next()
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/juan/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): End of sequence
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[1], [1,?], [1,?,4], [1,?,37], [1,?], [1,?], [1,?], [1,?], [1,?,?,3], [1], [1], [1,?,?,3], [1], [1,3]], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_UINT8, DT_STRING, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
	 [[Node: SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/non_max_suppression_8/NonMaxSuppressionV2/_4669 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5335_...pressionV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


```

**Comment by David-Lee-1990** [comment]
@jbasquiat I have the same problem when I train ssd-mobilenet v1 model on my own data. Have you solved this?

**Comment by jbasquiat** [comment]
@David-Lee-1990 No, finally I used Detectron instead of this repository.

**Comment by 201528014227051** [comment]
I have the same problem. Have you solved this? @David-Lee-1990

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
