### ISSUE TITLE
Create TFRecord files from the MNIST-M data set

### ISSUE THREAD

**Issue by Aksei** [tensorflow/models#5016]
Hi, 

i am trying to create the TFRecord files from the MNIST-M dataset. I did download and extract the dataset, however when I run the command : 

python download_and_convert_mnist_m.py -- --dataset_dir $DSN_DATA_DIR

I always get the following error: 

Traceback (most recent call last):
  File "download_and_convert_mnist_m.py", line 240, in <module>
    tf.app.run()
  File "/Users/myfolder/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "download_and_convert_mnist_m.py", line 234, in main
    assert FLAGS.dataset_dir
AssertionError

I have been working at it for quite I while, but I can't fix it. 

If I use bazel (bazel run domain_adaptation/datasets:download_and_convert_mnist_m -- --dataset_dir $DSN_DATA_DIR), I run into the same problem. 

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_myname/e9545550cccabf838338cbdd5e4c6269/execroot/__main__/bazel-out/darwin-fastbuild/bin/research/domain_adaptation/datasets/download_and_convert_mnist_m.runfiles/__main__/research/domain_adaptation/datasets/download_and_convert_mnist_m.py", line 240, in <module>
    tf.app.run()
  File "/Users/myFolder/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/private/var/tmp/_bazel_myname/e9545550cccabf838338cbdd5e4c6269/execroot/__main__/bazel-out/darwin-fastbuild/bin/research/domain_adaptation/datasets/download_and_convert_mnist_m.runfiles/__main__/research/domain_adaptation/datasets/download_and_convert_mnist_m.py", line 235, in main
    run(FLAGS.dataset_dir)
  File "/private/var/tmp/_bazel_myname/e9545550cccabf838338cbdd5e4c6269/execroot/__main__/bazel-out/darwin-fastbuild/bin/research/domain_adaptation/datasets/download_and_convert_mnist_m.runfiles/__main__/research/domain_adaptation/datasets/download_and_convert_mnist_m.py", line 219, in run
    train_validation_filenames_to_class_ids, dataset_dir)
  File "/private/var/tmp/_bazel_myname/e9545550cccabf838338cbdd5e4c6269/execroot/__main__/bazel-out/darwin-fastbuild/bin/research/domain_adaptation/datasets/download_and_convert_mnist_m.runfiles/__main__/research/domain_adaptation/datasets/download_and_convert_mnist_m.py", line 123, in _convert_dataset
    os.path.join(png_directory, filename), 'r').read()
  File "/Users/myFolder/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 127, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/Users/myFolder/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 95, in _prepare_value
    return compat.as_str_any(val)
  File "/Users/myFolder/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 113, in as_str_any
    return as_str(value)
  File "/Users/myFolder/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 86, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

Does anyone know how to fix it?

Thank you

**Comment by Aksei** [comment]
**What is the top-level directory of the model you are using:** /domain_adaption
**Have I written custom code :** I commented out the 'paropts' Line in BUILD in slim as recommended in #3819  (https://github.com/tensorflow/models/issues/3819)
**OS Platform and Distribution:**  MacOS High Sierra Version 10.13.6 
**TensorFlow installed from:** 
**TensorFlow version:** 1.8.0
**Bazel version:** 0.15.0
**CUDA/cuDNN version**: N/A
**GPU model and memory:** N/A
**Exact command to reproduce:** bazel run domain_adaptation/datasets:download_and_convert_mnist_m -- --dataset_dir $DSN_DATA_DIR

**Comment by karmel** [comment]
Unicode decode error-- perhaps a Python 3 compatibility issue? @bousmalis , can you take a look?

**Comment by karmel** [comment]
Spoke to @bousmalis offline, and contributions would be welcome on this issue-- @Aksei , care to submit a PR?

**Comment by Aksei** [comment]
I am not very familiar with github, but I think I managed to do a PR. Did it work out?

**Comment by Aksei** [comment]
I changed the Python version from  Python 3.6.5 to Python 2.7.15. 
The conversion of the MNIST-M dataset into TFRecord files was successful now. So it seems like it was a Python 3 compatibility issue, as @karmel suggested before. 
Thank you for the hint  :)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
