### ISSUE TITLE
models/official/resnet, when run cifar10_main.py cannot use --num_gpus.

### ISSUE THREAD

**Issue by shl666** [tensorflow/models#5029]
### System information
- **OS Platform and Distribution: Linux Ubuntu 16.04**:
- **TensorFlow installed from binary**:
- **TensorFlow version :1.9**:
- **CUDA/cuDNN version 9.0/7.0**:
- **GPU model and memory: 4*GTX1080Ti**:

### Describe the problem
Following the instruction, when I run 
```bash
python cifar10_main.py --data_dir=/path/to/dataset_Cifar_10/ --model_dir=/path/to/cifar10_model
```
It works well (occupied all 4 gpus memory and run on 1 of them)
However, when I add ```--num_gpus=2``` it gives me errors.

### Source code / logs
...
...
...
I0808 22:58:57.747971 140488908728064 tf_logging.py:115] Calling model_fn.
I0808 22:59:00.171719 140488900335360 tf_logging.py:115] Calling model_fn.
I0808 22:59:01.563793 140495269766912 tf_logging.py:115] batch_all_reduce invoked for batches size = 98 with algorithm = nccl and num_packs = 1

I0808 22:59:03.003044 140488908728064 tf_logging.py:115] Error reported to Coordinator: Use DistributionStrategy.update() to modify a MirroredVariable.
Traceback (most recent call last):
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 479, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "cifar10_main.py", line 224, in cifar10_model_fn
    dtype=params['dtype']
  File "/home/smluo/GithubProject/models/official/resnet/resnet_run_loop.py", line 303, in resnet_model_fn
    accuracy = tf.metrics.accuracy(labels, predictions['classes'])
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py", line 409, in accuracy
    name or 'accuracy')
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py", line 332, in mean
    update_total_op = state_ops.assign_add(total, math_ops.reduce_sum(values))
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 187, in assign_add
    return ref.assign_add(value)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 313, in assign_add
    return self.get(device=_get_update_device()).assign_add(*args, **kwargs)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 285, in _get_update_device
    "Use DistributionStrategy.update() to modify a MirroredVariable.")
RuntimeError: Use DistributionStrategy.update() to modify a MirroredVariable.
Traceback (most recent call last):
  File "cifar10_main.py", line 260, in <module>
    absl_app.run(main)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/absl/app.py", line 278, in run
    _run_main(main, args)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/absl/app.py", line 239, in _run_main
    sys.exit(main(argv))
  File "cifar10_main.py", line 254, in main
    run_cifar(flags.FLAGS)
  File "cifar10_main.py", line 249, in run_cifar
    shape=[_HEIGHT, _WIDTH, _NUM_CHANNELS])
  File "/home/smluo/GithubProject/models/official/resnet/resnet_run_loop.py", line 410, in resnet_main
    max_steps=flags_obj.max_train_steps)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1117, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1160, in _train_model_distributed
    self.config)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 794, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 269, in _call_for_each_tower
    coord.join(threads)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 479, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "cifar10_main.py", line 224, in cifar10_model_fn
    dtype=params['dtype']
  File "/home/smluo/GithubProject/models/official/resnet/resnet_run_loop.py", line 303, in resnet_model_fn
    accuracy = tf.metrics.accuracy(labels, predictions['classes'])
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py", line 409, in accuracy
    name or 'accuracy')
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py", line 332, in mean
    update_total_op = state_ops.assign_add(total, math_ops.reduce_sum(values))
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 187, in assign_add
    return ref.assign_add(value)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 313, in assign_add
    return self.get(device=_get_update_device()).assign_add(*args, **kwargs)
  File "/home/smluo/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 285, in _get_update_device
    "Use DistributionStrategy.update() to modify a MirroredVariable.")
RuntimeError: Use DistributionStrategy.update() to modify a MirroredVariable.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
Bazel version
Exact command to reproduce

**Comment by shl666** [comment]
Have I written custom code: no
Bazel version: not used

Exact command to reproduce:
```bash
git clone https://github.com/tensorflow/models.git

export PYTHONPATH=/path/to/models 

pip install –user –r /path/to/official/requirements.txt

python cifar10_download_and_extract.py

python cifar10_main.py --data_dir=/path/to/dataset_Cifar_10/ --model_dir=/path/to/cifar10_model --num_gpus=4
```

**Comment by jfzhuang** [comment]
I also meet this problem, can you share your older version with me? Thanks a lot!

**Comment by robieta** [comment]
I suspect the commit that you're running into is https://github.com/tensorflow/models/commit/a88b89be1075e3fdc40c3c223c2b22631082e53f. For a while metrics didn't work with DistributionStrategies; that was recently fixed and metrics were re-enabled. The fact that you're running TF 1.9 leads me to suspect that your version of TensorFlow just doesn't have those fixes. In general official models are only guaranteed to work with HEAD / nightly builds of tensorflow. (It has to be this way for us to promptly propagate features and fixes from core tensorflow) Unfortunately that can put Anaconda folks in a bind when Conda releases (which we don't control) lag behind TensorFlow HEAD.

**Comment by jfzhuang** [comment]
@robieta Thank you so much. I change the related code to the older version according to your given link, the problem is solved.
