### ISSUE TITLE
training error: unexpected keyword argument 'score_threshold'

### ISSUE THREAD

**Issue by algila** [tensorflow/models#5068]
My system: 
UBUNTU 18.04    
CUDA 9.0   
CUDNN v7.0   
TF-gpu 1.8.0   installed from pip
TF 1.9.0          installed from pip
Keras 2.2.0   
Bazel version N/A
Driver-gpu 385

GPU model TITAN X (Pascal)
If I train the model using the following command (I copied the file model_main.py in the folder where I stored all the model and training file) 
`python model_main.py \
	    --pipeline_config_path=./models/model/embedded_ssd_mobilenet_256x256_0125_Pascal.config \
	    --model_dir=./models/trained \
	    --num_train_steps=50000 \
	    --num_eval_steps=2000 \
	    --alsologtostderr`

after some steps as 3000 the following error come up.

`/home/alberto/TF_ObjDet_API/models/research/object_detection/utils/visualization_utils.py:25: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to u'TkAgg' by the following code:
  File "model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/model_lib.py", line 26, in <module>
    from object_detection import eval_util
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/eval_util.py", line 28, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/metrics/coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/metrics/coco_tools.py", line 47, in <module>
    from pycocotools import coco
  File "/home/alberto/TF_ObjDet_API/models/research/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()

  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7ff6dc485500>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
2018-08-13 21:43:51.273156: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-13 21:43:51.373076: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-13 21:43:51.373577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:01:00.0
totalMemory: 11.91GiB freeMemory: 11.19GiB
2018-08-13 21:43:51.373591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-08-13 21:43:51.515147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-13 21:43:51.515186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-08-13 21:43:51.515192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-08-13 21:43:51.515346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10830 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "model_main.py", line 101, in <module>
    tf.app.run()
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "model_main.py", line 97, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 657, in run_local
    eval_result = evaluator.evaluate_and_export()
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 847, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 425, in evaluate
    name=name)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1087, in _evaluate_model
    features, labels, model_fn_lib.ModeKeys.EVAL, self.config)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/model_lib.py", line 255, in model_fn
    prediction_dict, features[fields.InputDataFields.true_image_shape])
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 636, in postprocess
    additional_fields=additional_fields)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/core/post_processing.py", line 402, in batch_multiclass_non_max_suppression
    parallel_iterations=parallel_iterations)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/utils/shape_utils.py", line 230, in static_or_dynamic_map_fn
    outputs = [fn(arg_tuple) for arg_tuple in arg_tuples]
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/core/post_processing.py", line 378, in _single_image_nms_fn
    additional_fields=per_image_additional_fields)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/core/post_processing.py", line 150, in multiclass_non_max_suppression
    score_threshold=score_thresh)
TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'
`

The same error happen if I try to export the trained model for inference

`python export_inference_graph.py \
>     --input_type=image_tensor \
>     --pipeline_config_path=./models/model/embedded_ssd_mobilenet_256x256_0125_Pascal.config \
>     --trained_checkpoint_prefix=./models/trained/model.ckpt-3099 \
>     --output_directory=./models/EXPORT_DIR
Traceback (most recent call last):
  File "export_inference_graph.py", line 150, in <module>
    tf.app.run()
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 146, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/exporter.py", line 405, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/exporter.py", line 309, in _export_inference_graph
    graph_hook_fn=graph_hook_fn)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/exporter.py", line 277, in _build_detection_graph
    output_collection_name=output_collection_name)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/exporter.py", line 256, in _get_outputs_from_inputs
    output_tensors, true_image_shapes)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 636, in postprocess
    additional_fields=additional_fields)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/core/post_processing.py", line 402, in batch_multiclass_non_max_suppression
    parallel_iterations=parallel_iterations)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/utils/shape_utils.py", line 228, in static_or_dynamic_map_fn
    return tf.map_fn(fn, elems, dtype, parallel_iterations, back_prop)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 423, in map_fn
    swap_memory=swap_memory)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 413, in compute
    packed_fn_values = fn(packed_values)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/core/post_processing.py", line 378, in _single_image_nms_fn
    additional_fields=per_image_additional_fields)
  File "/home/alberto/TF_ObjDet_API/models/research/object_detection/core/post_processing.py", line 150, in multiclass_non_max_suppression
    score_threshold=score_thresh)
TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'
`

**Comment by algila** [comment]
Thank you, I solved updating TF-GPU to verify 1.9.0
