### ISSUE TITLE
error after error. Solve one another comes back. Detection does not work, Nothing runs.

### ISSUE THREAD

**Issue by A-Charvin** [tensorflow/models#5081]
https://pastebin.com/hMXVfayV
https://pastebin.com/LqjPw0N1﻿

**Comment by A-Charvin** [comment]
```
python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "legacy/train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 22, in <module>
    from tensorflow.python.ops import array_ops
ModuleNotFoundError: No module named 'tensorflow.python.ops'
```
How to train a new model now?

**Comment by netanel-s** [comment]
with model_main.py

**Comment by k-w-w** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
