### ISSUE TITLE
Message type "object_detection.protos.SsdFeatureExtractor" has no field named "fpn".

### ISSUE THREAD

**Issue by mjjdick** [tensorflow/models#5162]
Hi, all:
    I just follow the install guide of `object detection`. everything is OK but when I testing the installation, the error is like follow:
```
.........E.E..EE..
======================================================================
ERROR: test_create_ssd_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 152, in test_create_ssd_inception_v2_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
ParseError: 64:9 : Message type "object_detection.protos.Ssd" has no field named "use_expected_classification_loss_under_sampling".

======================================================================
ERROR: test_create_ssd_mobilenet_v1_fpn_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 554, in test_create_ssd_mobilenet_v1_fpn_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
ParseError: 7:11 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "fpn".

======================================================================
ERROR: test_create_ssd_mobilenet_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 707, in test_create_ssd_mobilenet_v2_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
ParseError: 64:9 : Message type "object_detection.protos.Ssd" has no field named "weight_regression_loss_by_score".

======================================================================
ERROR: test_create_ssd_resnet_v1_fpn_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 316, in test_create_ssd_resnet_v1_fpn_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
ParseError: 5:11 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "fpn".

----------------------------------------------------------------------
Ran 18 tests in 0.057s

FAILED (errors=4)

```

I searched on the net about these errors,but found nothing. so, anyone could help me? thx very much!!

**Comment by yinguobing** [comment]
Try recompiling the proto files according to the official document [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md).

**Comment by mjjdick** [comment]
@yinguobing  thx for your replying, I have tried the `Manual protobuf-compiler installation and usage`, and download the protobuf with 3.0 version, and got the error.  Is there anything I missed?

**Comment by yinguobing** [comment]
Sorry the previous comment is not very clear. You only need to recompile the **proto files** located in `object_detection/protos` with following command:
```
# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.
```
You might not need to use protobuf version 3.0. The version 3.5.1 works well by my side.

**Comment by mjjdick** [comment]
@yinguobing It is so wired, I have install protobuf-3.5.1, and I checked
```
$ protoc --version
libprotoc 3.5.1
```
but I still encounter this error. it maybe something wrong in other place?

**Comment by Mr-Optimistic** [comment]
Hi ..SSD inception works fine..however facing the same issue with SSD resnet ..protoc version = 3.5.1...doesnt help even after re compiling the protoc files

**Comment by Mr-Optimistic** [comment]
i did a git pull for models...recompiled the protoc files..it works fine now

**Comment by jillelajitta** [comment]
Hi,
Sorry for hijacking this thread.
I'm getting following warnings when I'm trying to retrain my model, I am using SSD+GoogleNet. Please someone help me.

Thanks.

WARNING:tensorflow:Ignoring ground truth with image id 2132974076 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 2132974076 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 483474429 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 483474429 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1042541771 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1042541771 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 374107777 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 374107777 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 851704672 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 851704672 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1267094741 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1267094741 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 674017641 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 674017641 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 2011324514 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 2011324514 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 655823972 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 655823972 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1069886348 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1069886348 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 432647899 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 432647899 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 192947873 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 192947873 since it was previously added

**Comment by xiongcaihua** [comment]
> i did a git pull for models...recompiled the protoc files..it works fine now

can you tell me how work you did

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
