### ISSUE TITLE
Getting error while running pretrain.py for adversarial text

### ISSUE THREAD

**Issue by javedsha** [tensorflow/models#5175]
- **What is the top-level directory of the model you are using**:
adversarial_text

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 17.10

- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.10
-**Keras version**:
2.1.6-tf
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
9.0, 7.1
- **GPU model and memory**:
K80, 56 GB memory
- **Exact command to reproduce**:
pretrain.py

### Describe the problem
Getting below error while running pretrain.py script in adversarial_text folder:

**TypeError: Expected int64, got -1.0 of type 'float' instead.**

I have tried with python 2.7 and 3.6, but still getting the same error. Below is the log:

_python pretrain.py --train_dir=/datadrive/experiments/vat/imdb/pretrain/ --data_dir=/datadrive/experiments/vat/imdb/output/ --vocab_size=87007 --embedding_dims=256 --rnn_cell_size=1024 --num_candidate_samples=1024 --batch_size=256 --learning_rate=0.001 --learning_rate_decay_factor=0.9999 --max_steps=100000 --num_timesteps=400 --max_grad_norm=1.0 --num_timesteps=400 --keep_prob_emb=0.5 --normalize_embeddings_

INFO:tensorflow:Constructing TFRecordReader from files: ['/datadrive/experiments/vat/imdb/output/train_lm.tfrecords']
Traceback (most recent call last):
  File "pretrain.py", line 46, in <module>
    tf.app.run()
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "pretrain.py", line 41, in main
    train_op, loss, global_step = model.language_model_training()
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/graphs.py", line 162, in language_model_training
    loss = self.language_model_graph()
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/graphs.py", line 222, in language_model_graph
    return self._lm_loss(inputs, compute_loss=compute_loss)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/graphs.py", line 231, in _lm_loss
    embedded = self.layers['embedding'](inputs.tokens)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 728, in __call__
    self.build(input_shapes)
  **File "/datadrive/experiments/vat/imdb/code/adversarial_text/layers.py", line 70,** in build
    name='embedding')
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 565, in add_weight
    aggregation=aggregation)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 535, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1918, in make_variable
    aggregation=aggregation)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2443, in variable
    aggregation=aggregation)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2425, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2395, in default_variable_creator
    constraint=constraint)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 312, in __init__
    constraint=constraint)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 417, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1903, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 256, in __call__
    shape, self.minval, self.maxval, dtype, seed=self.seed)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 235, in random_uniform
    minval = ops.convert_to_tensor(minval, dtype=dtype, name="min")
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 998, in convert_to_tensor
    as_ref=False)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 436, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/datadrive/experiments/vat/imdb/code/adversarial_text/gpu-tf-python2/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 347, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
**TypeError: Expected int64, got -1.0 of type 'float' instead.**

**Comment by javedsha** [comment]
I looked a little bit into the code of Keras, and looks like it could be keras version issue. Which version of tf.keras is recommended to repro the work? The keras version i have is - 2.1.6-tf.

**Comment by javedsha** [comment]
Okay, so I have resolved this issue.

The problem 'I think' is the code doesn't support tensorflow 1.10.
I have to install tensorflow-gpu 1.4.0 and hence cuDNN 6.0 and hence CUDA 8.0

It would be good to update the instruction page.
Thanks.

**Comment by ethir** [comment]
1) in Embedding,add   dtype=tf.float32  to the self.var 
2) In  SoftmaxLoss class, input_shape = input_shape[0].as_list()    in the build function

**Comment by khorshidisamira** [comment]
> 
> 
> in tensorflow1.8.0 ,I change those places
> 
>     1. In Embedding,add   dtype=tf.float32  to the self.var
> 
>     2. In  SoftmaxLoss class, input_shape = input_shape[0].as_list()    in the build function

Hi,
Can you explain how and where do "add dtype=tf.float32 to the self.var" ?
thanks

**Comment by dallascard** [comment]
Just to expand on the answer from @ethir 
In `layers.py`, on lines 67-70, add `dtype=tf.float32`, changing
```     
self.var = self.add_weight(
shape=(self.vocab_size, self.embedding_dim),
initializer=tf.random_uniform_initializer(-1., 1.),
name='embedding')
```
to
```
self.var = self.add_weight(
shape=(self.vocab_size, self.embedding_dim),
initializer=tf.random_uniform_initializer(-1., 1.),
name='embedding', dtype=tf.float32)
```
and on line 155, change:
`input_shape = input_shape[0]`
to
`input_shape = input_shape[0].as_list()`
