### ISSUE TITLE
Slim issue dataset_utils.py Python 3.5

### ISSUE THREAD

**Issue by ardiya** [tensorflow/models#528]
## Please let us know which model this issue is about (specify the top-level directory)
I am trying to use inception model in Slim. I use Tensorflow 0.11.0rc0 nightly binaries and have verified the installation of TF-slim image models library. However, when executing 

> ardiya@UBUNTU-PC:~/workspace/models/slim$ scripts/finetune_inception_v1_on_flowers.sh

I got this error. I don't know how to fix it. Please help

```
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/home/ardiya/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 415, in main
    FLAGS.dataset_name, FLAGS.dataset_split_name, FLAGS.dataset_dir)
  File "/home/ardiya/workspace/models/slim/datasets/dataset_factory.py", line 57, in get_dataset
    reader)
  File "/home/ardiya/workspace/models/slim/datasets/flowers.py", line 89, in get_split
    labels_to_names = dataset_utils.read_label_file(dataset_dir)
  File "/home/ardiya/workspace/models/slim/datasets/dataset_utils.py", line 129, in read_label_file
    lines = lines.split('\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by vonclites** [comment]
Check out this guy's fix: https://github.com/tensorflow/models/pull/503
I haven't tried it yet...

**Comment by asimshankar** [comment]
PR merged, this should be fixed now.
