### ISSUE TITLE
im2txt: ImportError: No module named inception_v3 

### ISSUE THREAD

**Issue by ProgramItUp** [tensorflow/models#532]
## Please let us know which model this issue is about (specify the top-level directory)
models/im2txt/
@cshallue 

I have followed the instructions for installing and configuring im2txt on Ubuntu 14.04 but am having trouble running bazel-bin/im2txt/train.  The error is No module named inception_v3.

Is this a problem with im2txt or my installation or configuration? 
Thanks.

```
myMachine:~/tensorflow_models/models$ cd im2txt/
myMachine:~/tensorflow_models/models/im2txt$ bazel build -c opt im2txt/...
INFO: Found 17 targets...
INFO: Elapsed time: 0.256s, Critical Path: 0.01s

myMachine:~/tensorflow_models/models/im2txt$ bazel-bin/im2txt/train   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=100
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/data/home/user123/tensorflow_models/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 25, in <module>
    from im2txt import show_and_tell_model
  File "/data/home/user123/tensorflow_models/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 29, in <module>
    from im2txt.ops import image_embedding
  File "/data/home/user123/tensorflow_models/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/image_embedding.py", line 25, in <module>
    from tensorflow.contrib.slim.python.slim.nets.inception_v3 import inception_v3_base
    ImportError: No module named inception_v3
    myMachine:~/tensorflow_models/models/im2txt$ ls -l ${INCEPTION_CHECKPOINT}
-rw-r----- 1 user123 user123 108816380 Aug 28 20:21 /home/user123/tensorflow_models/models/im2txt/data/inception_v3.ckpt
myMachine:~/tensorflow_models/models/im2txt$
```

**Comment by jart** [comment]
@cshallue Why is `//third_party/py/tensorflow` removed when exporting the tensorflow/models BUILD files to GitHub? Shouldn't it be replaced with things like `@org_tensorflow//tensorflow/contrib/slim:nets`?

CC: @gunan @wicke

**Comment by gunan** [comment]
I think you need to install the pip package of tensorflow to your system first.
Then bazel build should work.
I just verified that tensorflow pip package includes your missing package
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.contrib.slim.python.slim.nets.inception_v3 import inception_v3_base
>>> 

@jart I think that is the reason we remove the dependency to tensorflow in models repo, just like removing explicit dependency to numpy.

**Comment by ProgramItUp** [comment]
@gunan 
Unfornuately, I don't think that is not the problem- it was already installed.  For good measure, I tried reinstalling TensorFlow but it did not solve the problem. 

```
~/tensorflow_models/models/im2txt$ pip freeze
..... other packages ....
tensorflow==0.10.0
..... other packages ....
:~/tensorflow_models/models/im2txt$ sudo -E pip install tensorflow
Requirement already satisfied (use --upgrade to upgrade): tensorflow in /usr/local/lib/python2.7/dist-packages
Cleaning up...
~/tensorflow_models/models/im2txt$ bazel-bin/im2txt/train   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=100
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/data/home/user123/tensorflow_models/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 25, in <module>
    from im2txt import show_and_tell_model
  File "/data/home/user123/tensorflow_models/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 29, in <module>
    from im2txt.ops import image_embedding
  File "/data/home/user123/tensorflow_models/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/image_embedding.py", line 25, in <module>
    from tensorflow.contrib.slim.python.slim.nets.inception_v3 import inception_v3_base
ImportError: No module named inception_v3
```

**Comment by ProgramItUp** [comment]
Looks like something might have gone right during an upgrade of Tensorflow, it looks like a problem with CUDA. 

```
python
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
modprobe: FATAL: Module nvidia not found.
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:140] kernel driver does not appear to be running on this host (gozer06): /proc/driver/nvidia/version does not exist
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
```

Here is what happens running covenet_mnist.py .  

https://github.com/kendricktan/suiron/issues/3

```
~/tensorflow_models/models/im2txt$ python covenet_mnist.py
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Downloading MNIST...
Succesfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting mnist/train-images-idx3-ubyte.gz
Downloading MNIST...
Succesfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting mnist/train-labels-idx1-ubyte.gz
Downloading MNIST...
Succesfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting mnist/t10k-images-idx3-ubyte.gz
Downloading MNIST...
Succesfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting mnist/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "covenet_mnist.py", line 31, in <module>
    network = conv_2d(network, 32, 3, activation='relu', regularizer="L2")
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/conv.py", line 72, in conv_2d
    with tf.variable_scope(scope, name, values=[incoming], reuse=reuse) as scope:
  File "/usr/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
TypeError: variable_scope() got an unexpected keyword argument 'values'
```

**Comment by cshallue** [comment]
I see from your code snippet that you're running TensorFlow 0.10?

> tensorflow==0.10.0

As I [mention](https://github.com/tensorflow/models/tree/master/im2txt#install-required-packages) in the documentation you need TensorFlow [installed from source](https://www.tensorflow.org/versions/master/get_started/os_setup.html#installing-from-sources) to run this model because, in particular, `tensorflow.contrib.slim.python.slim.nets.inception_v3` was included after 0.10.

**Comment by gunan** [comment]
How about 0.11.0rc0?

**Comment by ProgramItUp** [comment]
@cshallue 
Thanks for your reply.
Would a better link at this time for building from sources for version greater than 0.10 be this?https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#installing-from-sources

Thanks,

**Comment by cshallue** [comment]
@gunan yes, I suspect 0.11.0rc0 will work but I haven't tried it myself
@ProgramItUp those two links should be equivalent, I think.

**Comment by ProgramItUp** [comment]
Installing 0.11.0rc0 via the [.wrl file](https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl) and cuDNN v5 fixed the problem.  Note: building from source was not needed.

Thanks all for the help.
