### ISSUE TITLE
How to train Nasnet on multiple servers

### ISSUE THREAD

**Issue by heweijia02** [tensorflow/models#5346]
Tensorflow version :1.10.1
model: Nasnet_large

I have 8 servers, each with 8 GPUs, and I have started training Nasnet_large on one of them. The command used is:
 python train_image_classifier.py  --train_dir=${TRAIN_DIR}  --dataset_dir=${DATASET_DIR} --dataset_name=imagenet --dataset_split_name=train --model_name=nasnet_large --checkpoint_path=${CHECKPOINT_PATH}  --checkpoint_exclude_scopes=final_layer  trainable_scopes=final_layer --batch_size=8 --num_clones=8 --max_number_of_steps=100 --worker_replicas=1 --num_ps_tasks=0 --log_every_n_steps=100

Currently I need to train Nasnet_large on 8 servers (64 GPUs), but I don't know what command to use? How can I get them to run? Github does not describe how to run on multiple servers?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by heweijia02** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

1、What is the top-level directory of the model you are using
https://github.com/tensorflow/models/tree/master/research/slim

2、Have I written custom code  
NO

3、OS Platform and Distribution
Ubuntu 16.04.3 LTS \n \l

4 、TensorFlow installed from
pip install tensorflow 1.10.1

5、Bazel version
16.1

6、CUDA/cuDNN version
cuda 9.0/ cuDNN7.0.5

7、GPU model and memory
Nvidia GPU P100 /16GB memory

8、Exact command to reproduce

I have tried to deploy NASNET on 3 servers.
（1）Configure the command for the cluster:
1）configure PS
TF_CONFIG='{"environment": "cloud", "cluster": {"ps": ["172.17.16.26:2222"],  "worker":["172.17.16.4:2222","172.17.16.1:2222"]}, "task": {"index": 0, "type": "ps"}}'

2）configure worker_0
TF_CONFIG='{"environment": "cloud", "cluster": {"ps": ["172.17.16.26:2222"],  "worker":["172.17.16.4:2222","172.17.16.1:2222"}, "task": {"index": 0, "type": "worker"}}'

3）configure worker_1
TF_CONFIG='{"environment": "cloud", "cluster": {"ps": ["172.17.16.26:2222"],  "worker":["172.17.16.4:2222","172.17.16.1:2222"}, "task": {"index": 1, "type": "worker"}}'

（2）train cmd
1）PS cmd
python train_image_classifier.py  --train_dir=${TRAIN_DIR}  --dataset_dir=${DATASET_DIR} --dataset_name=imagenet --dataset_split_name=train --model_name=nasnet_large --checkpoint_path=${CHECKPOINT_PATH}  --checkpoint_exclude_scopes=final_layer  trainable_scopes=final_layer --batch_size=4 --num_clones=4 --max_number_of_steps=100 --worker_replicas=2 --num_ps_tasks=1 --log_every_n_steps=100 --sync_replicas=False --master=grpc://172.17.16.26:2222 --task=0

2）worker_0 train cmd
python train_image_classifier.py  --train_dir=${TRAIN_DIR}  --dataset_dir=${DATASET_DIR} --dataset_name=imagenet --dataset_split_name=train --model_name=nasnet_large --checkpoint_path=${CHECKPOINT_PATH}  --checkpoint_exclude_scopes=final_layer  trainable_scopes=final_layer --batch_size=4 --num_clones=4 --max_number_of_steps=100 --worker_replicas=2 --num_ps_tasks=1 --log_every_n_steps=100 --sync_replicas=False --master=grpc://172.17.16.26:2222 --task=0

3）worker_1 train cmd
python train_image_classifier.py  --train_dir=${TRAIN_DIR}  --dataset_dir=${DATASET_DIR} --dataset_name=imagenet --dataset_split_name=train --model_name=nasnet_large --checkpoint_path=${CHECKPOINT_PATH}  --checkpoint_exclude_scopes=final_layer  trainable_scopes=final_layer --batch_size=4 --num_clones=4 --max_number_of_steps=100 --worker_replicas=2 --num_ps_tasks=1 --log_every_n_steps=100 --sync_replicas=False --master=grpc://172.17.16.26:2222 --task=1



ERROR info worker_0:
INFO:tensorflow:Fine-tuning from /data/checkpoints/model.ckpt
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:737: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnavailableError'>, OS Error
Traceback (most recent call last):
  File "train_image_classifier.py", line 581, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_image_classifier.py", line 577, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 748, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 1005, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 994, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 731, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 287, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnavailableError: OS Error

ERROR info worker_1:
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnavailableError'>, OS Error
Traceback (most recent call last):
  File "train_image_classifier.py", line 581, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_image_classifier.py", line 577, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 748, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 1005, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 994, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 739, in prepare_or_wait_for_session
    max_wait_secs=max_wait_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 408, in wait_for_session
    sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 492, in _try_run_local_init_op
    sess.run(self._local_init_op, options=self._local_init_run_options)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnavailableError: OS Error
root@G560-ubuntu1:/home/h00203740/models/research/slim#

**Comment by heweijia02** [comment]
I tried to modify --sync_replicas=False to --sync_replicas=True
Still reporting errors

error info work_0:
INFO:tensorflow:A GPU is available on the machine, consider using NCHW data format for increased speed on GPU.
INFO:tensorflow:SyncReplicasV2: replicas_to_aggregate=1; total_num_replicas=2
INFO:tensorflow:Fine-tuning from /data/checkpoints/model.ckpt
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:737: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnavailableError'>, OS Error
Traceback (most recent call last):
  File "train_image_classifier.py", line 581, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_image_classifier.py", line 577, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 748, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 1005, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 994, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 731, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 287, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnavailableError: OS Error
root@G560-ubuntu4:/home/h00203740/models/research/slim#


error info work_1:
INFO:tensorflow:A GPU is available on the machine, consider using NCHW data format for increased speed on GPU.
INFO:tensorflow:SyncReplicasV2: replicas_to_aggregate=1; total_num_replicas=2
INFO:tensorflow:Fine-tuning from /data/share/checkpoints/model.ckpt
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:737: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
Traceback (most recent call last):
  File "train_image_classifier.py", line 581, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_image_classifier.py", line 577, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 737, in train
    init_fn=init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 358, in __init__
    self._verify_setup()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 926, in _verify_setup
    "their device set: %s" % op)
ValueError: When using replicas, all Variables must have their device set: name: "sync_rep_local_step"
op: "VariableV2"
attr {
  key: "_class"
  value {
    list {
      s: "loc:@NoOp"
    }
  }
}
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT64
  }
}
attr {
  key: "shape"
  value {
    shape {
    }
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}

root@G560-ubuntu1:/home/h00203740/models/research/slim#


I don't know if I used the wrong command or other reasons, I hope I can get your guidance.
thank you~

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
