### ISSUE TITLE
module object has no attribute 'MOBILENETV1_CONV_DEFS'

### ISSUE THREAD

**Issue by adi1525** [tensorflow/models#5361]
I use Ubuntu 16.04 CPU only tensorflow version 1.5 and Python 2.7. When I try train my first model I try checkdemo:  
`models/research$ sudo python object_detection/builders/model_builder_test.py `
and I get:
```
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/builders/model_builder.py", line 46, in <module>
    from object_detection.models.ssd_mobilenet_v1_fpn_feature_extractor import SSDMobileNetV1FpnFeatureExtractor
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/models/ssd_mobilenet_v1_fpn_feature_extractor.py", line 38, in <module>
    _CONV_DEFS = _create_modified_mobilenet_config()
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/models/ssd_mobilenet_v1_fpn_feature_extractor.py", line 34, in _create_modified_mobilenet_config
    conv_defs = copy.copy(mobilenet_v1.MOBILENETV1_CONV_DEFS)
AttributeError: 'module' object has no attribute 'MOBILENETV1_CONV_DEFS'

```
there is the same when I use Python 3.5, sudo don't help.

**Comment by adi1525** [comment]
In file models/research/slim/nets/mobilenet_v1.py, must by changed _CONV_DEFS to MOBILENETV1_CONV_DEFS.

**Comment by Gowtham135** [comment]
Help me out to solve this issue

**Comment by feynmanliang** [comment]
Even after the fix given by @adi1525 , I am still getting an error trying to restore from the `ssd_mobilenet_v1` checkpoint provided in the docs

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/.local/lib/python2.7/site-packages/object_detection/model_main.py", line 102, in main
    eval_on_train_data=False)
  File "/root/.local/lib/python2.7/site-packages/object_detection/model_lib.py", line 656, in create_train_and_eval_spec
    exporters=exporter))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 237, in __new__
    raise TypeError('`name` must be string, given: {}'.format(name))
TypeError: `name` must be string, given: 0
```

**Comment by feynmanliang** [comment]
It looks like https://github.com/tensorflow/models/pull/5289/files#diff-075d9af0bc08198c52c1071434dc24bdR34 is the CL introducing this

**Comment by hammadullah125** [comment]
@feynmanliang how did you solve this https://github.com/tensorflow/models/issues/5361#issuecomment-424026422 problem?

**Comment by feynmanliang** [comment]
@hammadullah125 see https://github.com/tensorflow/models/pull/5372/files, though I believe a recent pr https://github.com/tensorflow/models/pull/5354 also resolves it and is merged.

**Comment by hammadullah125** [comment]
This https://github.com/tensorflow/models/pull/5372/files didn't solve my this https://github.com/tensorflow/models/issues/5361#issuecomment-424026422 problem.

**Comment by pkulzc** [comment]
Sync your fork to latest and this should be gone.

**Comment by hammadullah125** [comment]
@pkulzc can you explain how?

**Comment by andrea-simonelli** [comment]
I downloaded and installed the API on 31 October and still had the issue. I solved by changing the files following https://github.com/tensorflow/models/pull/5372/files.

**Comment by pkulzc** [comment]
Apparently you are not using the latest commit.
