### ISSUE TITLE
Error running pretrain.py from adversarial_text sample

### ISSUE THREAD

**Issue by sahararaghi** [tensorflow/models#5447]
### System information
- **What is the top-level directory of the model you are using**: `research/adversarial_text/`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: installed through `pip`
- **TensorFlow version (use command below)**: 1.11.0
- **Bazel version (if compiling from source)**: not relevant
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: NVidia Quadro M2000; 4GB Dedicated, 16 GB Shared
- **Exact command to reproduce**: 

```
pretrain.py --train_dir=c:\Users\saraghi\PycharmProjects\Adv-text-tensor\data\tmp\models\imdb_pretrain --data_dir=c:\Users\saraghi\PycharmProjects\Adv-text-tensor\data\tmp\imdb --vocab_size=45872 --embedding_dims=256 --rnn_cell_size=1024 --num_candidate_samples=1024 --batch_size=256 --learning_rate=0.001 --learning_rate_decay_factor=0.9999 --max_steps=100000 --max_grad_norm=1 --num_timesteps=400 --keep_prob_emb=0.5 --normalize_embeddings
```

### Describe the problem

I am using python 3.6.5 from Anaconda 3. I completed generating vocabulary, and training, validation and test data. I was trying to run `pretrain.py` from the sample without any modifications, but this is the error I get:

```
C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Constructing TFRecordReader from files: ['c:\\Users\\saraghi\\PycharmProjects\\Adv-text-tensor\\data\\tmp\\imdb\\train_lm.tfrecords']
WARNING:tensorflow:From C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\training\input.py:187: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\training\input.py:187: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Traceback (most recent call last):
  File "C:/Users/saraghi/PycharmProjects/Adv-text-tensor/pretrain.py", line 52, in <module>
    tf.app.run()
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:/Users/saraghi/PycharmProjects/Adv-text-tensor/pretrain.py", line 47, in main
    train_op, loss, global_step = model.language_model_training()
  File "C:\Users\saraghi\PycharmProjects\Adv-text-tensor\graphs.py", line 162, in language_model_training
    loss = self.language_model_graph()
  File "C:\Users\saraghi\PycharmProjects\Adv-text-tensor\graphs.py", line 223, in language_model_graph
    return self._lm_loss(inputs, compute_loss=compute_loss)
  File "C:\Users\saraghi\PycharmProjects\Adv-text-tensor\graphs.py", line 232, in _lm_loss
    embedded = self.layers['embedding'](inputs.tokens)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 759, in __call__
    self.build(input_shapes)
  File "C:\Users\saraghi\PycharmProjects\Adv-text-tensor\layers.py", line 70, in build
    name='embedding')
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 586, in add_weight
    aggregation=aggregation)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 591, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1986, in make_variable
    aggregation=aggregation)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 145, in __call__
    return cls._variable_call(*args, **kwargs)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 141, in _variable_call
    aggregation=aggregation)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 120, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2434, in default_variable_creator
    import_scope=import_scope)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 147, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 297, in __init__
    constraint=constraint)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 411, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1970, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py", line 254, in __call__
    shape, self.minval, self.maxval, dtype, seed=self.seed)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\random_ops.py", line 235, in random_uniform
    minval = ops.convert_to_tensor(minval, dtype=dtype, name="min")
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1048, in convert_to_tensor
    as_ref=False)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1144, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 228, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 207, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 442, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "C:\Users\saraghi\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 353, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int64, got -1.0 of type 'float' instead.

Process finished with exit code 1
```

**Comment by khorshidisamira** [comment]
@sahararaghi @tensorflowbutler I have the same error, how can I solve it?
Thanks

**Comment by sahararaghi** [comment]
My problem is solved by using CUDA 8 and Python 2.7 on Linux Ubuntu 16.04

**Comment by khorshidisamira** [comment]
I'm using python 3.6 and Windows 10.

**Comment by sahararaghi** [comment]
I think the error is because of the CUDA version, and the code is written
for python 2.7 (as I understood there is some difficulty to have
tensorflow-gpu in python 2.7 on Windows system). I couldn't fix the error
for python 3.6 and Windows 10, then I decided to run it on a similar
environment and setting to the original code.
