### ISSUE TITLE
Negative dimension size caused by subtracting 8 from 7 for op: 'AvgPool'

### ISSUE THREAD

**Issue by vilmara** [tensorflow/models#5456]
### System information
**What is the top-level directory of the model you are using: models/tree/master/research/tensorrt
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-134-generic x86_64)
**TensorFlow installed from (source or binary): via container image nvcr.io/nvidia/tensorflow:18.07-py3
**TensorFlow version (use command below): 1.8
**TensoRT version: 4.0.1.
**Bazel version (if compiling from source): n/a
**CUDA/cuDNN version: 9.0/7.1.4
**GPU model and memory: Tesla P4 / 7 GB
**Exact command to reproduce: python3 tensorrt_v2.py --savedmodel_dir=/home/saved_model/1538691479/ --image_file=image.jpg --native --fp32 --output_dir=/home/output_tensorrt/ --batch_size=64

### Describe the problem
I have modified the script tensorrt.py to accelerate the inference of my model (trained with TensorFlow and exported the inference graph as a SavedModel). The script runs fine for the inference mode FP32, but throws errors for native mode

### Source code / logs
**Inference mode: native**
```
INFO:tensorflow:Restoring parameters from b'/home/saved_model/1538691479/variables/variables'
INFO:tensorflow:Froze 251 variables.
Converted 251 variables to const ops.
graph_name frozen_graph.pb:
Running native graph
native_frozen_graph.pb
INFO:tensorflow:Starting execution
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 489, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError:
 
Negative dimension size caused by subtracting 8 from 7 for 'import/resnet_model/average_pooling2d/AvgPool' (op: 'AvgPool') with input shapes: [32,7,7,2048].

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tensorrt_v2.py", line 635, in <module>
    main(argv=sys.argv)
  File "tensorrt_v2.py", line 480, in main
    g_name, frozen_graph_def, data, log_buffer, flags)
  File "tensorrt_v2.py", line 376, in time_and_log_graph
    graph_def, data, flags.input_node, flags.output_node, flags.num_loops)
  File "tensorrt_v2.py", line 314, in time_graph
    return_elements=[output_node]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 493, in import_graph_def
    raise ValueError(str(e))

```

**Comment by vilmara** [comment]
hi, I resolved the issue by changing padding='same' to my average_pooling2d layer in my model
 
```
      inputs = tf.layers.average_pooling2d(
          inputs=inputs, pool_size=pool_size, strides=1, padding='SAME',
          data_format=data_format)
```

before it was padding='VALID', which was generating the error `Negative dimension size caused by subtracting 8 from 7 for op: 'AvgPool'`

For more information see this link: `https://stackoverflow.com/questions/47324571/keras-valueerror-negative-dimension-size-caused-by-subtracting-5-from-1`
