### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError: flag --train_logdir=None: Flag --train_logdir must be specified.

### ISSUE THREAD

**Issue by NazariAmin** [tensorflow/models#5466]
Nazari:deeplab Amin$ python train.py \ --logtostderr \ --training_number_of_steps=10 \ --train_split="train" \ --model_variant="xception_65" \ --atrous_rates=6 \ --atrous_rates=12 \ --atrous_rates=18 \ --output_stride=16 \ --decoder_output_stride=4 \ --train_crop_size=513 \ --train_crop_size=513 \ --train_batch_size=1 \ --dataset="pascal_voc_seg" \ --tf_initial_checkpoint="datasets/pascal_voc_seg/init_models/deeplabv3_pascal_train_aug/model.ckpt" \ --train_logdir="datasets/pascal_voc_seg/exp/train_on_trainval_set/train/" \ --dataset_dir="./datasets/pascal_voc_seg/tfrecord/"
Traceback (most recent call last):
  File "/Users/macbook/anaconda/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 527, in _assert_validators
    validator.verify(self)
  File "/Users/macbook/anaconda/lib/python3.5/site-packages/absl/flags/_validators.py", line 81, in verify
    raise _exceptions.ValidationError(self.message)
absl.flags._exceptions.ValidationError: Flag --train_logdir must be specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 394, in <module>
    tf.app.run()
  File "/Users/macbook/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/Users/macbook/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/Users/macbook/anaconda/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 635, in __call__
    self._assert_all_validators()
  File "/Users/macbook/anaconda/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 509, in _assert_all_validators
    self._assert_validators(all_validators)
  File "/Users/macbook/anaconda/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 530, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --train_logdir=None: Flag --train_logdir must be specified.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Robinxin123** [comment]
i met the same problem, do u solve it ?

**Comment by kumariko** [comment]
@NazariAmin We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. we will get you the right help.Thanks!
