### ISSUE TITLE
TypeError: `name` must be string, given: 0

### ISSUE THREAD

**Issue by hammadullah125** [tensorflow/models#5503]
Hello, Whenever I'm running "model_main.py", it is throwing this error. I have checked my annotations and other things thoroughly but everything seems to be fine. Any possible solutions ??? 

```
hull@ori:~/Desktop/models-master/research/object_detection$ python3 model_main.py --logtostderr --train_dir=/export/users/hull/Desktop/models-master/research/object_detection/training/ --pipeline_config_path=/export/users/hull/Desktop/models-master/research/object_detection/training/ssd_mobilenet_v1_pets.config
/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/utils/visualization_utils.py:27: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
W1011 21:32:46.516586 140555700737792 tf_logging.py:126] Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
W1011 21:32:46.516783 140555700737792 tf_logging.py:126] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpzk8wai22
W1011 21:32:46.517589 140555700737792 tf_logging.py:126] Using temporary folder as model directory: /tmp/tmpzk8wai22
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7fd535d80ae8>) includes params argument, but params are not passed to Estimator.
W1011 21:32:46.518054 140555700737792 tf_logging.py:126] Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7fd535d80ae8>) includes params argument, but params are not passed to Estimator.
Traceback (most recent call last):
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "model_main.py", line 102, in main
    eval_on_train_data=False)
  File "/usr/local/lib/python3.5/dist-packages/object_detection-0.1-py3.5.egg/object_detection/model_lib.py", line 656, in create_train_and_eval_specs
    exporters=exporter))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 220, in __new__
    raise TypeError('`name` must be string, given: {}'.format(name))
TypeError: `name` must be string, given: 0

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hammadullah125** [comment]
@k-w-w any solutions or suggestions?
