### ISSUE TITLE
TypeError: resize_images() takes at least 3 arguments (3 given)

### ISSUE THREAD

**Issue by phoenixqza** [tensorflow/models#552]
Inception: 
sudo bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir="${DATA_DIR}"

Traceback (most recent call last):
  File "/home/phoenixqq/PycharmProjects/models-master/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/phoenixqq/PycharmProjects/models-master/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/phoenixqq/PycharmProjects/models-master/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 216, in train
    num_preprocess_threads=num_preprocess_threads)
  File "/home/phoenixqq/PycharmProjects/models-master/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 136, in distorted_inputs
    num_readers=FLAGS.num_readers)
  File "/home/phoenixqq/PycharmProjects/models-master/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 491, in batch_inputs
    image = image_preprocessing(image_buffer, bbox, train, thread_id)
  File "/home/phoenixqq/PycharmProjects/models-master/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 326, in image_preprocessing
    image = distort_image(image, height, width, bbox, thread_id)
  File "/home/phoenixqq/PycharmProjects/models-master/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 257, in distort_image
    method=resize_method)
TypeError: resize_images() takes at least 3 arguments (3 given)

I followed each step in readme.md, while cannot train the model.

**Comment by asimshankar** [comment]
The `resize_images` function changed a bit in the 0.11 release because of tensorflow/tensorflow@8d1b23d999a563c56236a3d250e18ef825e4e66e and the code in `inception/image_processing.py` was updated to use the changed function signature in 253ca4ab8101dc2c2404530680b4a12e7518572d

Could you retry after either upgrading your TensorFlow installation to 0.11rc0 ?

**Comment by savage7** [comment]
Updatening to 0.11rc0 works.
