### ISSUE TITLE
API object detection error for multi-object detection

### ISSUE THREAD

**Issue by bellahcenmarwane** [tensorflow/models#5534]
when i execute this instruction
python3 legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=pipeline3.config

 with different architecture  i get this error :

Traceback (most recent call last):
  File "legacy/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/marwane/object__datection/models/research/object_detection/legacy/trainer.py", line 303, in train
    train_config.optimizer)
  File "/home/marwane/object__datection/models/research/object_detection/builders/optimizer_builder.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "/home/marwane/object__datection/models/research/object_detection/builders/optimizer_builder.py", line 112, in _create_learning_rate
    learning_rate_sequence, config.warmup)
  File "/home/marwane/object__datection/models/research/object_detection/utils/learning_schedules.py", line 160, in manual_stepping
    raise ValueError('First step cannot be zero.')
ValueError: First step cannot be zero.

**Comment by wt-huang** [comment]
@bellahcenmarwane Which architecture did you encounter this issue?

**Comment by twhitloc** [comment]
There is a problem with your train config in your Optimizer, the manual training schedule is not necessary.
If you look at the new sample configs you can modify your Optimizer to the new layout to match.

**Comment by bellahcenmarwane** [comment]
can you plz give more details

**Comment by twhitloc** [comment]
Sure, if you can post the train config section of your pipeline I can highlight the change.

Otherwise to put it a bit more concretely, in the  ``train_config: {}``
Where you have your ``optimizer {}`` if you have something like this:
   ``  schedule {
        step: 0
        learning_rate: .0001
      }``
You need to remove it in the newer versions of object detection.  [You can find more information here    #3794](https://github.com/tensorflow/models/issues/3794)

**Comment by bellahcenmarwane** [comment]
i try to change Learning_rate  but it not work for me

**Comment by twhitloc** [comment]
If you could post your train config I will post the fix.  
Alternatively pull the newest configs from the samples folder and use one of those, or check the other thread for perhaps better explanation.

Essentially:
If you delete the ``schedule {...}`` you should be able to use that config.

**Comment by wt-huang** [comment]
@twhitloc is correct that schedule block needs to be removed and learning rate has to specified separately in the config file.
