### ISSUE TITLE
something wrong when ssd mobilenetv2 training

### ISSUE THREAD

**Issue by 1453042287** [tensorflow/models#5567]
### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
pypi tensorflow-gpu
- **TensorFlow version (use command below)**:
1.11
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA9.0 cuDNN7.3
- **GPU model and memory**:
TITAN V 11G
- **Exact command to reproduce**:
CUDA_VISIBLE_DEVICES=0   python  object_detection/model_main.py --pipeline_config_path=project/ssdlite_mobilenet_v2_coco_2018_05_09/ssdlite.config --model_dir=project/ssdlite_result --num_train_steps=100000 --sample_1_of_n_eval_examples=1 --alsologtostderr

### Describe the problem
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

### Source code / logs
Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1304, in run
    run_metadata=run_metadata))
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 581, in after_run
    if self._save(run_context.session, global_step):
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 606, in _save
    if l.after_save(session, step):
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 517, in after_save
    self._evaluate(global_step_value)  # updates self.eval_result
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 537, in _evaluate
    self._evaluator.evaluate_and_export())
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 912, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 476, in evaluate
    return _evaluate()
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 462, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1422, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1455, in _call_model_fn_eval
    input_fn, model_fn_lib.ModeKeys.EVAL)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1049, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1136, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/chi_zhang/models/research/object_detection/inputs.py", line 568, in _eval_input_fn
    transform_input_data_fn=transform_and_pad_input_data_fn)
  File "/home/chi_zhang/models/research/object_detection/builders/dataset_builder.py", line 134, in build
    config.input_path[:], input_reader_config)
  File "/home/chi_zhang/models/research/object_detection/builders/dataset_builder.py", line 80, in read_dataset
    sloppy=config.shuffle))
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1128, in apply
    dataset = transformation_func(self)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 87, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 128, in __init__
    cycle_length, block_length)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2312, in __init__
    super(InterleaveDataset, self).__init__(input_dataset, map_func)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2275, in __init__
    experimental_nested_dataset_support=True)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1473, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 865, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1411, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 194, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1048, in convert_to_tensor
    as_ref=False)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1144, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/chi_zhang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 981, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
