### ISSUE TITLE
ImportError: No module named protos

### ISSUE THREAD

**Issue by farzadhallaji** [tensorflow/models#5574]
I  follow this installation [instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)

 so I test it by `python object_detection/builders/model_builder_test.py`
but I got error.

```
<path to tensorflow/models/research> $ python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/builders/model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/builders/anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: No module named protos




```

**Comment by wt-huang** [comment]
@farzadhallaji I ran the above command without running into any errors. 
Could you provide more information by filling out the issue template?

**Comment by farzadhallaji** [comment]
you'r right. it was because I ran commands in different terminals.
