### ISSUE TITLE
AttributeError: 'module' object has no attribute 'keras'

### ISSUE THREAD

**Issue by farzadhallaji** [tensorflow/models#5590]
I follow [this](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) install instructions 
when I was Testing the Installation I got this error
```
$ python object_detection/builders/model_builder_test.py

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/home/farzad/Desktop/jrnl/face recognition/tensorflow/models/research/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/home/farzad/Desktop/jrnl/face recognition/tensorflow/models/research/object_detection/builders/box_predictor_builder.py", line 21, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/home/farzad/Desktop/jrnl/face recognition/tensorflow/models/research/object_detection/predictors/convolutional_box_predictor.py", line 19, in <module>
    from object_detection.core import box_predictor
  File "/home/farzad/Desktop/jrnl/face recognition/tensorflow/models/research/object_detection/core/box_predictor.py", line 137, in <module>
    class KerasBoxPredictor(tf.keras.Model):
AttributeError: 'module' object has no attribute 'keras'

```
Python 2.7.12
TensorFlow 1.2.0
Keras 2.2.4

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by farzadhallaji** [comment]
What is the top-level directory of the model you are using : research/object_detection 
Have I written custom code : NO
OS Platform and Distribution : Linux Mint 18.4
TensorFlow installed from : [PyPI](https://pypi.org/project/tensorflow/)
TensorFlow version : 1.2.0
Bazel version : N/A
CUDA/cuDNN version : N/A
GPU model and memory : N/A
Exact command to reproduce : python object_detection/builders/model_builder_test.py

**Comment by farzadhallaji** [comment]
it's solved with updating tensorflow.
`pip install -U tensorflow`
