### ISSUE TITLE
Using eval() for Decode JPEG 

### ISSUE THREAD

**Issue by danleh93** [tensorflow/models#564]
## [tensorflow/models/slim/preprocessing/inception_preprocessing](https://github.com/tensorflow/models/blame/master/slim/preprocessing/inception_preprocessing.py#L237)

I modified the `preprocess_for_eval(...)` function to look like:

```
def preprocess_for_eval(img, height, width,
                        central_fraction=0.875, scope=None):

  image = tf.image.convert_image_dtype(tf.image.decode_jpeg(img, channels=3), dtype=tf.float32)

  with tf.name_scope(scope, 'eval_image', [image, height, width]):
    if image.dtype != tf.float32:
      image = tf.image.convert_image_dtype(image, dtype=tf.float32)
    # Crop the central region of the image with an area containing 87.5% of
    # the original image.
    if central_fraction:
      image = tf.image.central_crop(image, central_fraction=central_fraction)

    if height and width:
      # Resize the image to the specified height and width.
      image = tf.expand_dims(image, 0)
      image = tf.image.resize_bilinear(image, [height, width],
                                       align_corners=False)
      image = tf.squeeze(image, [0])
    image = tf.sub(image, 0.5)
    image = tf.mul(image, 2.0)
    return image
```

The code executes perfectly, however, when I do something like 

`image_tensor = preprocess_for_eval("path/to/image.jpeg",300,300).eval(session=sess)`

I get an error stating:

```
Traceback (most recent call last):
  File "preprocess_for_eval.py", line 53, in <module>
    print(image.eval())
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 564, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3784, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Invalid JPEG data, size 52
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](DecodeJpeg/contents)]]

Caused by op u'DecodeJpeg', defined at:
  File "preprocess_for_eval.py", line 50, in <module>
    image = preprocess_for_eval('/home/ec2-user/workspace/results/flowers/daisy2.jpeg', 300,300)
  File "preprocess_for_eval.py", line 29, in preprocess_for_eval
    image = tf.image.convert_image_dtype(tf.image.decode_jpeg(img, channels=3), dtype=tf.float32)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 283, in decode_jpeg
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2403, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1305, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Invalid JPEG data, size 52
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](DecodeJpeg/contents)]]
```

I know for a fact that my image is a JPEG because when I do:

`file image.jpeg` on the command line I get:

`JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 300x300, frames 3`

Even when I try ```tf.image.decode_png``` I get an invalid PNG header message.

**Comment by asimshankar** [comment]
@danleh93 : It is possible that the image is not valid (at 52-bytes, it seems really small :)
Note that `file image.jpeg` is just reading the header, so it is possible that the image file's content was truncated making it an invalid jpeg but still keeping the small header intact enough for `file` to think that it is an image.

Does the image load up correctly in an image viewer? You can also try the `identify` tool to see if it is really a valid image.

Let us know what you find.
Thanks.

**Comment by asimshankar** [comment]
Oh, wait, sorry, I missed something.
You're passing the filename to `tf.decode_jpeg`, which is not what it takes. It takes a string tensor that is the contents of the file. See https://www.tensorflow.org/api_docs/python/image.html#decode_jpeg

So the 52-bytes is the file.
Instead you want something like this:
```python
contents = ''
with open('path/to/image.jpeg') as f:
   contents = f.read()
tf.image.decode_jpeg(contents)
```

Hope that helps.

**Comment by danleh93** [comment]
That worked! Can't believe I forgot about that part. Thanks so much!

**Comment by UpCoder** [comment]
Hi~, I meet a problem about convert_image_dtype.
```python
    with open('/home/give/Documents/dataset/ADEChallengeData2016/images/validation/ADE_val_00000001.jpg') as f:
        content = f.read()
    image = tf.image.decode_jpeg(content, channels=3)
    image_float = tf.image.convert_image_dtype(image, dtype=tf.float32)
    img, img_float = sess.run([image, image_float])
    # print img
    # print img_float
    print np.max(img_float), np.min(img_float)
```
when i execute this code, why np.max(img_float), np.min(img_float) both are nan? The value of img is normal. Do you know the reason? Thanks

**Comment by clovking** [comment]
@danleh93 ,  I meet a silimar question with you when i train models on google TensorFlow Object Detection API, May i ask if the question has been solved? what's the problem and how to solved? thank you!
