### ISSUE TITLE
Failed to reproduce frozen inference graph as in models zoo

### ISSUE THREAD

**Issue by adithya-p** [tensorflow/models#5640]
### System information
- **What is the top-level directory of the model you are using**: tensorflow/models/tree/master/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11.0
- **Bazel version (if compiling from source)**: 0.17.2
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: -

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

**These are the exact steps I am following:**

- Training `ssd_inception_v2` model with the following command:
```
PIPELINE_CONFIG_PATH={path to pipeline config file}
MODEL_DIR={path to model directory}
NUM_TRAIN_STEPS=50000
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
python object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
    --alsologtostderr
```
-  Exporting the trained model for inference with the following command:
```
INPUT_TYPE=image_tensor
PIPELINE_CONFIG_PATH={path to pipeline config file}
TRAINED_CKPT_PREFIX={path to model.ckpt}
EXPORT_DIR={path to folder that will be used for export}
python object_detection/export_inference_graph.py \
    --input_type=${INPUT_TYPE} \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --trained_checkpoint_prefix=${TRAINED_CKPT_PREFIX} \
    --output_directory=${EXPORT_DIR}
```
The above command generates the frozen graph format of the exported model. **The issue is it is way different from what is given in the model zoo of object detection when visualized using tensorboard.** 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
Link to the config file: [ssd_inception_v2_coco.config ](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_inception_v2_coco.config)

**Comment by rnekk2** [comment]
@wt-huang we are able to reproduce this same issue on multiple tensorflow versions. Any update on this ?

**Comment by mkh-github** [comment]
@wt-huang any update on this?

**Comment by visignibraem** [comment]
Did someone get around this?

**Comment by mkh-github** [comment]
Not that I know of.

**Comment by Tantael** [comment]
reset to commit ae0a9409212d0072938fa60c9f85740bb89ced7e
recompile object det protoc object_detection/protos/*.proto --python_out=.
comment out # override_base_feature_extractor_hyperparams: true in pipeline config
reexport graph

**Comment by siddas27** [comment]
@Tantael commenting out "# override_base_feature_extractor_hyperparams: true" in pipeline config, throws the following error
```
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "/opt/anaconda/envs/newod/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/anaconda/envs/newod/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/anaconda/envs/newod/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/sid/models/research/object_detection/trainer.py", line 193, in train
    detection_model = create_model_fn()
  File "/home/sid/models-master/research/object_detection/builders/model_builder.py", line 634, in build
    add_summaries)
  File "/home/sid/models-master/research/object_detection/builders/model_builder.py", line 245, in _build_ssd_model
    is_training=is_training)
  File "/home/sid/models-master/research/object_detection/builders/model_builder.py", line 221, in _build_ssd_feature_extractor
    return feature_extractor_class(**kwargs)
  File "/home/sid/models-master/research/object_detection/models/ssd_inception_v2_feature_extractor.py", line 78, in __init__
    raise ValueError('SSD Inception V2 feature extractor always uses'
ValueError: SSD Inception V2 feature extractor always usesscope returned by `conv_hyperparams_fn` for both the base feature extractor and the additional layers added since there is no arg_scope defined for the base feature extractor.

```

**Comment by Tantael** [comment]
> @Tantael commenting out "# override_base_feature_extractor_hyperparams: true" in pipeline config, throws the following error
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 163, in <module>
>     tf.app.run()
>   File "/opt/anaconda/envs/newod/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/opt/anaconda/envs/newod/lib/python3.6/site-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/opt/anaconda/envs/newod/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "train.py", line 159, in main
>     worker_job_name, is_chief, FLAGS.train_dir)
>   File "/home/sid/models/research/object_detection/trainer.py", line 193, in train
>     detection_model = create_model_fn()
>   File "/home/sid/models-master/research/object_detection/builders/model_builder.py", line 634, in build
>     add_summaries)
>   File "/home/sid/models-master/research/object_detection/builders/model_builder.py", line 245, in _build_ssd_model
>     is_training=is_training)
>   File "/home/sid/models-master/research/object_detection/builders/model_builder.py", line 221, in _build_ssd_feature_extractor
>     return feature_extractor_class(**kwargs)
>   File "/home/sid/models-master/research/object_detection/models/ssd_inception_v2_feature_extractor.py", line 78, in __init__
>     raise ValueError('SSD Inception V2 feature extractor always uses'
> ValueError: SSD Inception V2 feature extractor always usesscope returned by `conv_hyperparams_fn` for both the base feature extractor and the additional layers added since there is no arg_scope defined for the base feature extractor.
> ```

Have you checked out commit I described?

**Comment by siddas27** [comment]
Yes @Tantael

**Comment by Ram-Godavarthi** [comment]
@siddas27 Did you solve the issue??

I want to run inference using C++ sampleUffSSD.cpp in TensorRT.
Any solutions to this??
