### ISSUE TITLE
pyfunc_1 returns 3 values, but expects to see 1 values.

### ISSUE THREAD

**Issue by shengheng1018** [tensorflow/models#5661]
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
pip install tensorflow-gpu
- **TensorFlow version (use command below)**:
1.11
- **Bazel version (if compiling from source)**:
none
- **CUDA/cuDNN version**:
CUDA9.0 cuDNN7.2
- **GPU model and memory**:
GeForce  GTX 1080Ti   11G
- **Exact command to reproduce**:
python models\research\object_detection\model_main.py --alsologtostderr --num_eval_steps=500 --num_train_steps=100000 --model_dir=training\ssd_main --pipeline_config_path=training\ssd_main\ssd_mobilenet_v2_coco.config

### Describe the problem
I use api and ssd_mobilenet_v2_coco.config to train my own dataset.The training program is executed normally,and the checkpint can be generated normally, but the error is reported when the evaluation program is executed.

### Source code / logs
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x000001975F672510>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From F:\tensorflow\models\research\object_detection\core\preprocessor.py:1205: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From F:\tensorflow\models\research\object_detection\builders\dataset_builder.py:146: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
2018-11-01 22:09:20.675703: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-01 22:09:21.216536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:07:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2018-11-01 22:09:21.222423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-01 22:09:22.091657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-01 22:09:22.094662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-11-01 22:09:22.096270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-11-01 22:09:22.098032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8795 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:07:00.0, compute capability: 6.1)
2018-11-01 22:19:48.414617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-01 22:19:48.416729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-01 22:19:48.419920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-11-01 22:19:48.421712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-11-01 22:19:48.423399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8795 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:07:00.0, compute capability: 6.1)
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=7.91s).
Accumulating evaluation results...
DONE (t=0.36s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.061
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.163
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.021
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.083
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.056
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.107
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.154
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.154
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
Traceback (most recent call last):
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: pyfunc_0 returns 3 values, but expects to see 1 values.
         [[{{node map/while/PyFunc}} = PyFunc[Tin=[DT_UINT8, DT_FLOAT, DT_INT64, DT_FLOAT], Tout=[DT_UINT8], _class=["loc:@map/while/TensorArrayWrite/TensorArrayWriteV3"], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3, map/while/TensorArrayReadV3_1/_2353, map/while/TensorArrayReadV3_2, map/while/TensorArrayReadV3_3/_2355)]]
         [[{{node map/while/TensorArrayWrite/TensorArrayWriteV3/_2359}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1747_map/while/TensorArrayWrite/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/NextIteration_2/_2188)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models\research\object_detection\model_main.py", line 103, in <module>
    tf.app.run()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "models\research\object_detection\model_main.py", line 99, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_evaluate
    return executor.run()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1304, in run
    run_metadata=run_metadata))
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 581, in after_run
    if self._save(run_context.session, global_step):
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 606, in _save
    if l.after_save(session, step):
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 517, in after_save
    self._evaluate(global_step_value)  # updates self.eval_result
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 537, in _evaluate
    self._evaluator.evaluate_and_export())
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 912, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 476, in evaluate
    return _evaluate()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 469, in _evaluate
    output_dir=self.eval_dir(name))
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1528, in _evaluate_run
    config=self._session_config)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\evaluation.py", line 212, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 783, in __exit__
    self._close_internal(exception_type)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 816, in _close_internal
    h.end(self._coordinated_creator.tf_sess)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 941, in end
    self._final_ops, feed_dict=self._final_ops_feed_dict)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: pyfunc_0 returns 3 values, but expects to see 1 values.
         [[{{node map/while/PyFunc}} = PyFunc[Tin=[DT_UINT8, DT_FLOAT, DT_INT64, DT_FLOAT], Tout=[DT_UINT8], _class=["loc:@map/while/TensorArrayWrite/TensorArrayWriteV3"], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3, map/while/TensorArrayReadV3_1/_2353, map/while/TensorArrayReadV3_2, map/while/TensorArrayReadV3_3/_2355)]]
         [[{{node map/while/TensorArrayWrite/TensorArrayWriteV3/_2359}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1747_map/while/TensorArrayWrite/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/NextIteration_2/_2188)]]

Caused by op 'map/while/PyFunc', defined at:
  File "models\research\object_detection\model_main.py", line 103, in <module>
    tf.app.run()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "models\research\object_detection\model_main.py", line 99, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_evaluate
    return executor.run()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1304, in run
    run_metadata=run_metadata))
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 581, in after_run
    if self._save(run_context.session, global_step):
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 606, in _save
    if l.after_save(session, step):
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 517, in after_save
    self._evaluate(global_step_value)  # updates self.eval_result
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 537, in _evaluate
    self._evaluator.evaluate_and_export())
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\training.py", line 912, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 476, in evaluate
    return _evaluate()
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 462, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1422, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1458, in _call_model_fn_eval
    features, labels, model_fn_lib.ModeKeys.EVAL, config)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1169, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "F:\tensorflow\models\research\object_detection\model_lib.py", line 371, in model_fn
    use_normalized_coordinates=False))
  File "F:\tensorflow\models\research\object_detection\utils\visualization_utils.py", line 440, in draw_side_by_side_evaluation_image
    use_normalized_coordinates=use_normalized_coordinates)
  File "F:\tensorflow\models\research\object_detection\utils\visualization_utils.py", line 385, in draw_bounding_boxes_on_image_tensors
    images = tf.map_fn(draw_boxes, elems, dtype=tf.uint8, back_prop=False)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 460, in map_fn
    maximum_iterations=n)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3274, in while_loop
    return_same_structure)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2994, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2929, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3243, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 449, in compute
    packed_fn_values = fn(packed_values)
  File "F:\tensorflow\models\research\object_detection\utils\visualization_utils.py", line 382, in draw_boxes
    tf.uint8)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\script_ops.py", line 457, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\script_ops.py", line 281, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\ops\gen_script_ops.py", line 132, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "e:\Program Files\Anaconda3\envs\shengheng\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): pyfunc_0 returns 3 values, but expects to see 1 values.
         [[{{node map/while/PyFunc}} = PyFunc[Tin=[DT_UINT8, DT_FLOAT, DT_INT64, DT_FLOAT], Tout=[DT_UINT8], _class=["loc:@map/while/TensorArrayWrite/TensorArrayWriteV3"], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3, map/while/TensorArrayReadV3_1/_2353, map/while/TensorArrayReadV3_2, map/while/TensorArrayReadV3_3/_2355)]]
         [[{{node map/while/TensorArrayWrite/TensorArrayWriteV3/_2359}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1747_map/while/TensorArrayWrite/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/NextIteration_2/_2188)]]

**Comment by raaghavradhakrishnan** [comment]
Hi.. Did you get this resolved?? If yes, could you tell me how?

**Comment by fangkuann** [comment]
> Hi.. Did you get this resolved?? If yes, could you tell me how?

This is maybe caused by your return value of Py_Func. 
The returned value shoud be casted to Numpy array like 
```def your_py_func():
         xxxx
         return np.array(xxx, np.float32)```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
