### ISSUE TITLE
Can't run visualisation on deeplabv3_xception_ade20k_train

### ISSUE THREAD

**Issue by EgorAntonovich** [tensorflow/models#5662]
Hi, i want to run deeplab v3+ on visualization on deeplabv3_xception_ade20k_train model.
i  download model from http://download.tensorflow.org/models/deeplabv3_xception_ade20k_train_2018_05_29.tar.gz
 and want to run visualization. 
GPU  2 * NVIDIA GeForce GTX 1060 3GB
Ubuntu 16.04
CUDA 9.0
cudNN 7.0
I use this command to run visualization:
`LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/egor.antonovich/cuda9cudnn7/lib64" CUDA_VISIBLE_DEVICES=0,1 python deeplab/vis.py --logtostderr --vis_split="val" --model_variant="xception_65" --atrous_rates=6 --atrous_rates=12 --atrous_rates=18 --atrous_rates=16 --decode_output_stride=4 --vis_crop_size=513 --vis_crop_size=513 --dataset="ade20k" --colormap_type="pascal" --checkpoint_dir='/home/egor.antonovich/model_deeplab/ade20k/model.ckpt.data-00000-of-00001' --vis_logdir='/home/egor.antonovich/visualization/' --datset_dir='/home/egor.antonovich/datasets/big_data/img/'`

and have this error

`INFO:tensorflow:Visualizing on val set
WARNING:tensorflow:From /home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Performing single-scale test.
WARNING:tensorflow:From deeplab/vis.py:270: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
INFO:tensorflow:Starting visualization at 2018-11-01-14:52:10
INFO:tensorflow:Visualizing with model /home/egor.antonovich/model_deeplab/ade20k/model.ckpt.data-00000-of-00001
2018-11-01 17:52:10.829450: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-01 17:52:11.910597: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-01 17:52:11.911013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
totalMemory: 2.94GiB freeMemory: 2.88GiB
2018-11-01 17:52:11.980107: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-01 17:52:11.980507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 1 with properties: 
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:02:00.0
totalMemory: 2.94GiB freeMemory: 2.88GiB
2018-11-01 17:52:11.980555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0, 1
2018-11-01 17:52:12.339414: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-01 17:52:12.339444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 1 
2018-11-01 17:52:12.339449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N N 
2018-11-01 17:52:12.339452: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   N N 
2018-11-01 17:52:12.339672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2580 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-11-01 17:52:12.349176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 2580 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1060 3GB, pci bus id: 0000:02:00.0, compute capability: 6.1)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Restoring parameters from /home/egor.antonovich/model_deeplab/ade20k/model.ckpt.data-00000-of-00001
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, corrupted record at 0
	 [[{{node parallel_read/ReaderReadV2}} = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
2018-11-01 17:52:15.548646: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/egor.antonovich/model_deeplab/ade20k/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2018-11-01 17:52:15.548955: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/egor.antonovich/model_deeplab/ade20k/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2018-11-01 17:52:15.549000: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:172 : Data loss: Unable to open table file /home/egor.antonovich/model_deeplab/ade20k/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "deeplab/vis.py", line 319, in <module>
    tf.app.run()
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/vis.py", line 305, in main
    image_id_offset += FLAGS.vis_batch_size
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 1005, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1215, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
	 [[{{node parallel_read/ReaderReadV2}} = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
`

maybe anybody know how to solve it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by YknZhu** [comment]
could you replace the flag: 
`checkpoint_dir='/home/egor.antonovich/model_deeplab/ade20k/model.ckpt.data-00000-of-00001'`

to 

`checkpoint_dir='/home/egor.antonovich/model_deeplab/ade20k/model.ckpt'` ?

**Comment by EgorAntonovich** [comment]
@YknZhu yes, but in archive there is no model with the given extension. In this archive i have 3 files:
frozen_inference_graph.pb   model.ckpt.data-00000-of-00001   model.ckpt.index

**Comment by YknZhu** [comment]
Well model.ckpt will direct to the corresponding .index and .data file.

see: `https://stackoverflow.com/questions/41265035/tensorflow-why-there-are-3-files-after-saving-the-model`

Meta file doesn't matter here and we don't include them in the archive.

**Comment by EgorAntonovich** [comment]
Okey, i use model.ckpt and have this traceback
`INFO:tensorflow:Restoring parameters from /home/egor.antonovich/model_deeplab/ade20k/model.ckpt
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, corrupted record at 0
	 [[{{node parallel_read/ReaderReadV2}} = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
2018-11-05 21:05:25.081241: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key aspp4_depthwise/BatchNorm/beta not found in checkpoint
Traceback (most recent call last):
  File "deeplab/vis.py", line 319, in <module>
    tf.app.run()
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/vis.py", line 305, in main
    image_id_offset += FLAGS.vis_batch_size
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 1005, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1215, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/egor.antonovich/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
	 [[{{node parallel_read/ReaderReadV2}} = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
`

**Comment by jillelajitta** [comment]
@YknZhu 
Sorry to hijack this post
Could you please tell me how many steps are required to train COCO dataset on SSD Inception V2 model? I have checked tensorflow object detection api paper, it is mentioned LR rate was decreased by 0.95 for every 800k steps, but what is the total number of steps required to train COCO dataset.
Please help me.
Thank you.

**Comment by YknZhu** [comment]
Opened an new issue to track this.
