### ISSUE TITLE
[Object Detection] TF trains 1 epoch and evaluates indefinitely, even when a limit is set

### ISSUE THREAD

**Issue by moderato** [tensorflow/models#5668]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.11
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.2/cudnn 7.3.0
- **GPU model and memory**: GTX 1050 Ti 4G
- **Exact command to reproduce**:
```bash
PIPELINE_CONFIG_PATH=/home/zhongyilin/Documents/models/research/object_detection/trained_models/bdd100k_ssdlite_mobilenet_v2/ssdlite_mobilenet_v2_bdd100k.config
MODEL_DIR=/home/zhongyilin/Documents/models/research/object_detection/trained_models/bdd100k_ssdlite_mobilenet_v2/train_logs
NUM_TRAIN_STEPS=200000
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
python object_detection/model_main.py \
	--pipeline_config_path=${PIPELINE_CONFIG_PATH} \
	--model_dir=${MODEL_DIR} --num_train_steps=${NUM_TRAIN_STEPS} \
	--sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
	--alsologtostderr
```

Config file:
```
# SSDLite with Mobilenet v2 configuration for BDD100K Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
# should be configured.

model {
  ssd {
    num_classes: 10
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 534
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 3
        use_depthwise: true
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v2'
      min_depth: 16
      depth_multiplier: 1.0
      use_depthwise: true
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 3
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 8
  batch_queue_capacity: 2
  prefetch_queue_capacity: 2
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  # fine_tune_checkpoint: "/home/zhongyilin/Documents/models/research/object_detection/trained_models/bdd100k_ssdlite_mobilenet_v2/train_logs/model.ckpt"
  # fine_tune_checkpoint_type: "detection"
  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
  # never decay). Remove the below line to train indefinitely.
  num_steps: 200000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "/home/zhongyilin/Documents/data/BDD/tfrecord/100k/train/output_train100k_000000.tfrecord"
  }
  label_map_path: "object_detection/data/bdd100k_label_map.pbtxt"
}

eval_config: {
  num_examples: 10000
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 1
  eval_interval_secs: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/home/zhongyilin/Documents/data/BDD/tfrecord/100k/val/output_val100k_000000.tfrecord"
  }
  label_map_path: "object_detection/data/bdd100k_label_map.pbtxt"
  shuffle: false
  num_readers: 1
}
```

### Describe the problem
As the title said. From Tensorboard it looks like the training only runs for 1 epoch and it keeps running eval all the time. The training loss doesn't get updated, while the eval loss updates for a bunch of data points. I have reset the parameters in "eval_config" with different values but it doesn't work.

Plus, it looks like the "fine_tune_checkpoint" in "train_config" doesn't work when it's set to PATH/model.ckpt. It shows an error of 
```
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/zhongyilin/Documents/models/research/object_detection/trained_models/bdd100k_ssdlite_mobilenet_v2/train_logs/model.ckpt
```
### Source code / logs
```
zhongyilin@zhongyilin-ECE:~/Documents/models/research/scripts$ ./bdd100k_mobilenet_v2_ssdlite.sh 
/home/zhongyilin/Documents/models/research/object_detection/utils/visualization_utils.py:27: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
W1101 21:06:28.286998 139715550816000 tf_logging.py:125] Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
W1101 21:06:28.287134 139715550816000 tf_logging.py:125] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f1181c42378>) includes params argument, but params are not passed to Estimator.
W1101 21:06:28.287409 139715550816000 tf_logging.py:125] Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f1181c42378>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W1101 21:06:28.308489 139715550816000 tf_logging.py:125] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /home/zhongyilin/Documents/models/research/object_detection/core/preprocessor.py:1207: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
W1101 21:06:28.501330 139715550816000 tf_logging.py:125] From /home/zhongyilin/Documents/models/research/object_detection/core/preprocessor.py:1207: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From /home/zhongyilin/Documents/models/research/object_detection/builders/dataset_builder.py:148: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
W1101 21:06:29.325152 139715550816000 tf_logging.py:125] From /home/zhongyilin/Documents/models/research/object_detection/builders/dataset_builder.py:148: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
2018-11-01 21:06:42.719184: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-01 21:06:42.787760: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-01 21:06:42.788059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.468
pciBusID: 0000:02:00.0
totalMemory: 3.94GiB freeMemory: 3.60GiB
2018-11-01 21:06:42.788071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-01 21:06:42.928717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-01 21:06:42.928742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-01 21:06:42.928748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-01 21:06:42.928843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3316 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2018-11-01 21:06:58.060117: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.55GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-01 21:06:58.396333: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.49GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-01 21:06:58.399570: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.51GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-01 21:06:58.574441: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.88GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-01 21:06:59.115525: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-01 21:16:58.264482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-01 21:16:58.264513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-01 21:16:58.264518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-01 21:16:58.264521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-01 21:16:58.264591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3316 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=96.65s).
Accumulating evaluation results...
DONE (t=8.93s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
2018-11-01 21:33:05.603130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-01 21:33:05.603162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-01 21:33:05.603166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-01 21:33:05.603169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-01 21:33:05.603231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3316 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=83.82s).
Accumulating evaluation results...
DONE (t=8.13s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
2018-11-01 21:49:09.087981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-11-01 21:49:09.088014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-01 21:49:09.088019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-11-01 21:49:09.088022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-11-01 21:49:09.088090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3316 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
^CTraceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1304, in run
    run_metadata=run_metadata))
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 581, in after_run
    if self._save(run_context.session, global_step):
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 606, in _save
    if l.after_save(session, step):
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 517, in after_save
    self._evaluate(global_step_value)  # updates self.eval_result
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 537, in _evaluate
    self._evaluator.evaluate_and_export())
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 912, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 476, in evaluate
    return _evaluate()
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 469, in _evaluate
    output_dir=self.eval_dir(name))
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1528, in _evaluate_run
    config=self._session_config)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/evaluation.py", line 212, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/zhongyilin/miniconda3/envs/neon/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
KeyboardInterrupt
```
Above shows the log produced by a normal run using the script and config file provided. It's been Ctrl+C at the end.

Anyone has an idea how to solve it? Thanks in advance!

**Comment by dcyoung** [comment]
I have experienced similar issues (#5057) and would love to get some feedback here as well.

**Comment by moderato** [comment]
Hello, are there any current updates on this issue? Thanks!

**Comment by Rosywolf** [comment]
I have experienced similar issues......How to fix it ?

**Comment by moderato** [comment]
@dcyoung @Rosywolf I used the train.py code under the legacy folder instead and it works well. If you really want a run this can be a workaround, but I still have no idea how to run with model_main.py.

**Comment by dawnCoder26** [comment]
> @dcyoung @Rosywolf I used the train.py code under the legacy folder instead and it works well. If you really want a run this can be a workaround, but I still have no idea how to run with model_main.py.

How did you do it with train.py?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
