### ISSUE TITLE
tensorflow.python.framework.errors.DataLossError while training with im2txt

### ISSUE THREAD

**Issue by TRGNN** [tensorflow/models#571]
## Please let us know which model this issue is about (specify the top-level directory)

Hello,

I'm on Ubuntu 16.04 with Cuda 8.0 and CudNN 5.1. I've installed Tensordlow from sources (0.11). My Tensorflow installation pass all the tests and looks good but I randomly get this error when I try to train a model while following the im2txt readme.

(Note that I can continue the training while relauching the script but It halt every five minutes.)

> INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors.DataLossError'>, truncated record at 173870435
> 	 [[Node: ReaderRead = ReaderRead[_class=["loc:@TFRecordReader", "loc:@filename_queue"], _device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReader, filename_queue)]]
> 
> Caused by op u'ReaderRead', defined at:
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
>     model.build()
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 352, in build
>     self.build_inputs()
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 153, in build_inputs
>     num_reader_threads=self.config.num_input_reader_threads)
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/inputs.py", line 115, in prefetch_input_data
>     _, value = reader.read(filename_queue)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 277, in read
>     return gen_io_ops._reader_read(self._reader_ref, queue_ref, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 211, in _reader_read
>     queue_handle=queue_handle, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 748, in apply_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2403, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1305, in __init__
>     self._traceback = _extract_stack()
> 
> DataLossError (see above for traceback): truncated record at 173870435
> 	 [[Node: ReaderRead = ReaderRead[_class=["loc:@TFRecordReader", "loc:@filename_queue"], _device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReader, filename_queue)]]
> 
> INFO:tensorflow:global step 3016: loss = 3.0129 (0.43 sec/step)
> INFO:tensorflow:Finished training! Saving model to disk.
> WARNING:tensorflow:*******************************************************
> WARNING:tensorflow:TensorFlow's V1 checkpoint format is deprecated; V2 will become the default shortly after 10/31/2016.
> WARNING:tensorflow:Consider switching to the more efficient V2 format now:
> WARNING:tensorflow:   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`
> WARNING:tensorflow:to prevent breakage.
> WARNING:tensorflow:*******************************************************
> Traceback (most recent call last):
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 110, in main
>     saver=saver)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 785, in train
>     raise
>   File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
>     self.gen.next()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 974, in managed_session
>     self.stop(close_summary_writer=close_summary_writer)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 802, in stop
>     stop_grace_period_secs=self._stop_grace_secs)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 386, in join
>     six.reraise(*self._exc_info_to_raise)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner.py", line 225, in _run
>     sess.run(enqueue_op)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
>     feed_dict_string, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
>     target_list, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors.DataLossError: truncated record at 173870435
> 	 [[Node: ReaderRead = ReaderRead[_class=["loc:@TFRecordReader", "loc:@filename_queue"], _device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReader, filename_queue)]]
> 
> Caused by op u'ReaderRead', defined at:
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
>     model.build()
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 352, in build
>     self.build_inputs()
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 153, in build_inputs
>     num_reader_threads=self.config.num_input_reader_threads)
>   File "/home/workshop/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/inputs.py", line 115, in prefetch_input_data
>     _, value = reader.read(filename_queue)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 277, in read
>     return gen_io_ops._reader_read(self._reader_ref, queue_ref, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 211, in _reader_read
>     queue_handle=queue_handle, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 748, in apply_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2403, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1305, in __init__
>     self._traceback = _extract_stack()
> 
> DataLossError (see above for traceback): truncated record at 173870435
> 	 [[Node: ReaderRead = ReaderRead[_class=["loc:@TFRecordReader", "loc:@filename_queue"], _device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReader, filename_queue)]]

Any ideas for solving this ?

Thanks in advance.

**Comment by asimshankar** [comment]
@TRGNN : Based on the error messages, it seems like the pre-processed data is corrupt. Is it possible that the preprocessing script failed or files got truncated/corrupted afterwards? If so, then you might want to regenerate the data by rerunning the command at [download_and_preprocess_mscoco.sh:83](https://github.com/tensorflow/models/blob/master/im2txt/im2txt/data/download_and_preprocess_mscoco.sh#L83)

**Comment by TRGNN** [comment]
Thank you !!!

Problem solved.

**Comment by TRGNN** [comment]
Thank you !!

Problem solved.

**Comment by bandarikanth** [comment]
i tried udc_train.py , I got below Errors

File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
# **tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_3_read_batch_features_train/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)**
	 [[Node: read_batch_features_train/fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](read_batch_features_train/fifo_queue)]]

Caused by op 'read_batch_features_train/fifo_queue_Dequeue', defined at:
  File "/home/mcis-lap-49/work/PycharmProject/cahtbot/chatbot-retrieval-master/udc_train.py", line 66, in <module>
    tf.app.run()
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/mcis-lap-49/work/PycharmProject/cahtbot/chatbot-retrieval-master/udc_train.py", line 63, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 953, in _train_model
    features, labels = input_fn()
  File "/home/mcis-lap-49/work/PycharmProject/cahtbot/chatbot-retrieval-master/udc_inputs.py", line 46, in input_fn
    name="read_batch_features_{}".format(mode))
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 778, in read_batch_features
    name=name)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 512, in read_keyed_batch_features
    name=scope)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 683, in queue_parsed_features
    dequeued_tensors = input_queue.dequeue()
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 415, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1065, in _queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()


 help me in this.

**Comment by bandarikanth** [comment]
when i tried udc_train.py I got below error:

File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 888, in close
    ignore_live_threads=True)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/mcis-lap-49/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
	 [[Node: read_batch_features_train/read/ReaderReadUpToV2 = ReaderReadUpToV2[_device="/job:localhost/replica:0/task:0/cpu:0"](read_batch_features_train/read/TFRecordReaderV2, read_batch_features_train/file_name_queue, read_batch_features_train/read/ReaderReadUpToV2/num_records)]]
help me in this.

**Comment by junfengluo** [comment]
Hi, I have also met this problem, how you solved it, can you tell me ?

**Comment by bandarikanth** [comment]
We didn't solved yet

**Comment by MloveDaxiong** [comment]
Hi, I can successfully train, but it shows DataLossError at global step 3862. And I have checked that the preprocessing script run OK. Can you give me some advice @asimshankar . And my devices is 1080*2.

**Comment by junfengluo** [comment]
I have also met this problem before, it is main due to the incomplete data. You should download the data again because some tfrecords are 0kb.

发自我的 iPhone

**Comment by MloveDaxiong** [comment]
@junfengluo I re-download several times, but it still shows DataLossError. I don't know how to guarantee all data is complete......

**Comment by junfengluo** [comment]
There is a file named *.json in the data folder, if the file is empty, it means all data are downloaded in right way.

发自我的 iPhone

**Comment by MloveDaxiong** [comment]
@junfengluo There is no such file in data folder, but it still shows DataLossError.  And it can re-run well with the loss it had pretrained before, if i do not delete model folder.

**Comment by KDcx35** [comment]
> @TRGNN : Based on the error messages, it seems like the pre-processed data is corrupt. Is it possible that the preprocessing script failed or files got truncated/corrupted afterwards? If so, then you might want to regenerate the data by rerunning the command at [download_and_preprocess_mscoco.sh:83](https://github.com/tensorflow/models/blob/master/im2txt/im2txt/data/download_and_preprocess_mscoco.sh#L83)

i have met a similar error

> Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: truncated record at 136219998
	 [[{{node IteratorGetNext}}]]
	 [[map/while/TensorArrayReadV3_1/_4059]]
  (1) Data loss: truncated record at 136219998
	 [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models/research/object_detection/model_main.py", line 114, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "models/research/object_detection/model_main.py", line 110, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: truncated record at 136219998
	 [[node IteratorGetNext (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[map/while/TensorArrayReadV3_1/_4059]]
  (1) Data loss: truncated record at 136219998
	 [[node IteratorGetNext (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "models/research/object_detection/model_main.py", line 114, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "models/research/object_detection/model_main.py", line 110, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/estimator.py", line 1025, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/tensorflow-1.15.2/python3.6/tensorflow_estimator/python/estimator/util.py", line 65, in parse_input_fn_result
    result = iterator.get_next()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

> 
Do you know how solve this?Thank you!
