### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by tahuy** [tensorflow/models#5730]
Hi,
I have built this repo [https://github.com/thatbrguy/Pedestrian-Detection](url) with tensorflow-gpu on colab. This repo from tensorflow/object-detection and I face error:

Traceback (most recent call last):
  File "create_tf_record.py", line 178, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "create_tf_record.py", line 173, in main
    image_dir, train_examples)
  File "create_tf_record.py", line 145, in create_tf_record
    tf_example = dict_to_tf_example(data, label_map_dict, image_dir)
  File "create_tf_record.py", line 60, in dict_to_tf_example
    img_path = os.path.join(image_subdirectory, data['filename'])
TypeError: string indices must be integers

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pkulzc** [comment]
I can't find anything useful from this limited messages. You can simple print your iamge_subdir and data[filename] to see what is wrong.

**Comment by pkulzc** [comment]
Closing this since no activity. Feel free to re-open if you have any issue with object detection.
