### ISSUE TITLE
Unable to train model using train.py

### ISSUE THREAD

**Issue by Sajjadmanal** [tensorflow/models#5753]
System information
What is the top-level directory of the model you are using: models\research\object_detection
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Little change
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
TensorFlow installed from (source or binary): Source
TensorFlow version (use command below): 1.12.0
Bazel version (if compiling from source):
CUDA/cuDNN version: NA
GPU model and memory: CPU 16 GB
Exact command to reproduce: `python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config`

faster_rcnn_inception_v2_pets.config file:

```
# Faster R-CNN with Inception v2, configured for Oxford-IIIT Pets Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
# should be configured.

model {
  faster_rcnn {
    num_classes: 6
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 600
        max_dimension: 1024
      }
    }
    feature_extractor {
      type: 'faster_rcnn_inception_v2'
      first_stage_features_stride: 16
    }
    first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [0.25, 0.5, 1.0, 2.0]
        aspect_ratios: [0.5, 1.0, 2.0]
        height_stride: 16
        width_stride: 16
      }
    }
    first_stage_box_predictor_conv_hyperparams {
      op: CONV
      regularizer {
        l2_regularizer {
          weight: 0.0
        }
      }
      initializer {
        truncated_normal_initializer {
          stddev: 0.01
        }
      }
    }
    first_stage_nms_score_threshold: 0.0
    first_stage_nms_iou_threshold: 0.7
    first_stage_max_proposals: 300
    first_stage_localization_loss_weight: 2.0
    first_stage_objectness_loss_weight: 1.0
    initial_crop_size: 14
    maxpool_kernel_size: 2
    maxpool_stride: 2
    second_stage_box_predictor {
      mask_rcnn_box_predictor {
        use_dropout: false
        dropout_keep_probability: 1.0
        fc_hyperparams {
          op: FC
          regularizer {
            l2_regularizer {
              weight: 0.0
            }
          }
          initializer {
            variance_scaling_initializer {
              factor: 1.0
              uniform: true
              mode: FAN_AVG
            }
          }
        }
      }
    }
    second_stage_post_processing {
      batch_non_max_suppression {
        score_threshold: 0.0
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 300
      }
      score_converter: SOFTMAX
    }
    second_stage_localization_loss_weight: 2.0
    second_stage_classification_loss_weight: 1.0
  }
}

train_config: {
  batch_size: 1
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        manual_step_learning_rate {
          initial_learning_rate: 0.0002
          schedule {
            step: 0
            learning_rate: .0002
          }
          schedule {
            step: 900000
            learning_rate: .00002
          }
          schedule {
            step: 1200000
            learning_rate: .000002
          }
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  gradient_clipping_by_norm: 10.0
  fine_tune_checkpoint: "C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt"
  from_detection_checkpoint: true
  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
  # never decay). Remove the below line to train indefinitely.
  num_steps: 200000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
}


train_input_reader: {
  tf_record_input_reader {
    input_path: "C:/tensorflow1/models/research/object_detection/train.record"
  }
  label_map_path: "C:/tensorflow1/models/research/object_detection/training/labelmap.pbtxt"
}

eval_config: {
  num_examples: 67
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "C:/tensorflow1/models/research/object_detection/test.record"
  }
  label_map_path: "C:/tensorflow1/models/research/object_detection/training/labelmap.pbtxt"
  shuffle: false
  num_readers: 1
}
````

Error:
````
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\sm50014\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\sm50014\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\sm50014\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 248, in train
    detection_model = create_model_fn()
  File "C:\Users\sm50014\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 121, in build
    add_summaries)
  File "C:\Users\sm50014\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 430, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "C:\Users\sm50014\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\box_predictor_builder.py", line 617, in build
    config_box_predictor.convolve_then_upsample_masks))
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'convolve_then_upsample_masks'
````

**Comment by Sajjadmanal** [comment]
Even if I use:` python model_main.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config`, I get the same error:

`Traceback (most recent call last):
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_evaluate
    return executor.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1234, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1075, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1162, in _call_input_fn
    return input_fn(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\inputs.py", line 479, in _train_input_fn
    batch_size=params['batch_size'] if params else train_config.batch_size)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py", line 145, in build
    num_parallel_calls=num_parallel_calls)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1040, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2649, in __init__
    use_inter_op_parallelism)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2611, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py", line 129, in process_fn
    processed_tensors = transform_input_data_fn(processed_tensors)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\inputs.py", line 456, in transform_and_pad_input_data_fn
    model = model_builder.build(model_config, is_training=True)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 121, in build
    add_summaries)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 430, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\box_predictor_builder.py", line 617, in build
    config_box_predictor.convolve_then_upsample_masks))
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'convolve_then_upsample_masks'`

**Comment by tmoeller4** [comment]
With another model (mask_rcnn) and another setup, I'm running into the same problem.
This problem is solved (for me), when I checkout commit 63ecef1.

### System Information:
What is the top-level directory of the model you are using: models\research\object_detection
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No change of any code but using my own dataset
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.12.0
Bazel version (if compiling from source):
CUDA/cuDNN version: CUDA Version 9.0.176
GPU model and memory: CPU Tesla P100 with 16GB
Exact command to reproduce: python object_detection/model_main.py --pipeline_config_path='pipeline.config' --model_dir='/vol/data/models/mask_rcnn_resnet50_atrous_coco_2018_01_28' --num_train_steps=50000 --sample_1_of_n_eval_examples=1 --alsologtostderr

The file pipeline.config is basically the same as the file as /tensorflow/models/research/object_detection/samples/configs/mask_rcnn_resnet50_atrous_coco.config. The only thing, I've changed is the number of classes and the path to data

If I can provide any data that helps, please let me know

**Comment by amgugu111** [comment]
Just change the path from          python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssdlite_mobilenet_v2_coco.config    to 
   python train.py --logtostderr --train_dir --train_dir=train/ --pipeline_config_path=training/ssdlite_mobilenet_v2_coco.config

You just need to add the train_dir to it.

**Comment by shubhjha04578** [comment]
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\shubham jha\Anaconda3\miniconda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\shubham jha\Anaconda3\miniconda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflowf\model\research\object_detection\legacy\trainer.py", line 280, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\tensorflowf\model\research\object_detection\legacy\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\tensorflowf\model\research\object_detection\builders\dataset_builder.py", line 130, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "C:\tensorflowf\model\research\object_detection\data_decoders\tf_example_decoder.py", line 314, in __init__
    default_value=''),
  File "C:\tensorflowf\model\research\object_detection\data_decoders\tf_example_decoder.py", line 59, in __init__
    label_map_proto_file, use_display_name=False)
  File "C:\tensorflowf\model\research\object_detection\utils\label_map_util.py", line 164, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "C:\tensorflowf\model\research\object_detection\utils\label_map_util.py", line 133, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\shubham jha\Anaconda3\miniconda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\shubham jha\Anaconda3\miniconda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\shubham jha\Anaconda3\miniconda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: ~/tensorflowf/model/research/object_detection/training/labelmap.pbtxt : The system cannot find the path specified.
; No such process


command-python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

-i used this command on anaconda prompt and getting above errors please help me

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ChandaniKeshari** [comment]
'Tensorflow'.format(feature_extractor_type))
ValueError: faster_rcnn_inception_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow


I am facing the above error while training.

**Comment by Dipesh1333** [comment]
@ChandaniKeshari did you find a solution? I'm too having the same  problem.

**Comment by joselitopradomarques** [comment]
I'm also

> 'Tensorflow'.format(feature_extractor_type))
> ValueError: faster_rcnn_inception_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow
> 
> I am facing the above error while training.

I'm also facing the same error

**Comment by Homayra22** [comment]
Hi, I am having the error

(object) C:\Users\homay\OneDrive\Documents\Object API\models\research\object_detection>python train.py --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config --logtostderr
Traceback (most recent call last):
  File "C:\Users\homay\OneDrive\Documents\Object API\models\research\object_detection\train.py", line 48, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
