### ISSUE TITLE
IndexError: list index out of range faster_rcnn_inception_v2_coco_2018_01_28

### ISSUE THREAD

**Issue by Spatialghost** [tensorflow/models#5787]
Hi, i try to train object detection model with faster_rcnn_inception_v2_coco_2018_01_28 use for custom dataset, when i run the training in Windows 10 with comand python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_coco.config i have next error:
WARNING:tensorflow:From C:\tensorflow\lib\site-packages\tensorflow\python\platform\app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1120 12:40:18.033661  7896 tf_logging.py:118] From C:\tensorflow\lib\site-packages\tensorflow\python\platform\app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From C:\tensorflow\models\research\object_detection\legacy\trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1120 12:40:18.079681  7896 tf_logging.py:118] From C:\tensorflow\models\research\object_detection\legacy\trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow\models\research\object_detection\legacy\trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\tensorflow\models\research\object_detection\legacy\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\tensorflow\models\research\object_detection\builders\dataset_builder.py", line 123, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "C:\tensorflow\models\research\object_detection\data_decoders\tf_example_decoder.py", line 297, in __init__
    default_value=''),
  File "C:\tensorflow\models\research\object_detection\data_decoders\tf_example_decoder.py", line 59, in __init__
    label_map_proto_file, use_display_name=False)
  File "C:\tensorflow\models\research\object_detection\utils\label_map_util.py", line 164, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "C:\tensorflow\models\research\object_detection\utils\label_map_util.py", line 136, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 888, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 1251, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 1266, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_format.py", line 1291, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_encoding.py", line 103, in CUnescape
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
  File "C:\tensorflow\lib\site-packages\google\protobuf\text_encoding.py", line 103, in <genexpr>
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
IndexError: list index out of range

i use tensorflow 1.12 and protobuf 3.6.1.
Please help to solve this problem.
Great Thanks!

**Comment by yingjieyao** [comment]
I have the same issue when I have **Chinese characters** in **label_map.pbtxt**.

**Comment by Spatialghost** [comment]
Thank you for answers.
I solved this problem, when i created xml- annotations in english languale, convertes records with classes in english language and used English language names for labelmap.pbtx

**Comment by ghity** [comment]
@Spatialghost could you tell me what did you do for this problem in detail ?

thank you ！

**Comment by yhliang2018** [comment]
Close this one for now due to the lack of activity. Feel free to reopen it if necessary.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
