### ISSUE TITLE
ssd_mobilenet_v1_quantized_300x300_coco14_sync unavailable fine_tune_checkpoint

### ISSUE THREAD

**Issue by baihualinxin** [tensorflow/models#5791]
------------------------

### System information
- **What is the top-level directory of the model you are using**:models-master\research\object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 16.04 windwos 10
- **TensorFlow installed from (source or binary)**:pip
- **TensorFlow version (use command below)**:1.10.0
- **Bazel version (if compiling from source)**:0.17.01
- **CUDA/cuDNN version**:cuda 9 cudnn 8
- **GPU model and memory**:GTX 1080Ti
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:
b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0

### Describe the problem
```
# SSD with Mobilenet v1 with quantized training.
# Trained on COCO, initialized from Imagenet classification checkpoint

# Achieves 18.2 mAP on coco14 minival dataset.

# This config is TPU compatible

model {
  ssd {
    inplace_batchnorm_update: true
    freeze_batchnorm: false
    num_classes: 1
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
        use_matmul_gather: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    encode_background_as_zeros: true
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        class_prediction_bias_init: -4.6
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            random_normal_initializer {
              stddev: 0.01
              mean: 0.0
            }
          }
          batch_norm {
            scale: true,
            center: true,
            decay: 0.97,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v1'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          random_normal_initializer {
            stddev: 0.01
            mean: 0.0
          }
        }
        batch_norm {
          scale: true,
          center: true,
          decay: 0.97,
          epsilon: 0.001,
        }
      }
      override_base_feature_extractor_hyperparams: true
    }
    loss {
      classification_loss {
        weighted_sigmoid_focal {
          alpha: 0.75,
          gamma: 2.0
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    normalize_loc_loss_by_codesize: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  fine_tune_checkpoint: "G:/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18/model.ckpt"
  batch_size: 16
  sync_replicas: true
  startup_delay_steps: 0
  replicas_to_aggregate: 8
  num_steps: 500000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  #data_augmentation_options {
    #ssd_random_crop {
    #}
  #}
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: .2
          total_steps: 500000
          warmup_learning_rate: 0.06
          warmup_steps: 2000
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
}
train_input_reader: {
  tf_record_input_reader {
    input_path: "G:/train/data_object_image_2/training/image_2/train.record"
  }
  label_map_path: "G:/kitti_label_map.pbtxt"
}

eval_config: {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  num_examples: 93
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "G:/val/data_object_image_2/training/image_2/train.record"
  }
  label_map_path: "G:/kitti_label_map.pbtxt"
  shuffle: false
  num_readers: 1
}

graph_rewriter {
  quantization {
    delay: 300
    activation_bits: 8
    weight_bits: 8
  }
}


```

### Report errors

```
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/max/biased] is not available in checkpoint
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/max/local_step] is not available in checkpoint
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/min/biased] is not available in checkpoint
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/min/local_step] is not available in checkpoint
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/max] is not available in checkpoint
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/act_quant/min] is not available in checkpoint
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/weights_quant/max] is not available in checkpoint
W1121 10:59:54.874578 32804 variables_helper.py:144] Variable [MobilenetV1/MobilenetV1/Conv2d_9_pointwise/weights_quant/min] is not available in checkpoint
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "D:\models-master\research\object_detection\legacy\trainer.py", line 397, in train
    init_saver = tf.train.Saver(available_var_map)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1281, in __init__
    self.build()
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1318, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

```

### Where does config need to be set up?

**Comment by k-w-w** [comment]
What command did you use to run the model?

**Comment by JoyLuo** [comment]
i have same error when use python legacy/train.py

**Comment by baihualinxin** [comment]
@k-w-w   
 Run the model command
 python legacy/train.py \
        --logtostderr \
        --train_dir=path/to/train_dir \
        --pipeline_config_path=pipeline_config.pbtxt

**Comment by baihualinxin** [comment]
@JoyLuo 
Don't take quantized is ssd_mobilenet_v1 No problem

**Comment by baihualinxin** [comment]
@k-w-w 
If you cannot use this feature, update the config file
https://github.com/tensorflow/models/pull/5816

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
