### ISSUE TITLE
Error when training "mask_rcnn_resnet101_pets" with train.py

### ISSUE THREAD

**Issue by tree89** [tensorflow/models#5802]
System information
What is the top-level directory of the model you are using: /home/user
Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.10.1
Bazel version (if compiling from source): I don't use it
CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
GPU model and memory: Geforce GTX 1070
Exact command to reproduce: Exact command to reproduce: 
python3 train.py --logtostderr --train_dir=data3 --pipeline_config_path=data3/mask_rcnn_resnet101_pets.config

#############################################################################
### I just tried to train "mask_rcnn_resnet101_pets" with train.py
I made my training dataset(for test training to check that I can train it)
My test set is made by using "create_pet_tf_record.py" with that dataset image

http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz
http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz

I erased everything except the "Bengal" from image, annotation, all txt files.
(I just wanna check how to make own dataset and how to train it)

### I changed "create_pet_tf_record.py" little bit like under.
I added this code 

label_map_dict['Bengal'] = 1

on line# 159, cuz this code on line# 263

label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)

make only output empty dictionary {}

### so, I got a dataset serise for checking 

pets_fullbody_with_masks_train.record-00000-of-00010
~
pets_fullbody_with_masks_train.record-00009-of-00010

and 
pets_fullbody_with_masks_val.record-00000-of-00010
~
pets_fullbody_with_masks_val.record-00009-of-00010

### and I also changed mask_rcnn_resnet101_pets.config file and pet_label_map.pbtxt file like this

train_input_reader: {
  tf_record_input_reader {
    input_path: ###"data3/pet_fullbody_with_masks_train.record-?????-of-00010"
  }
  label_map_path: ###"data3/pet_label_map.pbtxt"
  load_instance_masks: true
  mask_type: PNG_MASKS
}

eval_config: {
  num_examples: 50
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: ###"data3/pet_fullbody_with_masks_val.record-?????-of-00010"
  }
  label_map_path: ###"data3/pet_label_map.pbtxt"
  load_instance_masks: true
  mask_type: PNG_MASKS
  shuffle: false
  num_readers: 1
}

and

item {
  id: 1
  name: 'Bengal'
}

### I typed 
python3 train.py --logtostderr --train_dir=data3 --pipeline_config_path=data3/mask_rcnn_resnet101_pets.config
on my terminal

### I got error message
/home/cb/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From /home/cb/Work/models/research/object_detection/legacy/trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 0 to match input file shards.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/cb/Work/models/research/object_detection/legacy/trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/cb/Work/models/research/object_detection/legacy/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/home/cb/Work/models/research/object_detection/builders/dataset_builder.py", line 134, in build
    config.input_path[:], input_reader_config)
  File "/home/cb/Work/models/research/object_detection/builders/dataset_builder.py", line 80, in read_dataset
    sloppy=config.shuffle))
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1109, in apply
    dataset = transformation_func(self)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py", line 87, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 128, in __init__
    cycle_length, block_length)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2294, in __init__
    super(InterleaveDataset, self).__init__(input_dataset, map_func)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2257, in __init__
    experimental_nested_dataset_support=True)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1454, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 481, in add_to_graph
    self._create_definition_if_needed()
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 337, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 346, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 863, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1392, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 194, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 998, in convert_to_tensor
    as_ref=False)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 931, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

### [Question]

How can I solve this problem? I don't know what is my mistake.
I have totally no idea, please help.

Any help be appriciated
Thanks

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
