### ISSUE TITLE
Mask RCNN with tensorflow API: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

### ISSUE THREAD

**Issue by muralisb** [tensorflow/models#5831]
### System information
- **What is the top-level directory of the model you are using**:
My Repo is in E: drive and I have created a folder with a path "E:\Object_Detection\Masked-RCNN\Custom-Mask-RCNN-using-Tensorfow-Object-detection-API-master"

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I am trying to replicate the work done by vijendra and this is the lnk to his repo
https://github.com/vijendra1125/Custom-Mask-RCNN-using-Tensorfow-Object-detection-API

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
I am working on windows 10 platform
- **TensorFlow installed from (source or binary)**:
tensorflow was installed using pip install command (tensorflow-1.9.0-cp36-cp36m-win_amd64.whl)

- **TensorFlow version (use command below)**: 'v1.9.0-0-g25c197e023' 1.9.0

- **GPU model and memory**:
my laptop has 16 gb RAM and 1 TB memory and no GPU

- **Exact command to reproduce**:
(base) C:\Users\nVIALP2\Documents\Python_Scripts\Tensorflow\models\research>python object_detection/legacy/train.py --train_dir=E:\Object_Detection\Masked-RCNN\Custom-Mask-RCNN-using-Tensorfow-Object-detection-API-master\CP --pipeline_config_path=E:\Object_Detection\Masked-RCNN\Custom-Mask-RCNN-using-Tensorfow-Object-detection-API-master\mask_rcnn_inception_v2_coco.config

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

### Describe the problem
I am trying to build a Custom Mask RCNN using Tensorfow Object detection API that uses used pre-trained mask RCNN which is trained with inception V2 as feature extracter. I have used pixel annotation tool for creaking mask of hand images and was trying to train the model using my own dataset.

### Source code / logs

WARNING:tensorflow:From C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1128 16:57:42.430089 15960 tf_logging.py:125] From C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From C:\Users\nVIALP2\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1128 16:57:42.542089 15960 tf_logging.py:125] From C:\Users\nVIALP2\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 0 to match input file shards.
W1128 16:57:42.570088 15960 tf_logging.py:125] num_readers has been reduced to 0 to match input file shards.
Traceback (most recent call last):
  File "object_detection/legacy/train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "object_detection/legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "object_detection/legacy/train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py", line 134, in build
    config.input_path[:], input_reader_config)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py", line 80, in read_dataset
    sloppy=config.shuffle))
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1002, in apply
    dataset = transformation_func(self)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\contrib\data\python\ops\interleave_ops.py", line 88, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\data\ops\readers.py", line 130, in __init__
    cycle_length, block_length)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1988, in __init__
    super(InterleaveDataset, self).__init__(input_dataset, map_func)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1957, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 475, in add_to_graph
    self._create_definition_if_needed()
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 331, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 340, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 804, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1945, in tf_map_func
    dataset = map_func(nested_args)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\data\ops\readers.py", line 196, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1011, in convert_to_tensor
    as_ref=False)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\nVIALP2\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 944, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version

**Comment by dienhoa** [comment]
Check the train.record path is correct. I found that after creating the TFrecord, the record file is named as train.record-0000-of-0001 or something like that but in the config file, it jus just train.record

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by RonithSaju** [comment]
For those experiencing the problem on Google Colab, I replaced `%tensorflow_version 1.x` in my code with `!pip install tensorflow==1.15.5` and the error disappeared. Not limited to just version 1.15.5, it works for some other TensorFlow version 1s as well.
