### ISSUE TITLE
Test error about models-slim: nets- resnet_v1_test.py

### ISSUE THREAD

**Issue by codegank** [tensorflow/models#585]
## resnet_v1 model

======================================================================
ERROR: testEndPointsV1 (__main__.ResnetUtilsTest)
Test the end points of a tiny v1 bottleneck network.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./nets/resnet_v1_test.py", line 169, in testEndPointsV1
    _, end_points = self._resnet_plain(inputs, blocks, scope='tiny')
  File "./nets/resnet_v1_test.py", line 159, in _resnet_plain
    end_points = dict(tf.get_collection('end_points'))
TypeError: cannot convert dictionary update sequence element #0 to a sequence

----------------------------------------------------------------------
Ran 17 tests in 66.173s

It seems the resnet model miss a operation like this: net = tf.squeeze(net, [1, 2], name='SpatialSqueeze') ?

**Comment by drpngx** [comment]
Could you give more information? version, script, OS, etc.

**Comment by codegank** [comment]
My OS is centos 7, the tensorflow version is 0.10.0. I think this problem caused by my lower vision of tensorflow, right?

**Comment by drpngx** [comment]
How about the script you are using?

**Comment by codegank** [comment]
I simply use this script: python ./nets/resnet_v1_test.py. 

The reason why I test this model file is that I got an error when I was trying to fine-turning the resnt_v1_50 model for my own dataset. 

python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=mars \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=resnet_v1_50 \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --checkpoint_exclude_scopes=resnet_v1_50/Logits \
  --trainable_scopes=resnet_v1_50/Logits \
  --max_number_of_steps=5000 \
  --batch_size=64 \
  --labels_offsets=1 \
  --train_image_size=224 \
  --learning_rate=0.01 \
  --learning_rate_decay_type=fixed \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
  --weight_decay=0.00004

This is the  error log:

Traceback (most recent call last):
  File "train_image_classifier.py", line 587, in <module>
    tf.app.run()
  File "/import/linux/DEEP_LEARNING/tensorflow_C7.5_DNN5.0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 484, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/homes/xxx/Documents/models/slim/deployment/model_deploy.py", line 195, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "train_image_classifier.py", line 478, in clone_fn
    logits, labels, label_smoothing=FLAGS.label_smoothing, weight=1.0)
  File "/import/linux/DEEP_LEARNING/tensorflow_C7.5_DNN5.0/lib/python2.7/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py", line 372, in softmax_cross_entropy
    logits.get_shape().assert_is_compatible_with(onehot_labels.get_shape())
  File "/import/linux/DEEP_LEARNING/tensorflow_C7.5_DNN5.0/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 750, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (64, 1, 1, 625) and (64, 625) are incompatible

**Then I fixed this by add this code under the line of 199 in resnet_v1.py**

However, I got another error like this.
Traceback (most recent call last):
  File "train_image_classifier.py", line 587, in <module>
    tf.app.run()
  File "/import/linux/DEEP_LEARNING/tensorflow_C7.5_DNN5.0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 546, in main
    var_list=variables_to_train)
  File "/homes/wl307/Documents/models/slim/deployment/model_deploy.py", line 301, in optimize_clones
    optimizer, clone, num_clones, regularization_losses, **kwargs)
  File "/homes/wl307/Documents/models/slim/deployment/model_deploy.py", line 265, in _optimize_clone
    clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)
  File "/import/linux/DEEP_LEARNING/tensorflow_C7.5_DNN5.0/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 247, in compute_gradients
    raise ValueError("No variables to optimize")
ValueError: No variables to optimize

I am still trying to figure out this problem.

**Comment by drpngx** [comment]
If you could whittle it down to a smaller bite size, then stackoverflow might be your best bet (use tag "tensorflow").

**Comment by aldarabs** [comment]
I have the same issue. Did you fix it?
