### ISSUE TITLE
NanLossDuringTrainingError when training mnist

### ISSUE THREAD

**Issue by WeiyiLi** [tensorflow/models#5855]
### System information
- **What is the top-level directory of the model you are using**: /models/official/mnist
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 18.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**:1.12
- **Bazel version (if compiling from source)**: 0.15.0
- **CUDA/cuDNN version**:CPU-ONLY
- **GPU model and memory**:

### Describe the problem
I tried the mnist in [models/official/mnist](https://github.com/tensorflow/models/tree/master/official/mnist) and run it using command  `python3 mnist.py --export_dir ./mnist_saved_models
`
But it has error 
```
raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```
I tried to reduce the learning rate in mnist.py but this error still exists. 
The source code is from https://github.com/tensorflow/tensorflow/releases/tag/v1.12.0
### Source code / logs
```
I1203 15:30:05.617134 140284692195136 tf_logging.py:115] Initializing RunConfig with distribution strategies.
I1203 15:30:05.617341 140284692195136 tf_logging.py:115] Not using Distribute Coordinator.
I1203 15:30:05.617615 140284692195136 tf_logging.py:115] Using config: {'_model_dir': '/tmp/mnist_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.one_device_strategy.OneDeviceStrategy object at 0x7f95f2f2f780>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f95f2f2f7f0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': None}
I1203 15:30:05.661948 140284692195136 tf_logging.py:115] Calling model_fn.
I1203 15:30:06.011193 140284692195136 tf_logging.py:115] Done calling model_fn.
I1203 15:30:06.041876 140284692195136 tf_logging.py:115] Create CheckpointSaverHook.
I1203 15:30:06.174833 140284692195136 tf_logging.py:115] Graph was finalized.
I1203 15:30:06.178840 140284692195136 tf_logging.py:115] Restoring parameters from /tmp/mnist_model/model.ckpt-0
I1203 15:30:06.292510 140284692195136 tf_logging.py:115] Running local_init_op.
I1203 15:30:06.299429 140284692195136 tf_logging.py:115] Done running local_init_op.
I1203 15:30:06.514888 140284692195136 tf_logging.py:115] Saving checkpoints for 0 into /tmp/mnist_model/model.ckpt.
I1203 15:30:10.928804 140284692195136 tf_logging.py:115] cross_entropy = 5.2012495e+22, learning_rate = 1e-04, train_accuracy = 0.15
I1203 15:30:10.929588 140284692195136 tf_logging.py:115] loss = 5.2012495e+22, step = 0
E1203 15:30:11.142082 140284692195136 tf_logging.py:105] Model diverged with loss = NaN.
2018-12-03 15:30:11.148204: W tensorflow/core/kernels/data/cache_dataset_ops.cc:770] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the datasetwill be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
Traceback (most recent call last):
  File "mnist.py", line 236, in <module>
    absl_app.run(main)
  File "/home/kathy/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/kathy/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "mnist.py", line 230, in main
    run_mnist(flags.FLAGS)
  File "mnist.py", line 211, in run_mnist
    mnist_classifier.train(input_fn=train_input_fn, hooks=train_hooks)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1352, in _train_model_distributed
    saving_listeners)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/kathy/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1320, in run
    run_metadata=run_metadata))
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 753, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```
Please help out!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
