### ISSUE TITLE
 The pb file trained by retrain.py how to convert tflite file?

### ISSUE THREAD

**Issue by T-chuangxin** [tensorflow/models#5860]
The pb file trained by retrain.py how to convert tflite file,I want to use in mobile phone!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by T-chuangxin** [comment]
ZBMAC-C02VQ1YYH:~ tianchuangxin1$ tflite_convert \
>   --graph_def_file=/Users/tianchuangxin1/tensorflow_image/output_graph.pb \
>   --output_file=/Users/tianchuangxin1/tensorflow_image/output_graph.tflite \
>   --input_format=TENSORFLOW_GRAPHDEF \
>   --output_format=TFLITE \
>   --input_shape=1,244,244,3 \
>   --input_array=input \
>   --output_array=final_result \
>   --inference_type=FLOAT \
>   --input_data_type=FLOAT
2018-12-05 14:48:32.344934: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/Users/tianchuangxin1/anaconda/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 100, in _convert_model
    converter = _get_toco_converter(flags)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 87, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/contrib/lite/python/lite.py", line 283, in from_frozen_graph
    sess.graph, input_arrays)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 189, in get_tensors_from_tensor_names
    ",".join(invalid_tensors)))
ValueError: Invalid tensors 'input' were found.
