### ISSUE TITLE
Object Detection API - Gradient Clipping

### ISSUE THREAD

**Issue by maddyobrienjones** [tensorflow/models#5864]
### System information
- **What is the top-level directory of the model you are using**: /home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/models/facessd_mobilenet_v2_quantized_320x320_open_image_v4
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 19.0
- **TensorFlow installed from (source or binary)**: Deep Learning AMI on AWS
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: V9.0.176
- **GPU model and memory**: p2.xlarge
- **Exact command to reproduce**: PIPELINE_CONFIG_PATH=/home/ubuntu/anaconda3/lib/python3.6/site-packag
es/tensorflow/models/research/facessd_mobilenet_v2_quantized_320x320_open_image_v4/pipeline.config
MODEL_DIR=/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorfl
ow/models/research/facessd_mobilenet_v2_quantized_320x320_open_image_v4
NUM_TRAIN_STEPS=50000
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
python object_detection/model_main.py \
>     --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
>     --model_dir=${MODEL_DIR} \
>     --num_train_steps=${NUM_TRAIN_STEPS} \
>     —sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
>     --alsologtostderr

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
I am working on a face detection problem detecting small faces in large cluttered images. Every time I have tried training the model, my loss has exploded and become a NaN value. I've tried reorganizing my directories, double checking the coordinates of my bounding boxes, resizing my images, using both the FaceSSD model and the Faster RCNN Inception V2 Coco model, changing from RMS prop optimizer to Adam optimizer, decreasing my learning rate, and using legacy/train.py instead of model_main.py.

I am looking for advice on how to integrate gradient clipping into my model to avoid this happening. Is this done through the pipeline.config file or through the optimizerbuilder.py file? Any help/advice would be appreciated.

### Source code / logs
Traceback: 
ERROR:tensorflow:Model diverged with loss = NaN.
E1204 15:30:06.767873 140283027941120 tf_logging.py:105] Model diverged with loss = NaN.
Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1320, in run
    run_metadata=run_metadata))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 754, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by Ashutosh1995** [comment]
Hi,

I am also facing the same issue. When I try to finetune the EfficientDet D2 model with my dataset and change the localization loss with logIoU loss, then the loss immediately starts from NaN. But when I change to other losses such as L1 or like L2, it trains.

I am not able to understand that by changing one loss function value, the loss turns to nan .

Could some one please let me know ?
