### ISSUE TITLE
Unicode error when building ADE20K dataset tf record for deeplab.

### ISSUE THREAD

**Issue by QuantumLiu** [tensorflow/models#5899]
### System information
- **What is the top-level directory of the model you are using**:deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu16.04
- **TensorFlow installed from (source or binary)**:pip
- **TensorFlow version (use command below)**:1.90 gpu
- **Bazel version (if compiling from source)**:None
- **CUDA/cuDNN version**:9.0,7.1
- **GPU model and memory**:TITAN,1080ti
- **Exact command to reproduce**:bash download_and_convert_ade20k.sh

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
```
>> Converting image 1/20210 shard 0Traceback (most recent call last):
  File "./build_ade20k_data.py", line 118, in <module>
    tf.app.run()
  File "/home/re01/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./build_ade20k_data.py", line 113, in main
    'train', FLAGS.train_image_folder, FLAGS.train_image_label_folder)
  File "./build_ade20k_data.py", line 94, in _convert_dataset
    image_data = tf.gfile.FastGFile(image_filename, 'r').read()
  File "/home/re01/anaconda3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 132, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/re01/anaconda3/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "/home/re01/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 107, in as_str_any
    return as_str(value)
  File "/home/re01/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

```

**Comment by Eavis** [comment]
Hi,Quantum
Would you mind sharing your solution to this problem? I had the same issue as well. Thanks.

**Comment by arslanali900** [comment]
fo = tf.gfile.Open(f, "rb")
  d = cPickle.load(fo, encoding='latin1')
This solved the problem for me
use latin1 encoding
