### ISSUE TITLE
ImportError: libcublas.so.9.0

### ISSUE THREAD

**Issue by chkam05** [tensorflow/models#5903]
Python 3.6.7
Ubuntu 18.04 subsystem for Windows
This version of python is required becouse objects i traning is required to use in windows AI project

kamil@MSI-PC:/mnt/d/Users/models/research/object_detection$ python3 ./legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
Traceback (most recent call last):
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./legacy/train.py", line 47, in <module>
    import tensorflow as tf
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
Can you try if this [suggestion](https://stackoverflow.com/a/48429585) works in your case?

**Comment by chkam05** [comment]
The problem exists in CUDA installation, I can't even install CUDA 9.0 becouse of WSL Ubuntu.
I must try do it on Windows directly and found solution for it.

**Comment by chkam05** [comment]
After installing CUDA 10, i could install CUDA 9
Then this problem apears:

WARNING:tensorflow:From /home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1213 19:15:44.085035 140556441028416 tf_logging.py:125] From /home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From /mnt/d/Users/models/research/object_detection/legacy/trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1213 19:15:44.247436 140556441028416 tf_logging.py:125] From /mnt/d/Users/models/research/object_detection/legacy/trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 0 to match input file shards.
W1213 19:15:44.277505 140556441028416 tf_logging.py:125] num_readers has been reduced to 0 to match input file shards.
WARNING:tensorflow:From /mnt/d/Users/models/research/object_detection/builders/dataset_builder.py:80: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
W1213 19:15:44.282507 140556441028416 tf_logging.py:125] From /mnt/d/Users/models/research/object_detection/builders/dataset_builder.py:80: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
Traceback (most recent call last):
  File "./legacy/train.py", line 184, in <module>
    tf.app.run()
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "./legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/mnt/d/Users/models/research/object_detection/legacy/trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/mnt/d/Users/models/research/object_detection/legacy/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "./legacy/train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/mnt/d/Users/models/research/object_detection/builders/dataset_builder.py", line 134, in build
    config.input_path[:], input_reader_config)
  File "/mnt/d/Users/models/research/object_detection/builders/dataset_builder.py", line 80, in read_dataset
    sloppy=config.shuffle))
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1190, in apply
    dataset = transformation_func(self)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/interleave_ops.py", line 87, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 134, in __init__
    cycle_length, block_length)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2714, in __init__
    super(InterleaveDataset, self).__init__(input_dataset, map_func)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2677, in __init__
    experimental_nested_dataset_support=True)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 200, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/kamil/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 983, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

**Comment by usr34598** [comment]
I had the same issue and for me it worked again after adding

echo 'export LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}' >> ~/.bashrc

according to step 8 in this tutorial: https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-9-2-for-python-on-ubuntu/

**Comment by chkam05** [comment]
Better way i found something on windows.
After choosing:
- Tensorflow 1.12
- Cuda 9.0
- Cudnn 6.0
Tensorflow starts working for detection on actual data

But for training i made in:
\models\research
python setup.py build
python setup.py install

and now there is a problem with missing 'nets' library.
According to this post: [Issue 2031](https://github.com/tensorflow/models/issues/2031)
becouse my first problem was "not founding object_detection"
I can't do this:
export PYTHON_HOME=$PYTHON_HOME:`pwd`:`pwd`/slim
because of cmd not recognizing export command (it is for linux), same as pwd.

I can't do it on powershell becouse Anaconda3 environments are not launching on powershell.
So i stucked here

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
