### ISSUE TITLE
object_detection:TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Loovelj** [tensorflow/models#5905]
### System information
- **What is the top-level directory of the model you are using**:object dection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:pip
- **TensorFlow version (use command below)**:gpu-1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9.0.176
- **GPU model and memory**:12G
- **Exact command to reproduce**:python3.5

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

object_detection.
ssd_inception_v3_pets.config
ssd_inception_v2_coco_2018_01_28

Do:
python object_detection/model_main.py --alsologtostderr --model_dir=object_detection/train_ssd_inception_v2/ --pipeline_config_path=object_detection/train_ssd_inception_v2/ssd_inception_v3_pets.config

### Source code / logs
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
W1213 20:11:20.126205 139980489991936 tf_logging.py:125] Forced number of epochs for all eval validations to be 1.
INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: 1
I1213 20:11:20.126504 139980489991936 tf_logging.py:115] Maybe overwriting sample_1_of_n_eval_examples: 1
INFO:tensorflow:Maybe overwriting train_steps: None
I1213 20:11:20.126622 139980489991936 tf_logging.py:115] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting load_pretrained: True
I1213 20:11:20.126714 139980489991936 tf_logging.py:115] Maybe overwriting load_pretrained: True
INFO:tensorflow:Ignoring config override key: load_pretrained
I1213 20:11:20.126804 139980489991936 tf_logging.py:115] Ignoring config override key: load_pretrained
INFO:tensorflow:Maybe overwriting eval_num_epochs: 1
I1213 20:11:20.127182 139980489991936 tf_logging.py:115] Maybe overwriting eval_num_epochs: 1
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
W1213 20:11:20.127314 139980489991936 tf_logging.py:125] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
INFO:tensorflow:create_estimator_and_inputs: use_tpu False, export_to_tpu False
I1213 20:11:20.127432 139980489991936 tf_logging.py:115] create_estimator_and_inputs: use_tpu False, export_to_tpu False
INFO:tensorflow:Using config: {'_device_fn': None, '_model_dir': 'object_detection/train_ssd_inception_v2/', '_save_checkpoints_secs': 600, '_train_distribute': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4f96dbd7f0>, '_service': None, '_tf_random_seed': None, '_protocol': None, '_global_id_in_cluster': 0, '_keep_checkpoint_every_n_hours': 10000, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_is_chief': True, '_evaluation_master': '', '_master': '', '_save_checkpoints_steps': None, '_task_type': 'worker', '_keep_checkpoint_max': 5, '_task_id': 0, '_num_worker_replicas': 1, '_save_summary_steps': 100, '_eval_distribute': None, '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_experimental_distribute': None}
I1213 20:11:20.127867 139980489991936 tf_logging.py:115] Using config: {'_device_fn': None, '_model_dir': 'object_detection/train_ssd_inception_v2/', '_save_checkpoints_secs': 600, '_train_distribute': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4f96dbd7f0>, '_service': None, '_tf_random_seed': None, '_protocol': None, '_global_id_in_cluster': 0, '_keep_checkpoint_every_n_hours': 10000, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_is_chief': True, '_evaluation_master': '', '_master': '', '_save_checkpoints_steps': None, '_task_type': 'worker', '_keep_checkpoint_max': 5, '_task_id': 0, '_num_worker_replicas': 1, '_save_summary_steps': 100, '_eval_distribute': None, '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_experimental_distribute': None}
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f4f96dd77b8>) includes params argument, but params are not passed to Estimator.
W1213 20:11:20.128126 139980489991936 tf_logging.py:125] Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f4f96dd77b8>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Not using Distribute Coordinator.
I1213 20:11:20.128751 139980489991936 tf_logging.py:115] Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
I1213 20:11:20.128986 139980489991936 tf_logging.py:115] Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
I1213 20:11:20.129307 139980489991936 tf_logging.py:115] Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
Traceback (most recent call last):
  File "/home/models/research/object_detection/utils/label_map_util.py", line 137, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "/home/py3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/py3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/py3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/py3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/py3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 7:1 : Message type "object_detection.protos.StringIntLabelMap" has no field named "model".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/model_main.py", line 115, in <module>
    tf.app.run()
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 110, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1234, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1075, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/home/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1162, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/models/research/object_detection/inputs.py", line 479, in _train_input_fn
    batch_size=params['batch_size'] if params else train_config.batch_size)
  File "/home/models/research/object_detection/builders/dataset_builder.py", line 123, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "/home/models/research/object_detection/data_decoders/tf_example_decoder.py", line 297, in __init__
    default_value=''),
  File "/home/models/research/object_detection/data_decoders/tf_example_decoder.py", line 59, in __init__
    label_map_proto_file, use_display_name=False)
  File "/home/models/research/object_detection/utils/label_map_util.py", line 165, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/home/models/research/object_detection/utils/label_map_util.py", line 139, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'

**Comment by Loovelj** [comment]
I fount the error bacause   in the config, the  label_map_path  I wrote "ssd_inception_v3_pets.config"  , actually it should be  "label_map.pbtxt"
