### ISSUE TITLE
Perform py-3 premade_estimator.py error reporting

### ISSUE THREAD

**Issue by gunxiaoshi** [tensorflow/models#5942]
E:\Python\Tensorflow\models\samples\core\get_started>py -3  premade_estimator.py
Traceback (most recent call last):
  File "premade_estimator.py", line 88, in <module>
    tf.app.run(main)
  File "D:\Program Files\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "premade_estimator.py", line 34, in main
    (train_x, train_y), (test_x, test_y) = iris_data.load_data()
  File "E:\Python\Tensorflow\models\samples\core\get_started\iris_data.py", line 21, in load_data
    train = pd.read_csv(train_path, names=CSV_COLUMN_NAMES, header=0)
  File "D:\Program Files\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "D:\Program Files\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\Program Files\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "D:\Program Files\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\Program Files\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 697, in pandas._libs.parsers.TextReader._setup_parser_source
OSError: Initializing from file failed

E:\Python\Tensorflow\models\samples\core\get_started>

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
