### ISSUE TITLE
I am running the tensorflow object detection API i m getting these errors :3

### ISSUE THREAD

**Issue by Faaiza01** [tensorflow/models#5950]
Traceback (most recent call last):   File "legacy/train.py", line 51, in <module>     from object_detection.builders import model_builder    File "C:\Users\Faaiza Rasheed\Anaconda3\lib\site-packages\object_detection-0.1 -py3.6.egg\object_detection\builders\model_builder.py", line 34, in <module>     from object_detection.meta_architectures import ssd_meta_arch     File "C:\Users\Faaiza Rasheed\Anaconda3\lib\site-packages\object_detection-0.1 -py3.6.egg\object_detection\meta_architectures\ssd_meta_arch.py", line 31, in <m odule>     from object_detection.utils import visualization_utils     File "C:\Users\Faaiza Rasheed\Anaconda3\lib\site-packages\object_detection-0.1 -py3.6.egg\object_detection\utils\visualization_utils.py", line 28, in <module>     import matplotlib.pyplot as plt  # pylint: disable=g-import-not-at-top     File "C:\Users\Faaiza Rasheed\Anaconda3\lib\site-packages\matplotlib\pyplot.py ", line 31, in <module>     import matplotlib.colorbar     File "C:\Users\Faaiza Rasheed\Anaconda3\lib\site-packages\matplotlib\colorbar. py", line 32, in <module> import matplotlib.artist as martist    File "C:\Users\Faaiza Rasheed\Anaconda3\lib\site-packages\matplotlib\artist.py ", line 16, in <module>      from .path import Path   File "C:\Users\Faaiza Rasheed\Anaconda3\lib\site-packages\matplotlib\path.py",  line 21, in <module>      from . import _path, rcParams ImportError: cannot import name '_path'   S

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
