### ISSUE TITLE
label_map_util.py, line 138, load_labelmap label_map.ParseFromString<label_map_string> eError:a bytes-like object is required,not 'str'

### ISSUE THREAD

**Issue by benaliali** [tensorflow/models#5961]
C:\models\research\object_detection\legacy>python train.py --logtostderr --train _dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config WARNING:tensorflow:From C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\ site-packages\tensorflow\python\platform\app.py:125: main (from main) is dep recated and will be removed in a future version. Instructions for updating: Use object_detection/model_main.py. WARNING:tensorflow:From C:\models\research\object_detection\legacy\trainer.py:26 6: create_global_step (from tensorflow.contrib.framework.python.ops.variables) i s deprecated and will be removed in a future version. Instructions for updating: Please switch to tf.train.create_global_step Traceback (most recent call last): File "C:\models\research\object_detection\utils\label_map_util.py", line 136, in load_labelmap enter code heretext_format.Merge(label_map_string, label_map) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 536, in Merge descriptor_pool=descriptor_pool) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 590, in MergeLines return parser.MergeLines(lines, message) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 623, in MergeLines self._ParseOrMerge(lines, message) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 638, in _ParseOrMerge self._MergeField(tokenizer, message) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 763, in _MergeField merger(tokenizer, message, field) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 837, in _MergeMessageField self._MergeField(tokenizer, sub_message) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 749, in _MergeField tokenizer.Consume(':') File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\go ogle\protobuf\text_format.py", line 1101, in Consume raise self.ParseError('Expected "%s".' % token) google.protobuf.text_format.ParseError: 2:4 : Expected ":".

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "train.py", line 186, in tf.app.run() File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\te nsorflow\python\platform\app.py", line 125, in run _sys.exit(main(argv)) File "C:\Users\Ali\AppData\Local\Programs\Python\Python36\lib\site-packages\te nsorflow\python\util\deprecation.py", line 306, in new_func return func(*args, **kwargs) File "train.py", line 182, in main graph_hook_fn=graph_rewriter_fn) File "C:\models\research\object_detection\legacy\trainer.py", line 280, in tra in train_config.prefetch_queue_capacity, data_augmentation_options) File "C:\models\research\object_detection\legacy\trainer.py", line 59, in crea te_input_queue tensor_dict = create_tensor_dict_fn() File "train.py", line 123, in get_next dataset_builder.build(config)).get_next() File "C:\models\research\object_detection\builders\dataset_builder.py", line 1 23, in build num_additional_channels=input_reader_config.num_additional_channels) File "C:\models\research\object_detection\data_decoders\tf_example_decoder.py" , line 297, in init default_value=''), File "C:\models\research\object_detection\data_decoders\tf_example_decoder.py" , line 59, in init label_map_proto_file, use_display_name=False) File "C:\models\research\object_detection\utils\label_map_util.py", line 164, in get_label_map_dict label_map = load_labelmap(label_map_path) File "C:\models\research\object_detection\utils\label_map_util.py", line 138, in load_labelmap label_map.ParseFromString(label_map_string) TypeError: a bytes-like object is required, not 'str'
label_map.pbtxt     item { id=1 name='ciseau' }

**Comment by benaliali** [comment]
in label_map.pbtx instead of using "=" use ":"

**Comment by nazih1997** [comment]
HI , how did u resolved the problem?
