### ISSUE TITLE
google.protobuf.text_format.ParseError: 127:1 : Message type "object_detection.protos.InputReader" has no field named "eval_config".

### ISSUE THREAD

**Issue by RamishaRaniK** [tensorflow/models#5997]
I am getting this error,

'C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Anaconda3\envs\Helmet\lib\site-packages\tensorflow\python\platform\app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\tensorflow\python\util\deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\tensorflow1\models\research\object_detection\utils\config_util.py", line 96, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 127:1 : Message type "object_detection.protos.InputReader" has no field named "eval_config".'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by RamishaRaniK** [comment]
Thank you for the reply. 
please kindly read the below details

**python version:** python3.6.8

**What is the top-level directory of the model you are using**
C:\tensorflow1\models\research\object_detection>
**Error**
(Helmet) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Anaconda3\envs\Helmet\lib\site-packages\tensorflow\python\platform\app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\tensorflow\python\util\deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\tensorflow1\models\research\object_detection\utils\config_util.py", line 96, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Anaconda3\envs\Helmet\lib\site-packages\google\protobuf\text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 127:1 : Message type "object_detection.protos.InputReader" has no field named "eval_config".

(Helmet) C:\tensorflow1\models\research\object_detection>

**OS Platform and Distribution**
**OS platform:** Windows 10, 
**Distribution:** Anaconda Distribution
**TensorFlow installed from**
pip install tensorflow-gpu==1.5
**TensorFlow version**
tensorflow-gpu==1.5
Bazel version
**CUDA/cuDNN version**
**CUDA:**9.0 
**cuDNN:**7.0
**GPU model and memory**
**GPU model:** GTX1060(nvidia)
**GPU Memory:** 6GB
Exact command to reproduce
 Thanks in advance

**Comment by yaceben** [comment]
Hi @RamishaRaniK,

It's most likely a problem with a malformed faster_rcnn_inception_v2_pets.config, my best guess being that you probably forgot the closing bracket of the train_input_reader.

**Comment by RamishaRaniK** [comment]
Hi @yaceben
Thank you so much for your reply.

It worked for me. I have missed the closed bracket of the train_input_reader as you mentioned.

once again thanks!

**Comment by deep28vish** [comment]
I just installed TF-GPU=1.14 in new system and tried for training only to deal with this error:

Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 94, in main
    FLAGS.pipeline_config_path)
  File "D:\models\research\object_detection\utils\config_util.py", line 104, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\google\protobuf\text_format.py", line 702, in Merge
    allow_unknown_field=allow_unknown_field)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\google\protobuf\text_format.py", line 770, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\google\protobuf\text_format.py", line 795, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\google\protobuf\text_format.py", line 817, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\google\protobuf\text_format.py", line 942, in _MergeField
    merger(tokenizer, message, field)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\google\protobuf\text_format.py", line 1016, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\google\protobuf\text_format.py", line 909, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 173:1 : Message type "object_detection.protos.TrainConfig" has no field named "train_input_reader".

*******************************************************************************************************
here is my config file for ssd_v2_mobilenet

# SSD with Mobilenet v2 configuration for MSCOCO Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
# should be configured.

model {
ssd {
num_classes: 2
box_coder {
faster_rcnn_box_coder {
y_scale: 10.0
x_scale: 10.0
height_scale: 5.0
width_scale: 5.0
}
}
matcher {
argmax_matcher {
matched_threshold: 0.5
unmatched_threshold: 0.5
ignore_thresholds: false
negatives_lower_than_unmatched: true
force_match_for_each_row: true
}
}
similarity_calculator {
iou_similarity {
}
}
anchor_generator {
ssd_anchor_generator {
num_layers: 6
min_scale: 0.2000000000298023224
max_scale: 0.9499999988079071
aspect_ratios: 1.0
aspect_ratios: 2.0
aspect_ratios: 0.5
aspect_ratios: 3.0
aspect_ratios: 0.33299999944468896
}
}
image_resizer {
fixed_shape_resizer {
height: 600
width: 600
}
}
box_predictor {
convolutional_box_predictor {
min_depth: 0
max_depth: 0
num_layers_before_predictor: 0
use_dropout: false
dropout_keep_probability: 0.8
kernel_size: 1
box_code_size: 4
apply_sigmoid_to_scores: false
conv_hyperparams {
activation: RELU_6,
regularizer {
l2_regularizer {
weight: 0.00004
}
}
initializer {
truncated_normal_initializer {
stddev: 0.03
mean: 0.0
}
}
batch_norm {
train: true,
scale: true,
center: true,
decay: 0.9997,
epsilon: 0.001,
}
}
}
}
feature_extractor {
type: 'ssd_mobilenet_v2'
min_depth: 16
depth_multiplier: 1.0
conv_hyperparams {
activation: RELU_6,
regularizer {
l2_regularizer {
weight: 0.00004
}
}
initializer {
truncated_normal_initializer {
stddev: 0.03
mean: 0.0
}
}
batch_norm {
train: true,
scale: true,
center: true,
decay: 0.9997,
epsilon: 0.001,
}
}
}
loss {
classification_loss {
weighted_sigmoid {
}
}
localization_loss {
weighted_smooth_l1 {
}
}
hard_example_miner {
num_hard_examples: 3000
iou_threshold: 0.99
loss_type: CLASSIFICATION
max_negatives_per_positive: 3
min_negatives_per_image: 3
}
classification_weight: 1.0
localization_weight: 1.0
}
normalize_loss_by_num_matches: true
post_processing {
batch_non_max_suppression {
score_threshold: 1e-8
iou_threshold: 0.6
max_detections_per_class: 100
max_total_detections: 100
}
score_converter: SIGMOID
}
}
}

train_config: {
batch_size: 96
optimizer {
rms_prop_optimizer: {
learning_rate: {
exponential_decay_learning_rate {
initial_learning_rate: 0.004
decay_steps: 5000
decay_factor: 0.95
}
}
momentum_optimizer_value: 0.9
decay: 0.9
epsilon: 1.0
}
}
fine_tune_checkpoint:"D:\\models\\research\\object_detection\\ssd_mobilenet_v2_coco_2018_03_29\\model.ckpt"
fine_tune_checkpoint_type:  "detection"
# Note: The below line limits the training process to 200K steps, which we
# empirically found to be sufficient enough to train the pets dataset. This
# effectively bypasses the learning rate schedule (the learning rate will
# never decay). Remove the below line to train indefinitely.
num_steps: 2000000
data_augmentation_options {
#random_horizontal_flip {
#}
#}
#data_augmentation_options {
#ssd_random_crop {
#}
#}
}

train_input_reader:{
tf_record_input_reader {
input_path:"D:\\models\\research\\object_detection\\emma_record\\emma_train.record"
}
label_map_path:"D:\\models\\research\\object_detection\\ALL_PBTXT\\person_vehicle.pbtxt"
}

eval_config: {
num_examples: 8000
# Note: The below line limits the evaluation process to 10 evaluations.
# Remove the below line to evaluate indefinitely.
max_evals: 10
}

eval_input_reader: {
tf_record_input_reader {
input_path:"D:\\models\\research\\object_detection\\emma_record\\emma_train.record"
}
label_map_path:"D:\\models\\research\\object_detection\\ALL_PBTXT\\person_vehicle.pbtxt"
shuffle: false
num_readers: 1
}

my pbtxt file:
item {
  id: 1
  name: 'person'
}

item {
  id: 2
  name: 'vehicle'
}



I understand that there is some silly mistake only if one could help.


OS: windows 10
conda env : tF:1.14
CUDA :10.2
GPU Quadro RTX 8000 (48GB)
RAM : 192 GB

**Comment by sayannath** [comment]
Ig this issue must be closed now!
