### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError: flag --trained_checkpoint_prefix=None: Flag --trained_checkpoint_prefix must be specified.

### ISSUE THREAD

**Issue by yadinDean** [tensorflow/models#6070]
Im run
python3 export_inference_graph.py \ --input_type image_tensor \  --pipeline_config_path training/logo_v1.config \  ----trained_checkpoint_prefix training/model.ckpt-250000 \  --output_directory logo_deteksi

here is the log
Traceback (most recent call last):
  File "export_inference_graph.py", line 143, in <module>
    tf.app.run()
  File "/home/dukundeath/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/home/dukundeath/.virtualenvs/cv/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/home/dukundeath/.virtualenvs/cv/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 635, in __call__
    self._assert_all_validators()
  File "/home/dukundeath/.virtualenvs/cv/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 509, in _assert_all_validators
    self._assert_validators(all_validators)
  File "/home/dukundeath/.virtualenvs/cv/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 530, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --trained_checkpoint_prefix=None: Flag --trained_checkpoint_prefix must be specified.
how to fix it?
tks!

**Comment by GigsyKami** [comment]
hey @yadinDean do you mange to solve the error? i got the same error can you help me?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
