### ISSUE TITLE
[Textsum] Exception in thread Thread-*

### ISSUE THREAD

**Issue by prakhar21** [tensorflow/models#608]
## Textsum
Hi, tried training the model using the instructions mentioned in the docs. When I fire the train command then below is the error that I am encountering. 

`Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/prakhar/utilities/IOT/PythonUtilPlugin/models/textsum/batch_reader.py", line 135, in _FillInputQueue
    (article, abstract) = input_gen.next()
  File "/home/prakhar/utilities/IOT/PythonUtilPlugin/models/textsum/batch_reader.py", line 244, in _TextGenerator
    e = example_gen.next()
  File "/home/prakhar/utilities/IOT/PythonUtilPlugin/models/textsum/data.py", line 101, in ExampleGen
    str_len = struct.unpack('q', len_bytes)[0]
error: unpack requires a string argument of length 8
`
Please, let me know the problem.

Thanks

**Comment by aselle** [comment]
Please provide more info.
- What operating system?
- What version of TensorFlow?
- What exact command reproduces this error?

**Comment by girving** [comment]
Closing due to lack of activity.

**Comment by JustinLin610** [comment]
I also met this problem on Ubuntu 17.04, tensorflow-1.3, and I run the model on python2.7. If I run it on the python3, there will be a type error: require a byte-like object, not a str. I found the problems on both github and stackoverflow, but I still could not find the answers. Can anyone offer me some help?
Many thanks!
