### ISSUE TITLE
how to use center_loss in TF-slim  train_image_classifier.py

### ISSUE THREAD

**Issue by kelisiya** [tensorflow/models#6108]
when I use this [tensorflow-center_loss]( https://github.com/zoli333/Center-Loss )
`Traceback (most recent call last):
  File "D:/Kelisiya/models-master/research/slim/train_image_classifier.py", line 670, in <module>
    tf.app.run()
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:/Kelisiya/models-master/research/slim/train_image_classifier.py", line 566, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "D:\Kelisiya\models-master\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "D:/Kelisiya/models-master/research/slim/train_image_classifier.py", line 559, in clone_fn
    center_loss,center = get_center_loss(logits,labels)
  File "D:/Kelisiya/models-master/research/slim/train_image_classifier.py", line 459, in get_center_loss
    loss = tf.nn.l2_loss(features - centers_batch)
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 862, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 8913, in sub
    "Sub", x=x, y=y, name=name)
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1790, in __init__
    control_input_ops)
  File "C:\Users\startdt\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1629, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 5 and 105 for 'sub_1' (op: 'Sub') with input shapes: [5,21], [105,21].`

I don't know how to use this code in train_image_classifier.py , have anyone tried with this code ever?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
