### ISSUE TITLE
InternalError (see above for traceback): Overlapping slices: existing slice = -:-, new slice = -:-          [[node save/restore_slice_9 (defined at /home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py:109)  = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/restore_slice_9/tensor_name, save/restore_slice_9/shape_and_slice)]]

### ISSUE THREAD

**Issue by domil** [tensorflow/models#6160]
2 FMA
2019-02-06 12:58:29.314894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-06 12:58:29.315153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:00:1e.0
totalMemory: 15.75GiB freeMemory: 317.94MiB
2019-02-06 12:58:29.315182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-02-06 12:58:30.269515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-06 12:58:30.269563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-02-06 12:58:30.269579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-02-06 12:58:30.269745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1e.0, compute capability: 7.0)
2019-02-06 12:58:30.381076: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381058: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381119: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381150: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381065: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381151: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381165: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381223: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381239: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381143: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381262: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381262: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381287: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381202: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381206: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381328: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381341: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381341: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381386: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381401: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381183: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381310: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381428: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381446: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381447: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381463: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381495: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381104: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381510: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381352: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381554: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381570: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381585: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381591: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381620: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381454: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381643: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381506: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381307: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381705: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381607: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381521: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381705: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381761: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381745: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381780: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381786: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381661: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381816: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381748: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381840: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381848: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381717: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381800: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381854: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381799: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381891: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381913: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381868: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381881: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381951: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381972: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381954: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381982: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382011: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382024: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381920: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382024: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381869: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382070: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382070: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382071: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381990: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382117: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382047: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382159: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382116: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382159: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382184: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.381980: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382201: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382216: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382167: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382201: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382248: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382231: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382278: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382308: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382136: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382231: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382345: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382356: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382368: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382394: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382411: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382202: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382432: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382445: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382460: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382469: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382329: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382371: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382286: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
2019-02-06 12:58:30.382248: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:175 : Internal: Overlapping slices: existing slice = -:-, new slice = -:-
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Overlapping slices: existing slice = -:-, new slice = -:-
         [[{{node save/restore_slice_9}} = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/restore_slice_9/tensor_name, save/restore_slice_9/shape_and_slice)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 302, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 292, in main
    _SampleModel(FLAGS.prefix, vocab)
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 170, in _SampleModel
    sess, t = _LoadModel(FLAGS.pbtxt, FLAGS.ckpt)
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 113, in _LoadModel
    sess.run('save/restore_all', {'save/Const:0': ckpt_file})
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Overlapping slices: existing slice = -:-, new slice = -:-
         [[node save/restore_slice_9 (defined at /home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py:109)  = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/restore_slice_9/tensor_name, save/restore_slice_9/shape_and_slice)]]

Caused by op 'save/restore_slice_9', defined at:
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 302, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 292, in main
    _SampleModel(FLAGS.prefix, vocab)
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 170, in _SampleModel
    sess, t = _LoadModel(FLAGS.pbtxt, FLAGS.ckpt)
  File "/home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py", line 109, in _LoadModel
    'global_step:0'], name='')
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/ubuntu/anaconda3/envs/tensorflow36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Overlapping slices: existing slice = -:-, new slice = -:-
         [[node save/restore_slice_9 (defined at /home/ubuntu/preTrainedModel/bazel-bin/lm_1b/lm_1b_eval.runfiles/__main__/lm_1b/lm_1b_eval.py:109)  = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/restore_slice_9/tensor_name, save/restore_slice_9/shape_and_slice)]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
