### ISSUE TITLE
Restoring from checkpoint failed: OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key v/cg/affine0/biases not found in checkpoint

### ISSUE THREAD

**Issue by vilmara** [tensorflow/models#6209]
------------------------

### System information
- **What is the top-level directory of the model you are using**: benchmarks-cnn_tf_v1.12_compatible
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**: Via docker for CPU Only
- **TensorFlow version (use command below)**: 1.12
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: `python tf_cnn_benchmarks.py --device=cpu --data_format=NHWC --num_batches=100 --optimizer=sgd --distortions=True --mkl=True --num_warmup_batches=10 --use_fp16=True --data_dir=/home/data/imagenet_tfrecord/validation --data_name=imagenet --model=resnet50_v2 --eval=True --batch_size=32 --train_dir=/home/models/resnet_imagenet_v2_fp32_20181001/`

### Describe the problem
I am tryng to run the benchmarks in validation mode for inference with the official pre-trained model resnet50, checkpoints resnet_imagenet_v2_fp32_20181001 downloaded from 
http://download.tensorflow.org/models/official/20181001_resnet/checkpoints/resnet_imagenet_v2_fp32_20181001.tar.gz but I got errors

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
MP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 1 core 12 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 1 core 12 thread 1
OMP: Info #250: KMP_AFFINITY: pid 409 tid 409 thread 0 bound to OS proc set 0
2019-02-15 14:45:38.918800: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
TensorFlow:  1.12
Model:       resnet50
Dataset:     imagenet
Mode:        BenchmarkMode.EVAL
SingleSess:  False
Batch size:  32 global
             32 per device
Num batches: 100
Num epochs:  0.06
Devices:     ['/cpu:0']
Data format: NCHW
Optimizer:   sgd
Variables:   parameter_server
==========
Generating evaluation model
W0215 14:45:38.955034 140123845060352 tf_logging.py:125] From /benchmarks/preprocessing.py:672: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
W0215 14:45:38.978404 140123845060352 tf_logging.py:125] From /benchmarks/preprocessing.py:690: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.map_and_batch(...)`.
I0215 14:45:41.365115 140123845060352 tf_logging.py:115] Restoring parameters from /home/dell/models/resnet_imagenet_v2_fp32_20181001/model.ckpt-225207
2019-02-15 14:45:41.718159: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key v/cg/affine0/biases not found in checkpoint
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 60, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "/benchmarks/benchmark_cnn.py", line 1781, in run
    return self._run_eval()
  File "/benchmarks/benchmark_cnn.py", line 1808, in _run_eval
    global_step = load_checkpoint(saver, sess, self.params.train_dir)
  File "/benchmarks/benchmark_cnn.py", line 919, in load_checkpoint
    saver.restore(sess, model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1562, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key v/cg/affine0/biases not found in checkpoint
         [[node save/RestoreV2 (defined at /benchmarks/benchmark_cnn.py:1798)  = RestoreV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "tf_cnn_benchmarks.py", line 60, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "/benchmarks/benchmark_cnn.py", line 1781, in run
    return self._run_eval()
  File "/benchmarks/benchmark_cnn.py", line 1798, in _run_eval
    saver = tf.train.Saver(self.variable_mgr.savable_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 862, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key v/cg/affine0/biases not found in checkpoint
         [[node save/RestoreV2 (defined at /benchmarks/benchmark_cnn.py:1798)  = RestoreV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

**Comment by zhengjiangw** [comment]
I download the inception_resnet_v2 model and the code. but I got the similar error ! so how did you solve the error ?

**Comment by vilmara** [comment]
The pre-trained models downloaded from tensorflow/models repo are not compatible with tf_cnn_benchmarks.py script. Please see the issue https://github.com/tensorflow/benchmarks/issues/260.  and please read this link: [(https://github.com/NervanaSystems/ngraphtf/issues/89)]. 

As a solution, I retrained the model with the tf benchmarks scripts from scratch an used the checkpoints to evaluate it see https://github.com/tensorflow/benchmarks/issues/311

**Comment by FathUMinUllah3797** [comment]
> @zhengjiangw I got this error. I thought, I thought it has problem in saving the file but could not find the solution. Anyone please?

2022-06-17 14:47:43.668056: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at save_restore_v2_ops.cc:271 : PERMISSION_DENIED: Failed to create a directory: /; Permission denied
