### ISSUE TITLE
[DeepLab] Error: Key MobilenetV2/Conv/BatchNorm/beta not found in checkpoint

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/models#6212]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.6
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.13
- **Bazel version (if compiling from source)**: 0.15.2
- **CUDA/cuDNN version**: 9.2
- **GPU model and memory**: 1080Ti 8GB
- **Exact command to reproduce**: 

```
> cd research
> PYTHONPATH='.':'slim' python deeplab/vis.py \
    --logtostderr \
    --vis_split="val" \
    --model_variant="mobilenet_v2" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --vis_crop_size=1025 \
    --vis_crop_size=2049 \
    --dataset="cityscapes" \
    --colormap_type="cityscapes" \
    --checkpoint_dir=${PATH_TO_CHECKPOINT} \
    --vis_logdir=${PATH_TO_VIS_DIR} \
    --dataset_dir=${PATH_TO_DATASET}
```

### Describe the problem

Run the above command using [this official checkpoint](
http://download.tensorflow.org/models/deeplabv3_mnv2_cityscapes_train_2018_02_05.tar.gz) and the following error is generated:

```
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key MobilenetV2/Conv/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at vis.py:263) ]]
```

However, it runs perfectly fine using the option `--model_variant="xception_65"` and [this checkpoint](
http://download.tensorflow.org/models/deeplabv3_cityscapes_train_2018_02_06.tar.gz).

### Error Trace

```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key MobilenetV2/Conv/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at deeplab/vis.py:263) ]]

Caused by op u'save/RestoreV2', defined at:
  File "deeplab/vis.py", line 320, in <module>
    tf.app.run()
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/vis.py", line 263, in main
    saver = tf.train.Saver(slim.get_variables_to_restore())
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 501, in new_func
    return func(*args, **kwargs)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key MobilenetV2/Conv/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at deeplab/vis.py:263) ]]

Traceback (most recent call last):
  File "deeplab/vis.py", line 320, in <module>
    tf.app.run()
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/vis.py", line 291, in main
    sv.saver.restore(sess, last_checkpoint)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key MobilenetV2/Conv/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at deeplab/vis.py:263) ]]

Caused by op u'save/RestoreV2', defined at:
  File "deeplab/vis.py", line 320, in <module>
    tf.app.run()
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/vis.py", line 263, in main
    saver = tf.train.Saver(slim.get_variables_to_restore())
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 501, in new_func
    return func(*args, **kwargs)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Volumes/Data/Projects/tensorflow-models/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key MobilenetV2/Conv/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at deeplab/vis.py:263) ]]
```

**Comment by harshgrovr** [comment]
@hoonkai  what is the solution to this ?

**Comment by Robinxin123** [comment]
@hoonkai  have you solved now?

**Comment by mandakinee** [comment]
I am also getting this error

**Comment by gmt710** [comment]
Maybe the config file does not match the model.

**Comment by hust-nj** [comment]
@harshgrovr @hoonkai @Robinxin123 @mandakinee 
Have you solved it?
I get the same error.
Thank you!
