### ISSUE TITLE
Change train image size to 64*64

### ISSUE THREAD

**Issue by YusukeO** [tensorflow/models#6214]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:anaconda
- **TensorFlow version (use command below)**:v1.6.0-0-gd2e24b6039 1.6.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:GTX1080ti
- **Exact command to reproduce**:
```
$ DATASET_DIR=/home/yusuke/PycharmProjects/nasnet-tensorflow/data/car/real/traintfrecord 
$ TRAIN_DIR=./train

# For Nasnet-a-mobile
# --dataset_name=customized
$ CHECKPOINT_PATH=./pre-trained/nasnet-a_mobile_04_10_2017/model.ckpt
python train_image_classifier.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=customized \
    --dataset_split_name=train \
    --model_name=nasnet_mobile \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --checkpoint_exclude_scopes=final_layer,aux_7,aux_6,aux_5,aux_4,aux3,aux2,aux1 \
    --trainable_scopes=final_layer,aux_7,aux_6,aux_5,aux_4,aux3,aux2,aux1 \
    --max_number_of_steps=5000 \
    --train_image_size=64
```

### Describe the problem
I tried to train nasnet model with my own data whose shape is 64, 64, 3. 
When I ran below command without `--train_image_size=64` argument, that worked fine (but with low accuracy). 
But after I add `--train_image_size=64` argument like below, the code said following error. 
Should I add the argument when I train 64,64,3 images? If so, how can I avoid the error? 
Thank you!

```
(dagan) yusuke@yusuke-lab-pc:~/PycharmProjects/nasnet-tensorflow$ bash train_mobile.sh 
WARNING:tensorflow:From train_image_classifier.py:400: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
2019-02-17 13:59:02.647080: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-17 13:59:02.647479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 9.97GiB
2019-02-17 13:59:02.647502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2019-02-17 13:59:02.864017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/device:GPU:0 with 9646 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
INFO:tensorflow:A GPU is available on the machine, consider using NCHW data format for increased speed on GPU.
Traceback (most recent call last):
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 5 from 4 for 'aux_7/aux_logits/AvgPool2D/AvgPool' (op: 'AvgPool') with input shapes: [32,4,4,528].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_image_classifier.py", line 574, in <module>
    tf.app.run()
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_image_classifier.py", line 474, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/home/yusuke/PycharmProjects/nasnet-tensorflow/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "train_image_classifier.py", line 457, in clone_fn
    logits, end_points = network_fn(images)
  File "/home/yusuke/PycharmProjects/nasnet-tensorflow/nets/nets_factory.py", line 135, in network_fn
    return func(images, num_classes, is_training=is_training, **kwargs)
  File "/home/yusuke/PycharmProjects/nasnet-tensorflow/nets/nasnet/nasnet.py", line 370, in build_nasnet_mobile
    final_endpoint=final_endpoint)
  File "/home/yusuke/PycharmProjects/nasnet-tensorflow/nets/nasnet/nasnet.py", line 495, in _build_nasnet_base
    scope='aux_{}'.format(cell_num))
  File "/home/yusuke/PycharmProjects/nasnet-tensorflow/nets/nasnet/nasnet.py", line 225, in _build_aux_head
    aux_logits, [5, 5], stride=3, padding='VALID')
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 122, in avg_pool2d
    outputs = layer.apply(inputs)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 809, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/layers/pooling.py", line 277, in call
    data_format=utils.convert_data_format(self.data_format, 4))
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2095, in avg_pool
    name=name)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 68, in _avg_pool
    data_format=data_format, name=name)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3273, in create_op
    compute_device=compute_device)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3313, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2501, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2474, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2404, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/yusuke/.pyenv/versions/anaconda3-5.1.0/envs/dagan/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 5 from 4 for 'aux_7/aux_logits/AvgPool2D/AvgPool' (op: 'AvgPool') with input shapes: [32,4,4,528].
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
