### ISSUE TITLE
Tranformer Attention cannot get Layers

### ISSUE THREAD

**Issue by ideaian** [tensorflow/models#6219]
I am trying to make `official/transformer` work with tf2.0 because I have not had been able to get it to work with previous versions of tf and I guess just wanted to add some pain to my life. 

### System information
`cat tf_env.txt`
```
== cat /etc/issue ===============================================
Darwin MacBook-Pro-5.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.14

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin MacBook-Pro-5.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                            1.16.1
protobuf                         3.6.1
tensorflow                       1.12.0
tensorflow-estimator-2.0-preview 1.14.0.dev2019021700

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
-bash: nvidia-smi: command not found

== cuda libs  ===================================================

== cat /etc/issue ===============================================
Darwin MacBook-Pro-5.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.14

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin MacBook-Pro-5.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                            1.16.1
protobuf                         3.6.1
tensorflow                       1.12.0
tensorflow-estimator-2.0-preview 1.14.0.dev2019021700

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
-bash: nvidia-smi: command not found

== cuda libs  ===================================================

== cat /etc/issue ===============================================
Darwin MacBook-Pro-5.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.14

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin MacBook-Pro-5.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                            1.16.1
protobuf                         3.6.1
tensorflow                       1.12.0
tensorflow-estimator-2.0-preview 1.14.0.dev2019021700

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
-bash: nvidia-smi: command not found

== cuda libs  ===================================================
```

#NOTE I could not get the version above using https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh
but I could this way: 

`python -c 'import tensorflow as tf; print(tf.__version__)'`
2.0.0-dev20190217
- **Exact command to reproduce**:

but also not this way

` python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'GIT_VERSION'

### Describe the problem

When running the command:
`... official/transformer$ python transformer_main.py --data_dir=/Users/ian/data/transformer_data/translate_ende/ --model_dir=test_output --vocab_file=/Users/ian/data/transformer_data/translate_ende/vocab.ende.33945 --param_set=big`
I get the error
```
Traceback (most recent call last):
  File "transformer_main.py", line 38, in <module>
    from official.transformer.model import transformer
  File "/Users/ian/git/cloned_repos/models-1/official/transformer/model/transformer.py", line 27, in <module>
    from official.transformer.model import attention_layer
  File "/Users/ian/git/cloned_repos/models-1/official/transformer/model/attention_layer.py", line 24, in <module>
    class Attention(tf.layers.Layer):
AttributeError: module 'tensorflow' has no attribute 'layers'
```

Replacing tensorflow.layers with tensorflow.keras and rerunning yields:
```
Traceback (most recent call last):
  File "transformer_main.py", line 38, in <module>
    from official.transformer.model import transformer
  File "/Users/ian/git/cloned_repos/models-1/official/transformer/model/transformer.py", line 27, in <module>
    from official.transformer.model import attention_layer
  File "/Users/ian/git/cloned_repos/models-1/official/transformer/model/attention_layer.py", line 24, in <module>
    class Attention(tf.keras.Layer):
AttributeError: module 'tensorflow.python.keras.api._v2.keras' has no attribute 'Layer'
```

Admittedly I am unskilled in debugging TF especially during version upgrades. Assistance would certainly be appreciated.

**Comment by robieta** [comment]
I believe reason that you're seeing the Attribute error around `tf.layers` is that those symbols are no longer being exported in 2.0. (There is still a compatibility API, so you should still be able to get to 1.x symbols using things like `tf.compat.v1.layers.Layer`.) The keras Attribute error is because you used `tf.keras.Layer` rather than `tf.keras.layers.Layer`. Note, however, that tf layers and keras layers are not interchangeable, so I'm not sure whether inheriting from `tf.keras.layers.Layer` will have the correct behavior.

**Comment by ideaian** [comment]
Awesome, thanks for explaining @robieta
