### ISSUE TITLE
how to preprocess the image just before the real training function?

### ISSUE THREAD

**Issue by lunasdejavu** [tensorflow/models#6226]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
windows 7x64
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
CUDA9.0
- **GPU model and memory**:
GTX1060 6G
- **Exact command to reproduce**:
python 3.6

I use the CLAHE algorithm to enhance the feature of the objects, but it has a drawback that it caused something similar to a grid on the image. I  always do the data augmentation first then do put the preprocessed image into the real training function so that the grid will become noise to the image instead of the feature. It is easier to implement by the customized project was written by Keras, but can someone tell me how to write it by tensorflow object detection API?

I just want to do something like :

```
image1 = data_augmentation (image0,rotate,reflect,.....)
image2 = CLAHE(image1)
train_per_step(image2....)
```
I found  the class_TrainingExecutor tensorflow\python\estimaotor\training.py
So I should modify the run()  or make another class just like lass_TrainingExecutor?

**Comment by lunasdejavu** [comment]
I thought I could add it in `create_input_queue()` in trainer.py:
```
tensor_dict[fields.InputDataFields.image] = tf.expand_dims(
      tensor_dict[fields.InputDataFields.image], 0)
```
turn it into :
```
     img_tensor = tensor_dict[fields.InputDataFields.image]
     sess = tf.Session()
     with sess.as_default():
         img_numpy = img_tensor.eval()
          img_tensor = tf.convert_to_tensor(CLAHE(img_numpy))
     tensor_dict[fields.InputDataFields.image] = tf.expand_dims(
      img_tensor, 0)
```
but there was an error:
Traceback (most recent call last):
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element.
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?], [?,?,3], [], [2], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/willysung/tf_od_api/models/research/object_detection/legacy/trainer.py", line 292, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/willysung/tf_od_api/models/research/object_detection/legacy/trainer.py", line 66, in create_input_queue
    CLAHE(img_tensor), 0)
  File "/home/willysung/tf_od_api/models/research/object_detection/legacy/trainer.py", line 97, in CLAHE
    image = img_tensor.eval()
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 713, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5157, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element.
         [[node IteratorGetNext (defined at train.py:121)  = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?], [?,?,3], [], [2], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

Caused by op 'IteratorGetNext', defined at:
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/willysung/tf_od_api/models/research/object_detection/legacy/trainer.py", line 292, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/willysung/tf_od_api/models/research/object_detection/legacy/trainer.py", line 63, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element.
         [[node IteratorGetNext (defined at train.py:121)  = IteratorGetNext[output_shapes=[[], [?], [?,4], [?], [?], [?], [?], [?], [?], [?,?,3], [], [2], []], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_BOOL, DT_FLOAT, DT_UINT8, DT_STRING, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

I really think if there is no more extension functions for tf.image,we need a easier way to exchange tensor to numpy.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
