### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'num_parallel_reads'

### ISSUE THREAD

**Issue by tong1101** [tensorflow/models#6271]
- **OS Platform and Distribution : Linux Ubuntu 16.04
- **TensorFlow installed from:anaconda3.5.2
- **TensorFlow version :tensorflow_gpu_1.6.0
- **Bazel version :
- **CUDA/cuDNN version**:cuda9.0,cudnn7.1.2
- **GPU model and memory:8G，NVIDIA GeForce1080

### Describe the problem
Traceback (most recent call last):

  File "<ipython-input-1-b437fe00277f>", line 1, in <module>
    runfile('/home/osea/deeplab1/train.py', wdir='/home/osea/deeplab1')

  File "/home/osea/anaconda3/envs/ten16/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/home/osea/anaconda3/envs/ten16/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/osea/deeplab1/train.py", line 499, in <module>
    tf.app.run()

  File "/home/osea/anaconda3/envs/ten16/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))

  File "/home/osea/deeplab1/train.py", line 451, in main
    dataset.get_one_shot_iterator(), dataset.num_of_classes,

  File "/home/osea/deeplab1/datasets/data_generator.py", line 323, in get_one_shot_iterator
    tf.data.TFRecordDataset(files, num_parallel_reads=self.num_readers)

TypeError: __init__() got an unexpected keyword argument 'num_parallel_reads'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
Exact command to reproduce

**Comment by YknZhu** [comment]
Thanks tong1101@! Could you update your tensorflow to the latest version? tf 1.6 doesn't support this argument.
