### ISSUE TITLE
deep_speech2 NanLossDuringTrainingError

### ISSUE THREAD

**Issue by neelakanth** [tensorflow/models#6296]
### System information
- **What is the top-level directory of the model you are using**:
https://github.com/tensorflow/models/tree/master/research/deep_speech
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No, using stock example from deep_speech2
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.0
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: V10.0.130
- **GPU model and memory**: GeForce GTX TITAN X, 12GB, Dual GPU
- **Exact command to reproduce**: Execute run_deep_speech.sh, configure the it to use lstm, bi -directional with rnn_hidden_size=1600 
Using Anaconda envirnoment

### Describe the problem
Hitting NanLossDuringTrainingError. Nor sure it's deep_speech2 bug or Tensorflow bug.

### Source code / logs
Full log attached

Below is the traceback
Traceback (most recent call last):
  File "/data/tf_git_1.12.0/models/research/deep_speech/deep_speech.py", line 455, in <module>
    absl_app.run(main)
  File "/home/exx/.local/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/exx/.local/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/data/tf_git_1.12.0/models/research/deep_speech/deep_speech.py", line 448, in main
    run_deep_speech(flags_obj)
  File "/data/tf_git_1.12.0/models/research/deep_speech/deep_speech.py", line 324, in run_deep_speech
    estimator.train(input_fn=input_fn_train, hooks=train_hooks)
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1143, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1368, in _train_model_distributed
    saving_listeners)
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/home/exx/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1215, in run
    run_metadata=run_metadata))
  File "/data/anaconda3/envs/deepspeech_gpu/lib/python3.5/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 635, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

[deepspeech2_nan.log](https://github.com/tensorflow/models/files/2922858/deepspeech2_nan.log)

**Comment by menon92** [comment]
Hello @neelakanth, Do you solve your problem ?
