### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:  Op type not registered 'ExperimentalMapAndBatchDataset' in binary running on n-6ca716a0-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

### ISSUE THREAD

**Issue by chenshaolong** [tensorflow/models#6300]
I wanted to fine-tuning with BERT. When I run the example code below it works properly.

python /home/schen/bert/run_classifier.py \
    --task_name=MRPC  \
    --do_train=true \
    --do_eval=true \
    --data_dir=/home/schen/glue/glue_data/MRPC \
    --vocab_file=/home/schen/bert/uncased_L-12_H-768_A-12/vocab.txt \
    --bert_config_file=/home/schen/bert/uncased_L-12_H-768_A-12/bert_config.json \
    --init_checkpoint=/home/schen/bert/uncased_L-12_H-768_A-12/bert_model.ckpt \
    --max_seq_length=128 \
    --train_batch_size=32 \
    --learning_rate=2e-5 \
    --num_train_epochs=3.0 \
    --output_dir=/tmp/mrpc_output/ 

However, when I tried to run on Cloud TPU with more flags as follow,

python /home/schen/bert/run_classifier.py \
    --task_name=MRPC  \
    --do_train=true \
    --do_eval=true \
    --data_dir=/home/schen/glue/glue_data/MRPC \
    --vocab_file=/home/schen/bert/uncased_L-12_H-768_A-12/vocab.txt \
    --bert_config_file=/home/schen/bert/uncased_L-12_H-768_A-12/bert_config.json \
    --init_checkpoint=/home/schen/bert/uncased_L-12_H-768_A-12/bert_model.ckpt \
    --max_seq_length=128 \
    --train_batch_size=32 \
    --learning_rate=2e-5 \
    --num_train_epochs=3.0 \
    --output_dir=/tmp/mrpc_output/ 
    --use_tpu=True \
    --tpu_name=ai

It gives me the error below:

tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Op type not registered 'ExperimentalMapAndBatchDataset' in binary running on n-6ca716a0-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

If I change the flag --output_dir=gs://gcs_bucket_name/bert/ where gcs_bucket_name is my project  Google Cloud Storage bucket name, it also gives me quite the same error:

tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'ExperimentalMapAndBatchDataset' in binary running on n-6ca716a0-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

I just followed the instructions from this link:

https://github.com/google-research/bert

FYI, if I run the command "ctpu st" it shows:

Your cluster is running!
	Compute Engine VM:  RUNNING
	Cloud TPU:          RUNNING

Any idea for fixed this bug? Thanks in advance.

**Comment by chenshaolong** [comment]
Here is the full information for the error:

Traceback (most recent call last):
  File "/home/schen/bert/run_classifier.py", line 981, in <module>
    tf.app.run()
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/schen/bert/run_classifier.py", line 880, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2457, in train
    rendezvous.raise_errors()
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2452, in train
    saving_listeners=saving_listeners)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model_default
    saving_listeners)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1403, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 508, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 934, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 648, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1122, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1127, in _create_session
    return self._sess_creator.create_session()
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 805, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 571, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 287, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/schen/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'ExperimentalMapAndBatchDataset' in binary running on n-6ca716a0-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by donatasrep** [comment]
I am facing the same problem, was not able to find any workaround. Did you manage to solve this?

**Comment by chenshaolong** [comment]
@donatasrep  No solution yet. Hope to get someone help me out here.

**Comment by donatasrep** [comment]
@chenshaolong, I managed to fix it by reinstalling tensorflow library. I have added --force-reinstall flag and specified exact tensorflow version (1.12, in my case). My guess is that I by accident updated tensorflow to 1.13. Anyway, I do not get these errors ever since.

**Comment by chenshaolong** [comment]
`pip install tensorflow==1.11.0 --force-reinstall` can fix the issue.

**Comment by the-data-guy** [comment]
I was getting this error while running the following command:
"gcloud beta ai-platform versions create"

Solution: I had chosen the wrong runtime-version. My TF version was 2.6.0 while the runtime-version specified was 2.1. As soon as I corrected it, the issue was fixed. See more details [here](gcloud beta ai-platform versions create).
