### ISSUE TITLE
error @ ssd_inception_v2_coco while running cmd on ubuntu 18.04 " python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_inception_v2_coco.config  " 

### ISSUE THREAD

**Issue by veesamkrao999** [tensorflow/models#6319]
WARNING:tensorflow:From /home/krao/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()

  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 574, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 631, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 654, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 676, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 801, in _MergeField
    merger(tokenizer, message, field)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 875, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 801, in _MergeField
    merger(tokenizer, message, field)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 875, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 801, in _MergeField
    merger(tokenizer, message, field)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 875, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/krao/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 768, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 135:1 : Message type "object_detection.protos.PostProcessing" has no field named "model".

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by veesamkrao999** [comment]
Thank you for your replay. I am sending the details as per request. Please let me know if you have any question. 

Thank you.  
----------------------------------------------------------------------------------------------------------------------------------
Have I written custom code ------>  Not written custom code. But included 42 objects from different         
                                                        images inoder to train the model. That is using labelImg.

OS Platform and Distribution----->    Linux and ubuntu 18.04, (8 GB Ram)

TensorFlow installed from -------->    Install TensorFlow CPU for Python 
                                                           That is --- pip install --ignore-installed --upgrade tensorflow==1.9

Bazel version-------------------------->  Not Installed.

CUDA/cuDNN version--------------->  Not Installed.

GPU model and memory------------> No GPU model and  
                                                       " /dev/sda11   194GB (total)  55GB(used)  129GB (Available)  30% "

Exact command to reproduce -----> python train.py --logtostderr --train_dir=training/       
                                                       --pipeline_config_path=training/ssd_inception_v2_coco.config

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
