### ISSUE TITLE
Training im2txt with TensorFlow r0.11

### ISSUE THREAD

**Issue by hholst80** [tensorflow/models#637]
I am following the instructions in `models/im2txt/README.md` and failing on the `Initial Training` step. 

```
(im2txt) hholst@fb-hholst3:/efs/models/im2txt$ /usr/bin/bazel version
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254
```

```
(im2txt) hholst@fb-hholst3:/efs/models/im2txt$ echo $MSCOCO_DIR $INCEPTION_CHECKPOINT $MODEL_DIR
/efs/models/im2txt/data/mscoco /efs/models/im2txt/data/inception_v3.ckpt /efs/models/im2txt/model
```

```
(im2txt) hholst@fb-hholst3:/efs/models$ bazel-bin/im2txt/train \
>   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256" \
>   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}" \
>   --train_dir="${MODEL_DIR}/train" \
>   --train_inception=false \
>   --number_of_steps=1000000
-bash: bazel-bin/im2txt/train: No such file or directory
(im2txt) hholst@fb-hholst3:/efs/models$ cd im2txt/
(im2txt) hholst@fb-hholst3:/efs/models/im2txt$ bazel-bin/im2txt/train   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=1000000
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
CRITICAL:tensorflow:Found no input files matching /efs/models/im2txt/data/mscoco/train-?????-of-00256
Traceback (most recent call last):
  File "/efs/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/home/hholst/anaconda3/envs/im2txt/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/efs/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/efs/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 352, in build
    self.build_inputs()
  File "/efs/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 153, in build_inputs
    num_reader_threads=self.config.num_input_reader_threads)
  File "/efs/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/inputs.py", line 98, in prefetch_input_data
    data_files, shuffle=True, capacity=16, name=shard_queue_name)
  File "/home/hholst/anaconda3/envs/im2txt/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 178, in string_input_producer
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor
(im2txt) hholst@fb-hholst3:/efs/models/im2txt$ 
```

**Comment by hholst80** [comment]
It looks like the 'Prepare the Training Data' step has failed to generate the required files.

**Comment by girving** [comment]
@hholst80 What happened when you tried to generate the files it complains about not having?

**Comment by sunnyzxf** [comment]
I want to know how much time will the evaluate.py run. I set the "number_of_steps"=5000,but the evaluate.py has run over 5000 steps. I don't know when it will finish the process of training.

**Comment by michaelisard** [comment]
Closing due to lack of response.

**Comment by withyou1771** [comment]
I have encountered this problem. How did you solve the problem?

**Comment by tylertroy** [comment]
I encountered this problem and I _think_ my issue was that I had an extra backslash where I oughtn't in the bash directory variables. Specifically the $MSCOCO_DIR variable.

**Comment by j2233ack** [comment]
I also encountered the same problem, if you have a solution, can you teach me? Thank you~
