### ISSUE TITLE
Preparing data im2txt in TensorFlow 0.11.0

### ISSUE THREAD

**Issue by hholst80** [tensorflow/models#638]
I am using TensorFlow 0.11; Bazel 0.4.0 and Python 2.7 and following the instructions at `Show and Tell: A Neural Image Caption Generator`.

Specifically, at the step `Prepare the Training Data` I get the following error:

```
hholst@fb-hholst3:/efs/models/im2txt$ cat /efs/im2txt.envs 
export MSCOCO_DIR="/efs/models/im2txt/data/mscoco"
export INCEPTION_CHECKPOINT="/efs/models/im2txt/data/inception_v3.ckpt"
export MODEL_DIR="/efs/models/im2txt/model"
hholst@fb-hholst3:/efs/models/im2txt$ source /efs/im2txt.envs 
hholst@fb-hholst3:/efs/models/im2txt$ bazel build im2txt/download_and_preprocess_mscoco
INFO: Found 1 target...
Target //im2txt:download_and_preprocess_mscoco up-to-date:
  bazel-bin/im2txt/download_and_preprocess_mscoco
INFO: Elapsed time: 0.220s, Critical Path: 0.00s
hholst@fb-hholst3:/efs/models/im2txt$ bazel-bin/im2txt/download_and_preprocess_mscoco "${MSCOCO_DIR}"
Skipping download of train2014.zip
Unzipping train2014.zip
Skipping download of val2014.zip
Unzipping val2014.zip
Skipping download of captions_train-val2014.zip
Unzipping captions_train-val2014.zip
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/efs/models/im2txt/bazel-bin/im2txt/download_and_preprocess_mscoco.runfiles/im2txt/im2txt/data/build_mscoco_data.py", line 100, in <module>
    import tensorflow as tf
  File "/home/hholst/anaconda3/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/hholst/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/hholst/anaconda3/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/home/hholst/anaconda3/lib/python3.5/site-packages/google/protobuf/descriptor_pb2.py", line 964, in <module>
    options=None),
  File "/home/hholst/anaconda3/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 505, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package"
hholst@fb-hholst3:/efs/models/im2txt$
```

**Comment by hholst80** [comment]
INVALID.
