### ISSUE TITLE
object_detection:

### ISSUE THREAD

**Issue by RADHI18** [tensorflow/models#6388]
I'm using Windows 10, Python 3.7.2 and Tensorflow 1.13.0-rc2 , I am getting this error while trying to run train.py

WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 92, in main
    configs = config_util.get_configs_from_pipeline_file(FLAGS.pipeline_config_path)
  File "C:\tensorflow1\models\research\object_detection\utils\config_util.py", line 97, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: training/faster_rcnn_inception_v2_pets.config﻿ : Le fichier sp\udce9cifi\udce9 est introuvable.
; No such file or directory
please help me ! how can solve this problem？

**Comment by JoseGnRLuis** [comment]
do you have the file in training/faster_rcnn_inception_v2_pets.config﻿?

copy to your training config from /object_detection/samples/config/faster_rcnn_inception_v2_pets.config﻿ or https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_inception_v2_pets.config

then configure fine_tune_checkpoint, input_path and label_map_path from both train_input_reader and eval_input_reader

**Comment by RADHI18** [comment]
yes i have ! but i dont know whats the problem!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
