### ISSUE TITLE
unable to convert ssd_mobilenet_v2_oid frozen_inference_graph.pb to .tflite 

### ISSUE THREAD

**Issue by MitPatel971997** [tensorflow/models#6432]
### System information
- **What is the top-level directory of the model you are using**:
ssd_mobilenet_v2_oid_v4_2018_12_12
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.12.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
tflite_convert --graph_def_file=ssd_mobilenet_v2_oid_v4_2018_12_12/frozen_inference_graph.pb --input_format=TENSORFLOW_GRAPHDEF --output_file=demo.tflite --input_shape=1,300,300,3 --input_array=image_tensor --output_array=detection_boxes,detection_scores,num_detections,detection_classes

### Source code / logs
Traceback (most recent call last):
  File "/home/uadmin/Projects/Model_Conversion/venv/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/home/uadmin/Projects/Model_Conversion/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/uadmin/Projects/Model_Conversion/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/uadmin/Projects/Model_Conversion/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/home/uadmin/Projects/Model_Conversion/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 162, in _convert_model
    output_data = converter.convert()
  File "/home/uadmin/Projects/Model_Conversion/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 453, in convert
    **converter_kwargs)
  File "/home/uadmin/Projects/Model_Conversion/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert.py", line 342, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/uadmin/Projects/Model_Conversion/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert.py", line 135, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.

**Comment by alanchiao** [comment]
Did you get the ssd model from somewhere? If yes, could you point us to it?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
