### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'batch_gather'

### ISSUE THREAD

**Issue by Ishwar24** [tensorflow/models#6440]
WARNING:tensorflow:From /home/somesh/tensorflow01/models/research/object_detection/predictors/heads/box_head.py:93: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "export_inference_graph.py", line 156, in <module>
    tf.app.run()
  File "/home/somesh/anaconda3/envs/tensorflowenv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 152, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/somesh/tensorflow01/models/research/object_detection/exporter.py", line 465, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/somesh/tensorflow01/models/research/object_detection/exporter.py", line 368, in _export_inference_graph
    graph_hook_fn=graph_hook_fn)
  File "/home/somesh/tensorflow01/models/research/object_detection/exporter.py", line 335, in build_detection_graph
    output_collection_name=output_collection_name)
  File "/home/somesh/tensorflow01/models/research/object_detection/exporter.py", line 314, in _get_outputs_from_inputs
    output_tensors, true_image_shapes)
  File "/home/somesh/tensorflow01/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1180, in postprocess
    mask_predictions=mask_predictions)
  File "/home/somesh/tensorflow01/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1643, in _postprocess_box_classifier
    raw_detection_boxes = tf.squeeze(tf.batch_gather(refined_decoded_boxes_batch, class_ids), axis=2)
AttributeError: module 'tensorflow' has no attribute 'batch_gather'

**Comment by OmorFarukRakib** [comment]
I am facing the same problem :( stuck in here for a so long time.

**Comment by SHADOWMOOON** [comment]
I am also facing this problem when I run the expot_inference_graph.py. MY tensorflow-gpu is 1.9.0

**Comment by Ishwar24** [comment]
Hey Guys I found the solution @SHADOWMOOON and @OmorFarukRakib . I am also using tensorflow 1.9 its not working but when I am update my tensorflow to 1.13 its work perfectly and shows as expected result.

**Comment by eamonnkenny** [comment]
I'm using tensorflow 2.0.0. I get the same error as above. And whats interesting is that I'm using Mask_RCNN where the problem does not occur with 1 GPU. It only occurs if using 2 or more.
