### ISSUE TITLE
InvalidArgumentError (see above for traceback): padded_shape[0]=257 is not divisible by block_shape[0]=2

### ISSUE THREAD

**Issue by lxs802lxs8858** [tensorflow/models#6515]
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting evaluation at 2019-04-03-13:08:05
Traceback (most recent call last):
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=257 is not divisible by block_shape[0]=2
	 [[Node: xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND = SpaceToBatchND[T=DT_FLOAT, Tblock_shape=DT_INT32, Tpaddings=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](xception_65/exit_flow/block1/unit_1/xception_module/add-0-0-TransposeNCHWToNHWC-LayoutOptimizer, xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND/block_shape, xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND/paddings)]]
	 [[Node: mean_iou/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch/_4465 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2128_...ert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deeplab/eval.py", line 179, in <module>
    tf.app.run()
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/eval.py", line 172, in main
    eval_interval_secs=FLAGS.eval_interval_secs)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/evaluation.py", line 449, in evaluate_repeatedly
    session.run(eval_ops, feed_dict)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 577, in run
    run_metadata=run_metadata)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1053, in run
    run_metadata=run_metadata)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1144, in run
    raise six.reraise(*original_exc_info)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1129, in run
    return self._sess.run(*args, **kwargs)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1201, in run
    run_metadata=run_metadata)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 981, in run
    return self._sess.run(*args, **kwargs)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=257 is not divisible by block_shape[0]=2
	 [[Node: xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND = SpaceToBatchND[T=DT_FLOAT, Tblock_shape=DT_INT32, Tpaddings=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](xception_65/exit_flow/block1/unit_1/xception_module/add-0-0-TransposeNCHWToNHWC-LayoutOptimizer, xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND/block_shape, xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND/paddings)]]
	 [[Node: mean_iou/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch/_4465 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2128_...ert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND', defined at:
  File "deeplab/eval.py", line 179, in <module>
    tf.app.run()
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/eval.py", line 118, in main
    image_pyramid=FLAGS.image_pyramid)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/model.py", line 183, in predict_labels
    fine_tune_batch_norm=True)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/model.py", line 313, in multi_scale_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/model.py", line 553, in _get_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/model.py", line 395, in extract_features
    use_bounded_activation=model_options.use_bounded_activation)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/feature_extractor.py", line 341, in extract_features
    scope=name_scope[model_variant])
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/feature_extractor.py", line 408, in network_fn
    *args, **kwargs)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/xception.py", line 655, in xception_65
    scope=scope)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/xception.py", line 464, in xception
    net = stack_blocks_dense(net, blocks, output_stride)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/xception.py", line 379, in stack_blocks_dense
    net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/xception.py", line 293, in xception_module
    scope='separable_conv' + str(i+1))
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/xception.py", line 284, in _separable_conv
    scope=scope)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/xception.py", line 185, in separable_conv2d_same
    outputs = _split_separable_conv2d(padding='SAME')
  File "/home/kt210/Person/amy/deeplab/models-master/research/deeplab/core/xception.py", line 175, in _split_separable_conv2d
    **kwargs)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2810, in separable_convolution2d
    data_format=data_format)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 461, in depthwise_conv2d
    op=op)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 364, in with_space_to_batch
    return new_op(input, None)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 503, in _with_space_to_batch_call
    input=inp, block_shape=dilation_rate, paddings=paddings)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7570, in space_to_batch_nd
    paddings=paddings, name=name)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/kt210/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): padded_shape[0]=257 is not divisible by block_shape[0]=2
	 [[Node: xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND = SpaceToBatchND[T=DT_FLOAT, Tblock_shape=DT_INT32, Tpaddings=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](xception_65/exit_flow/block1/unit_1/xception_module/add-0-0-TransposeNCHWToNHWC-LayoutOptimizer, xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND/block_shape, xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND/paddings)]]
	 [[Node: mean_iou/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch/_4465 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2128_...ert/Switch", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by lxs802lxs8858** [comment]
> 谢谢你的文章。我们注意到您尚未在问题模板中填写以下字段。如果它们与您的情况相关，或者将它们保留为N / A，您能否更新它们？谢谢。
> 什么是您正在使用的模型的顶级目录
> 我是否已编写自定义代码
> OS平台和分发
> TensorFlow从
> TensorFlow版本安装
> Bazel版本
> CUDA / cuDNN版本
> GPU模型和内存
> Exact命令重现
tensorflow.python.framework.errors_impl.InvalidArgumentError：padded_shape [0] = 257不能被block_shape整除[0] = 2

**Comment by northeastsquare** [comment]
try change train_crop_size, bigger

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
