### ISSUE TITLE
[Object_detection]  RuntimeError: Coordinator stopped with threads still running

### ISSUE THREAD

**Issue by MassonAntoine** [tensorflow/models#6566]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Exact command to reproduce**: N/A

### Describe the problem
I'm new to Tensorflow and every time I trained my model, it ends with the error :
RuntimeError: Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany

I use the ssd_mobilenet_v1_fpn_shared_box_predictor as model. To train it, I execute the legacy/train.py script. I train my model since 1 month and this error appears only until now.

### Source code / logs
It happens just after Tensorflow save the checkpoint

```INFO:tensorflow:Stopping Training.
I0412 11:09:09.962124 139983862277952 tf_logging.py:115] Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
I0412 11:09:09.962288 139983862277952 tf_logging.py:115] Finished training! Saving model to disk.
Traceback (most recent call last):
  File "object_detection/train.py", line 184, in <module>
    tf.app.run()
  File "/home/ant/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ant/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "object_detection/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/legacy/trainer.py", line 415, in train
    saver=saver)
  File "/home/ant/.local/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 785, in train
    ignore_live_threads=ignore_live_threads)
  File "/home/ant/.local/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 832, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/ant/.local/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 397, in join
    " ".join(stragglers))
RuntimeError: Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany```

Does anyone have an idea ?

**Comment by MassonAntoine** [comment]
Well, it seems I've temporarily fix it:
I just deleted the line NUM_STEPS: in my pipeline config file.

It now save me a checkpoint every 25 steps.

**Comment by walter040422** [comment]
Hi friend, I met with the same question. I deleted the line NUM_STEPS: in my pipeline config file, but it will not stop. How about you?

**Comment by MassonAntoine** [comment]
Here is the first thread I've been looking. It might help a bit: #20833
However can you precise more, to see if I can reproduce you error.

**Comment by shnamin** [comment]
I get this when I am saving the mobilenetv3 model I have retrained. has anyone found how to resolve it?
