### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.distribute' has no attribute 'experimental'

### ISSUE THREAD

**Issue by jeffsaremi** [tensorflow/models#6610]
Trying to execute one of the models (mnist) under the tensorflow/models

```
(tf3.6) D:\repos\tf-models\official\mnist>set PYTHONPATH=D:\repos\tf-models

(tf3.6) D:\repos\tf-models\official\mnist>python mnist.py --export_dir /temo/mnist_model
Traceback (most recent call last):
  File "mnist.py", line 27, in <module>
    from official.utils.misc import distribution_utils
  File "D:\repos\tf-models\official\utils\misc\distribution_utils.py", line 28, in <module>
    None: tf.distribute.experimental.CollectiveCommunication.AUTO,
AttributeError: module 'tensorflow._api.v1.distribute' has no attribute 'experimental'
```
This is the output of pip list:

```
(tf3.6) D:\repos\tf-models\official\mnist>pip list
Package                  Version  Location
------------------------ -------- ------------------------
absl-py                  0.7.1
astor                    0.7.1
cachetools               3.1.0
certifi                  2019.3.9
chardet                  3.0.4
gast                     0.2.2
google-api-core          1.9.0
google-api-python-client 1.7.8
google-auth              1.6.3
google-auth-httplib2     0.0.3
google-cloud-bigquery    1.11.2
google-cloud-core        0.29.1
google-resumable-media   0.3.2
googleapis-common-protos 1.5.9
grpcio                   1.20.0
h5py                     2.9.0
httplib2                 0.12.1
idna                     2.8
kaggle                   1.5.3
Keras-Applications       1.0.7
Keras-Preprocessing      1.0.9
Markdown                 3.1
mlperf-compliance        0.0.10
mock                     2.0.0
numpy                    1.16.2
oauth2client             4.1.3
onnx                     1.4.1
onnxruntime              0.3.0
pandas                   0.24.2
pbr                      5.1.3
pip                      19.0.3
protobuf                 3.7.1
psutil                   5.6.1
py-cpuinfo               5.0.0
pyasn1                   0.4.5
pyasn1-modules           0.2.4
python-dateutil          2.8.0
python-slugify           3.0.2
pytz                     2019.1
requests                 2.21.0
rsa                      4.0
scipy                    1.2.1
setuptools               41.0.0
six                      1.12.0
tensorboard              1.13.1
tensorflow               1.13.1
tensorflow-estimator     1.13.0
termcolor                1.1.0
text-unidecode           1.2
tqdm                     4.31.1
typing                   3.6.6
typing-extensions        3.7.2
uritemplate              3.0.0
urllib3                  1.24.2
Werkzeug                 0.15.2
wheel                    0.33.1
wincertstore             0.2
```

OS: Windows 10

**Comment by jeffsaremi** [comment]
The advice here solved this issue:

https://github.com/tensorflow/models/issues/6466
