### ISSUE TITLE
 [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jesaremi\\AppData\\Local\\Temp\\tmpq5grc6ru.gz'

### ISSUE THREAD

**Issue by jeffsaremi** [tensorflow/models#6614]
Trying to run the mnist model on Windows 10, Python 3.6, TensorFlow 1.13.1
I get this:
```
(tf3.6) D:\repos\tf-models\official\mnist>python mnist.py
2019-04-19 08:41:53.283512: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

I0419 08:41:53.995170 40172 run_config.py:532] Initializing RunConfig with distribution strategies.
I0419 08:41:53.995170 40172 estimator_training.py:166] Not using Distribute Coordinator.
I0419 08:41:53.996170 40172 estimator.py:201] Using config: {'_model_dir': '/tmp/mnist_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.one_device_strategy.OneDeviceStrategy object at 0x0000022F13DE19B0>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000022F13DE1B38>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': None}
Downloading https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz to C:\Users\jesaremi\AppData\Local\Temp\tmpq5grc6ru.gz
Traceback (most recent call last):
  File "mnist.py", line 235, in <module>
    absl_app.run(main)
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "mnist.py", line 229, in main
    run_mnist(flags.FLAGS)
  File "mnist.py", line 211, in run_mnist
    mnist_classifier.train(input_fn=train_input_fn, hooks=train_hooks)
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1122, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1185, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1206, in _actual_train_model_distributed
    input_fn, model_fn_lib.ModeKeys.TRAIN, strategy)
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 981, in _get_iterator_from_input_fn
    lambda: self._call_input_fn(input_fn, mode))
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 364, in distribute_dataset
    return self._extended._distribute_dataset(dataset_fn)  # pylint: disable=protected-access
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow\contrib\distribute\python\one_device_strategy.py", line 78, in _distribute_dataset
    self._call_dataset_fn(dataset_fn), [self._device])
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1064, in _call_dataset_fn
    result = dataset_fn()
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 981, in <lambda>
    lambda: self._call_input_fn(input_fn, mode))
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\tf3.6\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1079, in _call_input_fn
    return input_fn(**kwargs)
  File "mnist.py", line 192, in train_input_fn
    ds = dataset.train(flags_obj.data_dir)
  File "D:\repos\tf-models\official\mnist\dataset.py", line 112, in train
    'train-labels-idx1-ubyte')
  File "D:\repos\tf-models\official\mnist\dataset.py", line 85, in dataset
    labels_file = download(directory, labels_file)
  File "D:\repos\tf-models\official\mnist\dataset.py", line 77, in download
    os.remove(zipped_filepath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jesaremi\\AppData\\Local\\Temp\\tmpq5grc6ru.gz'

```

It's very reproducible

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rootkitchao** [comment]
Try to restart your system may slove this problem.

**Comment by jeffsaremi** [comment]
The problem seems to have corrected itself after a reboot.
