### ISSUE TITLE
#TEXTSUM# Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found

### ISSUE THREAD

**Issue by xtr33me** [tensorflow/models#669]
I was using the Textsum model with TF 0.9 since I previously was having issues with 0.11. I trained Textsum against 1.3 million articles and my outputted results were in the standard log_root folder.  I recently have been trying to figure out how to use tensorflow_serving and was having problems when trying to import the exporter. After further analysis I found that 0.9 did not have this so I was forced to upgrade to 0.11.  0.11 does not provide any of the problems I was seeing previously, which is great however I am getting the above error in the title now when I try to perform "eval" or "decode" on data trained with TF 0.9.  Is there anything I can do or do I need to retrain everything in 0.11 to use the data?

I have pasted the long response I am getting when attempting to eval with 0.11 version agasint the data trained in 0.9.  Any ideas? I am currently using Ubuntu 16.04, Cuda 8, cudnn 5 and TF 0.11.

> 
> I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
> name: GeForce GTX 980M
> major: 5 minor: 2 memoryClockRate (GHz) 1.1265
> pciBusID 0000:01:00.0
> Total memory: 7.93GiB
> Free memory: 7.88GiB
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980M, pci bus id: 0000:01:00.0)
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> W tensorflow/core/framework/op_kernel.cc:968] Not found: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> Traceback (most recent call last):
>   File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 200, in main
>     _Eval(model, batcher, vocab=vocab)
>   File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 139, in _Eval
>     saver.restore(sess, ckpt_state.model_checkpoint_path)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1345, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
>     feed_dict_string, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
>     target_list, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors.NotFoundError: Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> 	 [[Node: save/restore_slice_3/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_164_save/restore_slice_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
> 
> Caused by op u'save/restore_slice_27', defined at:
>   File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 200, in main
>     _Eval(model, batcher, vocab=vocab)
>   File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 121, in _Eval
>     saver = tf.train.Saver()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 986, in __init__
>     self.build()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1015, in build
>     restore_sequentially=self._restore_sequentially)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 620, in build
>     restore_sequentially, reshape)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 357, in _AddRestoreOps
>     tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 270, in restore_op
>     preferred_shard=preferred_shard))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 204, in _restore_slice
>     preferred_shard, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
>     preferred_shard=preferred_shard, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
>     self._traceback = _extract_stack()
> 
> NotFoundError (see above for traceback): Tensor name "seq2seq/encoder3/BiRNN/FW/LSTMCell/W_0" not found in checkpoint files textsum/log_root/model.ckpt-249630
> 	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
> 	 [[Node: save/restore_slice_3/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_164_save/restore_slice_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
>

**Comment by xtr33me** [comment]
After looking further at the notes for 0.11, it seems that the checkpoint format was changed and this seems to be the source to this problem. I believe that if a model was trained with an older version of TF, such as 0.9 it will not be compatible with 0.11.  I retrained over the past week using 0.11 and everything seems to be working fine so I will close this as the answer. Should anyone know if you can use older trained data from 0.9 in 0.11 without retraining, I would love to know how just for knowledge purposes.
