### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'

### ISSUE THREAD

**Issue by Muguangfeng** [tensorflow/models#6701]
According to readme in the models/research/efficient-hrl folder, I run:
python scripts/local_train.py test1 hiro_orig ant_maze base_uvf suite

but it tells the problem:
"AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'' 
This is on tensorflow 1.12.0

if I change the version of tensorflow, it will be other questions ：
AttributeError: module 'tensorflow.io' has no attribute 'gfile'    (tf1.11.0)

AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'   (tf1.13.1)

AttributeError: module 'tensorflow' has no attribute 'io'    (tf1.5.0)
Does anyone know how to solve it?
Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Muguangfeng** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using  --/home
Have I written custom code --no
OS Platform and Distribution --ubuntu16.04 LTS
TensorFlow installed from --pip or conda
TensorFlow version  --tensorflow 1.12.0 , other versions have also been tried.
Bazel version  --not clear
CUDA/cuDNN version  --CUDA9.0 , cuDNN7.1
GPU model and memory  --Two TITAN Xp, 12196MiB，I use tensorflow(not tensorflow-gpu), If necessary, I can also use tensorflow-gpu
Exact command to reproduce  --Don't quite understand this.

https://github.com/tensorflow/models/tree/master/research/efficient-hrl
Run command:
python scripts/local_train.py test1 hiro_orig ant_maze base_uvf suite
Then the above error will occur.

**Comment by Muguangfeng** [comment]
Now, I installed tensorflow1.13.1 by running:
pip install tensorflow==1.13.1
In this way, the code can run more, reach line 29 of run_train.py. But it still occurs error.
`Traceback (most recent call last):
  File ".//run_train.py", line 29, in <module>
    import train
  File "/home/yang/models-master/research/efficient-hrl/train.py", line 33, in <module>
    import agent as agent_
  File "/home/yang/models-master/research/efficient-hrl/agent.py", line 21, in <module>
    from agents import ddpg_agent
  File "/home/yang/models-master/research/efficient-hrl/agents/ddpg_agent.py", line 28, in <module>
    from utils import utils
  File "/home/yang/models-master/research/efficient-hrl/utils/utils.py", line 26, in <module>
    from tf_agents.utils import common
  File "/home/yang/.local/lib/python3.6/site-packages/tf_agents/utils/__init__.py", line 18, in <module>
    from tf_agents.utils import common
  File "/home/yang/.local/lib/python3.6/site-packages/tf_agents/utils/common.py", line 27, in <module>
    from tf_agents.trajectories import time_step as ts
  File "/home/yang/.local/lib/python3.6/site-packages/tf_agents/trajectories/__init__.py", line 20, in <module>
    from tf_agents.trajectories import trajectory
  File "/home/yang/.local/lib/python3.6/site-packages/tf_agents/trajectories/trajectory.py", line 30, in <module>
    from tf_agents.utils import nest_utils
  File "/home/yang/.local/lib/python3.6/site-packages/tf_agents/utils/nest_utils.py", line 28, in <module>
    flatten_with_tuple_paths = nest.flatten_with_tuple_paths
AttributeError: module 'tensorflow.python.util.nest' has no attribute 'flatten_with_tuple_paths'`
Anyone know why?

**Comment by Muguangfeng** [comment]
Now, I installed tensorflow1.12.0 by running:
pip install tensorflow==1.12.0
In this way, the code can run more, reach line 29 of run_train.py. But it still occurs error.

`

Traceback (most recent call last):
  File ".//run_train.py", line 49, in <module>
    tf.app.run()
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File ".//run_train.py", line 45, in main
    return train.train_uvf(FLAGS.train_dir)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/gin/config.py", line 979, in wrapper
    new_kwargs = copy.deepcopy(new_kwargs)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/gin/config.py", line 336, in __deepcopy__
    return self._scoped_configurable_fn()
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/gin/config.py", line 261, in scoping_wrapper
    return fn(*args, **kwargs)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/yang/.conda/envs/hiro/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/yang/models-master/research/efficient-hrl/agents/circular_buffer.py", line 50, in __init__
    self._num_adds_cs = tf.contrib.framework.CriticalSection(name='num_adds')
AttributeError: module 'tensorflow.contrib.framework' has no attribute 'CriticalSection'
  In call to configurable 'CircularBuffer' (<function CircularBuffer.__init__ at 0x7f025157f2f0>) in scope 'agent'

`
Anyone know how to solve it?

**Comment by axnedergaard** [comment]
Modify line 50 in file agents/circular_buffer.py:

`self._num_adds_cs = tf.CriticalSection(name='num_adds')`

to

`self._num_adds_cs = tf.contrib.framework.CriticalSection(name='num_adds')`

**Comment by albingit70** [comment]
Hello, I got same error when I run tensorflow 1.9.0.
I am trying to run tensorflow object detection api, but it is not loading graph.
There is the code:
```
    with detection_graph_below.as_default():
        od_graph_def = tf.GraphDef()
        with tf.io.gfile.GFile(PATH_TO_CKPT_BELOW, 'rb') as fid:
            serialized_graph = fid.read()
            od_graph_def.ParseFromString(serialized_graph)
            tf.import_graph_def(od_graph_def, name='')
```

And the error message:
```
with tf.io.gfile.GFile(PATH_TO_CKPT_BELOW, 'rb') as fid:
AttributeError: module 'tensorflow' has no attribute 'io'
```

What is the solution?
Thank you

**Comment by jayesh0vasudeva** [comment]
hello, I am getting the same error when I run the tensorflow 2.0.
I am trying to load the inception model, but it is not loading.

OS platform and distribution: macOS catalina v0.15.2
Tensorflow installed from: pip3
tensorflow version: 2.0
bazel version: unclear
CUDA/cuDNN version: CPU
GPU: NA
code snippet:
`            with tf.io.gfile.FastGFile(path, 'rb') as file:
`
and the error message:
`AttributeError: module 'tensorflow_core._api.v2.io.gfile' has no attribute 'FastGFile'`
how to solve this?
Thank you
regards
jayesh

**Comment by jayesh0vasudeva** [comment]
`
yo`

**Comment by rbtirumala** [comment]
same error as above. Haven't found resolution yet

**Comment by ellcs** [comment]
Maybe using `tf.compat.v1.gfile.FastGFile` instead of `tf.gfile.FastGFile` resolves your issue. It's just a guess :)

https://www.tensorflow.org/api_docs/python/tf/compat/v1/gfile/FastGFile

**Comment by ofirnachum** [comment]
I will respond to the original query from Muguangfeng (the other issues I am not sure on and may be best created as separate issues).
It seems the underlying issue is with CriticalSection, and the fact that the alias for it has changed in tf1.12. 
Try replacing that call with tf.CriticalSection and see what happens.

**Comment by sanaz-rasti** [comment]
GYUS!
For tensorflow-gpu=2.2 

I replaced this: 
{
detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')
} 
with: 
{
detection_graph = tf.compat.v1.Graph()
with detection_graph.as_default():
  od_graph_def = tf.compat.v1.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')
}

And it is working perfect!
