### ISSUE TITLE
im2txt error: Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by Saeid-Balaneshinkordan** [tensorflow/models#671]
Given this [Panorama image](https://upload.wikimedia.org/wikipedia/commons/6/69/Independence_Mall_Panorama.jpg) as one of the input_files of im2txt, I get the following error:

Invalid SOS parameters for sequential JPEG
Input file read error.

My program uses PIL's Image.load() to check if downloaded images are not corrupt before submitting them to im2txt. I can open, display and load this image by using Pillow's Image Module w/o any warning. It's format is JPEG and it's size is 9392x2128, which seems acceptable. 

```
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
Invalid SOS parameters for sequential JPEG
Input file read error
Traceback (most recent call last):
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 84, in <module>
    tf.app.run()
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 73, in main
    captions = generator.beam_search(sess, image)
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/caption_generator.py", line 142, in beam_search
    initial_state = self.model.feed_image(sess, encoded_image)
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_wrapper.py", line 41, in feed_image
    feed_dict={"image_feed:0": encoded_image})
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data, size 8773168
	 [[Node: decode/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_image_feed_0)]]

Caused by op u'decode/DecodeJpeg', defined at:
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 84, in <module>
    tf.app.run()
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 49, in main
    FLAGS.checkpoint_path)
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 115, in build_graph_from_config
    self.build_model(model_config)
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_wrapper.py", line 36, in build_model
    model.build()
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 352, in build
    self.build_inputs()
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 138, in build_inputs
    images = tf.expand_dims(self.process_image(image_feed), 0)
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 119, in process_image
    image_format=self.config.image_format)
  File "/home/fj9124/projects/ir/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py", line 100, in process_image
    image = tf.image.decode_jpeg(encoded_image, channels=3)
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 311, in decode_jpeg
    name=name)
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2259, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/fj9124/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1130, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Invalid JPEG data, size 8773168
	 [[Node: decode/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_image_feed_0)]]
```

**Comment by cshallue** [comment]
Sounds like the file is formatted in such a way that the TensorFlow JPEG parsing op can't read it. You'll probably need to re-encode the file.

On a side note, the im2txt model is probably not going to work well on very wide/tall images, since it's going to resize the image into a square and it's going to end up very squashed.

**Comment by Saeid-Balaneshinkordan** [comment]
@cshallue Thank you very much for the reply! I will try to re-encode my images and find a way to deal with tall/wide images.
