### ISSUE TITLE
Inception fails to train on custom image dataset with TypeError: ones_initializer() got multiple values for keyword argument 'dtype'

### ISSUE THREAD

**Issue by anujsharma1** [tensorflow/models#672]
Hi,
I am getting TypeError while training inception on my custom dataset.
I have followed README of inception model, and am trying to train inception from scratch on my custom image dataset (500 images of 299*299 RGB not pre-processed in any other form, 4 labels).

1) I converted images into TFRecord files inside **data_dir=/home/airig/data_dir** 
2) Conversion done using [build_image_data.py](https://github.com/tensorflow/models/blob/master/inception/inception/data/build_image_data.py)
3) Have put label.txt file at /home/airig/data_labels/labels.txt
4) data_dir=/home/airig/data_dir contains :---
**train-00000-of-00002  train-00001-of-00002  validation-00000-of-00002  validation-00001-of-00002**
5) **train_dir=/tmp/imagenet_train** is empty
6) **I am using Python2.7 for TF and sys default**

When I try running imagenet_train, it results in error :---- 
```
airig@airig-Inspiron-7559:~/done/tensorflow/models/inception$ **bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=8 --train_dir=/tmp/imagenet_train --data_dir=/home/airig/data_dir**
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
['/home/airig/data_dir/train-00000-of-00002', '/home/airig/data_dir/train-00001-of-00002']  >>>>  /tmp/imagenet_train
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.variable_op_scope(values, name, default_name) is deprecated, use tf.variable_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.variable_op_scope(values, name, default_name) is deprecated, use tf.variable_scope(name, default_name, values)
Traceback (most recent call last):
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 42, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 38, in main
    inception_train.train(dataset)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 239, in train
    scope)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 108, in _tower_loss
    scope=scope)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_model.py", line 87, in inference
    scope=scope)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/inception_model.py", line 87, in inception_v3
    scope='conv0')
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/ops.py", line 234, in conv2d
    outputs = batch_norm(conv, **batch_norm_params)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/ops.py", line 111, in batch_norm
    collections=moving_collections)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/scopes.py", line 155, in func_with_args
    return func(*args, **current_args)
  File "/home/airig/done/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/variables.py", line 289, in variable
    trainable=trainable, collections=collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
**TypeError: ones_initializer() got multiple values for keyword argument 'dtype'**
```

**Why am I getting this error?Please help.**

**Comment by anujsharma1** [comment]
Reproduced at [an issue here](https://github.com/tensorflow/tensorflow/issues/5742)

Please provide way ahead..

**Comment by shlens** [comment]
@itsmeolivia Would you be able to port the API changes in [cfb2280](https://github.com/tensorflow/tensorflow/commit/cfb2280d3f6ced298681bd1141479a59a06abde8) into the inception model too? This seems to be the issue behind [here](https://github.com/tensorflow/tensorflow/issues/5742)
