### ISSUE TITLE
Error running train.py from lstm_object_detetcion

### ISSUE THREAD

**Issue by Aaronreb** [tensorflow/models#6777]
Getting this following error while running train.py from lstm_object_detection.

Traceback (most recent call last):
  File "lstm_object_detection/train.py", line 185, in <module>
    tf.app.run()
  File "/home/kt-ml1/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "lstm_object_detection/train.py", line 94, in main
    FLAGS.pipeline_config_path)
  File "/home/kt-ml1/models-master/models-master/research/lstm_object_detection/utils/config_util.py", line 46, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/kt-ml1/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 574, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/kt-ml1/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 631, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/kt-ml1/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 654, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/kt-ml1/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 676, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/kt-ml1/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    'that message\'s _pb2 module must be imported as well' % name)
google.protobuf.text_format.ParseError: 18:26 : Extension "object_detection.protos.lstm_model" not registered. Did you import the _pb2 module which defines it? If you are trying to place the extension in the MessageSet field of another message that is in an Any or MessageSet field, that message's _pb2 module must be imported as well

**Comment by matt-virgo** [comment]
I'm getting the same issue when trying to train on a data set of still images. not sure if that's causing the issue though

**Comment by Aaronreb** [comment]
> I'm getting the same issue when trying to train on a data set of still images. not sure if that's causing the issue though

Replace object_detection.protos.lstm_model with lstm_object_detection.protos.lstm_model in the config file.

**Comment by matt-virgo** [comment]
That worked, thanks! Now I'm running into issues with my tf_record format. I'm trying to train using the same still image tf_records I had created for the normal object detection retraining.

Do you know of any good guidance on creating the sort of sequence records that this lstm training is expecting? Thanks again!

**Comment by Aaronreb** [comment]
Well, I'm afraid i am having the same issue!

> TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [<object_detection.core.matcher.Match object at 0x7ffaf7e3d978>, <object_detection.core.matcher.Match object at 0x7ffaf7cbd5c0>, <object_detection.core.matcher.Match object at 0x7ffaf7b2cfd0>, <object_detection.core.matcher.Match object at 0x7ffaf79afb00>, <object_detection.core.matcher.Match object at 0x7ffaf78362b0>, <object_detection.core.matcher.Match object at 0x7ffaf76a06a0>, <object_detection.core.matcher.Match object at 0x7ffaf7522710>, <object_detection.core.matcher.Match object at 0x7ffaf73a72b0>, <object_detection.core.matcher.Match object at 0x7ffaf72136a0>, <object_detection.core.matcher.Match object at 0x7ffaf7093710>, <object_detection.core.matcher.Match object at 0x7ffaf6f192b0>, <object_detection.core.matcher.Match object at 0x7ffaf6d856a0>, <object_detection.core.matcher.Match object at 0x7ffaf6c0a710>, <object_detection.core.matcher.Match object at 0x7ffaf6a8e2b0>, <object_detection.core.matcher.Match object at 0x7ffaf69796a0>, <object_detection.core.matcher.Match object at 0x7ffaf67fb710>, <object_detection.core.matcher.Match object at 0x7ffaf66002b0>, <object_detection.core.matcher.Match object at 0x7ffaf64ef6a0>, <object_detection.core.matcher.Match object at 0x7ffaf63715f8>, <object_detection.core.matcher.Match object at 0x7ffaf61f32b0>, <object_detection.core.matcher.Match object at 0x7ffaf60626a0>, <object_detection.core.matcher.Match object at 0x7ffaf5ee5710>, <object_detection.core.matcher.Match object at 0x7ffaf5d682b0>, <object_detection.core.matcher.Match object at 0x7ffaf5bd36a0>, <object_detection.core.matcher.Match object at 0x7ffaf5a58710>, <object_detection.core.matcher.Match object at 0x7ffaf58dc2b0>, <object_detection.core.matcher.Match object at 0x7ffaf57496a0>, <object_detection.core.matcher.Match object at 0x7ffaf55cf710>, <object_detection.core.matcher.Match object at 0x7ffaf544f2b0>, <object_detection.core.matcher.Match object at 0x7ffaf533d6a0>, <object_detection.core.matcher.Match object at 0x7ffaf5143710>, <object_detection.core.matcher.Match object at 0x7ffaf4fc42b0>]. Consider casting elements to a supported type.

This is the error i am getting.
Any help would be appreciated.
Thanks.

**Comment by Aaronreb** [comment]
> That worked, thanks! Now I'm running into issues with my tf_record format. I'm trying to train using the same still image tf_records I had created for the normal object detection retraining.
> 
> Do you know of any good guidance on creating the sort of sequence records that this lstm training is expecting? Thanks again!

Well, I'm afraid i am having the same issue!

TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [<object_detection.core.matcher.Match object at 0x7ffaf7e3d978>, <object_detection.core.matcher.Match object at 0x7ffaf7cbd5c0>, <object_detection.core.matcher.Match object at 0x7ffaf7b2cfd0>, <object_detection.core.matcher.Match object at 0x7ffaf79afb00>, <object_detection.core.matcher.Match object at 0x7ffaf78362b0>, <object_detection.core.matcher.Match object at 0x7ffaf76a06a0>, <object_detection.core.matcher.Match object at 0x7ffaf7522710>, <object_detection.core.matcher.Match object at 0x7ffaf73a72b0>, <object_detection.core.matcher.Match object at 0x7ffaf72136a0>, <object_detection.core.matcher.Match object at 0x7ffaf7093710>, <object_detection.core.matcher.Match object at 0x7ffaf6f192b0>, <object_detection.core.matcher.Match object at 0x7ffaf6d856a0>, <object_detection.core.matcher.Match object at 0x7ffaf6c0a710>, <object_detection.core.matcher.Match object at 0x7ffaf6a8e2b0>, <object_detection.core.matcher.Match object at 0x7ffaf69796a0>, <object_detection.core.matcher.Match object at 0x7ffaf67fb710>, <object_detection.core.matcher.Match object at 0x7ffaf66002b0>, <object_detection.core.matcher.Match object at 0x7ffaf64ef6a0>, <object_detection.core.matcher.Match object at 0x7ffaf63715f8>, <object_detection.core.matcher.Match object at 0x7ffaf61f32b0>, <object_detection.core.matcher.Match object at 0x7ffaf60626a0>, <object_detection.core.matcher.Match object at 0x7ffaf5ee5710>, <object_detection.core.matcher.Match object at 0x7ffaf5d682b0>, <object_detection.core.matcher.Match object at 0x7ffaf5bd36a0>, <object_detection.core.matcher.Match object at 0x7ffaf5a58710>, <object_detection.core.matcher.Match object at 0x7ffaf58dc2b0>, <object_detection.core.matcher.Match object at 0x7ffaf57496a0>, <object_detection.core.matcher.Match object at 0x7ffaf55cf710>, <object_detection.core.matcher.Match object at 0x7ffaf544f2b0>, <object_detection.core.matcher.Match object at 0x7ffaf533d6a0>, <object_detection.core.matcher.Match object at 0x7ffaf5143710>, <object_detection.core.matcher.Match object at 0x7ffaf4fc42b0>]. Consider casting elements to a supported type.

This is the error i am getting.
Any help would be appreciated.
Thanks.

**Comment by matt-virgo** [comment]
Will let you know if I figure anything out!

**Comment by Aaronreb** [comment]
> Will let you know if I figure anything out!

Fixed it!
Comment out the line 165 from lstm_object_detection/meta_architectures/lstm_ssd_meta_arch.py
#match_list = [matcher.Match(match) for match in tf.unstack(batch_match)]
Instead use the following code-
match_list=batch_match

**Comment by matt-virgo** [comment]
Nice! I'm headed to a conference today so probably won't be able to test anything out until later next week. Were you able to get it to train all the way through on a set of still image tfrecord data?

**Comment by Aaronreb** [comment]
> Nice! I'm headed to a conference today so probably won't be able to test anything out until later next week. Were you able to get it to train all the way through on a set of still image tfrecord data?

Did youo solve the sequence tfrecord issue?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by Young768** [comment]
Did anyone train the lstm model successfully?

**Comment by meikorol** [comment]
can you tell me how to train lstm object detection code？I have no clue how to train it
