### ISSUE TITLE
local_test_mobilenetv2.sh

### ISSUE THREAD

**Issue by RizanPSTU** [tensorflow/models#6784]
Running on Colab

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

testBuildDeepLabWithDensePredictionCell (__main__.DeeplabModelTest) ... WARNING:tensorflow:From /usr/lib/python3.6/contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2019-05-15 09:02:14.623453: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-05-15 09:02:14.626554: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1561ce0 executing computations on platform Host. Devices:
2019-05-15 09:02:14.626639: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /root/models/research/deeplab/core/feature_extractor.py:196: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
ok
testBuildDeepLabv2 (__main__.DeeplabModelTest) ... ok
testForwardpassDeepLabv3plus (__main__.DeeplabModelTest) ... ok
testWrongDeepLabVariant (__main__.DeeplabModelTest) ... ok
test_session (__main__.DeeplabModelTest)
Use cached_session instead. (deprecated) ... skipped 'Not a test.'

----------------------------------------------------------------------
Ran 5 tests in 27.863s

OK (skipped=1)
Downloading VOCtrainval_11-May-2012.tar to ./pascal_voc_seg
--2019-05-15 09:02:42--  http://host.robots.ox.ac.uk/pascal/VOC/voc2012//VOCtrainval_11-May-2012.tar
Resolving host.robots.ox.ac.uk (host.robots.ox.ac.uk)... 129.67.94.152
Connecting to host.robots.ox.ac.uk (host.robots.ox.ac.uk)|129.67.94.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1999639040 (1.9G) [application/x-tar]
Saving to: ‘VOCtrainval_11-May-2012.tar’

VOCtrainval_11-May- 100%[===================>]   1.86G  12.6MB/s    in 2m 33s  

2019-05-15 09:05:16 (12.5 MB/s) - ‘VOCtrainval_11-May-2012.tar’ saved [1999639040/1999639040]

Uncompressing VOCtrainval_11-May-2012.tar
Removing the color map in ground truth annotations...
Converting PASCAL VOC 2012 dataset...
2019-05-15 09:06:12.404979: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-05-15 09:06:12.405225: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1844b00 executing computations on platform Host. Devices:
2019-05-15 09:06:12.405259: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
>> Converting image 1/2913 shard 0WARNING:tensorflow:From ./build_voc2012_data.py:116: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
>> Converting image 729/2913 shard 0
>> Converting image 1458/2913 shard 1
>> Converting image 2187/2913 shard 2
>> Converting image 2913/2913 shard 3
>> Converting image 363/1449 shard 0
>> Converting image 726/1449 shard 1
>> Converting image 1089/1449 shard 2
>> Converting image 1449/1449 shard 3
>> Converting image 366/1464 shard 0
>> Converting image 732/1464 shard 1
>> Converting image 1098/1464 shard 2
>> Converting image 1464/1464 shard 3
--2019-05-15 09:06:43--  http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz
Resolving download.tensorflow.org (download.tensorflow.org)... 172.217.212.128, 2607:f8b0:4001:c03::80
Connecting to download.tensorflow.org (download.tensorflow.org)|172.217.212.128|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23882985 (23M) [application/x-tar]
Saving to: ‘deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz’

deeplabv3_mnv2_pasc 100%[===================>]  22.78M  --.-KB/s    in 0.09s   

2019-05-15 09:06:43 (245 MB/s) - ‘deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz’ saved [23882985/23882985]

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

INFO:tensorflow:Training on trainval set
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/root/models/research/deeplab/train.py", line 513, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/models/research/deeplab/train.py", line 463, in main
    dataset.get_one_shot_iterator(), dataset.num_of_classes,
  File "/root/models/research/deeplab/datasets/data_generator.py", line 325, in get_one_shot_iterator
    .map(self._preprocess_image, num_parallel_calls=self.num_readers))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1584, in map
    self, map_func, num_parallel_calls, preserve_cardinality=False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2771, in __init__
    input_dataset, map_func, use_inter_op_parallelism, preserve_cardinality)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2737, in __init__
    map_func, self._transformation_name(), dataset=input_dataset)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2124, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 490, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 341, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 355, in _create_definition_if_needed_impl
    whitelisted_stateful_ops=self._whitelisted_stateful_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 883, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2099, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/root/models/research/deeplab/datasets/data_generator.py", line 286, in _preprocess_image
    crop_height=self.crop_size[0],
TypeError: 'map' object is not subscriptable

**Comment by JimHeo** [comment]
deeplab is not fully compatible with python3.
You need to use python2, instead.
I think that would be worked.

**Comment by RizanPSTU** [comment]
Thanks you very much :)

**Comment by CircleOnCircles** [comment]
this incompat. has been solved. [#6797](https://github.com/tensorflow/models/issues/6797)
