### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by Telang8100** [tensorflow/models#6804]
tensorflow installed using pip
Linux Ubuntu 18.04
python 2.7
tensorflow 1.10.0

Exact Command:-
python "${WORK_DIR}"/train.py \
  --logtostderr \
  --train_split="train" \
  --model_variant="xception_65" \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --decoder_output_stride=4 \
  --train_crop_size=1921  \
  --train_crop_size=1081  \
  --train_batch_size=1 \
  --dataset="pqr"\
  --training_number_of_steps="${NUM_ITERATIONS}" \
  --tf_initial_checkpoint="./deeplabv3_pascal_train_aug/model.ckpt "\
  --train_logdir="${TRAIN_LOGDIR}" \
  --dataset_dir="${DATASET}"\

I am doing the custom dataset segmentation  in deeplabfor 6 classes when i am training my dataset I am getting index error. 

Traceback:-
INFO:tensorflow:Training on train set
Traceback (most recent call last):
  File "/home/suraj/serv/models/research/deeplab/train.py", line 513, in <module>
    tf.app.run()
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/suraj/serv/models/research/deeplab/train.py", line 463, in main
    dataset.get_one_shot_iterator(), dataset.num_of_classes,
  File "/home/suraj/serv/models/research/deeplab/datasets/data_generator.py", line 333, in get_one_shot_iterator
    .map(self._preprocess_image, num_parallel_calls=self.num_readers))
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1040, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2649, in __init__
    use_inter_op_parallelism)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2611, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/suraj/anaconda2/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/home/suraj/serv/models/research/deeplab/datasets/data_generator.py", line 295, in _preprocess_image
    crop_width=self.crop_size[1],
IndexError: list index out of range

![Screenshot from 2019-05-17 11-50-56](https://user-images.githubusercontent.com/41721821/57907132-11c60e80-789a-11e9-8a77-43affd3ad25f.png)

**Comment by merofeev** [comment]
PR #6681 has changed format of input arguments. Instead of

```
--train_crop_size=1921 
--train_crop_size=1081 
```

you should write:

```
--train_crop_size=1921,1081 
```

The same change also applies to `eval.py` and `vis.py`

**Comment by Telang8100** [comment]
> PR #6681 has changed format of input arguments. Instead of
> 
> ```
> --train_crop_size=1921 
> --train_crop_size=1081 
> ```
> 
> you should write:
> 
> ```
> --train_crop_size=1921,1081 
> ```
> 
> The same change also applies to `eval.py` and `vis.py`
Thanks it solved the issue after that i met with another error
![Screenshot from 2019-05-17 17-17-41](https://user-images.githubusercontent.com/41721821/57926005-c0cd0f00-78c7-11e9-9d41-9a0252c39d6b.png)
