### ISSUE TITLE
Error object_detection/builders/model_builder_test.py with TF 1.13 but worked with 1.11

### ISSUE THREAD

**Issue by RobotEdh** [tensorflow/models#6813]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
- **TensorFlow installed from (source or binary)**:pip3 install
- **TensorFlow version (use command below)**: 1.13
- **Bazel version (if compiling from source)**:n/a
- **CUDA/cuDNN version**:n/a
- **GPU model and memory**:n/a
- **Exact command to reproduce**: python3 object_detection/builders/model_builder_test.py

### Describe the problem
the run of **model_builder_test.py** returns the following error with TF **1.13** but works fine with TF **1.11**

```

pi@raspberrypi:~/tensorflow1/models/research $ python3 object_detection/builde                                                                                                               rs/model_builder_test.py
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime ve                                                                                                               rsion 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not ma                                                                                                               tch runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type                                                                                                                size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/home/pi/tensorflow1/models/research/object_detection/builders/model_b                                                                                                               uilder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/home/pi/tensorflow1/models/research/object_detection/builders/box_pre                                                                                                               dictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/home/pi/tensorflow1/models/research/object_detection/predictors/convo                                                                                                               lutional_box_predictor.py", line 22, in <module>
    slim = tf.contrib.slim
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/lazy_loa                                                                                                               der.py", line 61, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/lazy_loa                                                                                                               der.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py"                                                                                                               , line 40, in <module>
    from tensorflow.contrib import distribute
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/_                                                                                                               _init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/p                                                                                                               ython/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/__init__                                                                                                               .py", line 69, in <module>
    from tensorflow.contrib.tpu.python.ops.tpu_ops import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/o                                                                                                               ps/tpu_ops.py", line 39, in <module>
    resource_loader.get_path_to_datafile("_tpu_ops.so"))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/util/loader.                                                                                                               py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/loa                                                                                                               d_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid name:
An op that loads optimization parameters into HBM for embedding. Must be
preceded by a ConfigureTPUEmbeddingHost op that sets up the correct
embedding table configuration. For example, this op is used to install
parameters that are loaded from a checkpoint before a training loop is
executed.

parameters: A tensor containing the initial embedding table parameters to use                                                                                                                in embedding
lookups using the Adagrad optimization algorithm.
accumulators: A tensor containing the initial embedding table accumulators to                                                                                                                use in embedding
lookups using the Adagrad optimization algorithm.
table_name: Name of this table; must match a name in the
  TPUEmbeddingConfiguration proto (overrides table_id).
num_shards: Number of shards into which the embedding tables are divided.
shard_id: Identifier of shard for this operation.
table_id: Index of this table in the EmbeddingLayerConfiguration proto
  (deprecated).
```

**Comment by gethgle** [comment]
![image](https://user-images.githubusercontent.com/53439157/64630422-b274a700-d412-11e9-90b7-b7acd6e1ac46.png)

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
