### ISSUE TITLE
Tensorflow object detection  error for : python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

### ISSUE THREAD

**Issue by mithilpatil1994** [tensorflow/models#6866]
I am tring to run : [https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10](url)

OS platform : windows 64 bits
protoc : protoc-3.7.1-win32
python : Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) [MSC v.1900 64 bit (AMD64)] on win32

During step the step **6. Run the Training** I got the following error :

#################################################################

(tensorflow6) C:\Users\Welcome\Desktop\dust\tensorflow6\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "C:\Users\Welcome\Anaconda3\envs\tensorflow6\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\Welcome\Desktop\dust\tensorflow6\models\research\object_detection\trainer.py", line 193, in train
    detection_model = create_model_fn()
  File "C:\Users\Welcome\Desktop\dust\tensorflow6\models\research\object_detection\builders\model_builder.py", line 85, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "C:\Users\Welcome\Desktop\dust\tensorflow6\models\research\object_detection\builders\model_builder.py", line 231, in _build_faster_rcnn_model
    first_stage_only = frcnn_config.first_stage_only
AttributeError: first_stage_only

########################################################################

For the step : **2g. Test TensorFlow setup to verify it works** I got the following error : 

#######################################################################

(tensorflow6) C:\Users\Welcome\Desktop\dust\tensorflow6\models\research\object_detection>python object_detection_tutorial.py
2019-05-23 16:47:59.204755: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

#######################################################################
stuck badly for above 2 issue. 
Help me for this issue. 
Thanks.

**Comment by pkulzc** [comment]
You are using deprecated train.py and have not synced to latest. Could you try syncing your fork and use model_main.py?
Regarding your 2 questions:
1. The field first_stage_only is already gone. Now you should use number_of_stages.
2. We don't have object_detection_tutorial.py, there is a notebook called object_detection_tutorial.ipynb though.

**Comment by mithilpatil1994** [comment]
1. Is it necessary to execute  **notebook called object_detection_tutorial.ipynb**  to train our own model ??
2. I tried with **Tensorflow object detection API** version used in the link, which provides me with train.py in object detection folder.

**Comment by pkulzc** [comment]
object_detection_tutorial.ipynb is used for running inference instead of running training.

If possible, sync your fork to use model_main.py.

**Comment by kranti65** [comment]
while executing train.py in object detection it shows the following  error:




Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 35, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 29, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'

**Comment by lt14** [comment]
please help:


Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 181, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow2\models\research\object_detection\legacy\trainer.py", line 398, in train
    include_global_step=False))
  File "C:\tensorflow2\models\research\object_detection\utils\variables_helper.py", line 139, in get_variables_available_in_checkpoint
    ckpt_reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 636, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 648, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on C: /tensorflow2/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt: Not found: FindFirstFile failed for: C: /tensorflow2/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28 : El sistema no puede encontrar la ruta especificada.
; No such process

**Comment by lt14** [comment]
help :
W0211 09:23:34.342873 19936 deprecation_wrapper.py:119] From C:\tensorflow2\models\research\object_detection\utils\variables_helper.py:139: The name tf.train.NewCheckpointReader is deprecated. Please use tf.compat.v1.train.NewCheckpointReader instead.

Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 181, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow2\models\research\object_detection\legacy\trainer.py", line 398, in train
    include_global_step=False))
  File "C:\tensorflow2\models\research\object_detection\utils\variables_helper.py", line 139, in get_variables_available_in_checkpoint
    ckpt_reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 636, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 648, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on C: /tensorflow2/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt: Not found: FindFirstFile failed for: C: /tensorflow2/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28 : El sistema no puede encontrar la ruta especificada.
; No such process

**Comment by rethamasae** [comment]
I can't run the Training, maybe someone can help me
(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
2020-08-10 22:08:00.754622: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\ASUS\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 39, in <module>
    from object_detection.protos import model_pb2
  File "C:\Users\ASUS\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\protos\model_pb2.py", line 14, in <module>
    from object_detection.protos import center_net_pb2 as object__detection_dot_protos_dot_center__net__pb2
ImportError: cannot import name 'center_net_pb2' from 'object_detection.protos' (C:\Users\ASUS\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\protos\__init__.py)

**Comment by torikol** [comment]
Hello, when I was trying to train my images using TensorFlow I got this message. can anyone help me to solve this issue?
(tensorflow1) C:\Users\misla\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
2020-12-02 18:19:03.201205: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-12-02 18:19:03.207767: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import dataset_builder
  File "C:\Users\misla\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 32, in <module>
    from object_detection.builders import decoder_builder
  File "C:\Users\misla\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\decoder_builder.py", line 25, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\Users\misla\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\data_decoders\tf_example_decoder.py", line 28, in <module>
    from tf_slim import tfexample_decoder as slim_example_decoder
ModuleNotFoundError: No module named 'tf_slim'

**Comment by Petros626** [comment]
> 
> 
> while executing train.py in object detection it shows the following error:
> 
> Traceback (most recent call last): File "train.py", line 51, in from object_detection.builders import model_builder File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 35, in from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 29, in from nets import inception_resnet_v2 ModuleNotFoundError: No module named 'nets'

you must copy the folder slim from research to the object_detection folder

**Comment by Petros626** [comment]
> 
> 
> Hello, when I was trying to train my images using TensorFlow I got this message. can anyone help me to solve this issue? (tensorflow1) C:\Users\misla\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config 2020-12-02 18:19:03.201205: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found 2020-12-02 18:19:03.207767: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. Traceback (most recent call last): File "train.py", line 51, in from object_detection.builders import dataset_builder File "C:\Users\misla\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 32, in from object_detection.builders import decoder_builder File "C:\Users\misla\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\decoder_builder.py", line 25, in from object_detection.data_decoders import tf_example_decoder File "C:\Users\misla\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\data_decoders\tf_example_decoder.py", line 28, in from tf_slim import tfexample_decoder as slim_example_decoder ModuleNotFoundError: No module named 'tf_slim'

try pip uninstall tf-slim and use conda install tf-slim, furthermore you must be carefull which version of tf-slim you use in combination with tensorflow, hope it helps you

**Comment by Medusjy** [comment]
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 91, in main
    assert FLAGS.train_dir, '`train_dir` is missing.'
AssertionError: `train_dir` is missing.

**Comment by Petros626** [comment]
> Traceback (most recent call last): File "train.py", line 186, in tf.app.run() File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\absl\app.py", line 312, in run _run_main(main, args) File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\absl\app.py", line 258, in _run_main sys.exit(main(argv)) File "C:\Users\keski\anaconda3\envs\eyesforvipgpu\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func return func(*args, **kwargs) File "train.py", line 91, in main assert FLAGS.train_dir, '`train_dir` is missing.' AssertionError: `train_dir` is missing.

The message explains itself, I guess?
