### ISSUE TITLE
Build fails with most recent version of Bazel

### ISSUE THREAD

**Issue by zv** [tensorflow/models#69]
I just built a copy of the most recent version of Bazel and it threw the following error when I build:

```
WARNING: /home/zv/.cache/bazel/_bazel_zv/d49f4fd45b21dc0a5977bc0da866df7a/external/tf/WORKSPACE:1: Workspace name in /home/zv/.cache/bazel/_bazel_zv/d49f4fd45b21dc0a5977bc0da866df7a/external/tf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@tf); this will cause a build error in future versions.
ERROR: /home/zv/Development/tflow/models/syntaxnet/WORKSPACE:11:1: Traceback (most recent call last):
        File "/home/zv/Development/tflow/models/syntaxnet/WORKSPACE", line 11
                check_version("0.2.0")
        File "/home/zv/.cache/bazel/_bazel_zv/d49f4fd45b21dc0a5977bc0da866df7a/external/tf/tensorflow/tensorflow.bzl", line 22, in check_version
                _parse_bazel_version(native.bazel_version)
        File "/home/zv/.cache/bazel/_bazel_zv/d49f4fd45b21dc0a5977bc0da866df7a/external/tf/tensorflow/tensorflow.bzl", line 15, in _parse_bazel_version
                int(number)
invalid literal for int(): "2b".
ERROR: Error evaluating WORKSPACE file.
ERROR: Loading of target '@bazel_tools//tools/cpp:toolchain' failed; build aborted: error loading package 'external': Package 'external' contains errors.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.098s
ERROR: Couldn't start the build. Unable to run tests.
```

This problem is addressed by removing the version check on line 11 of `syntaxnet/WORKSPACE` or converting to Bazel's `ccheck` syntax.

**Comment by goog** [comment]
Note: You must use bazel version 0.2.2, NOT 0.2.2b, due to a WORKSPACE issue

**Comment by zv** [comment]
Oh my, I totally spaced -- I see.
