### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by zorawar12** [tensorflow/models#7002]
I am using Ubuntu 18.04
CUDA 10.0
Tensorflow 1.13.1
python3.7

```I0612 11:11:53.837813 140085060675392 coordinator.py:224] Error reported to Coordinator: <class 'UnicodeDecodeError'>, 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Traceback (most recent call last):
  File "inference.py", line 416, in <module>
    app.run(main)
  File "/home/zorawar/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/zorawar/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "inference.py", line 412, in main
    use_masks=FLAGS.use_masks)
  File "inference.py", line 188, in _run_inference
    im = util.load_image(im_files[i], resize=(img_width, img_height))
  File "/home/zorawar/Desktop/models-master/research/struct2depth/util.py", line 60, in load_image
    im_data = np.fromstring(gfile.Open(img_file).read(), np.uint8)
  File "/home/zorawar/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 132, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/zorawar/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "/home/zorawar/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/compat.py", line 107, in as_str_any
    return as_str(value)
  File "/home/zorawar/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte```

**Comment by zorawar12** [comment]
[ #5857 ](https://github.com/tensorflow/models/issues/5857#issuecomment-485192104)
This Solves the above problem.

**Comment by ammerss** [comment]
@zorawar12  
Hi can you tell me exactly how you changed your code?? I have the same error as you
But #5857 that link does not help me, 
I can't find this code : im_data = np.fromstring(gfile.Open(img_file).read(), np.uint8) 
I don't think this is in autoaugment

**Comment by zorawar12** [comment]
@ammerss 

Hi, try this one.. [447764871](https://github.com/tensorflow/models/issues/5857#issuecomment-447764871)
