### ISSUE TITLE
struct2depth

### ISSUE THREAD

**Issue by zorawar12** [tensorflow/models#7015]
### System information
- **What is the top-level directory of the model you are using**:Struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 18.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:tensorflow-gpu 1.13.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:10.0
- **GPU model and memory**:GeForce MX130
- **Exact command to reproduce**:sudo python3 train.py   --logtostderr   --checkpoint_dir $ckpt_dir   --data_dir $data_dir   --architecture resnet   --imagenet_ckpt $imagenet_ckpt   --imagenet_norm true

### Describe the problem
Struct2Depth training issue, also without using sudo, I am getting tensorflow.contrib module not present error.

### Source code / logs
```I0614 14:29:31.849410 139772196542272 coordinator.py:224] Error reported to Coordinator: <class 'AttributeError'>, 'NoneType' object has no attribute 'restore_op_name'
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    app.run(main)
  File "/home/zorawar/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/zorawar/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 187, in main
    FLAGS.checkpoint_dir, FLAGS.train_steps, FLAGS.summary_freq)
  File "train.py", line 211, in train
    pretrain_restorer.restore(sess, ckpt_path)
  File "/home/zorawar/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1275, in restore
    sess.run(self.saver_def.restore_op_name,
AttributeError: 'NoneType' object has no attribute 'restore_op_name'
```

**Comment by zorawar12** [comment]
The original problem is somehow the train code is not getting the variables to restore from imagenet pretrained model. The error is following:

```Traceback (most recent call last):
  File "train.py", line 262, in <module>
    app.run(main)
  File "/home/zorawar/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/zorawar/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 187, in main
    FLAGS.checkpoint_dir, FLAGS.train_steps, FLAGS.summary_freq)
  File "train.py", line 203, in train
    pretrain_restorer = tf.train.Saver(vars_to_restore)
  File "/home/zorawar/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/zorawar/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/zorawar/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 869, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
