### ISSUE TITLE
AttributeError: 'module' object has no attribute 'keras' in google cloud

### ISSUE THREAD

**Issue by TZVIh** [tensorflow/models#7063]
Hi,
I am using google cloud with this :
gcloud ml-engine jobs submit training `whoami`_object_detection_`date +%s`   
  --job-dir=gs://cardboard_box_usa/train     --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz     --module-name object_detection.train     --scale-tier basic_gpu

I got this error:
message: "Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "/root/.local/lib/python2.7/site-packages/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/root/.local/lib/python2.7/site-packages/object_detection/builders/box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/root/.local/lib/python2.7/site-packages/object_detection/predictors/convolutional_box_predictor.py", line 19, in <module>
    from object_detection.core import box_predictor
  File "/root/.local/lib/python2.7/site-packages/object_detection/core/box_predictor.py", line 137, in <module>
    class KerasBoxPredictor(tf.keras.Model):
AttributeError: 'module' object has no attribute 'keras'

what should I do?
Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
