### ISSUE TITLE
Not possible to evaluate performance on the validation set of Open Image Challenge 2019

### ISSUE THREAD

**Issue by nicaogr** [tensorflow/models#7106]
Hi

When I try to apply the same process to the validation set of the Open Image Challenge 2019 to evaluate the performance of my model thanks to the object_detection scripts (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/challenge_evaluation.md#object-detection-track), this kind of error messages : 

>  File "dataset_tools/oid_hierarchical_labels_expansion.py", line 201, in <module>
    main(args)
  File "dataset_tools/oid_hierarchical_labels_expansion.py", line 172, in main
    expanded_lines = expansion_generator.expand_boxes_from_csv(line)
  File "dataset_tools/oid_hierarchical_labels_expansion.py", line 110, in expand_boxes_from_csv
    assert len(cvs_row_splitted) == 13
AssertionError
Traceback (most recent call last):
  File "dataset_tools/oid_hierarchical_labels_expansion.py", line 201, in <module>
    main(args)
  File "dataset_tools/oid_hierarchical_labels_expansion.py", line 170, in main
    expanded_lines = expansion_generator.expand_labels_from_csv(line)
  File "dataset_tools/oid_hierarchical_labels_expansion.py", line 133, in expand_labels_from_csv
    assert len(cvs_row_splited) == 4
AssertionError

Whar is the best way to do the evaluation on the validation set ?

Best,

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
