### ISSUE TITLE
[ im2txt]"ValueError: No variables to save" caused by "saver = tf.train.Saver(self.inception_variables)"

### ISSUE THREAD

**Issue by lawrencewxj** [tensorflow/models#713]
## im2txt
I have done all the preparatory work according to the tutorial. But,when i run the script:

bazel-bin/im2txt/train \
  --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256" \
  --inception_checkpoint_file="${INCEPTION_CHECKPOINT}" \
  --train_dir="${MODEL_DIR}/train" \
  --train_inception=false \
  --number_of_steps=1000000,

It starts to go wrong.I would be grateful if you could help me find out where the problems are.

**the log:**
INFO: Found 17 targets...
INFO: Elapsed time: 0.126s, Critical Path: 0.00s
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:Prefetching values from 256 files matching /home/cugrobot/im2txt/data/mscoco/train-?????-of-00256
Traceback (most recent call last):
  File "/home/cugrobot/im2txt-p/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/home/cugrobot/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/cugrobot/im2txt-p/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/home/cugrobot/im2txt-p/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 356, in build
    self.setup_inception_initializer()
  File "/home/cugrobot/im2txt-p/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 331, in setup_inception_initializer
    saver = tf.train.Saver(self.inception_variables)
  File "/home/cugrobot/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/home/cugrobot/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by lawrencewxj** [comment]
@cshallue
