### ISSUE TITLE
s3dg issue

### ISSUE THREAD

**Issue by hollowgalaxy** [tensorflow/models#7155]
### System information
- **What is the top-level directory of the model you are using**: slim
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.13.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:10.0
- **GPU model and memory**: GTX 1080
- **Exact command to reproduce**: see code below. Ran this in a python script with tensorflow_io installed.

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
I am feeding images with 5-D shape and dtype of uint8, as specified by the documentation s3dg However, bug arises saying that I am feeding a float
## Error:
```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    features,info = s3dg.s3dg(nxt)
  File "/home/hollowgalaxy/Github/models/research/slim/nets/s3dg.py", line 570, in s3dg
    scope=scope)
  File "/home/hollowgalaxy/Github/models/research/slim/nets/s3dg.py", line 228, in s3dg_base
    scope=end_point)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/hollowgalaxy/Github/models/research/slim/nets/i3d_utils.py", line 170, in conv3d_spatiotemporal
    scope=scope)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1198, in convolution3d
    conv_dims=3)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1058, in convolution
    outputs = layer.apply(inputs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 435, in add_weight
    getter=vs.get_variable)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1479, in get_variable
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1220, in get_variable
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 530, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1750, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1741, in _model_variable_getter
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 350, in model_variable
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 277, in variable
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 499, in _true_getter
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 911, in _get_single_variable
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2495, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1395, in __init__
    constraint=constraint)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1503, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 883, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py", line 345, in __call__
    shape, self.mean, self.stddev, dtype, seed=self.seed)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py", line 174, in truncated_normal
    mean_tensor = ops.convert_to_tensor(mean, dtype=dtype, name="mean")
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 466, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/hollowgalaxy/anaconda3/envs/py36/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 371, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected uint8, got 0.0 of type 'float' instead.
```

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
from pathlib import Path

import tensorflow as tf
import nets.s3dg as s3dg
from tensorflow_io.video import VideoDataset

video_path = Path.home()/'Desktop/1_minute.mp4'  # any video would suffice


video_path_ph = tf.placeholder(tf.string)

video = VideoDataset(video_path_ph)

video = video.batch(32).batch(1)

itr = video.make_initializable_iterator()
nxt = itr.get_next()
# nxt = Tensor("IteratorGetNext:0", shape=(?, ?, ?, ?, 3), dtype=uint8)
features,info = s3dg.s3dg(nxt)
```
Mentioning @pkulzc as you were made the last change on this model.

**Comment by hollowgalaxy** [comment]
Replacing the dataset stuff with this, fixed the issue.
```
video = VideoDataset(video_path_ph)

video = video.batch(32,drop_remainder=True)
video = video.map(lambda images: tf.image.resize_images(images,size=[224,224]))
video = video.batch(1)

itr = video.make_initializable_iterator()
nxt = itr.get_next()
```
