### ISSUE TITLE
deep_speech AttributeError: 'int' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ForeverZyh** [tensorflow/models#7156]
### System informationWhat is the top-level directory of the model you are using: research/deep_speech
Have I written custom code: No
OS Platform and Distribution: Linux
TensorFlow installed from: pip3
TensorFlow version: r1.13
Bazel version: N/A
CUDA/cuDNN version: 10.0
GPU model and memory: Titan 1080

### Describe the problem
Exception AttributeError: 'int' object has no attribute 'lower'
It seems that 
``distribution_utils.get_distribution_strategy(num_gpus)``
should be 
``distribution_utils.get_distribution_strategy(num_gpus=num_gpus)``

### Source code / logs
Traceback (most recent call last):
  File "deep_speech.py", line 411, in <module>
    absl_app.run(main)
  File "/home/yuhao/ENVs/py3.5-tensorflow-1.13.1/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/yuhao/ENVs/py3.5-tensorflow-1.13.1/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deep_speech.py", line 404, in main
    run_deep_speech(flags_obj)
  File "deep_speech.py", line 226, in run_deep_speech
    distribution_strategy = distribution_utils.get_distribution_strategy(num_gpus)
  File "/home/yuhao/repos/models/official/utils/misc/distribution_utils.py", line 115, in get_distribution_strategy
    distribution_strategy = distribution_strategy.lower()
AttributeError: 'int' object has no attribute 'lower'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by ForeverZyh** [comment]
Exact command to reproduce: ./run_deep_speech.sh

**Comment by ForeverZyh** [comment]
The issue was fixed by [pull request](https://github.com/tensorflow/models/pull/7157)
