### ISSUE TITLE
Faster RCNN object detection realtime video

### ISSUE THREAD

**Issue by AbhimanyuAryan** [tensorflow/models#7171]
I'm using [Object Detection notebook](https://github.com/tensorflow/models/blob/master
/research/object_detection/object_detection_tutorial.ipynb) to detect images in test dataset 

![2](https://user-images.githubusercontent.com/8083613/60861258-7452df80-a237-11e9-9479-2503d257559c.png)

I'm using [Faster RCNN Resnet101 COCO](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_resnet101_coco.config).

I don't want to put bounding box on images in test dataset. Rather I want this detection to happen realtime(like yolo examples) in a video live stream

How can I do that?

------------------------

### System information
- **What is the top-level directory of the model you are using**: 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: TensorFlow installed with pip
- **TensorFlow version (use command below)**: 1.13.1
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**: V10.1.168/7.*
- **GPU model and memory**: 2080Ti 11Gb
- **Exact command to reproduce**:

**Comment by QuickLearner171998** [comment]
Check this out: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/Object_detection_video.py
or
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/Object_detection_webcam.py

**Comment by AbhimanyuAryan** [comment]
@QuickLearner171998 

when I execute webcam script i.e. [this](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/Object_detection_webcam.py)

I get an error: 
```
 python stf_new.py
2019-07-09 15:11:35.179313: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2019-07-09 15:11:35.209618: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2663270000 Hz
2019-07-09 15:11:35.213981: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5642d13e24e0 executing computations on platform Host. Devices:
2019-07-09 15:11:35.214030: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "stf_new.py", line 68, in <module>
    sess = tf.Session(graph=detection_graph)
  File "/home/redtwo/anaconda3/envs/nstest2/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/redtwo/anaconda3/envs/nstest2/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 11521884160
```

**Comment by AbhimanyuAryan** [comment]
Solved it thanks

**Comment by QuickLearner171998** [comment]
> Solved it thanks

Can you share the solution that worked please.
