### ISSUE TITLE
Resnet_v2_*() from slim.nets does not coincide with pre-trained Resnet_v2_50.ckpt

### ISSUE THREAD

**Issue by prateethvnayak** [tensorflow/models#7176]
### System information
OS Platform and Distribution - Linux Ubuntu 16.04)
TensorFlow installed from Anaconda dist 3.6.
TensorFlow version 1.13-mkl / 1.13-gpu
Python version: Python 3.6.6 :: Anaconda, Inc.

### Describe the problem
The pre-trained model in `models/research/slim` for **Resnet_v2_50** does not coincide with the network creation in the *Code* under `slim.nets.resnet_v2`

### Code Snippet used for restoring model
```
import tensorflow as tf
import tensorflow.contrib.slim as slim
import tensorflow.contrib.slim.nets as nets

g = tf.Graph()
with g.as_default():
    image = tf.placeholder(tf.float32, shape=[None, 224, 224, 3])
    with slim.arg_scope(resnet_v2.resnet_arg_scope()):
        logits, _ = nets.resnet_v2.resnet_v2_50(image, 1000)
    preds = tf.nn.softmax(tf.reshape(logits, [-1, 1000]))
    variables_to_restore = slim.get_variables_to_restore()
    saver = tf.train.Saver(variables_to_restore)
    new_saver = tf.train.Saver()
    with tf.Session(graph=g) as sess:

        saver.restore(sess, "Downloads/resnet_v2_50_2017_04_14/resnet_v2_50.ckpt")
        print("Model Restored !")
```

### Traceback
```
Traceback (most recent call last):
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1000] rhs shape= [1001]
     [[{{node save/Assign_266}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1000] rhs shape= [1001]
     [[node save/Assign_266 (defined at create_nets.py:14) ]]

Caused by op 'save/Assign_266', defined at:
  File "create_nets.py", line 14, in <module>
    variables_to_restore = slim.get_variables_to_restore()
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1000] rhs shape= [1001]
     [[node save/Assign_266 (defined at create_nets.py:14) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_nets.py", line 14, in <module>
    variables_to_restore = slim.get_variables_to_restore()
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1312, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1000] rhs shape= [1001]
     [[node save/Assign_266 (defined at create_nets.py:14) ]]

Caused by op 'save/Assign_266', defined at:
  File "create_nets.py", line 14, in <module>
    variables_to_restore = slim.get_variables_to_restore()
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "anaconda3/envs/tf13-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1000] rhs shape= [1001]
     [[node save/Assign_266 (defined at create_nets.py:14) ]]
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Oceania2018** [comment]
I encountered error below:
```shell
python train_image_classifier --train_dir=train_logs 
--dataset_name=flowers 
--dataset_split_name=train 
--dataset_dir=data/flowers 
--model_name=resnet_v2_50 
--checkpoint_path=checkpoint/resnet_v2_50.ckpt
```

```shell
Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key resnet_v2_50/block1/unit_1/bottleneck_v2/conv1/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at D:\Projects\PythonLab\slim\train_image_classifier.py:588) ]]

Original stack trace for 'save/RestoreV2':
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
```

**Comment by uranusx86** [comment]
see troubleshooting
[The ResNet and VGG Models have 1000 classes but the ImageNet dataset has 1001](https://github.com/tensorflow/models/tree/master/research/slim#the-resnet-and-vgg-models-have-1000-classes-but-the-imagenet-dataset-has-1001)

**Comment by prateethvnayak** [comment]
Yes. @uranusx86 is correct. I figured that some models in the zoo are trained with 1001 classes with class 0 as background, while some are 1000 classes. 

Closing issue.
