### ISSUE TITLE
训练ssd_mobilenet_v2_coco.conf错误

### ISSUE THREAD

**Issue by 18483666678** [tensorflow/models#7199]
错误代码：Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
Traceback (most recent call last):
  File "E:/cvode/mayun/models-master/research/object_detection/model_main.py", line 111, in <module>
    tf.app.run()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "E:/cvode/mayun/models-master/research/object_detection/model_main.py", line 107, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "D:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 471, in train_and_evaluate
    return executor.run()
  File "D:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 611, in run
    return self.run_local()
  File "D:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 712, in run_local
    saving_listeners=saving_listeners)
  File "D:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1154, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "D:\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "E:\cvode\mayun\models-master\research\object_detection\model_lib.py", line 302, in model_fn
    features[fields.InputDataFields.true_image_shape])
  File "E:\cvode\mayun\models-master\research\object_detection\meta_architectures\ssd_meta_arch.py", line 569, in predict
    preprocessed_inputs)
  File "E:\cvode\mayun\models-master\research\object_detection\models\ssd_mobilenet_v2_feature_extractor.py", line 135, in extract_features
    image_features=image_features)
  File "E:\cvode\mayun\models-master\research\object_detection\models\feature_map_generators.py", line 418, in multi_resolution_feature_maps
    feature_map = image_features[from_layer]
KeyError: 'layer_15/expansion_output'

**Comment by 18483666678** [comment]
目前没找到原因，求指导

**Comment by ymodak** [comment]
Can you please provide all the information asked by the template? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
