### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[6] does not have value

### ISSUE THREAD

**Issue by amalti** [tensorflow/models#7239]
Hi
I have an issue converting pb file to coreml file with a Retval[6] error. here is my traceback log

Traceback (most recent call last):
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
try:
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1430, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[6] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "convert.py", line 25, in 
convert()
File "convert.py", line 23, in convert
output_feature_names=output_tensor_names)
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 589, in convert
custom_conversion_functions=custom_conversion_functions)
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 246, in _convert_pb_to_mlmodel
tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
run_metadata_ptr)
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
feed_dict_tensor, options, run_metadata)
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
run_metadata)
File "/home/abed/Development/projects/virenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
try:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[6] does not have value

Running inspect gives the attached txt

[model.txt](https://github.com/tensorflow/models/files/3402992/model.txt)

nd my convert script is pasted here

import os
import tensorflow as tf
import tfcoreml as tf_converter
from inspect_pb import inspect
frozen_model_file = os.path.abspath('model.pb')
input_tensor_shapes = { 'patch' : [128, 64, 64, 1], 'patch_p' : [128, 64, 64, 1],
'patch_n' : [128, 64, 64, 1],
'Placeholder_3:0' : [1],
'euclid_p':[128]}

Output CoreML model path
coreml_model_file = './model.mlmodel'
output_tensor_names = ['euclid_p']

def convert():
with tf.io.gfile.GFile(frozen_model_file, "rb") as f:
graph_def = tf.compat.v1.GraphDef()
graph_def.ParseFromString(f.read())
# Then, we import the graph_def into a new Graph
tf.import_graph_def(graph_def, name="") # Convert
tf_converter.convert( tf_model_path=frozen_model_file,
mlmodel_path=coreml_model_file,
input_name_shape_dict=input_tensor_shapes,
output_feature_names=output_tensor_names)

inspect('frozen_graph.pb','frozen_graph.txt')
convert()

Any clue of where the error come from?

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
