### ISSUE TITLE
Invalid argument: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'b\'\\xff\\xd8\\xff\\x'

### ISSUE THREAD

**Issue by shin8085** [tensorflow/models#7327]
### System information
- **What is the top-level directory of the model you are using**:im2txt
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:win10
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:1.14.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:10.0
- **GPU model and memory**:GeForce GTX 1050 Ti and 4 GB
- **Exact command to reproduce**:python train.py

### Describe the problem
I already converts MSCOCO data to TFRecord file, but when I run train.py, it made some mistakes and I don't konw how to solve it. By the way, the data is to mush so I had to run it in my windows

### Source code / logs
I0730 13:52:25.139621 14756 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, 2 root error(s) found.
  (0) Invalid argument: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'b\'\\xff\\xd8\\xff\\x'
	 [[{{node decode_1/DecodeJpeg}}]]
  (1) Invalid argument: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'b\'\\xff\\xd8\\xff\\x'
	 [[{{node decode_1/DecodeJpeg}}]]
	 [[decode_1/DecodeJpeg/_1663]]
0 successful operations.
0 derived errors ignored.
I0730 13:52:25.572993 14540 learning.py:783] Caught OutOfRangeError. Stopping Training. 2 root error(s) found.
  (0) Out of range: PaddingFIFOQueue '_2_batch_and_pad/padding_fifo_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[node batch_and_pad (defined at E:\CodeManage\python\test\im2txt\im2txt\ops\inputs.py:196) ]]
	 [[OptimizeLoss/train/update_seq_embedding/map/ScatterSub/_1714]]
  (1) Out of range: PaddingFIFOQueue '_2_batch_and_pad/padding_fifo_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[node batch_and_pad (defined at E:\CodeManage\python\test\im2txt\im2txt\ops\inputs.py:196) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'batch_and_pad':
  File "E:/CodeManage/python/test/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Python\Python36\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "D:\Python\Python36\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "E:/CodeManage/python/test/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "E:\CodeManage\python\test\im2txt\im2txt\show_and_tell_model.py", line 353, in build
    self.build_inputs()
  File "E:\CodeManage\python\test\im2txt\im2txt\show_and_tell_model.py", line 174, in build_inputs
    queue_capacity=queue_capacity))
  File "E:\CodeManage\python\test\im2txt\im2txt\ops\inputs.py", line 196, in batch_with_dynamic_pad
    name="batch_and_pad")
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\input.py", line 1188, in batch_join
    name=name)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\input.py", line 830, in _batch_join
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4182, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

I0730 13:52:25.573990 14540 learning.py:785] Finished training! Saving model to disk.
D:\Python\Python36\lib\site-packages\tensorflow\python\summary\writer\writer.py:386: UserWarning: Attempting to use a closed FileWriter. The operation will be a noop unless the FileWriter is explicitly reopened.
  warnings.warn("Attempting to use a closed FileWriter. "
Traceback (most recent call last):
  File "E:/CodeManage/python/test/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Python\Python36\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "D:\Python\Python36\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "E:/CodeManage/python/test/im2txt/im2txt/train.py", line 110, in main
    saver=saver)
  File "D:\Python\Python36\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 790, in train
    ignore_live_threads=ignore_live_threads)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "D:\Python\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1279, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "D:\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'b\'\\xff\\xd8\\xff\\x'
	 [[{{node decode_1/DecodeJpeg}}]]
  (1) Invalid argument: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'b\'\\xff\\xd8\\xff\\x'
	 [[{{node decode_1/DecodeJpeg}}]]
	 [[decode_1/DecodeJpeg/_1663]]
0 successful operations.
0 derived errors ignored.

Process finished with exit code 1

**Comment by SevenFoldDeep** [comment]
Was just having the same problem but solved it. Turns out when I was saving the files using rasterio, I was using the wrong 'driver' in the metadata and so it wasn't saving as a correct png even though it had the png file extension. Maybe this is the case for you?

A way to start debugging it, get the absolute path of one of your files and run it rhough the following code manually step by step:

`image_filename = os.path.join(
            FLAGS.image_folder, filenames[i] + '.' + FLAGS.image_format)
        image_data = tf.gfile.FastGFile(image_filename, 'rb').read()
        height, width = image_reader.read_image_dims(image_data)
        # Read the semantic segmentation annotation.
        seg_filename = os.path.join(
            FLAGS.semantic_segmentation_folder,
            filenames[i] + '.' + FLAGS.label_format)
        seg_data = tf.gfile.FastGFile(seg_filename, 'rb').read()
        seg_height, seg_width = label_reader.read_image_dims(seg_data)
        if height != seg_height or width != seg_width:
          raise RuntimeError('Shape mismatched between image and label.')
        # Convert to tf example.
        example = build_data.image_seg_to_tfexample(
            image_data, filenames[i], height, width, seg_data)
        tfrecord_writer.write(example.SerializeToString())`


This is how I was abkle to pinpoint the problem lied in my segmentation images rather than the original images.

**Comment by SevenFoldDeep** [comment]
You can also check the driver of all your images using the following code:

``with rasterio.open(file) as src:
    print(src.meta['driver'])``


Put that in a for loop inserting each image as file and you can see if there are any problem images. If you find one you can rewrite it in the desired format using:


``with rasterio.open(self.file) as src:
                    w = src.read()
meta_d=src.meta.copy()
meta_d.update({"driver": "PNG"})#can subsitute the PNG with whatever the format you want is
with rasterio.open(out_file_path, "w", **meta_d) as dest:
                        dest.write(w)
``

**Comment by chunduriv** [comment]
@shin8085, 

The files in your directory that have either a .jpg, .jpeg, .png or .gif extension but that are not actually JPEG, PNG of GIF images. Hence, TensorFlow isn't able to properly load them.

One way to overcome this problem would be to check files that are supposedly images and get rid of the ones that aren't actual JPEG, PNG or GIF images.

Checking for each picture individually if it is valid or not as shown below

```
def is_image(filename, verbose=False):

    data = open(filename,'rb').read(10)

    # check if file is JPG or JPEG
    if data[:3] == b'\xff\xd8\xff':
        if verbose == True:
             print(filename+" is: JPG/JPEG.")
        return True

    # check if file is PNG
    if data[:8] == b'\x89\x50\x4e\x47\x0d\x0a\x1a\x0a':
        if verbose == True:
             print(filename+" is: PNG.")
        return True

    # check if file is GIF
    if data[:6] in [b'\x47\x49\x46\x38\x37\x61', b'\x47\x49\x46\x38\x39\x61']:
        if verbose == True:
             print(filename+" is: GIF.")
        return True

    return False
```

For more details please refer [here](https://stackoverflow.com/a/62544801/14290681). Thank you.
