### ISSUE TITLE
'NoneType' object has no attribute 'outer_context error when computing gradients (ssd_mobilenet_v1)

### ISSUE THREAD

**Issue by mahdiabdollahpour** [tensorflow/models#7329]
I am using ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03 and want to compute this gradient :

```
image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
scores = detection_graph.get_tensor_by_name('detection_scores:0')
gr = tf.gradients(scores,image_tensor)


```
and I get this error

```
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    gr = tf.gradients(scores,image_tensor)
  File "C:\Users\workshop\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 664, in gradients
    unconnected_gradients)
  File "C:\Users\workshop\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 851, in _GradientsHelper
    to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs)
  File "C:\Users\workshop\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 192, in _PendingCount
    between_op_list, between_ops, colocate_gradients_with_ops)
  File "C:\Users\workshop\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1448, in MaybeCreateControlFlowState
    loop_state.AddWhileContext(op, between_op_list, between_ops)
  File "C:\Users\workshop\.conda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1251, in AddWhileContext
    outer_forward_ctxt = forward_ctxt.outer_context
AttributeError: 'NoneType' object has no attribute 'outer_context
```'
```

I searched and same problem was mentioned on StackOverFlow but no answer was given.

(Windows 10, python 3, tf 1.13.1)
`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kvaibhav2009** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you.

**Comment by Binh24399** [comment]
I am too facing the same problem. Anyone got a solution yet?
