### ISSUE TITLE
ResNet fails when applying quantization aware training

### ISSUE THREAD

**Issue by albertNod** [tensorflow/models#7336]
# System information
- **What is the top-level directory of the model you are using**:
ResNet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, I added 
`    tf.contrib.quantize.create_training_graph(quant_delay=1000)
`
(And corresponding create_eval_graph) to resnet_model_fn as follows:
```
def resnet_model_fn(features, labels, mode, model_class,
                    resnet_size, weight_decay, learning_rate_fn, momentum,
                    data_format, resnet_version, loss_scale,
                    loss_filter_fn=None, dtype=resnet_model.DEFAULT_DTYPE,
                    fine_tune=False, label_smoothing=0.0):

  # Generate a summary node for the images
  tf.compat.v1.summary.image('images', features, max_outputs=6)
  # Checks that features/images have same data type being used for calculations.
  assert features.dtype == dtype

  model = model_class(resnet_size, data_format, resnet_version=resnet_version,
                      dtype=dtype)

  logits = model(features, mode == tf.estimator.ModeKeys.TRAIN)

  # This acts as a no-op if the logits are already in fp32 (provided logits are
  # not a SparseTensor). If dtype is is low precision, logits must be cast to
  # fp32 for numerical stability.
  logits = tf.cast(logits, tf.float32)

  predictions = {
      'classes': tf.argmax(input=logits, axis=1),
      'probabilities': tf.nn.softmax(logits, name='softmax_tensor')
  }

  if mode == tf.estimator.ModeKeys.PREDICT:
    # Return the predictions and the specification for serving a SavedModel
    return tf.estimator.EstimatorSpec(
        mode=mode,
        predictions=predictions,
        export_outputs={
            'predict': tf.estimator.export.PredictOutput(predictions)
        })

  # Calculate loss, which includes softmax cross entropy and L2 regularization.
  if label_smoothing != 0.0:
    one_hot_labels = tf.one_hot(labels, 1001)
    cross_entropy = tf.losses.softmax_cross_entropy(
        logits=logits, onehot_labels=one_hot_labels,
        label_smoothing=label_smoothing)
  else:
    cross_entropy = tf.compat.v1.losses.sparse_softmax_cross_entropy(
        logits=logits, labels=labels)

  # Create a tensor named cross_entropy for logging purposes.
  tf.identity(cross_entropy, name='cross_entropy')
  tf.compat.v1.summary.scalar('cross_entropy', cross_entropy)

  # If no loss_filter_fn is passed, assume we want the default behavior,
  # which is that batch_normalization variables are excluded from loss.
  def exclude_batch_norm(name):
    return 'batch_normalization' not in name
  loss_filter_fn = loss_filter_fn or exclude_batch_norm

  # Add weight decay to the loss.
  l2_loss = weight_decay * tf.add_n(
      # loss is computed using fp32 for numerical stability.
      [
          tf.nn.l2_loss(tf.cast(v, tf.float32))
          for v in tf.compat.v1.trainable_variables()
          if loss_filter_fn(v.name)
      ])
  tf.compat.v1.summary.scalar('l2_loss', l2_loss)
  loss = cross_entropy + l2_loss

  if mode == tf.estimator.ModeKeys.TRAIN:
    ############################################
    tf.contrib.quantize.create_training_graph(quant_delay=1000)############# Added quantization
    global_step = tf.compat.v1.train.get_or_create_global_step()

    learning_rate = learning_rate_fn(global_step)

    # Create a tensor named learning_rate for logging purposes
    tf.identity(learning_rate, name='learning_rate')
    tf.compat.v1.summary.scalar('learning_rate', learning_rate)

    if flags.FLAGS.enable_lars:
      optimizer = tf.contrib.opt.LARSOptimizer(
          learning_rate,
          momentum=momentum,
          weight_decay=weight_decay,
          skip_list=['batch_normalization', 'bias'])
    else:
      optimizer = tf.compat.v1.train.MomentumOptimizer(
          learning_rate=learning_rate,
          momentum=momentum
      )

    fp16_implementation = getattr(flags.FLAGS, 'fp16_implementation', None)
    if fp16_implementation == 'graph_rewrite':
      optimizer = (
          tf.compat.v1.train.experimental.enable_mixed_precision_graph_rewrite(
              optimizer, loss_scale=loss_scale))

    def _dense_grad_filter(gvs):
      """Only apply gradient updates to the final layer.

      This function is used for fine tuning.

      Args:
        gvs: list of tuples with gradients and variable info
      Returns:
        filtered gradients so that only the dense layer remains
      """
      return [(g, v) for g, v in gvs if 'dense' in v.name]

    if loss_scale != 1 and fp16_implementation != 'graph_rewrite':
      # When computing fp16 gradients, often intermediate tensor values are
      # so small, they underflow to 0. To avoid this, we multiply the loss by
      # loss_scale to make these tensor values loss_scale times bigger.
      scaled_grad_vars = optimizer.compute_gradients(loss * loss_scale)

      if fine_tune:
        scaled_grad_vars = _dense_grad_filter(scaled_grad_vars)

      # Once the gradient computation is complete we can scale the gradients
      # back to the correct scale before passing them to the optimizer.
      unscaled_grad_vars = [(grad / loss_scale, var)
                            for grad, var in scaled_grad_vars]
      minimize_op = optimizer.apply_gradients(unscaled_grad_vars, global_step)
    else:
      grad_vars = optimizer.compute_gradients(loss)
      if fine_tune:
        grad_vars = _dense_grad_filter(grad_vars)
      minimize_op = optimizer.apply_gradients(grad_vars, global_step)

    update_ops = tf.compat.v1.get_collection(tf.compat.v1.GraphKeys.UPDATE_OPS)
    train_op = tf.group(minimize_op, update_ops)
  else:
   #########################################################
    tf.contrib.quantize.create_eval_graph()############# Added quantization
    train_op = None

  accuracy = tf.compat.v1.metrics.accuracy(labels, predictions['classes'])
  accuracy_top_5 = tf.compat.v1.metrics.mean(
      tf.nn.in_top_k(predictions=logits, targets=labels, k=5, name='top_5_op'))
  metrics = {'accuracy': accuracy,
             'accuracy_top_5': accuracy_top_5}

  # Create a tensor named train_accuracy for logging purposes
  tf.identity(accuracy[1], name='train_accuracy')
  tf.identity(accuracy_top_5[1], name='train_accuracy_top_5')
  tf.compat.v1.summary.scalar('train_accuracy', accuracy[1])
  tf.compat.v1.summary.scalar('train_accuracy_top_5', accuracy_top_5[1])

  return tf.estimator.EstimatorSpec(
      mode=mode,
      predictions=predictions,
      loss=loss,
      train_op=train_op,
      eval_metric_ops=metrics)`
```
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
v1.14.0-rc1-22-gaf24dc9 1.14.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
10.0, 7.4.1
- **GPU model and memory**:
Tesla K80, 11441MiB
- **Exact command to reproduce**:
 python cifar10_main.py --data_dir ~/cifar10/cifar-10-batches-bin

### Describe the problem

Without tf.compat.v1.train.experimental.enable_mixed_precision_graph_rewrite(), the ResNet model runs perfectly well. However, with that line, it crashes with the following message:

### Source code / logs
Traceback (most recent call last):
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 16 and 32 for 'resnet_model/conv2d/post_conv_mul' (op: 'Mul') with input shapes: [16], [?,16,32,32].

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "cifar10_main.py", line 295, in <module>
    absl_app.run(main)
  File "/home/albert/quant_env/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/albert/quant_env/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "cifar10_main.py", line 289, in main
    run_cifar(flags.FLAGS)
  File "cifar10_main.py", line 282, in run_cifar
    shape=[HEIGHT, WIDTH, NUM_CHANNELS])
  File "/home/albert/models/official/resnet/resnet_run_loop.py", line 691, in resnet_main
    max_steps=flags_obj.max_train_steps)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1156, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1219, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1299, in _actual_train_model_distributed
    self.config))
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1555, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/distribute/one_device_strategy.py", line 163, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "cifar10_main.py", line 246, in cifar10_model_fn
    fine_tune=params['fine_tune']
  File "/home/albert/models/official/resnet/resnet_run_loop.py", line 442, in resnet_model_fn
    tf.contrib.quantize.create_training_graph(quant_delay=1000)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/contrib/quantize/python/quantize_graph.py", line 122, in create_training_graph
    freeze_bn_delay=freeze_bn_delay)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/contrib/quantize/python/quantize_graph.py", line 73, in _create_graph
    is_training=is_training)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/contrib/quantize/python/fold_batch_norms.py", line 53, in FoldBatchNorms
    graph, is_training, freeze_batch_norm_delay=freeze_batch_norm_delay)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/contrib/quantize/python/fold_batch_norms.py", line 128, in _FoldFusedBatchNorms
    correction_recip, new_layer_tensor, name='post_conv_mul')
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 322, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6490, in mul
    "Mul", x=x, y=y, name=name)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
    control_input_ops)
  File "/home/albert/quant_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 16 and 32 for 'resnet_model/conv2d/post_conv_mul' (op: 'Mul') with input shapes: [16], [?,16,32,32].`

**Comment by albertNod** [comment]
I solved it by disabling fused batch normalization, but if there is a way to do it without removing that optimization, that would still be very helpful

**Comment by peri044** [comment]
Hello @albertNod , I'm trying to train a resnet 50 model with Quantization aware training nodes. I'm using estimator and it looks like you're working on the same thing. Were you able to finetune quantized resnet 50 model by importing pre-trained weights of Resnet 50 ? I'm facing an error (restoring checkpoint issue as the quantization parameters are not found in the checkpoint). Did you face such errors ?

**Comment by rose-jinyang** [comment]
Hello, 
While I'm working on transfer learning of ResNet50 model, I'm going to do quantization aware training of the final model.
I have a run-time issue in tf.contrib.quantize.create_training_graph method when I do quantization aware training of Resnet50.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Jin/Internet_Task/Jobs/2019/2019.11.20-fr_fl_rasppi-sridhar/work/fr_jin/fr_jin/test_quant_aware_training.py", line 42, in <module>
    tf.contrib.quantize.create_training_graph(sess.graph)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\quantize_graph.py", line 122, in create_training_graph
    freeze_bn_delay=freeze_bn_delay)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\quantize_graph.py", line 73, in _create_graph
    is_training=is_training)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 53, in FoldBatchNorms
    graph, is_training, freeze_batch_norm_delay=freeze_batch_norm_delay)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 98, in _FoldFusedBatchNorms
    freeze_batch_norm_delay=freeze_batch_norm_delay))
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 384, in _ComputeBatchNormCorrections
    match.moving_variance_tensor + match.batch_epsilon)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

I think that the problem is the batch normalization of ResNet.
I'm using Python 3.7 and tensorflow 1.14/1.15.
Could anybody help me for this issue?
Thanks
