### ISSUE TITLE
AttributeError: 'AdamWeightDecay' object has no attribute '_decayed_lr_t'

### ISSUE THREAD

**Issue by jmwoloso** [tensorflow/models#7369]
### System information
- **What is the top-level directory of the model you are using**: bert
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.0.0-beta1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `python run_classifier.py`

### Describe the problem
When running `run_classifier.py`, I get (full traceback below):

`AttributeError: 'AdamWeightDecay' object has no attribute '_decayed_lr_t'`

### Source code / logs
```
2019-08-02 15:48:25.362073: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-02 15:48:25.390601: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2112000000 Hz
2019-08-02 15:48:25.391289: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e441e77430 executing computations on platform Host. Devices:
2019-08-02 15:48:25.391321: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
W0802 15:48:25.392576 140425466451584 cross_device_ops.py:1168] There is non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
I0802 15:48:25.393204 140425466451584 <input>:203] Training using customized training loop TF 2.0 with distrubutedstrategy.
W0802 15:48:37.894714 140422696642304 deprecation.py:323] From /home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
I0802 15:48:42.047023 140425466451584 coordinator.py:219] Error reported to Coordinator: 'AdamWeightDecay' object has no attribute '_decayed_lr_t'
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 189, in _call_for_each_replica
    **merge_kwargs)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 476, in _distributed_apply
    var, apply_grad_to_update_var, args=(grad,), group=False))
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1458, in update
    return self._update(var, fn, args, kwargs, group)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 766, in _update
    **values.select_device_mirrored(d, kwargs)))
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 461, in apply_grad_to_update_var
    update_op = self._resource_apply_dense(grad, var)
  File "/home/jason/code/python/bert_poc/bert/optimization/optimizers.py", line 146, in _resource_apply_dense
    apply_state)
  File "/home/jason/code/python/bert_poc/bert/optimization/optimizers.py", line 133, in _get_lr
    return self._decayed_lr_t[var_dtype], {}
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 542, in __getattribute__
    raise e
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 532, in __getattribute__
    return super(OptimizerV2, self).__getattribute__(name)
AttributeError: 'AdamWeightDecay' object has no attribute '_decayed_lr_t'
Traceback (most recent call last):
  File "<input>", line 283, in <module>
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "<input>", line 251, in main
  File "<input>", line 219, in run_bert
  File "<input>", line 145, in run_customized_training
  File "/home/jason/code/python/bert_poc/bert/utils/models/training.py", line 409, in run_customized_training_loop
    train_single_step(train_iterator)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 416, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 359, in _initialize
    *args, **kwds))
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1360, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1648, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1541, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 716, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 309, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/jason/.virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 706, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
AttributeError: in converted code:
    relative to /home/jason:
    code/python/bert_poc/bert/utils/models/training.py:324 train_single_step  *
        strategy.experimental_run_v2(_replicated_step,
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:708 experimental_run_v2
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1710 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py:708 _call_for_each_replica
        fn, args, kwargs)
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py:195 _call_for_each_replica
        coord.join(threads)
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py:389 join
        six.reraise(*self._exc_info_to_raise)
    .virtualenvs/bert_poc/lib/python3.7/site-packages/six.py:693 reraise
        raise value
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py:297 stop_on_exception
        yield
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py:189 _call_for_each_replica
        **merge_kwargs)
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:476 _distributed_apply
        var, apply_grad_to_update_var, args=(grad,), group=False))
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1458 update
        return self._update(var, fn, args, kwargs, group)
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py:766 _update
        **values.select_device_mirrored(d, kwargs)))
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:461 apply_grad_to_update_var
        update_op = self._resource_apply_dense(grad, var)
    code/python/bert_poc/bert/optimization/optimizers.py:146 _resource_apply_dense
        apply_state)
    code/python/bert_poc/bert/optimization/optimizers.py:133 _get_lr
        return self._decayed_lr_t[var_dtype], {}
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:542 __getattribute__
        raise e
    .virtualenvs/bert_poc/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:532 __getattribute__
        return super(OptimizerV2, self).__getattribute__(name)
    AttributeError: 'AdamWeightDecay' object has no attribute '_decayed_lr_t'
```

**Comment by saberkun** [comment]
Hi, _decayed_lr_t relies on a recent optimizer change which is available in TF-nightly. The change is not included inside tf2 beta. Please use nightly build.

**Comment by jmwoloso** [comment]
Perfect, thank you @saberkun
