### ISSUE TITLE
"NotImplementedError: must be implemented in descendants" running estimator version resnet in distributed-manner using kubeflow

### ISSUE THREAD

**Issue by ali-raza-tariq** [tensorflow/models#7415]
Hi guys, i am not a machine learning (tensorflow) expert and am struggling to run resnet (estimator api version) example on kubernetes using distributed tensorflow. The documentation states, estimator api is agnostic to whether its running standalone or distributed. Please correct me if it can not be run in the distributed environment! ('https://github.com/tensorflow/models/blob/master/official/r1/resnet/'). While i can run it locally as well as on my kubernetes cluster (in single pod) using kubeflow - but when i try to run it in the distributed manner ... one of the pods fail (master or worker), with this error
`logs of master-pod`
```
I0808 19:51:02.516915 140622807734016 run_config.py:528] TF_CONFIG environment variable: {u'environment': u'cloud', u'cluster': {u'ps': [u'tfjobcifar-ps-0.ali.svc:2222'], u'chief': [u'tfjobcifar-chief-0.ali.svc:2222'], u'worker': [u'tfjobcifar-worker-0.ali.svc:2222']}, u'task': {u'index': 0, u'type': u'worker'}}
I0808 19:51:02.517596 140622807734016 run_config.py:558] Initializing RunConfig with distribution strategies.
I0808 19:51:02.518049 140622807734016 estimator_training.py:177] RunConfig initialized for Distribute Coordinator with INDEPENDENT_WORKER mode
I0808 19:51:02.519479 140622807734016 estimator.py:209] Using config: {'_save_checkpoints_secs': 86400, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': <tensorflow.python.distribute.one_device_strategy.OneDeviceStrategyV1 object at 0x7fe527b38990>, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fe527b38950>, '_model_dir': '/tmp/cifar10_model', '_protocol': None, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_experimental_max_worker_delay_secs': None, '_evaluation_master': '', '_eval_distribute': None, '_global_id_in_cluster': 0, '_master': '', '_distribute_coordinator_mode': 'independent_worker'}
W0808 19:51:02.521104 140622807734016 logger.py:387] 'cpuinfo' not imported. CPU info will not be logged.
W0808 19:51:02.521697 140622807734016 logger.py:400] 'psutil' not imported. Memory info will not be logged.
I0808 19:51:02.536117 140622807734016 logger.py:152] Benchmark run: {'machine_config': {}, 'run_date': '2019-08-08T19:51:02.520443Z', 'tensorflow_version': {'git_hash': 'v1.14.0-rc1-22-gaf24dc91b5', 'version': '1.14.0'}, 'dataset': {'name': 'CIFAR-10'}, 'tensorflow_environment_variables': [{'name': 'TF_CONFIG', 'value': '{"cluster":{"chief":["tfjobcifar-chief-0.ali.svc:2222"],"ps":["tfjobcifar-ps-0.ali.svc:2222"],"worker":["tfjobcifar-worker-0.ali.svc:2222"]},"task":{"type":"worker","index":0},"environment":"cloud"}'}], 'run_parameters': [{'long_value': 128, 'name': 'batch_size'}, {'name': 'dtype', 'string_value': "<dtype: 'float32'>"}, {'long_value': 2, 'name': 'num_workers'}, {'name': 'resnet_size', 'string_value': '56'}, {'name': 'resnet_version', 'string_value': '1'}, {'bool_value': 'False', 'name': 'synthetic_data'}, {'long_value': 182, 'name': 'train_epochs'}], 'test_id': None, 'model_name': 'resnet'}
I0808 19:51:02.536664 140622807734016 resnet_run_loop.py:651] Starting to train and evaluate.
I0808 19:51:02.537544 140622807734016 training.py:462] Running `train_and_evaluate` with Distribute Coordinator.
I0808 19:51:02.538577 140622807734016 distribute_coordinator.py:776] Running Distribute Coordinator with mode = 'independent_worker', cluster_spec = {u'ps': [u'tfjobcifar-ps-0.ali.svc:2222'], u'chief': [u'tfjobcifar-chief-0.ali.svc:2222'], u'worker': [u'tfjobcifar-worker-0.ali.svc:2222']}, task_type = u'worker', task_id = 0, environment = u'cloud', rpc_layer = 'grpc'
W0808 19:51:02.538826 140622807734016 distribute_coordinator.py:829] `eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
I0808 19:51:02.539495 140622807734016 distribute_coordinator.py:438] Starting standard TensorFlow server, target = u'grpc://tfjobcifar-worker-0.ali.svc:2222', session_config= allow_soft_placement: true

2019-08-08 19:51:02.540292: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-08 19:51:02.556249: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2297345000 Hz
2019-08-08 19:51:02.559362: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5588e80a7870 executing computations on platform Host. Devices:
2019-08-08 19:51:02.559416: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-08 19:51:02.562998: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:250] Initialize GrpcChannelCache for job chief -> {0 -> tfjobcifar-chief-0.ali.svc:2222}
2019-08-08 19:51:02.563044: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:250] Initialize GrpcChannelCache for job ps -> {0 -> tfjobcifar-ps-0.ali.svc:2222}
2019-08-08 19:51:02.563066: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:250] Initialize GrpcChannelCache for job worker -> {0 -> localhost:2222}
2019-08-08 19:51:02.567866: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:365] Started server with target: grpc://localhost:2222
2019-08-08 19:51:02.567928: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:369] Server already started (target: grpc://localhost:2222)
Traceback (most recent call last):
  File "/app/cifar10_main.py", line 295, in <module>
    absl_app.run(main)
  File "/usr/local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/app/cifar10_main.py", line 289, in main
    run_cifar(flags.FLAGS)
  File "/app/cifar10_main.py", line 282, in run_cifar
    shape=[HEIGHT, WIDTH, NUM_CHANNELS])
  File "/app/models/official/r1/resnet/resnet_run_loop.py", line 652, in resnet_main
    tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 464, in train_and_evaluate
    estimator, train_spec, eval_spec, _TrainingExecutor)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/distribute/estimator_training.py", line 290, in train_and_evaluate
    session_config=run_config.session_config)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 850, in run_distribute_coordinator
    if strategy.extended.experimental_between_graph:
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1582, in experimental_between_graph
    raise NotImplementedError("must be implemented in descendants")
NotImplementedError: must be implemented in descendants
Exception AttributeError: "'NoneType' object has no attribute 'UnimplementedError'" in <bound method Server.__del__ of <tensorflow.python.training.server_lib.Server object at 0x7fe527b38ed0>> ignored
```  
here is the 'job.yaml' file i am using to create the job
```
apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: tfjobcifar
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          volumes:
            - name: local-pv
              persistentVolumeClaim:
                claimName: local-pvc
          containers:
            - name: tensorflow
              image: ali19tariq/cifar10:1.0.0
              imagePullPolicy: Always
              args:
                - --data_dir
                - ./cifar10_data/cifar-10-batches-bin
                - --model_dir
                - ./out/home/tariqa/export
              volumeMounts:
                - mountPath: /app/out
                  name: local-pv
          restartPolicy: OnFailure
    Worker:
      replicas: 1
      template:
        spec:
          containers:
            - name: tensorflow
              image: ali19tariq/cifar10:1.0.0
              imagePullPolicy: Always
          restartPolicy: OnFailure
    PS:
      replicas: 1
      template:
        spec:
          volumes:
            - name: local-pv
              persistentVolumeClaim:
                claimName: local-pvc
          containers:
            - name: tensorflow
              image: ali19tariq/cifar10:1.0.0
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /app/out
                  name: local-pv
          restartPolicy: OnFailure

```
Platform details:
 - tensorflow 1.14.0
 - kubeflow v0.6.0
 - kubernetes v1.15.1
 - cluster-details = running 4 node bare-metal kubernetes cluster

Again, i have very limited knowledge of tensorflow so please let me know why this example is not working and how can i make it work by any modifications whatsoever!

thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ali-raza-tariq** [comment]
The exact file 'https://github.com/tensorflow/models/blob/master/official/r1/resnet/cifar10_main.py'
OS/distribution: Ubuntu 18.04.2 LTS 
Tensorflow installed using pip : tensorflow 1.14.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A

i am currently running this code on top of kubernetes using kubeflow (both version already mentioned above) using only CPU - no GPUs. The manifest file has been attached to launch the job on kubernetes. you can simply use my image to directly run it or compile a new Dockerfile image from the top level directory mentioned. Please let me know if i need to specify anything else!

**Comment by jaeyounkim** [comment]
Please use our [new code](https://github.com/tensorflow/models/tree/master/official/vision/image_classification/resnet) instead. The r1 directory is no longer supported.
