### ISSUE TITLE
unicode_escape

### ISSUE THREAD

**Issue by samudralaz** [tensorflow/models#7424]
### Describe the problem
Tried doing training object detection from the below link
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#training-the-model
In the last part of the page you can see the training part where i am getting the below error

### Source code / logs

(base) C:\Users\Admin\Desktop\tensorflow\workspace\training_demo>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=C:\Users\Admin\Desktop\tensorflow\workspace\training_demo\training\ssd_inception_v2_coco.config

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 1460, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_encoding.py", line 115, in CUnescape
    .decode('unicode_escape')
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\Users\Admin\Desktop\tensorflow\workspace\training_demo\object_detection\utils\config_util.py", line 104, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 685, in Merge
    allow_unknown_field=allow_unknown_field)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 752, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 777, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 799, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 924, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 998, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 924, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 1049, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 1420, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 1435, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "C:\Users\Admin\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 1462, in _ConsumeSingleByteString
    raise self.ParseError(str(e))
google.protobuf.text_format.ParseError: 151:25 : '  fine_tune_checkpoint: "C:\Users\Admin\Desktop\tensorflow\workspace\training_demo\pre-trained-model\model.ckpt"': 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
