### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by sonx1354** [tensorflow/models#7425]
Traceback (most recent call last):

  File "C:/tensorflow1/models/research/object_detection/Object_detection_webcam.py", line 103, in <module>

    \feed_dict={image_tensor: frame_expanded})

  File "C:\python verileri\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run

   \ run_metadata_ptr)

  File "C:\python verileri\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run

   \ np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)

  File "C:\python verileri\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 538, in asarray

    \return array(a, dtype, copy=False, order=order)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

[ WARN:1] terminating async callback

thanks in advance for help getting this when running training data

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
