### ISSUE TITLE
[Transformers] tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by blackclothheart** [tensorflow/models#7447]
### System information
- **What is the top-level directory of the model you are using**:Transformers
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.14
- **Bazel version (if compiling from source)**:none
- **CUDA/cuDNN version**:10.1
- **GPU model and memory**: Tesla K40m 12G
- **Exact command to reproduce**:python transformer_main.py --data_dir=./test_data/use_data --model_dir=./model_big --vocab_file=./test_data/use_data/vocab.txt --param_set=big --bleu_source=./test_data/raw_data/train.en --bleu_ref=./test_data/raw_data/train.de

### Describe the problem
When I' m trying to train a transformer model, I have encountered this problem weither the base version or v2 version.

### Source code / logs
Traceback (most recent call last):
  File "transformer_main.py", line 289, in <module>
    absl_app.run(main)
  File "/home/t-chazha/anaconda3/envs/tf/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/t-chazha/anaconda3/envs/tf/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 277, in main
    task.train()
  File "transformer_main.py", line 177, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/home/t-chazha/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 649, in fit
    validation_freq=validation_freq)
  File "/home/t-chazha/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_distributed.py", line 143, in fit_distributed
    steps_name='steps_per_epoch')
  File "/home/t-chazha/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 274, in model_iteration
    batch_outs = f(actual_inputs)
  File "/home/t-chazha/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/t-chazha/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Window size must be greater than zero, but got 0.
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
         [[loss_1/add/_2175]]
  (1) Invalid argument: Window size must be greater than zero, but got 0.
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]

**Comment by saberkun** [comment]
Could you try drop_remainder=True for dataset batching?

**Comment by blackclothheart** [comment]
Hi , I set the static_batch = True which call the tf.contrib.data.padded_batch_and_drop_remainder() fuction, but I still met the same problem.

**Comment by blackclothheart** [comment]
> Could you try drop_remainder=True for dataset batching?

Hi, I set static_batch=True whitch call the tf.contrib.data.padded_batch_and_drop_remainder() fuction, but I still met the same problem.

**Comment by blackclothheart** [comment]
> Could you try drop_remainder=True for dataset batching?

Hi, I set static_batch=True whitch call the tf.contrib.data.padded_batch_and_drop_remainder() fuction, but I still met the same problem.
