### ISSUE TITLE
【Transformer】Window size must be greater than zero, but got 0.

### ISSUE THREAD

**Issue by Gavin90s** [tensorflow/models#7467]
I0819 12:00:50.283545 140343560021824 tf_logging.py:115] Saving checkpoints for 0 into /home/rudy/git/models/official/transformer/model_base/model.ckpt.
Traceback (most recent call last):
  File "transformer_main.py", line 636, in <module>
    absl_app.run(main)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 630, in main
    run_transformer(flags.FLAGS)
  File "transformer_main.py", line 611, in run_transformer
    vocab_file=flags_obj.vocab_file)
  File "transformer_main.py", line 332, in run_loop
    hooks=train_hooks)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1352, in _train_model_distributed
    saving_listeners)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Window size must be greater than zero, but got 0.
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?], [?,?]], output_types=[DT_INT64, DT_INT64]](IteratorFromStringHandleV2)]]
         [[node ExperimentalFunctionBufferingResourceGetNext_2 (defined at /home/rudy/anaconda2/envs/tf1.12py2.7/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/prefetching_ops_v2.py:124)  = ExperimentalFunctionBufferingResourceGetNext[output_types=[DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:GPU:2"](ExperimentalFunctionBufferingResource_2)]]

**Comment by Gavin90s** [comment]
what‘ s problem？ any suggestion will be appreciated.

**Comment by EamonnCarson** [comment]
I had the same issue, and I fixed it by changing the 'max_length' parameter to one close to the true max sequence length in my data set. My problem seemed to be that the program makes some preset distribution of buckets partitioning sequence lengths between 0 and 'max_length', but since my 'max_length' was much higher than my maximum sequence length, there was a bucket that had 0 sequences assigned to it (causing the window size for that bucket to be zero). See official/transformer/v2/data_pipeline.py to see the code that does this.

So try lowering your 'max_length'.
