### ISSUE TITLE
`ModuleNotFoundError: No module named 'tensorflow_datasets'. `

### ISSUE THREAD

**Issue by MariaLavrovskaya** [tensorflow/models#7490]
Currently I am struggling with the same problem: `ModuleNotFoundError: No module named 'tensorflow_datasets'. `
Have tried to run `pip install tensorflow_datasets`, but it hasn't changed something. 

The terminal shows a number of tracebacks: 

```
`ERROR: Error checking for conflicts.
Traceback (most recent call last):
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _dep_map
    return self.__dep_map
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2806, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3003, in _parsed_pkg_info
    return self._pkg_info
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2806, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 524, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 47, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2727, in requires
    dm = self._dep_map
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3005, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1419, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1607, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/pandas-0.24.2.dist-info/METADATA'
Installing collected packages: tensorflow-estimator
Successfully installed tensorflow-estimator-1.14.0
(base) mbp-maria:~ marialavrovskaa$ find /usr/local/var/pyenv/versions/3.7.0/lib/python3.7/site-packages/ -name METADATA
find: /usr/local/var/pyenv/versions/3.7.0/lib/python3.7/site-packages/: No such file or directory
(base) mbp-maria:~ marialavrovskaa$ /Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/ -name METADATA
-bash: /Users/marialavrovskaa/anaconda3/lib/python3.6/site-packages/: is a directory
(base) mbp-maria:~ marialavrovskaa$ 
`
```
What I should do to fix it?

_Originally posted by @MariaLavrovskaya in https://github.com/tensorflow/models/issues/6669#issuecomment-523964596_

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by saberkun** [comment]
Please move this issue to tensorflow_datasets. Thanks
