### ISSUE TITLE
Bug found in visualize object detection results

### ISSUE THREAD

**Issue by TerryBryant** [tensorflow/models#7512]
### System information
- **What is the top-level directory of the model you are using**: faster_rcnn_resnet_v1
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Centos7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**: None
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: 
- **Exact command to reproduce**: 

### Describe the problem
As I followed this [tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb), I'm trying to visualize the detection results, while error happens:
```
Traceback (most recent call last):
  File "ys_eval.py", line 114, in <module>
    line_thickness=8)
  File "/home/work/ys/models-master/research/object_detection/utils/visualization_utils.py", line 781, in visualize_boxes_and_labels_on_image_array
    if classes[i] in six.viewkeys(category_index):
AttributeError: 'list' object has no attribute 'viewkeys'
```
Then I searched the `category_index`, and find its value comes from [here](https://github.com/tensorflow/models/blob/68c3c65596b8fc624be15aef6eac3dc8952cbf23/research/object_detection/utils/label_map_util.py#L77), however it gives a list value. In [here](https://github.com/tensorflow/models/blob/68c3c65596b8fc624be15aef6eac3dc8952cbf23/research/object_detection/utils/visualization_utils.py#L724), it says `category_index` is a dict value. So I think this is the reason why the error happens.

Finally, I think a datatype transfer is enough, so here is my [solution](https://github.com/TerryBryant/models/pull/1#issue-312218145).

**Comment by Prixxi** [comment]
I had a similar error: 
if classes[i] in six.viewkeys(category_index):
AttributeError: 'list' object has no attribute 'keys'
What fixed it for me was to change the lines 1207 and 1208 from the visualization_utils.py script to:
if classes[i] in six.viewvalues(category_index[classes[i]-1]):
              class_name = category_index[classes[i]-1]['name']
              
Depending on how you call the third argument of the function .visualize_boxes_and_labels_on_image_array() you may have to play with the offset of -1 in my case here.
If you call the function with an offset of +1, the solution above should work fine.
If you do not call the function with an offset, you would have to replace classes[i] with classes[i]+1 and delete the -1's in the above code.
I hope it can help.

**Comment by jvishnuvardhan** [comment]
@TerryBryant Is this still an issue for you? Is there any actionable PR or anything to update? Please share a standalone code to reproduce the issue. The link in your post is not working. Thanks!
