### ISSUE TITLE
Transpose op only supports 1D-4D input arrays

### ISSUE THREAD

**Issue by Kuloud** [tensorflow/models#7528]
### System information
-  **TensorFlow Lite** _org.tensorflow:tensorflow-lite:0.0.0-nightly_

### Describe the problem
ShuffleNet 
<img alt="Transpose" src="https://img0.didiglobal.com/static/gstar/img/OrXktyYHeF1567591844145.png" width="320">

### Source code / logs

```
2019-09-04 17:32:27.360 21991-22027/android.example.com.tflitecamerademo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: android.example.com.tflitecamerademo, PID: 21991
    java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/transpose.cc Transpose op only supports 1D-4D input arrays.Node number 7 (TRANSPOSE) failed to prepare.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:88)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:61)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:224)
        at com.example.android.tflitecamerademo.ImageClassifier.<init>(ImageClassifier.java:111)
        at com.example.android.tflitecamerademo.QcodeFloatNet.<init>(QcodeFloatNet.java:44)
        at com.example.android.tflitecamerademo.QcodeCameraFragment.lambda$updateActiveModel$0$QcodeCameraFragment(QcodeCameraFragment.java:365)
        at com.example.android.tflitecamerademo.QcodeCameraFragment$$Lambda$0.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Kuloud** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

_Sorry, it's about TensorFlow Lite._

What is the top-level directory of the model you are using N/A
Have I written custom code N/A
OS Platform and Distribution
    Android
TensorFlow installed from N/A
TensorFlow version
    Android AAR 
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce N/A

**Comment by TobinZuo** [comment]
I met this problem too.

**Comment by alanchiao** [comment]
+Jared for prioritization with Shufflenet

**Comment by jdduke** [comment]
Is the reshape node really necessary here? Why does it product a 5D tensor only to go back to a 4D tensor after the transpose?

**Comment by Kuloud** [comment]
ok, I will try this later

**Comment by wujiexiaowugui** [comment]
I met this problem, too.

**Comment by vizakshat** [comment]
> +Jared for prioritization with Shufflenet

+1
