### ISSUE TITLE
have problem after train.py for training faster_rcnn_inception_v2_pets.config

### ISSUE THREAD

**Issue by midimaco** [tensorflow/models#7534]
**System information
What is the top-level directory of the model you are using: tensorflow/models 1.13.0

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit

TensorFlow installed from (source or binary): binary

TensorFlow version (use command below): 1.13.1

Bazel version 

CUDA/cuDNN version : 10.0/ 7.4.2.24

GPU model and memory : GTX 1650 8GB

python 3.6.9**

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\midis\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\midis\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 304, in train
    train_config.optimizer)
  File "C:\tensorflow1\models\research\object_detection\builders\optimizer_builder.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "C:\tensorflow1\models\research\object_detection\builders\optimizer_builder.py", line 112, in _create_learning_rate
    learning_rate_sequence, config.warmup)
  File "C:\tensorflow1\models\research\object_detection\utils\learning_schedules.py", line 160, in manual_stepping
    raise ValueError('First step cannot be zero.')
ValueError: First step cannot be zero.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Exact command to reproduce

**Comment by fsolecki** [comment]
I had a similar issue. I solved it by removing the step 0 from manual_step_learning_rate in config file:
```
train_config {
...
  optimizer {
    momentum_optimizer {
      learning_rate {
        manual_step_learning_rate {
          initial_learning_rate: 0.0002
--          schedule {
--            step: 0
--            learning_rate: 0.0002
--          }
          schedule {
```
