### ISSUE TITLE
MNIST - example model returning CRC error

### ISSUE THREAD

**Issue by momih** [tensorflow/models#756]
```
~/models/tutorials/image/mnist$ python convolutional.py 
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcurand.so.8.0 locally
Extracting data/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "convolutional.py", line 339, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/username/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "convolutional.py", line 136, in main
    train_data = extract_data(train_data_filename, 60000)
  File "convolutional.py", line 83, in extract_data
    buf = bytestream.read(IMAGE_SIZE * IMAGE_SIZE * num_images * NUM_CHANNELS)
  File "/home/username/anaconda2/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/home/username/anaconda2/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/home/username/anaconda2/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x9ef4d52b != 0xd21b010dL

```

I'm getting this error on running the convolutional.py file. 
Built tensorflow from source, these are my stats
```
Operating System - Ubuntu 16.04
CUDA = 8.0
cuDNN = 5.1
Commit hash = 12f279d6f4cb33574bc20109b41eb8a59f40cfd1
Bazel version = 0.4.2
```

I was getting an error on importing tensorflow [same as this question](http://stackoverflow.com/questions/39844772/cxxabi-1-3-8-not-found-in-tensorflow-gpu-install-from-source) so I used Xer's answer and it is able to import correctly now.

**Comment by martinwicke** [comment]
Are you sure the file downloaded properly?

**Comment by szy1900** [comment]
Delete the files that you downloaded and try again

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
