### ISSUE TITLE
Eval.sh crashes for /models/research/feelvos/

### ISSUE THREAD

**Issue by nirat1606** [tensorflow/models#7580]
###System information
* What is the top-level directory of the model you are using: /models/research/feelvos/ 
* Have I written custom code (as opposed to using a stock example script provided in TensorFlow): trying to run /models/research/feelvos/ eval.sh
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat Enterprise Linux Server release 7.7 (Maipo)
* TensorFlow installed from (source or binary): source ,TensorFlow-gpu using pip (python 2.7), installed in a conda image
* TensorFlow version (use command below): 1.14.0
* Bazel version (if compiling from source): N/A
* CUDA/cuDNN version: no gpu acceleration used (although Cuda 9.2)
* GPU model and memory: no gpu acceleration used
* Exact command to reproduce: from the folder /models/research/feelvos/ , run the file ./eval.sh

###Describe the problem

Followed the exact instructions to setup /models/research/feelvos/.

While running the code, specifically deeplab setup gives the warning:

WARNING:tensorflow:Entity <bound method Conv2D.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f66d85b9650>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2D.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f66d85b9650>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0918 12:56:49.175844 140085883610944 ag_logging.py:145] Entity <bound method Conv2D.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f66d85b9650>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2D.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f66d85b9650>>: AssertionError: Bad argument number for Name: 3, expecting 4

It gives error in /models/research/feelvos/ vis_video.py. If I debug, at line 
Res = session.run(ops)

###Source code / logs
And then the code crashes giving the error:
Traceback (most recent call last):
  File "/nirat/feelVOS/python2/feelvos/vis_video.py", line 500, in <module>
    tf.app.run()
  File "/nirat/anaconda3/envs/feelvos1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/nirat/anaconda3/envs/feelvos1/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/nirat/anaconda3/envs/feelvos1/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/nirat/feelVOS/python2/feelvos/vis_video.py", line 480, in main
    all_ious = np.concatenate(all_ious, axis=0)
ValueError: need at least one array to concatenate

**Comment by andyzoujm** [comment]
I tried using gast 0.2.2 and that resolved the error. Also check your dataset folder tfrecord for val: if it's empty then try re-converting the data.
