### ISSUE TITLE
在运行train.py的时候image/encoded没有找到

### ISSUE THREAD

**Issue by m1018** [tensorflow/models#7583]
运行train.py，方式生错误：
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 181, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/object_detection/models/research/object_detection/data/maxiaochao/tensorflow_api_kitti/dataset/models-master/research/lstm_object_detection/trainer.py", line 409, in train
    saver=saver)
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 785, in train
    ignore_live_threads=ignore_live_threads)
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/tensorflow/python/training/supervisor.py", line 832, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1257, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/nlu/anaconda3/envs/object_detection/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Feature list 'image/encoded' is required but could not be found.  Did you mean to include it in feature_list_dense_missing_assumed_empty or feature_list_dense_defaults?
	 [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
主要就是说image/encoded没有找到，请问这是为什么呢

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xiuzhizheng** [comment]
您好，请问解决了嘛？我也是到这一步报错，另外你的tfrecord是怎么准备的,可以分享下嘛

**Comment by meikorol** [comment]
> 您好，请问解决了嘛？我也是到这一步报错，另外你的tfrecord是怎么准备的,可以分享下嘛

您好，请问这个代码怎么训练呀，能指导一下吗

**Comment by meikorol** [comment]
您好，请问这个代码怎么训练呀，能指导一下吗
