### ISSUE TITLE
Official recommendation model execution

### ISSUE THREAD

**Issue by ktfth** [tensorflow/models#7597]
Versions: v2.0.0-rc1-51-g2646d23 2.0.0-rc2

## Description

I0923 19:05:14.079890 140264431634240 movielens.py:107] Dataset ml-1m has already been downloaded
I0923 19:05:14.080133 140264431634240 data_preprocessing.py:201] Beginning data preprocessing.
Traceback (most recent call last):
  File "ncf_keras_main.py", line 523, in <module>
    app.run(main)
  File "/home/ktfth/anaconda3/envs/tfv2/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ktfth/anaconda3/envs/tfv2/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "ncf_keras_main.py", line 518, in main
    run_ncf(FLAGS)
  File "ncf_keras_main.py", line 239, in run_ncf
    num_users, num_items, _, _, producer = ncf_common.get_inputs(params)
  File "/home/ktfth/war/models/official/recommendation/ncf_common.py", line 61, in get_inputs
    deterministic=FLAGS.seed is not None)
  File "/home/ktfth/war/models/official/recommendation/data_preprocessing.py", line 236, in instantiate_pipeline
    create_data_offline=generate_data_offline)
  File "/home/ktfth/war/models/official/recommendation/data_pipeline.py", line 854, in __init__
    super(BisectionDataConstructor, self).__init__(*args, **kwargs)
  File "/home/ktfth/war/models/official/recommendation/data_pipeline.py", line 417, in __init__
    eval_batch_size, 1 + rconst.NUM_EVAL_NEGATIVES))
ValueError: Eval batch size 256 is not divisible by 1000

On "python ncf_keras_main.py"

**Comment by saberkun** [comment]
I think 256 might be the problem.
Can you try the params in https://github.com/tensorflow/models/blob/master/official/recommendation/ncf_keras_benchmark.py#L83?

**Comment by saberkun** [comment]
Eval flag should be multiple of 1000 due to implementation detail
