### ISSUE TITLE
official/Recommendation/ncf_keras_main.py: queue.Empty Error!

### ISSUE THREAD

**Issue by Beheshtian** [tensorflow/models#7608]
[run_0.log](https://github.com/tensorflow/models/files/3662935/run_0.log)

------------------------

### System information
- **What is the top-level directory of the model you are using**: tensorflow/models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: pip3 install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.14.0
- **Bazel version (if compiling from source)**: No
- **CUDA/cuDNN version**: cuda 10.0 / cudnn 7
- **GPU model and memory**:  Geforce GT 710 / 2gb
- **Exact command to reproduce**: run ncf_keras_main.py with python 3.6.8

### Describe the problem
Dear Experts
I changed distribution_strategy='off' and verbose=0 in ncf_keras_main.py.
When i run ncf_keras_main.py or run sh run.sh with keras parameter, queue.Empty Error will be occurred!  (ncf_estimator_main.py works well)
Could you help me to solve the problem?
Regards

### Source code / logs

Source code: ncf_keras_main.py

Logs:

2019-09-25 21:03:25.764677: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-09-25 21:08:25.878088: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: Empty: 
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/5026FB7C1CD2D899/PycharmProjects/models/official/recommendation/data_pipeline.py", line 248, in data_generator
    yield self._result_queue.get(timeout=300)

  File "/usr/lib/python3.6/queue.py", line 172, in get
    raise Empty

queue.Empty

Traceback (most recent call last):
  File "/mnt/5026FB7C1CD2D899/PycharmProjects/models/official/recommendation/ncf_keras_main.py", line 518, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/mnt/5026FB7C1CD2D899/PycharmProjects/models/official/recommendation/ncf_keras_main.py", line 513, in main
    run_ncf(FLAGS)
  File "/mnt/5026FB7C1CD2D899/PycharmProjects/models/official/recommendation/ncf_keras_main.py", line 307, in run_ncf
    verbose=0)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 274, in model_iteration
    batch_outs = f(actual_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Empty: 
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/5026FB7C1CD2D899/PycharmProjects/models/official/recommendation/data_pipeline.py", line 248, in data_generator
    yield self._result_queue.get(timeout=300)

  File "/usr/lib/python3.6/queue.py", line 172, in get
    raise Empty

queue.Empty

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_149]]
  (1) Unknown: Empty: 
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/mnt/5026FB7C1CD2D899/PycharmProjects/models/official/recommendation/data_pipeline.py", line 248, in data_generator
    yield self._result_queue.get(timeout=300)

  File "/usr/lib/python3.6/queue.py", line 172, in get
    raise Empty

queue.Empty

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

**Comment by Beheshtian** [comment]
No answer from Tensorflow members?!
