### ISSUE TITLE
Syntaxnet fails to build with GPU

### ISSUE THREAD

**Issue by HITalexwang** [tensorflow/models#762]
I am trying to build syntaxnet with GPU following instructions given in #248 ,
My bazel version is 0.3.1 and my syntaxnet code is the latest one. 
Firstly, I run `./configure` in `models/syntaxnet/tensorflow` and got

```
~/work/parser/syntaxnet_gpu/models/syntaxnet/tensorflow ~/work/parser/syntaxnet_gpu/models/syntaxnet/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/lib/python2.7/site-packages
  /usr/lib64/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python2.7/site-packages]
/usr/lib/python2.7/site-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda
Invalid path to CUDA 7.5 toolkit. /usr/local/cuda/lib64/libcudart.so.7.5 cannot be found
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-7.5
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda-7.5]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
WARNING: Output base '/users2/yxwang/.cache/bazel/_bazel_yxwang/6c66e48e47519106aae985305d5b165b' is on NFS. This may lead to surprising failures and undetermined behavior.
..
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: /users2/yxwang/.cache/bazel/_bazel_yxwang/6c66e48e47519106aae985305d5b165b/server (Directory not empty).
WARNING: Output base '/users2/yxwang/.cache/bazel/_bazel_yxwang/6c66e48e47519106aae985305d5b165b' is on NFS. This may lead to surprising failures and undetermined behavior.
..
INFO: Waiting for response from Bazel server (pid 85082)...
INFO: All external dependencies fetched successfully.
Configuration finished
```

Then I changed `crosstool_top` in `tools/bazel.rc` to `crosstool_top=@org_tensorflow//third_party/gpus/crosstool` following the instruction and run
`bazel test -c opt --config=cuda --define using_cuda_nvcc=true --define using_gcudacc=true syntaxnet/... util/utf8/...` in `models/syntaxnet`, then I got:

```
WARNING: Output base '/users2/yxwang/.cache/bazel/_bazel_yxwang/4d49ea334491d8c9391f9a5b10fd5be4' is on NFS. This may lead to surprising failures and undetermined behavior.
.............................
INFO: Waiting for response from Bazel server (pid 119165)...
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@8a68f730' (requested by nodes 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@882e0af1', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@efbf945f', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@c4f82afd')
INFO: Elapsed time: 80.649s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@8a68f730' (requested by nodes 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@882e0af1', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@efbf945f', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@c4f82afd')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool': target 'crosstool' not declared in package 'third_party/gpus/crosstool' defined by /users2/yxwang/.cache/bazel/_bazel_yxwang/4d49ea334491d8c9391f9a5b10fd5be4/external/org_tensorflow/third_party/gpus/crosstool/BUILD
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:179)
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.findCrosstoolConfiguration(CrosstoolConfigurationLoader.java:239)
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.readCrosstool(CrosstoolConfigurationLoader.java:281)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:128)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:73)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:48)
        at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:78)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1016)
        ... 4 more
Caused by: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool': target 'crosstool' not declared in package 'third_party/gpus/crosstool' defined by /users2/yxwang/.cache/bazel/_bazel_yxwang/4d49ea334491d8c9391f9a5b10fd5be4/external/org_tensorflow/third_party/gpus/crosstool/BUILD
        at com.google.devtools.build.lib.packages.Package.makeNoSuchTargetException(Package.java:559)
        at com.google.devtools.build.lib.packages.Package.getTarget(Package.java:543)
        at com.google.devtools.build.lib.skyframe.SkyframePackageLoaderWithValueEnvironment.getTarget(SkyframePackageLoaderWithValueEnvironment.java:71)
        at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction$ConfigurationBuilderEnvironment.getTarget(ConfigurationFragmentFunction.java:193)
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:177)
        ... 11 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@8a68f730' (requested by nodes 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@882e0af1', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@efbf945f', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@c4f82afd')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool': target 'crosstool' not declared in package 'third_party/gpus/crosstool' defined by /users2/yxwang/.cache/bazel/_bazel_yxwang/4d49ea334491d8c9391f9a5b10fd5be4/external/org_tensorflow/third_party/gpus/crosstool/BUILD
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:179)
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.findCrosstoolConfiguration(CrosstoolConfigurationLoader.java:239)
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.readCrosstool(CrosstoolConfigurationLoader.java:281)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:128)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:73)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:48)
        at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:78)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1016)
        ... 4 more
Caused by: com.google.devtools.build.lib.packages.NoSuchTargetException: no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool': target 'crosstool' not declared in package 'third_party/gpus/crosstool' defined by /users2/yxwang/.cache/bazel/_bazel_yxwang/4d49ea334491d8c9391f9a5b10fd5be4/external/org_tensorflow/third_party/gpus/crosstool/BUILD
        at com.google.devtools.build.lib.packages.Package.makeNoSuchTargetException(Package.java:559)
        at com.google.devtools.build.lib.packages.Package.getTarget(Package.java:543)
        at com.google.devtools.build.lib.skyframe.SkyframePackageLoaderWithValueEnvironment.getTarget(SkyframePackageLoaderWithValueEnvironment.java:71)
        at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction$ConfigurationBuilderEnvironment.getTarget(ConfigurationFragmentFunction.java:193)
        at com.google.devtools.build.lib.rules.cpp.CrosstoolConfigurationLoader.getCrosstoolProtofromBuildFile(CrosstoolConfigurationLoader.java:177)
        ... 11 more
```
I noticed that when I run `./configure` in `models/syntaxnet/tensorflow`, the bazel output base is `.cache/bazel/_bazel_yxwang/6c66e48e47519106aae985305d5b165b`.
However when I run `bazel test -c opt --config=cuda --define using_cuda_nvcc=true --define using_gcudacc=true syntaxnet/... util/utf8/...` in `models/syntaxnet` the bazel output base is `.cache/bazel/_bazel_yxwang/4d49ea334491d8c9391f9a5b10fd5be4`. 
I thought that maybe the reason why it couldn't find target 'crosstool' when building syntaxnet. But I don't know how to fix it, can anyone help me?
BTW, I am able to build syntaxnet with CPU and tensorflow with GPU separately.

**Comment by aselle** [comment]
@benoitsteiner , @andydavis1, I believe we don't have used Xeon Phi, correct?

**Comment by ducdauge** [comment]
After the recent Tensorflow release (1.0), the solution in #248 is not viable anymore apparently. Some files that @David-Ba suggested to edit are missing, e.g. `tensorflow/third_party/gpus/crosstool/CROSSTOOL`. In fact, downgrading to previous releases is inadvisable, since this would hamper the processing speed a lot. So, does anybody know how to build SyntaxNet with actual GPU support and Tensorflow r1.0?

**Comment by utkrist** [comment]
Please suggest way to build it in the new tensorflow. I was able to install syntaxnet in the previous version it seems to be broken after I upgraded to tensorflow 1.0

**Comment by TheodoreGalanos** [comment]
I was wondering if there is any news on this, been having exactly the same error. I followed advice of adding information to make files and changing directories to where they are pointing but it didn't work.

I know I'm probably a rare case but I still haven't been able to properly build syntaxnet, in either TF versions, with or without GPU, without getting Bazel failing during building.

Can anyone perhaps point me to a viable way of installing in Ubuntu 16.04? I'd really like to test this.

Thanks in advance!
Kind regards,
Theodore.

**Comment by dsshean** [comment]
I was able to successfully able to build it with the following steps:

Start with a clean install of ubuntu 16.10:
#install dependencies
sudo apt-get install -y python-pip python-dev &&
sudo apt-get install -y  libblas-dev liblapack-dev &&
sudo apt-get install -y  libcupti-dev &&
sudo apt-get install -y  swig &&
sudo pip install asciitree &&
sudo pip install mock &&
sudo pip install numpy &&
sudo pip install -U protobuf==3.0.0b2 &&
sudo apt-get install -y graphviz libgraphviz-dev &&
sudo pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
sudo apt-get install -y python-software-properties
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
# GCC 4.9 and 6 both fail use 5.
sudo apt-get install -y gcc-5 &&
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 &&
sudo apt-get install -y g++-5 &&
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50 

#Install cuda 8.0 - auto installs JDK8 make sure default ver is 8
#Install cudnn 5.1
#install bazel 0.4.2 use deb file non JDK version

export PATH=/usr/local/cuda/bin:$PATH
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${CUDA_HOME}/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export PATH=${CUDA_HOME}/bin:${PATH}
export PATH=/tmp/bazeltemp/bin:$PATH
export CUDNN_HOME=${CUDA_HOME}
export TEST_TMPDIR=/tmp/bazeltemp
export TF_NEED_CUDA=1
export CUDA_TOOLKIT_PATH=$CUDA_HOME
export TF_CUDA_VERSION=8.0
export TF_CUDNN_VERSION=5
export CUDNN_INSTALL_PATH=$CUDA_HOME

git clone --recursive https://github.com/tensorflow/models.git
cd models/syntaxnet/tensorflow
./configure
cd ..

Follow the recommended edits and troubleshooting such as NCCL missing errors in:
https://github.com/tensorflow/models/issues/248
# build
bazel test -c opt --config=cuda --define using_cuda_nvcc=true --define using_gcudacc=true syntaxnet/... util/utf8/...

Good luck

**Comment by michaelisard** [comment]
Does this solve the problem adequately for the others on the thread?

**Comment by udnaan** [comment]
Another workaround is to separately build and installed tensorflow with GPU support. Then use the same git-ref to build and install SyntaxNet. Tested on MacOS.

**Comment by mingxingtan** [comment]
Close due to inactivity. 

Please switch to the latest tensorlfow, but if you still have issues, please feel free to reopen it.
