### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found

### ISSUE THREAD

**Issue by suyali** [tensorflow/models#7638]
I want to use the API to retrain ssd_mobilenet,got the following error:

Traceback (most recent call last):
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: indices[0] = 0 is not in [0, 0)
	 [[{{node GatherV2_4}}]]
	 [[IteratorGetNext]]
	 [[Loss/non_max_suppression/NonMaxSuppressionV3/_9297]]
  (1) Invalid argument: indices[0] = 0 is not in [0, 0)
	 [[{{node GatherV2_4}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1192, in _train_model_default
    saving_listeners)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1484, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: indices[0] = 0 is not in [0, 0)
	 [[{{node GatherV2_4}}]]
	 [[IteratorGetNext]]
	 [[Loss/non_max_suppression/NonMaxSuppressionV3/_9297]]
  (1) Invalid argument: indices[0] = 0 is not in [0, 0)
	 [[{{node GatherV2_4}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

anyone know how to deal with this?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Tanmay-Kulkarni101** [comment]
Hey, I am running the ssd_mobilenet_v3_small_coco_2019_08_14 model on Google colab and I am facing the same error. 
`tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node Dataset_map_process_fn_70}} indices[0] = 0 is not in [0, 0)
	 [[{{node GatherV2_4}}]]
	 [[IteratorGetNext]]
`
Can someone help me out.

**Comment by y-ichilab** [comment]
I had the same problem.
In my case, this occurred because the number of annotations and the number of labels did not match when the source code was written and TFRecord was generated.
For example, if there are 3 annotations, it will be a tfrecord with the following content.

feature {
    key: "image/object/bbox/xmax"
    value {
      float_list {
        value: 0.03671874850988388
        value: 0.12890625
        value: 0.13437500596046448
      }
    }
  }

'xmin', 'ymax', 'ymin' have the same format.

At this time, 'class / label' and 'class / text' must have the same number of lists.

  feature {
    key: "image/object/class/label"
    value {
      int64_list {
        value: 0
        value: 1
        value: 2
      }
    }
  }
feature {
    key: "image/object/class/text"
    value {
      bytes_list {
        value: "Dog"
        value: "Cat"
        value: "Person"
      }
    }
  }


I wish you every success.

**Comment by rachellaserzhao** [comment]
I had the same problem when I changed the number of annotations. How do I modify the layers to accommodate the number shape?  Is there a way to regenerate the tfrecord?

**Comment by forkbabu** [comment]
Any updates on this? Facing the same issue.

**Comment by Tanmay-Kulkarni101** [comment]
Did you try this [SO](https://stackoverflow.com/questions/46940073/tensorflow-object-detection-aborts-with-invalidargumenterror-indices0-2-is) link. It worked for my code. I have posted my solution [here](https://github.com/tensorflow/tensorflow/issues/17353#issuecomment-553255953).

**Comment by 2008hsk** [comment]
I have encountered with same error. The reason was that one of my examples has a wrong annotation. Its xmin was greater than its xmax. After I corrected it, I went on training.
