### ISSUE TITLE
[TF2]'Tensor' object has no attribute '_keras_history'   

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/models#7643]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:2.0-GPU
- **CUDA/cuDNN version**:9.6
- **GPU model and memory**:
- **Exact command to reproduce**:

### Problem
in TF2.0 use Keras to save model.h5 ,then load model.h5.

I have saved **model.h5** from **official.nlp.bert_models.py** by use model.save("model.h5") .
everything is ok , but when I load the **model.h5** there have some problems.
```python

model =tf.keras.models.load_model('./my_model1.h5', custom_objects={'BertModel':bert_modeling.BertModel})
```

emmmmm, how to solve this problem???? 

### Traceback 
Traceback (most recent call last):
  File "/Users/lollipop/Documents/tf2g/false_news/test.py", line 30, in <module>
    model =tf.keras.models.load_model('./my_model1.h5', custom_objects={'BertModel':bert_modeling.BertModel})
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
    config, custom_objects)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1852, in reconstruct_from_config
    process_node(layer, node_data)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1802, in process_node
    output_index = nest.flatten(output_tensors)[0]._keras_history.node_index
AttributeError: 'Tensor' object has no attribute '_keras_history'

Process finished with exit code 1

**Comment by saberkun** [comment]
Please file this issue to tensorflow repo. It looks like a bug

**Comment by saberkun** [comment]
I think saving as tf savedmodel will work. Could you use tf format? (which is the trend to consolidate serialization to savedmodel)

**Comment by SmileTM** [comment]
@saberkun 

> I think saving as tf savedmodel will work. Could you use tf format? (which is the trend to consolidate serialization to savedmodel)

yes，**tf.saved_model** successed save and load. But I think the way is too complex.

**Comment by saberkun** [comment]
Hmmm. your keras model can use model.save(). There is an option to save/load as TF savedmodel (is it by default already?). It will just replace h5.

**Comment by SmileTM** [comment]
> Hmmm. your keras model can use model.save(). There is an option to save/load as TF savedmodel (is it by default already?). It will just replace h5.

yes, I found the document  it is already default to TF savedmodel .  But, I used model.save('XXX.h5'), so it saved as XXX.h5  . If I  use model.save('XXX), it wil save as TF savedmodel . Thanks.
```python
model.save('./model_out')
load=tf.keras.models.load_model('./model_out')
```
### problem
But I have another problem. I think this may be the format problem I entered, but I don't know how to modify it. Or is the first method the recommended method? But in my simple single-input model, these three methods all works.  
```python
test_input_ids   = np.load('./data/test/input_ids.npy')[:10]
test_input_masks = np.load('./data/test/input_masks.npy')[:10]
test_segment_ids = np.load('./data/test/segment_ids.npy')[:10]

test_input_word_ids =tf.convert_to_tensor(test_input_ids, dtype=tf.int32)
test_input_masks     =tf.convert_to_tensor(test_input_masks, dtype=tf.int32)
test_input_type_ids =tf.convert_to_tensor(test_segment_ids, dtype=tf.int32)
```
**One** ：In this way ,it works well.
```python
loaded=tf.keras.models.load_model('./model_out')  
or
loaded = tf.saved_model.load('./model_out')

infer = loaded.signatures["serving_default"]
predict = infer(input_mask=test_input_masks,input_type_ids=test_input_type_ids,input_word_ids=test_input_word_ids)
```
**Second**：In this way，it has some problem
```python
loaded=tf.keras.models.load_model('./model_out')  
or
loaded = tf.saved_model.load('./model_out')
loaded(input_mask=test_input_masks,input_type_ids=test_input_type_ids,input_word_ids=test_input_word_ids)
```
```
Traceback (most recent call last):
  File "/Users/lollipop/Documents/tf2g/false_news/test.py", line 49, in <module>
    pre = loaded(input_mask=test_input_masks,input_type_ids=test_input_type_ids,input_word_ids=test_input_word_ids)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 436, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 262, in restored_function_body
    "\n\n".join(signature_descriptions)))
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * False
    * None
  Keyword arguments: {'input_mask': <tf.Tensor 'input_mask:0' shape=(10, 256) dtype=int32>, 'input_type_ids': <tf.Tensor 'input_type_ids:0' shape=(10, 256) dtype=int32>, 'input_word_ids': <tf.Tensor 'input_word_ids:0' shape=(10, 256) dtype=int32>}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, 256), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='inputs/2')]
    * False
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, 256), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='inputs/2')]
    * True
    * None
  Keyword arguments: {}

Option 3:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, 256), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='input_type_ids'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='input_word_ids')]
    * True
    * None
  Keyword arguments: {}

Option 4:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, 256), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='input_type_ids'), TensorSpec(shape=(None, 256), dtype=tf.int32, name='input_word_ids')]
    * False
    * None
  Keyword arguments: {}
Process finished with exit code 1
```
**Third**：In this way，it also has some problem
```python
loaded=tf.keras.models.load_model('./model_out')  
loaded(input_mask=test_input_masks,input_type_ids=test_input_type_ids,input_word_ids=test_input_word_ids)
```
```
Traceback (most recent call last):
  File "/Users/lollipop/Documents/tf2g/false_news/test.py", line 49, in <module>
    pre = loaded(input_mask=test_input_masks,input_type_ids=test_input_type_ids,input_word_ids=test_input_word_ids)
TypeError: __call__() missing 1 required positional argument: 'inputs'
```

**Comment by saberkun** [comment]
Hmmm, I indeed only used `infer = loaded.signatures["serving_default"]`. Maybe need to inspect the savedmodel. @karmel Can keras team take a look at this?
BTW, the savedmodel file can be used as model.load() to restore model variables/states.

**Comment by saberkun** [comment]
Close as the TF issue is closed.
