### ISSUE TITLE
indices[24,16] = 33825 is not in [0, 33708) problem

### ISSUE THREAD

**Issue by skumyol** [tensorflow/models#7649]
### System information
- **What is the top-level directory of the model you are using**: models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux CentOS 7
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: tf-nightly==2.1.0.dev20191009
- **Bazel version NA:
- **CUDA/cuDNN NA*:
- **GPU model NA*:
-

### Describe the problem
Hi, 
I'm using the same setup you provide for v2 however, I always get a dimension error. I tried to delete the last empty line of the vocab file and change its suffix from 32768 to 33945 and it didn't work either. I have no idea about what is going wrong here. 

###command 
python3 transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET \
    --train_steps=100000 --steps_between_evals=5000 \
    --batch_size=4096 --max_length=64 \
    --bleu_source=$DATA_DIR/newstest2014.en \
    --bleu_ref=$DATA_DIR/newstest2014.de \
    --num_gpus=0 \
    --enable_time_history=false

### The invalid argument error before  epoch starts
W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: indices[32,35] = 33723 is not in [0, 33708)
]
### Source code / logs
`[[{{node model/transformer_v2/Transformer/encode/embedding_shared_weights/embedding/Gather}}]]
   1/5000 [..............................] - ETA: 424:03:16Traceback (most recent call last):
  File "transformer_main.py", line 471, in <module>
    app.run(main)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 460, in main
    _run_task(task)
  File "transformer_main.py", line 451, in _run_task
    task.train()
  File "transformer_main.py", line 326, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[24,16] = 33825 is not in [0, 33708)
	 [[node model/transformer_v2/Transformer/encode/embedding_shared_weights/embedding/Gather (defined at /homes/skumyol/v36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_distributed_function_37379]
`

**Comment by saberkun** [comment]
You need to change model params. The vocab dimension is not defined by lines in vocab

**Comment by ravikyram** [comment]
@skumyol 

Is this still an issue. Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
