### ISSUE TITLE
inception model training failing due to a ValueError

### ISSUE THREAD

**Issue by akshayc11** [tensorflow/models#767]
## Please let us know which model this issue is about (specify the top-level directory)
Directory: tensorflow/models/inception

I have been trying to run the inception-net model following the instructions in the README.md.
`$ bazel-bin/inception/imagenet_train --num_gpus=2 --batch_size=128 --train_dir=/data-local/akshayc/imagenet_train --data_dir="${DATA_DIR}"`
However, I get the following error:
```
Traceback (most recent call last):
  File "/home/akshayc/tensorflow-source/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>
    tf.app.run()
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/akshayc/tensorflow-source/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/akshayc/tensorflow-source/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 239, in train
    scope)
  File "/home/akshayc/tensorflow-source/tensorflow/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 124, in _tower_loss
    loss_averages_op = loss_averages.apply(losses + [total_loss])
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/akshayc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable tower_1/tower_1/CrossEntropyLoss/value/avg/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

```

Any idea what is happening here?

Thanks

**Comment by aselle** [comment]
What version of tensorflow did you use? What operating system?

**Comment by honeytidy** [comment]
I got the same error and the tensorflow version is 0.12.0

**Comment by akshayc11** [comment]
OS: Ubuntu 14.04 
TF version: 0.12.0-rc1

**Comment by akshayc11** [comment]
#778 solves the issue as mentioned by @honeytidy .

**Comment by aselle** [comment]
Ok, when that is merged we will close this. Thanks for the update.

**Comment by yuefengz** [comment]
Merged, closing this issue.
