### ISSUE TITLE
AttributeError: Cannot set the property experimental_allow_stateful on Options

### ISSUE THREAD

**Issue by lucapas** [tensorflow/models#7684]
python version 3.6.8
tensorflow version 2.0.0

i followed this guide: https://github.com/tensorflow/models/tree/master/official/vision/image_classification

when i run this: python resnet_cifar_main.py
i have this error:
    "Cannot set the property %s on %s." % (name, type(self).__name__))
AttributeError: Cannot set the property experimental_allow_stateful on Options.

logs:

Contrib missing: Skip remove monkey patch tf.contrib.distribute.*
2019-10-17 18:58:53.401697: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-17 18:58:53.411646: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2295670000 Hz
2019-10-17 18:58:53.412014: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x50d6d50 executing computations on platform Host. Devices:
2019-10-17 18:58:53.412060: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/image_ops_impl.py:1518: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W1017 18:58:53.800010 139969621636928 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/image_ops_impl.py:1518: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py:332: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W1017 18:58:53.801689 139969621636928 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py:332: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Traceback (most recent call last):
  File "resnet_cifar_main.py", line 242, in <module>
    absl_app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "resnet_cifar_main.py", line 236, in main
    return run(flags.FLAGS)
  File "resnet_cifar_main.py", line 142, in run
    drop_remainder=(not flags_obj.enable_get_next_as_optional))
  File "/home/luca/TensorFlowOnSpark/examples/resnet/models/official/vision/image_classification/cifar_preprocessing.py", line 163, in input_fn
    drop_remainder=drop_remainder
  File "/home/luca/TensorFlowOnSpark/examples/resnet/models/official/vision/image_classification/imagenet_preprocessing.py", line 138, in process_record_dataset
    options.experimental_allow_stateful = True
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/util/options.py", line 56, in __setattr__
    "Cannot set the property %s on %s." % (name, type(self).__name__))
AttributeError: Cannot set the property experimental_allow_stateful on Options.

**Comment by saberkun** [comment]
experimental_allow_stateful is not in TF2.0
It will be inside coming TF2.1.
Please use TF nightly or using this release branch: https://github.com/tensorflow/models/releases/tag/v2.0

**Comment by methylome** [comment]
I am using tf-nightly, but got the same error.

**Comment by lucapas** [comment]
yes, i downloaded this https://github.com/tensorflow/models/releases/tag/v2.0 and it works

**Comment by methylome** [comment]
@lucapas Have you updated tf using pip install tf-nightly? I did this and downloaded v2.0. However I had no luck to succeed as follows:

python resnet_imagenet_main.py --data_dir=/new_project/databases/imagenet/train
Contrib missing: Skip remove monkey patch tf.contrib.distribute.*
2019-10-28 19:09:17.623628: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-10-28 19:09:17.655035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Found device 0 with properties: 
name: Tesla V100-PCIE-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:86:00.0
2019-10-28 19:09:17.655146: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:/home/cjh/local/lib:/home/cjh/local/lib64:.:/home/cjh/local/lib:/home/cjh/local/lib64:/usr/local/cuda/lib64
2019-10-28 19:09:17.655205: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:/home/cjh/local/lib:/home/cjh/local/lib64:.:/home/cjh/local/lib:/home/cjh/local/lib64:/usr/local/cuda/lib64
2019-10-28 19:09:17.655260: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:/home/cjh/local/lib:/home/cjh/local/lib64:.:/home/cjh/local/lib:/home/cjh/local/lib64:/usr/local/cuda/lib64
2019-10-28 19:09:17.655315: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:/home/cjh/local/lib:/home/cjh/local/lib64:.:/home/cjh/local/lib:/home/cjh/local/lib64:/usr/local/cuda/lib64
2019-10-28 19:09:17.655368: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:/home/cjh/local/lib:/home/cjh/local/lib64:.:/home/cjh/local/lib:/home/cjh/local/lib64:/usr/local/cuda/lib64
2019-10-28 19:09:17.655421: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:/home/cjh/local/lib:/home/cjh/local/lib64:.:/home/cjh/local/lib:/home/cjh/local/lib64:/usr/local/cuda/lib64
2019-10-28 19:09:17.659117: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-28 19:09:17.659137: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1569] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2019-10-28 19:09:17.659390: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-10-28 19:09:17.681987: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz
2019-10-28 19:09:17.690046: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f9907bc920 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-28 19:09:17.690086: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-10-28 19:09:17.815276: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f990821be0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2019-10-28 19:09:17.815345: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-PCIE-16GB, Compute Capability 7.0
2019-10-28 19:09:17.815522: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1087] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-28 19:09:17.815541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1093]      
WARNING:tensorflow:From /opt/anaconda3/envs/tensorflow21-models/lib/python3.6/site-packages/tensorflow_core/python/ops/image_ops_impl.py:2522: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
W1028 19:09:18.380892 140219324237632 deprecation.py:323] From /opt/anaconda3/envs/tensorflow21-models/lib/python3.6/site-packages/tensorflow_core/python/ops/image_ops_impl.py:2522: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
Traceback (most recent call last):
  File "resnet_imagenet_main.py", line 271, in <module>
    app.run(main)
  File "/opt/anaconda3/envs/tensorflow21-models/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/anaconda3/envs/tensorflow21-models/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "resnet_imagenet_main.py", line 264, in main
    stats = run(flags.FLAGS)
  File "resnet_imagenet_main.py", line 130, in run
    tf_data_experimental_slack=flags_obj.tf_data_experimental_slack,
  File "/opt/anaconda3/envs/tensorflow21-models/lib/python3.6/site-packages/official/vision/image_classification/imagenet_preprocessing.py", line 322, in input_fn
    tf_data_experimental_slack=tf_data_experimental_slack,
  File "/opt/anaconda3/envs/tensorflow21-models/lib/python3.6/site-packages/official/vision/image_classification/imagenet_preprocessing.py", line 138, in process_record_dataset
    options.experimental_allow_stateful = True
  File "/opt/anaconda3/envs/tensorflow21-models/lib/python3.6/site-packages/tensorflow_core/python/data/util/options.py", line 56, in __setattr__
    "Cannot set the property %s on %s." % (name, type(self).__name__))
AttributeError: Cannot set the property experimental_allow_stateful on Options.

**Comment by methylome** [comment]
The following steps are working as described on https://medium.com/@shaolinkhoa/install-tensorflow-gpu-2-0-alpha-on-anaconda-for-windows-10-ubuntu-ced099010b21 .

1. conda create -n your_env_name python=3.6 cudnn cupti cudatoolkit=10.0
2. conda activate your_env_name
3. pip install tensorflow-gpu=2.0.0
4. python-dateutil=2.6.1 pytz=2017.2 requests
5. export PYTHOPATH=models-2.0
6. cd models-2.0/official/vision/image_classification
7.  python resnet_imagenet_main.py --data_dir=train

However, I ran into the following error:
tensorflow.python.framework.errors_impl.NotFoundError:  train/train-00198-of-01024; No such file or directory

**Comment by lucapas** [comment]
i used  Tensorflow 2.0.0
i downloaded this: https://github.com/tensorflow/models/archive/v2.0.zip
you can try with this: python resnet_imagenet_main.py --data_dir=train --num_gpus=0 --train_epochs=1

**Comment by methylome** [comment]
My question is how the train directory is formed.  My train directory has a bunch of subdirectories starting with n, e.g., n01440764, which contains *.jpeg.
