### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

### ISSUE THREAD

**Issue by janardana-raj1901** [tensorflow/models#7703]
![Screenshot (25)](https://user-images.githubusercontent.com/56503339/67268910-3bcbce80-f4d3-11e9-9d2e-989e1e3b9a35.png)

**Comment by janardana-raj1901** [comment]
> ![Image 5](https://user-images.githubusercontent.com/56503339/67270024-6cad0300-f4d5-11e9-9137-aeed7aeb5fa8.png)
> 
> Please do rectify it...

**Comment by saberkun** [comment]
Hi, what TF version do you use?

**Comment by IDNinja** [comment]
I have the same issue! TF version 2.

**Comment by saberkun** [comment]
Hi Guys,
I think all object detection notebooks and models have not been verified with TF 2.0.
For example, the session will be implicit in TF2.
Would you please try tf.disable_v2_behavior() + import tensorflow.compat.v1 as tf?

**Comment by milanlanlan** [comment]
python -m pip install tensorflow==1.14 will help. 
Of course if u want to use TF2, u need to update the code

**Comment by saberkun** [comment]
Yes, there might be some symbols disappeared in TF2 default behavior. 
Using 1.15 should be fine. 
I am just curious that if using TF 2.x in compat mode: tf.disable_v2_behavior() + import tensorflow.compat.v1 as tf will still work. In such case, you don't need to install 2 versions.

**Comment by hdmthao** [comment]
> Yes, there might be some symbols disappeared in TF2 default behavior.
> Using 1.15 should be fine.
> I am just curious that if using TF 2.x in compat mode: tf.disable_v2_behavior() + import tensorflow.compat.v1 as tf will still work. In such case, you don't need to install 2 versions.

I tested using: import tensorflow.compat.v1 as tf. And it work.

**Comment by saberkun** [comment]
Thanks! I update the title of this issue so that everyone can notice this to handle compatibility issue with TF 2.x. In theory, compat mode will be fine if there is no tf.contrib. TF 2 or TF 1.x share the same underlying TF runtime.

**Comment by kaeskaeshaan** [comment]
i got the same error

**Comment by ericjiang18** [comment]
same error :(

**Comment by PortScanner** [comment]
od_graph_def = tf.compat.v1.GraphDef()
works for me, but...
tf.compat.v1.io.gfile.GFile() does not work!
gfile is moved to tf.io in tensorflow-2., but how to import this?

**Comment by hdmthao** [comment]
> od_graph_def = tf.compat.v1.GraphDef()
> works for me, but...
> tf.compat.v1.io.gfile.GFile() does not work!
> gfile is moved to tf.io in tensorflow-2., but how to import this?
You just need  tf.io.gfile.GFile()

**Comment by PortScanner** [comment]
PATH_TO_FROZEN_GRAPH = 'D:/models/research/object_detection/' + MODEL_NAME + '/frozen_inference_graph.pb'

    with tf.io.gfile.GFile()(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
TypeError: __init__() missing 1 required positional argument: 'name'

**Comment by Asanka25** [comment]
First check your tensorflow version by running bellow code

import tensorflow as tf
print(tf.version)

If it's 2 or above then
pip install tensorflow==1.14.0 will run code successfully.

**Comment by AbhishekGoudaSH** [comment]
> First check your tensorflow version by running bellow code
> 
> import tensorflow as tf
> print(tf.version)
> 
> If it's 2 or above then
> pip install tensorflow==1.14.0 will run code successfully.

After installing tf1.14.0 I am getting another error for which i need to install tf1.20

**Comment by bigswede74** [comment]
I have downgraded my tensorflow-gpu==1.14.0 and I still get these error when running the object_detection scripts.

```
from object_detection.utils import label_map_util
ModuleNotFoundError: No module named object_detection
```

**Comment by kbaxx** [comment]
> I have downgraded my tensorflow-gpu==1.14.0 and I still get these error when running the object_detection scripts.
> 
> ```
> from object_detection.utils import label_map_util
> ModuleNotFoundError: No module named object_detection
> ```

If you are using tensorflow version < 2 you have to rewrite the utils imports to:
`from utils import label_map_util`

**Comment by bigswede74** [comment]
Once I added the PYTHONPATH environment variable to my system and added all the tensorflow repo local paths to the variable the code was able to see the references. Evidently Python will only look for script references using the PYTHONPATH env variable.

**Comment by jenniferchiang** [comment]
> Hi Guys,
> I think all object detection notebooks and models have not been verified with TF 2.0.
> For example, the session will be implicit in TF2.
> Would you please try tf.disable_v2_behavior() + import tensorflow.compat.v1 as tf?

Thanks a lot! It works!

**Comment by afvoskeuil** [comment]
Hii, Im having the same issue and nothing seems to work..
The error that I get is:

2020-01-20 02:45:45.916084: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-01-20 02:45:45.916282: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:/Users/frevo/PycharmProjects/CameraTracking/models/object_detection/object_detection_tutorial_CONVERTED.py", line 75, in <module>
    od_graph_def = tf.GraphDef()
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

This is my code:
`import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile

from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image

import cv2
cap = cv2.VideoCapture(1)

# This is needed since the notebook is stored in the object_detection folder.
sys.path.append("..")


# ## Object detection imports
# Here are the imports from the object detection module.

# In[3]:

from utils import label_map_util

from utils import visualization_utils as vis_util


# # Model preparation

# ## Variables
#
# Any model exported using the `export_inference_graph.py` tool can be loaded here simply by changing `PATH_TO_CKPT` to point to a new .pb file.
#
# By default we use an "SSD with Mobilenet" model here. See the [detection model zoo](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md) for a list of other models that can be run out-of-the-box with varying speeds and accuracies.

# In[4]:

# What model to download.
MODEL_NAME = 'ssd_mobilenet_v1_coco_11_06_2017'
MODEL_FILE = MODEL_NAME + '.tar.gz'
DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'

# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt')

NUM_CLASSES = 90


# ## Download Model

# In[5]:

opener = urllib.request.URLopener()
opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
tar_file = tarfile.open(MODEL_FILE)
for file in tar_file.getmembers():
  file_name = os.path.basename(file.name)
  if 'frozen_inference_graph.pb' in file_name:
    tar_file.extract(file, os.getcwd())


# ## Load a (frozen) Tensorflow model into memory.

# In[6]:

detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')


# ## Loading label map
# Label maps map indices to category names, so that when our convolution network predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility functions, but anything that returns a dictionary mapping integers to appropriate string labels would be fine

# In[7]:

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)


# ## Helper code

# In[8]:

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)


# # Detection

# In[9]:

# For the sake of simplicity we will use only 2 images:
# image1.jpg
# image2.jpg
# If you want to test the code with your images, just add path to the images to the TEST_IMAGE_PATHS.
PATH_TO_TEST_IMAGES_DIR = 'test_images'
TEST_IMAGE_PATHS = [ os.path.join(PATH_TO_TEST_IMAGES_DIR, 'dollar.jpg'.format(i)) for i in range(1, 3) ]

# Size, in inches, of the output images.
IMAGE_SIZE = (12, 8)


# In[10]:

with detection_graph.as_default():
  with tf.Session(graph=detection_graph) as sess:
    while True:
      ret, image_np = cap.read()
      # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
      image_np_expanded = np.expand_dims(image_np, axis=0)
      image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
      # Each box represents a part of the image where a particular object was detected.
      boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
      # Each score represent how level of confidence for each of the objects.
      # Score is shown on the result image, together with the class label.
      scores = detection_graph.get_tensor_by_name('detection_scores:0')
      classes = detection_graph.get_tensor_by_name('detection_classes:0')
      num_detections = detection_graph.get_tensor_by_name('num_detections:0')
      # Actual detection.
      (boxes, scores, classes, num_detections) = sess.run(
          [boxes, scores, classes, num_detections],
          feed_dict={image_tensor: image_np_expanded})
      # Visualization of the results of a detection.
      vis_util.visualize_boxes_and_labels_on_image_array(
          image_np,
          np.squeeze(boxes),
          np.squeeze(classes).astype(np.int32),
          np.squeeze(scores),
          category_index,
          use_normalized_coordinates=True,
          line_thickness=8)

      cv2.imshow('object detection', cv2.resize(image_np, (800,600)))
      if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
`

Can someone help me, Im struggling with this for almost 6 hours now :')

**Comment by ayushmankumar7** [comment]
The Colab Notebook is working fine. Is this issue supposed to be closed?

**Comment by AKIvan** [comment]
Any solutions except downgrade the versions on how to wrap this with the new one ?
"# ## Load a (frozen) Tensorflow model into memory." - version tf.2 ?

**Comment by ebron01** [comment]
updating this two lines:
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
with this solved the issue for me:
    od_graph_def = tf.compat.v1.GraphDef()
    with tf.io.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:

problem occurs from tf1 and v2 issues.

**Comment by Naeemmariam7** [comment]
> updating this two lines:
> od_graph_def = tf.GraphDef()
> with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
> with this solved the issue for me:
> od_graph_def = tf.compat.v1.GraphDef()
> with tf.io.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
> 
> problem occurs from tf1 and v2 issues.
> with these changes no need to downgrade the tf.

I tried this but now I get the error:

AttributeError: module 'tensorflow' has no attribute 'gfile'

**Comment by tanviagwl98** [comment]
> The Colab Notebook is working fine. Is this issue supposed to be closed?

How to upload upload files on google colab to test and train data?

**Comment by tanviagwl98** [comment]
> > od_graph_def = tf.compat.v1.GraphDef()
> > works for me, but...
> > tf.compat.v1.io.gfile.GFile() does not work!
> > gfile is moved to tf.io in tensorflow-2., but how to import this?
> 
> You just need tf.io.gfile.GFile()

If this is not working for me, can anybody help?

**Comment by redsigma** [comment]
After multiple tries. I got it working in this order:

0. Compile object_detection by running **pip3 install .** in models/research folder
1. Rename in/utils/label_map_util.py
from `object_detection.protos import string_int_label_map_pb2` to **from protos import string_int_label_map_pb2**
3. Rename  in /utils/label_map_util.py
`with tf.gfile.GFile(path, 'r') as fid:` to **with tf.io.gfile.GFile(path, 'r') as fid:**
4. Run jupyter notebook object_detection_tutorial.ipynb

Now inside jupyter:

1. Rename `%matplotlib inline` to **%matplotlib notebook** 
so it shows the image at the end. For me plt.show() didn't worked but this method worked
2. Rename 
`od_graph_def = tf.GraphDef()`
 `with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid: `
to
**od_graph_def = tf.compat.v1.GraphDef()**
 **with tf.io.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:**
3. Rename `tf.Session()` to **tf.compat.v1.Session()**
4. Rename any stuff that contains `tf.get_default_graph()` to **tf.compat.v1.get_default_graph()**
5. It should work now

Output of dpkg -l | grep rocm: 
ii  comgr - 1.6.0.121-rocm-rel-3.1-44-cbb02f9        
ii  hip-base - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d 
ii  hip-doc - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d       
ii  hip-hcc - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d      
ii  hip-samples - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d         
ii  hipblas - 0.20.0.307-rocm-rel-3.1-44-ff35c32      
ii  hipcub - 2.9.0.92-rocm-rel-3.1-44-40e1d66            
ii  hsa-ext-rocr-dev  - 1.1.30100.0-rocm-rel-3.1-44-ecafeba1            
ii  hsa-rocr-dev   -  1.1.30100.0-rocm-rel-3.1-44-ecafeba1      
ii  miopen-hip  - 2.2.1.7633-rocm-rel-3.1-44-9218683        
ii  miopengemm  - 1.1.6.647-rocm-rel-3.1-44-b51a125          
ii  rccl   -   2.10.0-254-g31648ec-rocm-rel-3.1-44             
ii  rocblas -   2.14.1.1861-rocm-rel-3.1-44-cc49425           
ii  rocfft  -  0.9.10.783-rocm-rel-3.1-44-b7f9ebe         
ii  rocm-clang-ocl  -  0.5.0.48-rocm-rel-3.1-44-fa039e7                
ii  rocm-cmake -  0.3.0.141-rocm-rel-3.1-44-1b9e698               
ii  rocm-debug-agent  -  1.0.0                                        
ii  rocm-dev  -  3.1.44                                     
ii  rocm-device-libs  - 1.0.0.563-rocm-rel-3.1-44-8f441a8  
ii  rocm-opencl  - 2.0.0-rocm-rel-3.1-44-8f28d95ad    
ii  rocm-opencl-dev - 2.0.0-rocm-rel-3.1-44-8f28d95ad  
ii  rocm-smi -  1.0.0-194-rocm-rel-3.1-44-g840011e    
ii  rocm-smi-lib64 - 2.3.0.3.rocm-rel-3.1-44-a246aac       
ii  rocm-utils - 3.1.44                                      
ii  rocminfo - 1.30100.0                                   
ii  rocprim - 2.9.0.952-rocm-rel-3.1-44-5fa0c79      
ii  rocrand - 2.10.0.657-rocm-rel-3.1-44-448c673
ii  rocsparse - 1.8.4.726-rocm-rel-3.1-44-eb854f0



Tested on docker image: rocm/tensorflow:latest which uses:
tensorboard          2.1.1          
tensorflow-estimator 2.1.0          
tensorflow-rocm      2.1.0 
protobuf             3.11.3       
Pillow               7.1.1          
pip                  20.0.2      
jupyter              1.0.0          
jupyter-client       6.1.0          
jupyter-console      6.1.0          
jupyter-core         4.6.3          
Keras-Applications   1.0.8          
Keras-Preprocessing  1.1.0  

Also my cpu doesn't have AVX support but has SSE 4.1 and SSE 4.2

**Comment by aniiketdongare07** [comment]
> Hi Guys,
> I think all object detection notebooks and models have not been verified with TF 2.0.
> For example, the session will be implicit in TF2.
> Would you please try tf.disable_v2_behavior() + import tensorflow.compat.v1 as tf?

I'm trying to understand what you've said here.
My error is the line

> output_graph_def = tf.GraphDef()

Will you explain me how and where  tf.disable_v2_behavior() + import tensorflow.compat.v1 as tf will work?

**Comment by saberkun** [comment]
import tensorflow.compat.v1 as tf for all symbols.

tf.compat.v1.disable_v2_behavior() calls inside __main__.
https://www.tensorflow.org/api_docs/python/tf/compat/v1/disable_v2_behavior

**Comment by aniiketdongare07** [comment]
@saberkun Thank you, works.

**Comment by abburimadhukar** [comment]
> > updating this two lines:
> > od_graph_def = tf.GraphDef()
> > with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
> > with this solved the issue for me:
> > od_graph_def = tf.compat.v1.GraphDef()
> > with tf.io.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
> > problem occurs from tf1 and v2 issues.
> > with these changes no need to downgrade the tf.
> 
> I tried this but now I get the error:
> 
> AttributeError: module 'tensorflow' has no attribute 'gfile'

i am gettingg same error what i have to do

**Comment by mehmood14** [comment]
> updating this two lines:
> od_graph_def = tf.GraphDef()
> with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
> with this solved the issue for me:
> od_graph_def = tf.compat.v1.GraphDef()
> with tf.io.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
> 
> problem occurs from tf1 and v2 issues.
> with these changes no need to downgrade the tf.

tried it but same issue

**Comment by ikaizenn** [comment]
Hey, can anyone tell the final solution for this ??

**Comment by shashwat1225** [comment]
> PATH_TO_FROZEN_GRAPH = 'D:/models/research/object_detection/' + MODEL_NAME + '/frozen_inference_graph.pb'
> with tf.io.gfile.GFile()(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
> TypeError: **init**() missing 1 required positional argument: 'name'
> 
> Edit: The Solution
> with tf.io.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:

Still getting this issue. Can someone please help out?

**Comment by goms12** [comment]
![Capture](https://user-images.githubusercontent.com/63918976/82696966-4ed59580-9c92-11ea-8103-4bd45281ae7a.PNG)
can anyone hel me please? :(
i can't uderstand this error

**Comment by mtreddy** [comment]
> After multiple tries. I got it working in this order:
> 
> 1. Compile object_detection by running `pip3 install .` in models/research folder
> 2. Rename in/utils/label_map_util.py
>    `from object_detection.protos import string_int_label_map_pb2` to **from protos import string_int_label_map_pb2**
> 3. Rename  in /utils/label_map_util.py
>    `with tf.gfile.GFile(path, 'r') as fid:` to **with tf.io.gfile.GFile(path, 'r') as fid:**
> 4. Run jupyter notebook object_detection_tutorial.ipynb
> 
> Now inside jupyter:
> 
> 1. Rename `%matplotlib inline` to **%matplotlib notebook**
>    so it shows the image at the end. For me plt.show() didn't worked but this method worked
> 2. Rename
>    `od_graph_def = tf.GraphDef()`
>    `with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid: `
>    to
>    **od_graph_def = tf.compat.v1.GraphDef()**
>    **with tf.io.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:**
> 3. Rename `tf.Session()` to **tf.compat.v1.Session()**
> 4. Rename any stuff that contains `tf.get_default_graph()` to **tf.compat.v1.get_default_graph()**
> 5. It should work now
> 6. If the image still doesn't show after the last step is over, run again the second step with matplotlib and then run again the last step and it should appear. Repeat this again if it still doesn't.
> 
> Tested on docker image: **rocm/tensorflow:latest** which uses:
> tensorboard 2.1.1
> tensorflow-estimator 2.1.0
> tensorflow-rocm 2.1.0
> protobuf 3.11.3
> Pillow 7.1.1
> pip 20.0.2
> jupyter 1.0.0
> jupyter-client 6.1.0
> jupyter-console 6.1.0
> jupyter-core 4.6.3
> Keras-Applications 1.0.8
> Keras-Preprocessing 1.1.0
> matplotlib 3.2.1
> kiwisolver 1.2.0
> numpy 1.18.2
> ...
> 
> Also my cpu **doesn't** have AVX support but has SSE 4.1 and SSE 4.2
> 
> Output of dpkg -l | grep rocm:
> ii comgr - 1.6.0.121-rocm-rel-3.1-44-cbb02f9
> ii hip-base - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hip-doc - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hip-hcc - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hip-samples - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hipblas - 0.20.0.307-rocm-rel-3.1-44-ff35c32
> ii hipcub - 2.9.0.92-rocm-rel-3.1-44-40e1d66
> ii hsa-ext-rocr-dev - 1.1.30100.0-rocm-rel-3.1-44-ecafeba1
> ii hsa-rocr-dev - 1.1.30100.0-rocm-rel-3.1-44-ecafeba1
> ii miopen-hip - 2.2.1.7633-rocm-rel-3.1-44-9218683
> ii miopengemm - 1.1.6.647-rocm-rel-3.1-44-b51a125
> ii rccl - 2.10.0-254-g31648ec-rocm-rel-3.1-44
> ii rocblas - 2.14.1.1861-rocm-rel-3.1-44-cc49425
> ii rocfft - 0.9.10.783-rocm-rel-3.1-44-b7f9ebe
> ii rocm-clang-ocl - 0.5.0.48-rocm-rel-3.1-44-fa039e7
> ii rocm-cmake - 0.3.0.141-rocm-rel-3.1-44-1b9e698
> ii rocm-debug-agent - 1.0.0
> ii rocm-dev - 3.1.44
> ii rocm-device-libs - 1.0.0.563-rocm-rel-3.1-44-8f441a8
> ii rocm-opencl - 2.0.0-rocm-rel-3.1-44-8f28d95ad
> ii rocm-opencl-dev - 2.0.0-rocm-rel-3.1-44-8f28d95ad
> ii rocm-smi - 1.0.0-194-rocm-rel-3.1-44-g840011e
> ii rocm-smi-lib64 - 2.3.0.3.rocm-rel-3.1-44-a246aac
> ii rocm-utils - 3.1.44
> ii rocminfo - 1.30100.0
> ii rocprim - 2.9.0.952-rocm-rel-3.1-44-5fa0c79
> ii rocrand - 2.10.0.657-rocm-rel-3.1-44-448c673
> ii rocsparse - 1.8.4.726-rocm-rel-3.1-44-eb854f0

Thanks this works.

**Comment by Murkor** [comment]
> After multiple tries. I got it working in this order:
> 
> 1. Compile object_detection by running `pip3 install .` in models/research folder
> 2. Rename in/utils/label_map_util.py
>    `from object_detection.protos import string_int_label_map_pb2` to **from protos import string_int_label_map_pb2**
> 3. Rename  in /utils/label_map_util.py
>    `with tf.gfile.GFile(path, 'r') as fid:` to **with tf.io.gfile.GFile(path, 'r') as fid:**
> 4. Run jupyter notebook object_detection_tutorial.ipynb
> 
> Now inside jupyter:
> 
> 1. Rename `%matplotlib inline` to **%matplotlib notebook**
>    so it shows the image at the end. For me plt.show() didn't worked but this method worked
> 2. Rename
>    `od_graph_def = tf.GraphDef()`
>    `with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid: `
>    to
>    **od_graph_def = tf.compat.v1.GraphDef()**
>    **with tf.io.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:**
> 3. Rename `tf.Session()` to **tf.compat.v1.Session()**
> 4. Rename any stuff that contains `tf.get_default_graph()` to **tf.compat.v1.get_default_graph()**
> 5. It should work now
> 6. If the image still doesn't show after the last step is over, run again the second step with matplotlib and then run again the last step and it should appear. Repeat this again if it still doesn't.
> 
> Tested on docker image: **rocm/tensorflow:latest** which uses:
> tensorboard 2.1.1
> tensorflow-estimator 2.1.0
> tensorflow-rocm 2.1.0
> protobuf 3.11.3
> Pillow 7.1.1
> pip 20.0.2
> jupyter 1.0.0
> jupyter-client 6.1.0
> jupyter-console 6.1.0
> jupyter-core 4.6.3
> Keras-Applications 1.0.8
> Keras-Preprocessing 1.1.0
> matplotlib 3.2.1
> kiwisolver 1.2.0
> numpy 1.18.2
> ...
> 
> Also my cpu **doesn't** have AVX support but has SSE 4.1 and SSE 4.2
> 
> Output of dpkg -l | grep rocm:
> ii comgr - 1.6.0.121-rocm-rel-3.1-44-cbb02f9
> ii hip-base - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hip-doc - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hip-hcc - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hip-samples - 3.1.20086.4516-rocm-rel-3.1-44-8ef00e2d
> ii hipblas - 0.20.0.307-rocm-rel-3.1-44-ff35c32
> ii hipcub - 2.9.0.92-rocm-rel-3.1-44-40e1d66
> ii hsa-ext-rocr-dev - 1.1.30100.0-rocm-rel-3.1-44-ecafeba1
> ii hsa-rocr-dev - 1.1.30100.0-rocm-rel-3.1-44-ecafeba1
> ii miopen-hip - 2.2.1.7633-rocm-rel-3.1-44-9218683
> ii miopengemm - 1.1.6.647-rocm-rel-3.1-44-b51a125
> ii rccl - 2.10.0-254-g31648ec-rocm-rel-3.1-44
> ii rocblas - 2.14.1.1861-rocm-rel-3.1-44-cc49425
> ii rocfft - 0.9.10.783-rocm-rel-3.1-44-b7f9ebe
> ii rocm-clang-ocl - 0.5.0.48-rocm-rel-3.1-44-fa039e7
> ii rocm-cmake - 0.3.0.141-rocm-rel-3.1-44-1b9e698
> ii rocm-debug-agent - 1.0.0
> ii rocm-dev - 3.1.44
> ii rocm-device-libs - 1.0.0.563-rocm-rel-3.1-44-8f441a8
> ii rocm-opencl - 2.0.0-rocm-rel-3.1-44-8f28d95ad
> ii rocm-opencl-dev - 2.0.0-rocm-rel-3.1-44-8f28d95ad
> ii rocm-smi - 1.0.0-194-rocm-rel-3.1-44-g840011e
> ii rocm-smi-lib64 - 2.3.0.3.rocm-rel-3.1-44-a246aac
> ii rocm-utils - 3.1.44
> ii rocminfo - 1.30100.0
> ii rocprim - 2.9.0.952-rocm-rel-3.1-44-5fa0c79
> ii rocrand - 2.10.0.657-rocm-rel-3.1-44-448c673
> ii rocsparse - 1.8.4.726-rocm-rel-3.1-44-eb854f0

that works properly, thank you

**Comment by Ravi-Nayak** [comment]
> First check your tensorflow version by running bellow code
> 
> import tensorflow as tf
> print(tf.version)
> 
> If it's 2 or above then
> pip install tensorflow==1.14.0 will run code successfully.

im still getting error after downgrading my tensorflow from 1.5 to 1.4
please can anyone say what is wrong with the code in 1.5 ?

**Comment by jitesh321** [comment]
i am using tesorflow=1.15 still i am getting error of graphdef() missing can someone help please

**Comment by perymerdeka** [comment]
I got the same error,

```python
 AttributeError: module 'tensorflow' has no attribute 'GraphDef'
```
where can import this module, I use the latest TensorFlow version?

**Comment by AditaSukmaW** [comment]
> Hii, Im having the same issue and nothing seems to work..
> The error that I get is:
> 
> 2020-01-20 02:45:45.916084: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
> 2020-01-20 02:45:45.916282: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> Traceback (most recent call last):
> File "C:/Users/frevo/PycharmProjects/CameraTracking/models/object_detection/object_detection_tutorial_CONVERTED.py", line 75, in
> od_graph_def = tf.GraphDef()
> AttributeError: module 'tensorflow' has no attribute 'GraphDef'
> 
> This is my code:
> 
> `import numpy as np`
> 
> ```
> import os
> import six.moves.urllib as urllib
> import sys
> import tarfile
> import tensorflow as tf
> import zipfile
> 
> 
> from collections import defaultdict
> from io import StringIO
> from matplotlib import pyplot as plt
> from PIL import Image
> 
> import cv2
> cap = cv2.VideoCapture(1)
> 
> # This is needed since the notebook is stored in the object_detection folder.
> sys.path.append("..")
> 
> 
> # ## Object detection imports
> # Here are the imports from the object detection module.
> 
> # In[3]:
> 
> from utils import label_map_util
> 
> from utils import visualization_utils as vis_util
> 
> 
> # # Model preparation
> 
> # ## Variables
> #
> # Any model exported using the `export_inference_graph.py` tool can be loaded here simply by changing `PATH_TO_CKPT` to point to a new .pb file.
> #
> # By default we use an "SSD with Mobilenet" model here. See the [detection model zoo](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md) for a list of other models that can be run out-of-the-box with varying speeds and accuracies.
> 
> # In[4]:
> 
> # What model to download.
> MODEL_NAME = 'ssd_mobilenet_v1_coco_11_06_2017'
> MODEL_FILE = MODEL_NAME + '.tar.gz'
> DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'
> 
> # Path to frozen detection graph. This is the actual model that is used for the object detection.
> PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'
> 
> # List of the strings that is used to add correct label for each box.
> PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt')
> 
> NUM_CLASSES = 90
> 
> 
> # ## Download Model
> 
> # In[5]:
> 
> opener = urllib.request.URLopener()
> opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
> tar_file = tarfile.open(MODEL_FILE)
> for file in tar_file.getmembers():
>   file_name = os.path.basename(file.name)
>   if 'frozen_inference_graph.pb' in file_name:
>     tar_file.extract(file, os.getcwd())
> 
> 
> # ## Load a (frozen) Tensorflow model into memory.
> 
> # In[6]:
> 
> detection_graph = tf.Graph()
> with detection_graph.as_default():
>   od_graph_def = tf.GraphDef()
>   with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
>     serialized_graph = fid.read()
>     od_graph_def.ParseFromString(serialized_graph)
>     tf.import_graph_def(od_graph_def, name='')
> 
> 
> # ## Loading label map
> # Label maps map indices to category names, so that when our convolution network predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility functions, but anything that returns a dictionary mapping integers to appropriate string labels would be fine
> 
> # In[7]:
> 
> label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
> categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
> category_index = label_map_util.create_category_index(categories)
> 
> 
> # ## Helper code
> 
> # In[8]:
> 
> def load_image_into_numpy_array(image):
>   (im_width, im_height) = image.size
>   return np.array(image.getdata()).reshape(
>       (im_height, im_width, 3)).astype(np.uint8)
> 
> 
> # # Detection
> 
> # In[9]:
> 
> # For the sake of simplicity we will use only 2 images:
> # image1.jpg
> # image2.jpg
> # If you want to test the code with your images, just add path to the images to the TEST_IMAGE_PATHS.
> PATH_TO_TEST_IMAGES_DIR = 'test_images'
> TEST_IMAGE_PATHS = [ os.path.join(PATH_TO_TEST_IMAGES_DIR, 'dollar.jpg'.format(i)) for i in range(1, 3) ]
> 
> # Size, in inches, of the output images.
> IMAGE_SIZE = (12, 8)
> 
> 
> # In[10]:
> 
> with detection_graph.as_default():
>   with tf.Session(graph=detection_graph) as sess:
>     while True:
>       ret, image_np = cap.read()
>       # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
>       image_np_expanded = np.expand_dims(image_np, axis=0)
>       image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
>       # Each box represents a part of the image where a particular object was detected.
>       boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
>       # Each score represent how level of confidence for each of the objects.
>       # Score is shown on the result image, together with the class label.
>       scores = detection_graph.get_tensor_by_name('detection_scores:0')
>       classes = detection_graph.get_tensor_by_name('detection_classes:0')
>       num_detections = detection_graph.get_tensor_by_name('num_detections:0')
>       # Actual detection.
>       (boxes, scores, classes, num_detections) = sess.run(
>           [boxes, scores, classes, num_detections],
>           feed_dict={image_tensor: image_np_expanded})
>       # Visualization of the results of a detection.
>       vis_util.visualize_boxes_and_labels_on_image_array(
>           image_np,
>           np.squeeze(boxes),
>           np.squeeze(classes).astype(np.int32),
>           np.squeeze(scores),
>           category_index,
>           use_normalized_coordinates=True,
>           line_thickness=8)
> 
>       cv2.imshow('object detection', cv2.resize(image_np, (800,600)))
>       if cv2.waitKey(25) & 0xFF == ord('q'):
>         cv2.destroyAllWindows()
>         break
> ```
> 
> Can someone help me, Im struggling with this for almost 6 hours now :')

Hi your fault and mine are the same, how do you solve it?

**Comment by aniiketdongare07** [comment]
import tensorflow.compat.v1 as tf for all symbols.

tf.compat.v1.disable_v2_behavior() calls inside main.


Try this?
Aniket Dongare
