### ISSUE TITLE
TypeError: x and y must have the same dtype, got tf.float32 != tf.float64

### ISSUE THREAD

**Issue by RohanWong** [tensorflow/models#7719]
I got the error when running the code of https://github.com/tensorflow/models/tree/master/research/efficient-hrl 
on ubuntu 18.04 python 3.6 tensorflow 1.15 and other requirements at latest version.

When running
`python scripts/local_train.py test1 hiro_orig ant_maze base_uvf suite`

I got the following errors:

```
Traceback (most recent call last):
  File "./run_train.py", line 49, in <module>
    tf.app.run()
    …
  File "/root/anaconda3/envs/hrl/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 997, in _truediv_python3
    (x_dtype, y_dtype))
TypeError: x and y must have the same dtype, got tf.float32 != tf.float64
  In call to configurable 'train_uvf' (<function train_uvf at 0x7f0b2e5ef320>)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by RohanWong** [comment]
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

directory of the model i used is models-mater/research/efficient-hrl
no custom code
ubuntu 18.04
tensorflow 1.15.0rc0 installed from pip
no Bazel no CUDA/cuDNN no GPU model
the exact command to reproduce is 
`python scripts/local_train.py test1 hiro_orig ant_maze base_uvf suite`

**Comment by ian-cannon** [comment]
Seeing the same thing

What is the top-level directory of the model you are using: models/research/efficient-hrl
Have I written custom code: No
OS Platform and Distribution: Ubuntu 18.04
TensorFlow installed from: pip 
TensorFlow version: 1.15.0
Bazel version: none
CUDA/cuDNN version: none
GPU model and memory
Exact command to reproduce `python scripts/local_train.py test1 hiro_orig ant_maze base_uvf suite`

**Comment by ian-cannon** [comment]
This was solved by changing like 152 of agent.py to `    normalized_error = tf.cast(error, tf.float64) / tf.constant(spec_range) ** 2`

credit to this post: https://stackoverflow.com/questions/56544619/how-to-fix-typeerror-x-and-y-must-have-the-same-dtype-got-tf-uint8-tf-floa

**Comment by ofirnachum** [comment]
Thanks for surfacing this. Would you like to make a pull request to fix this?

**Comment by ian-cannon** [comment]
Sure, I can do that
