### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Jeryhardianto** [tensorflow/models#7748]
how to solve this problem ??
I need :
- tensorflow 2.0.0
- pip 19.3.1
- Python 3.7.4 

c:\deteksi\models\research>python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 29, in <module>
    from object_detection.builders import model_builder
  File "C:\deteksi\models\research\object_detection\builders\model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "C:\deteksi\models\research\object_detection\builders\box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "C:\deteksi\models\research\object_detection\predictors\convolutional_box_predictor.py", line 23, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by saberkun** [comment]
contrib is not inside TF 2.0.
object_detection should use TF 1.15 for now

**Comment by blackCmd** [comment]
@saberkun 
Thanks X )
You saved my time !

**Comment by mirecta** [comment]
So when can i use object detection with tensorflow 2 ?

**Comment by ouening** [comment]
same question as @mirecta

**Comment by nicolascarratala** [comment]
same question as @mirecta
