### ISSUE TITLE
AssertionError: Some objects had attributes which were not restored:

### ISSUE THREAD

**Issue by DavidInWuhanChina** [tensorflow/models#7749]
D:\Anaconda\python.exe D:/Pythonwork/models-master/official/nlp/bert/run_classifier.py
2019-11-03 15:29:57.578584: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
D:\Anaconda\lib\site-packages\absl\flags\_validators.py:359: UserWarning: Flag --bert_config_file has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
D:\Anaconda\lib\site-packages\absl\flags\_validators.py:359: UserWarning: Flag --input_meta_data_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
D:\Anaconda\lib\site-packages\absl\flags\_validators.py:359: UserWarning: Flag --model_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
2019-11-03 15:29:59.334610: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-11-03 15:29:59.357601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:2d:00.0
2019-11-03 15:29:59.357728: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-03 15:29:59.358145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-03 15:29:59.358432: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-03 15:29:59.359831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:2d:00.0
2019-11-03 15:29:59.359949: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-03 15:29:59.360331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-03 15:29:59.859426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-03 15:29:59.859514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-11-03 15:29:59.859633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-11-03 15:29:59.860272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6283 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5)
2019-11-03 15:29:59.862266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:2d:00.0
2019-11-03 15:29:59.862364: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-03 15:29:59.862741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-03 15:29:59.862832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-03 15:29:59.862921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-11-03 15:29:59.862977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-11-03 15:29:59.863331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 6283 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5)
I1103 15:29:59.864534  2336 run_classifier.py:175] Training using customized training loop TF 2.0 with distrubuted strategy.
I1103 15:30:04.896698  2336 model_training_utils.py:208] Checkpoint file D:\Pythonwork\models-master\official/nlp/bert/bert_model.ckpt.index found and restoring from initial checkpoint for core model.
WARNING:tensorflow:From D:\Anaconda\lib\site-packages\tensorflow_core\python\training\tracking\util.py:1249: NameBasedSaverStatus.__init__ (from tensorflow.python.training.tracking.util) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
W1103 15:30:05.129548  2336 deprecation.py:323] From D:\Anaconda\lib\site-packages\tensorflow_core\python\training\tracking\util.py:1249: NameBasedSaverStatus.__init__ (from tensorflow.python.training.tracking.util) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Traceback (most recent call last):
  File "D:/Pythonwork/models-master/official/nlp/bert/run_classifier.py", line 354, in <module>
    app.run(main)
  File "D:\Anaconda\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Anaconda\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "D:/Pythonwork/models-master/official/nlp/bert/run_classifier.py", line 347, in main
    run_bert(strategy, input_meta_data)
  File "D:/Pythonwork/models-master/official/nlp/bert/run_classifier.py", line 315, in run_bert
    use_keras_compile_fit=FLAGS.use_keras_compile_fit)
  File "D:/Pythonwork/models-master/official/nlp/bert/run_classifier.py", line 191, in run_bert_classifier
    run_eagerly=run_eagerly)
  File "D:\Pythonwork\models-master\official\modeling\model_training_utils.py", line 210, in run_customized_training_loop
    checkpoint.restore(init_checkpoint).assert_existing_objects_matched()
  File "D:\Anaconda\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 958, in assert_existing_objects_matched
    return self.assert_consumed()
  File "D:\Anaconda\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 943, in assert_consumed
    "".join(unused_attribute_strings)))
AssertionError: Some objects had attributes which were not restored:
    MirroredVariable:{
  0 /job:localhost/replica:0/task:0/device:GPU:0: <tf.Variable 'bert_model/word_embeddings/embeddings:0' shape=(30522, 768) dtype=float32, numpy=
array([[-0.00827931,  0.01431082, -0.00777864, ...,  0.01801899,
        -0.0157681 ,  0.01644019],
       [ 0.00402739,  0.01077779, -0.03267807, ..., -0.00955056,
        -0.02823814, -0.00086142],
       [-0.00451602,  0.01798712,  0.00225978, ..., -0.01169181,
        -0.00619626,  0.00308232],
       ...,
       [ 0.02792709, -0.01492976,  0.00823874, ...,  0.01966464,
         0.00073174,  0.0058544 ],
       [ 0.02030507,  0.00855687, -0.01362395, ..., -0.01978453,
        -0.01236773,  0.00698793],
       [ 0.00139731, -0.00094716,  0.03630266, ..., -0.00655695,
        -0.0305069 , -0.01894755]], dtype=float32)>
}: ['bert_model/word_embeddings/embeddings']
    MirroredVariable:{
  0 /job:localhost/replica:0/task:0/device:GPU:0: <tf.Variable 'bert_model/embedding_postprocessor/type_embeddings:0' shape=(2, 768) dtype=float32, numpy=
array([[ 0.00656738,  0.00148078, -0.00961577, ..., -0.01950487,
        -0.01032996,  0.02670303],
       [-0.00623129,  0.00780312,  0.01977771, ...,  0.03336583,
         0.01022719, -0.00561789]], dtype=float32)>
}: ['bert_model/embedding_postprocessor/type_embeddings']

**Comment by saberkun** [comment]
Do you use bert_base config.json?
12 layer and hidden_size 768?

**Comment by DavidInWuhanChina** [comment]
def define_common_bert_flags():
  """Define the flags related to TPU's."""
  flags.DEFINE_string('bert_config_file', 'D:\Pythonwork\models-master\official/nlp/bert/bert_config.json',
                      'Bert configuration file to define core bert layers.')

{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

**Comment by DavidInWuhanChina** [comment]
> Do you use bert_base config.json?
> 12 layer and hidden_size 768?

in common_flags.py :
def define_common_bert_flags():
  """Define the flags related to TPU's."""
  flags.DEFINE_string('bert_config_file', 'D:\Pythonwork\models-master\official/nlp/bert/bert_config.json',
                      'Bert configuration file to define core bert layers.')

and the bert_config.json is
{
"attention_probs_dropout_prob": 0.1,
"hidden_act": "gelu",
"hidden_dropout_prob": 0.1,
"hidden_size": 768,
"initializer_range": 0.02,
"intermediate_size": 3072,
"max_position_embeddings": 512,
"num_attention_heads": 12,
"num_hidden_layers": 12,
"type_vocab_size": 2,
"vocab_size": 30522
}

**Comment by saberkun** [comment]
Which one do you have issue with?
BERT-Large, Uncased (Whole Word Masking): 24-layer, 1024-hidden, 16-heads, 340M parameters
BERT-Large, Cased (Whole Word Masking): 24-layer, 1024-hidden, 16-heads, 340M parameters
BERT-Base, Uncased: 12-layer, 768-hidden, 12-heads, 110M parameters
BERT-Large, Uncased: 24-layer, 1024-hidden, 16-heads, 340M parameters
BERT-Base, Cased: 12-layer, 768-hidden, 12-heads , 110M parameters
BERT-Large, Cased: 24-layer, 1024-hidden, 16-heads, 340M parameters

I tested "BERT-Base, Uncased". There is no problem. Please provide more information.

**Comment by DavidInWuhanChina** [comment]
> Which one do you have issue with?
> BERT-Large, Uncased (Whole Word Masking): 24-layer, 1024-hidden, 16-heads, 340M parameters
> BERT-Large, Cased (Whole Word Masking): 24-layer, 1024-hidden, 16-heads, 340M parameters
> BERT-Base, Uncased: 12-layer, 768-hidden, 12-heads, 110M parameters
> BERT-Large, Uncased: 24-layer, 1024-hidden, 16-heads, 340M parameters
> BERT-Base, Cased: 12-layer, 768-hidden, 12-heads , 110M parameters
> BERT-Large, Cased: 24-layer, 1024-hidden, 16-heads, 340M parameters
> 
> I tested "BERT-Base, Uncased". There is no problem. Please provide more information.

I use tf 2.0 not tf-nightly?
Does it matter?

**Comment by saberkun** [comment]
Hmmm, I don't think it matters. We have nightly regression test with TF2.0 branch using "BERT-Large, Uncased". Does "BERT-Large, Uncased" work for you? It is a bit weird.

**Comment by ibmxiang** [comment]
how to solve  this problem？，I use  tf2.3

**Comment by saberkun** [comment]
If you download the current checkpoints from the current links we provide and use the master or TF 2.3 release code, you should not see this issue. If you see this issue, the checkpoint + config + python code does not match.
