### ISSUE TITLE
[deeplab] The eval.py and vis.py not working 

### ISSUE THREAD

**Issue by gachiemchiep** [tensorflow/models#7769]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: : Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: : binary
- **TensorFlow version (use command below)**: : 1.15.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: : 10.0 / 7.6.4
- **GPU model and memory**:  V100, 32GB
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I use script in research/deeplab to train deeplab for my own dataset. 
My image has size as 1920x1080.

I use the following command to train. it worked smoothly

```bash
python deeplab/train.py \
    --logtostderr \
    --train_split="trainval" \
    --model_variant="mobilenet_v2" \
    --train_crop_size="769,769" \
    --train_batch_size=16 \
    --fine_tune_batch_norm=false \
    --tf_initial_checkpoint='/home/user/workspace/2019_ICT/deeplab_model_zoo/deeplabv3_mnv2_pascal_train_aug/model.ckpt-30000' \
    --initialize_last_layer=False \
    --last_layers_contain_logits_only=True \
    --train_logdir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_log' \
    --dataset_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/tfrecord/' \
    --dataset="icboard_seg" \
    --training_number_of_steps=1000 \
    --base_learning_rate=0.0001 
```

The training log: [train.log](https://github.com/tensorflow/models/files/3818482/train.log) . There aren't any error messages.

But when I try the eval.py, the mIoU is not output in the console. There isn't any error message in the log, so I guess there are some options that I have to turn on.

The eval log : [eval.log](https://github.com/tensorflow/models/files/3818485/eval.log). There isn't any error message too.

```bash
python deeplab/eval.py \
  --logtostderr \
  --eval_split="val" \
  --model_variant="mobilenet_v2" \
  --eval_crop_size="513,513" \
  --min_resize_value=288 \
  --max_resize_value=512 \
  --checkpoint_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_log' \
  --eval_logdir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_eval' \
  --dataset_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/tfrecord/' \
  --max_number_of_evaluations=1 \
  --eval_interval_secs=0 \
  --dataset="icboard_seg" 
```

I used the following command to run vis.py.

```bash
python deeplab/eval.py \
  --logtostderr \
  --eval_split="val" \
  --model_variant="mobilenet_v2" \
  --eval_crop_size="513,513" \
  --min_resize_value=288 \
  --max_resize_value=512 \
  --checkpoint_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_log' \
  --eval_logdir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_eval' \
  --dataset_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/tfrecord/' \
  --max_number_of_evaluations=1 \
  --eval_interval_secs=0 \
  --dataset="icboard_seg" 
```

The vis log : [vis.log](https://github.com/tensorflow/models/files/3818490/vis.log). As you can see the error is as follow.

```bash
tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

Traceback (most recent call last):
  File "deeplab/vis.py", line 320, in <module>
    tf.app.run()
  File "/home/user/opt/miniconda2/envs/py2.7/lib/python2.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/user/opt/miniconda2/envs/py2.7/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/user/opt/miniconda2/envs/py2.7/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "deeplab/vis.py", line 267, in main
    align_corners=True), 3)
  File "/home/user/opt/miniconda2/envs/py2.7/lib/python2.7/site-packages/tensorflow_core/python/ops/image_ops_impl.py", line 1187, in resize_images
    skip_resize_if_same=True)
  File "/home/user/opt/miniconda2/envs/py2.7/lib/python2.7/site-packages/tensorflow_core/python/ops/image_ops_impl.py", line 1053, in _resize_images_common
    new_height_const = size_const_as_shape.dims[0].value
TypeError: 'NoneType' object has no attribute '__getitem__'

```

Is there anybody who know why this happened and how can I overcome this?

**Comment by aquariusjay** [comment]
Hi gachiemchiep,

Please refer to Q8 in [FAQ](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/faq.md).
In your case, please set eval_crop_size="1921,1089"

Cheers,

**Comment by gachiemchiep** [comment]
Hello @aquariusjay 
I tried your suggestion but still the same: 

```bash
python deeplab/eval.py \
  --logtostderr \
  --eval_split="val" \
  --model_variant="mobilenet_v2" \
  --eval_crop_size="1921,1089" \
  --min_resize_value=288 \
  --max_resize_value=512 \
  --checkpoint_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_log' \
  --eval_logdir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_eval' \
  --dataset_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/tfrecord/' \
  --max_number_of_evaluations=1 \
  --eval_interval_secs=0 \
  --dataset="icboard_seg" 
```
[eval.log](https://github.com/tensorflow/models/files/3822531/eval.log)

```bash
python deeplab/vis.py \
    --logtostderr \
    --vis_split="val" \
    --dataset="icboard_seg" \
    --vis_crop_size="1921,1089" \
    --min_resize_value=288 \
    --max_resize_value=512 \
    --model_variant="mobilenet_v2" \
    --also_save_raw_predictions=True \
    --checkpoint_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_log' \
    --vis_logdir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/train_vis' \
    --dataset_dir='/home/user/workspace/2019_ICT/icboard_dataset/segmentation/part1/tfrecord/'
```

[vis.log](https://github.com/tensorflow/models/files/3822532/vis.log)

By the way, I set those parameters, so I think the image and mask should be resized from 1920x1080 into 512x288. As a result,   --eval_crop_size="513,513"  should be correct be in my case.


```bash
    --min_resize_value=288 \
    --max_resize_value=512 \
```
