### ISSUE TITLE
Can't use .pb extension Tensorflow Faster R-CNN when changing stride configuration

### ISSUE THREAD

**Issue by ankyaditya** [tensorflow/models#7795]
### System information
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): I installed tensorflow using pip install tensorflow-gpu
- TensorFlow version (use command below): 1.14.0
- CUDA/cuDNN version: CUDA 10/ CuDNN 7.6.4
- GPU model and memory: Nvidia GeForce GTX 1080 16GB

### Problem
I can't use converted model (.pb) when the configuration of faster R-CNN is using first_stage_features_stride: 8. it just work fin for first_stage_features_stride: 16. Can anybody help what to do next? I try to retrain my model with stride 8 but it just same as before, always get that error. I change the stride in file faster_rcnn_resnet101_coco.config.
![error2](https://user-images.githubusercontent.com/51365534/68685269-725dac00-059c-11ea-9008-99e67defb926.JPG)

### Source code / logs
Traceback (most recent call last):
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [38432] vs. [110592]
         [[{{node Decode/mul_3}}]]
         [[BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/unstack/_171]]
  (1) Invalid argument: Incompatible shapes: [38432] vs. [110592]
         [[{{node Decode/mul_3}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\IMV Laboratory\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\IMV Laboratory\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\IMV Laboratory\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\Anaconda\envs\taasu\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda\envs\taasu\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda\envs\taasu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\TAARS\models_anq\models-master\research\object_detection\Coor_Gen.py", line 118, in <module>
    feed_dict={image_tensor: frame_expanded})
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [38432] vs. [110592]
         [[node Decode/mul_3 (defined at d:\TAARS\models_anq\models-master\research\object_detection\Coor_Gen.py:73) ]]
         [[BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/unstack/_171]]
  (1) Invalid argument: Incompatible shapes: [38432] vs. [110592]
         [[node Decode/mul_3 (defined at d:\TAARS\models_anq\models-master\research\object_detection\Coor_Gen.py:73) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'Decode/mul_3':
  File "c:\Users\IMV Laboratory\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\IMV Laboratory\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\IMV Laboratory\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\Anaconda\envs\taasu\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda\envs\taasu\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda\envs\taasu\lib\runpy.py", line 85, in _run_code
  File "d:\TAARS\models_anq\models-master\research\object_detection\Coor_Gen.py", line 73, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\framework\importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\framework\importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\framework\ops.py", line 3751, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\framework\ops.py", line 3751, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\framework\ops.py", line 3641, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "D:\Anaconda\envs\taasu\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
![error](https://user-images.githubusercontent.com/51365534/68685106-2b6fb680-059c-11ea-8a39-725444690a01.JPG)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
Bazel version
Exact command to reproduce

**Comment by Vinmel24** [comment]
I have a similar problem.

i have "frozen_inference_graph.pb" file as my trained file. i want to test it;  my tensorflow 1.14 but im getting this erros:

ERROR:

InvalidArgumentError                      Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1355     try:
-> 1356       return fn(*args)
   1357     except errors.OpError as e:

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1340       return self._call_tf_sessionrun(
-> 1341           options, feed_dict, fetch_list, target_list, run_metadata)
   1342 

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1428         self._session, options, feed_dict, fetch_list, target_list,
-> 1429         run_metadata)
   1430 

InvalidArgumentError: Incompatible shapes: [38432] vs. [110592]
	 [[{{node Decode/mul_2}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-20-b19082c2666b> in <module>
      7   image_np_expanded = np.expand_dims(image_np, axis=0)
      8   # Actual detection.
----> 9   output_dict = run_inference_for_single_image(image_np, detection_graph)
     10   # Visualization of the results of a detection.
     11   vis_util.visualize_boxes_and_labels_on_image_array(

<ipython-input-19-f22e65a052c1> in run_inference_for_single_image(image, graph)
     33       # Run inference
     34       output_dict = sess.run(tensor_dict,
---> 35                              feed_dict={image_tensor: np.expand_dims(image, 0)})
     36 
     37       # all outputs are float32 numpy arrays, so convert types as appropriate

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1171     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1172       results = self._do_run(handle, final_targets, final_fetches,
-> 1173                              feed_dict_tensor, options, run_metadata)
   1174     else:
   1175       results = []

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1348     if handle is None:
   1349       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1350                            run_metadata)
   1351     else:
   1352       return self._do_call(_prun_fn, handle, feeds, fetches)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

InvalidArgumentError: Incompatible shapes: [38432] vs. [110592]
	 [[node Decode/mul_2 (defined at <ipython-input-15-d55b98fd5a78>:7) ]]

Original stack trace for 'Decode/mul_2':
  File "/home/melvin/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/melvin/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 563, in start
    self.io_loop.start()
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/melvin/anaconda3/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/home/melvin/anaconda3/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle._run()
  File "/home/melvin/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 378, in dispatch_queue
    yield self.process_one()
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 225, in wrapper
    runner = Runner(result, future, yielded)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 714, in __init__
    self.run()
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-d55b98fd5a78>", line 7, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3751, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3751, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3641, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/melvin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by rajatk11** [comment]
Has anyone managed to solve this yet? Or any other alternative for a pre-trained Faster RCNN where it could be trained with a shorter stride? 
Thanks!

**Comment by ankyaditya** [comment]
In my case, that error appear because I'm using first_stage_features_stride: 8 but my height and width stride in first_stage_anchor_generator using 16 instead of 8. So if you want using first_stage_features_stride: X, you should change the height and width stride in first_stage_anchor_generator to X too.

**Comment by rajatk11** [comment]
Oh yes, now I see it. Thanks a lot!

**Comment by Mantis4849** [comment]
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "D:\Anaconda\envs\tf\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda\envs\tf\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "D:\Anaconda\envs\tf\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "D:\Anaconda\envs\tf\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\trainer.py", line 211, in train
    detection_model = create_model_fn()
  File "D:\Anaconda\envs\tf\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 93, in build
    add_summaries)
  File "D:\Anaconda\envs\tf\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 249, in _build_faster_rcnn_model
    frcnn_config.feature_extractor, is_training)
  File "D:\Anaconda\envs\tf\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 224, in _build_faster_rcnn_feature_extractor
    batch_norm_trainable, reuse_weights)
  File "D:\Anaconda\envs\tf\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\models\faster_rcnn_inception_v2_feature_extractor.py", line 80, in __init__
    raise ValueError('`first_stage_features_stride` must be 8 or 16.')
ValueError: `first_stage_features_stride` must be 8 or 16.








    feature_extractor {
      type: 'faster_rcnn_inception_v2'
      first_stage_features_stride: 16
    }
    first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [0.25, 0.5, 1.0, 2.0]
        aspect_ratios: [0.5, 1.0, 2.0]
        height_stride: 16
        width_stride: 16
      }
    }
somebody help!!!
