### ISSUE TITLE
ImportError: cannot import name 'input_reader_pb2' in Google Colab

### ISSUE THREAD

**Issue by ac-ac1** [tensorflow/models#7860]
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **TensorFlow installed from (source or binary)**: However installed in Colab
- **TensorFlow version (use command below)**: 1.15
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**:Colab GPU
- **Exact command to reproduce**: !python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

### Describe the problem
When I run this script on my local machine, I get this error and I am able to fix it with a protobuff compilation and PYTHONPATH export. When I get this exact same error in Colab, the same thing does not fix it. I want to use Colab for the free GPUs.

### Source code / logs
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "/usr/local/lib/python3.6/dist-packages/object_detection/data_decoders/tf_example_decoder.py", line 24, in <module>
    from object_detection.protos import input_reader_pb2
ImportError: cannot import name 'input_reader_pb2'

**Comment by TheCaffeineDev** [comment]
Hi, @ac-ac1 you need to do this .Go to the research folder in colab after cloning the model. Like this

_%cd models/research_

!protoc object_detection/protos/*.proto --python_out=.

_import os
os.environ['PYTHONPATH'] += ':/content/models/research/:/content/models/research/slim/'_

Then it should work.

**Comment by NourhanM** [comment]
> Hi, @ac-ac1 you need to do this .Go to the research folder in colab after cloning the model. Like this
> 
> _%cd models/research_
> 
> !protoc object_detection/protos/*.proto --python_out=.
> 
> _import os os.environ['PYTHONPATH'] += ':/content/models/research/:/content/models/research/slim/'_
> 
> Then it should work.

I have the same issue, it didn't work for me
