### ISSUE TITLE
MobilenetEdgeTPU runs fail on Pixel 4 Edge TPU

### ISSUE THREAD

**Issue by ghostsun89** [tensorflow/models#7887]
I have tried to run the mobilenetv3 edgetpu version on Pixel 4's edgetpu using the NNAPI, but I failed.
The error log as follows

```
2019-11-30 16:53:37.181 12909-13045/com.huawei.hurricane E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.huawei.hurricane, PID: 12909
    java.lang.IllegalArgumentException: DataType error: DataType 9 is not recognized in Java (version 2.0.0)
        at org.tensorflow.lite.DataType.fromC(DataType.java:75)
        at org.tensorflow.lite.Tensor.<init>(Tensor.java:363)
        at org.tensorflow.lite.Tensor.fromIndex(Tensor.java:43)
        at org.tensorflow.lite.NativeInterpreterWrapper.getInputTensor(NativeInterpreterWrapper.java:291)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:134)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:259)
        at com.huawei.hurricane.nn.fragment.NNClassificationFragment.startTest(NNClassificationFragment.java:323)
        at com.huawei.hurricane.nn.fragment.NNClassificationFragment$4.run(NNClassificationFragment.java:196)
        at java.lang.Thread.run(Thread.java:919)
2019-11-30 16:53:37.222 12909-13045/com.huawei.hurricane I/Process: Sending signal. PID: 12909 SIG: 9
```
I am sure Pixel 4 is supported the EdgeTPU using the NNAPI.  The information is as follow.
```
2019-11-30 16:53:36.431 12909-13045/com.huawei.hurricane I/tflite: Initialized TensorFlow Lite runtime.
2019-11-30 16:53:36.432 12909-13045/com.huawei.hurricane I/tflite: Created TensorFlow Lite delegate for NNAPI.
2019-11-30 16:53:36.434 12909-13045/com.huawei.hurricane I/Manager: DeviceManager::DeviceManager
2019-11-30 16:53:36.434 12909-13045/com.huawei.hurricane I/Manager: findAvailableDevices
2019-11-30 16:53:36.435 12909-13045/com.huawei.hurricane I/Manager: Found interface google-edgetpu
2019-11-30 16:53:36.438 12909-13045/com.huawei.hurricane I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 10.000000, .powerUsage = 10.000000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 10.000000, .powerUsage = 10.000000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = INT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = UINT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_INT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 0.100000, .powerUsage = 0.100000}}, {.type = BOOL, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 10.000000, .powerUsage = 10.0
2019-11-30 16:53:36.438 12909-13045/com.huawei.hurricane I/Manager: Found interface qti-default
2019-11-30 16:53:36.439 12909-13045/com.huawei.hurricane I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 0.600000, .powerUsage = 0.800000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 0.600000, .powerUsage = 0.800000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = INT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = UINT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_INT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 0.700000, .powerUsage = 0.700000}}, {.type = BOOL, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 0.700000, .powerUsage = 0.700000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = FLOA
2019-11-30 16:53:36.439 12909-13045/com.huawei.hurricane I/Manager: Found interface qti-dsp
2019-11-30 16:53:36.440 12909-13045/com.huawei.hurricane I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 2.000000, .powerUsage = 2.000000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 2.000000, .powerUsage = 2.000000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = UINT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = BOOL, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = FLOA
2019-11-30 16:53:36.440 12909-13045/com.huawei.hurricane I/Manager: Found interface qti-gpu
2019-11-30 16:53:36.443 12909-13045/com.huawei.hurricane I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 1.100000, .powerUsage = 1.100000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 1.100000, .powerUsage = 1.100000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = INT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = UINT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_INT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = BOOL, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = FLOA
2019-11-30 16:53:36.443 12909-13045/com.huawei.hurricane I/Manager: Found interface qti-hta
2019-11-30 16:53:36.443 12909-13045/com.huawei.hurricane I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 2.000000, .powerUsage = 2.000000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 2.000000, .powerUsage = 2.000000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = UINT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = BOOL, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = FLOA
2019-11-30 16:53:36.443 12909-13045/com.huawei.hurricane I/TypeManager: Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.
```
The MobilenetV3 model is downloaded using the url: https://storage.cloud.google.com/mobilenet_edgetpu/checkpoints/mobilenet_edgetpu_224_1.0.tgz

I guess the model datatype maybe wrong while frozen the model, but I don't how to fix it.
Does anyone know how to fix the problem?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ghostsun89** [comment]
@tensorflowbutler Thanks for your reminder.

**System information**
- **What is the top-level directory of the model you are using**:
 I used the **mobilenet_edgetpu_224_1.0_int8.tflite** model downloading from the url: https://storage.cloud.google.com/mobilenet_edgetpu/checkpoints/mobilenet_edgetpu_224_1.0.tgz
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Android Q
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 
use the **TFLite API: Interpreter.run(Object input, Object, output)** to run the mobilenet_edgetpu_224_1.0_int8.tflite model

**Comment by nutsiepully** [comment]
Hi,

From a cursory look at the error message, it seems like this is a permissions issue.

If this is a third party app, it's likely the NNAPI HAL isn't allowing access to the device. If this is a device you control, you'll likely have to adjust permissions to allow edgetpu access to the app.

`2019-11-30 16:53:36.443 12909-13045/com.huawei.hurricane I/TypeManager: Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.`

**Comment by ghostsun89** [comment]
@nutsiepully Thanks for your reply. I thought so at the beginning, but when I switched to use the mobilenetv1_quant.tflite model it worked. The info was also appeared. The detail as follows:
```
2019-12-02 14:00:37.712 9436-9476/? I/tflite: Initialized TensorFlow Lite runtime.
2019-12-02 14:00:37.712 9436-9476/? I/tflite: Created TensorFlow Lite delegate for NNAPI.
2019-12-02 14:00:37.714 9436-9476/? I/Manager: DeviceManager::DeviceManager
2019-12-02 14:00:37.714 9436-9476/? I/Manager: findAvailableDevices
2019-12-02 14:00:37.715 9436-9476/? I/Manager: Found interface google-edgetpu
2019-12-02 14:00:37.717 9436-9476/? I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 10.000000, .powerUsage = 10.000000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 10.000000, .powerUsage = 10.000000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = INT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = UINT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_INT32, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 0.100000, .powerUsage = 0.100000}}, {.type = BOOL, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 10.000000, .powerUsage = 10.000000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 10.000000, .powerUsage = 10.0
2019-12-02 14:00:37.717 9436-9476/? I/Manager: Found interface qti-default
2019-12-02 14:00:37.718 9436-9476/? I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 0.600000, .powerUsage = 0.800000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 0.600000, .powerUsage = 0.800000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = INT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = UINT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_INT32, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 0.700000, .powerUsage = 0.700000}}, {.type = BOOL, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 0.700000, .powerUsage = 0.700000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 0.600000, .powerUsage = 0.800000}}, {.type = FLOA
2019-12-02 14:00:37.718 9436-9476/? I/Manager: Found interface qti-dsp
2019-12-02 14:00:37.720 9436-9476/? I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 2.000000, .powerUsage = 2.000000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 2.000000, .powerUsage = 2.000000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = UINT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = BOOL, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = FLOA
2019-12-02 14:00:37.720 9436-9476/? I/Manager: Found interface qti-gpu
2019-12-02 14:00:37.720 9436-9476/? I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 1.100000, .powerUsage = 1.100000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 1.100000, .powerUsage = 1.100000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = INT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = UINT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_INT32, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = BOOL, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = FLOA
2019-12-02 14:00:37.721 9436-9476/? I/Manager: Found interface qti-hta
2019-12-02 14:00:37.721 9436-9476/? I/Manager: Capab {.relaxedFloat32toFloat16PerformanceScalar = {.execTime = 2.000000, .powerUsage = 2.000000}, .relaxedFloat32toFloat16PerformanceTensor = {.execTime = 2.000000, .powerUsage = 2.000000}, .operandPerformance = [16]{{.type = FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = UINT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_FLOAT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_INT32, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT8_ASYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = BOOL, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_QUANT16_SYMM, .info = {.execTime = 1.100000, .powerUsage = 1.100000}}, {.type = TENSOR_FLOAT16, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = TENSOR_BOOL8, .info = {.execTime = 2.000000, .powerUsage = 2.000000}}, {.type = FLOA
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: setOperandValue for operand 1 size 864
2019-12-02 14:00:37.722 9436-9476/? I/TypeManager: TypeManager::TypeManager
2019-12-02 14:00:37.722 9436-9476/? I/TypeManager: Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.
2019-12-02 14:00:37.722 9436-9476/? I/TypeManager: NNAPI Vendor extensions enabled: 0
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: Saving large value
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: setOperandValue for operand 2 size 128
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: Copied small value to offset 0
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: setOperandValue for operand 3 size 4
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: Copied small value to offset 128
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: setOperandValue for operand 4 size 4
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: Copied small value to offset 132
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: setOperandValue for operand 5 size 4
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: Copied small value to offset 136
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: setOperandValue for operand 6 size 4
2019-12-02 14:00:37.722 9436-9476/? I/ModelBuilder: Copied small value to offset 140
2019-12-02 14:00:37.723 9436-9476/? I/ModelBuilder: setOperandValue for operand 8 size 288
...
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(DEPTHWISE_CONV_2D) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-gpu can't do operation CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-hta can't do operation CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(CONV_2D) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-gpu can't do operation DEPTHWISE_CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-hta can't do operation DEPTHWISE_CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(DEPTHWISE_CONV_2D) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-gpu can't do operation CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-hta can't do operation CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(CONV_2D) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-gpu can't do operation AVERAGE_POOL_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-hta can't do operation AVERAGE_POOL_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(AVERAGE_POOL_2D) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-gpu can't do operation CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-hta can't do operation CONV_2D
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(CONV_2D) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-gpu can't do operation RESHAPE
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-hta can't do operation RESHAPE
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(RESHAPE) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-gpu can't do operation SOFTMAX
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: Device qti-hta can't do operation SOFTMAX
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::findBestDeviceForEachOperation(SOFTMAX) = 0 (google-edgetpu)
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ModelBuilder::partitionTheWork: only one best device: 0 = google-edgetpu
2019-12-02 14:00:37.759 9436-9476/? I/ExecutionPlan: ExecutionPlan::SimpleBody::finish, compilation
```
**From the log, you can see the mobilenetv1_quant model choose the google-edpetpu for its best device.** So I thought the problem maybe in the model, but I don't known how to fix it.

**Comment by sunzhe09** [comment]
I met the same problem on qti 730G mobile devices

**Comment by freedomtan** [comment]
my patch (https://github.com/tensorflow/tensorflow/pull/36397) should resolve this problem.

**Comment by sunzhe09** [comment]
@freedomtan how can I  test this case,should I have to update my tensorfow to 2,1?

**Comment by freedomtan** [comment]
@sunzhe09 The patch is for TensorFlow master branch. Either try the TFLite nightly AAR or build your own AAR from the master branch. If you don't know how to do it, check the [TFLite Android quickstart guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/android.md)

**Comment by ghostsun89** [comment]
@freedomtan It works. Thanks a lot.

**Comment by ravikyram** [comment]
@ghostsun89 

Please close this thread if your issue was resolved. Thanks!
