### ISSUE TITLE
ImportError: cannot import name 'anchor_generator_pb2'. Protobuf doesn't work here.

### ISSUE THREAD

**Issue by aracnema** [tensorflow/models#7890]
when I run this on google colab
!python object_detection/builders/model_builder_test.py

I get: 
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/anchor_generator_builder.py", line 22, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2'

when I enter 
protoc object_detection/protos/*.proto --python_out=.
no error occures.
What should I do?

**Comment by TheCaffeineDev** [comment]
Can you please share your notebook link?

**Comment by jarvis-owl** [comment]
are there any *.py files in models/research/object_detection/protos/ ?
protoc is quiet calm there.
[This](https://gilberttanner.com/blog/installing-the-tensorflow-object-detection-api) seemed to have a similar issue and wrote a python script for converting *.protos to *.py.

**Comment by udithhaputhanthri** [comment]
Here https://github.com/tensorflow/models/tree/master/research/object_detection/protos there is no file called anchor_generator_pb2.py ???

**Comment by tmbenhura** [comment]
You need to generate the *.py files from the protobufs **BEFORE** you install the object detection package. If you already installed it, just re-run the installation command.
