### ISSUE TITLE
ImportError: cannot import name 'preprocessor_pb2'

### ISSUE THREAD

**Issue by thanhtran1** [tensorflow/models#7896]
CUDA:9
cuDNN:7
tensorflow-gpu:1.9
GPU: NVIDIA 940 
I run :python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection import trainer
  File "C:\tensorflow1\models\research\object_detection\trainer.py", line 27, in <module>
    from object_detection.builders import preprocessor_builder
  File "C:\tensorflow1\models\research\object_detection\builders\preprocessor_builder.py", line 21, in <module>
    from object_detection.protos import preprocessor_pb2
ImportError: cannot import name 'preprocessor_pb2'
Help me!!

**Comment by thanhtran1** [comment]
🔢

**Comment by TheCaffeineDev** [comment]
Maybe you forgot to do this?
_protoc object_detection/protos/*.proto --python_out=._ 

inside the research folder. It's recommended to use _model_main.py_ to train. 

follow this link-
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#protobuf-compilation
