### ISSUE TITLE
RuntimeError when trying to use the functional API.

### ISSUE THREAD

**Issue by christk1** [tensorflow/models#7917]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.0.0
- **Exact command to reproduce**:

### Describe the problem
I implemented transformer xl using tf.keras.layers with the subclassing api and it works. I also checked the trainable variables and their names are the same as in original implementation. If i want to use my model with the Functional api, i get a RuntimeError. 

### Source code / logs
My code for the Functional api follows the same structure as the code in bert [here](https://github.com/tensorflow/models/blob/master/official/nlp/modeling/networks/transformer_encoder.py). In my transformer xl code i have custom layers and a final big keras layer which connects all the other layers in the call function.

My code for the functional api is shown below:
```
class TransformerXLModel(network.Network):
    def __init__(self, n_token, init_method, init_std, init_range, n_layer, d_model, n_head, d_head, d_inner,
                 ff_activation, untie_r, dropout, dropout_att, mem_len, reuse_len, bi_data, clamp_len,
                 same_length, tf_float, residual, **kwargs):
        initializer = _get_initializer(init_method, init_std, init_range)
        attn_type = 'bi'
        self._self_setattr_tracking = False
        self._config_dict = {
            'n_token': n_token,
            'init_method': init_method,
            'init_std': init_std,
            'init_range': init_range,
            'n_layer': n_layer,
            'd_model': d_model,
            'n_head': n_head,
            'd_head': d_head,
            'd_inner': d_inner,
            'ff_activation': ff_activation,
            'untie_r': untie_r,
            'dropout': dropout,
            'dropout_att': dropout_att,
            'mem_len': mem_len,
            'reuse_len': reuse_len,
            'bi_data': bi_data,
            'clamp_len': clamp_len,
            'same_length': same_length,
            'tf_float': tf_float,
            'residual': residual
        }

        input_word_ids = tf.keras.layers.Input(
            shape=(FLAGS.seq_length,), dtype=tf.int32, name='input_ids')
        segment_ids = tf.keras.layers.Input(
            shape=(FLAGS.seq_length,), dtype=tf.int32, name='segment_ids')
        input_mask = tf.keras.layers.Input(
            shape=(FLAGS.seq_length,), dtype=tf.float32, name='input_mask')
        mems = None
        perm_mask = None
        inps = pack_inputs([input_word_ids, segment_ids, input_mask, mems, perm_mask])

        self.transformerxl_model = TransformerXlLayer(n_layer, d_model, n_head, d_head, d_inner, ff_activation, untie_r,
                                                      n_token, dropout, dropout_att, attn_type, mem_len, reuse_len,
                                                      bi_data, clamp_len, same_length, initializer, tf_float,
                                                      residual, name='transformer')
        output, new_mems, lookup_table = self.transformerxl_model(inps)

        super(TransformerXLModel, self).__init__(
            inputs=[input_word_ids, segment_ids, input_mask, mems, perm_mask],
            outputs=[output],
            **kwargs)

    def get_config(self):
        return self._config_dict

    @classmethod
    def from_config(cls, config, custom_objects=None):
        return cls(**config)
```

```
Traceback (most recent call last):
  File "checkpoint_converter/checkpoint_conv_tool.py", line 179, in <module>
    app.run(main=main)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "checkpoint_converter/checkpoint_conv_tool.py", line 173, in main
    FLAGS.target_checkpoint,
  File "checkpoint_converter/checkpoint_conv_tool.py", line 159, in convert_checkpoint
    model = get_XLnet()
  File "checkpoint_converter/checkpoint_conv_tool.py", line 146, in get_XLnet
    FLAGS.same_length, tf_float, FLAGS.residual)
  File "checkpoint_converter/checkpoint_conv_tool.py", line 90, in __init__
    output, new_mems, lookup_table = self.transformerxl_model(inps)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/chris/PycharmProjects/My_xlnet/modeling.py", line 664, in call
    non_tgt_mask = -tf.eye(qlen, dtype=self.tf_float)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/ops/linalg_ops.py", line 169, in eye
    name=name)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/ops/linalg_ops_impl.py", line 65, in eye
    diag_shape = array_ops.concat((batch_shape, [diag_size]), axis=0)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 1431, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1257, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 471, in _apply_op_helper
    as_ref=input_arg.is_ref)
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1365, in internal_convert_n_to_tensor
    ctx=ctx))
  File "/home/chris/miniconda3/envs/tensorflow_cpu/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1264, in internal_convert_to_tensor
    raise RuntimeError("Attempting to capture an EagerTensor without "
RuntimeError: Attempting to capture an EagerTensor without building a function.
```
Please help!!! i cant find a solution. It seems that functional api requires graph and not eager tensors. I used the @tf.function decorator without success. I also tried using functional api with the tf.keras.model.Model and the result is exactly the same.

**EDIT**
By watching a tensor when executing both functional and subclassing api i found that the names differ.
Subclassing API: Tensor("model/transformer/Cast:0", shape=(1, 128, 1, 1), dtype=float32)
Functional API: Tensor("Cast:0", shape=(1, 128, 1, 1), dtype=float32)

**Comment by saberkun** [comment]
Hi, we also failed to use functional api. That's why we stick to sub-class API.

**Comment by shidaide2019** [comment]
Excuse me, I wonder whether you have solved the problem you've mentioned above because i just find  i have the same problem with you, could you provide your solution for the question if you figure it out?

**Comment by christk1** [comment]
@shidaide2019 hi, I couldn't solve it but I moved to a more robust method for my problem which worked.

**Comment by shidaide2019** [comment]
@christk1 Thanks for your reply, I'll try a sub-class modeling method

**Comment by saberkun** [comment]
Closing.  The name difference is expected. We cannot rely on tensor names.
