### ISSUE TITLE
Does not supported to TF 2!

### ISSUE THREAD

**Issue by tensor2flow** [tensorflow/models#7979]
(tf) F:\Git\tensorflow_models\research>python object_detection/builders/model_builder_test.py
2019-12-23 13:15:50.353549: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_102.dll
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "F:\Git\tensorflow_models\research\object_detection\builders\model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "F:\Git\tensorflow_models\research\object_detection\builders\box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "F:\Git\tensorflow_models\research\object_detection\predictors\convolutional_box_predictor.py", line 23, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by jarvis-owl** [comment]
same issue as: [#7920](https://github.com/tensorflow/models/issues/7920)
