### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by samareshyadav55** [tensorflow/models#7985]
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    from object_detection.builders import dataset_builder
  File "C:\Users\samaresh yadav\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\Users\samaresh yadav\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\data_decoders\tf_example_decoder.py", line 29, in <module>
    from object_detection.protos import input_reader_pb2
ImportError: cannot import name 'input_reader_pb2'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
