### ISSUE TITLE
Evaluation couldn't completed after first epoch 

### ISSUE THREAD

**Issue by pushti-123** [tensorflow/models#7996]
Architecture : faster_rcnn_resnet101_coco_2018_01_28
Training Anotated data : 1.3 lakh
Testing anotated data : 40,000
Batch size : 1
num_example : 8000

After the first epoch, Evaluation takes too much time and then an error is :

Traceback (most recent call last):
  File "/home/dev1/anaconda3/envs/pushti/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/dev1/anaconda3/envs/pushti/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dev1/anaconda3/envs/pushti/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
  (1) Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[BatchMultiClassNonMaxSuppression/map/TensorArray_11/_3571]]
0 successful operations.
0 derived errors ignored.

How can I fix this bug?
Thank you.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pushti-123** [comment]
Top-level Directory is Tensorflow\models-1.12.0\research\object_detection.
No, I haven't written a custom code.
TensorFlow-gpu(1.14.0) installed from pip 19.3.1.
cuDNN version : 7.5
Exact command to reproduce : python model_main.py --logtostderr --model_dir=/models-1.12.0/research/object_detection/training/ --pipeline_config_path=/models-1.12.0/research/object_detection/training/faster_rcnn_resnet101_coco_2018_01_28.config

**Comment by wsqshiqing** [comment]
Guys, I meet this problem again, Had someone solve it ?
