### ISSUE TITLE
Run local_test.sh failed for deeplab

### ISSUE THREAD

**Issue by hzy5000** [tensorflow/models#7999]
I cloned and run commands according to the Installation guide.
After I run command "sh local_test.sh". It failed and shown the following errors.
---------------------------------------------------------------------------------------
(Python3GPU) hzy@ubun:~/OpenCode/models/research/deeplab$ sh local_test.sh
WARNING: Logging before flag parsing goes to stderr.
W1231 15:53:43.112672 140406109452096 deprecation_wrapper.py:119] From /mnt/sdb1/home/hzy/OpenCode/models/research/deeplab/core/conv2d_ws.py:40: The name tf.layers.Layer is deprecated. Please use tf.compat.v1.layers.Layer instead.

W1231 15:53:43.115272 140406109452096 deprecation_wrapper.py:119] From /home/hzy/OpenCode/models/research/slim/nets/mobilenet/mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

Traceback (most recent call last):
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 696, in get_value
    return next(args) if value is None else value
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hzy/OpenCode/models/research/deeplab/model_test.py", line 148, in <module>
    tf.test.main()
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/tensorflow/python/platform/test.py", line 64, in main
    return _googletest.main(argv)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/tensorflow/python/platform/googletest.py", line 65, in main
    benchmark.benchmarks_main(true_main=main_wrapper)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/tensorflow/python/platform/benchmark.py", line 407, in benchmarks_main
    true_main()
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/tensorflow/python/platform/googletest.py", line 64, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/absl/app.py", line 294, in run
    flags_parser,
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/absl/app.py", line 351, in _run_init
    flags_parser=flags_parser,
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/absl/app.py", line 213, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 31, in _parse_flags_tolerate_undef
    return flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 626, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 744, in _parse_args
    value = get_value()
  File "/mnt/sdb1/home/hzy/Python3GPU/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 698, in get_value
    raise _exceptions.Error('Missing value for flag ' + arg)  # pylint: disable=undefined-loop-variable
absl.flags._exceptions.Error: Missing value for flag -v
------------------------

### System information
- **What is the top-level directory of the model you are using**: 
deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
form the binary
- **TensorFlow version (use command below)**:
tensorflow-gpu 1.14.0
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
CUDA 10.0/cuDNN 7.5
- **GPU model and memory**:
4 GTX 1080Ti with 11GB memory
- **Exact command to reproduce**:
sh local_test.sh

**Comment by brahste** [comment]
I am getting the exact same error.

### System information

**top-level directory of model:**
.../deeplab
**OS Platform and Distribution:**
Linux Mint 18.3 (Ubuntu 16.04)
**TensorFlow installed from (source or binary):**
form the binary
**TensorFlow version (use command below):**
tensorflow-gpu 1.15
**CUDA/cuDNN version:**
CUDA 10.2/cuDNN 7.5
**GPU model and memory:**
GeForce MX150 (built into laptop)
**Exact command to reproduce:**
sh local_test.sh


**Error statement:**     
Traceback (most recent call last):
    File "/home/brahste/miniconda3/envs/tf1-15/lib/python3.7/site-packages/absl/flags/_flagvalues.py", line 696, in get_value
    return next(args) if value is None else value
StopIteration

During handling of the above exception, another exception occurred:

**Comment by grbagwe** [comment]
Has anyone solved this ?
