### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

### ISSUE THREAD

**Issue by shenglih** [tensorflow/models#8002]
System information
- What is the top-level directory of the model you are using**:models/research/object_detection/legacy
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- OS Platform and Distribution:Linux Ubuntu 16.04
- CUDA/cuDNN version**: 10.1
- GPU model and memory**: Tesla v100, 64G
- TensorFlow version
v1.15.0-rc3-22-g590d6ee 1.15.0

### Describe the problem
python ./legacy/train.py --logtostderr --pipeline_congif_path=./ssd_inception_v2.config --train_dir=./Logo/training

I am sure the above paths are correct 

### Source code / logs

Traceback (most recent call last):
  File "/home/shu/models/research/object_detection/legacy/train.py", line 186, in <module>
    tf.app.run()
  File "/home/shu/.local/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/shu/.local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/shu/.local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/shu/models/research/object_detection/legacy/train.py", line 110, in main
    overwrite=True)
  File "/home/shu/.local/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 469, in copy
    copy_v2(oldpath, newpath, overwrite)
  File "/home/shu/.local/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 486, in copy_v2
    compat.as_bytes(src), compat.as_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow installed from
Bazel version
Exact command to reproduce
