### ISSUE TITLE
google.protobuf.text_format.ParseError: 189:1

### ISSUE THREAD

**Issue by Abdulsemedsomi** [tensorflow/models#8048]
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Program Files\Python36\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Program Files\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 94, in main
    FLAGS.pipeline_config_path)
  File "C:\Program Files\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\config_util.py", line 104, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 702, in Merge
    allow_unknown_field=allow_unknown_field)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 770, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 795, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 817, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Program Files\Python36\lib\site-packages\google\protobuf\text_format.py", line 909, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 189:1 : Message type "object_detection.protos.TrainEvalPipelineConfig" has no field named "Inside".

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
