### ISSUE TITLE
Object Detection: TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by dumaaan** [tensorflow/models#8050]
### System information
- **What is the top-level directory of the model you are using**: Object detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.6
- **Bazel version (if compiling from source)**: Not applicable
- **CUDA/cuDNN version**: 7.4.x
- **GPU model and memory**: NVIDIA V100 32GB 
- **Exact command to reproduce**: python eval.py --pipeline_config_path='configs/rbox_cnn_resnet101.config' --checkpoint_dir='.ipynb_checkpoints/' --eval_dir='eval/' --run_mode='all'

### Describe the problem
I was using the Object Detection model to train on my own dataset. I was able to train the model, but when running eval.py file, I was getting a TypeError as described in the title. My labelmap is a .JSON file containing info on satellite images used in my dataset, looking like this:

`{
   "features":[
      {
         "geometry":{
            "coordinates":[
               [
                  [
                     x,
                     y,
                     z
                  ],
                  etc.
            ],
            "type":"Polygon"
         }   `

I saw a somewhat similar issue that was closed, but the issue was solved because the author found a typo in their [dataset.](https://github.com/tensorflow/models/issues/3624) At the moment, I am not sure of the exact reason for the problem, and I am actively troubleshooting the issue.

### Source code / logs
`/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/work/SIA_code/simplified_rbox_cnn/utils/cintersection_rbox.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "/home/work/SIA_code/simplified_rbox_cnn/utils/label_map_util.py", line 120, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 702, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 770, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 795, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 817, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 885, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1353, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
': Expected identifier or number, got {.1:1 : '{`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "eval.py", line 188, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "eval.py", line 177, in main
    label_map = label_map_util.load_labelmap(input_config.label_map_path)
  File "/home/work/SIA_code/simplified_rbox_cnn/utils/label_map_util.py", line 122, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'`

**Comment by dumaaan** [comment]
Solved - the pbtxt labelmap was simply missing.
