### ISSUE TITLE
How can I eval my dataset in deeplab V3+

### ISSUE THREAD

**Issue by bobmukza** [tensorflow/models#8064]
Linux Ubuntu 16.04)
TensorFlow version 1.15.0
CUDA 10.0 cuDNN 7
4 Titan xp / 12G
----------------------------------------------------------------------------------
My data set is ADE20K(150 class) but I'm using (0~4 class).
So I changed it to fit my data(annotation)

In conclusion, It is same the ade20k dataset!! but class number is different.

and I sucess training in this code

_2HAE_INFORMATION = DatasetDescriptor(
    splits_to_sizes={
        'train': 20210,  # num of samples in images/training
        'val': 2000,  # num of samples in images/validation
    },
    num_classes=5,
    ignore_label=0,
)

_DATASETS_INFORMATION = {
    'cityscapes': _CITYSCAPES_INFORMATION,
    'pascal_voc_seg': _PASCAL_VOC_SEG_INFORMATION,
    'ade20k': _ADE20K_INFORMATION,
    '2hae' : _2HAE_INFORMATION,
}

  exclude_list = ['global_step','logits']
  if not initialize_last_layer:
    exclude_list.extend(last_layers)

and my train code is

# Train 10 iterations.
NUM_ITERATIONS=100
python "${WORK_DIR}"/train.py \
  --logtostderr \
  --train_split="train" \
  --model_variant="xception_65" \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --decoder_output_stride=4 \
  --train_crop_size="513,513" \
  --min_resize_value=513 \
  --max_resize_value=513 \
  --resize_factor=16 \
  --train_batch_size=4 \
  --training_number_of_steps="${NUM_ITERATIONS}" \
  --fine_tune_batch_norm=True \
  --initialize_last_layer=False \
  --last_layers_contain_logits_only=True \
  --dataset="2hae" \
  --tf_initial_checkpoint="${INIT_FOLDER}/deeplabv3_xception_ade20k_train/model.ckpt" \
  --train_logdir="${TRAIN_LOGDIR}" \
  --dataset_dir="${ADE20K_DATASET}"
---------------------------------------------------------------
train is Success!!!

and my eval code is

python "${WORK_DIR}"/eval.py \
  --logtostderr \
  --eval_split="val" \
  --model_variant="xception_65" \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --decoder_output_stride=4 \
  --eval_crop_size="513,513" \
  --min_resize_value=513 \
  --max_resize_value=513 \
  --resize_factor=16 \
  --dataset="2hae" \
  --checkpoint_dir="${TRAIN_LOGDIR}" \
  --eval_logdir="${EVAL_LOGDIR}" \
  --dataset_dir="${DATASET}" \
  --max_number_of_evaluations=1

------------------------------------------------------------------------------------------------------------
I0120 01:41:34.026803 140433443366656 monitored_session.py:240] Graph was finalized.
2020-01-20 01:41:34.027186: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-01-20 01:41:34.033912: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2398850000 Hz
2020-01-20 01:41:34.034922: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56013f65c450 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-20 01:41:34.034949: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-20 01:41:34.451939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:05:00.0
2020-01-20 01:41:34.453821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:06:00.0
2020-01-20 01:41:34.455533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:09:00.0
2020-01-20 01:41:34.457131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
2020-01-20 01:41:34.457211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-20 01:41:34.457254: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-20 01:41:34.457293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-01-20 01:41:34.457336: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-01-20 01:41:34.457392: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-01-20 01:41:34.457441: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-01-20 01:41:34.457496: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-20 01:41:34.470353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3
2020-01-20 01:41:34.470437: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-20 01:41:34.478076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-20 01:41:34.478110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 2 3
2020-01-20 01:41:34.478132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y Y Y
2020-01-20 01:41:34.478150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N Y Y
2020-01-20 01:41:34.478168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   Y Y N Y
2020-01-20 01:41:34.478185: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3:   Y Y Y N
2020-01-20 01:41:34.487349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11435 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0, compute capability: 6.1)
2020-01-20 01:41:34.490617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11438 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:06:00.0, compute capability: 6.1)
2020-01-20 01:41:34.493754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 11438 MB memory) -> physical GPU (device: 2, name: TITAN Xp, pci bus id: 0000:09:00.0, compute capability: 6.1)
2020-01-20 01:41:34.496842: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 11438 MB memory) -> physical GPU (device: 3, name: TITAN Xp, pci bus id: 0000:0a:00.0, compute capability: 6.1)
2020-01-20 01:41:34.500099: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5601418a4390 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-01-20 01:41:34.500129: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2020-01-20 01:41:34.500145: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): TITAN Xp, Compute Capability 6.1
2020-01-20 01:41:34.500159: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): TITAN Xp, Compute Capability 6.1
2020-01-20 01:41:34.500174: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): TITAN Xp, Compute Capability 6.1
INFO:tensorflow:Restoring parameters from /home/test/models/research/deeplab/datasets/ADE20K/exp/train_on_train_set/train/model.ckpt-100
I0120 01:41:34.504012 140433443366656 saver.py:1284] Restoring parameters from /home/test/models/research/deeplab/datasets/ADE20K/exp/train_on_train_set/train/model.ckpt-100
INFO:tensorflow:Running local_init_op.
I0120 01:41:37.734876 140433443366656 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0120 01:41:37.879452 140433443366656 session_manager.py:502] Done running local_init_op.
INFO:tensorflow:Starting evaluation at 2020-01-20-01:41:39
I0120 01:41:39.764425 140433443366656 evaluation.py:450] Starting evaluation at 2020-01-20-01:41:39
2020-01-20 01:41:41.277770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-20 01:41:42.039554: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-01-20 01:41:42.062408: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/root/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: assertion failed: [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (mean_iou/confusion_matrix/control_dependency:0) = ] [0 0 0...] [y (mean_iou/Cast_1:0) = ] [5]
         [[{{node mean_iou/confusion_matrix/assert_less/Assert/AssertGuard/Assert}}]]
         [[mean_iou/AssignAdd/_4521]]
  (1) Invalid argument: assertion failed: [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (mean_iou/confusion_matrix/control_dependency:0) = ] [0 0 0...] [y (mean_iou/Cast_1:0) = ] [5]
         [[{{node mean_iou/confusion_matrix/assert_less/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
