### ISSUE TITLE
quantization aware training of a transferred model from ResNet50

### ISSUE THREAD

**Issue by rose-jinyang** [tensorflow/models#8065]
Hello,
While I'm working on transfer learning of ResNet50 model, I'm going to do quantization aware training of the final model.
I have a run-time issue in tf.contrib.quantize.create_training_graph method when I do quantization aware training of Resnet50.
Traceback (most recent call last):
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1741, in
main()
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1735, in main
globals = debugger.run(setup['file'], None, None, is_module)
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1135, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "D:/Jin/Internet_Task/Jobs/2019/2019.11.20-fr_fl_rasppi-sridhar/work/fr_jin/fr_jin/test_quant_aware_training.py", line 42, in
tf.contrib.quantize.create_training_graph(sess.graph)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\quantize_graph.py", line 122, in create_training_graph
freeze_bn_delay=freeze_bn_delay)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\quantize_graph.py", line 73, in _create_graph
is_training=is_training)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 53, in FoldBatchNorms
graph, is_training, freeze_batch_norm_delay=freeze_batch_norm_delay)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 98, in _FoldFusedBatchNorms
freeze_batch_norm_delay=freeze_batch_norm_delay))
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 384, in _ComputeBatchNormCorrections
match.moving_variance_tensor + match.batch_epsilon)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

I think that the problem is the batch normalization of ResNet.
I'm using Python 3.7 and tensorflow 1.14/1.15.
Could anybody help me for this issue?
Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by saberkun** [comment]
Assign to @alanchiao for the most recent quantization aware training library + TF2 + keras

**Comment by alanchiao** [comment]
@rose-jinyang 

As Hongkun suggested, have you seen the most recent Quantization Aware Training launch for Keras? The documentation starts at https://www.tensorflow.org/model_optimization/guide/quantization/training and we've trained Resnet with it. 

See the details there on what versions of TF / etc it is compatible with. Right now, you have to use tf-nightly to export to TFLite, though TF 2.2 would work for just training. Are you able to use TF2 instead?

tf.contrib.quantize is deprecated and we're not actively supporting it anymore.

**Comment by rose-jinyang** [comment]
Thanks for your reply

**Comment by alanchiao** [comment]
Should we close this issue or do you have followup questions on applying contrib.quantize to Resnet?

**Comment by rose-jinyang** [comment]
Please close.
Thanks
