### ISSUE TITLE
model_main.py contains tf.contrib

### ISSUE THREAD

**Issue by herruli** [tensorflow/models#8084]
Hi all,

I am trying out the model_main.py in object detection. When I try with the script. It shows 

Traceback (most recent call last):
  File "model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/home/herru/anaconda3/lib/python3.7/site-packages/object_detection-0.1-py3.7.egg/object_detection/model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "/home/herru/anaconda3/lib/python3.7/site-packages/object_detection-0.1-py3.7.egg/object_detection/eval_util.py", line 40, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

It seems like tensorflow 2.1 has removed contrib. yet in eval_util line 40 and 327 still contains contrib. I suspect it might be a bug? Thanks

**Comment by saberkun** [comment]
Hi, 

Sorry, object detection API does not migrate to TF 2 yet. Please use TF 1.15.

**Comment by maxpaynestory** [comment]
Why TF 1.15?
Can we use TF 1.9.0 which is also less than TF 2.

**Comment by saberkun** [comment]
1.9 should work but the head code always using latest TF. For OD libraries, they should match latest TF 1.x release which is TF 1.15. For more details, please reach out to the code owners. 
https://github.com/tensorflow/models/blob/master/CODEOWNERS
