### ISSUE TITLE
Error while installing object detection API: ImportError: cannot import name 'Cycler'

### ISSUE THREAD

**Issue by jm-mirza** [tensorflow/models#8098]
Okay so this has been making me crazy, I am trying to set up the tensorflow object detection api, I have followed all the steps mentioned on the github page. However, on the last step when we need to check the installation by running:

python object_detection/builders/model_builder_test.py

This error shows up:

ImportError: cannot import name 'Cycler'

`Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/mnt/data2/TensorFlow/models/research/object_detection/builders/model_builder.py", line 34, in <module>
    from object_detection.meta_architectures import ssd_meta_arch
  File "/mnt/data2/TensorFlow/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 34, in <module>
    from object_detection.utils import visualization_utils
  File "/mnt/data2/TensorFlow/models/research/object_detection/utils/visualization_utils.py", line 29, in <module>
    import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
  File "/localdisk/workspace/pycharm/anaconda/envs/tensorflow/lib/python3.5/site-packages/matplotlib/__init__.py", line 141, in <module>
    from . import cbook, rcsetup
  File "/localdisk/workspace/pycharm/anaconda/envs/tensorflow/lib/python3.5/site-packages/matplotlib/rcsetup.py", line 29, in <module>
    from cycler import Cycler, cycler as ccycler
ImportError: cannot import name 'Cycler'`

![Screenshot from 2020-01-31 08-53-03](https://user-images.githubusercontent.com/60502844/73523519-5d5e1f80-440b-11ea-941f-3bea63fd976c.png)

cycler is already installed but somehow its not able to import it. Can someone please help?

Thanks!

**Comment by chunduriv** [comment]
@jm-mirza,

Sorry for the late response. This likely happens because `cycler` is installed but doesn’t reside in the path you can use. You can try to extend the python path. Thank you.
