### ISSUE TITLE
quantization-aware training of ResNet50 model

### ISSUE THREAD

**Issue by rose-jinyang** [tensorflow/models#8107]
Hello,
While I'm working on transfer learning of ResNet50 model, I'm going to do quantization aware training of the final model.
I have a run-time issue in tf.contrib.quantize.create_training_graph method when I do quantization aware training of Resnet50.
Traceback (most recent call last):
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1741, in
main()
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1735, in main
globals = debugger.run(setup['file'], None, None, is_module)
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1135, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "D:/Jin/Internet_Task/Jobs/2019/2019.11.20-fr_fl_rasppi-sridhar/work/fr_jin/fr_jin/test_quant_aware_training.py", line 42, in
tf.contrib.quantize.create_training_graph(sess.graph)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\quantize_graph.py", line 122, in create_training_graph
freeze_bn_delay=freeze_bn_delay)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\quantize_graph.py", line 73, in _create_graph
is_training=is_training)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 53, in FoldBatchNorms
graph, is_training, freeze_batch_norm_delay=freeze_batch_norm_delay)
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 98, in _FoldFusedBatchNorms
freeze_batch_norm_delay=freeze_batch_norm_delay))
File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\contrib\quantize\python\fold_batch_norms.py", line 384, in _ComputeBatchNormCorrections
match.moving_variance_tensor + match.batch_epsilon)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

I think that the problem is the batch normalization of ResNet50.
I'm using Python 3.7 and tensorflow 1.14/1.15.
Could anybody help me for this issue?
Thanks

**Comment by saberkun** [comment]
tf.contrib.quantize uses pattern matching to add fake quant nodes. 
(1) you can try to add some identity nodes around batch norm to see if anything change
(2) debug more on TypeError: unsupported operand type(s) for +: 'NoneType' and 'float', why there is None?
(3) try to use batch norm without fusion?

**Comment by LeeHXAlice** [comment]
You can try to set the use_bias parameter of Conv to **True**

**Comment by jaeyounkim** [comment]
@rose-jinyang Please clarify which file you are using in the repository when you create an issue.
Please reopen this issue if you still have a problem.
