### ISSUE TITLE
Exporting tranformer model for serving.

### ISSUE THREAD

**Issue by jayendra13** [tensorflow/models#8150]
How to export the transformer model trained in TPU to serve it? I found some relevant issue here https://github.com/tensorflow/models/pull/4281 but I think this is obsolete now.

If I try to add `self.predict_model.save('mumodel')` under `def eval` of `TransformerTask` that gives me the following error.
```
Traceback (most recent call last):
  File "transformer_main.py", line 544, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 535, in main
    task.eval()
  File "transformer_main.py", line 425, in eval
    tf.keras.models.save_model(self.predict_model, 'mymodel', overwrite=True, include_optimizer=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/save.py", line 115, in save_model
    signatures, options)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/saved_model/save.py", line 886, in save
    checkpoint_graph_view)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/saved_model/signature_serialization.py", line 74, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/saved_model/save.py", line 142, in list_functions
    self._serialization_cache)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2420, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/base_serialization.py", line 91, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 80, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 162, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 258, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 172, in wrap_layer_functions
    '{}_layer_call_and_return_conditional_losses'.format(layer.name))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 513, in add_function
    self.add_trace(*self._input_signature)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 428, in add_trace
    trace_with_training(True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 426, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 557, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/eager/def_function.py", line 909, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 534, in wrapper
    ret = method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 113, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 112, in <lambda>
    lambda: replace_training_and_call(True),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 108, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 576, in call_and_return_conditional_losses
    return layer_call(inputs, *args, **kwargs), layer.get_losses_for(inputs)
  File "/work/models/official/transformer/v2/transformer.py", line 121, in call
    if len(inputs) == 2:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 733, in __len__
    "shape information.".format(self.name))
TypeError: len is not well defined for symbolic Tensors. (input_1:0) Please call `x.shape` rather than `len(x)` for shape information.
```

**Comment by saberkun** [comment]
Do you mean you added model.save() here? 
https://github.com/tensorflow/models/blob/master/official/nlp/transformer/transformer_main.py#L379
It seems that keras did not figure out the correct input tensors. 
We should feed a list: [inputs]
https://github.com/tensorflow/models/blob/master/official/nlp/transformer/transformer.py#L120
It may need some tensorspec. The other issue is for legacy estimator code which is not used here.

I will take a look and please feel free to try in the meantime.
Thank you

**Comment by jayendra13** [comment]
Yes I am appending the `model.save` at that location. 
So we have to pass a Tensorspec instead of list of tensors to make this work ?
I will try that.

**Comment by jayendra13** [comment]
Hi any updates here or pointers which I can look in to ?

**Comment by mrmartin** [comment]
Any reason not to use [the procedure explained in the README](https://github.com/tensorflow/models/tree/1cb0b9760196eee24889c24cc9a45cbd044411f4/official/r1/transformer#export-trained-model)? This works

**Comment by jayendra13** [comment]
Hey thanks for pointing this out I was not aware of this, I was always looking at https://github.com/tensorflow/models/tree/master/official/nlp/transformer . I will try this.
