### ISSUE TITLE
Error in models defined under research folder -> "object_detection.protos.StringIntLabelMap" has 'no field named node'.

### ISSUE THREAD

**Issue by yugaljain1999** [tensorflow/models#8181]
https://user-images.githubusercontent.com/32617984/75138549-7dce8080-5710-11ea-83ce-9214a78a6a51.png)

How should I resolve this error? I was using Faster-RCNN pretrained model and when I run main file I got this error..
google.protobuf.text_format.ParseError: 1:1 : Message type "object_detection.protos.StringIntLabelMap" has no field named "node".

Please help me to solve this error..

**Comment by monchichi27** [comment]
I have the same error with you. Have you find the reason?
---------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\workspace\models-master\research\object_detection\utils\label_map_util.py", line 155, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 702, in Merge
    allow_unknown_field=allow_unknown_field)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 770, in MergeLines
    return parser.MergeLines(lines, message)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 795, in MergeLines
    self._ParseOrMerge(lines, message)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 817, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 909, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "object_detection.protos.StringIntLabelMap" has no field named "node".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection\detect_test.py", line 34, in <module>
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "D:\workspace\models-master\research\object_detection\utils\label_map_util.py", line 157, in load_labelmap
    label_map.ParseFromString(label_map_string)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\internal\python_message.py", line 1124, in MergeFromString
    serialized = memoryview(serialized)
TypeError: memoryview: a bytes-like object is required, not 'str'

**Comment by monchichi27** [comment]
Traceback (most recent call last):
  File "D:\workspace\models-master\research\object_detection\utils\label_map_util.py", line 155, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 702, in Merge
    allow_unknown_field=allow_unknown_field)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 770, in MergeLines
    return parser.MergeLines(lines, message)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 795, in MergeLines
    self._ParseOrMerge(lines, message)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 817, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\text_format.py", line 909, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "object_detection.protos.StringIntLabelMap" has no field named "node".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection\detect_test.py", line 34, in <module>
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "D:\workspace\models-master\research\object_detection\utils\label_map_util.py", line 157, in load_labelmap
    label_map.ParseFromString(label_map_string)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "D:\Program Files\Anaconda3\envs\py36\lib\site-packages\google\protobuf\internal\python_message.py", line 1124, in MergeFromString
    serialized = memoryview(serialized)
TypeError: memoryview: a bytes-like object is required, not 'str'

I have the same error with you. Have you find the reason?

**Comment by yugaljain1999** [comment]
No, I didn't get any solution yet.

**Comment by eusojk** [comment]
@yugaljain1999, did you have the chance to figure this one out by any chance?

**Comment by yugaljain1999** [comment]
@eusojk No, I didn't get any solution of this. 
I think tf developers needs to fix this.

**Comment by Sayali22** [comment]
Did anyone find the solution? or workaround?
Any help is appreciated. Thank you.
