### ISSUE TITLE
im2txt: Unable to generate captions after moving trained data to different server

### ISSUE THREAD

**Issue by redserpent7** [tensorflow/models#820]
Hi,

I have trained im2txt a while back and it works fine on the server that I trained the model on. Recenlty I tried moving the trained model to a different server, I gitcloned im2txt, installed bazel, python and nltk (with nltk data). 

I then ran the generate captions script pointing to my training and vocab directory/file but I am getting this exception:

```Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 49, in main
    FLAGS.checkpoint_path)
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 115, in build_graph_from_config
    self.build_model(model_config)
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_wrapper.py", line 36, in build_model
    model.build()
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 352, in build
    self.build_inputs()
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 138, in build_inputs
    images = tf.expand_dims(self.process_image(image_feed), 0)
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/show_and_tell_model.py", line 119, in process_image
    image_format=self.config.image_format)
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py", line 106, in process_image
    image_summary("original_image", image)
  File "/home/ubuntu/tensorflow/tensorflow/models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/ops/image_processing.py", line 95, in image_summary
    tf.image_summary(name, tf.expand_dims(image, 0))
AttributeError: 'module' object has no attribute 'image_summary'```


Not sure what I missed or missing here, the caption scripts still works fine on the server where I trained the model.

Is there anything else I need to do beside copying the training data and word count file?

**Comment by redserpent7** [comment]
Any updates to this, I cannot seem to use im2txt with the latest tensorflow. It seems its using a function that is missing from the latest tf

**Comment by cshallue** [comment]
This was caused by some changes in the TensorFlow API. Pushing the fixes now.
