### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'video_id' is required but could not be found. 	 [[{{node train_input/ParseSingleSequenceExample_1/ParseSingleSequenceExample}}]]

### ISSUE THREAD

**Issue by shreyasgan** [tensorflow/models#8204]
### System information
- **youtube-8m**:
- **stock scripts**:
- **Mac OS Mojave**:
- **TensorFlow installed from source**:
- **TensorFlow version 1.15**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- ***:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'video_id' is required but could not be found.
	 [[{{node train_input/ParseSingleSequenceExample_1/ParseSingleSequenceExample}}]]
- **Exact command to reproduce**:
python youtube-8m/train.py --train_data_pattern=features/*.tfrecord --num_epochs=100 --learning_rate_decay_examples=40000 --feature_names=audio_embedding --feature_sizes=128 --frame_features --batch_size=64 --num_classes=20 --train_dir=trainlog --base_learning_rate=0.001 --model=LstmModel

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
The problem is that when the train.py script is run with those parameters, this issue is produced

### Source code / logs
INFO:tensorflow:/job:master/task:0: Done training -- epoch limit reached.
I0226 19:53:43.094465 4695209408 train.py:462] /job:master/task:0: Done training -- epoch limit reached.
Traceback (most recent call last):
  File "youtube-8m/train.py", line 670, in <module>
    app.run()
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "youtube-8m/train.py", line 661, in main
    FLAGS.export_model_steps).run(start_new_model=FLAGS.start_new_model)
  File "youtube-8m/train.py", line 462, in run
    task_as_string(self.task))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/tensorflow_core/python/training/supervisor.py", line 1014, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/tensorflow_core/python/training/supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/tensorflow_core/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1287, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/Users/shreyasganesh/vggish/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'video_id' is required but could not be found.
	 [[{{node train_input/ParseSingleSequenceExample_1/ParseSingleSequenceExample}}]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
GPU model and memory

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
