### ISSUE TITLE
ValueError: Eval batch size 256 is not divisible by 1000

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8206]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 LTS
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 2.1.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Please provide the entire URL of the model you are using?**
https://github.com/tensorflow/models/blob/master/official/recommendation/ncf_estimator_main.py --

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**

**Other info / logs**
 Traceback (most recent call last):
  File "official/recommendation/ncf_estimator_main.py", line 189, in <module>
    absl_app.run(main)
  File "/home/ayushman/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ayushman/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "official/recommendation/ncf_estimator_main.py", line 108, in main
    run_ncf(FLAGS)
  File "official/recommendation/ncf_estimator_main.py", line 116, in run_ncf
    ncf_common.get_inputs(params))
  File "/home/ayushman/Documents/Github/models/official/recommendation/ncf_common.py", line 61, in get_inputs
    deterministic=FLAGS.seed is not None)
  File "/home/ayushman/Documents/Github/models/official/recommendation/data_preprocessing.py", line 236, in instantiate_pipeline
    create_data_offline=generate_data_offline)
  File "/home/ayushman/Documents/Github/models/official/recommendation/data_pipeline.py", line 852, in __init__
    super(BisectionDataConstructor, self).__init__(*args, **kwargs)
  File "/home/ayushman/Documents/Github/models/official/recommendation/data_pipeline.py", line 414, in __init__
    eval_batch_size, 1 + rconst.NUM_EVAL_NEGATIVES))
ValueError: Eval batch size 256 is not divisible by 1000

**Comment by saberkun** [comment]
Hi ayushmankumar7 
Sorry. Would you mind using the keras version? 
recommendation/ncf_estimator_main.py is not maintained for a while.

**Comment by ayushmankumar7** [comment]
Okay. No Problem.
