### ISSUE TITLE
tutorials/cifar10_multi_gpu_train.py

### ISSUE THREAD

**Issue by AIROBOTAI** [tensorflow/models#826]
I encountered the following error when running `cifar10_multi_gpu_train.py`. Could anyone kindly provide a solution? Thanks a lot!

```
/usr/bin/python2.7 /home/AIJ/tf-models/tutorials/image/cifar10/cifar10_multi_gpu_train.py
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:120] successfully opened CUDA library libcurand.so.7.0 locally
E tensorflow/core/framework/op_kernel.cc:925] OpKernel ('op: "NegTrain" device_type: "CPU"') for unknown op: NegTrain
E tensorflow/core/framework/op_kernel.cc:925] OpKernel ('op: "Skipgram" device_type: "CPU"') for unknown op: Skipgram
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
WARNING:tensorflow:From /home/AIJ/tf-models/tutorials/image/cifar10/cifar10_input.py:135: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.image uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
WARNING:tensorflow:From /home/AIJ/tf-models/tutorials/image/cifar10/cifar10_input.py:135: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.image uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
Traceback (most recent call last):
  File "/home/AIJ/tf-models/tutorials/image/cifar10/cifar10_multi_gpu_train.py", line 273, in <module>
    tf.app.run()
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/AIJ/tf-models/tutorials/image/cifar10/cifar10_multi_gpu_train.py", line 269, in main
    train()
  File "/home/AIJ/tf-models/tutorials/image/cifar10/cifar10_multi_gpu_train.py", line 210, in train
    variables_averages_op = variable_averages.apply(tf.trainable_variables())
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/training/moving_averages.py", line 375, in apply
    colocate_with_primary=True)
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/training/slot_creator.py", line 101, in create_slot
    return _create_slot_var(primary, val, '')
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/training/slot_creator.py", line 55, in _create_slot_var
    slot = variable_scope.get_variable(scope, initializer=val, trainable=False)
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 1063, in get_variable
    custom_getter=custom_getter)
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 889, in get_variable
    custom_getter=custom_getter)
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 347, in get_variable
    validate_shape=validate_shape)
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 332, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/AIJ/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 656, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable conv1/weights/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

```

**Comment by michaelisard** [comment]
This type of usage question is better asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). Github issues are for bug reports and installation issues.
