### ISSUE TITLE
How to fine tune mobile net?

### ISSUE THREAD

**Issue by bgyoo91** [tensorflow/models#8272]
I want to do fine tuning using a pre-trained mobile net.
so, I looked at an example of slim and proceeded with a lot of problems.
I downloaded the flower dataset and pre-trained model(checkpoint) and ran the program with the following command.
However, the following error occurred. What is the problem.

> python train_image_classifier.py --train_dir=${TRAIN_DIR} --dataset_name=flowers --dataset_split_name=train --dataset_dir=${DATASET_DIR} --model_name=mobilenet_v2 --checkpoint_path=/tmp/checkpoints/mobilenet_v2_1.4_224.ckpt --checkpoint_exclude_scopes=MobilenetV2/Logits --trainable_scopes=MobilenetV2/Logits 

```
INFO:tensorflow:Restoring parameters from /tmp/checkpoints/mobilenet_v2_1.4_224.ckpt
I0312 18:52:10.890867 140344273155904 saver.py:1284] Restoring parameters from /tmp/checkpoints/mobilenet_v2_1.4_224.ckpt
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [384] rhs shape= [528]
	 [[node save/Assign_223 (defined at /home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/Assign_223':
  File "train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_image_classifier.py", line 580, in main
    init_fn=_get_init_fn(),
  File "train_image_classifier.py", line 374, in _get_init_fn
    ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 758, in assign_from_checkpoint_fn
    write_version=saver_pb2.SaverDef.V1)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

I0312 18:52:11.253753 140344273155904 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [384] rhs shape= [528]
	 [[node save/Assign_223 (defined at /home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/Assign_223':
  File "train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_image_classifier.py", line 580, in main
    init_fn=_get_init_fn(),
  File "train_image_classifier.py", line 374, in _get_init_fn
    ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 758, in assign_from_checkpoint_fn
    write_version=saver_pb2.SaverDef.V1)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

Traceback (most recent call last):
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [384] rhs shape= [528]
	 [[{{node save/Assign_223}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [384] rhs shape= [528]
	 [[node save/Assign_223 (defined at /home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/Assign_223':
  File "train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_image_classifier.py", line 580, in main
    init_fn=_get_init_fn(),
  File "train_image_classifier.py", line 374, in _get_init_fn
    ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 758, in assign_from_checkpoint_fn
    write_version=saver_pb2.SaverDef.V1)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_image_classifier.py", line 586, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/slim/python/slim/learning.py", line 753, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/supervisor.py", line 1014, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/supervisor.py", line 1003, in managed_session
    start_standard_services=start_standard_services)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/supervisor.py", line 734, in prepare_or_wait_for_session
    init_fn=self._init_fn)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/session_manager.py", line 298, in prepare_session
    init_fn(sess)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 761, in callback
    saver.restore(session, model_path)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1326, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [384] rhs shape= [528]
	 [[node save/Assign_223 (defined at /home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/Assign_223':
  File "train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_image_classifier.py", line 580, in main
    init_fn=_get_init_fn(),
  File "train_image_classifier.py", line 374, in _get_init_fn
    ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 758, in assign_from_checkpoint_fn
    write_version=saver_pb2.SaverDef.V1)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'init_ops/report_uninitialized_variables/boolean_mask/GatherV2:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 321, in run
    raise  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))  File "train_image_classifier.py", line 586, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/slim/python/slim/learning.py", line 796, in train
    should_retry = True  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
E0312 18:52:11.501665 140344273155904 tf_should_use.py:76] ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'init_ops/report_uninitialized_variables/boolean_mask/GatherV2:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 321, in run
    raise  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))  File "train_image_classifier.py", line 586, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/contrib/slim/python/slim/learning.py", line 796, in train
    should_retry = True  File "/home/bgyoo/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
```

**Comment by hust-nj** [comment]
Hello, I encountered the same problem.
Have you solved it?
@bgyoo91
