### ISSUE TITLE
Recurrent neuron network tutorial throw exception

### ISSUE THREAD

**Issue by bdqnghi** [tensorflow/models#829]
When I tried to run the Recurrent network for PTB dataset example, it throws an exception like this:

```
Traceback (most recent call last):
  File "ptb_word_lm.py", line 371, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 331, in main
    train_input = PTBInput(config=config, data=train_data, name="TrainInput")
  File "ptb_word_lm.py", line 94, in __init__
    data, batch_size, num_steps, name=name)
  File "/home/quocnghi/codes/models/tutorials/rnn/ptb/reader.py", line 119, in ptb_producer
    [batch_size, (i + 1) * num_steps])
TypeError: strided_slice() takes at least 4 arguments (3 given)
```

**Comment by michaelisard** [comment]
Could you give more details about your setup and exactly what you ran?

**Comment by jart** [comment]
Looking at the code, strided_slice appears to take three mandatory arguments. Maybe TensorFlow needs to be upgraded? I'm not sure. Anyway closing due to inactivity. Provided new information, I will re-open.

**Comment by wookayin** [comment]
@bdqnghi For your reference: The `strides` argument is optional with the latest version (TF 0.12 or master) (which was not, requiring 4 in TF 0.10) and the **current code is correct**, being up-to-date. I guess you might be using an old version of TensorFlow. The default value to `strides` will be `tf.ones_like(begin)`, i.e. `tf.ones_like([0, i * num_steps + 1])`.

**Comment by annuskeras** [comment]
I have exact the same error message with Tensorflow 0.12.1 while trying to run ptb_word_lm.py from model/tutorial/rnn/ptb.

**Comment by Jin-Chen-cn** [comment]
Same issue as what annuskeras found

**Comment by nimral** [comment]
Same issue here.

**Comment by chenhe95** [comment]
Same issue here, had the error with 
```
python -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 2
0.12.1
```

**Comment by bowu** [comment]
Is this problem solved? I had the same issue.

**Comment by FCInter** [comment]
I also have the same issue when running the models/tutorial/rnn/ptb_word_lm.py

**Comment by evankozliner** [comment]
Running into this issue as well :(

**Comment by WakedupChan** [comment]
I also have the same issue when running the models/tutorial/rnn/ptb_word_lm.py, and when I check the source code of strided_slice() at path "/usr/local/lib/python2.7/dist-packages/ops/gen_array_ops.py" in line 2385, I found that the source code of strided_slice(input,begin,end,strides,begin_mask=None,...) function really need four params at least, which is different from the latest version in tensorflow's API page(https://www.tensorflow.org/api_docs/python/tf/strided_slice).
Therefore, we need to do is to update its version, and it is really effective.
The commands of upgrading tensorflow as follows:
sudo pip uninstall tensorflow
sudo pip install tensorflow
Then, try to run ptb_word_lm.py with command:
python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model=small

**Comment by hleborgne** [comment]
Indeed by simply updating tensorflow, it fixed the issue. on Tensorflow activated:
pip install --upgrade tensorflow

**Comment by haoqipaopao** [comment]
pip install --upgrade tensorflow
when i update my tensorflow ,it's ok
