### ISSUE TITLE
support model feelvos with python 3.6+

### ISSUE THREAD

**Issue by wincent8** [tensorflow/models#8301]
**Please provide the entire URL of the model you are using?**
https://github.com/tensorflow/models/tree/master/research/feelvos

**Describe the feature you request and the current behavior/state.**
when i use python 2.7, it is ok. But When I use python3.6, i will face the below issue.

Traceback (most recent call last):
  File "/home/usr/oob/tf1.15/third_party/models/research/feelvos/vis_video.py", line 505, in <module>
    tf.app.run()
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/usr/oob/tf1.15/third_party/models/research/feelvos/vis_video.py", line 431, in main
    samples, reference_labels, first_frame_img, model_options)
  File "/home/usr/oob/tf1.15/third_party/models/research/feelvos/vis_video.py", line 298, in create_predictions_fast
    first_frame_img[tf.newaxis], model_options, FLAGS.embedding_dimension)
  File "/home/usr/oob/tf1.15/third_party/models/research/feelvos/utils/embedding_utils.py", line 502, in get_embeddings
    features, embedding_dimension, scope='split_separable_conv2d')
  File "/home/usr/oob/tf1.15/third_party/models/research/feelvos/utils/embedding_utils.py", line 955, in split_separable_conv2d_with_identity_initializer
    scope=scope + '_depthwise')
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 2816, in separable_convolution2d
    collections=weights_collections)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 351, in model_variable
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 281, in variable
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 550, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 1761, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 1752, in _model_variable_getter
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 351, in model_variable
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 281, in variable
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 933, in _get_single_variable
    aggregation=aggregation)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 258, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 219, in _variable_v1_call
    shape=shape)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 197, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2519, in default_variable_creator
    shape=shape)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 1688, in __init__
    shape=shape)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 1818, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/usr/anaconda3/envs/bp/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 905, in <lambda>
    partition_info=partition_info)
  File "/home/usr/oob/tf1.15/third_party/models/research/feelvos/utils/embedding_utils.py", line 915, in _initializer
    weights[center_y, center_x, i, i] = scale
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

so, i think it maybe the python version issue.

**Are you willing to contribute it (Yes/No)?**
Yes

**Any other info.**

**Comment by cbaus** [comment]
You need integer division on the center_x and center_y values. Unfortunately I noticed a lot of other changes required for python 3.6+.

Haven't fully gone trough all files otherwise you'd get those.

Here is the patch file for embedding_utils.py:

[patch.txt](https://github.com/tensorflow/models/files/4374671/patch.txt)
