### ISSUE TITLE
ValueError: Eval batch size 256 is not divisible by 1000

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/models#8319]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 LTS
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 2.2.0rc
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/blob/master/official/recommendation/ncf_keras_main.py
**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**

python3 official/recommendation/ncf_keras_main.py 

**Other info / logs**

Traceback (most recent call last):
  File "official/recommendation/ncf_keras_main.py", line 562, in <module>
    app.run(main)
  File "/home/ayushman/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ayushman/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "official/recommendation/ncf_keras_main.py", line 557, in main
    run_ncf(FLAGS)
  File "official/recommendation/ncf_keras_main.py", line 246, in run_ncf
    num_users, num_items, _, _, producer = ncf_common.get_inputs(params)
  File "/home/ayushman/Documents/github/models/official/recommendation/ncf_common.py", line 61, in get_inputs
    deterministic=FLAGS.seed is not None)
  File "/home/ayushman/Documents/github/models/official/recommendation/data_preprocessing.py", line 236, in instantiate_pipeline
    create_data_offline=generate_data_offline)
  File "/home/ayushman/Documents/github/models/official/recommendation/data_pipeline.py", line 852, in __init__
    super(BisectionDataConstructor, self).__init__(*args, **kwargs)
  File "/home/ayushman/Documents/github/models/official/recommendation/data_pipeline.py", line 414, in __init__
    eval_batch_size, 1 + rconst.NUM_EVAL_NEGATIVES))
ValueError: Eval batch size 256 is not divisible by 1000

**Comment by saberkun** [comment]
The issue is fixed. the batch size should 99000, etc. updated the default value. Thanks
