### ISSUE TITLE
error when wanted to generate tfrecord. Please help! Thanks!

### ISSUE THREAD

**Issue by xueqing311** [tensorflow/models#8322]
when I write the coding 'python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record'  The error below shown up:

Traceback (most recent call last):
  File "generate_tfrecord.py", line 126, in <module>
    tf.app.run()
  File "C:\Users\LiewXQ\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 117, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 106, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\tensorflow1\models\research\object_detection\utils\dataset_util.py", line 30, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long

Can anyone help me to find out what is the problem???

**Comment by proxip** [comment]
please check on def **class_text_to_int(row_label):** section on generate_tfrecord.py, change : **0 / None** to **return 0**

**Comment by xueqing311** [comment]
> please check on def **class_text_to_int(row_label):** section on generate_tfrecord.py, change : **0 / None** to **return 0**

**Comment by dreamitpossible1** [comment]
This is wrong
