### ISSUE TITLE
Transfer Learning with Inceptionv3 - flag directory error

### ISSUE THREAD

**Issue by CapitalZe** [tensorflow/models#8349]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04 running via VMware on Macbook Pro - External HDD
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.14.0
- Python version: 3
- Bazel version (if compiling from source): 2.2.0
- GCC/Compiler version (if compiling from source):5.4.0

**Describe the current behavior**

Using a custom dataset of grocery store items to retrain InceptionV3. The dataset is hosted on an external hard drive and is accessible by cd'ing into it. The `noexec` option is not tagged.
I can edit and modify the external hard drive data via terminal.

Running an unmodified retrain.py fails with the following error: `AttributeError: 'NoneType' object has no attribute 'keys`

Tracing back, I can see the dir_path is prepended incorrectly: `E0401 14:27:30.038295 140710347978496 retrain.py:141] Image directory '/home/XXX/media/XXX/book/dataset/train_img' not found.`

The pertinent output is:
`E0401 14:27:30.038295 140710347978496 retrain.py:141] Image directory '/home/XXX/media/XXX/book/dataset/train_img' not found.
Traceback (most recent call last):
  File "retrain.py", line 1285, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/XXX/MIDI/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/XXX/MIDI/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/XXX/MIDI/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "retrain.py", line 943, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
`

**Describe the expected behavior**
I expected the dir_path, in this case the image_dir, to be as I flagged it: `--image_dir ~/media/XXX/book/dataset/train_img`

and not what is seen in the output, above: `'/home/XXX/media/XXX/book/dataset/train_img' not found.`

**Code to reproduce the issue**

`python3 retrain.py --model_dir ./media/XXX/book/tmp/checkpoints --image_dir ~/media/XXX/book/dataset/train_img --output_graph ./media/XXX/book/tmp --how_many_training_steps 1000`

I ask if anyone knows why the dir_path is prepended with `home` directory, then the user `XXX`, and then follows the flagged directive?
I cannot find where in [retrain.py](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py) the germane changes should be made.
Line 141 assigns the `dir_name = os.path.basename()` and not a `os.path.dirname(path)`.

So I am trying to ascertain why the dir_path is prepended with the local `home` directory and then the user `/home/XXX/`.

If anyone can assist it would be a great help.

**Comment by CapitalZe** [comment]
It was syntax error to a certain degree. Resolved.
