### ISSUE TITLE
Saving Transformer Model to saved_model (.pb) format  [ TypeError: len is not well defined for symbolic Tensors ]

### ISSUE THREAD

**Issue by s4sarath** [tensorflow/models#8357]
Hi,

Tensorflow Version - '2.2.0-dev20200402'

I tried with other TF2 versions also.

I was able to train the model for en_de translation task and model seems pretty decent. But, When I tried to save it as a saved-model format , I am getting an error .

https://github.com/tensorflow/models/blob/master/official/nlp/transformer/transformer.py#L120
```
TypeError: len is not well defined for symbolic Tensors. (input_1:0) Please call `x.shape` rather than `len(x)` for shape information.
```
![image](https://user-images.githubusercontent.com/10637096/78348511-c73ba680-75bf-11ea-9e86-0006a4e35b1c.png)

**Comment by s4sarath** [comment]
So, to avoid the above bug, I removed ``` if len(inputs) == 2: ``` to ``` if training ``` , as both does the same purpose ( logically ). The previous error went off. But now another error in LayerNormalization . While converting to saved_model format, in the following line

https://github.com/tensorflow/models/blob/master/official/nlp/transformer/transformer.py#L368

```
StagingError: in user code:

    /Users/a642163/models-master/official/nlp/transformer/transformer.py:386 call  *
        y = self.layer_norm(x)
    /Users/a642163/anaconda3/envs/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:937 __call__  **
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /Users/a642163/anaconda3/envs/venv_tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py:1116 call
        broadcast_shape[dim] = input_shape.dims[dim].value

    IndexError: list index out of range
```

Any help?

**Comment by haimat** [comment]
How can you make this Object Detection API work with TF2, I tought it's for TF1.x only?!

**Comment by s4sarath** [comment]
Is it related to this @matt ?

**Comment by saberkun** [comment]
I don't really understand why the implementation needs: "*args, **kwargs" there. Can you try to remove them?
  def call(self, x, *args, **kwargs):
    """Calls wrapped layer with same parameters."""
    # Preprocessing: apply layer normalization
    training = kwargs["training"]

    y = self.layer_norm(x)

    # Get layer output
    y = self.layer(y, *args, **kwargs)

    # Postprocessing: apply dropout and residual connection
    if training:
      y = tf.nn.dropout(y, rate=self.postprocess_dropout)
    return x + y

**Comment by stefan-falk** [comment]
It seems that `inputs` is a tensor creating the infer graph. So, I created a simple patch for the `Transformer.call` method:

```python
def call_patch(self, inputs, training):
    if isinstance(inputs, list) and len(inputs) == 2:
        inputs, targets = inputs[0], inputs[1]
    else:
        # Decoding path.
        if isinstance(inputs, list):
            inputs, targets = inputs[0], None
        else:
            inputs, targets = inputs, None

        if self.params["padded_decode"]:
            if not self.params["num_replicas"]:
                raise NotImplementedError(
                    "Padded decoding on CPU/GPUs is not supported.")
            decode_batch_size = int(self.params["decode_batch_size"] /
                                    self.params["num_replicas"])
            inputs.set_shape([
                decode_batch_size, self.params["decode_max_length"]
            ])

    # Variance scaling is used here because it seems to work in many problems.
    # Other reasonable initializers may also work just as well.
    with tf.name_scope("Transformer"):
        # Calculate attention bias for encoder self-attention and decoder
        # multi-headed attention layers.
        attention_bias = model_utils.get_padding_bias(inputs)

        # Run the inputs through the encoder layer to map the symbol
        # representations to continuous representations.
        encoder_outputs = self.encode(inputs, attention_bias, training)
        # Generate output sequence if targets is None, or return logits if target
        # sequence is known.
        if targets is None:
            return self.predict(encoder_outputs, attention_bias, training)
        else:
            logits = self.decode(targets, encoder_outputs, attention_bias, training)
            return logits


transformer.Transformer.call = call_patch
```

This works but only until the next issue occurs:

> ValueError: call() should not modify its Python input arguments. Check if it modifies any lists or dicts passed as arguments. Modifying a copy is allowed.

It seems that, somewhere in the attention layer, inputs are mutated:

![image](https://user-images.githubusercontent.com/43335432/78995108-f2834000-7b41-11ea-8ace-e8b6133830a2.png)

### Full stack trace of the following exception

```
Traceback (most recent call last):
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/sfalk/tmp/pycharm_project_157/asr/main_translation_load2.py", line 150, in main
    model.save('/tmp/infer-model', include_optimizer=False, save_format='tf')
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1062, in save
    signatures, options)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 134, in save_model
    signatures, options)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1010, in _build_meta_graph
    checkpoint_graph_view)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 143, in list_functions
    self._serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1754, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2712, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 87, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 77, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 153, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 272, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 163, in wrap_layer_functions
    '{}_layer_call_and_return_conditional_losses'.format(layer.name))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 503, in add_function
    self.add_trace(*self._input_signature)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 418, in add_trace
    trace_with_training(True)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 416, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 547, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1000, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 906, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 548, in _initialize
    *args, **kwds))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2447, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2775, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2665, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 459, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 524, in wrapper
    ret = method(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 170, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 65, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 169, in <lambda>
    lambda: replace_training_and_call(True),
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 165, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 566, in call_and_return_conditional_losses
    return layer_call(inputs, *args, **kwargs), layer.get_losses_for(inputs)
  File "/home/sfalk/tmp/pycharm_project_157/asr/main_translation_load2.py", line 67, in call_patch
    return self.predict(encoder_outputs, attention_bias, training)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/official/nlp/transformer/transformer.py", line 348, in predict
    dtype=self.params["dtype"])
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/official/nlp/transformer/beam_search.py", line 113, in sequence_beam_search
    return sbs.search(initial_ids, initial_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/official/nlp/transformer/beam_search.py", line 38, in search
    parallel_iterations=1))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2494, in while_loop_v2
    return_same_structure=True)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2691, in while_loop
    back_prop=back_prop)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py", line 196, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py", line 174, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/official/nlp/transformer/beam_search_v1.py", line 326, in _search_step
    new_seq, new_log_probs, topk_ids, new_cache = self._grow_alive_seq(state)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/official/nlp/transformer/beam_search_v1.py", line 375, in _grow_alive_seq
    flat_logits, flat_cache = self.symbols_to_logits_fn(flat_ids, i, flat_cache)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/official/nlp/transformer/transformer.py", line 285, in symbols_to_logits_fn
    decode_loop_step=i if self.params["padded_decode"] else None)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 937, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 71, in return_outputs_and_add_losses
    outputs, losses = fn(inputs, *args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 170, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 65, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 169, in <lambda>
    lambda: replace_training_and_call(True),
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 165, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 541, in __call__
    self.call_collection.add_trace(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 418, in add_trace
    trace_with_training(True)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 416, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 547, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1000, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 906, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 548, in _initialize
    *args, **kwds))
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2447, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2775, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2665, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 988, in func_graph_from_py_func
    check_mutation(func_args_before, func_args, original_func)
  File "/home/sfalk/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1072, in check_mutation
    raise ValueError(errmsg)
ValueError: call() should not modify its Python input arguments. Check if it modifies any lists or dicts passed as arguments. Modifying a copy is allowed.
```

**Comment by saberkun** [comment]
Thanks for reporting! This is informative.
https://github.com/tensorflow/models/blob/master/official/nlp/transformer/attention_layer.py#L91
cache=None is mutable during decoding. I have tried another implementation: https://github.com/tensorflow/models/blob/master/official/nlp/modeling/layers/attention.py#L359
This works. We have a contributor to work on migrating the Transformer to using the modules inside nlp/modeling to resolve this issue. Sorry, it is more complicated than we thought originally.

**Comment by s4sarath** [comment]
Yes I know. It's very complicated. I am also working on this. I will let
you know about it, if it works well.

**Comment by 2020zyc** [comment]
I encountered the same error:

"ValueError: call() should not modify its Python input arguments. Check if it modifies any lists or dicts passed as arguments. Modifying a copy is allowed."

REPRODUCTION:

I used the almost latest code(0907) from "https://github.com/tensorflow/models/tree/master/official/nlp/transformer/";

I trained the model and restored the weights in the prediction mode successfully, then I tried to save the model in the protocol buffer format(savedModel):

```
...
with tf.name_scope("model"):
    model = transformer.create_model(params, is_train=False)
    self._load_weights_if_possible(model, tf.train.latest_checkpoint(self.flags_obj.model_dir))
    model.summary()

logging.info("Save inference graph into the .pb format.")
model.save(os.path.join(flags_obj.model_dir, "1"), include_optimizer=False)  #  ----> error here
logging.info("successfully.")
...
```

Any help?

**Comment by 2020zyc** [comment]
**Part of the error log, it seems the "decoder_stack"  is the source of the error**:

File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 635, in sequence_beam_search
    return sbs.search(initial_ids, initial_cache)
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 414, in search
    parallel_iterations=1))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2499, in while_loop_v2
    return_same_structure=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2696, in while_loop
    back_prop=back_prop)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/while_v2.py", line 196, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 987, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/while_v2.py", line 174, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 390, in _search_step
    new_seq, new_log_probs, topk_ids, new_cache = _grow_alive_seq(state)
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 238, in _grow_alive_seq
    flat_ids, i, flat_cache)
  **File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/transformer/transformer.py", line 287, in symbols_to_logits_fn
    decode_loop_step=i if self.params["padded_decode"] else None)**
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 990, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 71, in return_outputs_and_add_losses
    outputs, losses = fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 169, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/control_flow_util.py", line 113, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 168, in <lambda>
    training, lambda: replace_training_and_call(True),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 165, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 543, in __call__
    self.call_collection.add_trace(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 420, in add_trace
    trace_with_training(True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 418, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 549, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1176, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1082, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 717, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2955, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3333, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3188, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 994, in func_graph_from_py_func
    check_mutation(func_args_before, func_args, original_func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 1078, in check_mutation
    raise ValueError(errmsg)
ValueError: call() should not modify its Python input arguments. Check if it modifies any lists or dicts passed as arguments. Modifying a copy is allowed.

**Comment by saberkun** [comment]
The new transformer model is released: https://github.com/tensorflow/models/blob/master/official/nlp/tasks/translation.py
https://github.com/tensorflow/models/tree/master/official/nlp/modeling/models
