### ISSUE TITLE
tensorflow configuration file running pandas errors

### ISSUE THREAD

**Issue by aneeshamaria** [tensorflow/models#8359]
(newEnv) C:\Users\Windows\Desktop\newEnv\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 16, in <module>
    import pandas as pd
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\core\groupby\__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\core\groupby\groupby.py", line 46, in <module>
    from pandas.core.index import (Index, MultiIndex,
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\core\index.py", line 2, in <module>
    from pandas.core.indexes.api import *
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\core\indexes\api.py", line 4, in <module>
    from pandas.core.indexes.base import (Index,
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\core\indexes\base.py", line 53, in <module>
    from pandas.core import ops
  File "C:\Users\Windows\Anaconda3\envs\newEnv\lib\site-packages\pandas\core\ops\__init__.py", line 23, in <module>
    from pandas.core.dtypes.common import (
ImportError: cannot import name 'ensure_object'

(newEnv) C:\Users\Windows\Desktop\newEnv\models\research\object_detection>
pls help guys

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
