### ISSUE TITLE
Errors with pip install dependencies if numpy is not pre-installed

### ISSUE THREAD

**Issue by xiangshiyin** [tensorflow/models#8384]
**Documentation URL(s) with the issue:** https://github.com/tensorflow/models/tree/master/official#method-2-clone-the-source

**Description of the issue (what needs to be changed):** 
* numpy needs to first installed in order to install the dependencies listed in `requirements.txt`. Otherwise, following error will pop up:
```
Obtaining pycocotools from git+https://github.com/cocodataset/cocoapi#egg=pycocotools&subdirectory=PythonAPI (from -r official/requirements.txt (line 25))
  Cloning https://github.com/cocodataset/cocoapi to ./src/pycocotools
  Running command git clone -q https://github.com/cocodataset/cocoapi /Users/xyin/Documents/self/models/src/pycocotools
    ERROR: Command errored out with exit status 1:
     command: /Users/xyin/anaconda3/envs/py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/xyin/Documents/self/models/src/pycocotools/PythonAPI/setup.py'"'"'; __file__='"'"'/Users/xyin/Documents/self/models/src/pycocotools/PythonAPI/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /Users/xyin/Documents/self/models/src/pycocotools/PythonAPI
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/xyin/Documents/self/models/src/pycocotools/PythonAPI/setup.py", line 2, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by saberkun** [comment]
You need to install tensorflow first and the add all requirements.
The document says you should have tensorflow first and assume users will use tensorflow inside their environment. numpy is the deps of tensorflow so the right version of numpy will be installed.
