### ISSUE TITLE
RuntimeError when using TransformerXLModel layers 

### ISSUE THREAD

**Issue by shidaide2019** [tensorflow/models#8392]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 (10.0, Build 18362)
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:None
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
Describe the problem
I want to use transformer xl in my keras model and  I use xlnet_modeling.py provided in official models to test, when testing models I met a RuntimeError.
Source code / logs
the code here is mainly from xlnet_modeling.py in official models and I rewrite some part of input.
[code.txt](https://github.com/tensorflow/models/files/4470425/code.txt)
and here's the wrong information:
Traceback (most recent call last):

  File "<ipython-input-3-049aa757e999>", line 1, in <module>
    model_use = model_test1(True)

  File "D:\bug_fixing.py", line 800, in model_test1
    a,b = user_hist_item_transformerxl([input1, input3, input4, None, None, None, None])

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)

  File "D:\bug_fixing.py", line 637, in call
    non_tgt_mask = -tf.eye(qlen, dtype=self.tf_float)

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\ops\linalg_ops.py", line 169, in eye
    name=name)

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\ops\linalg_ops_impl.py", line 65, in eye
    diag_shape = array_ops.concat((batch_shape, [diag_size]), axis=0)

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 1517, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 1334, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 412, in _apply_op_helper
    as_ref=input_arg.is_ref)

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1382, in internal_convert_n_to_tensor
    ctx=ctx))

  File "C:\Users\win\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1280, in convert_to_tensor
    raise RuntimeError("Attempting to capture an EagerTensor without "

RuntimeError: Attempting to capture an EagerTensor without building a function.

As for me, I think it may because tf.eye EagerTensor part is not attached to the graph,but I haven't come up with any idea to solve the problem above

**Comment by lehougoogle** [comment]
Hi there,

The problem is qlen is a tensor, also if you want to get the query length of 256, you should use the second dimension:

qlen = inp_k.get_shape().as_list()[1]
