### ISSUE TITLE
Some Python objects were not bound to checkpointed values

### ISSUE THREAD

**Issue by david-wb** [tensorflow/models#8399]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-29517-g242129341e 2.2.0-dev20200414
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA Version 10.1.243
- GPU model and memory: GeForce GTX 970

**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/tree/master/official/nlp/bert

**Describe the current behavior**

I am fine-tuning a bert-based model and saving checkpoints. At prediction time, restoring the checkpoints fails with the errors similar to:
```
Traceback (most recent call last):
  File "/home/david/github/bert-checkpoints-bug/predict.py", line 12, in <module>
    checkpoint.restore(tf.train.latest_checkpoint('checkpoints')).assert_existing_objects_matched()
  File "/home/david/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/util.py", line 783, in assert_existing_objects_matched
    (list(unused_python_objects),))
AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program: [<tf.Variable 'save_counter:0' shape=() dtype=int64, numpy=0>, <tf.Variable 'transformer/layer_2/self_attention_output/kernel:0' shape=(12, 64, 768) dtype=float32, numpy=
...
```
**Describe the expected behavior**
Should work without errors

**Code to reproduce the issue**

reproduce.py:
```
import os

import tensorflow as tf
from official.nlp.bert.bert_models import get_transformer_encoder
from official.nlp.bert.configs import BertConfig
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model


def build_model(bert_dir):
    max_seq_len = 384

    bert_config = BertConfig.from_json_file(os.path.join(bert_dir, 'bert_config.json'))
    bert_encoder = get_transformer_encoder(bert_config, max_seq_len)

    input_ids = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32, name='input_ids')
    input_mask = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32, name='input_mask')
    segment_ids = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32, name='segment_ids')

    bert_inputs = [input_ids, input_mask, segment_ids]
    bert_sequence_output, bert_pooled_output = bert_encoder(bert_inputs)

    out = Dense(1, activation='sigmoid', name='out')(bert_pooled_output)
    return Model(inputs=bert_inputs, outputs=[out])


dir_path = os.path.dirname(os.path.realpath(__file__))
bert_dir = os.path.join(dir_path, 'uncased_L-12_H-768_A-12')

# TRAIN

model = build_model(bert_dir)
checkpoint = tf.train.Checkpoint(model=model)
checkpoint.restore(os.path.join(bert_dir, 'bert_model.ckpt')).expect_partial()

optimizer = tf.optimizers.Adam()
model.compile(optimizer=optimizer, loss=[tf.losses.BinaryCrossentropy()])

input_ids = tf.zeros((1, 384))
input_mask = tf.zeros((1, 384))
segment_ids = tf.zeros((1, 384))

y = tf.zeros((1, 1))

checkpoint_path = "checkpoints/model.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=1)
model.fit(x=[input_ids, input_mask, segment_ids], y=y, epochs=3, callbacks=[cp_callback])

# PREDICT

model = build_model(bert_dir)
checkpoint = tf.train.Checkpoint(model=model)
checkpoint.restore(tf.train.latest_checkpoint('checkpoints')).assert_existing_objects_matched()  # <-- ERROR

input_ids = tf.zeros((1, 384))
input_mask = tf.zeros((1, 384))
segment_ids = tf.zeros((1, 384))

model.predict([input_ids, input_mask, segment_ids])
```

To reproduce, first download and extract the pre-trained model https://storage.googleapis.com/cloud-tpu-checkpoints/bert/keras_bert/uncased_L-12_H-768_A-12.tar.gz

Then run
```
python reproduce.py
```

I also have a repo with the same code as above: https://github.com/david-wb/bert-checkpoints-bug
**Other info / logs**

**Comment by david-wb** [comment]
I found that replacing 
```
checkpoint = tf.train.Checkpoint(model=model)
checkpoint.restore(tf.train.latest_checkpoint('checkpoints')).assert_existing_objects_matched()
```
with 
```
model.load_weights(tf.train.latest_checkpoint('checkpoints')).assert_existing_objects_matched()
```
resolves my issue, but this still seems like a bug.

**Comment by saberkun** [comment]
Hi, ModelCheckpoint uses save_weights api, it does not use tf.train.Checkpoint.
Yes, it is confusing because ModelCheckpoint is a keras-specific stuff.

**Comment by janpisl** [comment]
Hi, I am experiencing a similar issue, described more in details [here](https://stackoverflow.com/questions/63552169/some-python-objects-were-not-bound-to-checkpointed-values) but I don't see how to solve it based on the information here. Can you please offer some advice?

Thank you!
