### ISSUE TITLE
Inception / imagenet_train fails with python2.7

### ISSUE THREAD

**Issue by yogeshg** [tensorflow/models#840]
I am trying to train Inception CNN using imagenet in python2.7 but it is failing.

Command run:
```
bazel-bin/inception/imagenet_train --num_gpus=4 --batch_size=32 --train_dir=/tmp/imagenet_train-yo/ --data_dir=/root/host_mount/datasets/imagenet/imagenet-data
```
Log:
```
Traceback (most recent call last):
  File "/root/host_mount/code/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>
    tf.app.run()
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/root/host_mount/code/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 37, in main
    inception_train.train(dataset)
  File "/root/host_mount/code/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 239, in train
    scope)
  File "/root/host_mount/code/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 124, in _tower_loss
    loss_averages_op = loss_averages.apply(losses + [total_loss])
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/root/tensorflow-py2/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable tower_1/tower_1/CrossEntropyLoss/value/avg/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```
Other Info:
```
python -c "import tensorflow; print(tensorflow.__version__)"
0.12.1

git rev-parse HEAD
bfa1bb1bf52c4b8eabf7c1766e65dcb04164f778

bazel version
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
```

**Comment by emqiongwu** [comment]
I have the same problem. Have you resolved this problem?

**Comment by shlens** [comment]
@yogeshg  Would you be able to try to sync and rerun? Additionally, would you rerun with `--num_gpus=1`?

**Comment by yogeshg** [comment]
seems to go somewhere with 1 gpu, although i would like to know what steps I should take to increase num gpus?

**Comment by shlens** [comment]
@yogeshg I don't have an immediate answer for why you are not able to run with num_gpu > 1 but in the mean time, the `slim` model library permits you to run inception on imagenet with multiple GPU's by using the `--num_clones`. Perhaps give this a shot in the mean time?
https://github.com/tensorflow/models/tree/master/slim/

**Comment by tfboyd** [comment]
I suggest using the slim version.  But here is a PR https://github.com/tensorflow/models/pull/1150 that upgrades this code to TF 1.0.  I tested locally on a GTX 1080 and it seems to work correctly now.
