### ISSUE TITLE
[deeplab] cityscapes  error:data split name val not recognized

### ISSUE THREAD

**Issue by sorrowyn** [tensorflow/models#8458]
when i try eval
python deeplab/eval.py \
    --logtostderr \
    --eval_split="val" \
    --model_variant="xception_65" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --eval_crop_size=1025 \
	--eval_crop_size=2049 \
    --dataset="cityscapes" \
    --checkpoint_dir="/data/mll/models/research/deeplab/datasets/cityscapes/exp/train_on_train_set/train" \
    --eval_logdir="/data/mll/models/research/deeplab/datasets/cityscapes/exp/train_on_train_set/val" \
    --dataset_dir="/data/mll/models/research/deeplab/datasets/cityscapes/tfrecord" \

error:
Traceback (most recent call last):
  File "deeplab/eval.py", line 227, in <module>
    tf.app.run()
  File "/home/mll/anaconda3/envs/tensor/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mll/anaconda3/envs/tensor/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/mll/anaconda3/envs/tensor/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "deeplab/eval.py", line 106, in main
    should_repeat=False)
  File "/data/mll/models/research/deeplab/datasets/data_generator.py", line 171, in __init__
    raise ValueError('data split name %s not recognized' % split_name)
ValueError: data split name val not recognized

**Comment by aquariusjay** [comment]
Try
--eval_split="val_fine"

https://github.com/tensorflow/models/blob/master/research/deeplab/datasets/data_generator.py#L76

**Comment by aquariusjay** [comment]
Closing the issue.
If there is any other issue, please feel free to re-open it or create a new one.

Cheers,
