### ISSUE TITLE
Object Detection with Multi GPU training result cannot be inference. Gives error 'Not found: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint'

### ISSUE THREAD

**Issue by donald2016** [tensorflow/models#8481]
System information

    What is the top-level directory of the model you are using: models/research
    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
    TensorFlow installed from (source or binary): Source
    TensorFlow version (use command below): 1.14.0 gpu
    Bazel version (if compiling from source): 
    CUDA/cuDNN version: Cuda compilation tools, release 10.0, V10.0.130/ CUDNN_MAJOR 7
    GPU model and memory: NVIDIA geforce rtx 2080 super X2
    Exact command to reproduce:
  CUDA_VISIBLE_DEVICES=0,1 python train.py --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_quantized_300x300_coco.config --num_clones=2 --ps_tasks=1
  python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_mobilenet_v2_quantized_300x300_coco.config --trained_checkpoint_prefix training/model.ckpt-100 --output_directory inference_graph

Describe the problem

I have follow this [link](https://medium.com/@teyou21/training-your-object-detection-model-on-tensorflow-part-2-e9e12714bdf) to produce my own object detection. I have successfully completed it with single GPU and I am moving on to use multi GPU.

According to @laksgreen from issue [6611](https://github.com/tensorflow/models/issues/6611) I have added  --num_clones=2 --ps_tasks=1 and increased my batch size to 20. And I have completed the training.

However, when I followed the same process to produce the inference graph, it was failed with the following error
`
INFO:tensorflow:Restoring parameters from training/model.ckpt-100
I0508 08:01:35.480847 140518557398784 saver.py:1280] Restoring parameters from training/model.ckpt-100
2020-05-08 08:01:36.478474: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/docker/models/research/object_detection/exporter.py:341) ]]

Original stack trace for 'save/RestoreV2':
  File "export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/docker/models/research/object_detection/exporter.py", line 510, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/docker/models/research/object_detection/exporter.py", line 439, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/home/docker/models/research/object_detection/exporter.py", line 341, in write_graph_and_checkpoint
    tf.import_graph_def(inference_graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3641, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1296, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1614, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 678, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/docker/models/research/object_detection/exporter.py", line 510, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/docker/models/research/object_detection/exporter.py", line 439, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/home/docker/models/research/object_detection/exporter.py", line 345, in write_graph_and_checkpoint
    saver.restore(sess, trained_checkpoint_prefix)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/docker/models/research/object_detection/exporter.py:341) ]]

Original stack trace for 'save/RestoreV2':
  File "export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/docker/models/research/object_detection/exporter.py", line 510, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/docker/models/research/object_detection/exporter.py", line 439, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/home/docker/models/research/object_detection/exporter.py", line 341, in write_graph_and_checkpoint
    tf.import_graph_def(inference_graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3641, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
`

I have searched for some information about
Not found: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint
in this issue [1783](https://github.com/tensorflow/models/issues/4783) @roadcode has mentioned the check point node name problem, but I do not know how to rewrite the node name.

**Comment by roadcode** [comment]
@donald2016 may this  [code](https://gist.github.com/batzner/7c24802dd9c5e15870b4b56e22135c96) can help you

**Comment by donald2016** [comment]
> @donald2016 may this [code](https://gist.github.com/batzner/7c24802dd9c5e15870b4b56e22135c96) can help you

Thank you roadcode
The renaming code works on renaming one node; however, I have a lot of nodes have the same problem. I will try to rename all of them.

**Comment by donald2016** [comment]
an update to this problem
I used roadcode's code to rename all the tensor name started with clone_0 and clone_1 by removing clone_0 and clone_1, respectively.
Then the eval.py and export_inference_graph.py are able to run successfully. The result shown in tensorboard also normal (compare with using single GPU)

Thank you ver much

**Comment by PrithviKambhampati** [comment]
Hi @donald2016, I am facing a similar problem to this. I used 6 GPUs to train my model. I tried roadcode's script but it did not remove all the clone_* (clone_0 to clone_5). Could you share how you renamed all the tensor names starting with clone_*?

**Comment by donald2016** [comment]
> Hi @donald2016, I am facing a similar problem to this. I used 6 GPUs to train my model. I tried roadcode's script but it did not remove all the clone_* (clone_0 to clone_5). Could you share how you renamed all the tensor names starting with clone_*?

`import sys, getopt

import tensorflow as tf

usage_str = 'python tensorflow_rename_variables.py --checkpoint_dir=path/to/dir/ ' \
            '--replace_from=substr --replace_to=substr --add_prefix=abc --dry_run'


def rename(checkpoint_dir, replace_from, replace_to, add_prefix, dry_run):
    checkpoint = tf.train.get_checkpoint_state(checkpoint_dir)
    with tf.Session() as sess:
        for var_name, _ in tf.contrib.framework.list_variables(checkpoint_dir):
            # Load the variable
            var = tf.contrib.framework.load_variable(checkpoint_dir, var_name)

            # Set the new name
            new_name = var_name
            if None not in [replace_from, replace_to]:
                new_name = new_name.replace(replace_from, replace_to)
            if add_prefix:
                new_name = add_prefix + new_name

            if dry_run:
                print('%s would be renamed to %s.' % (var_name, new_name))
            else:
                print('Renaming %s to %s.' % (var_name, new_name))
                # Rename the variable
                var = tf.Variable(var, name=new_name)

        if not dry_run:
            # Save the variables
            saver = tf.train.Saver()
            sess.run(tf.global_variables_initializer())
            saver.save(sess, checkpoint.model_checkpoint_path)


def main(argv):
    checkpoint_dir = None
    replace_from = None
    replace_to = None
    add_prefix = None
    dry_run = False

    try:
        opts, args = getopt.getopt(argv, 'h', ['help=', 'checkpoint_dir=', 'replace_from=',
                                               'replace_to=', 'add_prefix=', 'dry_run'])
    except getopt.GetoptError:
        print(usage_str)
        sys.exit(2)
    for opt, arg in opts:
        if opt in ('-h', '--help'):
            print(usage_str)
            sys.exit()
        elif opt == '--checkpoint_dir':
            checkpoint_dir = arg
        elif opt == '--replace_from':
            replace_from = arg
        elif opt == '--replace_to':
            replace_to = arg
        elif opt == '--add_prefix':
            add_prefix = arg
        elif opt == '--dry_run':
            dry_run = True

    if not checkpoint_dir:
        print('Please specify a checkpoint_dir. Usage:')
        print(usage_str)
        sys.exit(2)

    rename(checkpoint_dir, replace_from, replace_to, add_prefix, dry_run)


if __name__ == '__main__':
    main(sys.argv[1:])`

try this
but remember this is a one way modification
if you want to continue the training, remember backup your training files

**Comment by kunalgoyal9** [comment]
@donald2016 Hey I got a similar error When I trained `ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03`.  
But for me the number of gpus is 1 only. Also when I printed `var_name` in both checkpoints i.e. trained by me and pretrained.

**Pretrained:**  
![image](https://user-images.githubusercontent.com/21281457/85190135-ebf80e00-b2d2-11ea-85a9-8f9ec8d16408.png)

**Trained using transfer learning**
![image](https://user-images.githubusercontent.com/21281457/85190160-2a8dc880-b2d3-11ea-957e-4c1049b82a75.png)u
Seems like quantization nodes are missing in later one. Can you help me?

**Comment by csingh27** [comment]
python -c "import numpy; print(numpy.version.version)"

**Comment by parameswar-ds** [comment]
> System information
> 
> What is the top-level directory of the model you are using: models/research
> Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
> OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
> TensorFlow installed from (source or binary): Source
> TensorFlow version (use command below): 1.14.0 gpu
> Bazel version (if compiling from source):
> CUDA/cuDNN version: Cuda compilation tools, release 10.0, V10.0.130/ CUDNN_MAJOR 7
> GPU model and memory: NVIDIA geforce rtx 2080 super X2
> Exact command to reproduce:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1 python train.py --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_quantized_300x300_coco.config --num_clones=2 --ps_tasks=1
> python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_mobilenet_v2_quantized_300x300_coco.config --trained_checkpoint_prefix training/model.ckpt-100 --output_directory inference_graph
> ```
> 
> Describe the problem
> 
> I have followed this [link](https://medium.com/@teyou21/training-your-object-detection-model-on-tensorflow-part-2-e9e12714bdf) to produce my own object detection. I have successfully completed it with single GPU and I am moving on to use multi GPU.
> 
> According to @laksgreen from issue [6611](https://github.com/tensorflow/models/issues/6611) I have added --num_clones=2 --ps_tasks=1 and increased my batch size to 20. And I have completed the training.
> 
> However, when I followed the same process to produce the inference graph, it was failed with the following error
> 
> > `INFO:tensorflow:Restoring parameters from training/model.ckpt-100 I0508 08:01:35.480847 140518557398784 saver.py:1280] Restoring parameters from training/model.ckpt-100 2020-05-08 08:01:36.478474: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint Traceback (most recent call last):   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call     return fn(*args)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn     options, feed_dict, fetch_list, target_list, run_metadata)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun     run_metadata) tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint 	 [[{{node save/RestoreV2}}]] During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1286, in restore     {self.saver_def.filename_tensor_name: save_path})   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 950, in run     run_metadata_ptr)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1173, in _run     feed_dict_tensor, options, run_metadata)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run     run_metadata)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call     raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint 	 [[node save/RestoreV2 (defined at /home/docker/models/research/object_detection/exporter.py:341) ]] Original stack trace for 'save/RestoreV2':   File "export_inference_graph.py", line 162, in <module>     tf.app.run()   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run     _run_main(main, args)   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main     sys.exit(main(argv))   File "export_inference_graph.py", line 158, in main     write_inference_graph=FLAGS.write_inference_graph)   File "/home/docker/models/research/object_detection/exporter.py", line 510, in export_inference_graph     write_inference_graph=write_inference_graph)   File "/home/docker/models/research/object_detection/exporter.py", line 439, in _export_inference_graph     trained_checkpoint_prefix=checkpoint_to_use)   File "/home/docker/models/research/object_detection/exporter.py", line 341, in write_graph_and_checkpoint     tf.import_graph_def(inference_graph_def, name='')   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func     return func(*args, **kwargs)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def     _ProcessNewOps(graph)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps     for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in _add_new_tf_operations     for c_op in c_api_util.new_tf_operations(self)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in <listcomp>     for c_op in c_api_util.new_tf_operations(self)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3641, in _create_op_from_tf_operation     ret = Operation(c_op, self)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__     self._traceback = tf_stack.extract_stack() During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1296, in restore     names_to_keys = object_graph_key_mapping(save_path)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1614, in object_graph_key_mapping     object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 678, in get_tensor     return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str)) tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "export_inference_graph.py", line 162, in <module>     tf.app.run()   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run     _run_main(main, args)   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main     sys.exit(main(argv))   File "export_inference_graph.py", line 158, in main     write_inference_graph=FLAGS.write_inference_graph)   File "/home/docker/models/research/object_detection/exporter.py", line 510, in export_inference_graph     write_inference_graph=write_inference_graph)   File "/home/docker/models/research/object_detection/exporter.py", line 439, in _export_inference_graph     trained_checkpoint_prefix=checkpoint_to_use)   File "/home/docker/models/research/object_detection/exporter.py", line 345, in write_graph_and_checkpoint     saver.restore(sess, trained_checkpoint_prefix)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1302, in restore     err, "a Variable name or other graph key that is missing") tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint 	 [[node save/RestoreV2 (defined at /home/docker/models/research/object_detection/exporter.py:341) ]] Original stack trace for 'save/RestoreV2':   File "export_inference_graph.py", line 162, in <module>     tf.app.run()   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run     _run_main(main, args)   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main     sys.exit(main(argv))   File "export_inference_graph.py", line 158, in main     write_inference_graph=FLAGS.write_inference_graph)   File "/home/docker/models/research/object_detection/exporter.py", line 510, in export_inference_graph     write_inference_graph=write_inference_graph)   File "/home/docker/models/research/object_detection/exporter.py", line 439, in _export_inference_graph     trained_checkpoint_prefix=checkpoint_to_use)   File "/home/docker/models/research/object_detection/exporter.py", line 341, in write_graph_and_checkpoint     tf.import_graph_def(inference_graph_def, name='')   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func     return func(*args, **kwargs)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def     _ProcessNewOps(graph)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps     for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in _add_new_tf_operations     for c_op in c_api_util.new_tf_operations(self)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3751, in <listcomp>     for c_op in c_api_util.new_tf_operations(self)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3641, in _create_op_from_tf_operation     ret = Operation(c_op, self)   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__     self._traceback = tf_stack.extract_stack()`
> 
> It looks like the key cannot found in checkpoint.
> I have searched for some information about
> Not found: Key BoxPredictor_0/BoxEncodingPredictor/act_quant/max not found in checkpoint
> in this issue [1783](https://github.com/tensorflow/models/issues/4783) @roadcode has mentioned the check point node name problem. When training with multi GPU, there I found that there are some node name started with clone_0 and clone_1, but I do not know how to rewrite the node name. Is it correct to rename the nodes?

plz add following lines in config files at end:
graph_rewriter {
  quantization {
    delay: 48000
    weight_bits: 8
    activation_bits: 8
  }
}

these represent quantization aware training in ssd models. then it can automatically set those min max values in graph while training.
