### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.   (0) Failed precondition:  data/training; Is a directory

### ISSUE THREAD

**Issue by paulrich1234** [tensorflow/models#8488]
running     on tensorflow-gpu=2.2.0  

!python3 transformer_main.py --data_dir=data \
    --model_dir=model\
    --vocab_file=data/vocab.ende.32768 \
    --param_set=big \
    --train_steps=100000 \
    --steps_between_evals=5000\
    --batch_size=4096 --max_length=64 \
    --bleu_source=data/newstest2014.en \
    --bleu_ref=data/newstest2014.de \
    --num_gpus=2 \
    --enable_time_history=false

the following error occors

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0511 16:00:08.782238 140326923654976 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0511 16:00:08.783418 140326923654976 transformer_main.py:186] Running transformer with num_gpus = 2
I0511 16:00:08.784826 140326923654976 transformer_main.py:190] For training, using distribution strategy: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x7fa0207a48d0>
Model: "model"

Total params: 210,804,736
Trainable params: 210,804,736
Non-trainable params: 0
__________________________________________________________________________________________________
I0511 16:00:16.170870 140326923654976 transformer_main.py:312] Start train iteration at global step:0
INFO:tensorflow:batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
I0511 16:00:23.557520 140326923654976 cross_device_ops.py:697] batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0511 16:00:26.764555 140326923654976 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0511 16:00:26.767467 140326923654976 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
I0511 16:00:36.671541 140326923654976 cross_device_ops.py:697] batch_all_reduce: 185 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0511 16:00:38.748556 140326923654976 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0511 16:00:38.750910 140326923654976 cross_device_ops.py:439] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
Traceback (most recent call last):
  File "transformer_main.py", line 509, in <module>
    app.run(main)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 497, in main
    task.train()
  File "transformer_main.py", line 364, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 72, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 907, in fit
    tmp_logs = train_function(iterator)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 766, in __call__
    result = self._call(*args, **kwds)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 826, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2812, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1838, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1915, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 549, in call
    ctx=ctx)
  File "/home/dell/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition:  data/training; Is a directory
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional_1]]
  (1) Cancelled:  Function was cancelled before it was started
0 successful operations.
1 derived errors ignored. [Op:__inference_train_function_45467]

Function call stack:
train_function -> train_function

**Comment by goneofwind** [comment]
hello，do you solve this problem?  can you share it, thanks!
