### ISSUE TITLE
deeplabv3+

### ISSUE THREAD

**Issue by songguoqing-coder** [tensorflow/models#8506]
Applying the mobilenetv3 pre-trained model to deeplabv3 + ：
python3 train.py 
   --logtostderr 
   --train_split="trainval" 
   --model_variant="mobilenet_v3_small_seg" 
   --train_crop_size='513,513' 
   --train_batch_size=1 
   --training_number_of_steps=10000 
   --fine_tune_batch_norm=False --tf_initial_checkpoint="/home/song/models-master/research/deeplab/backbone/deeplab_mnv3_small_cityscapes_trainfine/model.ckpt" 
   --train_logdir="/home/song/models-master/research/deeplab/train" 
   --dataset_dir="/home/song/dataset/tfrecord"
 
    the following error occurs:
Traceback (most recent call last):
  File "/home/song/aayuyifenge/models-master/research/deeplab/train.py", line 464, in <module>
    tf.app.run()
  File "/home/song/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/song/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/song/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/song/aayuyifenge/models-master/research/deeplab/train.py", line 444, in main
    ignore_missing_vars=True)
  File "/home/song/aayuyifenge/models-master/research/deeplab/utils/train_utils.py", line 221, in get_model_init_fn
    ignore_missing_vars=ignore_missing_vars)
  File "/home/song/.local/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 694, in assign_from_checkpoint
    (ckpt_name, str(ckpt_value.shape), str(var.get_shape())))
ValueError: Total size of new array must be unchanged for image_pooling/weights lh_shape: [(1, 1, 288, 128)], rh_shape: [(1, 1, 288, 256)]
Can anyone help me solve this problem? thank you very much!

**Comment by rinley** [comment]
https://github.com/tensorflow/models/blob/master/research/deeplab/core/feature_extractor.py#L211-L218

This is the cause of the Error.

You are using a MobileNetV3 checkpoint for classification, which does not do this reduction. I believe if you comment out these lines, you would be able to load the model checkpoint. (untested)

**Comment by songguoqing-coder** [comment]
Still the same problem.
ValueError: Total size of new array must be unchanged for image_pooling/weights lh_shape: [(1, 1, 288, 128)], rh_shape: [(1, 1, 288, 256)]

**Comment by songguoqing-coder** [comment]
> Still the same problem，I do not know why.
> ValueError: Total size of new array must be unchanged for image_pooling/weights lh_shape: [(1, 1, 288, 128)], rh_shape: [(1, 1, 288, 256)]
