### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnimplementedError: /content/drive/My; Operation not supported

### ISSUE THREAD

**Issue by xueqing311** [tensorflow/models#8513]
Coding I used to exports the model specifed and inference graph:

!python /content/export_inference_graph.py \
    --input_type=image_tensor \
    --pipeline_config_path=/content/ssd_mobilenet_v2_coco.config \
    --output_directory={output_directory} \
    --trained_checkpoint_prefix={last_model_path}

Error I faced:

Traceback (most recent call last):
  File "/content/export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/content/drive/My Drive/object_detection/models/research/object_detection/exporter.py", line 510, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/content/drive/My Drive/object_detection/models/research/object_detection/exporter.py", line 402, in _export_inference_graph
    tf.gfile.MakeDirs(output_directory)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.UnimplementedError: /content/drive/My; Operation not supported
After I trained the model and run the TensorBoard, then I need to export the graph. However, I faced this error, can someone tell me what happened to my coding? thanks in advanced, I am a new in this field.

**Comment by chunduriv** [comment]
@xueqing311,

Try to quote the path in double quotes (i.e.  "/content/drive/My"). Otherwise the path will be accepted as separate paths since there is a space in between. Thank you.
