### ISSUE TITLE
A Problem when running train_cifar.py

### ISSUE THREAD

**Issue by ouisyasser** [tensorflow/models#8518]
Traceback (most recent call last):
  File "train_cifar.py", line 452, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python2.7/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train_cifar.py", line 447, in main
    cifar_trainer = CifarModelTrainer(hparams)
  File "train_cifar.py", line 225, in __init__
    self.data_loader = data_utils.DataSet(hparams)
  File "/content/models/research/autoaugment/data_utils.py", line 85, in __init__
    d = unpickle(os.path.join(hparams.data_path, f))
  File "/content/models/research/autoaugment/data_utils.py", line 182, in unpickle
    d = cPickle.load(fo)
EOFError

**Comment by vidursatija** [comment]
Hi ouisyasser! Can you show us the code where you load the file? I think this is happening because your directory structure isn't what is required for training on the CIFAR dataset.

**Comment by ouisyasser** [comment]
Yes sure! Thank you for responding me.

https://colab.research.google.com/drive/1sFwKBam6LrYmNJoHIDw3HSFQ4fVR_QDW

This is the file and how I execute it. Im working on a project and I need
your classifier.

Le mer. 20 mai 2020 à 4:22 AM, Vidur Satija <notifications@github.com> a
écrit :
