### ISSUE TITLE
AttributeError: change_coordinate_frame 

### ISSUE THREAD

**Issue by alexdwu13** [tensorflow/models#8559]
## The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/model_main.py

## Describe the bug

When running `model_main.py` after pulling the latest from master, I'm getting the error: `AttributeError: change_coordinate_frame` from `https://github.com/tensorflow/models/tree/master/research/model_lib.py`:

```
WARNING: Logging before flag parsing goes to stderr.
W0522 01:48:09.645347 140098740733760 deprecation_wrapper.py:119] From /tf/models/research/object_detection/model_main.py:111: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0522 01:48:09.647595 140098740733760 deprecation_wrapper.py:119] From /tf/models/research/object_detection/utils/config_util.py:137: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0522 01:48:09.653165 140098740733760 deprecation_wrapper.py:119] From /tf/models/research/object_detection/model_lib.py:685: The name tf.logging.warning is deprecated. Please use tf.compat.v1.logging.warning instead.

W0522 01:48:09.653301 140098740733760 model_lib.py:686] Forced number of epochs for all eval validations to be 1.
W0522 01:48:09.653435 140098740733760 deprecation_wrapper.py:119] From /tf/models/research/object_detection/utils/config_util.py:523: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

I0522 01:48:09.653532 140098740733760 config_util.py:523] Maybe overwriting train_steps: None
I0522 01:48:09.653616 140098740733760 config_util.py:523] Maybe overwriting use_bfloat16: False
I0522 01:48:09.653701 140098740733760 config_util.py:523] Maybe overwriting sample_1_of_n_eval_examples: 1
I0522 01:48:09.653797 140098740733760 config_util.py:523] Maybe overwriting eval_num_epochs: 1
I0522 01:48:09.653898 140098740733760 config_util.py:523] Maybe overwriting load_pretrained: True
I0522 01:48:09.653985 140098740733760 config_util.py:533] Ignoring config override key: load_pretrained
W0522 01:48:09.654740 140098740733760 model_lib.py:702] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
I0522 01:48:09.654871 140098740733760 model_lib.py:737] create_estimator_and_inputs: use_tpu False, export_to_tpu False
I0522 01:48:09.655415 140098740733760 estimator.py:209] Using config: {'_model_dir': 'v2_fpn-dwise_BOX_AR1.0__AUG_0.15-1.0//train', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6b10801f60>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
W0522 01:48:09.655672 140098740733760 model_fn.py:630] Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f6b0de8d488>) includes params argument, but params are not passed to Estimator.
I0522 01:48:09.656445 140098740733760 estimator_training.py:186] Not using Distribute Coordinator.
I0522 01:48:09.656667 140098740733760 training.py:612] Running training and evaluation locally (non-distributed).
I0522 01:48:09.656970 140098740733760 training.py:700] Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
W0522 01:48:09.668902 140098740733760 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Traceback (most recent call last):
  File "/tf/models/research/object_detection/model_main.py", line 111, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tf/models/research/object_detection/model_main.py", line 107, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1185, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1022, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1113, in _call_input_fn
    return input_fn(**kwargs)
  File "/tf/models/research/object_detection/inputs.py", line 645, in _train_input_fn
    params=params)
  File "/tf/models/research/object_detection/inputs.py", line 720, in train_input
    model_config, is_training=True).preprocess
  File "/tf/models/research/object_detection/builders/model_builder.py", line 905, in build
    add_summaries)
  File "/tf/models/research/object_detection/builders/model_builder.py", line 340, in _build_ssd_model
    ssd_config.post_processing)
  File "/tf/models/research/object_detection/builders/post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "/tf/models/research/object_detection/builders/post_processing_builder.py", line 105, in _build_non_max_suppressor
    change_coordinate_frame=nms_config.change_coordinate_frame)
AttributeError: change_coordinate_frame
```

## Steps to reproduce

`python models/tree/master/research/model_main.py`

## System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14
- Python version: 3.6.8

**Comment by alexdwu13** [comment]
I compiled the latest protobufs and the issue was fixed!
