### ISSUE TITLE
Cant export frozen inference graph ValueError: The passed save_path is not a valid checkpoint: training/model.ckpt-4347

### ISSUE THREAD

**Issue by bloodgreed99** [tensorflow/models#8566]
Whenever I try to export the frozen inference graph it produces an error "ValueError: The passed save_path is not a valid checkpoint: training/model.ckpt-4347" even though I am currently in object detection directory and there is a training folder which contains model.ckpt.4347

Logs

Traceback (most recent call last):
  File "export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "C:\Users\Rahul\Anaconda3\envs\tf1.13.1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "D:\ExtraWork\models\research\object_detection\exporter.py", line 489, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "D:\ExtraWork\models\research\object_detection\exporter.py", line 418, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "D:\ExtraWork\models\research\object_detection\exporter.py", line 327, in write_graph_and_checkpoint
    saver.restore(sess, trained_checkpoint_prefix)
  File "C:\Users\Rahul\Anaconda3\envs\tf1.13.1\lib\site-packages\tensorflow\python\training\saver.py", line 1268, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: training/model.ckpt-4347.

6. System information

- OS Platform :windows10
- TensorFlow version 1.13.1
- Python version 3.7
-Both my cuda and cudann are compatible with TensorFlow
- GPU model and memory: GTX 1050 4gb

![Screenshot (97)](https://user-images.githubusercontent.com/38246396/82751010-ea215480-9dd1-11ea-867e-ced490c6f5bf.png)

**Comment by bloodgreed99** [comment]
Sorry it was my mistake, I have several models in my PC and i was pasting the checkpoint number of a different model which does not exist in my current model. mY bad

**Comment by bilibilikanpei** [comment]
this is my first time generate model, i met a same question. how do you fix this?
