### ISSUE TITLE
official nlp transformer tutorial doesn't work InvalidArgumentError:  indices[85,26] = 33764 is not in [0, 33708)

### ISSUE THREAD

**Issue by vikramambrose** [tensorflow/models#8579]
Following the walkthrough on this page https://github.com/tensorflow/models/tree/master/official/nlp/transformer

```
$ git rev-parse HEAD
a0d4ac797592f59c74f69d73706c7acf2aedf321
$ pip list | grep tf
tf-estimator-nightly          2.3.0.dev2020052701
tf-nightly                    2.3.0.dev20200527
```

```
python3 transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET \
    --train_steps=100000 --steps_between_evals=5000 \
    --batch_size=4096 --max_length=64 \
    --bleu_source=$DATA_DIR/newstest2014.en \
    --bleu_ref=$DATA_DIR/newstest2014.de \
    --num_gpus=1 \
    --enable_time_history=false
```

```
2020-05-27 14:07:32.416002: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-05-27 14:07:32.435006: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd1b0931be0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-27 14:07:32.435025: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0527 14:07:32.435575 4631133632 cross_device_ops.py:1187] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0527 14:07:32.435838 4631133632 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0527 14:07:32.436186 4631133632 transformer_main.py:172] Running transformer with num_gpus = 0
I0527 14:07:32.436355 4631133632 transformer_main.py:176] For training, using distribution strategy: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x148601b50>

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
inputs (InputLayer)             [(None, None)]       0                                            
__________________________________________________________________________________________________
targets (InputLayer)            [(None, None)]       0                                            
__________________________________________________________________________________________________
transformer_v2 (Transformer)    (None, None, 33708)  210804736   inputs[0][0]                     
                                                                 targets[0][0]                    
__________________________________________________________________________________________________
logits (Lambda)                 (None, None, 33708)  0           transformer_v2[0][0]             
__________________________________________________________________________________________________
tf_op_layer_Shape (TensorFlowOp [(3,)]               0           logits[0][0]                     
__________________________________________________________________________________________________
tf_op_layer_Shape_1 (TensorFlow [(2,)]               0           targets[0][0]                    
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens [()]                 0           tf_op_layer_Shape[0][0]          
__________________________________________________________________________________________________
tf_op_layer_strided_slice_1 (Te [()]                 0           tf_op_layer_Shape_1[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Maximum (TensorFlow [()]                 0           tf_op_layer_strided_slice[0][0]  
                                                                 tf_op_layer_strided_slice_1[0][0]
__________________________________________________________________________________________________
tf_op_layer_Sub_1 (TensorFlowOp [()]                 0           tf_op_layer_Maximum[0][0]        
                                                                 tf_op_layer_strided_slice_1[0][0]
__________________________________________________________________________________________________
tf_op_layer_Pad_1/paddings/1 (T [(2,)]               0           tf_op_layer_Sub_1[0][0]          
__________________________________________________________________________________________________
tf_op_layer_Sub (TensorFlowOpLa [()]                 0           tf_op_layer_Maximum[0][0]        
                                                                 tf_op_layer_strided_slice[0][0]  
__________________________________________________________________________________________________
tf_op_layer_Pad_1/paddings (Ten [(2, 2)]             0           tf_op_layer_Pad_1/paddings/1[0][0
__________________________________________________________________________________________________
tf_op_layer_Pad/paddings/1 (Ten [(2,)]               0           tf_op_layer_Sub[0][0]            
__________________________________________________________________________________________________
tf_op_layer_Pad_1 (TensorFlowOp [(None, None)]       0           targets[0][0]                    
                                                                 tf_op_layer_Pad_1/paddings[0][0] 
__________________________________________________________________________________________________
tf_op_layer_Pad/paddings (Tenso [(3, 2)]             0           tf_op_layer_Pad/paddings/1[0][0] 
__________________________________________________________________________________________________
tf_op_layer_Cast (TensorFlowOpL [(None, None)]       0           tf_op_layer_Pad_1[0][0]          
__________________________________________________________________________________________________
tf_op_layer_Pad (TensorFlowOpLa [(None, None, None)] 0           logits[0][0]                     
                                                                 tf_op_layer_Pad/paddings[0][0]   
__________________________________________________________________________________________________
tf_op_layer_OneHot (TensorFlowO [(None, None, 33708) 0           tf_op_layer_Cast[0][0]           
__________________________________________________________________________________________________
tf_op_layer_Shape_3 (TensorFlow [(3,)]               0           tf_op_layer_Pad[0][0]            
__________________________________________________________________________________________________
tf_op_layer_Shape_4 (TensorFlow [(3,)]               0           tf_op_layer_OneHot[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Slice (TensorFlowOp [(1,)]               0           tf_op_layer_Shape_3[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Slice_1 (TensorFlow [(1,)]               0           tf_op_layer_Shape_4[0][0]        
__________________________________________________________________________________________________
tf_op_layer_concat (TensorFlowO [(2,)]               0           tf_op_layer_Slice[0][0]          
__________________________________________________________________________________________________
tf_op_layer_concat_1 (TensorFlo [(2,)]               0           tf_op_layer_Slice_1[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Reshape (TensorFlow [(None, None)]       0           tf_op_layer_Pad[0][0]            
                                                                 tf_op_layer_concat[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Reshape_1 (TensorFl [(None, None)]       0           tf_op_layer_OneHot[0][0]         
                                                                 tf_op_layer_concat_1[0][0]       
__________________________________________________________________________________________________
tf_op_layer_Shape_2 (TensorFlow [(3,)]               0           tf_op_layer_Pad[0][0]            
__________________________________________________________________________________________________
tf_op_layer_SoftmaxCrossEntropy [(None,), (None, Non 0           tf_op_layer_Reshape[0][0]        
                                                                 tf_op_layer_Reshape_1[0][0]      
__________________________________________________________________________________________________
tf_op_layer_Slice_2 (TensorFlow [(2,)]               0           tf_op_layer_Shape_2[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Reshape_2 (TensorFl [(None, None)]       0           tf_op_layer_SoftmaxCrossEntropyWi
                                                                 tf_op_layer_Slice_2[0][0]        
__________________________________________________________________________________________________
tf_op_layer_NotEqual (TensorFlo [(None, None)]       0           tf_op_layer_Pad_1[0][0]          
__________________________________________________________________________________________________
tf_op_layer_Sub_2 (TensorFlowOp [(None, None)]       0           tf_op_layer_Reshape_2[0][0]      
__________________________________________________________________________________________________
tf_op_layer_Cast_1 (TensorFlowO [(None, None)]       0           tf_op_layer_NotEqual[0][0]       
__________________________________________________________________________________________________
tf_op_layer_Mul (TensorFlowOpLa [(None, None)]       0           tf_op_layer_Sub_2[0][0]          
                                                                 tf_op_layer_Cast_1[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Sum (TensorFlowOpLa [()]                 0           tf_op_layer_Mul[0][0]            
__________________________________________________________________________________________________
tf_op_layer_Sum_1 (TensorFlowOp [()]                 0           tf_op_layer_Cast_1[0][0]         
__________________________________________________________________________________________________
tf_op_layer_RealDiv (TensorFlow [()]                 0           tf_op_layer_Sum[0][0]            
                                                                 tf_op_layer_Sum_1[0][0]          
__________________________________________________________________________________________________
add_loss (AddLoss)              ()                   0           tf_op_layer_RealDiv[0][0]        
==================================================================================================
Total params: 210,804,736
Trainable params: 210,804,736
Non-trainable params: 0
__________________________________________________________________________________________________
I0527 14:07:38.184003 4631133632 transformer_main.py:298] Start train iteration at global step:0


Traceback (most recent call last):
  File "transformer_main.py", line 496, in <module>
    app.run(main)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 484, in main
    task.train()
  File "transformer_main.py", line 350, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1090, in fit
    tmp_logs = train_function(iterator)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 766, in __call__
    result = self._call(*args, **kwds)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 826, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2811, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1838, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1914, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 549, in call
    ctx=ctx)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[85,26] = 33764 is not in [0, 33708)
	 [[node functional_1/transformer_v2/Transformer/decode/embedding_shared_weights/embedding/GatherV2 (defined at /Users/vikram/Workspace/tensorflow-models/official/nlp/transformer/embedding_layer.py:80) ]] [Op:__inference_train_function_22457]

Errors may have originated from an input operation.
Input Source operations connected to node functional_1/transformer_v2/Transformer/decode/embedding_shared_weights/embedding/GatherV2:
 cond_1/Identity_1 (defined at transformer_main.py:350)

Function call stack:
train_function
```

**Comment by saberkun** [comment]
@vikramambrose Hi, this is because the vocabulary size changed. As PY3 involve, we have seen the tokenization and char handling is changing.
In this case, you need to change the vocab_size:
https://github.com/tensorflow/models/blob/master/official/nlp/transformer/model_params.py#L25 from 33708 to XXX? the real vocab you generated.

**Comment by lehougoogle** [comment]
I started a job running with the default setting, dataset, and VOCAB_FILE on google's side. It is running fine so far.

**Comment by saberkun** [comment]
@lehougoogle the default setting is using vocab and dataset we generated one year ago.
Recently, we notified that download_data.py script yields a slightly different vocab.

**Comment by vikramambrose** [comment]
After correcting vocab_size in model_params.py it gets further (runs for a few minutes) but eventually errors out in a similar error.

```
$ grep vocab_size model_params.py 
    vocab_size=33923,  # Number of tokens defined in the vocabulary file.
```

```
__________________________________________________________________________________________________
I0528 10:54:48.488357 4671204800 transformer_main.py:298] Start train iteration at global step:0
  15/5000 [..............................] - ETA: 40:41:21 - loss: 9.7110Traceback (most recent call last):
  File "transformer_main.py", line 496, in <module>
    app.run(main)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 484, in main
    task.train()
  File "transformer_main.py", line 350, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1090, in fit
    tmp_logs = train_function(iterator)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 766, in __call__
    result = self._call(*args, **kwds)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 793, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2811, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1838, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1914, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 549, in call
    ctx=ctx)
  File "/Users/vikram/Workspace/tensorflow-models/venv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[69,42] = 33942 is not in [0, 33923)
	 [[node functional_1/transformer_v2/Transformer/encode/embedding_shared_weights/embedding/GatherV2 (defined at /Users/vikram/Workspace/tensorflow-models/official/nlp/transformer/embedding_layer.py:80) ]] [Op:__inference_train_function_22457]
```

**Comment by jaeyounkim** [comment]
@xinliupitt Can you check this issue?

**Comment by lehougoogle** [comment]
We need to check what changed in the data got by download_data.py.

**Comment by xinliupitt** [comment]
Hello @vikramambrose ! Could you also try to use CPU (by setting `--num_gpus=0`), and see how far the it goes?

What I experienced before is that, the code was fine by CPU, but received data reading errors by TPU. After correcting my TPU setting, the code was fine with TPU.
