### ISSUE TITLE
Inception: multiple GPU training error when restoring a pretrained mdoel

### ISSUE THREAD

**Issue by emqiongwu** [tensorflow/models#860]
I was trying to continue training by restoring a pretrained model of [inception](https://github.com/tensorflow/models/tree/master/inception). It runs fine when num_gpus=1. when I specifiy num_gpus=2, it gives out fowllowing error. Could anyone help explain why?

> 

```
Traceback (most recent call last):
  File "/home/qiong/Documents/inception_place/bazel-bin/inception/place_train.runfiles/inception/inception/place_train.py", line 29, in <module>
    tf.app.run()
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/qiong/Documents/inception_place/bazel-bin/inception/place_train.runfiles/inception/inception/place_train.py", line 25, in main
    inception_train.train(dataset)
  File "/home/qiong/Documents/inception_place/bazel-bin/inception/place_train.runfiles/inception/inception/inception_train.py", line 222, in train
    scope)
  File "/home/qiong/Documents/inception_place/bazel-bin/inception/place_train.runfiles/inception/inception/inception_train.py", line 107, in _tower_loss
    loss_averages_op = loss_averages.apply(losses + [total_loss])
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/qiong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable tower_1/tower_1/CrossEntropyLoss/value/avg/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

```

Other info:
```
python -c "import tensorflow; print(tensorflow.__version__)"
0.12.0

git rev-parse HEAD
1fbc3a59af7264b6b3b2fa35f6cdf217c0900513

bazel version
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392
```

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow).
