### ISSUE TITLE
Does clone_model work with Transformer?

### ISSUE THREAD

**Issue by srcarroll** [tensorflow/models#8612]
I am trying to use clone_model on the official Transformer model.  I get KeyError: 'layers'.  All code is from the tensorflow official models repo.  The only thing I have changed is adding the line

clone_model = tf.keras.models.clone_model(model)

in the train function in transformer_main.py after model has been compiled.  I've used clone_model on the MNIST model and ResNet with no problem.  Is there anything special about Transformer that clone_model doesn't work for, or am I missing something?  Thanks in advance.

Traceback (most recent call last):
  File "transformer_main.py", line 498, in <module>
    app.run(main)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 486, in main
    task.train()
  File "transformer_main.py", line 225, in train
    cloned_model = tf.keras.models.clone_model(model)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 435, in clone_model
    model, input_tensors=input_tensors, layer_fn=clone_function)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 201, in _clone_functional_model
    model, new_input_layers, layer_fn)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 254, in _clone_layers_and_model_config
    config = network.get_network_config(model, serialize_layer_fn=_copy_layer)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 2069, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 251, in _copy_layer
    created_layers[layer.name] = layer_fn(layer)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 61, in _clone_layer
    return layer.__class__.from_config(layer.get_config())
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 999, in from_config
    config, custom_objects)
  File "/home/Sam/testingenv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1994, in reconstruct_from_config
    for layer_data in config['layers']:
KeyError: 'layers'

**Comment by saberkun** [comment]
Hi, the transformer model is written with a fully subclass style which does not fully fullfill keras API. clone_model does not work. I think many components miss get/from configs.
As transformer decoding has a nature of dynamism, it is hard to write it as keras functional style.

**Comment by srcarroll** [comment]
Thank you for your reply.  Does this mean that it would be completely impossible to write a Transformer model that is compatible with clone_model?  I don't expect a detailed suggestion on how this can be done, but would like to know if it is even possible before spending a lot of time attempting to do it.  Thanks again
