### ISSUE TITLE
COCO-trained models for tf2,where can download?

### ISSUE THREAD

**Issue by xpdrycry** [tensorflow/models#8752]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the bug
python3 legacy/train.py --logtostderr --train_dir=voc --pipeline_config_path=voc_lib/faster_rcnn_resnet101_pets.config

ValueError: faster_rcnn_resnet101 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

## 3. Steps to reproduce

WARNING:tensorflow:From /home/c/.local/lib/python3.6/site-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W0630 14:38:04.062839 140272845739840 deprecation.py:323] From /home/c/.local/lib/python3.6/site-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "legacy/train.py", line 186, in <module>
    tf.app.run()
  File "/home/c/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/c/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/c/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/c/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/legacy/trainer.py", line 248, in train
    detection_model = create_model_fn()
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 950, in build
    add_summaries)
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 510, in _build_faster_rcnn_model
    _check_feature_extractor_exists(frcnn_config.feature_extractor.type)
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 208, in _check_feature_extractor_exists
    'Tensorflow'.format(feature_extractor_type))

## 6. System information

>>> import tensorflow as tf
>>> print(tf.version.GIT_VERSION, tf.version.VERSION)
v2.2.0-rc4-8-g2b96f3662b 2.2.0

##according to model_builder.py, where is pretraining model for tf2?

**Comment by jch1** [comment]
We currently only support TF1 in the Object Detection API --- so this is why things are breaking if you try to use the models with a TF2 installation.  But we plan to make TF2 models available very soon (in the next couple of weeks), so please stay tuned.

**Comment by pkulzc** [comment]
We just released Object Detection API for TF2. Please see our updated [doc](https://github.com/tensorflow/models/tree/master/research/object_detection). Please note that for TF2 training,  train.py is no longer supported.
