### ISSUE TITLE
faster_rcnn_resnet101 is not supported.

### ISSUE THREAD

**Issue by AshishGusain17** [tensorflow/models#8763]
# Prerequisites

Tensorflow version I am using is 1.15.2
Using google colab

When I started training, by the command
` !python3 train.py --logtostderr --train_dir=../training --pipeline_config_path=../training/faster_rcnn_resnet101_coco.config`

Got error
`Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/models/research/object_detection/legacy/trainer.py", line 248, in train
    detection_model = create_model_fn()
  File "/content/models/research/object_detection/builders/model_builder.py", line 957, in build
    add_summaries)
  File "/content/models/research/object_detection/builders/model_builder.py", line 517, in _build_faster_rcnn_model
    _check_feature_extractor_exists(frcnn_config.feature_extractor.type)
  File "/content/models/research/object_detection/builders/model_builder.py", line 215, in _check_feature_extractor_exists
    'Tensorflow'.format(feature_extractor_type))
ValueError: faster_rcnn_resnet101 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow`

I tried different models than and getting the same error again and again.

**Comment by ashiqak** [comment]
same issue 
python3 train.py --logtostderr --train_dir='object_detection/training/' --pipeline_config_path='object_detection/training/faster_rcnn_resnet101_pets.config'
WARNING:tensorflow:From /home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W0707 07:44:50.830823 139935229212480 deprecation.py:323] From /home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/legacy/trainer.py", line 248, in train
    detection_model = create_model_fn()
  File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/builders/model_builder.py", line 957, in build
    add_summaries)
  File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/builders/model_builder.py", line 517, in _build_faster_rcnn_model
    _check_feature_extractor_exists(frcnn_config.feature_extractor.type)
  File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/builders/model_builder.py", line 215, in _check_feature_extractor_exists
    'Tensorflow'.format(feature_extractor_type))
ValueError: faster_rcnn_resnet101 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

**Comment by AshishGusain17** [comment]
> **same issue**
> python3 train.py --logtostderr --train_dir='object_detection/training/' --pipeline_config_path='object_detection/training/faster_rcnn_resnet101_pets.config'
> WARNING:tensorflow:From /home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py:250: main (from **main**) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use object_detection/model_main.py.
> W0707 07:44:50.830823 139935229212480 deprecation.py:323] From /home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py:250: main (from **main**) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use object_detection/model_main.py.
> Traceback (most recent call last):
> File "train.py", line 186, in
> tf.app.run()
> File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py", line 299, in run
> _run_main(main, args)
> File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
> sys.exit(main(argv))
> File "/home/nec2/anaconda3/envs/fasterrcnn/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
> return func(*args, **kwargs)
> File "train.py", line 182, in main
> graph_hook_fn=graph_rewriter_fn)
> File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/legacy/trainer.py", line 248, in train
> detection_model = create_model_fn()
> File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/builders/model_builder.py", line 957, in build
> add_summaries)
> File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/builders/model_builder.py", line 517, in _build_faster_rcnn_model
> _check_feature_extractor_exists(frcnn_config.feature_extractor.type)
> File "/home/nec2/faster_rcnn/resnet101/models/research/object_detection/builders/model_builder.py", line 215, in _check_feature_extractor_exists
> 'Tensorflow'.format(feature_extractor_type))
> ValueError: faster_rcnn_resnet101 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

try uninstalling tensorflow and install tensorflow-gpu if u are working with colab......that worked for me

**Comment by ashiqak** [comment]
actually I'm running in local machine.

OS: Ubuntu 18.04.4 LTS

Graphics card: GeForce GTX 1060 6GB, NVIDIA Corporation, 64 bits

CUDA version:
cat /usr/lib/cuda/version.txt
CUDA Version 10.0.130

CUDNN version:
cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 27

**Comment by AshishGusain17** [comment]
@ashiqak so get a virtual environment for tf1 and than work on it. Else you can work in colab, I can send you my notebook with te code in colab

**Comment by ashiqak** [comment]
I had resolved it by changing the TensorFlow-GPU version form 2.2 to 1.15.2,
then I meet with another issue:

INFO:tensorflow:Graph was finalized.
I0708 07:09:29.176818 140553422391104 monitored_session.py:240] Graph was finalized.
2020-07-08 07:09:29.195499: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-08 07:09:29.298565: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3199980000 Hz
2020-07-08 07:09:29.301147: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5615564456e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-08 07:09:29.301216: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-08 07:09:29.322852: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-08 07:09:29.455617: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-08 07:09:29.456071: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561554eb8850 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-08 07:09:29.456085: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060 6GB, Compute Capability 6.1
2020-07-08 07:09:29.456376: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-08 07:09:29.456785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
2020-07-08 07:09:29.456943: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2020-07-08 07:09:29.457044: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2020-07-08 07:09:29.457111: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2020-07-08 07:09:29.457206: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2020-07-08 07:09:29.457259: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2020-07-08 07:09:29.457337: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2020-07-08 07:09:29.459364: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-08 07:09:29.459375: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1662] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-07-08 07:09:29.459407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-08 07:09:29.459413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0
2020-07-08 07:09:29.459417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N
INFO:tensorflow:Running local_init_op.

**Comment by AshishGusain17** [comment]
@ashiqak can't help it out.....never trained locally, I have always worked in colab

**Comment by pkulzc** [comment]
1. Please sync to HEAD
2. Use model_main.py for TF1 training, use model_main_tf2.py for TF2 training ( you need another config faster_rcnn_resnet101_v1_640x640_coco17_tpu-8.config)

**Comment by ashiqak** [comment]
you saved my day
