### ISSUE TITLE
ValueError: Unknown ssd feature_extractor: ssd_mobilenet_v3_large

### ISSUE THREAD

**Issue by Huangshisheng** [tensorflow/models#8775]
(tf1.12) D:\Users\Dell\Anaconda3\envs\tf1.12\models-master\research\object_detection>python export_tflite_ssd_graph.py --input_type image_tensor --pipeline_config_path=szuyk_change2pb/config/pipeline.config --trained_checkpoint_prefix=szuyk_change2pb/ckpt/model.ckpt --output_directory=szuyk_change2pb/output --add_postprocessing_op=false
2020-07-03 17:11:33.190283: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-07-03 17:11:33.208376: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From D:\models-master\models\research\slim\nets\mobilenet\mobilenet.py:389: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From D:\models-master\models\research\object_detection\export_tflite_ssd_graph_lib.py:153: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0703 17:11:36.461366 50100 module_wrapper.py:139] From D:\models-master\models\research\object_detection\export_tflite_ssd_graph_lib.py:153: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From D:\models-master\models\research\object_detection\export_tflite_ssd_graph_lib.py:197: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0703 17:11:36.468336 50100 module_wrapper.py:139] From D:\models-master\models\research\object_detection\export_tflite_ssd_graph_lib.py:197: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "export_tflite_ssd_graph.py", line 144, in <module>
    tf.app.run(main)
  File "D:\Users\Dell\Anaconda3\envs\tf1.12\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Users\Dell\Anaconda3\envs\tf1.12\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\Users\Dell\Anaconda3\envs\tf1.12\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_tflite_ssd_graph.py", line 140, in main
    FLAGS.max_classes_per_detection) #, use_regular_nms=FLAGS.use_regular_nms    hss
  File "D:\models-master\models\research\object_detection\export_tflite_ssd_graph_lib.py", line 201, in export_tflite_graph
    pipeline_config.model, is_training=False)
  File "D:\models-master\models\research\object_detection\builders\model_builder.py", line 108, in build
    add_background_class)
  File "D:\models-master\models\research\object_detection\builders\model_builder.py", line 176, in _build_ssd_model
    is_training=is_training)
  File "D:\models-master\models\research\object_detection\builders\model_builder.py", line 142, in _build_ssd_feature_extractor
    raise ValueError('Unknown ssd feature_extractor: {}'.format(feature_type))
ValueError: Unknown ssd feature_extractor: ssd_mobilenet_v3_large

**Comment by syiming** [comment]
Hi, could you please confirm you are using TF 1? Also, in your model_builder.py SSD_FEATURE_EXTRACTOR_CLASS_MAP there is ssd_mobilenet_v3_large (https://github.com/tensorflow/models/blob/acb34644536e6c66059c2decd73c23a69b41d85d/research/object_detection/builders/model_builder.py#L183). If not sync the repo should help with the issue. Thanks!

**Comment by syiming** [comment]
Closing this issue due to lack of activity. Please reopen it if you have further questions. Thanks!
