### ISSUE TITLE
Message type "object_detection.protos.DetectionModel" has no field named "loss"

### ISSUE THREAD

**Issue by sirvnvu98** [tensorflow/models#8776]
I am training model ssd_mobilenet_v2_quantized_coco
tensorflow = 1.15.0
protobuf = 3.12.3
Can you fix me this error? thank you

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py:125: main (from main) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
File "train.py", line 184, in 
tf.app.run()
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
return func(*args, **kwargs)
File "train.py", line 93, in main
FLAGS.pipeline_config_path)
File "/content/tensorflow1/models/research/object_detection/utils/config_util.py", line 96, in get_configs_from_pipeline_file
text_format.Merge(proto_str, pipeline_config)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 693, in Merge
allow_unknown_field=allow_unknown_field)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 760, in MergeLines
return parser.MergeLines(lines, message)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 785, in MergeLines
self._ParseOrMerge(lines, message)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 807, in _ParseOrMerge
self._MergeField(tokenizer, message)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 932, in _MergeField
merger(tokenizer, message, field)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 1006, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 899, in _MergeField
(message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 109:5 : Message type "object_detection.protos.DetectionModel" has no field named "loss"

**Comment by syiming** [comment]
Hi, could you please provide the config file you are using? The issue might result from an incorrect config file format. Thanks.

**Comment by sirvnvu98** [comment]
Thanks you, I have solved the issue
