### ISSUE TITLE
im2txt latest commit issue

### ISSUE THREAD

**Issue by redserpent7** [tensorflow/models#884]
Hi,

I pulled the latest im2txt code a couple of hours ago and it seems there is an issue. When I execute run_inference I get this error:

```Traceback (most recent call last):
  File "/home/ubuntu/tensor-models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/tensor-models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 49, in main
    FLAGS.checkpoint_path)
  File "/home/ubuntu/tensor-models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 118, in build_graph_from_config
    return self._create_restore_fn(checkpoint_path, saver)
  File "/home/ubuntu/tensor-models/models/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 92, in _create_restore_fn
    raise ValueError("No checkpoint file found in: %s", checkpoint_path)
ValueError: ('No checkpoint file found in: %s', None)
```

I still have the old im2txt from a couple of months ago on a different work station and that one works fine with the same exact checkpoints I'm providing here.

**Comment by redserpent7** [comment]
Luckily I still have TF 0.10 source with a compatible im2txt model. I've managed to build and run them on a different server and the checkpoint files work with no issues. So it seems there's something amiss in this latest commit

**Comment by jart** [comment]
Thanks for reaching out. Have you modified the im2txt implementation? The raise ValueError statement in your backtrace above doesn't appear that way in the codebase, and did not at previous revisions.

**Comment by redserpent7** [comment]
Yes sorry about that, i changed it because i was printing the name of the object instead of the value

**Comment by jart** [comment]
If the code is modified, I'm going to assume this isn't a bug a TensorFlow. If that isn't a case, then let me know by providing more information that helps us understand the bug, and I will re-open this issue.

**Comment by redserpent7** [comment]
Seriously? I only modified the log because it wasnot writing the path. I did not touch anything else. Maybe you should test the code before pushing any updates
