### ISSUE TITLE
Issues with models/official/nlp/bert/run_pretraining.py

### ISSUE THREAD

**Issue by aidad** [tensorflow/models#8868]
Hello,

I'm using 
https://github.com/tensorflow/models/blob/master/official/nlp/bert/run_pretraining.py
to pre-train bert on my custom data. I'm using tf-nightly and training the model on cloud TPU. 

The code uses model_training_utils.run_customized_training_loop(), which has been deprecated and I get "Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error" from a line in that function.

Here is the error log:

```
***** Number of cores used :  32
I0715 00:59:07.309198 140290240782464 run_pretraining.py:178] Training using customized training loop TF 2.0 with distributedstrategy.
WARNING:tensorflow:From research/bert/pretraining/training/run_pretraining.py:165: run_customized_training_loop (from official.nlp.bert.model_training_utils) is deprecated and will be removed in a future version.
Instructions for updating:
This function is deprecated and we do not expect adding new functionalities. Please do not have your code depending on this library.
W0715 00:59:07.309652 140290240782464 deprecation.py:323] From research/bert/pretraining/training/run_pretraining.py:165: run_customized_training_loop (from official.nlp.bert.model_training_utils) is deprecated and will be removed in a future version.
Instructions for updating:
This function is deprecated and we do not expect adding new functionalities. Please do not have your code depending on this library.
I0715 00:59:36.497698 140290240782464 optimization.py:89] using Adamw optimizer
2020-07-15 00:59:37.604910: W tensorflow/core/common_runtime/executor.cc:1086] [/device:CPU:0] Executor start aborting: Invalid argument: You must feed a value for placeholder tensor 'steps' with dtype int32
	 [[{{node steps}}]]
2020-07-15 01:00:20.527288: W tensorflow/core/common_runtime/executor.cc:1086] [/device:CPU:0] Executor start aborting: Invalid argument: You must feed a value for placeholder tensor 'steps' with dtype int32
	 [[{{node steps}}]]
Traceback (most recent call last):
  File "research/bert/pretraining/training/run_pretraining.py", line 219, in <module>
    app.run(main)
  File "/opt/virtualenv/pretrain/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/virtualenv/pretrain/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "research/bert/pretraining/training/run_pretraining.py", line 215, in main
    run_bert_pretrain(strategy)
  File "research/bert/pretraining/training/run_pretraining.py", line 201, in run_bert_pretrain
    custom_callbacks=custom_callbacks)
  File "research/bert/pretraining/training/run_pretraining.py", line 165, in run_customized_training
    custom_callbacks=custom_callbacks)
  File "/opt/virtualenv/pretrain/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/opt/virtualenv/pretrain/lib/python3.6/site-packages/official/nlp/bert/model_training_utils.py", line 482, in run_customized_training_loop
    train_loss = _float_metric_value(train_loss_metric)
  File "/opt/virtualenv/pretrain/lib/python3.6/site-packages/official/nlp/bert/model_training_utils.py", line 75, in _float_metric_value
    return metric.result().numpy().astype(float)
  File "/opt/virtualenv/pretrain/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1064, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/opt/virtualenv/pretrain/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1032, in _numpy
2020-07-15 01:02:01.903083: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: 3 root error(s) found.
  (0) Out of range: {{function_node __inference_train_steps_217694}} {{function_node __inference_train_steps_217694_15939018961085879472_10}} End of sequence
	 [[{{node while/body/_1/while/IteratorGetNext_18}}]]
	 [[while/cluster_while_body_198928/_execute_22_0/_964]]
	 [[while/LoopCond/_1251/_244]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2/device:TPU:5:
:{"created":"@1594774842.995987202","description":"Error received from peer ipv4:10.240.1.5:8470","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"{{function_node __inference_train_steps_217694_15939018961085879472_10}} End of sequence\n\t [[{{node while/body/_1/while/IteratorGetNext_18}}]]\n\t [[while/cluster_while_body_198928/_execute_22_0/_964]]\n\t [[while/LoopCond/_1251/_244]]","grpc_status":11}
  (1) Out of range: {{function_node __inference_train_steps_217694}} End of sequence
	 [[{{node while/body/_1/while/IteratorGetNext_18}}]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1594774842.994945378","description":"Error received from peer ipv4:10.240.1.5:8470","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"End of sequence\n\t [[{{node while/body/_1/while/IteratorGetNext_18}}]]","grpc_status":11}
	 [[GroupCrossDeviceControlEdges_0/TPUVariableReshard/last_iteration/_16617246711369326259/_7/_796]]
	 [[tpu_compile_succeeded_assert/_6992992333505467331/_3/_832]]
  (2) Out of range: {{function_node __inference_train_steps_217694}} End of sequence
	 [[{{node while/body/_1/while/IteratorGetNext_18}}]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1594774842.994945378","description":"Error received from peer ipv4:10.240.1.5:8470","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"End of sequence\n\t [[{{node while/body/_1/while/IteratorGetNext_18}}]]","grpc_status":11}
	 [[GroupCrossDeviceControlEdges_0/TPUVariableReshard/last_iteration/_16617246711369326259/_7/_796]]
0 successful operations.
30 derived errors ignored.
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.OutOfRangeError: 3 root error(s) found.
  (0) Out of range: {{function_node __inference_train_steps_217694}} {{function_node __inference_train_steps_217694_15939018961085879472_10}} End of sequence
	 [[{{node while/body/_1/while/IteratorGetNext_18}}]]
	 [[while/cluster_while_body_198928/_execute_22_0/_964]]
	 [[while/LoopCond/_1251/_244]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2/device:TPU:5:
:{"created":"@1594774842.995987202","description":"Error received from peer ipv4:10.240.1.5:8470","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"{{function_node __inference_train_steps_217694_15939018961085879472_10}} End of sequence\n\t [[{{node while/body/_1/while/IteratorGetNext_18}}]]\n\t [[while/cluster_while_body_198928/_execute_22_0/_964]]\n\t [[while/LoopCond/_1251/_244]]","grpc_status":11}
  (1) Out of range: {{function_node __inference_train_steps_217694}} End of sequence
	 [[{{node while/body/_1/while/IteratorGetNext_18}}]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1594774842.994945378","description":"Error received from peer ipv4:10.240.1.5:8470","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"End of sequence\n\t [[{{node while/body/_1/while/IteratorGetNext_18}}]]","grpc_status":11}
	 [[GroupCrossDeviceControlEdges_0/TPUVariableReshard/last_iteration/_16617246711369326259/_7/_796]]
	 [[tpu_compile_succeeded_assert/_6992992333505467331/_3/_832]]
  (2) Out of range: {{function_node __inference_train_steps_217694}} End of sequence
	 [[{{node while/body/_1/while/IteratorGetNext_18}}]]
Additional GRPC error information from remote target /job:worker/replica:0/task:2:
:{"created":"@1594774842.994945378","description":"Error received from peer ipv4:10.240.1.5:8470","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"End of sequence\n\t [[{{node while/body/_1/while/IteratorGetNext_18}}]]","grpc_status":11}
	 [[GroupCrossDeviceControlEdges_0/TPUVariableReshard/last_iteration/_16617246711369326259/_7/_796]]
0 successful operations.

```

I've also tried using Tensorflow 2.2.0 and the r 2.2.0 branch codes, I get a similar error. 

I didn't have this issue when running the run_classifer.py and that did run ok. 

Any thoughts are appreciated. Thank you.

**Comment by saberkun** [comment]
@aidad Sorry, the error log is not that useful. Because TPU enables async execution, the error reports at the place we ask eager tensor value: metric.result().numpy().
According to my experience, could we rule out two things first?
(1) number of tfrecord files. If you are using tpu-v3-32 for example, you need to provide more than one file. I would recommend generate many sharded files for pretraining data.
(2) does the data format match? whether the number of masked tokens matched the data?

Lastly, could you also share your flags to run the job? Do you modify the code?  Out of range error may indicate the iterator hitting data end because repeat() is not called?

**Comment by aidad** [comment]
Thanks for getting back to me @saberkun! Here is some more details:
(1) I have sharded the data into 20 txt files (each one has one sentence per line and different documents are separated by an empty line). I have created 20 tfrecord files from those by using the `create_pretraining_data.py` script. Each of the tfrecord files is about 2G in size. I just wanted to test the `run_pretraining.py` code, so I just passed the first tfrecord to the script with a small number of training steps. This file has about 2.7 million records in it. I'm using a v2-32 TPU:

```
export TPU_NAME=tpu-pretrain 
export TPU_SIZE=v2-32
ctpu up --name=$TPU_NAME --zone=us-central1-a --tpu-size=$TPU_SIZE --tf-version=nightly  -tpu-only -noconf
```
and here are the flags for pretraining:
`python run_pretraining.py 
--distribution_strategy=tpu 
--tpu=$TPU_NAME 
--input_files=$BERT_DIR/input/tfrecord/tf_examples0.tfrecord 
--bert_config_file=$BERT_DIR/input/config/bert_config.json 
--model_dir=$BERT_DIR/model_output 
--train_batch_size=256 
--max_seq_length=128 
--max_predictions_per_seq=20 
--num_steps_per_epoch=1000 
--steps_per_loop=200 
--num_train_epochs=3 
--learning_rate=$1e-4 
--warmup_steps=10000 
--scale_loss=True `

I'm not modifying the codes and am using them as they are. I see in the code that the train data is repeated (dataset.repeat()), but the error does sound like out of range ... end of sequence. I'm just wondering if the issue comes from eval, not the train.

(2) I've checked the format of the data in the tfrecord file and it has `input_ids`, `input_mask`, `segment_ids`, `masked_lm_positions`, `masked_lm_ids`, `masked_lm_weights`, `next_sentence_labels` with the right lengths. I haven't changed the default value of  `output_fake_labels` (True by default) in the `create_pretrain_dataset()` function.

Not sure whether the issue is coming from data, but I'll keep checking that. Thanks for helping with this.

**Comment by aidad** [comment]
I wonder if the `--num_steps_per_epoch` could be causing the issue. For fine tuning in `run_classifier.py`, `steps_per_epoch` (and also `eval_steps` and `warmup_steps`) are calculated in that code based on the train and eval data size (I was able to run `run_classifier.py` with no issues). I wonder if it makes sense to do something similar to that for pre-training.
Also, in `run_classifier.py` there is a flag for `eval_batch_size` and `eval_input_fn` is defined in the script. We don't have that in `run_pretraining.py` though.

**Comment by saberkun** [comment]
The input pipeline has a sharding logic based on files. You need to provide multiple files for v2-32 because it is a cluster of machines. Can you try a file pattern with multiple files (>=8) for ** input_files**?

Or comment out this section? https://github.com/tensorflow/models/blob/master/official/nlp/bert/input_pipeline.py#L95

**Comment by aidad** [comment]
So i passed a file pattern to input_files: `--input_files=$BERT_DIR/input/tfrecord/tf_examples*.tfrecord` and it worked!
Thanks a lot @saberkun.

**Comment by saberkun** [comment]
Thanks! @aidad 
Let me forward this to core TF team.
