### ISSUE TITLE
CenterNet ValueError: Dimensions must be equal, but are 90601 and 92416 for '{{node Loss/mul_1}} = Mul[T=DT_FLOAT](Loss/Pow_1, Loss/Pow_2)' with input shapes: [1,90601,1], [1,92416,1].

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/models#8908]
I was trying to use CenterNet for my dataset. Upon changing the dimensions in `image_resizer`, I'm getting following error:

```
Traceback (most recent call last):
  File "object_detection/model_main_tf2.py", line 106, in <module>
    tf.compat.v1.app.run()
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main_tf2.py", line 103, in main
    use_tpu=FLAGS.use_tpu)
  File "/home/deploy/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 622, in train_loop
    loss = _dist_train_step(train_input_iter)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/deploy/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:608 _dist_train_step  *
        return _sample_and_train(strategy, train_step_fn, data_iterator)
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:590 _sample_and_train  *
        per_replica_losses = strategy.run(
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:573 train_step_fn  *
        loss = eager_train_step(
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:246 eager_train_step  *
        losses_dict, _ = _compute_losses_and_predictions_dicts(
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:123 _compute_losses_and_predictions_dicts  *
        losses_dict = model.loss(
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/meta_architectures/center_net_meta_arch.py:2325 loss  *
        object_center_loss = self._compute_object_center_loss(
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/meta_architectures/center_net_meta_arch.py:1745 _compute_object_center_loss  *
        loss += object_center_loss(
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/core/losses.py:92 __call__  *
        return self._compute_loss(prediction_tensor, target_tensor, **params)
    /home/deploy/.local/lib/python3.6/site-packages/object_detection/core/losses.py:741 _compute_loss  *
        negative_loss = (tf.math.pow((1 - target_tensor), self._beta)*
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:984 binary_op_wrapper
        return func(x, y, name=name)
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:1283 _mul_dispatch
        return gen_math_ops.mul(x, y, name=name)
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py:6092 mul
        "Mul", x=x, y=y, name=name)
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:595 _create_op_internal
        compute_device)
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3327 _create_op_internal
        op_def=op_def)
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1817 __init__
        control_input_ops, op_def)
    /home/deploy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1657 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 90601 and 92416 for '{{node Loss/mul_1}} = Mul[T=DT_FLOAT](Loss/Pow_1, Loss/Pow_2)' with input shapes: [1,90601,1], [1,92416,1].
```

Here, is my config I used for training:

```
# CenterNet meta-architecture from the "Objects as Points" [1] paper
# with the ResNet-v2-101 backbone. The ResNet backbone has a few differences
# as compared to the one mentioned in the paper, hence the performance is
# slightly worse. This config is TPU comptatible.
# [1]: https://arxiv.org/abs/1904.07850

model {
  center_net {
    num_classes: 1
    feature_extractor {
      type: "resnet_v2_50"
    }
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 360
        max_dimension: 1205
        pad_to_max_dimension: true
      }
    }
    object_detection_task {
      task_loss_weight: 1.0
      offset_loss_weight: 1.0
      scale_loss_weight: 0.1
      localization_loss {
        l1_localization_loss {
        }
      }
    }
    object_center_params {
      object_center_loss_weight: 1.0
      min_box_overlap_iou: 0.7
      max_box_predictions: 100
      classification_loss {
        penalty_reduced_logistic_focal_loss {
          alpha: 2.0
          beta: 4.0
        }
      }
    }
    # mask_estimation_task{
    #   task_loss_weight: 4.0
    #   classification_loss {
    #     penalty_reduced_logistic_focal_loss {
    #       alpha: 2.0
    #       beta: 4.0
    #     }
    #   }
    # }
  }
}

train_config: {
  batch_size: 1
  num_steps: 150000

  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    random_crop_image {
      min_object_covered: 0.0
      min_aspect_ratio: 0.75
      max_aspect_ratio: 3.0
      min_area: 0.75
      max_area: 1.0
      overlap_thresh: 0.0
    }
  }

  optimizer {
    adam_optimizer: {
      epsilon: 1e-7  # Match tf.keras.optimizers.Adam's default.
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: 1e-3
          total_steps: 150000
          warmup_learning_rate: 2.5e-4
          warmup_steps: 5000
        }
      }
    }
    use_moving_average: false
  }
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false

  fine_tune_checkpoint_version: V2
  #fine_tune_checkpoint: "/home/deploy/ved/centernet_resnet101_v1_fpn_512x512_coco17_tpu-8/checkpoint/ckpt-0"
  fine_tune_checkpoint_type: "detection"
}

train_input_reader: {
  label_map_path: "/home/deploy/ved/label_map_potato_l1.pbtxt"
  tf_record_input_reader {
    input_path: "/home/deploy/ved/potato_l1_3x1_11_train.record"
  }
  load_instance_masks: true
  mask_type: PNG_MASKS
}

eval_config: {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  num_visualizations: 100
  batch_size: 1
}

eval_input_reader: {
  label_map_path: "/home/deploy/ved/label_map_potato_l1.pbtxt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "/home/deploy/ved/potato_l1_3x1_11_val.record"
  }
  mask_type: PNG_MASKS
  load_instance_masks: true
}
```

I was expecting to train the model with different input size.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 4.9.144-3.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b
- Python version: 3.6.3
- CUDA/cuDNN version: 10.1
- GPU model and memory: 11441MiB

**Comment by ravikyram** [comment]
@anshkumar 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by anshkumar** [comment]
@ravikyram  Update the info.

**Comment by ymodak** [comment]
I don't see CenterNet models hosted on `tensorflow/models` repo. Is it possible that the CenterNet model you are trying is hosted elsewhere? Can you please point me to the location where its located? Thanks!

**Comment by anshkumar** [comment]
I'm using tensorflow object detection api hosted [here](https://github.com/tensorflow/models/tree/master/research/object_detection).

**Comment by dapladoc** [comment]
I have the same error. It happens only when image size is not a power of 2. For image sizes like 512x512, 1024x1024, 1024x512 everything works fine for me.

**Comment by vighneshbirodkar** [comment]
Hello @anshkumar , @dapladoc . The size of the input should be a multiple of 128 due to the feature extractor we use. Once that is set in the config, the API if setup to handle the rest of the scaling correctly.
