### ISSUE TITLE
AttributeError: 'CenterNetResnetFeatureExtractor' object has no attribute 'get_model'

### ISSUE THREAD

**Issue by AarnavSawant** [tensorflow/models#8915]
Hi there, 
I am trying to train an object detection model using the new Tensorflow 2 API. When I try to train any CenterNet Models, I get this error.
 Traceback (most recent call last):
  File "/content/models/research/object_detection/model_main_tf2.py", line 106, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/model_main_tf2.py", line 103, in main
    use_tpu=FLAGS.use_tpu)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/model_lib_v2.py", line 554, in train_loop
    unpad_groundtruth_tensors)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/model_lib_v2.py", line 370, in load_fine_tune_checkpoint
    fine_tune_checkpoint_type=checkpoint_type)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/meta_architectures/center_net_meta_arch.py", line 2769, in restore_from_objects
    return {'feature_extractor': self._feature_extractor.get_model()}
AttributeError: 'CenterNetResnetFeatureExtractor' object has no attribute 'get_model'

I followed the notebook for training EfficientDet step by step and just changed the config file and fine_tune_checkpoint to the CenterNetResnet101 model. Please let me know if I am missing any steps. Thanks!

**Comment by saikumarchalla** [comment]
@AarnavSawant Could you please fill the  [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Also,please share the complete code snippet for us to reproduce the issue in our environment.Thanks!

**Comment by vighneshbirodkar** [comment]
Hello @AarnavSawant The issue is that the CenterNet Resnet 101 backbone does not support fine tuning from a `'detection'` checkpoint. Please change `fine_tune_checkpoint_type` to be `"classification"`. The error message there is not very intuitive. I will try to get a fix in soon.

**Comment by vighneshbirodkar** [comment]
I just realized that the ResNet V2 classification backbones have not been put up yet. We plan to release them soon. Till then, you can either train from scratch, or use the hourglass backbone with the ExtremeNet checkpoint here
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

Config for reference:
https://github.com/tensorflow/models/blob/master/research/object_detection/configs/tf2/center_net_hourglass104_512x512_coco17_tpu-8.config

**Comment by AarnavSawant** [comment]
Ok I will try another model till the ResNet Backbone gets put up. Thanks for the quick response!

**Comment by vighneshbirodkar** [comment]
I also just realized that we have this script that lets you create ResNet based classification checkpoints compatible with CenterNet
https://github.com/tensorflow/models/blob/master/research/object_detection/models/keras_models/convert_keras_models.py
