### ISSUE TITLE
TypeError: expected bytes, Descriptor found i ma using tensorflow 1.12 (cpu)

### ISSUE THREAD

**Issue by ahhkb** [tensorflow/models#8936]
(tf1.12) C:\Users\Ali\Desktop\tf1.12\model\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\Ali\anaconda3\envs\tf1.12\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Ali\anaconda3\envs\tf1.12\lib\site-packages\tensorflow\python\__init__.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\Ali\anaconda3\envs\tf1.12\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "C:\Users\Ali\anaconda3\envs\tf1.12\lib\site-packages\google\protobuf\symbol_database.py", line 184, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: module 'google.protobuf.descriptor_pool' has no attribute 'Default'

**Comment by ravikyram** [comment]
@ahhkb 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Please, share related code .Thanks!
