### ISSUE TITLE
Not possible to train Object Detection 2.0 in Colab using TPU

### ISSUE THREAD

**Issue by martinlyons** [tensorflow/models#8947]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection

## 2. Describe the bug

I'm familiar with the need to use gcs buckets for training data for colab TPUs. I have buckets setup to do this.
I'm trying to port my OD colab notebooks to tf2.0. I thought I'd try and use the TPUs available in Colab.

The issue is that the fine tuned checkpoint files in the config need to be on the local VM for the OD scripts to run - otherwise model_main_tf2.py will error almost immediately if a gs:// url is used. Changing the config location to a local VM drive will prevent this. However, soon afterwards, tensorflow will error when trying to access the checkpoint, saying that 'local storage' isn't implemented, which is the correct behavior since TPUs must use GCS buckets.

So I don't know how to have the config file point at both a local checkpoint and a gs:// resource. I'm assuming the same error will occur for the training/validation data tf records as well

## 3. Steps to reproduce
Create a colab
upload config files pointing to either local (colab drive) or gs:// locations for the fine tuning checkpoint.
run model_main_tf2.py with --use_tpu set to True

## 4. Expected behavior

TPU training should be possible somehow from colab?

## 5. Additional context

Error for gs:// content is 
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for gs://MYBUCKET/checkpoint/ckpt-0
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/models/research/object_detection/model_main_tf2.py", line 106, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/model_main_tf2.py", line 103, in main
    use_tpu=FLAGS.use_tpu)
  File "/content/models/research/object_detection/model_lib_v2.py", line 554, in train_loop
    unpad_groundtruth_tensors)
  File "/content/models/research/object_detection/model_lib_v2.py", line 335, in load_fine_tune_checkpoint
    if not is_object_based_checkpoint(checkpoint_path):
  File "/content/models/research/object_detection/model_lib_v2.py", line 298, in is_object_based_checkpoint
    var_names = [var[0] for var in tf.train.list_variables(checkpoint_path)]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 98, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 67, in load_checkpoint
    return py_checkpoint_reader.NewCheckpointReader(filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2
- Python version: 3.6

**Comment by ravikyram** [comment]
@martinlyons 

Will it be possible to share colab link to reproduce the issue .It helps us in localizing the issue faster.Thanks!

**Comment by martinlyons** [comment]
My bad. There was a bug in my location of my fine tuned data when I copied it over to gcs.

Cleaning up the colab to share it with you exposed it, so thanks!

Closing.
