### ISSUE TITLE
model_main.py (from object_detection import model_lib) doesn't work

### ISSUE THREAD

**Issue by goalpang** [tensorflow/models#8986]
https://github.com/tensorflow/models/blob/9556ebcc076e696dfd698bda8e25698db0625036/research/object_detection/model_main.py#L25

Hi guys, this line doesn't work.
I have the full tensorflow repositary, but the model_main.py stops at that line.
That's the error:

> Traceback (most recent call last):
  File "model_main.py", line 25, in < module >
    from object_detection import model_lib
  File "c:\tensorflow_SSD_1\models\research\object_detection\model_lib.py", line 30, in < module >
    from object_detection import exporter as exporter_lib
  File "c:\tensorflow_SSD_1\models\research\object_detection\exporter.py", line 24, in < module >
    from object_detection.builders import model_builder
  File "c:\tensorflow_SSD_1\models\research\object_detection\builders\model_builder.py", line 63, in < module >
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "c:\tensorflow_SSD_1\models\research\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 33, in < module >
    from official.vision.image_classification.efficientnet import efficientnet_model
ModuleNotFoundError: No module named 'official.vision'

Can someone help me? Thanks

**Comment by goalpang** [comment]
Resolved by setting pythonpath

**Comment by Deadpoolrah** [comment]
Can u show step by step??
