### ISSUE TITLE
'tensorflow.keras.activations' has no attribute 'gelu'

### ISSUE THREAD

**Issue by datistiquo** [tensorflow/models#8994]
I set up a new clean conda environment with python 3.6. 

I installed tf-nightly, tensorflow-addons and tensorflow_hup as requested. But I cannot run the examples (but with a external trained BERT model for my language) and get the following:

```

Traceback (most recent call last):
  File "run_classifier.py", line 506, in <module>
    app.run(main)
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_classifier.py", line 499, in main
    custom_main(custom_callbacks=None, custom_metrics=None)
  File "run_classifier.py", line 495, in custom_main
    custom_metrics=custom_metrics)
  File "run_classifier.py", line 410, in run_bert
    custom_metrics=custom_metrics)
  File "run_classifier.py", line 199, in run_bert_classifier
    custom_callbacks=custom_callbacks)
  File "run_classifier.py", line 221, in run_keras_compile_fit
    bert_model, sub_model = model_fn()
  File "run_classifier.py", line 149, in _get_classifier_model
    hub_module_trainable=FLAGS.hub_module_trainable))
  File "C:\Users\\Corona_Bot\models-master\official\nlp\bert\bert_models.py", line 344, in classifier_model
    bert_config, max_seq_length, output_range=1)
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\gin\config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\gin\utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\gin\config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "C:\Users\\Corona_Bot\models-master\official\nlp\bert\bert_models.py", line 175, in get_transformer_encoder
    return networks.TransformerEncoder(**kwargs)
  File "C:\Users\\Corona_Bot\models-master\official\nlp\modeling\networks\transformer_encoder.py", line 199, in __init__
    data = layer([data, attention_mask])
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 926, in __call__
    input_list)
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 667, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    C:\Users\\Corona_Bot\models-master\official\nlp\modeling\layers\transformer.py:214 call  *
        intermediate_output = self._intermediate_activation_layer(
    C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:926 __call__  **
        input_list)
    C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1117 _functional_construction_call
        outputs = call_fn(cast_inputs, *args, **kwargs)
    C:\Users\\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\python\keras\layers\core.py:427 call
        return self.activation(inputs)
    C:\Users\\Corona_Bot\models-master\official\modeling\activations\gelu.py:32 gelu
        return tf.keras.activations.gelu(x, approximate=True)

    AttributeError: module 'tensorflow.keras.activations' has no attribute 'gelu'

  In call to configurable 'get_transformer_encoder' (<function get_transformer_encoder at 0x00000274B249BB70>)
```

**Comment by saberkun** [comment]
Sorry for the break. The 'gelu' activation should be inside tf-nightly now.
'2.4.0-dev20200729'. Could you please try again?

**Comment by saberkun** [comment]
I think this problem should be fixed as our integration tests are passing for a few days already.
Closing. Thanks
