### ISSUE TITLE
DELF GLDv2 training with tpu error

### ISSUE THREAD

**Issue by feiwofeifeixiaowo** [tensorflow/models#9003]
Hi,  i am training delf follow [this ](https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training) tutorial.
it works well on gpu, i switch to tpu for speed up training by following code.
```bash
!python3 /content/models/research/delf/delf/python/training/train.py \
  --train_file_pattern=gs://xxx/train* \
  --validation_file_pattern=gs://xxx/validation* \
  --imagenet_checkpoint=gs://xxx/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5 \
  --dataset_version=gld_v2_clean \
  --batch_size=256 \
  --logdir=gs://save_bucket 
```
and change in train.py
```Python
#   strategy = tf.distribute.MirroredStrategy()
#   logging.info('Number of devices: %d', strategy.num_replicas_in_sync)
#   if FLAGS.debug:
#     print('Number of devices:', strategy.num_replicas_in_sync)
  print("connecting to TPU...")
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
  tf.config.experimental_connect_to_cluster(tpu)
  tf.tpu.experimental.initialize_tpu_system(tpu)
  strategy = tf.distribute.experimental.TPUStrategy(tpu)
```
got these error, i am new to tensorflow and tpu,  please give some advice  ^_^ .
``` bash
Traceback (most recent call last):
  File "/content/models/research/delf/delf/python/training/train.py", line 482, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/delf/delf/python/training/train.py", line 410, in main
    'loss/desc/crossentropy', desc_dist_loss, step=global_step)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/plugins/scalar/summary_v2.py", line 63, in scalar
    tf.debugging.assert_scalar(data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/check_ops.py", line 2096, in assert_scalar_v2
    assert_scalar(tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/check_ops.py", line 2122, in assert_scalar
    shape = tensor.get_shape()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1073, in get_shape
    return self.shape
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1067, in shape
    six.raise_from(core._status_to_exception(e.code, e.message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: RET_CHECK failure (learning/brain/google/xla/distributed_tpu_rewrite_pass.cc:1256) arg_shape.handle_type != DT_INVALID 
2020-07-29 15:49:57.433326: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:58] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 32935, Output num: 0
Additional GRPC error information:
{"created":"@1596037797.418826461","description":"Error received from peer ipv4:10.76.245.42:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 32935, Output num: 0","grpc_status":3}
```

**Comment by feiwofeifeixiaowo** [comment]
Any suggestions?  @andrefaraujo

**Comment by andrefaraujo** [comment]
I don't know, I have never used the TPUStrategy myself so far.

(Removed the type:bug label, since this is not a bug but rather a custom edit you did which does not yet work)

**Comment by feiwofeifeixiaowo** [comment]
Hi @andrefaraujo , sorry for so late reply.
 When I removed all tf.summary, the following error occurred. need help ^_^.

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_distributed_train_step_43711}} Compilation failure: Input 1 to node `backbone/Mean` with op Mean must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.
	 [[{{node backbone/Mean}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_12534948015575227521/_5]]
	 [[tpu_compile_succeeded_assert/_12534948015575227521/_5/_59]]
...

```

**Comment by ngoanpv** [comment]
Hi @feiwofeifeixiaowo, 
Have you fixed the error to train on TPU successfully? Could you please give me suggestions?
