### ISSUE TITLE
DELF local feature model

### ISSUE THREAD

**Issue by chhokarpardeep** [tensorflow/models#9008]
@andrefaraujo 

I have run this command to export local feature model but getting below error 👍 

command : 
python3 model/export_model.py \
  --ckpt_path=gldv2_training/delf_weights \
  --export_path=gldv2_model_local \
  --block3_strides

Error 

2020-07-30 12:50:59.844301: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "models/research/delf/delf/python/training/model/export_model.py", line 111, in <module>
    app.run(main)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "models/research/delf/delf/python/training/model/export_model.py", line 107, in main
    tf.saved_model.save(module, export_path)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 950, in save
    _, exported_graph, object_saver, asset_info = _build_meta_graph(
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1007, in _build_meta_graph
    signatures = signature_serialization.find_function_to_export(
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 85, in find_function_to_export
    concrete = _get_signature(function)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 42, in _get_signature
    function = function._get_concrete_function_garbage_collected()  # pylint: disable=protected-access
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 865, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 505, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3299, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/chhokarpardeep/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    models/research/delf/delf/python/training/model/export_model.py:73 ExtractFeatures  *
        extracted_features = export_model_utils.ExtractLocalFeatures(
    /mnt/d/models/research/delf/delf/python/training/model/export_model_utils.py:167 ExtractLocalFeatures  *
        final_boxes = box_list_ops.non_max_suppression(feature_boxes, iou,
    /home/chhokarpardeep/.local/lib/python3.8/site-packages/object_detection/core/box_list_ops.py:739 non_max_suppression  *
        with tf.name_scope(scope, 'NonMaxSuppression'):

    TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by andrefaraujo** [comment]
This seems an issue with the underlying object_detection codebase. Do you have a recent version of it installed?

Looking at the object_detection code, it seems like they have three positional arguments: https://github.com/tensorflow/models/blob/master/research/object_detection/core/box_list_ops.py#L749

**Comment by chhokarpardeep** [comment]
@andrefaraujo ,

I have checked the object_detection code, it has three positional arguments. Please check the screenshot.
![image](https://user-images.githubusercontent.com/20667075/88964578-3653ae00-d2c7-11ea-8b55-588a71b22f11.png)

**Comment by andrefaraujo** [comment]
right, so how can it complain that you gave 3 positional arguments?

**Comment by andrefaraujo** [comment]
oh wait, maybe the problem is with `tf.name_scope` actually?

**Comment by chhokarpardeep** [comment]
@andrefaraujo 

I have the TF version. Please let me know if I need to change for a specific version.
![image](https://user-images.githubusercontent.com/20667075/88965872-07d6d280-d2c9-11ea-841f-e9584687a58d.png)

**Comment by andrefaraujo** [comment]
I think I may have figured it out. Can you confirm if your `box_list_ops.py` file contains "import tensorflow as tf" or "import tensorflow.compat.v1 as tf"?

Seems like this commit in object_detection changed it recently: https://github.com/tensorflow/models/commit/451906e4e82f19712455066c1b27e2a6ba71b1dd

My guess is that you are using the old object_detection code with "import tensorflow as tf", which would lead to [this name_scope call](https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/framework/ops.py#L3934), which only accepts two arguments (`self` and `name`), while we would actually want to use the [TF1 name_scope call](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/name_scope).

**Comment by chhokarpardeep** [comment]
@andrefaraujo 

yes,  box_list_ops.py file file contains "import tensorflow.compat.v1 as tf".

![image](https://user-images.githubusercontent.com/20667075/89061388-41b7df80-d382-11ea-96d7-ad114615f183.png)

**Comment by andrefaraujo** [comment]
ok, then I'm puzzled :(

Is it possible that you would have different object_detection libraries installed, and accidentally are using the wrong one?

**Comment by chhokarpardeep** [comment]
@andrefaraujo ,

yes, I have found tensorflow-object-detection-api package install on my system and package builder script using this package.

Thanks andrefaraujo for your help. Issue fixed.

**Comment by andrefaraujo** [comment]
Great!

**Comment by cristyioan2000** [comment]
Worked for me:

# From within TensorFlow/models/research/
cp object_detection/packages/tf2/setup.py .
python -m pip install --use-feature=2020-resolver .
