### ISSUE TITLE
Converting tf2 ssd_mobilenet-v1 object detection model to tflite model

### ISSUE THREAD

**Issue by Raphaeal19** [tensorflow/models#9057]
I am using Google Colab to run the training and conversion.

When I run the script 

!python /content/models/research/object_detection/export_tflite_ssd_graph.py \
--pipeline_config=/content/workspace/training/pipeline.config \
--trained_checkpoint=/content/workspace/training/model.ckpt \
--output_dir=/content/workspace/hands_detection \
--add_postprocessing_op=true

I get this error:

Traceback (most recent call last):
  File "/content/models/research/object_detection/export_tflite_ssd_graph.py", line 144, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/export_tflite_ssd_graph.py", line 135, in main
    text_format.Merge(f.read(), pipeline_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python._pywrap_file_io.BufferedInputStream(arg0: str, arg1: int)

Invoked with: None, 524288

I traced the error to a pre_reading check for pipeline.config file. But it doesn't seem to be changed at all and all paths are correct.

**Comment by ravikyram** [comment]
@Raphaeal19 

I tried in colab with TF nightly version and was able to convert  tf2 mobilenet-v1 object detection model to tflite model .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/688464077c636cdbcd71b14a8b806bcf/untitled225.ipynb).Thanks!

**Comment by Raphaeal19** [comment]
This worked!! Thank you so much.

**Comment by CarrierDiagnostics** [comment]
I'm getting the same error when trying to train a custom model with model_main_tf2.py

Tensorflow 2.3
python 3.6.8
windows 10

**Comment by wathek** [comment]
Actually, in `model_main_tf2.py` there is a small error in the command, it's written:

```
python model_main_tf2.py -- \
  --model_dir=$MODEL_DIR --num_train_steps=$NUM_TRAIN_STEPS \
  --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
  --pipeline_config_path=$PIPELINE_CONFIG_PATH \
  --alsologtostderr

```

Just remove the -- in the first line:
```
python model_main_tf2.py  \
  --model_dir=$MODEL_DIR --num_train_steps=$NUM_TRAIN_STEPS \
  --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
  --pipeline_config_path=$PIPELINE_CONFIG_PATH \
  --alsologtostderr

```

**Comment by CarrierDiagnostics** [comment]
Hey

 yeah I migrated to ubuntu, tried everything again and the noticed that but it lead me to another error:

raise ValueError("The `global_batch_size` %r is not divisible by "
ValueError: The `global_batch_size` 1 is not divisible by `num_replicas_in_sync` 2 

Ubuntu
Python 3.8.2
TF 2.3.0

So is the last error caused by those two extra "--"?

**Comment by KuznetsovIllya** [comment]
> 
> 
> I'm getting the same error when trying to train a custom model with model_main_tf2.py
> 
> ---
> TypeError: **init**(): incompatible constructor arguments. The following argument types are supported:
> 1. tensorflow.python._pywrap_file_io.BufferedInputStream(arg0: str, arg1: int)
> 
> Invoked with: None, 524288`
Hi, @CarrierDiagnostics 
I had the same error - this means model_main_tf2.py can't find config file. I've found, that in some internet manuals the command for running training used parameter **pipeline_config**. However, **pipeline_config_path** should be used instead. Check the name of parameter you use and the the path to the config file.

**Comment by Laudarisd** [comment]
Same issue while training my custom datasets.
```
!python /content/models/research/object_detection/model_main_tf2.py \
    -- /content/models/research/deploy/\ ##path to config file 
    --/content/drive/MyDrive/Colab_Notebooks/tf_detection/ \ # path to custom data
    --/content/drive/MyDrive/Colab_Notebooks/tf_detection/ \ # path to save model
    --8 \
    --1 \
    --11
```


```
2021-04-26 11:59:54.520161: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-26 11:59:57.679610: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-26 11:59:57.681456: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-04-26 11:59:57.694010: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-26 11:59:57.694074: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (f2f060df2fee): /proc/driver/nvidia/version does not exist
2021-04-26 11:59:57.694791: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0426 11:59:57.695634 140023409923968 cross_device_ops.py:1321] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0426 11:59:57.695985 140023409923968 mirrored_strategy.py:350] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
Traceback (most recent call last):
  File "/content/models/research/object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 488, in train_loop
    pipeline_config_path, config_override=config_override)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/utils/config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 117, in read
    self._preread_check()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python._pywrap_file_io.BufferedInputStream(filename: str, buffer_size: int, token: tensorflow.python._pywrap_file_io.TransactionToken = None)

Invoked with: None, 524288
```

Any suggestion would be appreciated.

Thank you

**Comment by pannawis** [comment]
> I'm getting the same error when trying to train a custom model with model_main_tf2.py
> 
> Tensorflow 2.3
> python 3.6.8
> windows 10
> 
> `Traceback (most recent call last):
> File "model_main_tf2.py", line 115, in 
> tf.compat.v1.app.run()
> File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "C:\Python36\lib\site-packages\absl\app.py", line 299, in run
> _run_main(main, args)
> File "C:\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
> sys.exit(main(argv))
> File "model_main_tf2.py", line 112, in main
> record_summaries=FLAGS.record_summaries)
> File "C:\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\model_lib_v2.py", line 465, in train_loop
> pipeline_config_path, config_override=config_override)
> File "C:\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\config_util.py", line 138, in get_configs_from_pipeline_file
> proto_str = f.read()
> File "C:\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
> self._preread_check()
> File "C:\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
> self.__name, 1024 * 512)
> TypeError: **init**(): incompatible constructor arguments. The following argument types are supported:
> 1. tensorflow.python._pywrap_file_io.BufferedInputStream(arg0: str, arg1: int)
> 
> Invoked with: None, 524288`

You must use space instead of "=" if your path is not variable

 >python model_main_tf2.py --model_dir models/YourModel_xxx --pipeline_config_path models/YourModel_xxx/pipeline.config

**Comment by jxx789456** [comment]
I'm getting the same error when trying to train a custom model with model_main_tf2.py
Tensorflow 2.6
python 3.6
windows 10

Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\Anaconda3\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 112, in main
    record_summaries=FLAGS.record_summaries)
  File "D:\Program Files\models-master\research\object_detection\model_lib_v2.py", line 499, in train_loop
    pipeline_config_path, config_override=config_override)
  File "D:\Program Files\models-master\research\object_detection\utils\config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream(filename: str, buffer_size: int, token: tensorflow.python.lib.io._pywrap_file_io.TransactionToken = None)

Invoked with: None, 524288
