### ISSUE TITLE
ValueError: Tensor's shape is not compatible with supplied shape custom dataset using ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8

### ISSUE THREAD

**Issue by mgon5170** [tensorflow/models#9061]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/configs/tf2/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8.config
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

## 2. Describe the bug

When attempting to train a custom model using the config file and the corresponding model from the model zoo I receive the following error:   ValueError: Tensor's shape (3, 3, 256, 546) is not compatible with supplied shape (3, 3, 256, 12). Full output listed below. I am having difficult identifying what the source of this error is.

## 3. Steps to reproduce

Add custom dataset into the object_detection directory, download the config file and model from the links above, move the model to the object_detection directory, config gets placed into a object_detection/training directory, and edit the config file as shown below. Then run the command: 

MEG:object_detection meg$ python model_main_tf2.py --pipeline_config_path ./trainingpython model_main_tf2.py --pipeline_config_path=training/ssd_mobilenet_v1_fpn_shared_box_predictor_640x64

## 4. Expected behavior

I expect when I run the following command that I will begin to train an object detection model:

MEG:object_detection meg$ python model_main_tf2.py --pipeline_config_path ./trainingpython model_main_tf2.py --pipeline_config_path=training/ssd_mobilenet_v1_fpn_shared_box_predictor_640x64

## 5. Additional context
 SSD with Mobilenet v1 FPN feature extractor, shared box predictor and focal
 loss (a.k.a Retinanet).
 See Lin et al, https://arxiv.org/abs/1708.02002
 Trained on COCO, initialized from Imagenet classification checkpoint

 Achieves 29.7 mAP on COCO14 minival dataset.

--------config file --------------
 This config is TPU compatible

model {
  ssd {
    inplace_batchnorm_update: true
    freeze_batchnorm: false
    num_classes: 1
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
        use_matmul_gather: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    encode_background_as_zeros: true
    anchor_generator {
      multiscale_anchor_generator {
        min_level: 3
        max_level: 7
        anchor_scale: 4.0
        aspect_ratios: [1.0, 2.0, 0.5]
        scales_per_octave: 2
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 640
        width: 640
      }
    }
    box_predictor {
      weight_shared_convolutional_box_predictor {
        depth: 256
        class_prediction_bias_init: -4.6
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            random_normal_initializer {
              stddev: 0.01
              mean: 0.0
            }
          }
          batch_norm {
            scale: true,
            decay: 0.997,
            epsilon: 0.001,
          }
        }
        num_layers_before_predictor: 4
        kernel_size: 3
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v1_fpn_keras'
      fpn {
        min_level: 3
        max_level: 7
      }
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          random_normal_initializer {
            stddev: 0.01
            mean: 0.0
          }
        }
        batch_norm {
          scale: true,
          decay: 0.997,
          epsilon: 0.001,
        }
      }
      override_base_feature_extractor_hyperparams: true
    }
    loss {
      classification_loss {
        weighted_sigmoid_focal {
          alpha: 0.25
          gamma: 2.0
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    normalize_loc_loss_by_codesize: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  fine_tune_checkpoint: "ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/checkpoint/model.ckpt"
  batch_size: 20
  sync_replicas: true
  startup_delay_steps: 0
  replicas_to_aggregate: 8
  num_steps: 25000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    random_crop_image {
      min_object_covered: 0.0
      min_aspect_ratio: 0.75
      max_aspect_ratio: 3.0
      min_area: 0.75
      max_area: 1.0
      overlap_thresh: 0.0
    }
  }
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: .04
          total_steps: 25000
          warmup_learning_rate: .013333
          warmup_steps: 2000
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "data/train.record"
  }
  label_map_path: "data/object-detection.pbtxt"
}

eval_config: {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  num_examples: 8000
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "data/test.record"
  }
  label_map_path: "training/object-detection.pbtxt"
  shuffle: false
  num_readers: 1
}

--------ERROR OUTPUT----------

(SSD) MEG:object_detection meg$ python model_main_tf2.py --pipeline_config_path ./trainingpython model_main_tf2.py --pipeline_config_path=training/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync.config  --model_dir results --checkpoint_dir ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/checkpoint/
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
W0806 10:46:35.252889 4634940864 model_lib_v2.py:905] Forced number of epochs for all eval validations to be 1.
INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: None
I0806 10:46:35.253049 4634940864 config_util.py:552] Maybe overwriting sample_1_of_n_eval_examples: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0806 10:46:35.253113 4634940864 config_util.py:552] Maybe overwriting use_bfloat16: False
INFO:tensorflow:Maybe overwriting eval_num_epochs: 1
I0806 10:46:35.253171 4634940864 config_util.py:552] Maybe overwriting eval_num_epochs: 1
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
W0806 10:46:35.253251 4634940864 model_lib_v2.py:920] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
2020-08-06 10:46:35.342232: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-06 10:46:35.360943: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fae5731f580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-06 10:46:35.360963: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
W0806 10:46:35.394832 4634940864 deprecation.py:323] From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
WARNING:tensorflow:From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:175: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0806 10:46:35.418838 4634940864 deprecation.py:323] From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/builders/dataset_builder.py:175: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/inputs.py:79: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W0806 10:46:40.934005 4634940864 deprecation.py:323] From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/inputs.py:79: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/inputs.py:259: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0806 10:46:42.502683 4634940864 deprecation.py:323] From /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/inputs.py:259: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
INFO:tensorflow:Waiting for new checkpoint at ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/checkpoint/
I0806 10:46:46.062254 4634940864 checkpoint_utils.py:125] Waiting for new checkpoint at ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/checkpoint/
INFO:tensorflow:Found new checkpoint at ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/checkpoint/ckpt-0
I0806 10:46:46.079427 4634940864 checkpoint_utils.py:134] Found new checkpoint at ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/checkpoint/ckpt-0
Traceback (most recent call last):
  File "model_main_tf2.py", line 106, in <module>
    tf.compat.v1.app.run()
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 83, in main
    wait_interval=300, timeout=FLAGS.eval_timeout)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 959, in eval_continuously
    global_step=global_step)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/model_lib_v2.py", line 774, in eager_eval_loop
    eval_dict, losses_dict, class_agnostic = compute_eval_dict(features, labels)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/model_lib_v2.py:721 compute_eval_dict  *
        losses_dict, prediction_dict = _compute_losses_and_predictions_dicts(
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/model_lib_v2.py:118 _compute_losses_and_predictions_dicts  *
        prediction_dict = model.predict(
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/meta_architectures/ssd_meta_arch.py:591 predict  *
        predictor_results_dict = self._box_predictor(feature_maps)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/core/box_predictor.py:202 call  *
        return self._predict(image_features, **kwargs)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/predictors/convolutional_keras_box_predictor.py:484 _predict  *
        prediction = head_obj(head_tower_feature)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/predictors/heads/head.py:69 call  *
        return self._predict(features)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/object_detection/predictors/heads/keras_class_head.py:340 _predict  *
        class_predictions_with_background = layer(
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:897 __call__  **
        self._maybe_build(inputs)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:2416 _maybe_build
        self.build(input_shapes)  # pylint:disable=not-callable
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py:163 build
        dtype=self.dtype)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:577 add_weight
        caching_device=caching_device)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py:724 _add_variable_with_custom_getter
        name=name, shape=shape)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py:791 _preload_simple_restoration
        checkpoint_position=checkpoint_position, shape=shape)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py:75 __init__
        self.wrapped_value.set_shape(shape)
    /Users/meg/opt/anaconda3/envs/SSD/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1107 set_shape
        (self.shape, shape))

    ValueError: Tensor's shape (3, 3, 256, 546) is not compatible with supplied shape (3, 3, 256, 12)

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.6
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): command line? I used the setup file
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.10
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Comment by mgon5170** [comment]
My apologies for the confusion the first version may have caused. I was submitting two errors initially and mixed up the windows.

**Comment by mgon5170** [comment]
Closed issue to reopen it with new details. I have updated all files in the new issue opened: 
Training custom dataset ssd_resnet101_640x640, TF 2.2.0 giving ValueError: Tensor's shape is not compatible with supplied shape #9133
