### ISSUE TITLE
"masks" missing from Mask RCNN prediction parser labels['groundtruths']

### ISSUE THREAD

**Issue by roserustowicz** [tensorflow/models#9084]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/detection/dataloader/maskrcnn_parser.py 

## 2. Describe the bug

`masks` is missing from `labels['groundtruths']` in the Mask RCNN prediction parse function, `_parse_predict_data`. This error comes when trying to run evaluation with the following command: 

```
python tf_models/official/vision/detection/main.py \
   --strategy_type=one_device \
   --num_gpus=1 \
   --model_dir=${MODEL_DIR} \
   --mode=eval \
   --model=mask_rcnn \
   --config_file="my_config.yaml"
```

## 3. Steps to reproduce

Run the evaluation script for Mask RCNN with the above command.

## 4. Expected behavior

I expect `masks` to be included in the `labels['groundtruths']` so that the code can properly evaluate prediction performance in evaluation mode.

## 5. Additional context

```
Traceback (most recent call last):
  File "tf_models/official/vision/detection/main.py", line 279, in <module>
    app.run(main)
  File "/home/rose/.conda/envs/tsymmetry/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/rose/.conda/envs/tsymmetry/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tf_models/official/vision/detection/main.py", line 267, in main
    run()
  File "tf_models/official/vision/detection/main.py", line 261, in run
    callbacks=callbacks)
  File "tf_models/official/vision/detection/main.py", line 164, in run_executor
    total_steps=params.train.total_steps)
  File "/home/rose/dl-ag-team/projects/tsymmetry_colombia/tsymmetry_colombia/models/tf_models/official/modeling/training/distributed_executor.py", line 633, in evaluate_from_model_dir
    summary_writer=summary_writer)
  File "/home/rose/dl-ag-team/projects/tsymmetry_colombia/tsymmetry_colombia/models/tf_models/official/modeling/training/distributed_executor.py", line 697, in evaluate_checkpoint
    eval_metric, eval_iterator)
  File "/home/rose/dl-ag-team/projects/tsymmetry_colombia/tsymmetry_colombia/models/tf_models/official/vision/detection/executor/detection_executor.py", line 159, in _run_evaluation
    metric.update_state(labels, outputs)
  File "/home/rose/dl-ag-team/projects/tsymmetry_colombia/tsymmetry_colombia/models/tf_models/official/vision/detection/evaluation/coco_evaluator.py", line 81, in update_state
    self._evaluator.update(predictions, groundtruths)
  File "/home/rose/dl-ag-team/projects/tsymmetry_colombia/tsymmetry_colombia/models/tf_models/official/vision/detection/evaluation/coco_evaluator.py", line 270, in update
    'Missing the required key `{}` in groundtruths!'.format(k))
ValueError: Missing the required key `masks` in groundtruths!
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9.11
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.3
- CUDA/cuDNN version: 10.1/7.6.4
- GPU model and memory: NVIDIA Tesla K80

**Comment by gagika** [comment]
Hi  roserustowicz, 

Thanks for reporting it.
It looks like you are missing validation annotation JSON file (`instances_val2017.json`) in your evaluation.
In coco dataset it's under `annotations` folder in coco dataset. You can follow see more details in Mask-RCNN TPU [tutorial](https://cloud.google.com/tpu/docs/tutorials/mask-rcnn-2.x). If you are using for GPUs ignore TPU specific things.

```
# my_maskrcnn.yaml
train:
  train_file_pattern: <path to the TFRecord training data>
eval:
  eval_file_pattern: <path to the TFRecord validation data>
  val_json_file: <path to the validation annotation JSON file>
```

`val_json_file` needs to point to the `instances_val2017.json` file.

I will check if it's easy fix to make it work without the validation annotation file.

**Comment by roserustowicz** [comment]
@gagika Thank you for the response. I'm working with the repository in a case _without_ the annotation JSON file. In this case, `masks` are never defined in the `groundtruths` dictionary. 

```
      groundtruths = {
          'source_id': data['source_id'],
          'height': data['height'],
          'width': data['width'],
          'num_detections': tf.shape(data['groundtruth_classes']),
          'boxes': boxes,
          'classes': data['groundtruth_classes'],
          'areas': data['groundtruth_area'],
          'is_crowds': tf.cast(data['groundtruth_is_crowd'], tf.int32),
      }
```

**Comment by laxmareddyp** [comment]
Hi @roserustowicz,

The issue is outdated. The mentioned bug is not reproducible.
`tf_models/official/vision/detection/main.py` is not supported anymore.

Thanks.
