### ISSUE TITLE
DELF GLDv2 build_image_dataset.py make error: KeyError: 'image_path'

### ISSUE THREAD

**Issue by PeterKim1** [tensorflow/models#9125]
Hi.

I run `python3 build_image_dataset.py \
  --train_csv_path=gldv2_dataset/train/train.csv \
  --train_clean_csv_path=gldv2_dataset/train/train_clean.csv \
  --train_directory=gldv2_dataset/train/*/*/*/ \
  --output_directory=gldv2_dataset/tfrecord/ \
  --num_shards=128 \
  --generate_train_validation_splits \
  --validation_split_size=0.2`

 (https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training)

But, It makes this error:

Traceback (most recent call last):
  File "build_image_dataset.py", line 490, in <module>
    app.run(main)
  File "/home/smart02/anaconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/smart02/anaconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "build_image_dataset.py", line 484, in main
    FLAGS.seed)
  File "build_image_dataset.py", line 439, in _build_train_tfrecord_dataset
    image_dir)
  File "build_image_dataset.py", line 167, in _get_clean_train_image_files_and_labels
    image_paths.append(value['image_path'])
KeyError: 'image_path'

Someone upload same error before, but he doesn't say anything about solution. (https://github.com/tensorflow/models/issues/8924)

How to fix this error?

**Comment by andrefaraujo** [comment]
Did you check if part of the data was missing, like described in the other issue? 

If you found the solution, please let us know -- so we can help anyone else who ran into this :)

Closing this issue due to lack of activity in the past month, but please feel free to reopen if needed.

**Comment by shrikant-temburwar** [comment]
How did you solve this issue? I took a small size of data and encountered the same issue on it. How to solve it?

**Comment by shrikant-temburwar** [comment]
> Did you check if part of the data was missing, like described in the other issue?
> 
> If you found the solution, please let us know -- so we can help anyone else who ran into this :)
> 
> Closing this issue due to lack of activity in the past month, but please feel free to reopen if needed.



> Hi.
> 
> I run `python3 build_image_dataset.py \ --train_csv_path=gldv2_dataset/train/train.csv \ --train_clean_csv_path=gldv2_dataset/train/train_clean.csv \ --train_directory=gldv2_dataset/train/*/*/*/ \ --output_directory=gldv2_dataset/tfrecord/ \ --num_shards=128 \ --generate_train_validation_splits \ --validation_split_size=0.2`
> 
> (https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training)
> 
> But, It makes this error:
> 
> Traceback (most recent call last):
> File "build_image_dataset.py", line 490, in
> app.run(main)
> File "/home/smart02/anaconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
> _run_main(main, args)
> File "/home/smart02/anaconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
> sys.exit(main(argv))
> File "build_image_dataset.py", line 484, in main
> FLAGS.seed)
> File "build_image_dataset.py", line 439, in _build_train_tfrecord_dataset
> image_dir)
> File "build_image_dataset.py", line 167, in _get_clean_train_image_files_and_labels
> image_paths.append(value['image_path'])
> KeyError: 'image_path'
> 
> Someone upload same error before, but he doesn't say anything about solution. (#8924)
> 
> How to fix this error?

How did you solve this issue? I took a small size of data and encountered the same issue on it. How to solve it?

**Comment by Paranormaly** [comment]
@andrefaraujo Is using one tar file considered missing data?
I'm facing the same issue . I downloaded  one image tar (images_000) file
![Screenshot from 2020-11-21 14-00-39](https://user-images.githubusercontent.com/59418389/99876818-6224d780-2bc7-11eb-866e-8e67ce59684b.png)

**Comment by hamzakhalil798** [comment]
@Paranormaly  did it work? im running into same problem and using 5 tars.

**Comment by hamzakhalil798** [comment]
@PeterKim1 did you find solution?

**Comment by khatchad** [comment]
This issue should be open.

**Comment by khatchad** [comment]
A problem is that the value for this key is populated conditionally:

https://github.com/tensorflow/models/blob/b4c7ea90e8e9209c568d1b59f71432cfd69bb688/research/delf/delf/python/training/build_image_dataset.py#L159-L160

But, the value is retrieved unconditionally:

https://github.com/tensorflow/models/blob/b4c7ea90e8e9209c568d1b59f71432cfd69bb688/research/delf/delf/python/training/build_image_dataset.py#L166-L167
