### ISSUE TITLE
Try to insert codes and save the training model, meet [TypeError: 3 has type int, but expected one of: bytes, unicode] 

### ISSUE THREAD

**Issue by XudongWang97** [tensorflow/models#9137]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ x ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/detection/main.py
https://github.com/tensorflow/models/blob/master/official/modeling/training/distributed_executor.py

## 2. Describe the bug

In order to save the model when training ShapeMask on GPU, I insert some codes in `official/modeling/training/distributed_executor.py`. A bug happened when call `tensorflow.python.keras.engine.training.Model.save`:
**TypeError: 3 has type int, but expected one of: bytes, unicode**

In addition, there is no bug before the insertion of mode saving codes.

## 3. Steps to reproduce

- Install Python, CUDA, cudnn, TensorFlow, and other dependencies
- Insert codes to `official/modeling/training/distributed_executor.py`, line 459:
```python
    ...
    # Use training summary writer in TimeHistory if it's in use
    for cb in custom_callbacks:
      if isinstance(cb, keras_utils.TimeHistory):
        cb.summary_writer = self.train_summary_writer
    
    # model.save()
    logging.info('Saving training model...')
    save_model = model
    save_model.compile(
        optimizer=optimizer,
        loss=self.loss_fn(),
        metrics=metrics_as_dict(train_metric))
    save_model.save('save_model_train') # where the bug happened
    logging.info('Successfully save training model to {}'.format('save_model_train'))
    
    # Continue training loop.
    train_step = self._create_train_step(
        ...
```
- Run the following code in terminal,
```bash
cd path/to/tensorflow
python models/official/vision/detection/main.py \
  --strategy_type=mirrored \
  --num_gpus=4 \
  --model_dir=${MODEL_DIR_R101} \
  --mode=train \
  --model=shapemask \
  --config_file="workspace/training_shapemask/train_shapemask_R101.yaml"
```
where `MODEL_DIR_R101` is the path to **SSD ResNet101 V1 FPN 640x640 (RetinaNet101)** in [TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). The config file `train_shapemask_R101.yaml` is:
```yaml
# train_shapemask_R101.yaml
type: 'shapemask'
resnet:
  resnet_depth: 101
train:
  batch_size: 8
  total_steps: 90000
  learning_rate:
    init_learning_rate: 0.02
    learning_rate_levels: [0.002, 0.0002]
    learning_rate_steps: [60000, 80000]
    type: step
    warmup_learning_rate: 0.002
    warmup_steps: 200
  checkpoint:
    path: "/home/Xudong.wang/github/tensorflow/workspace/training_shapemask/pre-trained-models/ssd_resnet101_v1_fpn_640x640_coco17_tpu-8/checkpoint/checkpoint"
    prefix: 'resnet101/'
  train_file_pattern: "/data/mscoco_tfRecord/coco_train.record*"
  batch_size: 8
eval:
  eval_file_pattern: "/data/mscoco_tfRecord/coco_val.record*"
  val_json_file: "/data/mscoco_tfRecord/raw-data/annotations/instances_val2017.json"
shapemask_head:
  shape_prior_path: "/home/username/github/tensorflow/workspace/training_shapemask/kmeans_class_priors_91x20x32x32.npy"
```

- Behavior when running:
```bash
...
I0821 03:38:46.481346 140451885864768 distributed_executor.py:446] Checkpoint file /home/username/github/tensorflow/workspace/training_shapemask/pre-trained-models/ssd_resnet101_v1_fpn_640x640_coco17_tpu-8/checkpoint/ckpt-0 found and restoring from checkpoint
I0821 03:38:46.833778 140451885864768 distributed_executor.py:450] Loading from checkpoint file completed. Init step 0
I0821 03:38:46.841148 140451885864768 distributed_executor.py:474] Saving training model...
2020-08-21 03:43:44.564889: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0821 03:45:45.019718 140451885864768 deprecation.py:506] From /home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "models/official/vision/detection/main.py", line 287, in <module>
    app.run(main)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "models/official/vision/detection/main.py", line 282, in main
    run()
  File "models/official/vision/detection/main.py", line 276, in run
    callbacks=callbacks)
  File "models/official/vision/detection/main.py", line 137, in run_executor
    save_config=True)
  File "/home/username/github/tensorflow/models/official/modeling/training/distributed_executor.py", line 482, in train
    save_model.compile(
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1052, in save
    signatures, options)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 138, in save_model
    signatures, options)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1037, in _build_meta_graph
    asset_info.asset_index)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 691, in _serialize_object_graph
    concrete_function, saveable_view.captured_tensor_node_ids, coder)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/function_serialization.py", line 73, in serialize_concrete_function
    coder.encode_structure(structured_outputs))
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 96, in encode_structure
    return self._map_structure(nested_structure, self._get_encoders())
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 80, in _map_structure
    return do(pyobj, recursion_fn)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 181, in do_encode
    encoded_tuple.tuple_value.values.add().CopyFrom(encode_fn(element))
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 80, in _map_structure
    return do(pyobj, recursion_fn)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 204, in do_encode
    encoded_dict.dict_value.fields[key].CopyFrom(encode_fn(value))
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 80, in _map_structure
    return do(pyobj, recursion_fn)
  File "/home/username/anaconda3/envs/tfmodels/lib/python3.6/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 204, in do_encode
    encoded_dict.dict_value.fields[key].CopyFrom(encode_fn(value))
TypeError: 3 has type int, but expected one of: bytes, unicode
```

## 4. Expected behavior

Successfully save a model to filepath.

## 5. Additional context

I have find an exactly same issue on [stackoverflow](https://stackoverflow.com/questions/61344999/how-to-save-complete-tensorflow-model-while-using-official-tensorflow-object-det), but there is no answer.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.10
- CUDA/cuDNN version: 10.1.243 / 7.6.5
- GPU model and memory: 4 nvidia RTX 2080 Ti with 11GB memory

**Comment by yeqingli** [comment]
This might be the same issue as issue #8470. Please check  https://github.com/tensorflow/models/issues/8470#issuecomment-802218996
