### ISSUE TITLE
[TF 2 Object Detection API] Unable to run evaluation - TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Panaroja** [tensorflow/models#9183]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ Y ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ Y ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

When I run model_main_tf2.py using the steps mentioned in the official guide [(here)](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md) and execute following code (I left out references to my local files):

```
python model_main_tf2.py \
--pipeline_config_path=C:/Users/User/Documents/TensorFlow/workspace/mgr_holes/pre-trained/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8/pipeline.config \
--checkpoint_dir=models/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8_groceries \
 --alsologtostderr 

```
The TF2 initializes correctly, load the model, latest checkpoint is loaded and then I get the below error message:

```
I0901 22:21:48.011265 49544 checkpoint_utils.py:134] Found new checkpoint at kodels/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8_groceries\ckpt-30
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\User\anaconda3\envs\Mgr_TF2_P8\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\User\anaconda3\envs\Mgr_TF2_P8\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\User\anaconda3\envs\Mgr_TF2_P8\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 80, in main
    model_lib_v2.eval_continuously(
  File "C:\Users\User\anaconda3\envs\Mgr_TF2_P8\lib\site-packages\object_detection\model_lib_v2.py", line 974, in eval_continuously
    os.path.join(model_dir, 'eval', eval_name))
  File "C:\Users\User\anaconda3\envs\Mgr_TF2_P8\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This error message is consistent across my 3 conda environments (on python 3.7, python 3.8 with TF 2.2 and python 3.8 with TF 2.3). I am able to execute the training just as expected but evaluation, no matter what model is used and what evaluation metric is specified in the config file, always fails on the below message.

## 3. Steps to reproduce

As stated above, the script which I execute is following the below template:

```
# From the tensorflow/models/research/ directory
PIPELINE_CONFIG_PATH="XXXX/models/research/object_detection/configs/tf2/uhuru.config"
MODEL_DIR="XXXX"
CHECKPOINT_DIR=${MODEL_DIR}
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
nohup python XXXX/models/research/object_detection/model_main_tf2.py \
        --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
        --model_dir=${MODEL_DIR} \
        --checkpoint_dir=${CHECKPOINT_DIR} \
        --alsologtostderr 
```

Below I have also attached example of one of the config files used during training and when trying to execute eval:

```
# Faster R-CNN with Resnet-50 (v1)
# Trained on COCO, initialized from Imagenet classification checkpoint

# Achieves -- mAP on COCO14 minival dataset.

# This config is TPU compatible.

model {
  faster_rcnn {
    num_classes: 4
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 640
        max_dimension: 640
        pad_to_max_dimension: true
      }
    }
    feature_extractor {
      type: 'faster_rcnn_resnet50_keras'
      batch_norm_trainable: true
    }
    first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [0.25, 0.5, 1.0, 2.0]
        aspect_ratios: [0.5, 1.0, 2.0]
        height_stride: 16
        width_stride: 16
      }
    }
    first_stage_box_predictor_conv_hyperparams {
      op: CONV
      regularizer {
        l2_regularizer {
          weight: 0.0
        }
      }
      initializer {
        truncated_normal_initializer {
          stddev: 0.01
        }
      }
    }
    first_stage_nms_score_threshold: 0.0
    first_stage_nms_iou_threshold: 0.7
    first_stage_max_proposals: 300
    first_stage_localization_loss_weight: 2.0
    first_stage_objectness_loss_weight: 1.0
    initial_crop_size: 14
    maxpool_kernel_size: 2
    maxpool_stride: 2
    second_stage_box_predictor {
      mask_rcnn_box_predictor {
        use_dropout: false
        dropout_keep_probability: 1.0
        fc_hyperparams {
          op: FC
          regularizer {
            l2_regularizer {
              weight: 0.0
            }
          }
          initializer {
            variance_scaling_initializer {
              factor: 1.0
              uniform: true
              mode: FAN_AVG
            }
          }
        }
        share_box_across_classes: true
      }
    }
    second_stage_post_processing {
      batch_non_max_suppression {
        score_threshold: 0.0
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 300
      }
      score_converter: SOFTMAX
    }
    second_stage_localization_loss_weight: 2.0
    second_stage_classification_loss_weight: 1.0
    use_static_shapes: true
    use_matmul_crop_and_resize: true
    clip_anchors_to_image: true
    use_static_balanced_label_sampler: true
    use_matmul_gather_in_matcher: true
  }
}

train_config: {
  batch_size: 1
  sync_replicas: true
  startup_delay_steps: 0
  replicas_to_aggregate: 8
  num_steps: 250000
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: .04
          total_steps: 25000
          warmup_learning_rate: .013333
          warmup_steps: 2000
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  fine_tune_checkpoint_version: V2
  fine_tune_checkpoint: "C:/Users/User/Documents/TensorFlow/workspace/mgr_holes/pre-trained/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8_groceries/checkpoint/ckpt-0"
  fine_tune_checkpoint_type: "detection"
  data_augmentation_options {
    random_horizontal_flip {
    }
  }

  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
  use_bfloat16: false  # works only on TPUs
}

train_input_reader: {
  label_map_path: "C:/Users/User/Documents/TensorFlow/workspace/mgr_training_demo/annotations/label_map.pbtxt"
  tf_record_input_reader {
    input_path: "C:/Users/User/Documents/TensorFlow/workspace/mgr_training_demo/annotations/train.record"
  }
}

eval_config: {
  metrics_set: "oid_V2_detection_metrics"
  use_moving_averages: false
  batch_size: 1;
}

eval_input_reader: {
  label_map_path: "C:/Users/User/Documents/TensorFlow/workspace/mgr_training_demo/annotations/label_map.pbtxt"
  shuffle: true
  num_epochs: 1
  tf_record_input_reader {
    input_path: "C:/Users/User/Documents/TensorFlow/workspace/mgr_holes/annotations/test.record"
  }
}

```
## 4. Expected behavior

I expect the evaluation process to start and print evaluation metrics (like mAP) to the Tensorboard. Currently, even during the training, no evaluation data is visible.

## 5. Additional context

Training works perfectly as expected. Evaluation cannot be launched and even when eval options are added when launching model_main_tf2.py, no evaluation metrics are printed to the Tensorflow.
Only loss, steps and train images are visible in the Tensorboard.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): TF installed in conda environment via pip
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1.243
- GPU model and memory: NVIDIA GeForce RTX 2060

**Comment by huberemanuel** [comment]
You need to specify the model_dir parameter

**Comment by huberemanuel** [comment]
You need to specify the `model_dir` parameter, you actually mention this parameter on the "Steps to reproduce" section, but you are no using it on "Describe the bug" section. Did you try passing this parameter?

**Comment by Panaroja** [comment]
If I could *facepalm* myself here, that would be the place. Indeed, even though I was looking at this several times, time after time I was skipping this exact parameter.
