### ISSUE TITLE
TypeError: ('Not JSON Serializable:', tf.float32)

### ISSUE THREAD

**Issue by 2020zyc** [tensorflow/models#9186]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/nlp/transformer/transformer_main.py

## 2. Describe the bug
I need a ".pb" model(savedModel) for tf.serving, not just a ".ckpt" model created by save_weights_only=TRUE.
When changed the "save_weights_only" option(in line 418) from "True" to "False",
the error occured: TypeError: ('Not JSON Serializable:', tf.float32)
![image](https://user-images.githubusercontent.com/7539692/91956469-45e76c00-ed37-11ea-8c1a-f215d0b2f063.png)

## 3. Steps to reproduce

I just ran the code in the URL above following its example tutorial. 
Two params were changed: hidden_size=256(default 512) AND filter_size=512(default 2048)
With the above configuration, weights could be saved successfully with the default "save_weights_only=True".

## 4. Expected behavior

if save_weights_only=False, a savedModel(not ckpt) would be generated.

## 5. Additional context

pycharm logs:

> 2020-09-02 07:46:07.054060: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
I0902 07:47:15.653520 140510663464768 keras_utils.py:122] TimeHistory: 87.05 seconds, 2352.78 examples/second between steps 0 and 100
2020-09-02 07:47:19.791337: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
**INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).**
I0902 07:47:26.516451 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
**INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).**
I0902 07:47:26.516770 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
I0902 07:47:26.516961 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
I0902 07:47:26.517098 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
I0902 07:47:27.793794 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
I0902 07:47:27.794195 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
I0902 07:47:27.794377 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
I0902 07:47:27.794553 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
I0902 07:47:27.794695 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
I0902 07:47:27.794836 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
I0902 07:47:28.309843 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
I0902 07:47:28.310060 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
I0902 07:47:28.310272 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
I0902 07:47:28.310407 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
I0902 07:47:28.359903 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7e5a20>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
I0902 07:47:28.360061 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e30d860>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
I0902 07:47:28.360238 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
I0902 07:47:28.360367 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
I0902 07:47:28.360511 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e2fcc88>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
I0902 07:47:28.360628 140510663464768 def_function.py:1038] Unsupported signature for serialization: ((TensorSpec(shape=(None, None), dtype=tf.int64, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fc97e7d0d68>), {}).
Traceback (most recent call last):
  File "/home/xxx/pycharm_proj/models-master/official/nlp/transformer/transformer_main.py", line 628, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/xxx/pycharm_proj/models-master/official/nlp/transformer/transformer_main.py", line 609, in main
    task.train()
  File "/home/xxx/pycharm_proj/models-master/official/nlp/transformer/transformer_main.py", line 437, in train
    verbose=(2 if flags_obj.enable_time_history else 1))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 412, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 1249, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 1313, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1979, in save
    signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 134, in save_model
    signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 80, in save
    save_lib.save(model, filepath, signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 976, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1076, in _build_meta_graph
    asset_info.asset_index)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 721, in _serialize_object_graph
    saveable_view.function_name_map)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 761, in _write_object_proto
    metadata=obj._tracking_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 3011, in _tracking_metadata
    return self._trackable_saved_model_saver.tracking_metadata
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 54, in tracking_metadata
    return json_utils.Encoder().encode(self.python_properties)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 44, in encode
    return super(Encoder, self).encode(_encode_tuple(obj))
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 41, in default
    return serialization.get_json_type(obj)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/serialization.py", line 72, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', tf.float32)

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04.3 LTS
- Mobile device name if the issue happens on a mobile device:  None
- TensorFlow installed from (source or binary):  pip
- TensorFlow version (use command below):  tensorflow-gpu 2.3.0
- Python version:  3.6.8
- Bazel version (if compiling from source):  None
- GCC/Compiler version (if compiling from source):  None
- CUDA/cuDNN version:  CUDA 10.1   Driver Version: 430.50
- GPU model and memory:  one GTX1080TI, 11G memory

**Comment by 2020zyc** [comment]
any solution? thanks

**Comment by chenGitHuber** [comment]
Hi 2020zyc,

Thanks for reporting this bug. I will send a fix shortly.

**Comment by chenGitHuber** [comment]
This [commit](https://github.com/tensorflow/models/commit/c60951b148f66d337084b07fa5da52b8246b6600) fixed the problem. Please try again.

**Comment by 2020zyc** [comment]
> This [commit](https://github.com/tensorflow/models/commit/c60951b148f66d337084b07fa5da52b8246b6600) fixed the problem. Please try again.

Thank @chenGitHuber. I could save a .pb model now at the training stage, but I failed in saving a .pb model as I changed the mode to  "mode=predict". I submitted a bug issue [here](https://github.com/tensorflow/models/issues/9235#issue-700498479).

The error is:
**ValueError: call() should not modify its Python input arguments. Check if it modifies any lists or dicts passed as arguments. Modifying a copy is allowed.**

my code:
```
with tf.name_scope("model"):
    model = transformer.create_model(params, is_train=False)
    self._load_weights_if_possible(model, tf.train.latest_checkpoint(self.flags_obj.model_dir))  
    model.summary()

# I tried to save the inference model in .pb format for tf.serving
logging.info("Save inference graph into the .pb format.")
model.save(os.path.join(flags_obj.model_dir, "1"), 
                    include_optimizer=False, options=save_options_lib.SaveOptions())  #  ----> error here
logging.info("successfully.")
```

**From the pycharm log, it seems the "decoder_stack" is the source of the error:**
Traceback (most recent call last):
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/transformer/transformer_main.py", line 955, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/transformer/transformer_main.py", line 944, in main
    task.predict(chunk_list, line=line, use_bsrule=False)
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/transformer/transformer_main.py", line 541, in predict
    options=save_options_lib.SaveOptions())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1950, in save
    signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 135, in save_model
    signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 80, in save
    save_lib.save(model, filepath, signatures, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1000, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1148, in _build_meta_graph
    meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1095, in _build_meta_graph_impl
    checkpoint_graph_view)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 147, in list_functions
    self._serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2561, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 3047, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 87, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 79, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 57, in _get_serialized_attributes_internal
    serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 155, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 274, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 57, in _get_serialized_attributes_internal
    serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 165, in wrap_layer_functions
    '{}_layer_call_and_return_conditional_losses'.format(layer.name))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 505, in add_function
    self.add_trace(*self._input_signature)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 420, in add_trace
    trace_with_training(True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 418, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 549, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1176, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1082, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 717, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2955, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3333, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3188, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 987, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 625, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 526, in wrapper
    ret = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 169, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/control_flow_util.py", line 113, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 168, in <lambda>
    training, lambda: replace_training_and_call(True),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 165, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 569, in call_and_return_conditional_losses
    call_output = layer_call(inputs, *args, **kwargs)
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/transformer/transformer.py", line 154, in call
    return self.predict(encoder_outputs, attention_bias, training)
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/transformer/transformer.py", line 349, in predict
    dtype=self.params["dtype"])
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 635, in sequence_beam_search
    return sbs.search(initial_ids, initial_cache)
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 414, in search
    parallel_iterations=1))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2499, in while_loop_v2
    return_same_structure=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2696, in while_loop
    back_prop=back_prop)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/while_v2.py", line 196, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 987, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/while_v2.py", line 174, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 390, in _search_step
    new_seq, new_log_probs, topk_ids, new_cache = _grow_alive_seq(state)
  File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/modeling/ops/beam_search.py", line 238, in _grow_alive_seq
    flat_ids, i, flat_cache)
  **File "/home/xxx/pycharm_proj/models-master-0907/official/nlp/transformer/transformer.py", line 287, in symbols_to_logits_fn
    decode_loop_step=i if self.params["padded_decode"] else None)**
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 990, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 71, in return_outputs_and_add_losses
    outputs, losses = fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 169, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/control_flow_util.py", line 113, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 168, in <lambda>
    training, lambda: replace_training_and_call(True),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py", line 165, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 543, in __call__
    self.call_collection.add_trace(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 420, in add_trace
    trace_with_training(True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 418, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 549, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1176, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 1082, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 717, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2955, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3333, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3188, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 994, in func_graph_from_py_func
    check_mutation(func_args_before, func_args, original_func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 1078, in check_mutation
    raise ValueError(errmsg)
ValueError: call() should not modify its Python input arguments. Check if it modifies any lists or dicts passed as arguments. Modifying a copy is allowed.
