### ISSUE TITLE
finetune BERT-Tiny

### ISSUE THREAD

**Issue by tc64** [tensorflow/models#9195]
python 3.7.6
tf 2.3.0-dev20200620
running on Jupyter Notebook instance in google cloud

I'm able to fine-tune for the SST-2 task using the BERT models mentioned here: https://github.com/tensorflow/models/tree/master/official/nlp/bert

Is it expected that finetuning would work for BERT-Tiny, or other models linked to from here? https://github.com/google-research/bert

It seems from the logs like perhaps I need to load the model elsewhere, then save it in a certain way (object based), but I am not sure.

I get this error:
```
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0903 20:18:21.115236 140138680104320 mirrored_strategy.py:342] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0903 20:18:21.533809 140138680104320 run_classifier.py:177] Training using TF 2.x Keras compile/fit API with distribution strategy.
I0903 20:18:23.797391 140138680104320 optimization.py:89] using Adamw optimizer
WARNING:tensorflow:From /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py:1298: NameBasedSaverStatus.__init__ (from tensorflow.python.training.tracking.util) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
W0903 20:18:23.812926 140138680104320 deprecation.py:323] From /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py:1298: NameBasedSaverStatus.__init__ (from tensorflow.python.training.tracking.util) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Traceback (most recent call last):
  File "run_classifier.py", line 498, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_classifier.py", line 491, in main
    custom_main(custom_callbacks=None, custom_metrics=None)
  File "run_classifier.py", line 487, in custom_main
    custom_metrics=custom_metrics)
  File "run_classifier.py", line 401, in run_bert
    custom_metrics=custom_metrics)
  File "run_classifier.py", line 193, in run_bert_classifier
    custom_callbacks=custom_callbacks)
  File "run_classifier.py", line 220, in run_keras_compile_fit
    checkpoint.restore(init_checkpoint).assert_existing_objects_matched()
  File "/home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 998, in assert_existing_objects_matched
    return self.assert_consumed()
  File "/home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 983, in assert_consumed
    "".join(unused_attribute_strings)))
AssertionError: Some objects had attributes which were not restored:
    MirroredVariable:{
  0: <tf.Variable 'word_embeddings/embeddings:0' shape=(30522, 128) dtype=float32, numpy=
array([[ 0.01793153, -0.02772574,  0.00235425, ...,  0.01793916,
         0.00867778, -0.00760466],
       [ 0.02553082, -0.02151281, -0.00777549, ...,  0.00097344,
        -0.01089773, -0.02009542],
       [-0.01146627,  0.03694598, -0.00263269, ...,  0.01312859,
         0.00132318,  0.01872476],
       ...,
```

thanks.

**Comment by tc64** [comment]
this is the command to run fine tuning:

```commandline
export BERT_DIR=/home/jupyter/uncased_L-2_H-128_A-2
export MODEL_DIR=<some bucket path>
export GLUE_DIR=<some bucket path>
export TASK=SST-4

python run_classifier.py \
          --mode='train_and_eval' \
          --input_meta_data_path=${GLUE_DIR}/${TASK}_meta_data \
          --train_data_path=${GLUE_DIR}/${TASK}_train.tf_record \
          --eval_data_path=${GLUE_DIR}/${TASK}_eval.tf_record \
          --bert_config_file=${BERT_DIR}/bert_config.json \
          --init_checkpoint=${BERT_DIR}/bert_model.ckpt \
          --train_batch_size=4 \
          --eval_batch_size=4 \
          --steps_per_loop=1 \
          --learning_rate=2e-5 \
          --num_train_epochs=10 \
          --model_dir=${MODEL_DIR} \
          --distribution_strategy=mirrored
```

**Comment by tc64** [comment]
note: above should be sst-2 not 4

**Comment by chenGitHuber** [comment]
Hi, 

Checkpoint files from https://github.com/google-research/bert (including BERT-Tiny) are in TF1 checkpoint format and are not expected to work with our TF2 code. You need to convert them to TF2 checkpoint format using the following tool:

https://github.com/tensorflow/models/blob/master/official/nlp/bert/tf2_encoder_checkpoint_converter.py

**Comment by tc64** [comment]
@chenGitHuber thank you
