### ISSUE TITLE
AttributeError: use_cpu_nms

### ISSUE THREAD

**Issue by MediavoiceSrL** [tensorflow/models#9211]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

## 2. Describe the bug

I followed instructions to install tensorflow 2 as described in the link above in "Python Package Installation" section.
The installation ends whitout errors.

## 3. Steps to reproduce

When I try to run test 

python object_detection/builders/model_builder_tf2_test.py 

I obtain the following errors:

AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_faster_rcnn_from_config_with_crop_feature(True) (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_from_config_with_crop_feature(True) (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_from_config_with_crop_feature(True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\deep-user\.conda\envs\tensorflow2\lib\site-packages\absl\testing\parameterized.py", line 267, in bound_param_test
    test_method(self, testcase_params)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 292, in test_create_faster_rcnn_from_config_with_crop_feature
    _ = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_faster_rcnn_from_config_with_crop_feature(False) (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_from_config_with_crop_feature(False) (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_from_config_with_crop_feature(False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\deep-user\.conda\envs\tensorflow2\lib\site-packages\absl\testing\parameterized.py", line 267, in bound_param_test
    test_method(self, testcase_params)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 292, in test_create_faster_rcnn_from_config_with_crop_feature
    _ = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_faster_rcnn_model_from_config_with_example_miner (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_model_from_config_with_example_miner (__main__.ModelBuilderTF2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 271, in test_create_faster_rcnn_model_from_config_with_example_miner
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_faster_rcnn_models_from_config_faster_rcnn_with_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_faster_rcnn_with_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_faster_rcnn_with_matmul(use_matmul_crop_and_resize=False, enable_mask_prediction=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\deep-user\.conda\envs\tensorflow2\lib\site-packages\absl\testing\parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 262, in test_create_faster_rcnn_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_faster_rcnn_models_from_config_faster_rcnn_without_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_faster_rcnn_without_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_faster_rcnn_without_matmul(use_matmul_crop_and_resize=True, enable_mask_prediction=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\deep-user\.conda\envs\tensorflow2\lib\site-packages\absl\testing\parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 262, in test_create_faster_rcnn_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_faster_rcnn_models_from_config_mask_rcnn_with_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_mask_rcnn_with_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_mask_rcnn_with_matmul(use_matmul_crop_and_resize=False, enable_mask_prediction=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\deep-user\.conda\envs\tensorflow2\lib\site-packages\absl\testing\parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 262, in test_create_faster_rcnn_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_faster_rcnn_models_from_config_mask_rcnn_without_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_mask_rcnn_without_matmul (__main__.ModelBuilderTF2Test)
test_create_faster_rcnn_models_from_config_mask_rcnn_without_matmul(use_matmul_crop_and_resize=True, enable_mask_prediction=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\deep-user\.conda\envs\tensorflow2\lib\site-packages\absl\testing\parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 262, in test_create_faster_rcnn_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_rfcn_model_from_config (__main__.ModelBuilderTF2Test)
test_create_rfcn_model_from_config (__main__.ModelBuilderTF2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 282, in test_create_rfcn_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 663, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_ssd_fpn_model_from_config (__main__.ModelBuilderTF2Test)
test_create_ssd_fpn_model_from_config (__main__.ModelBuilderTF2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 220, in test_create_ssd_fpn_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 402, in _build_ssd_model
    ssd_config.post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

======================================================================
ERROR: test_create_ssd_models_from_config (__main__.ModelBuilderTF2Test)
test_create_ssd_models_from_config (__main__.ModelBuilderTF2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder_test.py", line 212, in test_create_ssd_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 1062, in build
    add_summaries)
  File "D:\faster_rcnn\models\research\object_detection\builders\model_builder.py", line 402, in _build_ssd_model
    ssd_config.post_processing)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "D:\faster_rcnn\models\research\object_detection\builders\post_processing_builder.py", line 107, in _build_non_max_suppressor
    use_cpu_nms=nms_config.use_cpu_nms)
AttributeError: use_cpu_nms

----------------------------------------------------------------------
Ran 20 tests in 2.246s

FAILED (errors=11, skipped=1)
 

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
 
- TensorFlow installed from (source or binary): tensorflow installed using "python -m pip install --use-feature=2020-resolver ." as described in "https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md"
- TensorFlow version: 2.4.0-dev20200907
- Python version: 3.6

- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA Quadro RTX4000 8Gb

**Comment by SamLee514** [comment]
I had this issue when I pulled the other day because I hadn't rebuilt the protos (use_cpu_nms looks like it was only recently added). Fixed by running protoc object_detection/protos/*.proto --python_out=. from models/research as per this guide: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#protobuf-installation-compilation
