### ISSUE TITLE
Civar10_train & Cifar10_multi_gpu_train won't run: TypeError: strided_slice() missing 1 required positional argument: 'strides'

### ISSUE THREAD

**Issue by hurbotulk** [tensorflow/models#923]
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
Traceback (most recent call last):
  File "C:/Users/TH/PycharmProjects/TensorflowTest/cifar10_3/cifar10_train.py", line 120, in <module>
    tf.app.run()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "C:/Users/TH/PycharmProjects/TensorflowTest/cifar10_3/cifar10_train.py", line 116, in main
    train()
  File "C:/Users/TH/PycharmProjects/TensorflowTest/cifar10_3/cifar10_train.py", line 63, in train
    images, labels = cifar10.distorted_inputs()
  File "C:\Users\TH\PycharmProjects\TensorflowTest\cifar10_3\cifar10.py", line 156, in distorted_inputs
    batch_size=FLAGS.batch_size)
  File "C:\Users\TH\PycharmProjects\TensorflowTest\cifar10_3\cifar10_input.py", line 161, in distorted_inputs
    read_input = read_cifar10(filename_queue)
  File "C:\Users\TH\PycharmProjects\TensorflowTest\cifar10_3\cifar10_input.py", line 87, in read_cifar10
    tf.strided_slice(record_bytes, [0], [label_bytes]), tf.int32)
TypeError: strided_slice() missing 1 required positional argument: 'strides'

**Comment by drpngx** [comment]
@itsmeolivia is that a known/fixed problem?

**Comment by itsmeolivia** [comment]
it's an api change that was made for the 1.0 alpha release.  strides is no longer a required argument on the latest version

**Comment by drpngx** [comment]
@hurbotulk please upgrade your TF version. Feel free to re-open if it still doesn't work.
