### ISSUE TITLE
AttributeError: super_categories

### ISSUE THREAD

**Issue by Ahmad-Omar-Ahsan** [tensorflow/models#9240]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/model_main.py

## 2. Describe the bug

After initiating training for 30 mins Google cloud platform for ssd inception v2, the training gets terminated due to an attribute error called super_categories inside eval_util.py.

## 3. Steps to reproduce

# From tensorflow/models/research
cp object_detection/packages/tf1/setup.py .
gcloud ai-platform jobs submit training ssd_nrc_htr_`date +%m_%d_%Y_%H_%M_%S` \
    --runtime-version 1.15 \
    --python-version 3.7 \
    --job-dir=gs://my_bucket/temp_tesseract/model_dir \
    --package-path ./object_detection \
    --module-name object_detection.model_main \
    --region us-central1 \
    --config object_detection/configs/optimized_ssd_config.yaml \
    -- \
    --model_dir=gs://my_bucket/temp_tesseract/model_dir \
    --pipeline_config_path=gs://my_bucket/temp_tesseract/data/pipeline_ssd.config

## 4. Expected behavior

Expected the model to finish training without any error

## 5. Additional context

`Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/training.py", line 539, in _evaluate
    self._evaluator.evaluate_and_export())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/training.py", line 920, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 480, in evaluate
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 522, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 504, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1511, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1547, in _call_model_fn_eval
    features, labels, ModeKeys.EVAL, config)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/object_detection/model_lib.py", line 624, in model_fn
    eval_config, list(category_index.values()), eval_dict)
  File "/root/.local/lib/python3.7/site-packages/object_detection/eval_util.py", line 1094, in get_eval_metric_ops_for_evaluators
    evaluator_options = evaluator_options_from_eval_config(eval_config)
  File "/root/.local/lib/python3.7/site-packages/object_detection/eval_util.py", line 1133, in evaluator_options_from_eval_config
    for super_category in eval_config.super_categories:
AttributeError: super_categories`

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.15
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Used google cloud platform 
- GPU model and memory: NVIDIA Tesla K80

**Comment by jlovick** [comment]
i have also come been stumped with this.. appears to be related to changes in commit 3f3ecc47de53d1c127889912a0a3ab3c74635a42

**Comment by jlovick** [comment]
this change "side-steps" the problem  in eval_util.py  ... but may have unintended side effects I am not aware of

`1133       if hasattr(eval_config, "super_catagories"):
1134         for super_category in eval_config.super_categories:
1135           if 'super_categories' not in evaluator_options[eval_metric_fn_key]:
1136             evaluator_options[eval_metric_fn_key]['super_categories'] = {}
1137           key = super_category
1138           value = eval_config.super_categories[key].split(',')
1139           evaluator_options[eval_metric_fn_key]['super_categories'][key] = value`
