### ISSUE TITLE
Object Detection: tflite conversion documentation missing metadata adding instructions for Android deployment added in new commit

### ISSUE THREAD

**Issue by quickgrid** [tensorflow/models#9341]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ x ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md

https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

## 2. Describe the issue

The links above point to Android example where latest change in code is not reflected in documentation.

https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

Current example code expects zip based `tflite` with `metadata`, but documentation does not provide instruction for it.

https://github.com/tensorflow/examples/commit/de42482b453de6f7b6488203b20e7eec61ee722e#diff-0cf980453f18b3cc1368f8eb16a803f9L113

Without this step it gives error when deploying to android,

```
java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
        at org.tensorflow.lite.support.metadata.MetadataExtractor.assertZipFile(MetadataExtractor.java:325)
        at org.tensorflow.lite.support.metadata.MetadataExtractor.getAssociatedFile(MetadataExtractor.java:165)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:116)
```

I have commented on this issue below with detailed information on error,

https://github.com/tensorflow/tensorflow/issues/43583

**Comment by KATSUYA2** [comment]
For "Describe the issue", the sample program worked by rewriting as follows.

```java
    InputStream labelsInput  = context.getAssets().open(labelFilename);
    BufferedReader br = new BufferedReader(new InputStreamReader(labelsInput));
    String line;
    boolean firstLine = true;
    while ((line = br.readLine()) != null) {
      Log.w(TAG, line);
      d.labels.add(line);
    }
    br.close();
```

However, there are other problems besides "metadata.getAssociatedFile ()".
The recognition result that the list file is off by one line is displayed.
By not forcibly registering the first line as shown below, the operation was as expected. However, I don't know the reason for one line.
```java
    InputStream labelsInput  = context.getAssets().open(labelFilename);
    BufferedReader br = new BufferedReader(new InputStreamReader(labelsInput));
    String line;
    boolean firstLine = true;
    while ((line = br.readLine()) != null) {
      if ( firstLine ) {
        firstLine=false;
      } else {
        Log.w(TAG, line);
        d.labels.add(line);
      }
    }
    br.close();
```

**Comment by mocialov** [comment]
I have the same issue. I need to write metadata to the SSD model to run it with Android Firebase framework. Is there a script that shows how to add metadata to the SSD like here https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/metadata/2?

Image classification example has a script for the metadata (https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/metadata/metadata_writer_for_image_classifier.py) but not the object detection

**Comment by Johnson145** [comment]
> The recognition result that the list file is off by one line is displayed.
By not forcibly registering the first line as shown below, the operation was as expected. However, I don't know the reason for one line.

As described [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md#label-maps), label maps used during training start with index `1`. I think I remember to have read somewhere that the index `0` is reserved for the background class. The exported tflite model file seems to have shifted the indices towards such that `0` is used for the first foreground class.

**Comment by quickgrid** [comment]
Closing this issue as the android code was updated and may no longer apply for new change.

**Comment by Johnson145** [comment]
@quickgrid This issue does affect the latest Android version, too. Neither the `lib_task_api` nor the `lib_interpreter` work out-of-the-box, if a model file without embedded meta data is used. AFAIK, the objet detection guide still doesn't mention this though.

**Comment by quickgrid** [comment]
Thank you for letting me know. I thought it was fixed.

**Comment by karuneshpalekar** [comment]
I am facing the same issue . I also haven't found any source from where i could find a tutorial to add metadata for a tflite object detection model

**Comment by mocialov** [comment]
> I am facing the same issue . I also haven't found any source from where i could find a tutorial to add metadata for a tflite object detection model

I could be wrong, but I think that mlkit requires metadata, while older methods, like using an interpreter class in Android does not require metadata (except for the labels file) since parameters, such as the buffer size, input size, quantization flag, etc are specified directly in the interpreter object

**Comment by karuneshpalekar** [comment]
Hey I guess I found the solution . Check this out 
https://gist.github.com/4PixelsDev/7400df5cd6f004c4d630c849660577d6
Hope this helps.

**Comment by Andreahernandezt** [comment]
> Hey I guess I found the solution . Check this out
> https://gist.github.com/4PixelsDev/7400df5cd6f004c4d630c849660577d6
> Hope this helps.

I used this and the model is not fully supported by android studio. Any solutions?

**Comment by karuneshpalekar** [comment]
I faced the same issue following the above gist .I found a tutorial doing the needful on Youtube. Here is the Link 
https://www.youtube.com/watch?v=p56ILZdLddc  .
It is divided into 8 parts wherein the first 4 parts Model is created and in the next 4 parts process of integrating  the model  with android is shown.

**Comment by Niloofar-bgh** [comment]
@mocialov  & @Andreahernandezt 
FYI:
https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/metadata/python/metadata_writers
