### ISSUE TITLE
Can im2txt run in shell by os.popen?

### ISSUE THREAD

**Issue by adaxidedakaonang** [tensorflow/models#937]
## Please let us know which model this issue is about (specify the top-level directory)
I met a question . When I run the commend by os.popen, it'swrong. This is my code :

def getMessage(img):
    jpg = img
    cmdline = '''
                 CHECKPOINT_DIR="${HOME}/models-master/im2txt/im2txt/model/model.ckpt-3000000" & \

                 VOCAB_FILE="${HOME}/models-master/im2txt/im2txt/data/word_counts.txt"  & \

                 IMAGE_FILE="%s"  & \
                 bazel build -c opt im2txt/run_inference  & \
                 export CUDA_VISIBLE_DEVICES=""  & \
                 bazel-bin/im2txt/run_inference \ & \
                 --checkpoint_path=/home/ubuntu/models-master/im2txt/im2txt/model/model.ckpt-3000000 \
                 --vocab_file= /home/ubuntu/models-master/im2txt/im2txt/data/word_counts.txt\
                  --input_files=%s

    ''' % (jpg, jpg).

I want run the im2txt by shell. However,  I met  a wrong while running this code.  after researching, I found it is because the last three commends didn't run as I wished. I paste it in shell ,does anyone know how to run it with os.popen? This is the error:

Traceback (most recent call last):
  File "/home/ubuntu/models-master/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/models-master/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/run_inference.py", line 49, in main
    FLAGS.checkpoint_path)
  File "/home/ubuntu/models-master/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 118, in build_graph_from_config
    return self._create_restore_fn(checkpoint_path, saver)
  File "/home/ubuntu/models-master/im2txt/bazel-bin/im2txt/run_inference.runfiles/im2txt/im2txt/inference_utils/inference_wrapper_base.py", line 92, in _create_restore_fn
    raise ValueError("No checkpoint file found in: %s" % checkpoint_path)
ValueError: No checkpoint file found in: None

**Comment by asimshankar** [comment]
This question is probably better asked on [stackoverflow](http://stackoverflow.com/) as we try to keep the github issues focused on bugs and feature requests. Thanks.
