### ISSUE TITLE
AttributeError: 'ConvolutionalBoxPredictor' object has no attribute 'inputs'

### ISSUE THREAD

**Issue by MarcoPianta** [tensorflow/models#9372]
Tensorflow version: 2.3.1
I'm trying to do transfer learning on model ssd_mobilenet_v2_320x320_coco17_tpu-8

To start the training I run:
```
python model_main.py \
  --pipeline_config_path="ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config" \
  --model_dir="/content/model_output" \
  --num_train_steps="500" \
  --num_eval_steps="100"
```

but I get this error:
```python
Traceback (most recent call last):
  File "model_main.py", line 108, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main.py", line 104, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 505, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 646, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 747, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/content/models/research/object_detection/model_lib.py", line 556, in model_fn
    update_ops=detection_model.updates(),
  File "/content/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 1350, in updates
    self._box_predictor.inputs))
AttributeError: 'ConvolutionalBoxPredictor' object has no attribute 'inputs'
```

Here is my config file: [pipeline.config.txt](https://github.com/tensorflow/models/files/5377120/pipeline.config.txt)
And here is the colab link: https://colab.research.google.com/drive/1_W49JUgMCezfie9ikbspQbXs7I7Y1kx5?usp=sharing

**Comment by gowthamkpr** [comment]
This is very similar to this issue [here](https://github.com/tensorflow/models/issues/8913)

**Comment by MarcoPianta** [comment]
The problem was that I was using the wrong script, using model_main_tf2.py everything work

**Comment by shubham7066** [comment]
Getting this error on using model_main_tf2.py:

Traceback (most recent call last):
  File "model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 112, in main
    record_summaries=FLAGS.record_summaries)
  File "/kaggle/working/TFOD/models/research/object_detection/model_lib_v2.py", line 585, in train_loop
    os.path.join(model_dir, 'train'))
  File "/opt/conda/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

what should i do
