### ISSUE TITLE
MultiworkerStrategy validation error: tensorflow.python.framework.errors_impl.FailedPreconditionError

### ISSUE THREAD

**Issue by ashiqimranintel** [tensorflow/models#9377]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/image_classification

## 2. Describe the bug

Traceback (most recent call last):
  File "classifier_trainer.py", line 485, in <module>
    app.run(main)
  File "/localdisk/aimran/TF2.4bin/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/localdisk/aimran/TF2.4bin/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "classifier_trainer.py", line 472, in main
    stats = run(flags.FLAGS)
  File "classifier_trainer.py", line 464, in run
    return train_and_eval(params, strategy_override)
  File "classifier_trainer.py", line 418, in train_and_eval
    **validation_kwargs)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/engine/training.py", line 1117, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/callbacks.py", line 428, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/callbacks.py", line 1323, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/callbacks.py", line 1389, in _save_model
    self._maybe_remove_file()
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/callbacks.py", line 1419, in _maybe_remove_file
    self._write_filepath, self.model.distribute_strategy)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/distribute/distributed_file_utils.py", line 149, in remove_temp_dir_with_filepath
    remove_temp_dirpath(os.path.dirname(filepath), strategy)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/distribute/distributed_file_utils.py", line 122, in remove_temp_dirpath
    file_io.delete_recursively(_get_temp_dir(dirpath, strategy))
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/lib/io/file_io.py", line 587, in delete_recursively
    delete_recursively_v2(dirname)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/lib/io/file_io.py", line 600, in delete_recursively_v2
    _pywrap_file_io.DeleteRecursively(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /tmp/resnet50/workertemp_1/validation; Directory not empty

## 3. Steps to reproduce

python classifier_trainer.py \
  --mode=train_and_eval \
  --model_type=resnet \
  --dataset=imagenet \
  --model_dir=$MODEL_DIR \
  --data_dir=$DATA_DIR \
  --config_file=configs/examples/resnet/imagenet/gpu.yaml \
  --params_override='runtime.distribution_strategy=multi_worker_mirrored' \
  --log_steps=1

## 4. Expected behavior

Validation is showing me some errors with MultiworkerStrategy

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master
- Python version: 3.7
- Bazel version (if compiling from source): 3.1
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by ashiqimranintel** [comment]
I found the fix for this issue. Closing it now
