### ISSUE TITLE
"python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/efficientdet_d7_coco17.config" not working.

### ISSUE THREAD

**Issue by NhatAi** [tensorflow/models#9392]
Help me plz,...
I am following this: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10
But instead of using TF 1, I use:
              - **TF 2** and ***efficientdet_d7_coco17_tpu-32*** instead of _*faster_rcnn_inception_v2_pets*_
              -  THEN I GOT THIS:

**(tensorflow1) PS C:\tensorflow1\models\research\object_detection> python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/efficientdet_d7_co
co17.config
2020-10-19 16:37:31.809425: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py:251: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1019 16:37:34.574319  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py:251: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
2020-10-19 16:37:34.600214: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-10-19 16:37:35.666400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: Quadro K1000M computeCapability: 3.0
coreClock: 0.8505GHz coreCount: 1 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 26.82GiB/s
2020-10-19 16:37:35.671684: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-19 16:37:35.677602: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-19 16:37:35.683852: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-19 16:37:35.689218: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-19 16:37:35.696246: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-19 16:37:35.701566: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-19 16:37:35.706357: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-10-19 16:37:35.709193: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-10-19 16:37:35.726013: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x21873bca9e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-19 16:37:35.729675: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-19 16:37:35.732603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-19 16:37:35.734904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
I1019 16:37:35.744936  9100 ssd_efficientnet_bifpn_feature_extractor.py:144] EfficientDet EfficientNet backbone version: efficientnet-b6
I1019 16:37:35.744936  9100 ssd_efficientnet_bifpn_feature_extractor.py:145] EfficientDet BiFPN num filters: 384
I1019 16:37:35.745436  9100 ssd_efficientnet_bifpn_feature_extractor.py:147] EfficientDet BiFPN num iterations: 8
I1019 16:37:35.758453  9100 efficientnet_model.py:148] round_filter input=32 output=56
I1019 16:37:35.802468  9100 efficientnet_model.py:148] round_filter input=32 output=56
I1019 16:37:35.802468  9100 efficientnet_model.py:148] round_filter input=16 output=32
I1019 16:37:36.031706  9100 efficientnet_model.py:148] round_filter input=16 output=32
I1019 16:37:36.032229  9100 efficientnet_model.py:148] round_filter input=24 output=40
I1019 16:37:36.634285  9100 efficientnet_model.py:148] round_filter input=24 output=40
I1019 16:37:36.634285  9100 efficientnet_model.py:148] round_filter input=40 output=72
I1019 16:37:37.298918  9100 efficientnet_model.py:148] round_filter input=40 output=72
I1019 16:37:37.299418  9100 efficientnet_model.py:148] round_filter input=80 output=144
I1019 16:37:38.136620  9100 efficientnet_model.py:148] round_filter input=80 output=144
I1019 16:37:38.136620  9100 efficientnet_model.py:148] round_filter input=112 output=200
I1019 16:37:39.004179  9100 efficientnet_model.py:148] round_filter input=112 output=200
I1019 16:37:39.005179  9100 efficientnet_model.py:148] round_filter input=192 output=344
I1019 16:37:40.433311  9100 efficientnet_model.py:148] round_filter input=192 output=344
I1019 16:37:40.433311  9100 efficientnet_model.py:148] round_filter input=320 output=576
I1019 16:37:40.883462  9100 efficientnet_model.py:148] round_filter input=1280 output=2304
I1019 16:37:40.953514  9100 efficientnet_model.py:462] Building model efficientnet with params ModelConfig(width_coefficient=1.8, depth_coefficient=2.6, resolution=528, dropout_rate=0.5, blocks=(BlockConfig(input_filters=32, output_filters=16, kernel_size=3, num_repeat=1, expand_ratio=1, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=16, output_filters=24, kernel_size=3, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=24, output_filters=40, kernel_size=5, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=40, output_filters=80, kernel_size=3, num_repeat=3, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=80, output_filters=112, kernel_size=5, num_repeat=3, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=112, output_filters=192, kernel_size=5, num_repeat=4, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=192, output_filters=320, kernel_size=3, num_repeat=1, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise')), stem_base_filters=32, top_base_filters=1280, activation='simple_swish', batch_norm='default', bn_momentum=0.99, bn_epsilon=0.001, weight_decay=5e-06, drop_connect_rate=0.2, depth_divisor=8, min_depth=None, use_se=True, input_channels=3, num_classes=1000, model_name='efficientnet', rescale_input=False, data_format='channels_last', dtype='float32')
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py:265: create_global_step (from tf_slim.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1019 16:37:41.120647  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py:265: create_global_step (from tf_slim.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
INFO:tensorflow:Reading unweighted datasets: ['C:/tensorflow1/models/research/object_detection/train.record']
I1019 16:37:41.139898  9100 dataset_builder.py:148] Reading unweighted datasets: ['C:/tensorflow1/models/research/object_detection/train.record']
INFO:tensorflow:Reading record datasets for input file: ['C:/tensorflow1/models/research/object_detection/train.record']
I1019 16:37:41.146900  9100 dataset_builder.py:77] Reading record datasets for input file: ['C:/tensorflow1/models/research/object_detection/train.record']
INFO:tensorflow:Number of filenames to read: 1
I1019 16:37:41.147900  9100 dataset_builder.py:78] Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W1019 16:37:41.148901  9100 dataset_builder.py:86] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py:103: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
W1019 16:37:41.153904  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py:103: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py:222: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W1019 16:37:41.189917  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py:222: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py:48: DatasetV1.make_initializable_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_initializable_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.
W1019 16:37:43.031208  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py:48: DatasetV1.make_initializable_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_initializable_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\core\batcher.py:101: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
W1019 16:37:43.151279  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\core\batcher.py:101: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\training\input.py:752: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1019 16:37:43.160428  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\training\input.py:752: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\training\input.py:752: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1019 16:37:43.163428  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\training\input.py:752: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
I1019 16:37:43.184436  9100 ssd_efficientnet_bifpn_feature_extractor.py:144] EfficientDet EfficientNet backbone version: efficientnet-b6
I1019 16:37:43.184436  9100 ssd_efficientnet_bifpn_feature_extractor.py:145] EfficientDet BiFPN num filters: 384
I1019 16:37:43.185437  9100 ssd_efficientnet_bifpn_feature_extractor.py:147] EfficientDet BiFPN num iterations: 8
I1019 16:37:43.197441  9100 efficientnet_model.py:148] round_filter input=32 output=56
I1019 16:37:43.254489  9100 efficientnet_model.py:148] round_filter input=32 output=56
I1019 16:37:43.254489  9100 efficientnet_model.py:148] round_filter input=16 output=32
I1019 16:37:43.739614  9100 efficientnet_model.py:148] round_filter input=16 output=32
I1019 16:37:43.739614  9100 efficientnet_model.py:148] round_filter input=24 output=40
I1019 16:37:45.160442  9100 efficientnet_model.py:148] round_filter input=24 output=40
I1019 16:37:45.160942  9100 efficientnet_model.py:148] round_filter input=40 output=72
I1019 16:37:46.483127  9100 efficientnet_model.py:148] round_filter input=40 output=72
I1019 16:37:46.483782  9100 efficientnet_model.py:148] round_filter input=80 output=144
I1019 16:37:48.357353  9100 efficientnet_model.py:148] round_filter input=80 output=144
I1019 16:37:48.357353  9100 efficientnet_model.py:148] round_filter input=112 output=200
I1019 16:37:50.201900  9100 efficientnet_model.py:148] round_filter input=112 output=200
I1019 16:37:50.202400  9100 efficientnet_model.py:148] round_filter input=192 output=344
I1019 16:37:53.021636  9100 efficientnet_model.py:148] round_filter input=192 output=344
I1019 16:37:53.022137  9100 efficientnet_model.py:148] round_filter input=320 output=576
I1019 16:37:53.860046  9100 efficientnet_model.py:148] round_filter input=1280 output=2304
I1019 16:37:53.964131  9100 efficientnet_model.py:462] Building model efficientnet with params ModelConfig(width_coefficient=1.8, depth_coefficient=2.6, resolution=528, dropout_rate=0.5, blocks=(BlockConfig(input_filters=32, output_filters=16, kernel_size=3, num_repeat=1, expand_ratio=1, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=16, output_filters=24, kernel_size=3, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=24, output_filters=40, kernel_size=5, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=40, output_filters=80, kernel_size=3, num_repeat=3, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=80, output_filters=112, kernel_size=5, num_repeat=3, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=112, output_filters=192, kernel_size=5, num_repeat=4, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=192, output_filters=320, kernel_size=3, num_repeat=1, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise')), stem_base_filters=32, top_base_filters=1280, activation='simple_swish', batch_norm='default', bn_momentum=0.99, bn_epsilon=0.001, weight_decay=5e-06, drop_connect_rate=0.2, depth_divisor=8, min_depth=None, use_se=True, input_channels=3, num_classes=1000, model_name='efficientnet', rescale_input=False, data_format='channels_last', dtype='float32')
WARNING:tensorflow:From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py:312: SyncReplicasOptimizer.__init__ (from tensorflow.python.training.sync_replicas_optimizer) is deprecated and will be removed in a future version.
Instructions for updating:
The `SyncReplicaOptimizer` class is deprecated. For synchronous training, please use [Distribution Strategies](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute).
W1019 16:38:16.644356  9100 deprecation.py:323] From C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py:312: SyncReplicasOptimizer.__init__ (from tensorflow.python.training.sync_replicas_optimizer) is deprecated and will be removed in a future version.
Instructions for updating:
The `SyncReplicaOptimizer` class is deprecated. For synchronous training, please use [Distribution Strategies](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute).
INFO:tensorflow:SyncReplicasV2: replicas_to_aggregate=8; total_num_replicas=1
I1019 16:38:16.649864  9100 sync_replicas_optimizer.py:187] SyncReplicasV2: replicas_to_aggregate=8; total_num_replicas=1
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 392, in train
    train_config.load_all_detection_checkpoint_vars))
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\meta_architectures\ssd_meta_arch.py", line 1277, in restore_map
    return self._feature_extractor.restore_from_classification_checkpoint_fn(
AttributeError: 'SSDEfficientNetB6BiFPNKerasFeatureExtractor' object has no attribute 'restore_from_classification_checkpoint_fn'
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables/boolean_mask/GatherV2:0' shape=(None,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 415, in train
    saver=saver)  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\training\sync_replicas_optimizer.py", line 358, in apply_gradients
    return train_op  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 249, in wrapped
    error_in_function=error_in_function)
==================================
E1019 16:38:50.980139  9100 tf_should_use.py:90] ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables/boolean_mask/GatherV2:0' shape=(None,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 415, in train
    saver=saver)  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\training\sync_replicas_optimizer.py", line 358, in apply_gradients
    return train_op  File "C:\Users\Admin\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 249, in wrapped
    error_in_function=error_in_function)
==================================**

Is this a error? Please tell me how to fix it.
                          -  I tried to replace **faster_rcnn_inception_v2_pets.config** turn to **efficientdet_d7_coco17.config**  ( efficientdet_d7_coco17.config is the **pipeline.config** in **efficientdet_d7_coco17_tpu-32**) and I also edit inside **efficientdet_d7_coco17.config** , 
THEY ARE:
            - fine_tune_checkpoint: "C:\tensorflow1\models\research\object_detection\efficientdet_d7_coco17_tpu- 
32\checkpoint\ckpt-0.ckpt"
        - train_input_reader: {
label_map_path: "C:/tensorflow1/models/research/object_detection/training/labelmap.pbtxt"
         -tf_record_input_reader {
input_path: "C:/tensorflow1/models/research/object_detection/train.record"
          -label_map_path: "C:/tensorflow1/models/research/object_detection/training/labelmap.pbtxt"
          -input_path: "C:/tensorflow1/models/research/object_detection/test.record"

Plz help me, i can't find the answer Love

**Comment by Jayden0211** [comment]
same problem. plz, help!
