### ISSUE TITLE
How to start training from a checkpoint on Tensorflow-2 Faster R-CNN with Resnet-101 

### ISSUE THREAD

**Issue by urieli** [tensorflow/models#9402]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

When I attempt to train from a previous checkpoint, I get two errors, "AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program" and "NameError: name 'open' is not defined"

## 3. Steps to reproduce

I'm building a network from scratch using Kaggle, Tensorflow 2, and the Faster R-CNN with Resnet-101 network.

The kaggle commands are:
```shell
!git clone https://github.com/tensorflow/models.git
import os
os.environ['PYTHONPATH'] += ":/kaggle/working/models/research"
%cd /kaggle/working/models/research

# Compile protos.
!protoc object_detection/protos/*.proto --python_out=.
# Install TensorFlow Object Detection API.
!cp object_detection/packages/tf2/setup.py .
!pip install .

PIPELINE_CONFIG_PATH='/kaggle/input/my-project/kaggle_faster_rcnn_resnet101.config'
MODEL_DIR='/kaggle/working/my-models'

!mkdir {MODEL_DIR}
!mkdir {MODEL_DIR}/train

!python /kaggle/working/models/research/object_detection/model_main_tf2.py \
    --pipeline_config_path='{PIPELINE_CONFIG_PATH}' \
    --model_dir='{MODEL_DIR}' \
    --alsologtostderr \
    --num_train_steps=5000 \
    --sample_1_of_n_eval_examples=1 \
    --num_eval_steps=50
```

When I trained without a checkpoint, everything seems to work correctly.

After this, I wanted to run a new training, this time starting at the last checkpoint created by the original train.

I changed my configuration to start at a checkpoint as follows:
```
train_config: {
  ...
  fine_tune_checkpoint_version: V2
  fine_tune_checkpoint: "/path-to-checkpoints/ckpt-6"
  fine_tune_checkpoint_type: "classification"
}
```
I got the following two errors:
```
Traceback (most recent call last):
  File "/kaggle/working/models/research/object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/kaggle/working/models/research/object_detection/model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/kaggle/working/models/research/object_detection/model_lib_v2.py", line 569, in train_loop
    unpad_groundtruth_tensors)
  File "/kaggle/working/models/research/object_detection/model_lib_v2.py", line 383, in load_fine_tune_checkpoint
    ckpt.restore(checkpoint_path).assert_existing_objects_matched()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 791, in assert_existing_objects_matched
    (list(unused_python_objects),))
AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program: [SyncOnReadVariable:{
  0: <tf.Variable 'conv5_block1_2_bn/moving_variance:0' shape=(512,) dtype=float32, numpy=
```
And
```
Exception ignored in: <function _CheckpointRestoreCoordinatorDeleter.__del__ at 0x7f25cbe81e60>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 150, in __del__
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/tf_logging.py", line 178, in warning
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1390, in warning
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1514, in _log
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1524, in handle
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 894, in handle
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1126, in emit
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1116, in _open
NameError: name 'open' is not defined
```

## 4. Expected behavior

I expect new checkpoints to be added after the current checkpoint 6.

## 5. Additional context

Full log here: 
[TensorFlow2CheckpointsOutput.log](https://github.com/tensorflow/models/files/5414912/TensorFlow2CheckpointsOutput.log)

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kaggle.
Linux distribution specified as
```
Linux 247bf6b79242 5.4.49+ #1 SMP Sun Oct 18 19:43:35 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-0-gb36436b087 2.3.0
- Python version: Python 3.7.6
- CUDA/cuDNN version: 10.2
- GPU model and memory:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    28W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by BouweCeunen** [comment]
Any progress on this?

**Comment by urieli** [comment]
Thanks @BouweCeunen  that did the trick:
Therefore, in `/kaggle/input/my-project/kaggle_faster_rcnn_resnet101.config` file I replaced:
```
fine_tune_checkpoint_type: "classification"
```
With:
```
fine_tune_checkpoint_type: "detection"
```
