### ISSUE TITLE
model_builder_tf2_test.py test file fails 

### ISSUE THREAD

**Issue by shehroz010** [tensorflow/models#9412]
I installed the tf od api as per the documentation and everything regarding the setup runs without error. But when i try to run the model_builder_tf2_test.py file to test my installation it fails at last step. Below is the error which I get. I even tried to create a fresh env but still it fails at the same step. 
M using Linux Ubuntu 18.04.4 as CLI.

`
ERROR: test_create_center_net_model (__main__.ModelBuilderTF2Test)
ModelBuilderTF2Test.test_create_center_net_model
Test building a CenterNet model from proto txt.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 224, in test_create_center_net_model
    model = model_builder.build(config, is_training=True)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 1090, in build
    add_summaries)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 1040, in _build_center_net_model
    compute_heatmap_sparse=center_net_config.compute_heatmap_sparse)
AttributeError: compute_heatmap_sparse
`

**Comment by saikumarchalla** [comment]
@shehroz010  Have you installed  OD API  using this [link](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html)? Can you confirm it?. 

Also, Please check this [link](https://towardsdatascience.com/how-to-install-tensorflow-2-object-detection-api-on-windows-2eef9b7ae869) where they have provided alternative approach to test the installation. Thanks!

**Comment by shehroz010** [comment]
@saikumarchalla yes this was the only link I installed it through. 
The other link you provided is for windows installation. As you can see in my prblm statement I have already mentioned that m using a Linux (Ubuntu 18.04) not windows. I have a windows machine and it runs perfectly on windows but i have issue on linux.

**Comment by saikumarchalla** [comment]
@shehroz010   I tried to install TF OD API and  it was installed properly on colab. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/62ee67712b1f59687a7c838ae883afdb/models_repo.ipynb).

Could you please try to install again as per the documentation provided above and let us know if you are facing the issue still. Thanks!

**Comment by shehroz010** [comment]
It is still failing on my linux but on windows machine it works perfectly. There is one more thing, even the test fails, still when i try to run the training it runs normally.
