### ISSUE TITLE
loss function for the prado model

### ISSUE THREAD

**Issue by Alex-Arsenal** [tensorflow/models#9416]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [yes] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [yes] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/sequence_projection

## 2. Describe the bug

Rank mismatch: Rank of labels (received 2) should equal rank of logits minus 1 (received2)

## 3. Steps to reproduce

I tried to run prado model on my own single label dataset. I created a text file and change the multilabel option into single, but after I run this, it shows the rank mismatch. I checked the code, it seems like the loss function requires a mismatched shape for input values. 

## 4. Expected behavior

It expected to train the data.

## 6. System information

- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): 2.3
- TensorFlow version (use command below): 2.3
- Python version: 3.6
- Bazel version (if compiling from source): 3.5

Also, I tried to change the multilabel into true, and it works. But when I tried to evaluated my data, it takes long long time and without any outcomes. I am not sure what happened in here.

**Comment by prabhukaliamoorthi** [comment]
Can you reduce the batch size to something very small like 4 and try to check if it trains. We train the model on TPU or GPU with large batch sizes. If you are training on CPU it would seem like the trainer is doing nothing.

The result of the model is expected to be [batch_size, num_labels] for both multi label and muticlass problems. For multiclass we do arg max over labels dimesnion to get the class. For multilabel we check the sigmoid value to be above threshold to get a binary classification for all labels. Hopefully that clarifies.

We are also in the process of migrating over to Keras version of PRADO model with TF1 based trainer.

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi When keras + tf1 based trainer will release?

**Comment by Alex-Arsenal** [comment]
I tried a smaller batch size but it did not work either. I thought this might be something related to my data inputing problem. I used a dataset from a csv file. So I cannot use the tfds.load function. I tried to use tf.data.experimental.make_csv_dataset instead. But the result is slightly different. And when I sent this into the estimator function, the model learns nothing(I just change the loss function to softmax_cross_entropy and it worked).

**Comment by prabhukaliamoorthi** [comment]
The keras based version is already available. It is under the name seq_flow_lite. What is open sourced is just a demo app and the model. You'll need some work to adapt it for your problem. This includes things like
1) Adapting the input function
2) The loss
3) Metrics

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi @thunderfyc Thanks for keras based version of this model, I was waiting for this.
I am facing problem in evaluating this model for single example after training.
In `export_to_tflite.py` I am trying to pass example input string to placeholder and try to run `session.run(logits,feed_dict={text:[example_string]})` as follows:
![image](https://user-images.githubusercontent.com/32617984/98661859-052a5580-236d-11eb-8583-23fd3f18f339.png)
 

but I got following error

`2020-11-10 09:37:15.807473: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Missing 0-th output from {{node encoder/attention_pool_reduce/ExpectedValueOp}}
  (1) Internal: Missing 0-th output from {{node encoder/attention_pool_reduce/ExpectedValueOp}}
	 [[encoder/attention_pool_reduce_1/ExpectedValueOp/_41]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/58ff60c74b862561db406f51771cebf5/execroot/tensorflow_models_seq_flow_lite/bazel-out/k8-opt/bin/export_to_tflite.runfiles/tensorflow_models_seq_flow_lite/export_to_tflite.py", line 69, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/58ff60c74b862561db406f51771cebf5/execroot/tensorflow_models_seq_flow_lite/bazel-out/k8-opt/bin/export_to_tflite.runfiles/tensorflow_models_seq_flow_lite/export_to_tflite.py", line 58, in main
    print(session.run(logits,feed_dict={text:['Those fucking nights']}))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Missing 0-th output from node encoder/attention_pool_reduce/ExpectedValueOp (defined at <string>:144) 
  (1) Internal: Missing 0-th output from node encoder/attention_pool_reduce/ExpectedValueOp (defined at <string>:144) 
	 [[encoder/attention_pool_reduce_1/ExpectedValueOp/_41]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node encoder/attention_pool_reduce/ExpectedValueOp:
 encoder/attention_pool_reduce/padded_masked_var_len_conv/Reshape_1 (defined at /root/.cache/bazel/_bazel_root/58ff60c74b862561db406f51771cebf5/execroot/tensorflow_models_seq_flow_lite/bazel-out/k8-opt/bin/export_to_tflite.runfiles/tensorflow_models_seq_flow_lite/layers/conv_layers.py:88)

Input Source operations connected to node encoder/attention_pool_reduce/ExpectedValueOp:
 encoder/attention_pool_reduce/padded_masked_var_len_conv/Reshape_1 (defined at /root/.cache/bazel/_bazel_root/58ff60c74b862561db406f51771cebf5/execroot/tensorflow_models_seq_flow_lite/bazel-out/k8-opt/bin/export_to_tflite.runfiles/tensorflow_models_seq_flow_lite/layers/conv_layers.py:88)`


Please help me to solve this error.. as only after testing on single example I can think about deploying it on android.
Thanks!

**Comment by prabhukaliamoorthi** [comment]
You can create the graph in 4 modes, train/eval/predict/tflite. The first 3 will work with tensorflow meaning you can do sess.run with it. The last one works just with TFLite. Also the first 2 supports batching and the last 2 are batch 1 zero padded inference.
 Below is a snippet for TFLite inference.
        tflite_fb = tflite_utils.generate_tflite(session, graph, [input_tensor],
                                                 [infer_result])
        interpreter = tflite_utils.InterpreterWithCustomOps(
            model_content=tflite_fb,
            custom_op_registerers=[registerer.CustomOps])

    input_details = interpreter.get_input_details()
    interpreter.resize_tensor_input(input_details[0]['index'], values.shape)
    interpreter.allocate_tensors()
    scale, zero_point = input_details[0]['quantization']
    values = (values / scale) + zero_point
    interpreter.set_tensor(input_details[0]['index'], values.astype('uint8'))
    interpreter.invoke()
    output_details = interpreter.get_output_details()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    scale, zero_point = output_details[0]['quantization']
    return (output_data.astype('float') - zero_point) * scale


The only thing missing is figuring out how to install the custom ops registerer.CustomOps. Hopefully you can figure it out. Otherwise we'll add it in the next week or 2.

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi Thanks for your reply.
But I couldn't find 'predict' mode in `trainer.py` file as follows:
![image](https://user-images.githubusercontent.com/32617984/98693246-0de35180-2396-11eb-823c-a7dc7738026a.png)
There is only train/train_and_eval/eval mode in runner_mode argument.

And if predict mode is present in another file then can you please share the snippet to build graph and predict the logits for single example using 'predict' mode?

I have one more query...Is there any way to predict logits from 'graph.pbtxt' or model checkpoints? If yes, can you tell me output and input node name of meta_graph?
Thanks!

**Comment by prabhukaliamoorthi** [comment]
I am talking about base_layer.TFLITE mode. That is used to generate the TFLite model. Please see line 10/11 in export_to_tflite.

**Comment by prabhukaliamoorthi** [comment]
If you want to do a sess run you can change base_layer.TFLITE to base_layer.PREDICT in the file when creating the projection layer and encoder. In your first snippet this would change line 10/11. This would allow you to et the logits for the inference/predict graph.

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi  Thanks for your reply.
I changed base_layer.TFLITE to base_layer.PREDICT as you said but got this **error** as follows:

W1111 04:59:06.686723 140608135063424 lite.py:1311] Please consider switching to the new converter by setting experimental_new_converter=True. The old converter (TOCO) is deprecated.
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/58ff60c74b862561db406f51771cebf5/execroot/tensorflow_models_seq_flow_lite/bazel-out/k8-opt/bin/export_to_tflite.runfiles/tensorflow_models_seq_flow_lite/export_to_tflite.py", line 69, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/58ff60c74b862561db406f51771cebf5/execroot/tensorflow_models_seq_flow_lite/bazel-out/k8-opt/bin/export_to_tflite.runfiles/tensorflow_models_seq_flow_lite/export_to_tflite.py", line 62, in main
    tflite_fb = tflite_utils.generate_tflite(session, graph, [text], [logits])
  File "/root/.cache/bazel/_bazel_root/58ff60c74b862561db406f51771cebf5/execroot/tensorflow_models_seq_flow_lite/bazel-out/k8-opt/bin/export_to_tflite.runfiles/tensorflow_models_seq_flow_lite/utils/tflite_utils.py", line 80, in generate_tflite
    return converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 1970, in convert
    return super(TFLiteConverter, self).convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 1330, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 574, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py", line 279, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.

Warning following above error-
Constant array encoder/base_q_dense_var_len/weight/transpose lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.

How can I resolve this error and warning?

Thanks!

**Comment by prabhukaliamoorthi** [comment]
tflite.fb is a flatbuffer and yes you can deploy it on Android. You can use the below code snippet to invoke the model in python, you can do the same with TFLite interpreter (C library), you will need to install the custom op handlers for the model. PRADO uses ExpectedValueOp handler

  def invoke_single_inference_tflite(self, interpreter, values):
    input_details = interpreter.get_input_details()
    interpreter.allocate_tensors()
    interpreter.set_tensor(input_details[0]['index'], np.array(values))
    interpreter.invoke()
    output_details = interpreter.get_output_details()

    def get_output(output):
      output_data = interpreter.get_tensor(output['index'])
      scale, zero_point = output['quantization']
      return (output_data.astype('float') - zero_point) * scale

    return [get_output(output) for output in output_details]

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi Thanks for your reply but this code snippet will need custom op handlers as you said earlier which I don't know how can I install this and I am not getting what interpreter and values are in `invoke_single_inference_tflite` function and what is the use of `get_output` function?

Is there any way to invoke model from `graph.pbtxt` or `graph.pb` or model checkpoints which saved after training of model?
Can you share the code snippet for that?
Thanks!

**Comment by yugaljain1999** [comment]
> If you want to do a sess run you can change base_layer.TFLITE to base_layer.PREDICT in the file when creating the projection layer and encoder. In your first snippet this would change line 10/11. This would allow you to et the logits for the inference/predict graph.

By changing base_layer.TFLITE to base_layer.PREDICT, I got logits but Is there any way to save model as well during base_layer.PREDICT mode instead of base_layer.TFLITE mode?

**Comment by prabhukaliamoorthi** [comment]
Yes you can. You can create the graph with base_layer.PREDICT and save the frozen graph. seq_flow_lite/utils/tflite_utils.py first creates tensorflow proto in line 57. You can save it and invoke tensorflow inference like sess.run

**Comment by yugaljain1999** [comment]
> Yes you can. You can create the graph with base_layer.PREDICT and save the frozen graph. seq_flow_lite/utils/tflite_utils.py first creates tensorflow proto in line 57. You can save it and invoke tensorflow inference like sess.run

But when I change mode from TFLITE to PREDICT it shows an error while saving frozen graph, but if I use previous mode then it easily save frozen flat buffer model..
How can I get rid of error?

**Comment by yugaljain1999** [comment]
> @prabhukaliamoorthi Thanks for your reply but this code snippet will need custom op handlers as you said earlier which I don't know how can I install this and I am not getting what interpreter and values are in `invoke_single_inference_tflite` function and what is the use of `get_output` function?
> 
> Is there any way to invoke model from `graph.pbtxt` or `graph.pb` or model checkpoints which saved after training of model?
> Can you share the code snippet for that?
> Thanks!

@prabhukaliamoorthi Please reply to last question of this comment.
Thanks!

**Comment by prabhukaliamoorthi** [comment]
You can, if you create with base_layer.PREDICT, you can do sess.run with the input text and evaluate the output tensor just like in your original example. You can skip the tflite generation call sinc you don't need it. Once you have the graph in the session saving it as a graph.pb and loading it again and doing sess.run is all standard tensorflow. You should be able to find pointers in the web.

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi Thanks for your reply
I have to change base_layer.PREDICT defined in `export_to_tflite.py` or somewhere else too?
I tried again loading `graph.pb` but unable to run sess.run after loading `graph.pb`.. It shows an error-

`FailedPreconditionError: Error while reading resource variable encoder/base_q_dense/batch_normalization/mva_variance from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/encoder/base_q_dense/batch_normalization/mva_variance)
	 [[{{node encoder/base_q_dense/batch_normalization/Read_1/ReadVariableOp}}]]`

How can I resolve this error?
Thanks

**Comment by prabhukaliamoorthi** [comment]
You will need to restore the variables from the checkpoint. So you should do the following before the sess.run

def main(_):
  runner_config = load_runner_config()
  model_config = runner_config["model_config"]
  rel_module_path = "google3.third_party.tensorflow_models.seq_flow_lite."
  model = importlib.import_module(rel_module_path + runner_config["name"])
  with tf.Graph().as_default() as graph:
    with tf.Session(graph=graph) as session:
      text = tf.placeholder(tf.string, shape=[1], name="Input")
      prxlayer = projection_layers.ProjectionLayer(model_config,
                                                   base_layers.TFLITE)
      encoder = model.Encoder(model_config, base_layers.TFLITE)
      projection, seq_lengh = prxlayer(text)
      logits = encoder(projection, seq_lengh)

      session.run(tf.global_variables_initializer())
      session.run(tf.local_variables_initializer())
      saver = tf.train.Saver()
      saver.restore(session, tf.train.latest_checkpoint(FLAGS.output_dir))

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi why didn't you use `base_layers.PREDICT` here as per your previous responses?
Thanks!

**Comment by prabhukaliamoorthi** [comment]
uh copy paste error, it should be base_layers.PREDICT

**Comment by yugaljain1999** [comment]
Okay so I have to write above code snippet in `export_to_tflite.py` or `tf_utils.py` to save graph.pb model?

**Comment by prabhukaliamoorthi** [comment]
export_to_tflite.py

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi  I am able to invoke model from `graph.pb` but only in bazel environment.
But I wanted to invoke model from `graph.pb` from somewhere else where I just imported tensorflow and it throws an error out there as follows-
![image](https://user-images.githubusercontent.com/32617984/98936689-4ce6e380-250b-11eb-936b-a5588532ed3a.png)
![image](https://user-images.githubusercontent.com/32617984/98936893-a3542200-250b-11eb-9141-570a66b1eae6.png)

Can you help me to resolve this error?

I have one more query- Where should I place generated `tflite.fb` in third party folders to deploy model in android? Should I need custom ops register while deploying model in android?

Thanks!

**Comment by prabhukaliamoorthi** [comment]
You need to link the below two libraries in the bazel BUILD rule as a dependency.

        "seq_flow_lite/tf_ops:sequence_string_projection_op",
        "seq_flow_lite/tf_ops:sequence_string_projection_op_py",

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi There are four folders of bazel BUILD i.e. bazel-in,bazel-out,bazel-seq_flow_lite generated during training, In which folder should I link those two libraries which you mentioned above?

As per my second question I was asking about how to use `tflite.fb` and link to android as instructions and commands to deploy tflite.fb model isn't present in README? Can you please tell me the steps to be followed to deploy this 'tflite.fb' on android?

Thanks !

**Comment by prabhukaliamoorthi** [comment]
@thunderfyc wrote a colab to demo the TFLite model. @thunderfyc  Can you fix the colab/README?

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi Can you please answer my first question in my recent comment?
Thanks

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi Can you please answer my first question in my recent comment?
Thanks

**Comment by yugaljain1999** [comment]
> You can create the graph in 4 modes, train/eval/predict/tflite. The first 3 will work with tensorflow meaning you can do sess.run with it. The last one works just with TFLite. Also the first 2 supports batching and the last 2 are batch 1 zero padded inference.
> Below is a snippet for TFLite inference.
> tflite_fb = tflite_utils.generate_tflite(session, graph, [input_tensor],
> [infer_result])
> interpreter = tflite_utils.InterpreterWithCustomOps(
> model_content=tflite_fb,
> custom_op_registerers=[registerer.CustomOps])
> 
> ```
> input_details = interpreter.get_input_details()
> interpreter.resize_tensor_input(input_details[0]['index'], values.shape)
> interpreter.allocate_tensors()
> scale, zero_point = input_details[0]['quantization']
> values = (values / scale) + zero_point
> interpreter.set_tensor(input_details[0]['index'], values.astype('uint8'))
> interpreter.invoke()
> output_details = interpreter.get_output_details()
> output_data = interpreter.get_tensor(output_details[0]['index'])
> scale, zero_point = output_details[0]['quantization']
> return (output_data.astype('float') - zero_point) * scale
> ```
> 
> The only thing missing is figuring out how to install the custom ops registerer.CustomOps. Hopefully you can figure it out. Otherwise we'll add it in the next week or 2.

@prabhukaliamoorthi What is the datatype of `values` in `interpreter.resize_tensor_input(input_details[0]['index'],values.shape)`?
Is it just list of strings or it is projected vectors?

**Comment by prabhukaliamoorthi** [comment]
it is bytes representantion that contains the string in python.

**Comment by yugaljain1999** [comment]
> @thunderfyc wrote a colab to demo the TFLite model. @thunderfyc Can you fix the colab/README?

@prabhukaliamoorthi  I couldn't find any colab to demo TFLite model on `seq_flow_lite` github.. Can you share the colab to demo TFLite model?

Thanks

**Comment by prabhukaliamoorthi** [comment]
We'll add this in a few days.

**Comment by yugaljain1999** [comment]
okay,thanks

**Comment by yugaljain1999** [comment]
> > @thunderfyc wrote a colab to demo the TFLite model. @thunderfyc Can you fix the colab/README?
> 
> @prabhukaliamoorthi I couldn't find any colab to demo TFLite model on `seq_flow_lite` github.. Can you share the colab to demo TFLite model?
> 
> Thanks


@prabhukaliamoorthi When it will add as it's been a week when you informed?

**Comment by prabhukaliamoorthi** [comment]
Can you check seq_flow_lite/demo/prado:prado_tflite_example?

**Comment by prabhukaliamoorthi** [comment]
Looks like the code is not synced. Its already added to the repo. We'll try to have it synced today

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi it would be really great. Waiting desperately.

**Comment by prabhukaliamoorthi** [comment]
I create a pr https://github.com/tensorflow/models/pull/9500 its not merged yet, but maybe it will unblock you. There is a demo app in it.

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi Thanks for your PR, but I didn't get how can I run that .cc file in python with tflite.fb model? Can you please tell me how should I run files in `demo/prado` folder?

**Comment by prabhukaliamoorthi** [comment]
it is just a c demo code, you can link it with your application.

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi Okay, so can I link it with an Android or flutter application?

**Comment by prabhukaliamoorthi** [comment]
Yes, you may need jni if you want to use it from Android. You can look into TFLite support library which may have java bindings for TFLite. I don't know about flutter, but I believe it should be possible.

**Comment by yugaljain1999** [comment]
@prabhukaliamoorthi  Thanks a lot, I will look into it.
