### ISSUE TITLE
module 'tensorflow.python.feature_column.feature_column_v2' has no attribute '_BaseFeaturesLayer'

### ISSUE THREAD

**Issue by atomrun39** [tensorflow/models#9419]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ yes ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ yes ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection

## 2. Describe the bug

Error when running model_main.py: AttributeError: module 'tensorflow.python.feature_column.feature_column_v2' has no attribute '_BaseFeaturesLayer'

## 3. Steps to reproduce
running:
python model_main.py --pipeline_config_path=training/centernet_resnet50_v1_fpn_512x512.config --model_dir=training --num_train_steps=90000 --num_eval_steps=9000 --alsologtostderr
error:
Traceback (most recent call last):
  File "model_main.py", line 108, in <module>
    tf.app.run()
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main.py", line 62, in main
    config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir)
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import dense_features
  File "/home/wei16/anaconda3/envs/tf2.2/lib/python3.6/site-packages/tensorflow/python/feature_column/dense_features.py", line 30, in <module>
    class DenseFeatures(fc._BaseFeaturesLayer):  # pylint: disable=protected-access
AttributeError: module 'tensorflow.python.feature_column.feature_column_v2' has no attribute '_BaseFeaturesLayer'

## 4. System information

- Linux Ubuntu 18.04
- tensorflow--gpu==2.2.0 
- Python version: 3.6
- CUDA : 10.1
- cuDNN : 7.6.5

**Comment by ravikyram** [comment]
@atomrun39 

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!
