### ISSUE TITLE
Premature end of JPEG file

### ISSUE THREAD

**Issue by shehroz010** [tensorflow/models#9424]
OS - Ubuntu 18.04 as CLI
TF - TF GPU 2.3.1

I was training a ssd_resnet50 model for Object Detection. But when i started the training after few steps i got this error. I understand this is because of corrupted image but how do I fix this ? Please help me out.

**TraceBack:**

```
2020-10-28 05:57:57.511499: E tensorflow/core/lib/jpeg/jpeg_mem.cc:323] Premature end of JPEG data. Stopped at line 1214/2593
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/shehroz/tf/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/shehroz/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/home/shehroz/tf/lib/python3.7/site-packages/object_detection/model_lib_v2.py", line 639, in train_loop
    loss = _dist_train_step(train_input_iter)
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/shehroz/tf/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Invalid JPEG data or crop window, data size 179702
         [[{{node case/cond/else/_10/case/cond/cond_jpeg/then/_104/case/cond/cond_jpeg/DecodeJpeg}}]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
         [[IteratorGetNext]] [Op:__inference__dist_train_step_35302]

Function call stack:
_dist_train_step
```

**Comment by saikumarchalla** [comment]
@shehroz010  Please  have a look at this [issue](https://github.com/tensorflow/tpu/issues/455)  and let  us know if it helps. Thanks!

**Comment by saikumarchalla** [comment]
@shehroz010 Any update on this?. Please  go ahead and close the issue if it was resolved for you.Thanks!

**Comment by saikumarchalla** [comment]
@shehroz010 Closing this issue due to lack of recent activity. Please feel free to re-open the issue if you have any concern. Thanks!
