### ISSUE TITLE
No Module named lvis 

### ISSUE THREAD

**Issue by Artiintern** [tensorflow/models#9431]
while training the model getting this error..
The code was running fine yesterday. 

**File"/content/models/research/object_detection/metrics/lvis_evaluation.py", line 23, in <module>
    from lvis import results as lvis_results
ModuleNotFoundError: No module named 'lvis'**

**Comment by ravikyram** [comment]
@Artiintern 

Please install `!pip install lvis`.
Please, see the colab [link](https://colab.research.google.com/gist/ravikyram/e4a34b349ad8dfe46a3377a2b8c6d0dd/untitled102.ipynb?authuser=1) for your reference. Please, verify once and close the issue. Thanks!

**Comment by Artiintern** [comment]
Yes, Done that.
Resolved.
Thank you very much

**Comment by ravikyram** [comment]
@Artiintern 

I am closing this thread as your issue was resolved. Thanks!

**Comment by Obenhelen** [comment]
I have similar issue when training my model. 
this is the error I get.
Traceback (most recent call last):
  File "C:\Users\OBENCECILIA\Desktop\RealTimeObjectDetection\Tensorflow\models\research\object_detection\model_main_tf2.py", line 31, in <module>
    import model_lib_v2
  File "C:\Users\OBENCECILIA\Desktop\RealTimeObjectDetection\Tensorflow\models\research\object_detection\model_lib_v2.py", line 29, in <module>
    import eval_util
  File "C:\Users\OBENCECILIA\Desktop\RealTimeObjectDetection\Tensorflow\models\research\object_detection\eval_util.py", line 34, in <module>
    import lvis_evaluation
ModuleNotFoundError: No module named 'lvis_evaluation'

**Comment by Obenhelen** [comment]
i tried pip install lvis_evaluation  but i get another error:
ERROR: Could not find a version that satisfies the requirement lvis_evaluation (from versions: none)
ERROR: No matching distribution found for lvis_evaluation
thanks in advance
