### ISSUE TITLE
object_detection/export_tflite_ssd_graph.py failed with ssd_mobilenet_v1

### ISSUE THREAD

**Issue by guomingjin** [tensorflow/models#9442]
I am struggling to convert custom ssd mobilenet to .tflite, I just tried to test with the model first, but it doesn't seem to work correctly. I am using Tensorflow 1.15(Anaconda, Python 3.6) on Windows 10.
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz

I followed this: 
https://gist.github.com/apivovarov/eff80275d0f72e4582c105921919b852

Logs
```
(object_detection) E:\Project\ObjectDetection\models\research>python object_detection/export_tflite_ssd_graph.py --pipeline_config_path=./ssd_mobilenet_v1_coco_2018_01_28/pipeline.config --trained_checkpoint_prefix=./ssd_mobilenet_v1_coco_2018_01_28/model.ckpt --output_directory=tmp/tflite_graph --add_postprocessing_op=true
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:193: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W1102 18:07:27.781878 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:193: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:237: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1102 18:07:27.783873 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:237: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\meta_architectures\ssd_meta_arch.py:589: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W1102 18:07:27.789879 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\meta_architectures\ssd_meta_arch.py:589: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\meta_architectures\ssd_meta_arch.py:597: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W1102 18:07:27.790871 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\meta_architectures\ssd_meta_arch.py:597: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tf_slim-1.1.0-py3.6.egg\tf_slim\layers\layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W1102 18:07:27.793871 15964 deprecation.py:323] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tf_slim-1.1.0-py3.6.egg\tf_slim\layers\layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\core\anchor_generator.py:171: The name tf.assert_equal is deprecated. Please use tf.compat.v1.assert_equal instead.

W1102 18:07:29.505894 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\core\anchor_generator.py:171: The name tf.assert_equal is deprecated. Please use tf.compat.v1.assert_equal instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\predictors\convolutional_box_predictor.py:150: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W1102 18:07:29.522878 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\predictors\convolutional_box_predictor.py:150: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:depth of additional conv before box predictor: 0
I1102 18:07:29.524873 15964 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1102 18:07:29.567879 15964 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1102 18:07:29.611879 15964 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1102 18:07:29.655879 15964 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1102 18:07:29.699878 15964 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I1102 18:07:29.769874 15964 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:52: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W1102 18:07:29.847879 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:52: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:267: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

W1102 18:07:30.002777 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:267: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:292: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W1102 18:07:30.020791 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:292: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:295: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1102 18:07:30.175776 15964 module_wrapper.py:139] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py:295: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\tools\freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W1102 18:07:30.230777 15964 deprecation.py:323] From C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\tools\freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./ssd_mobilenet_v1_coco_2018_01_28/model.ckpt
I1102 18:07:30.829770 15964 saver.py:1284] Restoring parameters from ./ssd_mobilenet_v1_coco_2018_01_28/model.ckpt
2020-11-02 18:07:31.135687: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key FeatureExtractor/MobilenetV1/Conv2d_0/biases not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key FeatureExtractor/MobilenetV1/Conv2d_0/biases not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key FeatureExtractor/MobilenetV1/Conv2d_0/biases not found in checkpoint
         [[node save/RestoreV2 (defined at C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "object_detection/export_tflite_ssd_graph.py", line 144, in <module>
    tf.app.run(main)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_tflite_ssd_graph.py", line 140, in main
    FLAGS.max_classes_per_detection, use_regular_nms=FLAGS.use_regular_nms)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py", line 292, in export_tflite_graph
    saver = tf.train.Saver(**saver_kwargs)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1695, in restore_v2
    name=name)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/export_tflite_ssd_graph.py", line 144, in <module>
    tf.app.run(main)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_tflite_ssd_graph.py", line 140, in main
    FLAGS.max_classes_per_detection, use_regular_nms=FLAGS.use_regular_nms)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py", line 306, in export_tflite_graph
    initializer_nodes='')
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\tools\freeze_graph.py", line 151, in freeze_graph_with_def_protos
    saver.restore(sess, input_checkpoint)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key FeatureExtractor/MobilenetV1/Conv2d_0/biases not found in checkpoint
         [[node save/RestoreV2 (defined at C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "object_detection/export_tflite_ssd_graph.py", line 144, in <module>
    tf.app.run(main)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_tflite_ssd_graph.py", line 140, in main
    FLAGS.max_classes_per_detection, use_regular_nms=FLAGS.use_regular_nms)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\export_tflite_ssd_graph_lib.py", line 292, in export_tflite_graph
    saver = tf.train.Saver(**saver_kwargs)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1695, in restore_v2
    name=name)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\KKM\Anaconda3\envs\object_detection\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

I really appreciate it if anyone can help me out.

**Comment by ravikyram** [comment]
@guomingjin 

Please, refer #9118 and see if it helps you. Thanks!

**Comment by guomingjin** [comment]
@ravikyram 

Thanks for your reply. I want to convert a custom mobilenet into tflite format in the end. But the generation of a frozen graph compatible with tflite converter was failed even with a base model. I can't figure out what the reason is and spent several days.
