### ISSUE TITLE
Error using export_inference_graph.py

### ISSUE THREAD

**Issue by abrahamperz** [tensorflow/models#9454]
System information

 - OS Plataform: Windows 10
 - TensorFlow installed from anaconda:
 - TensorFlow version :1.15
 - Python version: python 3.7.0
 - GPU: I tried google colab and my computer with put GPU

Execute Command 

  `  python export_inference_graph.py --input_type=image_tensor --pipeline_config_path=training/ssd_mobilenet_v1_pets.config --trained_checkpoint_prefix=training/model.ckpt-104 --output_directory=new`

Error :
```

    Traceback (most recent call last):
      File "export_inference_graph.py", line 162, in <module>
        tf.app.run()
      File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
        _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
      File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
        _run_main(main, args)
      File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
        sys.exit(main(argv))
      File "export_inference_graph.py", line 121, in main
        raise ValueError('You must supply the path to save to with --output_file')
    ValueError: You must supply the path to save to with --output_file
```

I am using export_inference_graph.py that is in the following link
https://github.com/tensorflow/models/tree/master/research/object_detection

  ```
  from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function
    import os
    
    import tensorflow.compat.v1 as tf
    from tensorflow.contrib import quantize as contrib_quantize
    
    
    from tensorflow.python.platform import gfile
    from datasets import dataset_factory
    from nets import nets_factory
    
    
    tf.app.flags.DEFINE_string(
        'model_name', 'inception_v3', 'The name of the architecture to save.')
    
    tf.app.flags.DEFINE_boolean(
        'is_training', False,
        'Whether to save out a training-focused version of the model.')
    
    tf.app.flags.DEFINE_integer(
        'image_size', None,
        'The image size to use, otherwise use the model default_image_size.')
    
    tf.app.flags.DEFINE_integer(
        'batch_size', None,
        'Batch size for the exported model. Defaulted to "None" so batch size can '
        'be specified at model runtime.')
    
    tf.app.flags.DEFINE_string('dataset_name', 'imagenet',
                               'The name of the dataset to use with the model.')
    
    tf.app.flags.DEFINE_integer(
        'labels_offset', 0,
        'An offset for the labels in the dataset. This flag is primarily used to '
        'evaluate the VGG and ResNet architectures which do not use a background '
        'class for the ImageNet dataset.')
    
    tf.app.flags.DEFINE_string(
        'output_file', '', 'Where to save the resulting file to.')
    
    tf.app.flags.DEFINE_string(
        'dataset_dir', '', 'Directory to save intermediate dataset files to')
    
    tf.app.flags.DEFINE_bool(
        'quantize', False, 'whether to use quantized graph or not.')
    
    tf.app.flags.DEFINE_bool(
        'is_video_model', False, 'whether to use 5-D inputs for video model.')
    
    tf.app.flags.DEFINE_integer(
        'num_frames', None,
        'The number of frames to use. Only used if is_video_model is True.')
    
    tf.app.flags.DEFINE_bool('write_text_graphdef', False,
                             'Whether to write a text version of graphdef.')
    
    tf.app.flags.DEFINE_bool('use_grayscale', False,
                             'Whether to convert input images to grayscale.')
    
    FLAGS = tf.app.flags.FLAGS
    
    
    def main(_):
      if FLAGS.is_video_model and not FLAGS.num_frames:
        raise ValueError(
            'Number of frames must be specified for video models with --num_frames')
      tf.logging.set_verbosity(tf.logging.INFO)
      with tf.Graph().as_default() as graph:
        dataset = dataset_factory.get_dataset(FLAGS.dataset_name, 'train',
                                              FLAGS.dataset_dir)
        network_fn = nets_factory.get_network_fn(
            FLAGS.model_name,
            num_classes=(dataset.num_classes - FLAGS.labels_offset),
            is_training=FLAGS.is_training)
        image_size = FLAGS.image_size or network_fn.default_image_size
        num_channels = 1 if FLAGS.use_grayscale else 3
        if FLAGS.is_video_model:
          input_shape = [
              FLAGS.batch_size, FLAGS.num_frames, image_size, image_size,
              num_channels
          ]
        else:
          input_shape = [FLAGS.batch_size, image_size, image_size, num_channels]
        placeholder = tf.placeholder(name='input', dtype=tf.float32,
                                     shape=input_shape)
        network_fn(placeholder)
    
        if FLAGS.quantize:
          contrib_quantize.create_eval_graph()
    
        graph_def = graph.as_graph_def()
        if FLAGS.write_text_graphdef:
          tf.io.write_graph(
              graph_def,
              os.path.dirname(FLAGS.output_file),
              os.path.basename(FLAGS.output_file),
              as_text=True)
        else:
          with gfile.GFile(FLAGS.output_file, 'wb') as f:
            f.write(graph_def.SerializeToString())
    
    
    if __name__ == '__main__':
      tf.app.run()

```
I already have the checkpoint #104

![image](https://user-images.githubusercontent.com/52021842/98447697-9f2f9b00-20ec-11eb-8d02-69fa9f4e6662.png)

**Comment by ravikyram** [comment]
@abrahamperz 

Please change command to

`python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_coco.config --trained_checkpoint_prefix training/model.ckpt-104 --output_directory new`

Also, refer #117 and see if it helps you. I hope ckpt-104 is the last saved checkpoint you have given in command?

Thanks!
