### ISSUE TITLE
Error in fine tuning centernet_hg104_512x512

### ISSUE THREAD

**Issue by paoloalba** [tensorflow/models#9488]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

Error while fine tuning centernet_hg104_512x512 model

## 3. Steps to reproduce

try to fine tune centernet_hg104_512x512 model with novel classes and TF2

## 4. Expected behavior

start the training

## 5. Additional context

Traceback (most recent call last):
  File "object_detection/model_main_tf2.py", line 117, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/model_main_tf2.py", line 114, in main
    record_summaries=FLAGS.record_summaries)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/model_lib_v2.py", line 511, in train_loop
    model_config=model_config, is_training=True)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 1090, in build
    add_summaries)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 374, in _build_ssd_model
    _check_feature_extractor_exists(ssd_config.feature_extractor.type)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/builders/model_builder.py", line 248, in _check_feature_extractor_exists
    'Tensorflow'.format(feature_extractor_type))
ValueError:  is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): tensorflow/tensorflow:latest-gpu
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 2x Tesla K80, Compute Capability 3.7 (coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s)

**Comment by ravikyram** [comment]
@paoloalba 

Just to verify have you download the models from the below link .
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

Thanks!

**Comment by paoloalba** [comment]
@ravikyram I downloaded the checkpoint from the link you mention. Let me know if I can provide further details if you need some.
