### ISSUE TITLE
Unable to parse - xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by lurers** [tensorflow/models#9490]
I'm a complete beginner, 0 knowledge, and was instructed to follow [this guide.](https://www.instructables.com/Object-Detection-With-Sipeed-MaiX-BoardsKendryte-K/) The guide explains how to train and detect objects.

After several installs/uninstalls and setting everything up, I seem to have reached my wall.
Using aXeleRate, it tells me to use TensorFlow ver 1.15 and (or?) TensorFlowgpu ver 1.15, or less than 2.0 .

Here is the message I get after running `python axelerate/train.py -c configs /raccoon_detector.json`

Failed to load pre-trained weights for the whole model. It might be because you didn't specify any or the weight file cannot be found
Traceback (most recent call last):
  File "axelerate/train.py", line 184, in <module>
    setup_training(config_file=args.config)
  File "axelerate/train.py", line 169, in setup_training
    return(train_from_config(config, dirname))
  File "axelerate/train.py", line 147, in train_from_config
    config['train']['valid_metric'])
  File "C:\Users\forme\miniconda3\envs\yolo\lib\site-packages\axelerate\networks\yolo\frontend.py", line 126, in train
    is_only_detect=False)
  File "C:\Users\forme\miniconda3\envs\yolo\lib\site-packages\axelerate\networks\yolo\backend\utils\annotation.py", line 40, in get_train_annotations
    is_only_detect)
  File "C:\Users\forme\miniconda3\envs\yolo\lib\site-packages\axelerate\networks\yolo\backend\utils\annotation.py", line 174, in parse_annotation
    fname = parser.get_fname(annotation_file)
  File "C:\Users\forme\miniconda3\envs\yolo\lib\site-packages\axelerate\networks\yolo\backend\utils\annotation.py", line 75, in get_fname
    root = self._root_tag(annotation_file)
  File "C:\Users\forme\miniconda3\envs\yolo\lib\site-packages\axelerate\networks\yolo\backend\utils\annotation.py", line 148, in _root_tag
    tree = parse(fname)
  File "C:\Users\forme\miniconda3\envs\yolo\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\Users\forme\miniconda3\envs\yolo\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

I read the issue this was last posted on but no method to resolve has been found.

**Comment by Rprabudeva** [comment]
I would like to contribute
