### ISSUE TITLE
Fine-tune Inception V3 with Tensorflow 0.12.1 failed

### ISSUE THREAD

**Issue by panovr** [tensorflow/models#950]
Fine-tune Inception V3 with Tensorflow 0.12.1 failed.
```
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 448, in main
    image = image_preprocessing_fn(image, train_image_size, train_image_size)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/inception_preprocessing.py", line 302, in preprocess_image
    return preprocess_for_train(image, height, width, bbox, fast_mode)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/inception_preprocessing.py", line 195, in preprocess_for_train
    tf.image_summary('image_with_bounding_boxes', image_with_box)
AttributeError: 'module' object has no attribute 'image_summary'
```
```
Traceback (most recent call last):
  File "eval_image_classifier.py", line 191, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_image_classifier.py", line 128, in main
    image = image_preprocessing_fn(image, eval_image_size, eval_image_size)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/inception_preprocessing.py", line 304, in preprocess_image
    return preprocess_for_eval(image, height, width)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/inception_preprocessing.py", line 273, in preprocess_for_eval
    image = tf.sub(image, 0.5)
AttributeError: 'module' object has no attribute 'sub'
```
```
Traceback (most recent call last):
  File "eval_image_classifier.py", line 191, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_image_classifier.py", line 128, in main
    image = image_preprocessing_fn(image, eval_image_size, eval_image_size)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/inception_preprocessing.py", line 304, in preprocess_image
    return preprocess_for_eval(image, height, width)
  File "/home/ylzhao/project/tensorflow-models/slim/preprocessing/inception_preprocessing.py", line 274, in preprocess_for_eval
    image = tf.mul(image, 2.0)
AttributeError: 'module' object has no attribute 'mul'
```
```
Traceback (most recent call last):
  File "eval_image_classifier.py", line 191, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_image_classifier.py", line 139, in main
    logits, _ = network_fn(images)
  File "/home/ylzhao/project/models/slim/nets/nets_factory.py", line 105, in network_fn
    return func(images, num_classes, is_training=is_training)
  File "/home/ylzhao/project/models/slim/nets/inception_v3.py", line 481, in inception_v3
    depth_multiplier=depth_multiplier)
  File "/home/ylzhao/project/models/slim/nets/inception_v3.py", line 161, in inception_v3_base
    net = tf.concat(3, [branch_0, branch_1, branch_2, branch_3])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1053, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

**Comment by drpngx** [comment]
Yes, the `image_summary` has been moved to `tf.summary.image`. If you could send a PR for that, that would be great. thanks!

**Comment by panovr** [comment]
@drpngx I realized that `tf.image_summary` -> `tf.summary.image` change. However, I still have no ideas of how to resolve the `TypeError: Expected int32, got list containing Tensors of type '_Message' instead.` error.

**Comment by drpngx** [comment]
Did you check the parameter order? I think we swapped them.

**Comment by deepankar1994** [comment]
I was getting a similar error. I reverted to TF 0.11 and got it resolved.

**Comment by da-steve101** [comment]
I had a similar issue, I found it was cause by the parameter order of concat. Changing to concat_v2 (which has other order ) as [here](https://www.tensorflow.org/api_docs/python/array_ops/slicing_and_joining#concat_v2) seemed to work

**Comment by drpngx** [comment]
Still waiting for @panovr

**Comment by panovr** [comment]
Though I can run `finetune_inception_v3_on_flowers.sh` after some changes, the modifications is much more than estimated, and I'm a bit afraid that if my changes are correct.
Personally, I will reverted to TF 0.11 until TF 1.0.0 released.

**Comment by drpngx** [comment]
OK. @da-steve101 , do you want to submit a PR?

**Comment by as6520** [comment]
I resolved these issues by changing concat to concat_v2, explicitly casting the mismatched type tensors to float, replacing the operators by their new names  and replacing image_summary, histogram_summary and scalar_summary with summary.image, summary.histogram, summary.scalar. But currently stuck with the following error

Traceback (most recent call last):
  File "/home/ameya.shringi/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ameya.shringi/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_train.py", line 37, in main
    inception_train.train(dataset)
  File "/home/ameya.shringi/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inception_train.py", line 281, in train
    apply_gradient_op = opt.apply_gradients(grads, global_step=global_step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 441, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 80, in update_op
    return optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/rmsprop.py", line 142, in _apply_dense
    use_locking=self._use_locking).op
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/gen_training_ops.py", line 468, in apply_rms_prop
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2404, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shapes must be equal rank, but are 4 and 5 for 'RMSProp/update_conv0/weights/ApplyRMSProp' (op: 'ApplyRMSProp') with input shapes: [3,3,3,32], [3,3,3,32], [3,3,3,32], [], [], [], [], [1,3,3,3,32]

Any thoughts on where I am going wrong would be appreciated.

**Comment by SihamTabik** [comment]
Hi everyone,
I've just started playing with tensorflow through slim.

I've done exactly all the steps mentioned in this link:
https://github.com/tensorflow/models/tree/master/slim

They suggest installing this binary: tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
which is tensorflow version 0.10 

However, I am getting the same errors mentioned above. Replacing  "image_summary" with "summary.image" worked  but Replacing "concat" with  "concat_v2" has not solve the problem. I am still getting: AttributeError: 'module' object has no attribute 'concat_v2'

It seems that there are incompatibilities between the current Slim and tensorflow. Should I wait for an updated version of slim?. Is there a tensorfolw version that works correctly with Slim?

Thanks

**Comment by anywang** [comment]
Hi guys, have very similar problem, I already used tf_upgrade.py update our code, but it still has the error
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by tfboyd** [comment]
For TF 1.0 users, this upgrades inception and resnet_v2 for slim, which should help the situation.  I tested training from scratch rather the fine-tune but this is much better than trying to run TF 1.0 on the current code.
https://github.com/tensorflow/models/pull/1151

**Comment by tfboyd** [comment]
Let me know other issues you having running TF 1.0.  I can/will try to help with anything related to imagenet and these models because I happen to be in this code right now.
