### ISSUE TITLE
AttributeError: 

### ISSUE THREAD

**Issue by znapgz** [tensorflow/models#9501]
Traceback (most recent call last):
  File "D:/CNN程序/models-master/research/slim/train_image_classifier.py", line 27, in <module>
    from nets import nets_factory
  File "D:\CNN程序\models-master\research\slim\nets\nets_factory.py", line 34, in <module>
    from nets.mobilenet import mobilenet_v2
  File "D:\CNN程序\models-master\research\slim\nets\mobilenet\mobilenet_v2.py", line 35, in <module>
    from nets.mobilenet import mobilenet as lib
  File "D:\CNN程序\models-master\research\slim\nets\mobilenet\mobilenet.py", line 399, in <module>
    def global_pool(input_tensor, pool_op=tf.compat.v2.nn.avg_pool2d):
AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'

**Comment by ravikyram** [comment]
@znapgz 

Can you refer this [SO link](https://stackoverflow.com/questions/60292905/attributeerror-module-tensorflow-api-v1-compat-has-no-attribute-v2-for-ten),#8088 and see if it helps you.
If the problem still persists then request you to share colab link or commands / steps that you executed before running into the problem. It helps us in localizing the issue faster. Thanks!

**Comment by saberkun** [comment]
Which TF version are you running? These compat.v2 module requires TF 2.x
