### ISSUE TITLE
when run run_classifier.py  error

### ISSUE THREAD

**Issue by ibmxiang** [tensorflow/models#9509]
use uncased_L-12_H-768_A-12 checkpoint  ,when i  run run_classifier.py  ,the error happen on  this code: checkpoint.restore(init_checkpoint).assert_existing_objects_matched()
it  looks like  can`t load pretraining model 
AssertionError: Some objects had attributes which were not restored:MirroredVariable:{
  0: <tf.Variable 'word_embeddings/embeddings:0' shape=(21128, 768) dtype=float32, numpy=
array([[ 0.03178228, -0.01392684,  0.01429486, ...,  0.00253374,

**Comment by ibmxiang** [comment]
--mode=train_and_eval
  --input_meta_data_path=../xlsbertdatas/MRPC_meta_data
  --train_data_path=../xlsbertdatas/MRPC_train.tf_record
  --eval_data_path=../xlsbertdatas/MRPC_eval.tf_record
  --bert_config_file=D:\mypython_code\models-master\official\nlp\chinese_L-12_H-768_A-12/bert_config.json
  --init_checkpoint=D:\mypython_code\models-master\official\nlp\chinese_L-12_H-768_A-12/bert_model.ckpt
  --train_batch_size=4
  --eval_batch_size=4
  --steps_per_loop=1
  --learning_rate=2e-5
  --num_train_epochs=3
  --model_dir=D://mypython_code//models-master//official//nlp//chinese_L-12_H-768_A-12
  --distribution_strategy=mirrored




Traceback (most recent call last):
  File "D:/mypython_code/models-master/official/nlp/bert/run_classifier.py", line 518, in <module>
    app.run(main)
  File "C:\Users\xls\Anaconda3\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\xls\Anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "D:/mypython_code/models-master/official/nlp/bert/run_classifier.py", line 511, in main
    custom_main(custom_callbacks=None, custom_metrics=None)
  File "D:/mypython_code/models-master/official/nlp/bert/run_classifier.py", line 507, in custom_main
    custom_metrics=custom_metrics)
  File "D:/mypython_code/models-master/official/nlp/bert/run_classifier.py", line 416, in run_bert
    custom_metrics=custom_metrics)
  File "D:/mypython_code/models-master/official/nlp/bert/run_classifier.py", line 197, in run_bert_classifier
    custom_callbacks=custom_callbacks)
  File "D:/mypython_code/models-master/official/nlp/bert/run_classifier.py", line 224, in run_keras_compile_fit
    checkpoint.restore(init_checkpoint).assert_existing_objects_matched()
  File "C:\Users\xls\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1015, in assert_existing_objects_matched
    return self.assert_consumed()
  File "C:\Users\xls\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1000, in assert_consumed
    "".join(unused_attribute_strings)))
AssertionError: Some objects had attributes which were not restored:
    MirroredVariable:{
  0: <tf.Variable 'word_embeddings/embeddings:0' shape=(21128, 768) dtype=float32, numpy=

**Comment by saberkun** [comment]
Your vocabulary size does not match your checkpoint. This cause the word_embeddings/embeddings variable cannot be loaded.

**Comment by ibmxiang** [comment]
emm, I test uncased_L-12_H-768_A-12 , it's download from https://storage.googleapis.com/cloud-tpu-checkpoints/bert/keras_bert/uncased_L-12_H-768_A-12.tar.gz,  this  checkpoint not match the vocab?,same problem arises，AssertionError: Some objects had attributes which were not restored:
    MirroredVariable:{
  0: <tf.Variable 'word_embeddings/embeddings:0' shape=(30522, 768) dtype=float32, numpy=
array([[ 0.02221753,  0.01757775,  0.00135117, ...,  0.01361255,

I download this model  on

**Comment by ibmxiang** [comment]
it's ok, I download cased checkpoint, thanks  a lot @saberkun
