### ISSUE TITLE
Training EdgeTPU Deeplab on custom dataset

### ISSUE THREAD

**Issue by gdebrecz** [tensorflow/models#9510]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md

## 2. Describe the issue

I'd like to train EdgeTPU-DeepLab (http://download.tensorflow.org/models/edgetpu-deeplab_2020_03_09.tar.gz) further on CityScapes dataset and also on custom dataset for EdgeTPU !

Though, there is some hint in the documentation how it should be done, there are no clear instructions **with all the necessary and required command line flag listed IN ONE PLACE !.** This information is scattered around and it is diccicult to figure out which flags to use for which network/dataset/ combination.

After downloadinf and converting CityScaped dataset as described, Im I'm trying to apply:

python3 deeplab/train.py \
    --logtostderr \
    --train_split="trainval" \
    --model_variant="mobilenet_edgetpu" \
    --decoder_output_stride='' \
    --aspp_convs_filters=256 \
    --quantize_delay_step=-1 \
    --output_stride=16 \
    --train_crop_size="320,200" \
    --train_batch_size=1 \
    --initialize_last_layer=true \
    --training_number_of_steps=1000 \
    --fine_tune_batch_norm=true \
    --tf_initial_checkpoint=${PATH_TO_TRAINED_FLOAT_MODEL} \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET} \
    --decoder_output_is_logits=1 
    --last_layers_contain_logits_only=False \
    --decoder_filter=19 \
    --num_classes=19

where 

PATH_TO_DATASET=~/models/research/deeplab/datasets/cityscapes/tfrecord
PATH_TO_TRAINED_FLOAT_MODEL=/root/edgetpu-deeplab/model.ckpt
PATH_TO_TRAIN_DIR=./traindir-edgetpu

and the command fails with:
Traceback (most recent call last):
  File "deeplab/train.py", line 464, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deeplab/train.py", line 444, in main
    ignore_missing_vars=True)
  File "/root/models/research/deeplab/utils/train_utils.py", line 221, in get_model_init_fn
    ignore_missing_vars=ignore_missing_vars)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/framework/python/ops/variables.py", line 690, in assign_from_checkpoint
    (ckpt_name, str(ckpt_value.shape), str(var.get_shape())))
ValueError: Total size of new array must be unchanged for logits/semantic/weights lh_shape: [(1, 1, 256, 19)], rh_shape: [(1, 1, 256, 21)]

My final goal is to retrain EdgeTPU-Deeplab on custom dataset for EdgeTPU.

Thanks in advance for your help,

**Comment by gdebrecz** [comment]
My, bad it adding dataset= parameter and fixing the train_split value solved the problem.

python3 deeplab/train.py \
    --logtostderr \
    --train_split="train_fine" \
    --model_variant="mobilenet_edgetpu" \
    --decoder_output_stride='' \
    --aspp_convs_filters=256 \
    --quantize_delay_step=0 \
    --output_stride=16 \
    --train_crop_size="320,200" \
    --train_batch_size=4 \
    --initialize_last_layer=true \
    --training_number_of_steps=10 \
    --fine_tune_batch_norm=true \
    --tf_initial_checkpoint=${PATH_TO_TRAINED_FLOAT_MODEL} \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET} \
    --last_layers_contain_logits_only=False \
    --decoder_filter=19 \
    --num_classes=19 \
    --dataset="cityscapes"
