### ISSUE TITLE
all_metrics_per_categroy doesnt work

### ISSUE THREAD

**Issue by nilskk** [tensorflow/models#9520]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/metrics/coco_tools.py

## 2. Describe the bug

Although I set 'all_metrics_per_category' to true in my pipeline.config, it won't print out any metrics per category when I run model_main_tf2.py in eval mode. Does somebody have a fix to that?

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1/8.0.5
- GPU model and memory: RTX 3080 / 10 GB

**Comment by ravikyram** [comment]
@nilskk 

Please, provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by nilskk** [comment]
I figured out, that i had to set 'include_metrics_per_category' to true, but now it says: 
```Traceback (most recent call last):
  File "evaluation.py", line 33, in <module>
    tf.compat.v1.app.run(evaluate)
  File "/home/nilskk/anaconda3/envs/fruit_tf_od_api/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/nilskk/anaconda3/envs/fruit_tf_od_api/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/nilskk/anaconda3/envs/fruit_tf_od_api/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "evaluation.py", line 23, in evaluate
    model_lib_v2.eval_continuously(
  File "/home/nilskk/Desktop/Projektarbeit/fruit_tf_od_api/object_detection/model_lib_v2.py", line 1081, in eval_continuously
    eval_metrics = eager_eval_loop(
  File "/home/nilskk/Desktop/Projektarbeit/fruit_tf_od_api/object_detection/model_lib_v2.py", line 957, in eager_eval_loop
    eval_metrics.update(evaluator.evaluate())
  File "/home/nilskk/Desktop/Projektarbeit/fruit_tf_od_api/object_detection/metrics/coco_evaluation.py", line 304, in evaluate
    box_metrics, box_per_category_ap = box_evaluator.ComputeMetrics(
  File "/home/nilskk/Desktop/Projektarbeit/fruit_tf_od_api/object_detection/metrics/coco_tools.py", line 305, in ComputeMetrics
    raise ValueError('Category stats do not exist')
ValueError: Category stats do not exist
```
Does that feature not work?

**Comment by ravikyram** [comment]
@nilskk 

Please, refer #5010 and see if it helps you. Thanks!

**Comment by nilskk** [comment]
yeah that worked for me
