### ISSUE TITLE
Tensorflow 1.x required but error asking for Tensorflow version >= 2.3 appearing

### ISSUE THREAD

**Issue by fernando2xV** [tensorflow/models#9543]
I'm trying to run the models/research/efficient-hrl by running the "training job based on the original HIRO paper on Ant Maze". The github repo specifies that a version of Tensorflow 1.x is required, however, when running the script in Anaconda environment, an error asking to upgrade to Tensorflow >= 2.3 is required.

**Here is the error:**

(hrl_googlebrain_2) C:\Users\flemo\Documents\TRINITY\4th_year\FYP\HRL_googlebrain\models\research\efficient-hrl>python scripts/local_train.py test1 hiro_orig ant_maze base_uvf suite
python ./run_train.py  --train_dir=C:\Users\flemo/tmp/hiro_orig/ant_maze/base_uvf/test1/train --config_file=./configs/base_uvf.gin --config_file=./configs/train_uvf.gin --config_file=./context/configs/hiro_orig.gin --config_file=./context/configs/ant_maze.gin --summarize_gradients=False --save_interval_secs=60 --save_summaries_secs=1 --master=local --alsologtostderr
2020-12-09 09:25:37.295451: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-12-09 09:25:37.295665: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "./run_train.py", line 29, in <module>
    import train
  File "C:\Users\flemo\Documents\TRINITY\4th_year\FYP\HRL_googlebrain\models\research\efficient-hrl\train.py", line 33, in <module>
    import agent as agent_
  File "C:\Users\flemo\Documents\TRINITY\4th_year\FYP\HRL_googlebrain\models\research\efficient-hrl\agent.py", line 21, in <module>
    from agents import ddpg_agent
  File "C:\Users\flemo\Documents\TRINITY\4th_year\FYP\HRL_googlebrain\models\research\efficient-hrl\agents\ddpg_agent.py", line 28, in <module>
    from utils import utils
  File "C:\Users\flemo\Documents\TRINITY\4th_year\FYP\HRL_googlebrain\models\research\efficient-hrl\utils\utils.py", line 25, in <module>
    from tf_agents import specs
  File "C:\Users\flemo\miniconda3\envs\hrl_googlebrain_2\lib\site-packages\tf_agents\specs\__init__.py", line 20, in <module>
    from tf_agents.specs.distribution_spec import DistributionSpec
  File "C:\Users\flemo\miniconda3\envs\hrl_googlebrain_2\lib\site-packages\tf_agents\specs\distribution_spec.py", line 22, in <module>
    import tensorflow_probability as tfp
  File "C:\Users\flemo\miniconda3\envs\hrl_googlebrain_2\lib\site-packages\tensorflow_probability\__init__.py", line 69, in <module>
    _ensure_tf_install()
  File "C:\Users\flemo\miniconda3\envs\hrl_googlebrain_2\lib\site-packages\tensorflow_probability\__init__.py", line 66, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.3; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.

**Comment by ravikyram** [comment]
@fernando2xV 

For TF 1.15 please install and see if it helps you.

```
pip install tensorflow-probability==0.8.0
pip install tf-agents==0.3.0
```
Please, find Tensorflow probablity compatible versions from [here](https://github.com/tensorflow/probability/releases).Thanks!
