### ISSUE TITLE
python model_main_tf2.py error

### ISSUE THREAD

**Issue by YuByoungJoon** [tensorflow/models#9549]
> window10
   anaconda3
   Python3.8.5
   Tensorflow 2.3.1

I am now running tensorflow2 object_detection.
Faced with various problems, we are reducing errors one by one through Github.
But I don't know how to solve this problem.

`(tensorflow) PS C:\Users\Admin\Tensorflow\models\research\object_detection> python model_main_tf2.py --logtostderr --train_dir=training/ --pipeline_config_path=trainin/ssd_mobilenet_v1_pets.config`

I entered the model_main_tf2.py file.

but....

> 2020-12-11 15:44:46.551774: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-12-11 15:44:50.397040: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-12-11 15:44:50.436066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 SUPER computeCapability: 7.5
coreClock: 1.83GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-12-11 15:44:50.436856: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-12-11 15:44:50.442191: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-12-11 15:44:50.446561: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-12-11 15:44:50.458495: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-12-11 15:44:50.463772: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-12-11 15:44:50.474853: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-12-11 15:44:50.484008: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-12-11 15:44:50.489996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-11 15:44:50.490892: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-11 15:44:50.499236: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x17287b61590 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-11 15:44:50.507700: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-11 15:44:50.508330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 SUPER computeCapability: 7.5
coreClock: 1.83GHz coreCount: 22 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-12-11 15:44:50.509281: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-12-11 15:44:50.509507: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-12-11 15:44:50.509723: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-12-11 15:44:50.509880: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-12-11 15:44:50.510087: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-12-11 15:44:50.510498: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-12-11 15:44:50.510698: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-12-11 15:44:50.525487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-11 15:44:51.101107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-11 15:44:51.101395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-12-11 15:44:51.101727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-12-11 15:44:51.102058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4746 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-12-11 15:44:51.105036: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x172b39f35c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-12-11 15:44:51.118938: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1660 SUPER, Compute Capability 7.5
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I1211 15:44:51.120347 18108 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 104, in main
    model_lib_v2.train_loop(
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection\model_lib_v2.py", line 462, in train_loop
    configs = get_configs_from_pipeline_file(
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection\utils\config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 82: invalid start byte

In a situation like this, it is difficult to use an environment like Ubuntu or Linux.
I want to know how to solve this error when running on Windows 10.
I hope the guardians of github help me.

**Comment by YuByoungJoon** [comment]
In the tutorial, I was told to use the `train.py` file, but an error occurred and I checked on github and told me to use the `model_main_tf2.py` file.

**Comment by saikumarchalla** [comment]
@YuByoungJoon  Could you please let us know which tutorial are you referring to?. Thanks!

**Comment by YuByoungJoon** [comment]
It is possible.
The tutorial I'm learning right now `https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html` this homepage and `https://www.youtube.com/watch?v=JR8CmWyh2E8` youtube channel!

**Comment by YuByoungJoon** [comment]
This problem has been resolved.
The above problem was caused by an error in the` label_map.pbtxt` file.
After solving the problem, it was confirmed that `ssd_mobilenet_v1` is not supported by Tensorflow2.
Therefore, I checked the items supported by Tensorflow in `Model_builder.py`, and I want to try object_detection again with the supported `*.config` file.
