### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

### ISSUE THREAD

**Issue by theumang100** [tensorflow/models#9563]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the bug

When i try to convert saved_model.pb to .tflite file it says "tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse"

## 3. I've tried below code:
import tensorflow as tf

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model("efficientdet_d0_coco17_tpu-32\saved_model") # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)

## 4. Expected behavior

It should generate model.tflite file

## 5. cmd error

WARNING:tensorflow:Importing a function (__inference_bifpn_layer_call_and_return_conditional_losses_75975) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:tensorflow:Importing a function (__inference_bifpn_layer_call_and_return_conditional_losses_75975) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:tensorflow:Importing a function (__inference_bifpn_layer_call_and_return_conditional_losses_75975) with ops with custom gradients. Will likely fail if a gradient is requested.
Traceback (most recent call last):
  File "tflite_converter.py", line 4, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model("efficientdet_d0_coco17_tpu-32\saved_model") # path to the SavedModel directory
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\lite.py", line 1028, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 632, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 130, in __init__
    self._load_all()
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 141, in _load_all
    self._load_nodes()
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 283, in _load_nodes
    node, setter = self._recreate(proto, node_id)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 393, in _recreate
    return factory[kind]()
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 386, in <lambda>
    "variable": lambda: self._recreate_variable(proto.variable),
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 449, in _recreate_variable
    return variables.Variable(
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 244, in _variable_v2_call
    return previous_getter(
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 67, in getter
    return captured_getter(captured_previous, **kwargs)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\load.py", line 441, in uninitialized_variable_creator
    return resource_variable_ops.UninitializedVariable(**kwargs)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1879, in __init__
    handle = _variable_handle_from_shape_and_dtype(
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 174, in _variable_handle_from_shape_and_dtype
    gen_logging_ops._assert(  # pylint: disable=protected-access
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 49, in _assert
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\theum\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):2.3.1
- Python version:3.8.3
- Bazel version (if compiling from source):3.7.1
- GCC/Compiler version (if compiling from source):9.2.0
- CUDA/cuDNN version:10.1/ 7
- GPU model and memory:NVIDIA GEFORCE 920MX Compute capability:5.0

**Comment by saikumarchalla** [comment]
@theumang100  Please have a look at this [issue](https://github.com/tensorflow/tensorflow/issues/38518) and hope it helps your query. Thanks!

**Comment by theumang100** [comment]
> @theumang100 Please have a look at this [issue](https://github.com/tensorflow/tensorflow/issues/38518) and hope it helps your query. Thanks!

This error is for different process. I'm trying to convert my tensorflow model to tflite.

**Comment by saikumarchalla** [comment]
@theumang100  Could you please provide the saved model so that it helps debugging the issue at our end.

Also, please try using this code to convert the saved model to tflite and let us know if it works.

converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_PATH)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

Thank you !!

**Comment by theumang100** [comment]
> @theumang100 Could you please provide the saved model so that it helps debugging the issue at our end.
> 
> Also, please try using this code to convert the saved model to tflite and let us know if it works.
> 
> converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_PATH)
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> converter.experimental_new_converter = True
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> tflite_model = converter.convert()
> 
> Thank you !!

same issue with this code also!!!

My saved model is:

[saved_model.zip](https://github.com/tensorflow/models/files/5709568/saved_model.zip)

**Comment by theumang100** [comment]
@saikumarchalla any update?

**Comment by theumang100** [comment]
@saikumarchalla have you got anything?

**Comment by ymodak** [comment]
Can you try converting in to TFLite using TF 2.4 and tf-nightly? You may use google colab to quickly test with different TF versions. Thanks!

**Comment by theumang100** [comment]
@ymodak can you refer me a process of how convert using tf-nighty?  As i can't find something right.

**Comment by theumang100** [comment]
There is a issue with tensorflow-gpu version i used **tensorflow-gpu=2.4.0** and can't find this error. Thank You!!
