### ISSUE TITLE
centernet to tf1.0， train and eval were normal， but got same score （very low）for all the boxes

### ISSUE THREAD

**Issue by yuanrui1987** [tensorflow/models#9564]
I am doing a tf1.0 centernet thing.
I have added center_net_mobilenet_v2 to model_builders, and train & eval looks pretty normal (by model_main.py), but inference result is strange, all the boxes had a same score!
any one has ideas, really appreciate!

**Comment by saikumarchalla** [comment]
@yuanrui1987 
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by yuanrui1987** [comment]
@saikumarchalla Thanks a lot for reply!

I updated to the latest centernet code from the master branch, and now i got a centernet_mobilenet_v2 TF1.0 model with a AP 0.32 (train and eval with model_main.py).
I try to freeze it with export_inference_graph.py, but get a error "Not found: Key sequential/conv2d_3/bias not found in checkpoint".

_Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "/home/yuanrui/anaconda3/envs/pruning_2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/yuanrui/anaconda3/envs/pruning_2/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/yuanrui/anaconda3/envs/pruning_2/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/yuanrui/Code/tmp/object_detection_model_training/object_detection_model/object_detection/exporter.py", line 506, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/yuanrui/Code/tmp/object_detection_model_training/object_detection_model/object_detection/exporter.py", line 434, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/home/yuanrui/Code/tmp/object_detection_model_training/object_detection_model/object_detection/exporter.py", line 342, in write_graph_and_checkpoint
    saver.restore(sess, trained_checkpoint_prefix)
  File "/home/yuanrui/anaconda3/envs/pruning_2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key sequential/conv2d_3/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/yuanrui/Code/tmp/object_detection_model_training/object_detection_model/object_detection/exporter.py:338) ]]_

but when i train with legacy/train.py, i can use export_inference_graph.py to freeze the model successfully.
and i noticed that model trained by model_main.py and model trained by legacy/train.py are different.  i parsed variable of ckpt files of the two models with the following code, and found names of variables are different, it seems that variables name of model trained by model_main.py starts from sequential_3, not sequential.

any helps? thanks.

`checkpoint_path = r'./model.ckpt-0' 
reader = pywrap_tensorflow.NewCheckpointReader(checkpoint_path)
var_to_shape_map = reader.get_variable_to_shape_map()
for key in var_to_shape_map:
    print("tensor_name: ", key)`
