### ISSUE TITLE
run train_image_classifier.py   training mnist datasets  error 

### ISSUE THREAD

**Issue by jimmery-XUT** [tensorflow/models#9566]
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path saver_1/resnet_v1_50_mnist/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
2020-12-17 10:32:03.724587: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at strided_slice_op.cc:105 : Invalid argument: slice index 2 of dimension 0 out of bounds.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, slice index 2 of dimension 0 out of bounds.
	 [[Node: strided_slice_4 = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Shape_2, strided_slice_4/stack, strided_slice_4/stack_1, strided_slice_4/stack_2)]]
2020-12-17 10:32:03.725129: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at strided_slice_op.cc:105 : Invalid argument: slice index 2 of dimension 0 out of bounds.
2020-12-17 10:32:03.725518: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at strided_slice_op.cc:105 : Invalid argument: slice index 2 of dimension 0 out of bounds.
2020-12-17 10:32:03.725842: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at strided_slice_op.cc:105 : Invalid argument: slice index 2 of dimension 0 out of bounds.
INFO:tensorflow:Caught OutOfRangeError. Stopping Training. FIFOQueue '_1_prefetch_queue/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prefetch_queue/fifo_queue)]]
	 [[Node: group_deps/_2134 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5011_group_deps", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'fifo_queue_Dequeue', defined at:
  File "/home/shuoxing/z_net/slim_1/train_image_classifier.py", line 618, in <module>
    tf.app.run()
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/shuoxing/z_net/slim_1/train_image_classifier.py", line 516, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/home/shuoxing/z_net/slim_1/deployment/model_deploy.py", line 194, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/shuoxing/z_net/slim_1/train_image_classifier.py", line 498, in clone_fn
    images, labels = batch_queue.dequeue()
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 433, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3734, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_prefetch_queue/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](prefetch_queue/fifo_queue)]]
	 [[Node: group_deps/_2134 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5011_group_deps", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "/home/shuoxing/z_net/slim_1/train_image_classifier.py", line 618, in <module>
    tf.app.run()
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/shuoxing/z_net/slim_1/train_image_classifier.py", line 614, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 785, in train
    ignore_live_threads=ignore_live_threads)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1205, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/shuoxing/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 2 of dimension 0 out of bounds.
	 [[Node: strided_slice_4 = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Shape_2, strided_slice_4/stack, strided_slice_4/stack_1, strided_slice_4/stack_2)]]

Process finished with exit code 1
Please tell me how to solve it? Thanks

**Comment by saikumarchalla** [comment]
@jimmery-XUT Could you please fill the issue template. Also,Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks
