### ISSUE TITLE
Clone a loaded object detection model in memory fails

### ISSUE THREAD

**Issue by OliverPfau** [tensorflow/models#9576]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Done] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [Done] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Done] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models.git

## 2. Describe the bug

Trained my model from **ssd_mobilenet_v2_320x320_coco17_tpu-8** as base, saved it to disk with `exporter_main_v2.py`. After loading the model with `detect_fn = tf.saved_model.load(model_dir)` I want to clone the python object with tf.keras.models.clone_model(detect_fn). This fails with **Expected `model` argument to be a `Model` instance, got ', <tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject object at 0x7f7195138e80>**

## 3. Steps to reproduce

See 2.

## 4. Expected behavior

Get a in-memory clone of the model

## 5. Additional context

Expected `model` argument to be a `Model` instance, got ', <tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject object at 0x7f7195138e80>

## 6. System information

- Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version: v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.6.9
- Bazel version (if compiling from source): na
- GCC/Compiler version (if compiling from source): na
- CUDA/cuDNN version: na
- GPU model and memory: AMD

**Comment by OliverPfau** [comment]
If I try to load the model saved with `exporter_main_v2.py` with `tf.keras.models.load_model(model_path)` I get an exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 211, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 114, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: /workdir/6/model/saved_model.pb/{saved_model.pbtxt|saved_model.pb}
>>> model = tf.keras.models.load_model("/workdir/6/model/")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 147, in load
    keras_loader.finalize_objects()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 600, in finalize_objects
    self._reconstruct_all_models()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 619, in _reconstruct_all_models
    self._reconstruct_model(model_id, model, layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 666, in _reconstruct_model
    config, created_layers={layer.name: layer for layer in layers})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 1285, in reconstruct_from_config
    process_node(layer, node_data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 1233, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py", line 917, in call
    result = self.function(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 205, in wrapper
    result = dispatch(wrapper, args, kwargs)
TypeError: 'module' object is not callable
