### ISSUE TITLE
Fail to convert to tflite

### ISSUE THREAD

**Issue by Trumpiter-max** [tensorflow/models#9577]
Hi
I got problem:
Traceback (most recent call last):
  File "/content/models/research/object_detection/export_tflite_graph_tf2.py", line 126, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/export_tflite_graph_tf2.py", line 122, in main
    FLAGS.ssd_use_regular_nms)
  File "/content/models/research/object_detection/export_tflite_graph_lib_tf2.py", line 231, in export_tflite_model
    pipeline_config.model, is_training=False)
  File "/content/models/research/object_detection/builders/model_builder.py", line 1090, in build
    add_summaries)
  File "/content/models/research/object_detection/builders/model_builder.py", line 380, in _build_ssd_model
    is_training=is_training)
  File "/content/models/research/object_detection/builders/model_builder.py", line 293, in _build_ssd_feature_extractor
    feature_extractor_class = SSD_KERAS_FEATURE_EXTRACTOR_CLASS_MAP[
NameError: name 'SSD_KERAS_FEATURE_EXTRACTOR_CLASS_MAP' is not defined  

After run below command, can show me how to fix this one

!python /content/models/research/object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path /content/data/pipeline.config \
    --trained_checkpoint_dir /content/output/checkpoint \
    --output_directory /content/model_android

**Comment by PetervanLunteren** [comment]
I have the same problem. Found a solution?
