### ISSUE TITLE
Error parsey_universal/parse.sh

### ISSUE THREAD

**Issue by candaj** [tensorflow/models#963]
Hello,

I'm trying to use the universal parser with French models. I'm following the tutorial https://github.com/tensorflow/models/blob/master/syntaxnet/universal.md

With the following command i'm getting : 
```
$:~/Projects/NaturalLanguage/models/syntaxnet$ echo "Je suis un homme." | syntaxnet/models/parsey_universal/parse.sh ~/Projects/NaturalLanguage/French/
Traceback (most recent call last):
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 80, in Eval
    task_context = RewriteContext(task_context)
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 70, in RewriteContext
    part.file_pattern = os.path.join(FLAGS.resource_dir, part.file_pattern)
  File "/usr/lib/python2.7/posixpath.py", line 78, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "~/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 80, in Eval
    task_context = RewriteContext(task_context)
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 70, in RewriteContext
    part.file_pattern = os.path.join(FLAGS.resource_dir, part.file_pattern)
  File "/usr/lib/python2.7/posixpath.py", line 78, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 161, in <module>
    tf.app.run()
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/jcanda/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 157, in main
    Eval(sess)
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 80, in Eval
    task_context = RewriteContext(task_context)
  File "~/Projects/NaturalLanguage/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 70, in RewriteContext
    part.file_pattern = os.path.join(FLAGS.resource_dir, part.file_pattern)
  File "/usr/lib/python2.7/posixpath.py", line 78, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
```

Seems to have some issues in decoding specific character in the model but i don't know why.
Any help ?

Regards,

**Comment by drpngx** [comment]
From the stack trace, it looks like that one of the input files is invalid characters. Could you try to rename that?

**Comment by candaj** [comment]
Hello,

Sorry for the time i took. In fact yes it was a mistake from my side. 
Sorry for that.

Regards,
