### ISSUE TITLE
Cyclic Learning Rate implementation in TF1 ObjectDetectionAPI  google.protobuf.text_format.ParseError:

### ISSUE THREAD

**Issue by DemolationPeter** [tensorflow/models#9643]
**Prerequisites**
--------------------------------------------------------------------------------------------------------------------------------------------------------

-  [ ]  I am using the latest TensorFlow Model Garden release and TensorFlow 2. No TF1.15

- [ x] I am reporting the issue to the correct repository. (Model Garden official or research directory)

- [ x] I checked to make sure that this issue has not been filed already.

---------------------------------------------------------------------------------------------------------------------------------------------------------------
**2. Describe the bug**

At the moment I try to implement for TF1 Object Detection API a custom Learning Rate Schedule (Cyclic Learning Rate). Via Anaconda environment and TF1.15 it is working. 

For the next step I want to implement TF1 OD API in a Docker Image and also implement the new Learning Rate Schedule inside the Image. With the other Learning Rate Schedules (manual_step etc.) it is working fine and i can start the training but with my Cyclic Learning Rate Schedule I get an protobuf error and I can't solve it.

**Error**

python model_main.py --alsologtostderr --model_dir=own/models/Variation60/model_checkpoints --pipeline_config_path=own/models/Variation60/mobilnetv2_variation60.config
2021-01-17 19:07:27.776022: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Traceback (most recent call last):
  File "model_main.py", line 108, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main.py", line 70, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "/usr/local/lib/python3.6/dist-packages/object_detection/model_lib.py", line 781, in create_estimator_and_inputs
    pipeline_config_path, config_override=config_override)
  File "/usr/local/lib/python3.6/dist-packages/object_detection/utils/config_util.py", line 139, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 734, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 802, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 827, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 849, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/text_format.py", line 941, in _MergeField
    (message_descriptor.full_name, name))
**google.protobuf.text_format.ParseError: 148:9 : Message type "object_detection.protos.LearningRate" has no field named "cyclic_learning_rate".**

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
**3. Changed Files for new Learning Rate and Ideas**

- optimizer.proto
- optimizer_builder.py
- learning_schedules.py
- optimizer_pb2.py

The files are in the following zip folder
**[files.zip](https://github.com/tensorflow/models/files/5826686/files.zip)**

I think the error is in the optimizer.proto file or during the conversion into the optimizer_pb2.py file. I don`t understand why protobuf cant find the field name  "cyclic_learning_rate" because the field name exists in the optimizer_pb2.py (see down below).

**part of   optimizer_pb2.py**

_LEARNINGRATE = _descriptor.Descriptor(
  name='LearningRate',
  full_name='object_detection.protos.LearningRate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='constant_learning_rate', full_name='object_detection.protos.LearningRate.constant_learning_rate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exponential_decay_learning_rate', full_name='object_detection.protos.LearningRate.exponential_decay_learning_rate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manual_step_learning_rate', full_name='object_detection.protos.LearningRate.manual_step_learning_rate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cosine_decay_learning_rate', full_name='object_detection.protos.LearningRate.cosine_decay_learning_rate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      **name='cyclic_learning_rate', full_name='object_detection.protos.LearningRate.cyclic_learning_rate', index=4,**
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='learning_rate', full_name='object_detection.protos.LearningRate.learning_rate',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=768,
  serialized_end=1229,
)

--------------------------------------------------------------------------------------------------------------------------------------
**4. System information**

- Nvidia Tensorflow Container (nvcr.io/nvidia/tensorflow:20.10-tf1-py3) 
- Ubuntu18.04
- Tensorflow 1.15.4
- Cuda 11.1.0
- cuDNN 8.0.4

---------------------------------------------------------------------------------------------------------------------------------------------
If I can provide any more information just ask please. If it is necesarry I can also send a docker image.  

Cheers

**Comment by DemolationPeter** [comment]
I have found the solution.

The problem was that the changed files weren't in the correct folder. You need to copy them into the path from your python Version. Inside the directory of Python /site_packages is a directory /object_detection and  a directory /object_detection-0.1-py3.6.egg (name can be different). Inside the /object_detection-0.1-py3.6.egg directory you have also the folder /protos, /builders, /utils etc. I copied the needed files also inside these folders. Don't ask me why I needed to copy them inside these folders. It wasn't enough to copy them inside the directory which you create when you download the ObjectDetectionAPI repository and used inside these directory the setup.py for the installation. Inside my conda enviroment on the desktop it isn't needed (maybe it is a Pythonpath issue). But know I can use the CyclicalLearningRate inside my Nvidia Tensorflow Docker Container.

Inside the NvidiaDocker Container you can find the /object_detection-0.1-py3.6.egg directory under these path /usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/ .

**Important**

- These is working for Tensorflow1.14 and the ObjectDetectionAPI folder (Date: 22.01.2021). 
- I used the Nvidia Tensorflow Container (Version: nvcr.io/nvidia/tensorflow:19.10-py3).
- I think it should work with TF1.15 also but not tested
- The Cyclical Learning Rate is probably not working for TF2 because of Code and Operation changes between TF1 and TF2. You can find the Code implementation inside the learning_schedules.py. Probably some of the operations are different in TF2 and you will get errors.
- The mode=3 (exponential decay cyclical learning rate) is not working. I don't know why but I never used it.
