### ISSUE TITLE
Error submitting Object Detection job to ai-platform

### ISSUE THREAD

**Issue by ecatkins** [tensorflow/models#9658]
I am using the instructions laid out in the documentation to submit a job to Google Clouds ai-platform. My pipeline runs correctly both locally and when deploying to a Google Cloud VM.

The command I am running is below, it is practically the same as the documentation, except updated for the latest runtime versions. I have also tried the GPU training instructions with the same result

```
cp object_detection/packages/tf2/setup.py .
gcloud ai-platform jobs submit training `whoami`_object_detection_`date +%m_%d_%Y_%H_%M_%S` \
    --job-dir=${MODEL_DIR} \
    --package-path ./object_detection \
    --module-name object_detection.model_main_tf2 \
    --runtime-version 2.3 \
    --python-version 3.7 \
    --scale-tier BASIC_TPU \
    --region us-central1 \
    -- \
    --use_tpu true \
    --model_dir=${MODEL_DIR} \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH}

```

In the AI Platform job details I am receiving the error message below. I have seen this error brought up in a couple of other places, including [here](https://github.com/tensorflow/tensorflow/issues/42076). But nothing is referenced, which it would appear I have the ability to configure in the context of submitting a job to the ai-platform

```
The replica master 0 exited with a non-zero status of 1. 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.7/site-packages/object_detection/model_main_tf2.py", line 31, in <module>
    import tensorflow.compat.v2 as tf
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/wrapt/importer.py", line 156, in load_module
    module = self.loader.load_module(fullname)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 436, in <module>
    _ll.load_library(_main_dir)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
```

**Comment by ravikyram** [comment]
@ecatkins 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).Please, let us know which TF version you are using?

Please, share complete code snippet with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by ecatkins** [comment]
@ravikyram Thanks for your response. 

The tensorflow/runtime version is [2.3](https://cloud.google.com/ai-platform/training/docs/runtime-version-list) as specified in the script above.

The script above is effectively my full code snippet as indicated by the notebook [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md). I am running on it using the up-to-date master branch of this repo. `$MODEL_DIR` and `$PIPELINE_CONFIG_PATH` point to my google cloud storage. 

I have attached below the config file I am using, but obviously it is custom to my dataset. 


[pipeline.txt](https://github.com/tensorflow/models/files/5858189/pipeline.txt)

**Comment by acidassassin** [comment]
I get the same issue when trying to retrain the SSD MobileNet V2 320x320 model on the GCP AI platform. I am using the statement inside a conda env.

**Comment by wanderlustzoe** [comment]
@tombstone 
@jch1 
@pkulzc 

i also get the same exact error. when submitting a job with tensorflow 2.5 in setup.py and a runtime version of 2.4 (because 2.5 is not out yet)

**Comment by wanderlustzoe** [comment]
@ecatkins , did you manage to find a resolution?

**Comment by mafshar** [comment]
@tombstone
@jch1
@pkulzc

I am also getting the same issue, specifically mine is 
```
Hyperparameter Tuning Trial #5 failed. 5 total hyperparameter trial failures were seen, out of 7 trials attempted which reaches the user-specified limit of 5.The last trial to fail was #5, with parameters: weight-decay=5.9464733774846743e-05, lr=1.3190903729304733e-05, length-penalty=0.72037500239037422, repetition-penalty=1.0766390111454258, freeze-weights=True, softmax-temp=0.61544765429837833, optimizer=Adam, .  The trial's error message was: The replica master 0 exited with a non-zero status of 1. Termination reason: Error. 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/.local/lib/python3.7/site-packages/half/sqgen/__init__.py", line 1, in <module>
    from tensorflow_transform.tf_metadata import schema_utils
  File "/root/.local/lib/python3.7/site-packages/tensorflow_transform/__init__.py", line 18, in <module>
    from tensorflow_transform import coders
  File "/root/.local/lib/python3.7/site-packages/tensorflow_transform/coders/__init__.py", line 16, in <module>
    from tensorflow_transform.coders.csv_coder import CsvCoder
  File "/root/.local/lib/python3.7/site-packages/tensorflow_transform/coders/csv_coder.py", line 25, in <module>
    import tensorflow as tf
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/wrapt/importer.py", line 156, in load_module
    module = self.loader.load_module(fullname)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 444, in <module>
    _ll.load_library(_main_dir)
  File "/root/.local/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow6thread10ThreadPool26TransformRangeConcurrentlyExxRKSt8functionIFvxxEE
```

Everything else is exactly like the people above.
