### ISSUE TITLE
I am getting error object_detection.builders import model_builder

### ISSUE THREAD

**Issue by mrjaved121** [tensorflow/models#9663]
![image](https://user-images.githubusercontent.com/44700120/105585354-875bd080-5d45-11eb-832a-510ef8671801.png)

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
2021-01-23 19:20:39.137987: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-01-23 19:20:39.157593: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 66
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
       ^
IndentationError: expected an indented block

**Comment by mrjaved121** [comment]
![image](https://user-images.githubusercontent.com/44700120/105596896-af006800-5d48-11eb-92a2-37ea8058a233.png)

**Comment by saikumarchalla** [comment]
@mrjaved121 Please check the indentation error  after the if statement(line num: 67). Also, see this [link](https://github.com/tensorflow/models/issues/1832) if it helps. Thanks!
