### ISSUE TITLE
not able to create model for export_inference_graph.py

### ISSUE THREAD

**Issue by rohit220594** [tensorflow/models#9679]
python3 export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_mobilenet_v1_pets.config --trained_checkpoint_prefix training/model.ckpt-2822 --output_directory inference_graph1
WARNING:tensorflow:From /Users/cronj/Documents/custom/models/research/object_detection/object_detection.py:64: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From /Users/cronj/Documents/custom/models/research/object_detection/object_detection.py:65: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "export_inference_graph.py", line 57, in <module>
    from object_detection import exporter
  File "/Users/cronj/Documents/custom/models/research/object_detection/object_detection.py", line 66, in <module>
    serialized_graph = fid.read()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /Users/cronj/Documents/custom/models/research/object_detection/inference_graph/frozen_inference_graph.pb; No such file or directory

i have model chekpoint and all from training .

**Comment by saikumarchalla** [comment]
@rohit220594  Could you please check whether the frozen_inference_graph.pb file is in proper path  or not. Thanks!
