### ISSUE TITLE
Creating TFRecords from COCO v1.0 Annotations

### ISSUE THREAD

**Issue by digiwang** [tensorflow/models#9697]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/beta/data/create_coco_tf_record.py

## 2. Describe the bug

There is one (1) bug and just two misspelled words (same variable misspelled twice, yay consistency haha), which is not the source of the issue, as far as I can tell, but I figured I would mention it for the sake of practicing good literacy.

**Misspelled variables**
line 290 and 293, read `caption_annotaion` but they think they should read `caption_annotation`.

**The bug**
I believe the bug only happens when no argument is passed to the `caption_annotations_file` parameter. When I left it blank, I received the following error:

```sh
(TF2) tstark@inference:~/TensorFlow$  cd /home/tstark/TensorFlow ; /usr/bin/env /home/tstark/TF2/bin/python /home/tstark/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/launcher 46527 -- /home/tstark/TensorFlow/models/official/vision/beta/data/create_coco_tf_record.py --logtostderr --image_dir=/home/tstark/TensorFlow/workspace/frames/test --object_annotations_file=/home/tstark/TensorFlow/workspace/coco/test.json --output_file_prefix=/home/tstark/TensorFlow/workspace/test/test 
2021-02-02 00:09:29.565043: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0202 00:09:35.856384 139915741054784 create_coco_tf_record.py:321] writing to output path: /home/tstark/TensorFlow/workspace/test/test
I0202 00:09:35.864160 139915741054784 create_coco_tf_record.py:234] Building bounding box index.
I0202 00:09:35.864521 139915741054784 create_coco_tf_record.py:245] 0 images are missing bboxes.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tstark/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/tstark/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/tstark/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tstark/TensorFlow/models/official/vision/beta/data/create_coco_tf_record.py", line 370, in <module>
    app.run(main)
  File "/home/tstark/TF2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/tstark/TF2/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/tstark/TensorFlow/models/official/vision/beta/data/create_coco_tf_record.py", line 366, in main
    FLAGS.include_masks)
  File "/home/tstark/TensorFlow/models/official/vision/beta/data/create_coco_tf_record.py", line 340, in _create_tf_record_from_coco_annotations
    output_path, coco_annotations_iter, create_tf_example, num_shards)
  File "/home/tstark/TensorFlow/models/official/vision/beta/data/tfrecord_lib.py", line 142, in write_tf_record_dataset
    tf_example_iterator = pool.starmap(process_func, annotation_iterator)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 376, in _map_async
    iterable = list(iterable)
  File "/home/tstark/TensorFlow/models/official/vision/beta/data/create_coco_tf_record.py", line 293, in generate_annotations
    caption_annotation, include_masks)
UnboundLocalError: local variable 'caption_annotation' referenced before assignment
```
I was able to get my work done by removing `caption_annotaion` from line 293 since I wasn't using them anyways.

## 3. Steps to reproduce

Do not pass an argument to the `"caption_annotations_file` parameter.

## 4. Expected behavior

I expected for the script to generate tfrecords for me even though I didn't have caption annotations to use as inputs.

## 5. Additional context

I included the error output I got from running the script through my debugger above.

## 6. System information

- OS Platform and Distribution: **Linux Ubuntu 18.04**
- TensorFlow installed from (source or binary): **installed from binary (i.e., pip install tensorflow)**
- TensorFlow version (use command below): **v2.4.0-49-g85c8b2a817f 2.4.1**
- Python version: **3.6.9 (default, Oct  8 2020, 12:12:24)**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **11.0.2/8.0.4.30 (NCCL Version 2.8.3-1)**
- GPU model and memory: **Tesla K80 11GB**

**Comment by saberkun** [comment]
Fixed by https://github.com/tensorflow/models/commit/fb6e611af030db2374230919d6467b23aa988388.
Thanks for reporting.
