### ISSUE TITLE
ValueError: faster_rcnn_inception_v2 is not supported. See `model_builder.py`.

### ISSUE THREAD

**Issue by MingshanHe** [tensorflow/models#9742]
Hello,

I am facing issue while trying to run below command:-

python3 object_detection/model_main_tf2.py --pipeline_config_path="/home/hemingshan/auto_ws/src/vision/models/research/config/ssd_inception_v2_coco.config" --model_dir="/home/hemingshan/auto_ws/src/models/model_dir" --alsologtostderr

Tensorflow Version:- 2.2.0
Python Version:- 3.8.5
OS :- Ubuntu 20.04 LTS

Please find below mentioned error message:-
2021-02-22 02:04:58.455369: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:There are non-GPU devices in tf.distribute.Strategy, not using nccl allreduce.
W0222 02:04:58.457545 140023730894656 cross_device_ops.py:1175] There are non-GPU devices in tf.distribute.Strategy, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0222 02:04:58.457746 140023730894656 mirrored_strategy.py:500] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: None
I0222 02:04:58.460945 140023730894656 config_util.py:552] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0222 02:04:58.461282 140023730894656 config_util.py:552] Maybe overwriting use_bfloat16: False
Traceback (most recent call last):
File "object_detection/model_main_tf2.py", line 113, in
tf.compat.v1.app.run()
File "/home/hemingshan/.local/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
_run_main(main, args)
File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
sys.exit(main(argv))
File "object_detection/model_main_tf2.py", line 104, in main
model_lib_v2.train_loop(
File "/home/hemingshan/auto_ws/src/vision/models/research/object_detection/model_lib_v2.py", line 515, in train_loop
detection_model = MODEL_BUILD_UTIL_MAP['detection_model_fn_base'](
File "/home/hemingshan/auto_ws/src/vision/models/research/object_detection/builders/model_builder.py", line 1110, in build
return build_func(getattr(model_config, meta_architecture), is_training,
File "/home/hemingshan/auto_ws/src/vision/models/research/object_detection/builders/model_builder.py", line 377, in _build_ssd_model
_check_feature_extractor_exists(ssd_config.feature_extractor.type)
File "/home/hemingshan/auto_ws/src/vision/models/research/object_detection/builders/model_builder.py", line 249, in _check_feature_extractor_exists
raise ValueError('{} is not supported. See model_builder.py for features '
ValueError: ssd_inception_v2 is not supported. See model_builder.py for features extractors compatible with different versions of Tensorflow
Please help me to fix this issue.

Thanks,
Beal. MS

**Comment by MingshanHe** [comment]
I think I need to fix the type of feature_extractor but I don`t know what to change.

**Comment by MingshanHe** [comment]
I change it to 'ssd_mobilenet_v2_keras' and it can be run . but there are any other mistake.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
W0222 02:45:25.307474 140529359337280 util.py:151] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
