### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by wolf-hash** [tensorflow/models#9749]
### While trying to train a model on custom data set I'm getting this error related to import of pycocotools._mask as _mask
```Traceback (most recent call last):
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "/home/wolf/anaconda3/envs/tf_gest_api/lib/python3.7/site-packages/object_detection/model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "/home/wolf/anaconda3/envs/tf_gest_api/lib/python3.7/site-packages/object_detection/eval_util.py", line 35, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/wolf/anaconda3/envs/tf_gest_api/lib/python3.7/site-packages/object_detection/metrics/coco_evaluation.py", line 25, in <module>
    from object_detection.metrics import coco_tools
  File "/home/wolf/anaconda3/envs/tf_gest_api/lib/python3.7/site-packages/object_detection/metrics/coco_tools.py", line 51, in <module>
    from pycocotools import coco
  File "/home/wolf/anaconda3/envs/tf_gest_api/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/wolf/anaconda3/envs/tf_gest_api/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject```

**Comment by ravikyram** [comment]
@wolf-hash 

Please, share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by JariWarmerdam** [comment]
I don't know if you fixed this problem but this thread has helped me fix the same problem: https://stackoverflow.com/questions/66373169/tensorflow-2-object-detection-api-numpy-version-errors,
if you do pip uninstall pycocotools and do pip install pycocotools-windows the error should be gone
only now I get another error but maybe you don't

**Comment by wolf-hash** [comment]
> I don't know if you fixed this problem but this thread has helped me fix the same problem: https://stackoverflow.com/questions/66373169/tensorflow-2-object-detection-api-numpy-version-errors,
> if you do pip uninstall pycocotools and do pip install pycocotools-windows the error should be gone
> only now I get another error but maybe you don't

Hey thanks a lot. This fixed the problem for me!
