### ISSUE TITLE
Basic import failures when running resnet_cifar_main.py

### ISSUE THREAD

**Issue by shankgan** [tensorflow/models#9755]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using
https://github.com/tensorflow/models/blob/r2.4.0/official/benchmark/models/resnet_cifar_main.py

Bug occurs because of using this module - 
https://github.com/tensorflow/models/blob/r2.4.0/official/utils/misc/keras_utils.py

## 2. Describe the bug
Tried to deploy a dockerized image of [resnet_cifar](https://github.com/tensorflow/models/blob/r2.4.0/official/benchmark/models/resnet_cifar_main.py) in kubernetes. This failed with import errors. Then tried the same on my MacBook Pro on the python interpreter. Ran through same import statements in the file -

Saw the following problem - 
```
Python 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from models.official.utils.misc import keras_utils
>>> from models.official.vision.image_classification.resnet import common
2021-02-26 09:45:03.574945: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/training/global_batch_size
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shankgan/random_repos/models/official/vision/image_classification/resnet/common.py", line 28, in <module>
    from official.utils.misc import keras_utils
  File "/Users/shankgan/Library/Python/3.8/lib/python/site-packages/official/utils/misc/keras_utils.py", line 30, in <module>
    global_batch_size_gauge = monitoring.IntGauge(
  File "/Users/shankgan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/eager/monitoring.py", line 243, in __init__
    super(IntGauge, self).__init__('IntGauge', _int_gauge_methods, len(labels),
  File "/Users/shankgan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/eager/monitoring.py", line 126, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

Version of tensorflow :- 2.4.0
Branch of model garden repo :- r2.4.0

It appears that importing (https://github.com/tensorflow/models/blob/r2.4.0/official/utils/misc/keras_utils.py) twice fails because of lines 30-38. 

## 3. Steps to reproduce
Clone model garden repo. Switch to branch r2.4.0. 
Add [model garden repo to python path](https://github.com/tensorflow/models/tree/r2.4.0/official) as "**models**". Then 
```

shankgan-macbookpro:random_repos shankgan$ python3
Python 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from models.official.utils.misc import keras_utils
>>> from models.official.vision.image_classification.resnet import common
2021-02-26 09:45:03.574945: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/training/global_batch_size
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shankgan/random_repos/models/official/vision/image_classification/resnet/common.py", line 28, in <module>
    from official.utils.misc import keras_utils
  File "/Users/shankgan/Library/Python/3.8/lib/python/site-packages/official/utils/misc/keras_utils.py", line 30, in <module>
    global_batch_size_gauge = monitoring.IntGauge(
  File "/Users/shankgan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/eager/monitoring.py", line 243, in __init__
    super(IntGauge, self).__init__('IntGauge', _int_gauge_methods, len(labels),
  File "/Users/shankgan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/eager/monitoring.py", line 126, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Os X Big Sur, Version 11.2.1. Note problem also happened in docker image corresponding to tensorflow:nightly. Not sure which OS that uses. 
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 2.4.0
- Python version:Python 3.8.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by zacps** [comment]
This issue also occurs with the Spectral Normalized Gaussian Processes (SNGP) notebook [on collab](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/understanding/sngp.ipynb).

Is there a workaround?

**Comment by dpostolovski** [comment]
https://github.com/tensorflow/tensorflow/issues/32574#issuecomment-532428339
This might be a clue why the imports are broken. 

```
Note that both importing from tensorflow_core and directly importing from .python are not supported and will break without any rollback.

The recommended way to use TensorFlow is import tensorflow as tf and accessing the API via the tf symbol and it's attributes.
```

**Comment by laxmareddyp** [comment]
Hi All,

This issue was addressed in latest tensor flow version release and can close as it is fixed.

Thanks.
