### ISSUE TITLE
im2txt:   Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 

### ISSUE THREAD

**Issue by loveJasmine** [tensorflow/models#977]
mldl@mldlUB1604:/media/mldl/data1t/os_prj/models/im2txt$ sudo bazel-bin/im2txt/train   --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=1000000
[sudo] password for mldl: 
2017-02-05 06:21:22: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
2017-02-05 06:21:22: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
2017-02-05 06:21:22: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
2017-02-05 06:21:22: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
2017-02-05 06:21:22: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
INFO:tensorflow:Creating training directory: /media/mldl/data1t/os_prj/models/im2txt/im2txt/model/train
INFO:tensorflow:Prefetching values from 256 files matching /media/mldl/data1t/os_prj/models/im2txt/data/mscoco/train-?????-of-00256
2017-02-05 06:21:42: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-05 06:21:42: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-02-05 06:21:42: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-05 06:21:42: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-02-05 06:21:42: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:911] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-02-05 06:21:42: I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.43GiB
2017-02-05 06:21:42: I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
2017-02-05 06:21:42: I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
2017-02-05 06:21:42: I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
INFO:tensorflow:Restoring Inception variables from checkpoint file 
2017-02-05 06:22:03: W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
.................
2017-02-05 07:33:17: W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-02-05 07:33:28: W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-02-05 07:33:40: W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-02-05 07:33:46: W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
	 [[Node: save/RestoreV2_121 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_121/tensor_names, save/RestoreV2_121/shape_and_slices)]]
	 [[Node: save/RestoreV2_108/_541 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1663_save/RestoreV2_108", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_121', defined at:
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 357, in build
    self.setup_inception_initializer()
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 332, in setup_inception_initializer
    saver = tf.train.Saver(self.inception_variables)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
	 [[Node: save/RestoreV2_121 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_121/tensor_names, save/RestoreV2_121/shape_and_slices)]]
	 [[Node: save/RestoreV2_108/_541 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1663_save/RestoreV2_108", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Traceback (most recent call last):
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 110, in main
    saver=saver)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/contrib/slim/python/slim/learning.py", line 776, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/supervisor.py", line 973, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/supervisor.py", line 801, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/supervisor.py", line 962, in managed_session
    start_standard_services=start_standard_services)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/supervisor.py", line 719, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/session_manager.py", line 264, in prepare_session
    init_fn(sess)
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 337, in restore_fn
    saver.restore(sess, self.config.inception_checkpoint_file)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
	 [[Node: save/RestoreV2_121 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_121/tensor_names, save/RestoreV2_121/shape_and_slices)]]
	 [[Node: save/RestoreV2_108/_541 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1663_save/RestoreV2_108", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_121', defined at:
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    tf.app.run()
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    model.build()
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 357, in build
    self.setup_inception_initializer()
  File "/media/mldl/data1t/os_prj/models/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 332, in setup_inception_initializer
    saver = tf.train.Saver(self.inception_variables)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/media/mldl/data1t/ub16_prj/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
	 [[Node: save/RestoreV2_121 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_121/tensor_names, save/RestoreV2_121/shape_and_slices)]]
	 [[Node: save/RestoreV2_108/_541 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1663_save/RestoreV2_108", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

mldl@mldlUB1604:/media/mldl/data1t/os_prj/models/im2txt$ 
mldl@mldlUB1604:/media/mldl/data1t/os_prj/models/im2txt$ 
mldl@mldlUB1604:/media/mldl/data1t/os_prj/models/im2txt$

**Comment by girving** [comment]
What path are you giving it?  Are there files there?

**Comment by loveJasmine** [comment]
I misconfig the path, sorry
