### ISSUE TITLE
--strategy_type=mirrored doesn't seem to utilize multiple GPUs and throwing ValueError with total_loss NaN

### ISSUE THREAD

**Issue by chudur-budur** [tensorflow/models#9831]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/vision/detection/main.py

## 2. Describe the bug

I have 2 GPUs, when I run the retinanet code, and check my GPU (`nvidia-smi`), I'm seeing only one GPU has been used. 

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0    33W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:05.0 Off |                    0 |
| N/A   58C    P0   277W / 300W |  15574MiB / 16160MiB |     99%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A     10910      C   python3                         15569MiB |
+-----------------------------------------------------------------------------+
```

and after a while, it gives me a `ValueError`:
```
Traceback (most recent call last):
  File "$HOME/models/official/vision/detection/main.py", line 265, in <module>
    app.run(main)
  File "$HOME/.local/share/virtualenvs/models-4FBaKOtf/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "$HOME/.local/share/virtualenvs/models-4FBaKOtf/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "$HOME/models/official/vision/detection/main.py", line 260, in main
    run()
  File "$HOME/models/official/vision/detection/main.py", line 248, in run
    return run_executor(
  File "$HOME/models/official/vision/detection/main.py", line 119, in run_executor
    return dist_executor.train(
  File "$HOME/models/official/vision/detection/executor/distributed_executor.py", line 502, in train
    raise ValueError('total loss is NaN.')
ValueError: total loss is NaN.
```

## 3. Steps to reproduce
I'm running on coco2014 dataset. Converting them to TFRecords with [this code](https://github.com/chudur-budur/models/blob/master/research/object_detection/dataset_tools/create_coco_tf_record.py), using [this script](https://github.com/chudur-budur/models/blob/master/coco2tfr.sh).

After conversion, I'm running the code using [this script](https://github.com/chudur-budur/models/blob/master/train.sh). Which looks like this:
```
PROJ_HOME="$HOME/models"
MODEL_DIR="$HOME/experiments/models/retinanet"
CUDA_VISIBLE_DEVICES=1 PYTHONPATH=$PROJ_HOME python3 $PROJ_HOME/official/vision/detection/main.py \
    --strategy_type=mirrored \
    --num_gpus=2 \
    --model_dir="${MODEL_DIR?}" \
    --mode=train \
    --config_file="$PROJ_HOME/configs/retinanet.yaml"
```

The `retinanet.yaml` is [here](https://github.com/chudur-budur/models/blob/master/configs/retinanet.yaml) and looks like this:

```
type: 'retinanet'
train:
    train_file_pattern: '$HOME/tfr2014/coco_train.*'
    batch_size: 8
eval:
    eval_file_pattern: '$HOME/tfr2014/coco_val.*'
    val_json_file: '$HOME/coco2014/annotations/instances_val2014.json'
    batch_size: 1
```

## 4. Expected behavior

I was expecting both GPUs to be utilized and that should reflect in the 2nd row of the `nvidia-smi` output above, also it should run without giving any `ValueError`.

## 5. Additional context

Model parameters:
```
{'anchor': {'anchor_size': 4.0,
            'aspect_ratios': [1.0, 2.0, 0.5],
            'num_scales': 3},
 'architecture': {'backbone': 'resnet',
                  'max_level': 7,
                  'min_level': 3,
                  'multilevel_features': 'fpn',
                  'num_classes': 91,
                  'parser': 'retinanet_parser',
                  'use_bfloat16': False},
 'enable_summary': True,
 'eval': {'batch_size': 1,
          'eval_dataset_type': 'tfrecord',
          'eval_file_pattern': '$HOME/tfr2014/coco_val.*',
          'eval_samples': 5000,
          'eval_timeout': None,
          'input_sharding': True,
          'min_eval_interval': 180,
          'num_images_to_visualize': 0,
          'num_steps_per_eval': 1000,
          'type': 'box',
          'use_json_file': True,
          'val_json_file': '$HOME/coco2014/annotations/instances_val2014.json'},
 'fpn': {'fpn_feat_dims': 256,
         'use_batch_norm': True,
         'use_separable_conv': False},
 'isolate_session_state': False,
 'model_dir': '$HOME/experiments/models/retinanet',
 'norm_activation': {'activation': 'relu',
                     'batch_norm_epsilon': 0.0001,
                     'batch_norm_momentum': 0.997,
                     'batch_norm_trainable': True,
                     'use_sync_bn': False},
 'postprocess': {'max_total_size': 100,
                 'nms_iou_threshold': 0.5,
                 'pre_nms_num_boxes': 5000,
                 'score_threshold': 0.05,
                 'use_batched_nms': False},
 'predict': {'batch_size': 8},
 'resnet': {'resnet_depth': 50},
 'retinanet_head': {'num_convs': 4,
                    'num_filters': 256,
                    'use_separable_conv': False},
 'retinanet_loss': {'box_loss_weight': 50,
                    'focal_loss_alpha': 0.25,
                    'focal_loss_gamma': 1.5,
                    'huber_loss_delta': 0.1},
 'retinanet_parser': {'aug_rand_hflip': True,
                      'aug_scale_max': 1.0,
                      'aug_scale_min': 1.0,
                      'autoaugment_policy_name': 'v0',
                      'match_threshold': 0.5,
                      'max_num_instances': 100,
                      'num_channels': 3,
                      'output_size': [640, 640],
                      'skip_crowd_during_training': True,
                      'unmatched_threshold': 0.5,
                      'use_autoaugment': False},
 'spinenet': {'model_id': '49'},
 'strategy_config': {'all_reduce_alg': None,
                     'distribution_strategy': 'mirrored',
                     'num_gpus': 2,
                     'num_packs': 1,
                     'task_index': -1,
                     'tpu': None,
                     'worker_hosts': None},
 'strategy_type': 'mirrored',
 'train': {'batch_size': 8,
           'checkpoint': {'path': '', 'prefix': ''},
           'frozen_variable_prefix': '',
           'gradient_clip_norm': 0.0,
           'input_partition_dims': None,
           'input_sharding': False,
           'iterations_per_loop': 100,
           'l2_weight_decay': 0.0001,
           'learning_rate': {'init_learning_rate': 0.08,
                             'learning_rate_levels': [0.008, 0.0008],
                             'learning_rate_steps': [15000, 20000],
                             'type': 'step',
                             'warmup_learning_rate': 0.0067,
                             'warmup_steps': 500},
           'num_cores_per_replica': None,
           'optimizer': {'momentum': 0.9, 'nesterov': True, 'type': 'momentum'},
           'regularization_variable_regex': '.*(kernel|weight):0$',
           'total_steps': 22500,
           'train_dataset_type': 'tfrecord',
           'train_file_pattern': '$HOME/tfr2014/coco_train.*',
           'transpose_input': False},
 'type': 'retinanet',
 'use_tpu': False}
```

When I print the `train_loss` before line 502, `official/vision/detection/executor/distributed_executor.py"` I get this:

```
train_loss: {
    'total_loss': <tf.Tensor: shape=(), dtype=float32, numpy=nan>, 
    'cls_loss': <tf.Tensor: shape=(), dtype=float32, numpy=nan>, 
    'box_loss': <tf.Tensor: shape=(), dtype=float32, numpy=0.011734616>, 
    'model_loss': <tf.Tensor: shape=(), dtype=float32, numpy=nan>, 
    'l2_regularization_loss': <tf.Tensor: shape=(), dtype=float32, numpy=nan>
}
```

I'm seeing everything is `nan` except the `box_loss`.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.0  
- GPU model and memory: 2 x NVIDIA Tesla V100 16GB

**Comment by gagika** [comment]
NaN issue should be solved by this [commit](https://github.com/tensorflow/models/commit/96eed9050def51e50e3c3d8dfc60290230afe7bd).
Please try again and comment if any errors occur.
Also you might try higher batch size, e.g. 16.
