### ISSUE TITLE
OP_REQUIRES failed at xla_ops.cc:489 : Not found: ./bin/ptxas not found

### ISSUE THREAD

**Issue by Nason-S** [tensorflow/models#9847]
## 1. The entire URL of the file you are using

https://pypi.org/project/tensorflow-gpu/1.15.0/

## 2. Describe the bug
XLA doesn't work with with tf 1.15 GPU. Can run XLA with CPU just fine. 
 
Trying to run some scripts on tf 1.15 and it seems to fail as pxtas is not found.

## 3. Steps to reproduce

Setup anaconda environment:
`$conda create --name tfgpu_15 tensorflow-gpu=1.15 python=3.7 `

Then run this bench mark script:

```
## BENCH MARK 1  - XLA works on GPU
import tensorflow as tf
try:
  with tf.device('device:XLA_GPU:0'):
    a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.linalg.matmul(a, b)
    print(c)
except RuntimeError as e:
  print(e)


## BENCH MARK 2  - XLA doesn't work on GPU
from tensorflow.contrib import rnn
import numpy as np
from tensorflow.python.framework import dtypes

import time
# Import MINST data


from tensorflow.contrib.rnn.python.ops import fused_rnn_cell

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)


# '''
# To classify images using a reccurent neural network, we consider every image
# row as a sequence of pixels. Because MNIST image shape is 28*28px, we will then
# handle 28 sequences of 28 steps for every sample.
# '''

# In[2]:

# Parameters
learning_rate = 0.001
training_iters = 10
batch_size = 128
display_step = 10

# Network Parameters
n_input = 28 # MNIST data input (img shape: 28*28)
n_steps = 28 # timesteps
n_hidden = 128 # hidden layer num of features
n_classes = 10 # MNIST total classes (0-9 digits)

# tf Graph input
x = tf.placeholder("float", [None, n_steps, n_input])
y = tf.placeholder("float", [None, n_classes])

# Define weights
weights = {
    'out': tf.Variable(tf.random_normal([n_hidden, n_classes]))
}
biases = {
    'out': tf.Variable(tf.random_normal([n_classes]))
}


# In[3]:

def RNN(x, weights, biases):

    # Prepare data shape to match `rnn` function requirements
    # Current data input shape: (batch_size, n_steps, n_input)
    # Required shape: 'n_steps' tensors list of shape (batch_size, n_input)
    x = tf.transpose(x, [1, 0, 2])
    # Reshaping to (n_steps*batch_size, n_input)
    x = tf.reshape(x, [-1, n_input])
    # Split to get a list of 'n_steps' tensors of shape (batch_size, n_input)
    x = tf.split(x, n_steps, 0)

    # Define a lstm cell with tensorflow
    lstm_cell = rnn.BasicLSTMCell(n_hidden, forget_bias=1.0)

    # Get lstm cell output
    outputs, states = rnn.static_rnn(lstm_cell, x, dtype=tf.float32)

    # Linear activation, using rnn inner loop last output
    return tf.matmul(outputs[-1], weights['out']) + biases['out']

pred = RNN(x, weights, biases)

# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# Evaluate model
correct_pred = tf.equal(tf.argmax(pred,1), tf.argmax(y,1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initializing the variables
init = tf.global_variables_initializer()


# In[4]:

def benchmark(use_xla, use_gpu):

    # Launch the graph
    config = tf.ConfigProto(
        device_count = {'GPU': 0 if not use_gpu else 1}
    )
   
    if use_xla:
        config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1

    with tf.Session(config=config) as sess:
        sess.run(init)
        step = 1
        # Keep training until reach max iterations
        while step * batch_size < training_iters:
            batch_x, batch_y = mnist.train.next_batch(batch_size)
            # Reshape data to get 28 seq of 28 elements
            batch_x = batch_x.reshape((batch_size, n_steps, n_input))
            # Run optimization op (backprop)
            sess.run(optimizer, feed_dict={x: batch_x, y: batch_y})
            if step % display_step == 0:
                # Calculate batch accuracy
                acc = sess.run(accuracy, feed_dict={x: batch_x, y: batch_y})
                # Calculate batch loss
                loss = sess.run(cost, feed_dict={x: batch_x, y: batch_y})
                print ("Iter " + str(step*batch_size) + ", Minibatch Loss= " +                       "{:.6f}".format(loss) + ", Training Accuracy= " +                       "{:.5f}".format(acc))
            step += 1

        # Calculate accuracy for 128 mnist test images
        test_len = 128
        test_data = mnist.test.images[:test_len].reshape((-1, n_steps, n_input))
        test_label = mnist.test.labels[:test_len]

        t_start = time.time()
        total_steps = 500
        for i in range(total_steps):
            outs = sess.run(accuracy, feed_dict={x: test_data, y: test_label})
        tdiff = time.time() - t_start
        print( "XLA {} :{} inference steps took: {:.2f}".format(use_xla, total_steps, tdiff))
       

benchmark(False, False) 
benchmark(True, False)  
benchmark(False, True) 
benchmark(True, True)  



#Outputs Benchmark 1
# Tensor("MatMul_5:0", shape=(2, 2), dtype=float32, device=/device:XLA_GPU:0) 

#Outputs Benchmark 2
#benchmark(False, False) XLA False :500 inference steps took: 8.2
#benchmark(True, False)  XLA True :500 inference steps took: 76.69
#benchmark(False, True) XLA False :500 inference steps took: 2.31
#benchmark(True, True)  Fails with traceback below

```

Steps to reproduce the behavior.

## 4. Expected behavior

the following should return a inference time just as the other 3 bench mark conditions. 
benchmark(True, True)

## 5. Additional context

```
runcell('[4]', '/u/user1/code/tf_test')
Traceback (most recent call last):

  File "/u/user1/anaconda3/envs/NN_1/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)

  File "/u/user1/anaconda3/envs/NN_1/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)

  File "/u/user1/anaconda3/envs/NN_1/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)

NotFoundError: 2 root error(s) found.
  (0) Not found: ./bin/ptxas not found
	 [[{{node cluster_0_1/xla_compile}}]]
	 [[cluster_0_1/merge_oidx_0/_1]]
  (1) Not found: ./bin/ptxas not found
	 [[{{node cluster_0_1/xla_compile}}]]
0 successful operations.
0 derived errors ignored.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/u/user1/code/tf_test", line 161, in <module>
    benchmark(True, True)

  File "/u/user1/code/tf_test", line 157, in benchmark
    outs = sess.run(accuracy, feed_dict={x: test_data, y: test_label})

  File "/u/user1/anaconda3/envs/NN_1/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)

  File "/u/user1/anaconda3/envs/NN_1/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)

  File "/u/user1/anaconda3/envs/NN_1/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)

  File "/u/user1/anaconda3/envs/NN_1/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)

NotFoundError: 2 root error(s) found.
  (0) Not found: ./bin/ptxas not found
	 [[{{node cluster_0_1/xla_compile}}]]
	 [[cluster_0_1/merge_oidx_0/_1]]
  (1) Not found: ./bin/ptxas not found
	 [[{{node cluster_0_1/xla_compile}}]]
0 successful operations.
0 derived errors ignored.


2021-03-29 15:11:20.569956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Quadro M4000 major: 5 minor: 2 memoryClockRate(GHz): 0.7725
pciBusID: 0000:03:00.0
2021-03-29 15:11:20.570092: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-03-29 15:11:20.570146: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-03-29 15:11:20.570188: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-03-29 15:11:20.570231: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-03-29 15:11:20.570272: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-03-29 15:11:20.570313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-03-29 15:11:20.570357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-03-29 15:11:20.572963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-03-29 15:11:20.573076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-29 15:11:20.573104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-03-29 15:11:20.573132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2021-03-29 15:11:20.575987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7326 MB memory) -> physical GPU (device: 0, name: Quadro M4000, pci bus id: 0000:03:00.0, compute capability: 5.2)
2021-03-29 15:11:21.031918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-03-29 15:11:23.393553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-29 15:11:23.393608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
2021-03-29 15:11:23.495495: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1586] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2021-03-29 15:11:30.330503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-29 15:11:30.330587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
2021-03-29 15:12:02.247677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Quadro M4000 major: 5 minor: 2 memoryClockRate(GHz): 0.7725
pciBusID: 0000:03:00.0
2021-03-29 15:12:02.247866: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-03-29 15:12:02.247913: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-03-29 15:12:02.247954: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-03-29 15:12:02.247991: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-03-29 15:12:02.248028: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-03-29 15:12:02.248067: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-03-29 15:12:02.248123: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-03-29 15:12:02.249343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-03-29 15:12:02.249426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-29 15:12:02.249455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-03-29 15:12:02.249469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2021-03-29 15:12:02.250826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7326 MB memory) -> physical GPU (device: 0, name: Quadro M4000, pci bus id: 0000:03:00.0, compute capability: 5.2)
2021-03-29 15:12:02.789588: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2021-03-29 15:12:02.796917: I tensorflow/compiler/jit/xla_compilation_cache.cc:238] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2021-03-29 15:12:02.797972: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at xla_ops.cc:489 : Not found: ./bin/ptxas not found
```

Conda list:

```
(NN_1) bash-4.2$ conda list
# packages in environment at /u/user/anaconda3/envs/NN_1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.12.0           py37h06a4308_0  
alabaster                 0.7.12                   py37_0  
appdirs                   1.4.4                      py_0  
argh                      0.26.2                   py37_0  
astor                     0.8.1            py37h06a4308_0  
astroid                   2.5              py37h06a4308_1  
async_generator           1.10             py37h28b3542_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.6              pyhd3eb1b0_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
binutils_impl_linux-64    2.31.1               h6176602_1    anaconda
binutils_linux-64         2.31.1               h6176602_9    anaconda
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py37h27cfd23_1003  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.1.19            h06a4308_1  
certifi                   2020.12.5        py37h06a4308_0  
cffi                      1.14.5           py37h261ae71_0  
chardet                   4.0.0           py37h06a4308_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
colorama                  0.4.4              pyhd3eb1b0_0  
coverage                  5.5              py37h27cfd23_2  
cryptography              3.4.7            py37hd23ed53_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
cupti                     10.0.130                      0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.22          py37h2531618_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
docutils                  0.16                     py37_1  
entrypoints               0.3                      py37_0  
evtk                      1.1.1                    pypi_0    pypi
expat                     2.3.0                h2531618_2  
flake8                    3.9.0              pyhd3eb1b0_0  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   py37_1  
gast                      0.2.2                    py37_0  
gcc_impl_linux-64         7.3.0                habb00fd_1    anaconda
gcc_linux-64              7.3.0                h553295d_9    anaconda
glib                      2.68.0               h36276a3_0  
google-pasta              0.2.0                      py_0  
grpcio                    1.36.1           py37h2157cd5_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
gxx_impl_linux-64         7.3.0                hdf63c60_1    anaconda
gxx_linux-64              7.3.0                h553295d_9    anaconda
h5py                      2.10.0           py37hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
horovod                   0.19.5                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        3.7.3            py37h06a4308_1  
importlib_metadata        3.7.3                hd3eb1b0_1  
intel-openmp              2020.2                      254  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.21.0           py37hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
jedi                      0.17.2           py37h06a4308_1  
jeepney                   0.6.0              pyhd3eb1b0_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.7                      py_0  
jupyter_core              4.7.1            py37h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
keras-applications        1.0.8                      py_1  
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
keyring                   22.3.0           py37h06a4308_0  
kiwisolver                1.3.1                    pypi_0    pypi
lazy-object-proxy         1.6.0            py37h27cfd23_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.14.0               h8c45485_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                h2531618_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
llvmlite                  0.36.0                   pypi_0    pypi
markdown                  3.3.4            py37h06a4308_0  
markupsafe                1.1.1            py37h14c3975_1  
matplotlib                3.4.0                    pypi_0    pypi
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.3.0            py37h54f3939_0  
mkl_random                1.1.1            py37h0573a6f_0  
mpmath                    1.2.1                    pypi_0    pypi
mypy_extensions           0.4.3                    py37_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  he6710b0_1  
ndim                      0.1.4                    pypi_0    pypi
nest-asyncio              1.5.1              pyhd3eb1b0_0  
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
numpy-stl                 2.16.0                   pypi_0    pypi
numpydoc                  1.1.0              pyhd3eb1b0_1  
openssl                   1.1.1k               h27cfd23_0  
opt_einsum                3.1.0                      py_0  
orthopy                   0.8.5                    pypi_0    pypi
packaging                 20.9               pyhd3eb1b0_0  
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.4.3            py37h06a4308_1  
parso                     0.7.0                      py_0  
pathspec                  0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.1.2                    pypi_0    pypi
pip                       21.0.1           py37h06a4308_0  
pluggy                    0.13.1           py37h06a4308_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
protobuf                  3.14.0           py37h2531618_1  
psutil                    5.8.0            py37h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycparser                 2.20                       py_2  
pydocstyle                6.0.0              pyhd3eb1b0_0  
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.8.1              pyhd3eb1b0_0  
pylint                    2.7.2            py37h06a4308_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.17.3           py37h7b6447c_0  
pysdf                     0.1                      pypi_0    pypi
pysocks                   1.7.1                    py37_1  
python                    3.7.10               hdb3f193_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-utils              2.5.6                    pypi_0    pypi
pytz                      2021.1             pyhd3eb1b0_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     20.0.0           py37h2531618_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
quadpy                    0.16.6                   pypi_0    pypi
readline                  8.1                  h27cfd23_0  
regex                     2021.3.17        py37h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py37_1  
scipy                     1.6.2            py37h91f5cce_0  
secretstorage             3.3.1            py37h06a4308_0  
setuptools                52.0.0           py37h06a4308_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0           py37h06a4308_0  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
sphinx                    3.5.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
spyder                    4.2.5            py37h06a4308_0  
spyder-kernels            1.10.2           py37h06a4308_0  
sqlite                    3.35.2               hdfb4753_0  
symengine                 0.7.2                    pypi_0    pypi
sympy                     1.5.1                    pypi_0    pypi
tensorboard               1.15.0             pyhb230dea_0  
tensorflow                1.15.0          gpu_py37h0f0df58_0  
tensorflow-base           1.15.0          gpu_py37h9dcbed7_0  
tensorflow-estimator      1.15.1             pyh2649769_0  
tensorflow-gpu            1.15.0               h0d30ee6_0  
termcolor                 1.1.0            py37h06a4308_1  
testpath                  0.4.4              pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
toml                      0.10.2             pyhd3eb1b0_0  
tornado                   6.1              py37h27cfd23_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
transforms3d              0.3.1                    pypi_0    pypi
typed-ast                 1.4.2            py37h27cfd23_1  
typing                    3.7.4.3                  pypi_0    pypi
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py37h2531618_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
watchdog                  1.0.2            py37h06a4308_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.1                     py_0  
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1           py37h7b6447c_1  
wurlitzer                 2.0.1                    py37_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3 
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 7.9
- TensorFlow installed from (source or binary):  pip install tensorflow-gpu==1.15.0
- TensorFlow version (use command below): 1.15.0
- Python version: 3.7.10 
- CUDA/cuDNN version:  cudatoolkit - 10.0.130,  cudnn - 7.6.5           
- GPU model and memory:  Quadro M4000 (7326 MB )

**Comment by Nkosana-263** [comment]
Hi @Nason-S could you please try using 
```
conda create -n tf-gpu tensorflow-gpu=1.15 
conda activate tf-gpu
```
or

```
pip install tensorflow-gpu==1.15
```
and see if the error gets resolved. Good luck!

**Comment by Nason-S** [comment]
@Nkosana-263 No change, I get the same error. Any other ideas?

```

  File "/u/user/anaconda3/envs/tf-gpu15/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)

NotFoundError: 2 root error(s) found.
  (0) Not found: ./bin/ptxas not found
	 [[{{node cluster_0_1/xla_compile}}]]
  (1) Not found: ./bin/ptxas not found
	 [[{{node cluster_0_1/xla_compile}}]]
	 [[cluster_0_1/merge_oidx_0/_1]]
0 successful operations.
0 derived errors ignored.


```

**Comment by Nkosana-263** [comment]
Hi @Nason-S I've tried running your code using a globally installed version of tensorflow-gpu==1.15 via pip.
[Find the notebook here](https://colab.research.google.com/drive/1zTUrBtNBdu5pg01cWs1gf48fmAA_t3pu?usp=sharing)

I hope it helps. All the best!

**Comment by Nason-S** [comment]
`tf.__version__ returns 1.15.0` but I'm getting  same `Not found: ./bin/ptxas not found` error.

**Comment by Nkosana-263** [comment]
Then I think maybe `ptxas` might actually be in the system `PATH`.

You might find this thread [here l](https://github.com/tensorflow/tensorflow/issues/35423) helpful.

Good luck!

**Comment by Nason-S** [comment]
I'll take a loom, much appreciated sha!

**Comment by saikumarchalla** [comment]
@Nason-S  Any update on this? Is the issue resolved for you. If so, please go ahead and close the issue.Thanks!
