### ISSUE TITLE
model_main_tf2 -> Invoked with: None, 524288

### ISSUE THREAD

**Issue by Daboudette** [tensorflow/models#9864]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

I have this issue : 

```
>python model_main_tf2.py --model_dir=models/faster_rcnn_inception_resnet_v2/ 
pipeline_config=models/faster_rcnn_inception_resnet_v2/pipeline.config
2021-04-01 10:01:45.599626: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/usr/local/lib/python3.6/dist-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported).
 The versions of TensorFlow you are currently using is 2.3.0 and is not supported.
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version.
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
2021-04-01 10:01:47.795499: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-04-01 10:01:47.895219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:8e:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-04-01 10:01:47.903808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties:
pciBusID: 0000:9c:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-04-01 10:01:47.903854: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-04-01 10:01:47.906261: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-04-01 10:01:47.908093: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-04-01 10:01:47.908456: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-04-01 10:01:47.911005: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-04-01 10:01:47.912845: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-04-01 10:01:47.917731: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-04-01 10:01:47.932945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2021-04-01 10:01:47.933520: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-01 10:01:47.957330: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3000000000 Hz
2021-04-01 10:01:47.974563: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x728ae70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-01 10:01:47.974600: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-01 10:01:48.647795: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x72f8a40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-04-01 10:01:48.647873: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-PCIE-16GB, Compute Capability 7.0
2021-04-01 10:01:48.647897: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): Tesla V100-PCIE-16GB, Compute Capability 7.0
2021-04-01 10:01:48.660014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:8e:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-04-01 10:01:48.661051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties:
pciBusID: 0000:9c:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-04-01 10:01:48.661096: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-04-01 10:01:48.661160: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-04-01 10:01:48.661175: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-04-01 10:01:48.661189: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-04-01 10:01:48.661203: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-04-01 10:01:48.661217: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-04-01 10:01:48.661233: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-04-01 10:01:48.664443: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2021-04-01 10:01:48.664488: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-04-01 10:01:51.277278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-01 10:01:51.277330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1
2021-04-01 10:01:51.277341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N Y
2021-04-01 10:01:51.277348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   Y N
2021-04-01 10:01:51.311655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2994 MB memory) -> physical GPU (device: 0, name:Tesla V100-PCIE-16GB, pci bus id: 0000:8e:00.0, compute capability: 7.0)
2021-04-01 10:01:51.319807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 14729 MB memory) -> physical GPU (device: 1, name: Tesla V100-PCIE-16GB, pci bus id: 0000:9c:00.0, compute capability: 7.0)
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0401 10:01:51.357107 140248356579136 mirrored_strategy.py:341] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
Traceback (most recent call last):
  File "model_main_tf2.py", line 133, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 130, in main
    record_summaries=FLAGS.record_summaries)
  File "/tf/EPhotoCompteur_Object_Detection/models/research/object_detection/model_lib_v2.py", line 455, in train_loop
    pipeline_config_path, config_override=config_override)
  File "/tf/EPhotoCompteur_Object_Detection/models/research/object_detection/utils/config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python._pywrap_file_io.BufferedInputStream(arg0: str, arg1: int)

Invoked with: None, 524288
```

## 3. Steps to reproduce

I follow the step of the following link : https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#

And to train, run this code : 
`python model_main_tf2.py --model_dir=models/faster_rcnn_inception_resnet_v2/ 
--pipeline_config=models/faster_rcnn_inception_resnet_v2/pipeline.config`

## 4. Expected behavior

I have already train the same model on a different dataset, on the same container, and it has worked. 

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- TensorFlow version (use command below): 2.2.3
- Python version: 3.6.8
- CUDA/cuDNN version: 10.1.105/7.6.4.38
- GPU model and memory:

**Comment by Daboudette** [comment]
Can nobody help me ? :'(

**Comment by ECEN404Team34** [comment]
I'm having the same issue. Can run everything smoothly on my Windows 10 machine, but getting this error on a Linux server

**Comment by ECEN404Team34** [comment]
Forgot to run the file with the command line arguments, that solved it for me

https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#training-the-model

This has an example

**Comment by felipebutcher** [comment]
> I'm having the same issue. Can run everything smoothly on my Windows 10 machine, but getting this error on a Linux server

mine is the opposite. i can run on linux but getting this error on windows. lol

**Comment by Daboudette** [comment]
> 
> 
> Forgot to run the file with the command line arguments, that solved it for me
> 
> https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#training-the-model
> 
> This has an example

What do you mean ? Does my command line arguments look wrong ?
```
python model_main_tf2.py --model_dir=models/faster_rcnn_inception_resnet_v2/ --pipeline_config=models/faster_rcnn_inception_resnet_v2/pipeline.config
```

**Comment by felipebutcher** [comment]
Unbelievable. The fix for me in Windows was to change "--pipeline_config" to "--pipeline_config_path". According to the comment: https://github.com/tensorflow/models/issues/9057#issuecomment-683731749

@Daboudette you may try that too.

**Comment by Daboudette** [comment]
> 
> 
> Unbelievable. The fix for me in Windows was to change "--pipeline_config" to "--pipeline_config_path". According to the comment: [#9057 (comment)](https://github.com/tensorflow/models/issues/9057#issuecomment-683731749)
> 
> @Daboudette you may try that too.

Oh thanks ! I'm stupid ! I don't know why i have replaced "--pipeline_config_path" by "--pipeline_config" ! It's perfect !

**Comment by felipebutcher** [comment]
> > Unbelievable. The fix for me in Windows was to change "--pipeline_config" to "--pipeline_config_path". According to the comment: [#9057 (comment)](https://github.com/tensorflow/models/issues/9057#issuecomment-683731749)
> > @Daboudette you may try that too.
> 
> Oh thanks @felipebutcher ! I'm stupid ! I don't know why i have replaced "--pipeline_config_path" by "--pipeline_config" ! It's perfect !

The tutorial I followed had "--pipeline_config", maybe you followed the same tutorial, lol. Welcome!
