### ISSUE TITLE
inception: "TypeError: Expected int32, got list containing Tensors of type '_Message' instead."

### ISSUE THREAD

**Issue by haeusser** [tensorflow/models#987]
Steps to reproduce: follow the inception tutorial with TensorFlow 0.12.head installed.

When running training from scratch, I get:

```
$ bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/work/user/data/imagenet
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/usr/wiss/user/libs/tfmodels/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>
    tf.app.run()
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/wiss/user/libs/tfmodels/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 37, in main
    inception_train.train(dataset)
  File "/usr/wiss/user/libs/tfmodels/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 217, in train
    num_preprocess_threads=num_preprocess_threads)
  File "/usr/wiss/user/libs/tfmodels/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 136, in distorted_inputs
    num_readers=FLAGS.num_readers)
  File "/usr/wiss/user/libs/tfmodels/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 490, in batch_inputs
    example_serialized)
  File "/usr/wiss/user/libs/tfmodels/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 397, in parse_example_proto
    bbox = tf.concat(0, [ymin, xmin, ymax, xmax])
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1248, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/wiss/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

```

The problem is that some examples don't provide bounding boxes. In that case, xmin etc are all `[]` in which case concat fails.

**Comment by girving** [comment]
Seems like a bug.  The code you mention is https://github.com/tensorflow/models/blob/master/inception/inception/image_processing.py#L397.

@shlens What would be the right fix here?  I don't know the semantics of the surrounding non-tf code.  Might just need to explicitly set a dtype somewhere.

**Comment by haeusser** [comment]
@girving I think there are two issues:
1. `concat` expects non-scalars (hence `[ ]` is illegal)
2. `bbox` is piped through to `distort_image` which will fail if `bbox` doesn't contain anything (in image_processing.py, lines 222, 233

Therefore, I'd suggest to allow `bbox` to be `None` (should be checked for in L397ish) and react accordingly in `distort_image`.

**Comment by girving** [comment]
@haeusser [] is an empty list, not a scalar.

**Comment by shlens** [comment]
Unfortunately, the API for TF has changed and we have not had time to update this model. Contributions welcome.

In the mean time, https://github.com/tensorflow/models/tree/master/slim is available. It is a more modern implementation of Inception and has been updated AFAIK.

**Comment by jeremygoetz** [comment]
If I use version TF 0.11 will this avoid this issue. Also I followed https://github.com/tensorflow/models/pull/909/files/680218d8696d987a373101f252cd9eec73f22b3c so would I have to remove the changes to use TF 0.11

**Comment by xlhu19** [comment]
The same problem. Any solutions?

**Comment by tfboyd** [comment]
https://github.com/tensorflow/models/pull/1150   When submitted should fix your issue.
