### ISSUE TITLE
after typing this command python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config i am getting such erroor

### ISSUE THREAD

**Issue by DheerajTecheureka** [tensorflow/models#9879]
i am using tenserflow 2.20
intel i3 processor
without gpu
this is my first project so please pull me out from this error i have tried different option to fix this bt not grtting any output

Traceback (most recent call last):
  File "train.py", line 53, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\Dhira\anaconda3\envs\tensorflow1\lib\site-packages\slim-0.1-py3.5.egg\object_detection\builders\model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import context_rcnn_meta_arch
  File "C:\Users\Dhira\anaconda3\envs\tensorflow1\lib\site-packages\slim-0.1-py3.5.egg\object_detection\meta_architectures\context_rcnn_meta_arch.py", line 35, in <module>
    from object_detection.protos import faster_rcnn_pb2
  File "C:\Users\Dhira\anaconda3\envs\tensorflow1\lib\site-packages\slim-0.1-py3.5.egg\object_detection\protos\faster_rcnn_pb2.py", line 22, in <module>
    from object_detection.protos import fpn_pb2 as object__detection_dot_protos_dot_fpn__pb2
ImportError: cannot import name 'fpn_pb2'

**Comment by saikumarchalla** [comment]
@DheerajTecheureka  PTAL at this [issue](https://stackoverflow.com/questions/64853702/cannot-import-name-fpn-pb2-from-object-detection-protos).Thanks!
