### ISSUE TITLE
Bug in centernet object detection

### ISSUE THREAD

**Issue by ApproximateIdentity** [tensorflow/models#9880]
I'm running into a problem when going through this file:

https://github.com/sglvladi/TensorFlowObjectDetectionTutorial/blob/master/docs/source/auto_examples/plot_object_detection_checkpoint.rst

The plain English summary of the problem is the following: Going through that example fails when predicting on images. It throws an error about the tensor shapes being incorrect. I tracked down the commit in the tensorflow/models repo which causes this issue (see below), but I don't know how to adapt this example to the new repository. So basically I see at least two possibilities:

1. Is this a bug with tensorflow/models? In that case, it should be fixed here in this repo.
2. Is it something that should be changed in the tutorial example above? In that case, what needs changing? I'm new to tensorflow so I'm a bit at a loss...

## General description and system information

While going through this tutorial I ran into an issue:

https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_checkpoint.html

I am not sure if it is a bug in this repository or not (though it must be a bug in either this repository or the one with the tutorials). I have stripped down a simplified python script to exhibit the issue. I am also providing a script to build the necessary environment (at least on a system similar to my debian 11/testing/bullseye system). I have no GPU. My python was downloaded from the official site and compiled by myself. Here is some system information:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
$ python3.8 -V
Python 3.8.8
```

## Reproducing the necessary environment

Running the following bash script should rebuild the environment necessary to reproduce the bug:

`source_me.sh`

```bash
mkdir root && cd root

python3.8 -m venv venv
source venv/bin/activate

# Install these packages first so the installation doesn't fall down later
pip3 install -U pip wheel
pip3 install cython 

# Install the tensorflow models packages
git clone https://github.com/tensorflow/models.git
cd models/research
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
pip3 install .
cd ../..

# Download the model
wget download.tensorflow.org/models/object_detection/tf2/20200711/centernet_hg104_1024x1024_coco17_tpu-32.tar.gz
tar xf centernet_hg104_1024x1024_coco17_tpu-32.tar.gz
```

Next save the following python script inside the prior created `root/` directory:

`test.py`

```python
import tensorflow as tf

from object_detection.utils import config_util
from object_detection.builders import model_builder

import numpy as np
from PIL import Image

# Restore checkpoint
pipeline_config_path = "centernet_hg104_1024x1024_coco17_tpu-32/pipeline.config"
model_config = config_util.get_configs_from_pipeline_file(pipeline_config_path)['model']
detection_model = model_builder.build(model_config=model_config, is_training=False)
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt_path = 'centernet_hg104_1024x1024_coco17_tpu-32/checkpoint/ckpt-0'
ckpt.restore(ckpt_path).expect_partial()

image_path = "models/research/object_detection/test_images/image1.jpg"
image_np = np.array(Image.open(image_path))
image_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)
image, shapes = detection_model.preprocess(image_tensor)
prediction_dict = detection_model.predict(image, shapes)
```

## Bug produced by script with stack trace

Running the test script in the `root/` directory results in the following error (the exception is thrown on the final line of the test above):

```bash
(venv) $ python3 test.py
2021-04-08 16:04:52.091563: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-04-08 16:04:52.091586: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-04-08 16:04:53.390298: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-08 16:04:53.390411: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-04-08 16:04:53.390419: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-04-08 16:04:53.390433: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (xps13): /proc/driver/nvidia/version does not exist
2021-04-08 16:04:53.390566: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-08 16:04:53.391186: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-08 16:04:53.793067: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 134217728 exceeds 10% of free system memory.
2021-04-08 16:04:53.854163: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 134217728 exceeds 10% of free system memory.
2021-04-08 16:04:53.863445: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 134217728 exceeds 10% of free system memory.
2021-04-08 16:04:53.889863: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 134217728 exceeds 10% of free system memory.
2021-04-08 16:04:53.905967: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 135268352 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    prediction_dict = detection_model.predict(image, shapes)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/object_detection/meta_architectures/center_net_meta_arch.py", line 3288, in predict
    predictions[head_name] = [
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/object_detection/meta_architectures/center_net_meta_arch.py", line 3289, in <listcomp>
    head(feature) for (feature, head) in zip(features_list, heads)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 389, in call
    outputs = layer(inputs, **kwargs)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1008, in __call__
    self._maybe_build(inputs)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2710, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 198, in build
    self.kernel = self.add_weight(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 623, in add_weight
    variable = self._add_variable_with_custom_getter(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 805, in _add_variable_with_custom_getter
    new_variable = getter(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 130, in make_variable
    return tf_variables.VariableV1(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 206, in _variable_v1_call
    return previous_getter(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/ops/variable_scope.py", line 2604, in default_variable_creator
    return resource_variable_ops.ResourceVariable(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1574, in __init__
    self._init_from_args(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1712, in _init_from_args
    initial_value = initial_value()
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 81, in __call__
    return CheckpointInitialValue(
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 117, in __init__
    self.wrapped_value.set_shape(shape)
  File "/tmp/scratch/bug/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1215, in set_shape
    raise ValueError(
ValueError: Tensor's shape (3, 3, 256, 256) is not compatible with supplied shape (1, 1, 256, 90)
```

## Discussion about commit introducing the issue

I have narrowed down the commit that causes this bug (you can verify this using my approach above, just make sure you remember to re-generate the protos and re-run e.g. `pip3 install .`):

https://github.com/tensorflow/models/commit/6e5c5a1bd50e07aab485fddf7bab958b80d95bee

Running the script on `6e5c5a1bd50e07aab485fddf7bab958b80d95bee~1` results in no exception being thrown (in fact, if you plot the predictions using the visualization tools things are working I just decided to leave out the parts of the code that are not strictly necessary). Also note that I did test versions 2.2 and 2.3 of tensorflow, but those result in the same error.

The commit message shows that changes were made involving the centernet model so this seems not totally surprising. However, after reading the commit's message, code changes, and changes in the tests, I'm still not sure what changes I need to make for my test script to work. I presume it's pretty trivial, but I'm new to tensorflow so I can't sort it out myself.

Thanks for any help!

## Pip freeze

```
$ pip3 freeze
absl-py==0.12.0
apache-beam==2.28.0
astunparse==1.6.3
attrs==20.3.0
avro-python3==1.9.2.1
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
contextlib2==0.6.0.post1
crcmod==1.7
cycler==0.10.0
Cython==0.29.22
dataclasses==0.6
dill==0.3.1.1
dm-tree==0.1.5
docopt==0.6.2
fastavro==1.3.5
flatbuffers==1.12
future==0.18.2
gast==0.3.3
gin-config==0.4.0
google-api-core==1.26.3
google-api-python-client==2.1.0
google-auth==1.28.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.4
google-cloud-bigquery==2.13.1
google-cloud-core==1.6.0
google-crc32c==1.1.2
google-pasta==0.2.0
google-resumable-media==1.2.0
googleapis-common-protos==1.53.0
grpcio==1.32.0
h5py==2.10.0
hdfs==2.6.0
httplib2==0.17.4
idna==2.10
importlib-resources==5.1.2
joblib==1.0.1
kaggle==1.5.12
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
lvis==0.5.3
lxml==4.6.3
Markdown==3.3.4
matplotlib==3.4.1
mock==2.0.0
numpy==1.19.5
oauth2client==4.1.3
oauthlib==3.1.0
object-detection @ file:///home/twn/scratch/root/models/research
opencv-python==4.5.1.48
opencv-python-headless==4.5.1.48
opt-einsum==3.3.0
packaging==20.9
pandas==1.2.3
pbr==5.5.1
Pillow==8.2.0
promise==2.3
proto-plus==1.18.1
protobuf==3.15.7
psutil==5.8.0
py-cpuinfo==7.0.0
pyarrow==2.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.2
pycparser==2.20
pydot==1.4.2
pymongo==3.11.3
pyparsing==2.4.7
python-dateutil==2.8.1
python-slugify==4.0.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-learn==0.24.1
scipy==1.6.2
sentencepiece==0.1.95
seqeval==1.2.2
six==1.15.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-addons==0.12.1
tensorflow-datasets==4.2.0
tensorflow-estimator==2.4.0
tensorflow-hub==0.11.0
tensorflow-metadata==0.29.0
tensorflow-model-optimization==0.5.0
termcolor==1.1.0
text-unidecode==1.3
tf-models-official==2.4.0
tf-slim==1.1.0
threadpoolctl==2.1.0
tqdm==4.60.0
typeguard==2.12.0
typing-extensions==3.7.4.3
uritemplate==3.0.1
urllib3==1.26.4
Werkzeug==1.0.1
wrapt==1.12.1
```

**Comment by jartantupjar** [comment]
@ApproximateIdentity 
this issue seems to be related to the loading of the checkpoint version of the model. You can make it work with the saved_model/ folder like this:
```
#Import the required libraries for Object detection infernece
import time
import tensorflow as tf
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils
import os
import cv2
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
# setting min confidence threshold
MIN_CONF_THRESH=.6
#Loading the exported model from saved_model directory
PATH_TO_SAVED_MODEL =r'models/v2/centernet_hg104_key_512/saved_model'
print('Loading model...', end='')
start_time = time.time()
# LOAD SAVED MODEL AND BUILD DETECTION FUNCTION
detect_fn = tf.saved_model.load(PATH_TO_SAVED_MODEL)
end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))
# LOAD LABEL MAP DATA
PATH_TO_LABELS=r'object_detection/object_detection/data/mscoco_label_map.pbtxt'
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS,                                                                    use_display_name=True)
#Image file for inference
IMAGE_PATH=r'object_detection/object_detection/test_images/image1.jpg'
def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.
    Puts image into numpy array of shape (height, width, channels), where channels=3 for RGB to feed into tensorflow graph.
    Args:
      path: the file path to the image
    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB))
image_np = load_image_into_numpy_array(IMAGE_PATH)
# Running the infernce on the image specified in the  image path
# The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
input_tensor = tf.convert_to_tensor(image_np)
# The model expects a batch of images, so add an axis with `tf.newaxis`.
input_tensor = input_tensor[tf.newaxis, ...]
detections = detect_fn(input_tensor)

# All outputs are batches tensors.
# Convert to numpy arrays, and take index [0] to remove the batch dimension.
# We're only interested in the first num_detections.
num_detections = int(detections.pop('num_detections'))
detections = {key: value[0, :num_detections].numpy()
               for key, value in detections.items()}
detections['num_detections'] = num_detections
# detection_classes should be ints.
detections['detection_classes'] = detections['detection_classes'].astype(np.int64)
#print(detections['detection_classes'])
image_np_with_detections = image_np.copy()
viz_utils.visualize_boxes_and_labels_on_image_array(
      image_np_with_detections,
      detections['detection_boxes'],
      detections['detection_classes'],
      detections['detection_scores'],
      category_index,
      use_normalized_coordinates=True,
      max_boxes_to_draw=200,
      min_score_thresh=MIN_CONF_THRESH,
      agnostic_mode=False)
plt.figure()
plt.imshow(image_np_with_detections)
print('Done')
plt.show()
```

**Comment by ApproximateIdentity** [comment]
@jartantupjar thanks for the response, but I don't really understand your code. Your code has the line

```
PATH_TO_SAVED_MODEL =r'models/v2/centernet_hg104_key_512/saved_model'
```

but I'm not sure where that is coming from. Can you start with the code that I posted above? If you run the `source_me.sh` and then the `test.py` scripts we'll at least be talking about exactly the same thing.

Of if you'd prefer your script, could you give me instructions for running it? I.e. if what you posted is called say `test.py`, then I should be able to execute `python3 test.py` and not have any errors. But that requires, for instance, for paths like `'models/v2/centernet_hg104_key_512/saved_model'` to actually exist so you'd need to explain where that is coming from.

In any case, thanks for the help!

**Comment by jartantupjar** [comment]
@ApproximateIdentity  Okay. So essentially it is like test.py. You can save it as a separate script called "test1.py", then replace the following assuming you are using the same paths you've mentioned above:
```
PATH_TO_SAVED_MODEL=r'centernet_hg104_1024x1024_coco17_tpu-32/saved_model'
PATH_TO_LABELS=r'models/research/object_detection/data/mscoco_label_map.pbtxt'
IMAGE_PATH=r'models/research/object_detection/test_images/image1.jpg'
```

**Comment by jartantupjar** [comment]
@ApproximateIdentity  Also for reference, you can get better code comments from the source [inference from saved model](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_saved_model.html)

**Comment by ApproximateIdentity** [comment]
Thanks a lot! So if I take your version and translate it into my stripped-down simplified format, it would look like this:

```
import tensorflow as tf

import numpy as np
from PIL import Image

saved_model_path = 'centernet_hg104_1024x1024_coco17_tpu-32/saved_model'
detect_fn = tf.saved_model.load(saved_model_path)

image_path = 'models/research/object_detection/test_images/image1.jpg'
image_np = np.array(Image.open(image_path))
image_tensor = tf.convert_to_tensor(image_np)
image_tensor = image_tensor[tf.newaxis, ...]
detections = detect_fn(image_tensor)
```

Note that I changed your version to use PIL like mine, but that doesn't make a difference in this case (though interestingly the image loaded in does vary extremely slightly in a few pixels so PIL and cv2 must use different algorithms for this).

**Comment by ApproximateIdentity** [comment]
I sorted on the problem. It is a slight mistake in the logic of this commit: https://github.com/tensorflow/models/commit/6e5c5a1bd50e07aab485fddf7bab958b80d95bee

This issue is in the following line:

https://github.com/tensorflow/models/blob/6e5c5a1bd50e07aab485fddf7bab958b80d95bee/research/object_detection/builders/model_builder.py#L950

That evaluates to `True` even if the pipeline config does not have the `center_head_params` set to anything. Looking at the code it's clear that assume default is to have the following parameters in the config:

```
      center_head_params: {
        num_filters: 256
        kernel_sizes: 3
      }
```

It is very odd that `bool(oc_config.center_head_params)` is `True` even when no parameters are set (if you print out the object at that point you even get nothing), but I think that might be a bug in the implementation of the code parsing the config. Regardless, a fix is to change the line to something like

```
if oc_config.center_head_params.num_filters and oc_config.center_head_params.kernel_sizes:
```

That restores the original default behavior and seems to match the author's intent. I'll open a PR.

**Comment by ApproximateIdentity** [comment]
This bug was fixed in this commit: https://github.com/tensorflow/models/commit/d7a784e6a85528292abf960be3a7cc643fa2b02c
