### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:/tensorflow1/models/research/object_detection/training/label_map.pbtxt : The system cannot find the file specified. ; No such file or directory

### ISSUE THREAD

**Issue by CaptainOrigami** [tensorflow/models#9898]
I try and run training using this command in an anaconda virtual environment: 

python model_main_tf2.py --pipeline_config_path=training/ssd_mobilenet_v2_320x320_coco17_tpu-8.config --model_dir=training --alsologtostderr

I get this error message: 

2021-04-12 18:37:04.088113: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-12 18:37:06.655223: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-12 18:37:06.656013: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-04-12 18:37:06.684835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2021-04-12 18:37:06.684996: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-12 18:37:06.692284: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-12 18:37:06.692377: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-12 18:37:06.695732: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-12 18:37:06.696829: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-12 18:37:06.703113: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-12 18:37:06.705500: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-12 18:37:06.706084: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-12 18:37:06.706239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-12 18:37:06.706646: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-12 18:37:06.707440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2021-04-12 18:37:06.707535: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-12 18:37:06.707817: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-12 18:37:06.708072: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-12 18:37:06.708330: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-12 18:37:06.708561: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-12 18:37:06.708795: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-12 18:37:06.709074: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-12 18:37:06.709325: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-12 18:37:06.709636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-12 18:37:07.174427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-12 18:37:07.174619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-04-12 18:37:07.175352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-04-12 18:37:07.175683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6637 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-04-12 18:37:07.176314: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I0412 18:37:07.177573  5168 mirrored_strategy.py:350] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: None
I0412 18:37:07.181586  5168 config_util.py:552] Maybe overwriting train_steps: None
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0412 18:37:07.181586  5168 config_util.py:552] Maybe overwriting use_bfloat16: False
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\model_lib_v2.py:546: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0412 18:37:07.458816  5168 deprecation.py:339] From C:\tensorflow1\models\research\object_detection\model_lib_v2.py:546: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\capta\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\capta\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "C:\tensorflow1\models\research\object_detection\model_lib_v2.py", line 546, in train_loop
    train_dataset_fn)
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\util\deprecation.py", line 340, in new_func
    return func(*args, **kwargs)
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1143, in experimental_distribute_datasets_from_function
    return self.distribute_datasets_from_function(dataset_fn, options)
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1135, in distribute_datasets_from_function
    dataset_fn, options)
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\distribute\mirrored_strategy.py", line 547, in _distribute_datasets_from_function
    options)
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 162, in get_distributed_datasets_from_function
    input_contexts, strategy, options)
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1273, in __init__
    self._input_contexts, self._input_workers, dataset_fn))
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 1936, in _create_datasets_from_function_with_input_context
    dataset = dataset_fn(ctx)
  File "C:\tensorflow1\models\research\object_detection\model_lib_v2.py", line 541, in train_dataset_fn
    input_context=input_context)
  File "C:\tensorflow1\models\research\object_detection\inputs.py", line 898, in train_input
    reduce_to_frame_fn=reduce_to_frame_fn)
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 210, in build
    decoder = decoder_builder.build(input_reader_config)
  File "C:\tensorflow1\models\research\object_detection\builders\decoder_builder.py", line 64, in build
    load_keypoint_depth_features=input_reader_config
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 416, in __init__
    default_value=''),
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 89, in __init__
    label_map_proto_file, use_display_name=False)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 201, in get_label_map_dict
    label_map = load_labelmap(label_map_path_or_proto)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 168, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "C:\Users\capta\.conda\envs\tf24\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:/tensorflow1/models/research/object_detection/training/label_map.pbtxt : The system cannot find the file specified.
; No such file or directory

I believe I have set my path correctly in the config file and formatted my labelmap.pbtxt correctly.

**Comment by CaptainOrigami** [comment]
I found the issue, my label_map.pbtxt was a .txt or text document, not a .pbtxt.
