### ISSUE TITLE
Message type "object_detection.protos.CenterNet" has no field named "deepmac_mask_estimation".

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/models#9942]
I was trying to use deepMAC on my custom dataset using the following config:

```
# DeepMAC meta architecture from the "The surprising impact of mask-head
# architecture on novel class segmentation" [1] paper with an Hourglass-100[2]
# mask head. This config is trained on all COCO classes and achieves a
# mask mAP of 39.4% on the COCO testdev-2017 set.
# [1]: https://arxiv.org/abs/2104.00613
# [2]: https://arxiv.org/abs/1904.07850

# Train on TPU-128

model {
  center_net {
    num_classes: 6
    feature_extractor {
      type: "hourglass_104"
      bgr_ordering: true
      channel_means: [104.01362025, 114.03422265, 119.9165958 ]
      channel_stds: [73.6027665 , 69.89082075, 70.9150767 ]
    }
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 1024
        max_dimension: 1024
        pad_to_max_dimension: true
      }
    }
    object_detection_task {
      task_loss_weight: 1.0
      offset_loss_weight: 1.0
      scale_loss_weight: 0.1
      localization_loss {
        l1_localization_loss {
        }
      }
    }
    object_center_params {
      object_center_loss_weight: 1.0
      min_box_overlap_iou: 0.7
      max_box_predictions: 2000
      classification_loss {
        penalty_reduced_logistic_focal_loss {
          alpha: 2.0
          beta: 4.0
        }
      }
    }

    deepmac_mask_estimation {
      dim: 32
      task_loss_weight: 5.0
      pixel_embedding_dim: 16
      mask_size: 32
      use_xy: true
      use_instance_embedding: true
      network_type: "hourglass100"
      classification_loss {
        weighted_sigmoid {}
      }
    }
  }
}

train_config: {

  batch_size: 1
  num_steps: 50000

  data_augmentation_options {
    random_horizontal_flip {
    }
  }

  data_augmentation_options {
    random_adjust_hue {
    }
  }

  data_augmentation_options {
    random_adjust_contrast {
    }
  }

  data_augmentation_options {
    random_adjust_saturation {
    }
  }

  data_augmentation_options {
    random_adjust_brightness {
    }
  }

   data_augmentation_options {
     random_square_crop_by_scale {
      scale_min: 0.6
      scale_max: 1.3
    }
  }

  optimizer {
    adam_optimizer: {
      epsilon: 1e-7  # Match tf.keras.optimizers.Adam's default.
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: 1e-3
          total_steps: 50000
          warmup_learning_rate: 2.5e-4
          warmup_steps: 5000
        }
      }
    }
    use_moving_average: false
  }
  max_number_of_boxes: 2000
  unpad_groundtruth_tensors: false

  fine_tune_checkpoint_version: V2
  fine_tune_checkpoint: "/home/deploy/ved/deepmac_1024x1024_coco17/checkpoint/ckpt-0"
  fine_tune_checkpoint_type: "fine_tune"
}

train_input_reader: {
  load_instance_masks: true
  label_map_path: "/home/deploy/ved/label_map_rice_l1.txt"
  mask_type: PNG_MASKS
  tf_record_input_reader {
    input_path: "/home/deploy/ved/rice_l1.record"
  }
}

eval_config: {
  metrics_set: "coco_detection_metrics"
  metrics_set: "coco_mask_metrics"
  include_metrics_per_category: true
  use_moving_averages: false
  batch_size: 1;
}

eval_input_reader: {
  load_instance_masks: true
  mask_type: PNG_MASKS
  label_map_path: "/home/deploy/ved/label_map_rice_l1.txt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "/home/deploy/ved/rice_l1_val.record"
  }
}
```
But it's throwing me following error:
```
Traceback (most recent call last):
  File "/home/deploy/models/research/object_detection/model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/deploy/models/research/object_detection/model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/home/deploy/models/research/object_detection/model_lib_v2.py", line 488, in train_loop
    pipeline_config_path, config_override=config_override)
  File "/home/deploy/models/research/object_detection/utils/config_util.py", line 139, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 737, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 805, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 830, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 852, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 982, in _MergeField
    merger(tokenizer, message, field)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1057, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 982, in _MergeField
    merger(tokenizer, message, field)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1057, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/text_format.py", line 949, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 47:5 : Message type "object_detection.protos.CenterNet" has no field named "deepmac_mask_estimation".
```
I also check [center_net.proto](https://github.com/tensorflow/models/blob/master/research/object_detection/protos/center_net.proto) but there is no `deepmac_mask_estimation` in it.

**Comment by vighneshbirodkar** [comment]
Thanks for pointing this out. It looks like we didn't update this file during the release. The fix should be in by Monday.

**Comment by vighneshbirodkar** [comment]
Fixed with this commit
https://github.com/tensorflow/models/commit/cadd143ab19c4de603dd937e1c7a90f889213039
