### ISSUE TITLE
KeyError: 2 in SpineNet-49 based Mask R-CNN

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/models#9948]
In the README file, in section `Train a SpineNet-49 based Mask R-CNN`, `params_override` is wrongly written. You are missing `train: {` before `train_file_pattern`. Also, in `model_id` 49 should be single quotes. 

After doing this, when I try to train the model using following command:
```
MODEL_DIR="/home/deploy/ved/maskrcnn_SpineNet-49"
TRAIN_FILE_PATTERN="/home/deploy/ved/rice_l1.record"
EVAL_FILE_PATTERN="/home/deploy/ved/rice_l1_val.record"
python3 ~/models/official/vision/detection/main.py \
  --strategy_type=mirrored \
  --num_gpus=2 \
  --model_dir="${MODEL_DIR?}" \
  --mode=train \
  --model=mask_rcnn \
  --params_override="{architecture: {backbone: spinenet, multilevel_features: identity}, spinenet: {model_id: '49'}, train: {train_file_pattern: ${TRAIN_FILE_PATTERN?} }, eval: { use_json_file: False, eval_file_pattern: ${EVAL_FILE_PATTERN?} } }"
```
I'm getting errror:
```
Traceback (most recent call last):
  File "/home/deploy/models/official/vision/detection/main.py", line 263, in <module>
    app.run(main)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/deploy/models/official/vision/detection/main.py", line 258, in main
    run()
  File "/home/deploy/models/official/vision/detection/main.py", line 252, in run
    callbacks=callbacks)
  File "/home/deploy/models/official/vision/detection/main.py", line 124, in run_executor
    save_config=True)
  File "/home/deploy/models/official/vision/detection/executor/distributed_executor.py", line 420, in train
    model = self.model_fn(params.as_dict())
  File "/home/deploy/models/official/vision/detection/executor/distributed_executor.py", line 176, in model_fn
    return self._model_fn(params)
  File "/home/deploy/models/official/vision/detection/main.py", line 96, in _model_fn
    return model_builder.build_model(params, mode=ModeKeys.TRAIN)
  File "/home/deploy/models/official/vision/detection/modeling/maskrcnn_model.py", line 295, in build_model
    outputs = self.model_outputs(input_layers, mode)
  File "/home/deploy/models/official/vision/detection/modeling/base_model.py", line 102, in model_outputs
    return self.build_outputs(inputs, mode)
  File "/home/deploy/models/official/vision/detection/modeling/maskrcnn_model.py", line 86, in build_outputs
    fpn_features, is_training)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.pyct.error_utils.KeyError: in user code:

    /home/deploy/models/official/vision/detection/modeling/architecture/heads.py:133 call  *
        scores_output, box_output = self._shared_rpn_heads(

    KeyError: 2
```

**Comment by xianzhidu** [comment]
SpineNet only support feature level 3 to 7 for detection. Can you set the `min_level` and `max_level` to numbers in range [3, 7] for Mask RCNN?

**Comment by anshkumar** [comment]
After setting `min_level: 3` and `max_level:7`, I'm getting following error:
```
WARNING:tensorflow:Model was constructed with shape (None, 640, 640, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, 640, 640, 3), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'"), but it was called on an input with incompatible shape (1, 1024, 1024, 3).
W0429 06:13:59.664381 140061237630784 functional.py:635] Model was constructed with shape (None, 640, 640, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, 640, 640, 3), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'"), but it was called on an input with incompatible shape (1, 1024, 1024, 3).
Traceback (most recent call last):
  File "/home/deploy/models/official/vision/detection/main.py", line 263, in <module>
    app.run(main)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/deploy/models/official/vision/detection/main.py", line 258, in main
    run()
  File "/home/deploy/models/official/vision/detection/main.py", line 252, in run
    callbacks=callbacks)
  File "/home/deploy/models/official/vision/detection/main.py", line 124, in run_executor
    save_config=True)
  File "/home/deploy/models/official/vision/detection/executor/distributed_executor.py", line 420, in train
    model = self.model_fn(params.as_dict())
  File "/home/deploy/models/official/vision/detection/executor/distributed_executor.py", line 176, in model_fn
    return self._model_fn(params)
  File "/home/deploy/models/official/vision/detection/main.py", line 96, in _model_fn
    return model_builder.build_model(params, mode=ModeKeys.TRAIN)
  File "/home/deploy/models/official/vision/detection/modeling/maskrcnn_model.py", line 295, in build_model
    outputs = self.model_outputs(input_layers, mode)
  File "/home/deploy/models/official/vision/detection/modeling/base_model.py", line 102, in model_outputs
    return self.build_outputs(inputs, mode)
  File "/home/deploy/models/official/vision/detection/modeling/maskrcnn_model.py", line 144, in build_outputs
    box_outputs, class_outputs, rpn_rois, inputs['image_info'][:, 1:2, :])
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 970, in __call__
    input_list)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1108, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 840, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 880, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/deploy/models/official/vision/detection/ops/postprocess_ops.py:405 call  *
        nmsed_boxes, nmsed_scores, nmsed_classes, valid_detections = (
    /home/deploy/models/official/vision/detection/ops/postprocess_ops.py:136 _generate_detections  *
        (nmsed_scores_i, nmsed_boxes_i) = nms.sorted_non_max_suppression_padded(
    /home/deploy/models/official/vision/detection/ops/nms.py:181 sorted_non_max_suppression_padded  *
        idx = num_boxes - tf.cast(
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py:5297 top_k
        return gen_nn_ops.top_kv2(input, k=k, sorted=sorted, name=name)
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py:11438 top_kv2
        "TopKV2", input=input, k=k, sorted=sorted, name=name)
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:601 _create_op_internal
        compute_device)
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3565 _create_op_internal
        op_def=op_def)
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:2042 __init__
        control_input_ops, op_def)
    /home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: input must have last dimension >= k = 2000 but is 512 for '{{node generic_detection_generator/generate_detections/TopKV2_1}} = TopKV2[T=DT_INT32, sorted=true](generic_detection_generator/generate_detections/mul_1, generic_detection_generator/generate_detections/TopKV2_1/k)' with input shapes: [1,512], [] and with computed input tensors: input[1] = <2000>.
```

My complete config is as follows:
```
use_tpu: False
train: {
    iterations_per_loop: 100,
    batch_size: 2,
    total_steps: 22500,
    num_cores_per_replica: None,
    input_partition_dims: None,
    optimizer: {
        type: momentum,
        momentum: 0.9,
        nesterov: True,  # `False` is better for TPU v3-128.
    },
    learning_rate: {
        type: step,
        warmup_learning_rate: 0.0067,
        warmup_steps: 500,
        init_learning_rate: 0.08,
        learning_rate_levels: [0.008, 0.0008],
        learning_rate_steps: [15000, 20000],
    },
    checkpoint: {
        path: '',
        prefix: '',
    },
    # One can use RESNET_FROZEN_VAR_PREFIX to speed up ResNet training
    # when loading from the checkpoint.
    frozen_variable_prefix: '',
    train_file_pattern: "/home/deploy/ved/rice_l1.record",
    train_dataset_type: tfrecord,
    # TODO(b/142174042): Support transpose_input option.
    transpose_input: False,
    regularization_variable_regex: REGULARIZATION_VAR_REGEX,
    l2_weight_decay: 0.0001,
    gradient_clip_norm: 0.0,
    input_sharding: False,
}
eval: {
    input_sharding: True,
    batch_size: 2,
    eval_samples: 5000,
    min_eval_interval: 180,
    eval_timeout: None,
    num_steps_per_eval: 1000,
    type: box_and_mask,
    use_json_file: False,
    # val_json_file: ,
    eval_file_pattern: "/home/deploy/ved/rice_l1_val.record",
    eval_dataset_type: tfrecord,
    # When visualizing images, set evaluation batch size to 40 to avoid
    # potential OOM.
    num_images_to_visualize: 0,
}
predict: {
    batch_size: 2,
}
architecture: {
    backbone: spinenet,
    multilevel_features: identity,
    use_bfloat16: False,
    # Note that `num_classes` is the total number of classes including
    # one background classes whose index is 0.
    num_classes: 7,
    include_mask: True,
    mask_target_size: 28,
    parser: maskrcnn_parser,
    min_level: 3,
    max_level: 7
}
anchor: {
    num_scales: 3,
    aspect_ratios: [1.0, 2.0, 0.5],
    anchor_size: 4.0,
}
norm_activation: {
    activation: relu,
    batch_norm_momentum: 0.997,
    batch_norm_epsilon: 1e-4,
    batch_norm_trainable: True,
    use_sync_bn: False,
}
spinenet: {
    model_id: '49'
}
mask_sampling: {
  num_mask_samples_per_image: 128,  # Typically = `num_samples_per_image` * `fg_fraction`.
}
maskrcnn_parser: {
  aug_rand_hflip: True,
  aug_scale_max: 1.0,
  aug_scale_min: 1.0,
  mask_crop_size: 112,
  max_num_instances: 100,   
  num_channels: 3,
  output_size: [1024, 1024],
  rpn_batch_size_per_im: 256,
  rpn_fg_fraction: 0.5,
  rpn_match_threshold: 0.7, 
  rpn_unmatched_threshold: 0.3,
  skip_crowd_during_training: True
}

postprocess: {
    use_batched_nms: False,
    max_total_size: 2000,
    nms_iou_threshold: 0.5,
    score_threshold: 0.05,
    pre_nms_num_boxes: 5000,
}
enable_summary: False
```

**Comment by MUzairS15** [comment]
Hey, can i work on this??

**Comment by xianzhidu** [comment]
Hi, please try min_level and max_level in range [3, 7] for SpineNet models. min_level 2 is generally very expensive so not included in the architecture design.

**Comment by wathek** [comment]
@xianzhidu a quick question do you know where I can get the right checkpoint for maskrcnn-spinenet49 ? thank you

**Comment by xianzhidu** [comment]
@wathek We stopped maintain this codebase anymore. Please check the [new codebase](https://github.com/tensorflow/models/blob/master/official/vision/beta/) out, we have supported more models and checkpoints [there](https://github.com/tensorflow/models/blob/master/official/vision/beta/MODEL_GARDEN.md).

**Comment by wathek** [comment]
@xianzhidu ok thank you so much

**Comment by anshkumar** [comment]
@xianzhidu The link does not contains checkpoints.

**Comment by laxmareddyp** [comment]
Hi @anshkumar ,

Is still facing an issue here ?

Thanks
