### ISSUE TITLE
deepmac_maskrcnn ValueError: Missing the required key `masks` in groundtruths!

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/models#9957]
I was trying to use [DeepMac](https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/deepmac_maskrcnn) in the beta directory. During training I'm getting following error:
```
Traceback (most recent call last):
  File "/home/deploy/models/official/vision/beta/projects/deepmac_maskrcnn/train.py", line 72, in <module>
    app.run(main)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/deploy/models/official/vision/beta/projects/deepmac_maskrcnn/train.py", line 66, in main
    model_dir=model_dir)
  File "/home/deploy/models/official/core/train_lib.py", line 110, in run_experiment
    eval_interval=params.trainer.validation_interval)
  File "/home/deploy/models/orbit/controller.py", line 304, in train_and_evaluate
    self.evaluate(steps=eval_steps)
  File "/home/deploy/models/orbit/controller.py", line 257, in evaluate
    eval_output = self.evaluator.evaluate(steps_tensor)
  File "/home/deploy/models/orbit/standard_runner.py", line 340, in evaluate
    eval_iter, num_steps, state=outputs, reduce_fn=self.eval_reduce)
  File "/home/deploy/models/orbit/utils/loop_fns.py", line 76, in loop_fn
    state = reduce_fn(state, outputs)
  File "/home/deploy/models/official/core/base_trainer.py", line 453, in eval_reduce
    return self.task.aggregate_logs(state, step_outputs)
  File "/home/deploy/models/official/vision/beta/tasks/maskrcnn.py", line 353, in aggregate_logs
    step_outputs[self.coco_metric.name][1])
  File "/home/deploy/models/official/vision/beta/evaluation/coco_evaluator.py", line 331, in update_state
    'Missing the required key `{}` in groundtruths!'.format(k))
ValueError: Missing the required key `masks` in groundtruths!
```

I'm using a custom dataset, so I'm passing mask in the tf-record itself. For `ANNOTAION_FILE`, I'm passing empty string. Is this error coming because of not passing `ANNOTAION_FILE` ? If yes, is there any work around other then creating it ? (Beacuse mask is already in the record file)

**Comment by vighneshbirodkar** [comment]
The error is due to no annotation file. It is currently not supported to evaluate instance segmentation without it. @arashwan can comment if this would be a feature supported in the future.

**Comment by arashwan** [comment]
Right now, we only evaluate predictions for maskrcnn using annotation file. However, you can try to modify maskrcnn_input to return masks in the groundtruths (https://github.com/tensorflow/models/blob/master/official/vision/beta/dataloaders/maskrcnn_input.py#L330). Feel free to send us a PR if you successfully test that feature.
