### ISSUE TITLE
TF-slim training crashed 

### ISSUE THREAD

**Issue by rickymf4** [tensorflow/models#997]
## Tensorflow 0.10.0rc0 

I use slim/train_image_classifier.py to train a inception_v1 model on my own dataset, 
`
python train_image_classifier.py 
    --train_dir=${TRAIN_DIR} 
    --dataset_name=mydataset 
    --dataset_split_name=train 
    --dataset_dir=${DATASET_DIR} 
    --model_name=inception_v1
    --num_clones=2
`

but it crashed, the following are the last output:

INFO:tensorflow:global step 47590: loss = 0.3513 (0.39 sec/step)
Corrupt JPEG data: 1 extraneous bytes before marker 0xd9
INFO:tensorflow:global step 47600: loss = 0.3669 (0.39 sec/step)
INFO:tensorflow:global step 47610: loss = 0.4119 (0.39 sec/step)
INFO:tensorflow:global step 47620: loss = 0.3987 (0.84 sec/step)
INFO:tensorflow:global step 47630: loss = 0.3887 (0.39 sec/step)
Corrupt JPEG data: premature end of data segment
Unsupported marker type 0x44
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors.InvalidArgumentError'>, Invalid JPEG data, size 82243
	 [[Node: case/If_0/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](case/If_0/DecodeJpeg/Switch:1, ^case/Assert/AssertGuard/Merge)]]
Caused by op u'case/If_0/DecodeJpeg', defined at:
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 442, in main
    common_queue_min=10 * FLAGS.batch_size)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/dataset_data_provider.py", line 78, in __init__
    tensors = dataset.decoder.decode(data, items)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 398, in decode
    outputs.append(handler.tensors_to_item(keys_to_tensors))
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 297, in tensors_to_item
    image = self._decode(image_buffer, image_format)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 324, in _decode
    }, default=decode_jpg, exclusive=True)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2888, in case
    case_seq = _build_case()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2870, in _build_case
    name="If_%d" % i)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1712, in cond
    orig_res, res_t = context_t.BuildCondBranch(fn1)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1615, in BuildCondBranch
    r = fn()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 317, in decode_jpg
    return image_ops.decode_jpeg(image_buffer, self._channels)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 283, in decode_jpeg
    name=name)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2372, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 581, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 780, in train
    raise
  File "/home/maofeng.mf/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 969, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 797, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/queue_runner.py", line 225, in _run
    sess.run(enqueue_op)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Invalid JPEG data, size 82243
	 [[Node: case/If_0/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](case/If_0/DecodeJpeg/Switch:1, ^case/Assert/AssertGuard/Merge)]]
Caused by op u'case/If_0/DecodeJpeg', defined at:
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 442, in main
    common_queue_min=10 * FLAGS.batch_size)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/dataset_data_provider.py", line 78, in __init__
    tensors = dataset.decoder.decode(data, items)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 398, in decode
    outputs.append(handler.tensors_to_item(keys_to_tensors))
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 297, in tensors_to_item
    image = self._decode(image_buffer, image_format)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 324, in _decode
    }, default=decode_jpg, exclusive=True)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2888, in case
    case_seq = _build_case()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2870, in _build_case
    name="If_%d" % i)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1712, in cond
    orig_res, res_t = context_t.BuildCondBranch(fn1)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1615, in BuildCondBranch
    r = fn()
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/data/tfexample_decoder.py", line 317, in decode_jpg
    return image_ops.decode_jpeg(image_buffer, self._channels)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 283, in decode_jpeg
    name=name)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2372, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/maofeng.mf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

`

**Comment by girving** [comment]
Presumably your dataset contains a PNG, and you are trying to read it as a JPEG.  I recommend switching from `decode_jpeg` to `decode_image`; the latter handles both formats.

**Comment by rickymf4** [comment]
Thanks girving. But it was not due to a PNG image, it was due to a Corrupt JPEG. 
How can I skip such bad data to continue training?

**Comment by indra215** [comment]
@girving where should I do the change from `decode_jpeg` to `decode_image` while using the slim `train_image_classifier.py`.

**Comment by girving** [comment]
I made recent versions of `decode_jpeg` silently handle PNGs, so upgrading TensorFlow may suffice.

**Comment by aalibasic** [comment]
@rickymf4 - did you find a way to skip over the corrupt jpeg?
