### ISSUE TITLE
DeepMac mask validation using tfrecord

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/models#9980]
I've done some changes to utilize mask directly from the record file while validation instead of using a coco json file.

[maskrcnn_input.py](https://github.com/tensorflow/models/blob/238922e98dd0e8254b5c0921b241a1f5a151782f/official/vision/beta/dataloaders/maskrcnn_input.py#L339)
```
    if self._include_mask:
      groundtruths['masks'] = data['groundtruth_instance_masks']
    groundtruths['source_id'] = utils.process_source_id(
        groundtruths['source_id'])
    groundtruths = utils.pad_groundtruths_to_fixed_size(
        groundtruths, self._max_num_instances, self._include_mask)
```

[utils.py](https://github.com/tensorflow/models/blob/238922e98dd0e8254b5c0921b241a1f5a151782f/official/vision/beta/dataloaders/utils.py#L43)
```
def pad_groundtruths_to_fixed_size(groundtruths: Dict[str, tf.Tensor],
                                   size: int,
                                   include_mask=False) -> Dict[str, tf.Tensor,]:
  """Pads the first dimension of groundtruths labels to the fixed size.

  Args:
    groundtruths: A dictionary of {`str`: `tf.Tensor`} that contains groundtruth
      annotations of `boxes`, `is_crowds`, `areas` and `classes`.
    size: An `int` that specifies the expected size of the first dimension of
      padded tensors.

  Returns:
    A dictionary of the same keys as input and padded tensors as values.

  """
  groundtruths['boxes'] = preprocess_ops.clip_or_pad_to_fixed_size(
      groundtruths['boxes'], size, -1)
  groundtruths['is_crowds'] = preprocess_ops.clip_or_pad_to_fixed_size(
      groundtruths['is_crowds'], size, 0)
  groundtruths['areas'] = preprocess_ops.clip_or_pad_to_fixed_size(
      groundtruths['areas'], size, -1)
  groundtruths['classes'] = preprocess_ops.clip_or_pad_to_fixed_size(
      groundtruths['classes'], size, -1)
  if include_mask:
    groundtruths['masks'] = preprocess_ops.clip_or_pad_to_fixed_size(
      groundtruths['masks'], size, -1)
  return groundtruths
```

[coco_utils.py](https://github.com/tensorflow/models/blob/238922e98dd0e8254b5c0921b241a1f5a151782f/official/vision/beta/evaluation/coco_utils.py#L242)
```
        if 'masks' in groundtruths:
          if isinstance(groundtruths['masks'][i][j, k], bytes):
            mask = Image.open(six.BytesIO(groundtruths['masks'][i][j, k]))
            width, height = mask.size
            np_mask = (
                np.array(mask.getdata()).reshape(height, width).astype(np.uint8))
          else:
            np_mask = groundtruths['masks'][i][j, k].astype(np.uint8)
```

Things work when running the training on a single GPU, but I try to use multiple GPUs, I'm getting following error:
```
I0507 12:42:38.541230 140698041124672 controller.py:252]  eval | step:  100001 | running 10 steps of evaluation...
 eval | step:  100001 | running 10 steps of evaluation...
Traceback (most recent call last):
  File "/home/deploy/models/official/vision/beta/projects/deepmac_maskrcnn/train.py", line 72, in <module>
    app.run(main)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/deploy/models/official/vision/beta/projects/deepmac_maskrcnn/train.py", line 66, in main
    model_dir=model_dir)
  File "/home/deploy/models/official/core/train_lib.py", line 110, in run_experiment
    eval_interval=params.trainer.validation_interval)
  File "/home/deploy/models/orbit/controller.py", line 304, in train_and_evaluate
    self.evaluate(steps=eval_steps)
  File "/home/deploy/models/orbit/controller.py", line 257, in evaluate
    eval_output = self.evaluator.evaluate(steps_tensor)
  File "/home/deploy/models/orbit/standard_runner.py", line 340, in evaluate
    eval_iter, num_steps, state=outputs, reduce_fn=self.eval_reduce)
  File "/home/deploy/models/orbit/utils/loop_fns.py", line 74, in loop_fn
    outputs = step_fn(iterator)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 924, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/deploy/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Shapes of all inputs must match: values[0].shape = [3,512] != values[1].shape = [0,512]
	 [[node replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/stack (defined at home/deploy/models/official/vision/beta/ops/box_ops.py:473) ]]
  (1) Invalid argument:  Shapes of all inputs must match: values[0].shape = [3,512] != values[1].shape = [0,512]
	 [[node replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/stack (defined at home/deploy/models/official/vision/beta/ops/box_ops.py:473) ]]
	 [[replica_1/deep_mask_rcnn_model/add/_760]]
0 successful operations.
0 derived errors ignored. [Op:__inference_eval_step_340270]

Errors may have originated from an input operation.
Input Source operations connected to node replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/stack:
 replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/mul (defined at home/deploy/models/official/vision/beta/ops/box_ops.py:470)	
 replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/TopKV2 (defined at home/deploy/models/official/vision/beta/ops/box_ops.py:502)

Input Source operations connected to node replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/stack:
 replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/mul (defined at home/deploy/models/official/vision/beta/ops/box_ops.py:470)	
 replica_1/deep_mask_rcnn_model/multilevel_roi_generator/multilevel_propose_rois/level_7/top_k_boxes/TopKV2 (defined at home/deploy/models/official/vision/beta/ops/box_ops.py:502)

Function call stack:
eval_step -> eval_step
```
I don't understand why it's throwing error from `multilevel_roi_generator`? 
Things works perfectly without the above changes. In config I'm passing empty string to `annotation_file`.

**Comment by anshkumar** [comment]
Making training and evaluation batch size same, made it worked. Created a [PR](https://github.com/tensorflow/models/pull/9987).
